"""
Preprocessing Wrapper Script for T017d.

Executes the preprocessing pipeline on the first available subject from the downloaded
OpenNeuro dataset (ds000224) to generate `data/processed/preprocessing_stats.json`.

This script respects the N=10 limit and real data constraints defined in the amendment.
It does NOT use mock data unless explicitly invoked with --mock-input for unit testing.
"""
import os
import sys
import json
import argparse
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add project root to path if not already there
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "code"))

from preprocess import preprocess_subject, load_motion_exclusion_log
from config import get_sample_limit
from utils import ResourceMonitor

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_subject_list_from_download_log(download_log_path: Path) -> List[Dict[str, Any]]:
    """
    Reads the subject list from the download log generated by T015b.
    This ensures we only process subjects that were actually downloaded and validated.
    """
    if not download_log_path.exists():
        logger.error(f"Download log not found at {download_log_path}. Run T015b first.")
        return []

    try:
        with open(download_log_path, 'r') as f:
            data = json.load(f)
            # The download log structure from T015b typically has 'subjects' key
            subjects = data.get('subjects', [])
            if not subjects:
                logger.warning("No subjects found in download log.")
            return subjects
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse download log: {e}")
        return []

def run_preprocessing_wrapper(
    input_dir: Path,
    output_dir: Path,
    atlas_dir: Path,
    sample_size: int = 1,
    mock_input: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Iterates over valid subjects and calls preprocess_subject().
    Writes the aggregated stats to data/processed/preprocessing_stats.json.

    Args:
        input_dir: Path to raw data (data/raw)
        output_dir: Path to interim/processed data (data/interim)
        atlas_dir: Path to atlas files
        sample_size: Number of subjects to process (default 1 for T017d verification)
        mock_input: Optional path to mock subjects file for testing

    Returns:
        Dictionary containing processing statistics.
    """
    stats = {
        "total_subjects": 0,
        "processed_successfully": 0,
        "failed": 0,
        "subjects": []
    }

    # Determine subject list source
    subject_list = []
    if mock_input and mock_input.exists():
        logger.warning("Using mock input for verification. This flag is for testing only.")
        with open(mock_input, 'r') as f:
            mock_data = json.load(f)
            subject_list = mock_data.get('subjects', [])
    else:
        # Prefer the download log from T015b
        download_log = input_dir.parent / "download_log.json" # Assuming standard location
        if not download_log.exists():
            # Fallback check: look in data/raw if log is elsewhere
            download_log = Path("data/download_log.json")
        
        if download_log.exists():
            subject_list = load_subject_list_from_download_log(download_log)
        else:
            # Fallback: scan raw directory if log is missing (less reliable for metadata)
            logger.warning("Download log not found. Scanning raw directory for subjects.")
            subject_list = [] # Simplified for this task; real implementation would scan BIDS
            # For T017d, we rely on the download log being present from T015b

    if not subject_list:
        logger.error("No subjects found to process. Ensure T015b has run successfully.")
        return stats

    # Apply sample size limit (N=10 baseline, but T017d asks for first available)
    if sample_size > 0:
        subject_list = subject_list[:sample_size]

    stats["total_subjects"] = len(subject_list)

    # Initialize Resource Monitor
    rm = ResourceMonitor()
    rm.start()

    for i, subject in enumerate(subject_list):
        subject_id = subject.get('id')
        if not subject_id:
            logger.warning(f"Subject {i} missing 'id', skipping.")
            continue

        logger.info(f"Processing subject {i+1}/{len(subject_list)}: {subject_id}")

        try:
            # Call the core preprocessing function
            # Assumes preprocess_subject handles the FSL/AFNI calls
            result = preprocess_subject(
                subject_id=subject_id,
                input_dir=input_dir,
                output_dir=output_dir,
                atlas_dir=atlas_dir
            )

            if result.get('success'):
                stats["processed_successfully"] += 1
                stats["subjects"].append({
                    "id": subject_id,
                    "status": "success",
                    "details": result
                })
            else:
                stats["failed"] += 1
                stats["subjects"].append({
                    "id": subject_id,
                    "status": "failed",
                    "error": result.get('error', 'Unknown error')
                })
                logger.error(f"Failed to process {subject_id}: {result.get('error')}")

        except Exception as e:
            stats["failed"] += 1
            stats["subjects"].append({
                "id": subject_id,
                "status": "failed",
                "error": str(e)
            })
            logger.exception(f"Exception processing {subject_id}: {e}")

    rm.stop()
    rm.finalize() # This writes data/processed/resource_profile.json

    # Write the stats file required by T017d
    output_stats_path = output_dir / "preprocessing_stats.json"
    with open(output_stats_path, 'w') as f:
        json.dump(stats, f, indent=2)

    logger.info(f"Preprocessing stats written to {output_stats_path}")
    return stats

def main():
    parser = argparse.ArgumentParser(description="Run preprocessing pipeline on subjects.")
    parser.add_argument(
        "--input",
        type=str,
        default="data/raw",
        help="Path to raw data directory"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/interim",
        help="Path to output directory"
    )
    parser.add_argument(
        "--atlas",
        type=str,
        default="data/external",
        help="Path to atlas directory"
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=1,
        help="Number of subjects to process (default 1 for T017d)"
    )
    parser.add_argument(
        "--mock-input",
        type=str,
        default=None,
        help="Path to mock subjects JSON for testing"
    )

    args = parser.parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)
    atlas_dir = Path(args.atlas)
    mock_path = Path(args.mock_input) if args.mock_input else None

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # Run the wrapper
    stats = run_preprocessing_wrapper(
        input_dir=input_dir,
        output_dir=output_dir,
        atlas_dir=atlas_dir,
        sample_size=args.sample_size,
        mock_input=mock_path
    )

    # Verify output exists for T017d verification
    stats_file = output_dir / "preprocessing_stats.json"
    if stats_file.exists():
        print(f"SUCCESS: Preprocessing stats generated at {stats_file}")
        sys.exit(0)
    else:
        print(f"ERROR: Preprocessing stats file not found at {stats_file}")
        sys.exit(1)

if __name__ == "__main__":
    main()
