"""
Contract tests for data ingestion schema.

Validates that the Pantheon+ dataset structure matches the expected
SupernovaRecord Pydantic model defined in src/models/.
"""
import pandas as pd
import pytest
from pathlib import Path
from pydantic import ValidationError

# Import the model defined in T010
from src.models import SupernovaRecord

# Import config to get project paths
from src.utils.config import get_project_paths

# Import logger for potential audit (optional but good practice)
from src.utils.logger import get_logger

logger = get_logger(__name__)

# Define the expected raw data file path based on T014/T015 context
# Note: In a real CI run, this file might not exist yet if T014 hasn't run,
# but the contract test validates the *schema* of the file if it exists.
# We will check against the expected location.
PROJECT_ROOT = get_project_paths()
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "pantheon_plus.csv"

def test_loader_schema_matches_pantheon_plus():
    """
    Contract test: Validate that the Pantheon+ CSV schema matches the SupernovaRecord model.
    
    This test ensures that:
    1. The raw data file exists (or skips if not yet generated by T014).
    2. All columns in the CSV can be mapped to fields in the SupernovaRecord model.
    3. A sample of rows can be successfully parsed into the model without ValidationError.
    
    Raises:
        AssertionError: If schema mismatch or validation failure occurs.
        FileNotFoundError: If the expected raw data file is missing (indicates T014 failure).
    """
    if not RAW_DATA_PATH.exists():
        pytest.fail(
            f"Raw data file not found at {RAW_DATA_PATH}. "
            "Ensure Task T014 (fetch Pantheon+ dataset) has been completed first."
        )
    
    try:
        # Load a sample of the raw data to validate schema
        # Reading only the header and first 100 rows for efficiency
        df = pd.read_csv(RAW_DATA_PATH, nrows=100)
        logger.info(f"Loaded sample of {len(df)} rows from {RAW_DATA_PATH}")
    except Exception as e:
        pytest.fail(f"Failed to read CSV file: {e}")
    
    # Get the expected field names from the Pydantic model
    expected_fields = set(SupernovaRecord.model_fields.keys())
    actual_columns = set(df.columns)
    
    logger.info(f"Expected fields from model: {expected_fields}")
    logger.info(f"Actual columns in CSV: {actual_columns}")
    
    # Check for missing columns (columns in model but not in CSV)
    missing_columns = expected_fields - actual_columns
    if missing_columns:
        pytest.fail(
            f"Schema mismatch: The following fields defined in SupernovaRecord are missing "
            f"in the CSV: {missing_columns}"
        )
    
    # Check for extra columns (optional: strict mode might require this, but usually we ignore extras)
    # For a robust loader, we often ignore extra columns, but we log them.
    extra_columns = actual_columns - expected_fields
    if extra_columns:
        logger.warning(f"Extra columns found in CSV not in model: {extra_columns}")
    
    # Attempt to validate a sample of rows against the model
    # We iterate through rows to ensure type coercion and validation rules hold
    validation_errors = []
    sample_count = min(50, len(df)) # Validate first 50 rows
    
    for idx, row in df.head(sample_count).iterrows():
        try:
            # Convert row to dict, handling potential NaNs if the model allows Optional
            row_dict = row.to_dict()
            # Pydantic handles NaNs if fields are Optional[float] or similar
            record = SupernovaRecord(**row_dict)
            assert record is not None, "Validation returned None"
        except ValidationError as e:
            validation_errors.append({
                "row_index": idx,
                "error": str(e)
            })
            # Log the first few errors for debugging
            if len(validation_errors) <= 5:
                logger.error(f"Validation error at row {idx}: {e}")
    
    if validation_errors:
        error_summary = validation_errors[0]["error"]
        pytest.fail(
            f"Schema validation failed for {len(validation_errors)} rows. "
            f"First error: {error_summary}"
        )
    
    logger.info(f"Contract test passed: {sample_count} rows validated successfully against SupernovaRecord schema.")