"""
T048: Implement analyze_latency_bias module.

Performs stratified bootstrap with propensity-score matching for latency reduction validation
using independent covariates (frame timestamp and audio energy, excluding estimator prediction).
Outputs: data/metrics/latency_bootstrap_results.csv
"""
import os
import sys
import argparse
import logging
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple, Union
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import csv

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / 'code'))

from config import get_config_summary
from utils.update_state_yaml import update_state_with_artifacts

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_hybrid_output() -> pd.DataFrame:
    """Load the hybrid output parquet file generated by T050."""
    input_path = PROJECT_ROOT / 'data' / 'processed' / 'hybrid_output.parquet'
    if not input_path.exists():
        raise FileNotFoundError(f"Required input file not found: {input_path}. "
                              "Ensure T050 (hybrid_sim) has completed successfully.")
    
    logger.info(f"Loading hybrid output from {input_path}")
    df = pd.read_parquet(input_path)
    logger.info(f"Loaded {len(df)} rows with columns: {list(df.columns)}")
    return df

def load_config_summary() -> Dict[str, Any]:
    """Load configuration summary to determine data source."""
    return get_config_summary()

def propensity_score_matching(df: pd.DataFrame) -> pd.DataFrame:
    """
    Perform propensity score matching using independent covariates.
    
    Covariates: frame timestamp, audio energy (EXCLUDING estimator prediction).
    Treatment: whether frame was skipped (lazy inference) or full solver.
    
    Returns: DataFrame with propensity scores and matched groups.
    """
    logger.info("Performing propensity score matching...")
    
    # Define covariates (independent of estimator prediction)
    covariates = ['timestamp', 'audio_energy']
    
    # Ensure covariates exist
    missing = [col for col in covariates if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required covariates for propensity matching: {missing}")
    
    # Define treatment variable (1 = skipped/lazy, 0 = full solver)
    # Assuming 'inference_mode' or similar column indicates the method used
    treatment_col = None
    for col in ['inference_mode', 'method', 'mode']:
        if col in df.columns:
            treatment_col = col
            break
    
    if treatment_col is None:
        # Create treatment based on latency or a heuristic if explicit column missing
        logger.warning("No explicit inference mode column found. Using latency threshold as proxy.")
        # If latency is high, assume full solver; if low, assume skipped
        # This is a fallback - ideally the hybrid_sim should have logged the mode
        median_latency = df['latency_ms'].median()
        df['_treatment'] = (df['latency_ms'] < median_latency).astype(int)
        treatment_col = '_treatment'
    else:
        # Convert treatment column to binary
        if df[treatment_col].dtype == 'object':
            df['_treatment'] = df[treatment_col].apply(lambda x: 1 if 'skip' in str(x).lower() or 'lazy' in str(x).lower() else 0)
        else:
            df['_treatment'] = df[treatment_col].astype(int)
        treatment_col = '_treatment'
    
    # Prepare features for logistic regression
    X = df[covariates].values
    y = df[treatment_col].values
    
    # Standardize covariates
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # Fit logistic regression to estimate propensity scores
    logger.info("Fitting logistic regression for propensity scores...")
    model = LogisticRegression(max_iter=1000, random_state=42)
    model.fit(X_scaled, y)
    
    # Get propensity scores (probability of being treated/skipped)
    propensity_scores = model.predict_proba(X_scaled)[:, 1]
    df['propensity_score'] = propensity_scores
    
    # Create matched groups (1:1 matching with caliper)
    logger.info("Performing 1:1 matching with caliper...")
    treated = df[df['_treatment'] == 1].copy()
    control = df[df['_treatment'] == 0].copy()
    
    matched_indices = []
    for _, t_row in treated.iterrows():
        # Find closest control with caliper (0.05)
        control_diff = (control['propensity_score'] - t_row['propensity_score']).abs()
        caliper = 0.05
        valid_controls = control[control_diff < caliper]
        
        if len(valid_controls) > 0:
            best_match = valid_controls.loc[valid_controls['propensity_score'].idxmin()]
            matched_indices.append((t_row.name, best_match.name))
    
    logger.info(f"Found {len(matched_indices)} matched pairs")
    df['matched_pair_id'] = -1
    for i, (t_idx, c_idx) in enumerate(matched_indices):
        df.loc[t_idx, 'matched_pair_id'] = i
        df.loc[c_idx, 'matched_pair_id'] = i
    
    # Filter to matched samples only
    matched_df = df[df['matched_pair_id'] != -1].copy()
    matched_df.drop(columns=['_treatment'], inplace=True, errors='ignore')
    
    return matched_df

def stratified_bootstrap(df: pd.DataFrame, n_bootstrap: int = 1000, seed: int = 42) -> pd.DataFrame:
    """
    Perform stratified bootstrap on matched pairs.
    
    Returns: DataFrame with bootstrap statistics.
    """
    logger.info(f"Performing stratified bootstrap with {n_bootstrap} iterations...")
    np.random.seed(seed)
    
    bootstrap_results = []
    
    # Group by matched pairs
    unique_pairs = df['matched_pair_id'].unique()
    
    for i in range(n_bootstrap):
        # Sample pairs with replacement
        sampled_pairs = np.random.choice(unique_pairs, size=len(unique_pairs), replace=True)
        sampled_df = df[df['matched_pair_id'].isin(sampled_pairs)]
        
        # Calculate latency reduction for this bootstrap sample
        # Latency reduction = (control_latency - treated_latency) / control_latency
        # Higher is better (more reduction)
        
        treated_latencies = sampled_df[sampled_df['inference_mode'] == 'skipped']['latency_ms']
        control_latencies = sampled_df[sampled_df['inference_mode'] == 'full_solver']['latency_ms']
        
        if len(treated_latencies) == 0 or len(control_latencies) == 0:
            continue
        
        mean_treated = treated_latencies.mean()
        mean_control = control_latencies.mean()
        
        if mean_control > 0:
            reduction_pct = ((mean_control - mean_treated) / mean_control) * 100
            bootstrap_results.append(reduction_pct)
    
    if not bootstrap_results:
        raise RuntimeError("Bootstrap failed: no valid samples computed.")
    
    results_df = pd.DataFrame({
        'iteration': range(len(bootstrap_results)),
        'latency_reduction_pct': bootstrap_results
    })
    
    return results_df

def run_latency_bias_analysis(hybrid_df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Run the full latency bias analysis pipeline.
    
    1. Propensity score matching
    2. Stratified bootstrap
    3. Compute final statistics
    """
    logger.info("Starting latency bias analysis...")
    
    # Step 1: Propensity Score Matching
    matched_df = propensity_score_matching(hybrid_df)
    
    # Step 2: Stratified Bootstrap
    bootstrap_df = stratified_bootstrap(matched_df)
    
    # Step 3: Compute final statistics
    mean_reduction = bootstrap_df['latency_reduction_pct'].mean()
    std_reduction = bootstrap_df['latency_reduction_pct'].std()
    ci_lower = np.percentile(bootstrap_df['latency_reduction_pct'], 2.5)
    ci_upper = np.percentile(bootstrap_df['latency_reduction_pct'], 97.5)
    
    logger.info(f"Latency Reduction: {mean_reduction:.2f}% (95% CI: [{ci_lower:.2f}%, {ci_upper:.2f}%])")
    
    # Create results summary
    results = pd.DataFrame([{
        'metric': 'mean_latency_reduction_pct',
        'value': mean_reduction,
        'std': std_reduction,
        'ci_lower_95': ci_lower,
        'ci_upper_95': ci_upper,
        'n_bootstrap': len(bootstrap_df),
        'n_matched_pairs': len(matched_df) // 2,
        'data_source': config.get('data_source', 'unknown')
    }])
    
    # Also include bootstrap distribution for further analysis
    bootstrap_results = bootstrap_df.copy()
    bootstrap_results['metric'] = 'latency_reduction_pct'
    
    return bootstrap_results

def main():
    """Main entry point for the latency bias analysis."""
    parser = argparse.ArgumentParser(description='Analyze latency bias with propensity score matching')
    parser.add_argument('--n-bootstrap', type=int, default=1000, help='Number of bootstrap iterations')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    parser.add_argument('--output', type=str, default=None, help='Output file path (default: auto)')
    args = parser.parse_args()
    
    try:
        # Load data
        config = load_config_summary()
        hybrid_df = load_hybrid_output()
        
        # Run analysis
        results_df = run_latency_bias_analysis(hybrid_df, config)
        
        # Save results
        output_path = args.output
        if output_path is None:
            output_path = PROJECT_ROOT / 'data' / 'metrics' / 'latency_bootstrap_results.csv'
        else:
            output_path = Path(output_path)
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        results_df.to_csv(output_path, index=False)
        
        logger.info(f"Results saved to {output_path}")
        logger.info(f"Mean latency reduction: {results_df['value'].iloc[0]:.2f}%")
        
        # Update state
        update_state_with_artifacts([str(output_path)])
        
        return 0
        
    except Exception as e:
        logger.error(f"Analysis failed: {e}", exc_info=True)
        return 1

if __name__ == '__main__':
    sys.exit(main())
