import os
import csv
import logging
from typing import List, Dict, Any, Optional
from config import RESULTS_DIR

logger = logging.getLogger(__name__)

def load_mdes_results() -> List[Dict[str, Any]]:
    """
    Load MDES results from the power analysis step.
    Expects `results/mdes/mdes_results.json` or similar intermediate file.
    Since T021 writes directly to CSV in the current flow, we check for that first.
    However, to support the specific T025 task of generating the summary CSV
    from computed values, we assume the intermediate data exists in memory
    or a temporary file generated by `run_power_analysis`.
    
    For this implementation, we assume the `run_power_analysis` function
    (in power_analysis.py) has already computed the MDES values and stored them
    in a list of dicts or a temporary JSON file. If that file doesn't exist,
    we attempt to read from the CSV if it was written there directly by T021.
    
    Note: T021 description says "Write MDES result to results/mdes/mdes_summary.csv".
    If T021 writes the final file directly, T025 might be redundant or a verification step.
    However, per T025 description: "Generate results/mdes/mdes_summary.csv".
    We will implement the logic to read intermediate results (if T021 outputs to a temp file)
    or re-compute if necessary, but primarily we will ensure the file exists with correct columns.
    
    Given the dependency T021 -> T025, and T021 writes to the target file,
    T025 might be ensuring the format or regenerating it from a canonical source.
    We will assume T021 writes to a temporary file `results/mdes/mdes_results_raw.json`
    and T025 converts it to the final CSV. If that raw file doesn't exist, we check the CSV.
    """
    raw_path = os.path.join(RESULTS_DIR, "mdes", "mdes_results_raw.json")
    csv_path = os.path.join(RESULTS_DIR, "mdes", "mdes_summary.csv")
    
    results = []
    
    if os.path.exists(raw_path):
        import json
        with open(raw_path, 'r') as f:
            results = json.load(f)
        logger.info(f"Loaded {len(results)} MDES results from {raw_path}")
    elif os.path.exists(csv_path):
        # If T021 already wrote the CSV, we just read it back to return the structure
        # This handles the case where T021 is the one generating the file.
        logger.warning("Raw JSON not found, reading existing CSV as source of truth.")
        with open(csv_path, 'r', newline='') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Convert numeric strings back to float
                row['mdes'] = float(row['mdes'])
                row['power'] = float(row['power'])
                row['ci_width'] = float(row['ci_width'])
                results.append(row)
    else:
        raise FileNotFoundError(
            f"Neither raw MDES results ({raw_path}) nor summary CSV ({csv_path}) found. "
            "Ensure T021 (power_analysis) has run successfully."
        )
    
    return results

def generate_mdes_summary_csv(results: List[Dict[str, Any]], output_path: Optional[str] = None) -> str:
    """
    Generate the MDES summary CSV with columns: metric, mdes, power, ci_width.
    """
    if not output_path:
        output_path = os.path.join(RESULTS_DIR, "mdes", "mdes_summary.csv")
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    fieldnames = ['metric', 'mdes', 'power', 'ci_width']
    
    with open(output_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        
        for row in results:
            # Ensure metric is a string and others are floats
            writer.writerow({
                'metric': str(row.get('metric', '')),
                'mdes': float(row.get('mdes', 0.0)),
                'power': float(row.get('power', 0.0)),
                'ci_width': float(row.get('ci_width', 0.0))
            })
    
    logger.info(f"Generated MDES summary CSV: {output_path}")
    return output_path

def run_mdes_summary_generation() -> str:
    """
    Main entry point for T025: Load MDES results and generate the summary CSV.
    """
    logger.info("Starting MDES summary generation (T025)...")
    try:
        results = load_mdes_results()
        if not results:
            logger.warning("No MDES results found to generate summary.")
            # Create an empty file with headers? Or raise?
            # Per spec, we should generate the file. Empty is valid if no data.
            output_path = os.path.join(RESULTS_DIR, "mdes", "mdes_summary.csv")
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            with open(output_path, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=['metric', 'mdes', 'power', 'ci_width'])
                writer.writeheader()
            return output_path
        
        output_path = generate_mdes_summary_csv(results)
        return output_path
    except Exception as e:
        logger.error(f"Failed to generate MDES summary: {e}")
        raise

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run_mdes_summary_generation()
