"""
Script to generate docs/results.md from the computed stats_report.json.
This task finalizes the documentation by rendering the statistical findings
into a human-readable Markdown report.
"""
import json
import os
import logging
from pathlib import Path
from typing import Dict, Any

# Import existing utilities from the project
from analysis.report_generator import load_stats_report, generate_report

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def ensure_output_dirs():
    """Ensure the docs directory exists."""
    docs_dir = Path("docs")
    docs_dir.mkdir(exist_ok=True)
    return docs_dir

def main():
    """
    Main entry point to generate docs/results.md.
    
    1. Loads the stats_report.json generated by T027/T026.
    2. Uses the existing report generation logic to format the data.
    3. Writes the final Markdown to docs/results.md.
    """
    # Define paths relative to project root
    project_root = Path(__file__).resolve().parent.parent
    stats_path = project_root / "data" / "processed" / "stats_report.json"
    docs_dir = ensure_output_dirs()
    output_path = docs_dir / "results.md"

    logger.info(f"Loading stats report from: {stats_path}")
    
    if not stats_path.exists():
        logger.error(f"Stats report not found at {stats_path}. "
                     "Please ensure T027 and T026 have completed successfully.")
        raise FileNotFoundError(f"Stats report missing: {stats_path}")

    # Load the stats report using the existing utility
    stats_data = load_stats_report(stats_path)

    if not stats_data:
        logger.error("Stats report is empty or invalid.")
        raise ValueError("Stats report contains no data.")

    logger.info("Generating Markdown report from stats data...")
    
    # Generate the report content using the existing generator
    # The generate_report function returns the formatted string
    report_content = generate_report(stats_data)

    # Write the final output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    logger.info(f"Successfully generated documentation at: {output_path}")
    return output_path

if __name__ == "__main__":
    main()
