"""
Mock NIfTI Generator for Format Testing.

This module generates valid NIfTI-1 (.nii) header structures and minimal
image data files to test data ingestion pipelines, schema validation,
and error handling for corrupted or missing files.

It relies on `nibabel` to write the binary format, ensuring the output
is a genuine, parseable NIfTI file, not a synthetic text placeholder.

Usage:
    python code/data/mock_nifti.py --output data/raw/mock_test.nii
"""

import os
import sys
import logging
import argparse
from pathlib import Path
from typing import Optional, Tuple

import numpy as np
import nibabel as nib

# Add project root to path for imports if running as script
if __package__ is None:
    sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.logging import get_logger

logger = get_logger(__name__)


def create_mock_nifti(
    output_path: str,
    shape: Tuple[int, int, int, int] = (10, 10, 10, 1),
    dtype: np.dtype = np.float32,
    affine: Optional[np.ndarray] = None,
    voxel_sizes: Tuple[float, float, float] = (2.0, 2.0, 2.0),
    seed: int = 42
) -> str:
    """
    Generates a valid NIfTI-1 file with random or zero-filled data.

    This function creates a file that passes `nibabel.load()` validation,
    allowing downstream tests (e.g., T018) to verify handling of valid
    structures vs. corrupted files.

    Args:
        output_path: Full path where the .nii file will be written.
        shape: Dimensions of the image (x, y, z, t).
        dtype: Data type of the image array.
        affine: 4x4 affine transformation matrix. If None, identity is used.
        voxel_sizes: (x, y, z) voxel dimensions in mm.
        seed: Random seed for reproducibility if data is randomized.

    Returns:
        str: The path to the created file.

    Raises:
        ValueError: If the output path is invalid or dimensions are non-positive.
        IOError: If writing to disk fails.
    """
    if not output_path.endswith(('.nii', '.nii.gz')):
        output_path = f"{output_path}.nii"

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if any(dim <= 0 for dim in shape):
        raise ValueError(f"Shape dimensions must be positive: {shape}")

    if affine is None:
        affine = np.eye(4)
        # Set scaling based on voxel sizes
        affine[0, 0] = voxel_sizes[0]
        affine[1, 1] = voxel_sizes[1]
        affine[2, 2] = voxel_sizes[2]

    # Generate data
    np.random.seed(seed)
    # Use small random values to simulate fMRI noise, avoiding extreme outliers
    data = np.random.normal(loc=0.0, scale=0.1, size=shape).astype(dtype)

    # Create NIfTI image object
    img = nib.Nifti1Image(data, affine)

    # Set header fields to standard values for testing
    # Ensure data type in header matches array dtype
    img.set_data_dtype(dtype)
    
    # Set intent code to 'NONE' (0) or 'TTEST' (1001) if needed, defaulting to 0
    img.header['intent_code'] = 0
    img.header['descrip'] = b"Mock data generated by mock_nifti.py for T009"

    try:
        nib.save(img, str(output_path))
        logger.info(f"Successfully created mock NIfTI file: {output_path}")
        return str(output_path)
    except Exception as e:
        logger.error(f"Failed to write NIfTI file to {output_path}: {e}")
        raise IOError(f"Could not write NIfTI file: {e}")


def create_corrupted_nifti(output_path: str) -> str:
    """
    Creates a file with a .nii extension but invalid binary content.
    
    Used to test error handling in preprocess.py (T018).
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write garbage bytes that do not form a valid NIfTI header
    with open(output_path, 'wb') as f:
        f.write(b"NOT A NIFTI FILE - CORRUPTED DATA FOR TESTING")
    
    logger.info(f"Successfully created corrupted NIfTI file: {output_path}")
    return str(output_path)


def main():
    """CLI entry point for generating mock NIfTI files."""
    parser = argparse.ArgumentParser(description="Generate mock NIfTI files for testing.")
    parser.add_argument(
        "--output", 
        type=str, 
        default="data/raw/mock_test.nii",
        help="Output path for the .nii file."
    )
    parser.add_argument(
        "--corrupt", 
        action="store_true", 
        help="If set, creates a corrupted file instead of a valid one."
    )
    parser.add_argument(
        "--shape", 
        type=int, 
        nargs=3, 
        default=[10, 10, 10],
        help="Shape of the image (x, y, z). Time dimension fixed at 1."
    )
    parser.add_argument(
        "--voxel-size", 
        type=float, 
        nargs=3, 
        default=[2.0, 2.0, 2.0],
        help="Voxel dimensions (x, y, z) in mm."
    )
    
    args = parser.parse_args()
    
    try:
        if args.corrupt:
            create_corrupted_nifti(args.output)
        else:
            shape = tuple(list(args.shape) + [1])
            create_mock_nifti(
                args.output,
                shape=shape,
                voxel_sizes=tuple(args.voxel_size)
            )
        print(f"File created: {args.output}")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()