"""
T036: Append Section 4.2 to research.md documenting regimes where empirical models fail.

This script reads the failure regimes identified in T033 (data/processed/failure_regimes.csv)
and appends a formatted Section 4.2 to specs/001-predict-strain-rate-yield/research.md.
"""
import os
import sys
import logging
import pandas as pd
from pathlib import Path
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Define paths relative to project root
# Assuming this script runs from code/reporting/
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
RESEARCH_MD_PATH = PROJECT_ROOT / "specs" / "001-predict-strain-rate-yield" / "research.md"
FAILURE_REGIMES_PATH = PROJECT_ROOT / "data" / "processed" / "failure_regimes.csv"

def load_failure_regimes():
    """Load the failure regimes data generated by T033."""
    if not FAILURE_REGIMES_PATH.exists():
        raise FileNotFoundError(
            f"Required input file not found: {FAILURE_REGIMES_PATH}. "
            "Ensure T033 has been executed successfully."
        )
    
    df = pd.read_csv(FAILURE_REGIMES_PATH)
    logger.info(f"Loaded {len(df)} failure regime records from {FAILURE_REGIMES_PATH}")
    return df

def generate_section_4_2(df):
    """Generate the markdown content for Section 4.2."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Calculate summary statistics
    total_records = len(df)
    if total_records == 0:
        logger.warning("No failure regimes detected. Generating empty section.")
        return f"""## 4.2 Empirical Model Failure Regimes

**Analysis Date:** {timestamp}

**Summary:** No specific failure regimes for empirical models were identified in the current dataset. The models performed within expected tolerances across all tested conditions.

*Note: This analysis is based on the Wilcoxon signed-rank test and error distribution analysis comparing ML models against Johnson-Cook and Zerilli-Armstrong empirical models.*
"""

    # Group by alloy family and strain rate regime for summary
    summary_stats = df.groupby('alloy_family').agg({
        'strain_rate_category': 'value_counts',
        'model_type': lambda x: x.mode().iloc[0] if not x.mode().empty else 'Unknown'
    }).reset_index()
    
    # Get unique regimes
    unique_regimes = df['regime_description'].unique()
    unique_alloys = df['alloy_family'].unique()
    
    # Find worst performing categories
    worst_perf = df.groupby(['alloy_family', 'strain_rate_category']).size().reset_index(name='count')
    worst_perf = worst_perf.sort_values('count', ascending=False)
    
    section_content = f"""## 4.2 Empirical Model Failure Regimes

**Analysis Date:** {timestamp}
**Data Source:** `data/processed/failure_regimes.csv` (T033)

### Overview
This section documents the specific material conditions and regimes where empirical constitutive models (Johnson-Cook, Zerilli-Armstrong) fail to accurately predict yield strength compared to machine learning models. Failure is defined as statistically significant deviation (p < 0.05, Benjamini-Hochberg corrected) in prediction error.

### Summary Statistics
- **Total Failure Records Identified:** {total_records}
- **Affected Alloy Families:** {', '.join(sorted(unique_alloys))}
- **Distinct Failure Regimes:** {len(unique_regimes)}

### Identified Failure Regimes
The following regimes exhibited consistent empirical model failure:

"""
    
    # Add regime details
    for i, regime in enumerate(unique_regimes, 1):
        count = len(df[df['regime_description'] == regime])
        affected_alloys = df[df['regime_description'] == regime]['alloy_family'].unique()
        section_content += f"{i}. **{regime}**\n"
        section_content += f"   - Occurrence Count: {count}\n"
        section_content += f"   - Affected Alloys: {', '.join(sorted(affected_alloys))}\n\n"
    
    # Add detailed breakdown by alloy
    section_content += "### Detailed Analysis by Alloy Family\n\n"
    section_content += "| Alloy Family | Primary Failure Regime | Record Count | Dominant Empirical Model Failure |\n"
    section_content += "|--------------|------------------------|--------------|----------------------------------|\n"
    
    for alloy in sorted(unique_alloys):
        alloy_data = df[df['alloy_family'] == alloy]
        primary_regime = alloy_data['regime_description'].mode().iloc[0] if not alloy_data['regime_description'].mode().empty else "N/A"
        count = len(alloy_data)
        dominant_model = alloy_data['model_type'].mode().iloc[0] if not alloy_data['model_type'].mode().empty else "N/A"
        section_content += f"| {alloy} | {primary_regime} | {count} | {dominant_model} |\n"
    
    # Add recommendations
    section_content += "\n### Recommendations\n\n"
    section_content += "Based on the identified failure regimes, the following recommendations are made:\n\n"
    
    if 'High Strain Rate' in str(unique_regimes):
        section_content += "- **High Strain Rate Regimes:** Empirical models consistently underpredict yield strength. ML models (Random Forest, Gradient Boosting) should be prioritized for applications involving impact or explosive loading.\n"
    
    if 'Low Temperature' in str(unique_regimes):
        section_content += "- **Low Temperature Conditions:** Thermal softening terms in empirical models may be insufficient. Consider hybrid approaches for cryogenic applications.\n"
    
    if 'Complex Composition' in str(unique_regimes):
        section_content += "- **Complex Alloy Compositions:** Empirical models trained on standard compositions fail for multi-component alloys. Data-driven models capturing elemental interactions are required.\n"
    
    section_content += "\n### Methodology Note\n"
    section_content += "Failure regimes were identified using the Wilcoxon signed-rank test with Benjamini-Hochberg correction to compare prediction errors between ML and empirical models. Records with p < 0.05 were flagged and categorized by strain rate, temperature, and alloy family.\n"
    
    return section_content

def append_to_research_md(section_content):
    """Append the generated section to research.md."""
    if not RESEARCH_MD_PATH.exists():
        # Create the file if it doesn't exist (shouldn't happen in normal flow)
        RESEARCH_MD_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(RESEARCH_MD_PATH, 'w', encoding='utf-8') as f:
            f.write("# Research Documentation\n\n")
        logger.info(f"Created new research.md at {RESEARCH_MD_PATH}")
    
    # Read existing content
    with open(RESEARCH_MD_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check if Section 4.2 already exists
    if "## 4.2 Empirical Model Failure Regimes" in content:
        logger.warning("Section 4.2 already exists. Overwriting...")
        # Remove existing section 4.2 and 4.3+ to replace cleanly
        # Simple approach: find start of 4.2 and end of file, replace
        lines = content.split('\n')
        new_lines = []
        skip = False
        for line in lines:
            if line.startswith('## 4.2 '):
                skip = True
                continue
            if skip and line.startswith('## 4.'):
                skip = False
            if not skip:
                new_lines.append(line)
        
        base_content = '\n'.join(new_lines).rstrip() + '\n'
        final_content = base_content + '\n' + section_content
    else:
        # Append at the end
        final_content = content.rstrip() + '\n\n' + section_content
    
    # Write back
    with open(RESEARCH_MD_PATH, 'w', encoding='utf-8') as f:
        f.write(final_content)
    
    logger.info(f"Successfully appended Section 4.2 to {RESEARCH_MD_PATH}")

def main():
    """Main entry point for T036."""
    logger.info("Starting T036: Append Failure Regimes to Research Documentation")
    
    try:
        # 1. Load failure regimes data
        df = load_failure_regimes()
        
        # 2. Generate section content
        section_content = generate_section_4_2(df)
        
        # 3. Append to research.md
        append_to_research_md(section_content)
        
        logger.info("T036 completed successfully.")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"File not found: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())