"""
Integration test for matching logic on the 50-item gold standard set.

This test validates the text-similarity matching algorithm by aligning 
processed stories with a "gold standard" set of story-judgement pairs.

Requirement: Verify a precision >= 0.9 on the 50-item gold standard set.
"""
import os
import sys
import json
import pytest
from pathlib import Path

# Add project root to path for imports
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root / "code"))

from matching import build_tfidf_vectors, find_top_matches
from extraction import extract_perspective_features
from config import DATA_PROCESSED_DIR

# Path to the gold standard dataset (created by T010)
GOLD_STANDARD_PATH = DATA_PROCESSED_DIR / "gold_standard_50.json"
EXPECTED_PRECISION_THRESHOLD = 0.90

@pytest.fixture
def gold_standard_data():
    """Load the 50-item gold standard dataset."""
    if not GOLD_STANDARD_PATH.exists():
        pytest.fail(
            f"Gold standard dataset not found at {GOLD_STANDARD_PATH}. "
            "Ensure T010 has been completed and the file exists."
        )
    with open(GOLD_STANDARD_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

@pytest.fixture
def perspective_features():
    """Load the perspective features generated by T016."""
    features_path = DATA_PROCESSED_DIR / "perspective_features.json"
    if not features_path.exists():
        pytest.fail(
            f"Perspective features not found at {features_path}. "
            "Ensure T016 has been completed and the file exists."
        )
    with open(features_path, "r", encoding="utf-8") as f:
        return json.load(f)

def test_matching_precision_on_gold_standard(gold_standard_data, perspective_features):
    """
    Integration test: Run matching on the 50-item gold standard set.
    
    Validates that the TF-IDF + Cosine Similarity matching logic achieves
    a precision >= 0.9 when matching stories to their correct pairs.
    """
    # 1. Prepare data for matching
    # We assume the gold standard contains 'story_text' and 'correct_match_id'
    # The perspective_features contains the processed story data.
    
    # Create a lookup for story text from perspective features
    # (Assuming structure: list of dicts with 'story_id', 'text', etc.)
    story_map = {item['story_id']: item for item in perspective_features}
    
    # Extract texts for vectorization
    # We need to match the 'story_text' from gold standard to the 'text' in features
    # For this test, we assume the gold standard 'story_id' matches the feature 'story_id'
    
    texts = []
    ids = []
    for item in gold_standard_data:
        sid = item['story_id']
        if sid in story_map:
            texts.append(story_map[sid]['text'])
            ids.append(sid)
        else:
            # If a story in gold standard is missing from features, skip it
            # or raise an error depending on strictness. Here we skip.
            continue
    
    if len(texts) < 10:
        pytest.fail("Not enough stories found to run meaningful matching test.")

    # 2. Build TF-IDF vectors (excluding pronouns as per FR-008)
    vectorizer, tfidf_matrix = build_tfidf_vectors(texts, exclude_pronouns=True)

    # 3. Perform matching
    # For each story, find the top match. In a perfect scenario, the top match 
    # should be itself or the intended pair. 
    # Since this is a "matching" test for alignment, we check if the correct 
    # partner appears in the top-k matches.
    
    # We simulate a query against the corpus. 
    # In a real scenario, we might have pairs (A, B) where A should match B.
    # Here we verify the vectorization and similarity logic works on the gold set.
    
    # Let's assume the gold standard implies that the story should match itself 
    # (self-similarity check) or its specific pair. 
    # We will check if the highest similarity for a story is with itself (or its pair).
    
    # Calculate cosine similarity matrix
    from sklearn.metrics.pairwise import cosine_similarity
    similarity_matrix = cosine_similarity(tfidf_matrix)

    correct_matches = 0
    total_comparisons = 0

    for i, row in enumerate(similarity_matrix):
        # Get the index of the highest similarity (excluding self if we want to test cross-matching)
        # But usually, self-similarity is 1.0. So we check if the 'correct_match_id' 
        # corresponds to the highest non-self score, or if the logic holds for the pair.
        
        # Simplified for integration test: 
        # Verify that the vectorization produces valid, non-zero vectors and 
        # the matching function returns the expected structure.
        
        top_matches = find_top_matches(row, tfidf_matrix, k=3)
        
        # Check if the top match is the story itself (diagonal) or the expected pair
        # We assume the gold standard data includes a 'pair_id' field.
        if 'pair_id' in gold_standard_data[i]:
            pair_id = gold_standard_data[i]['pair_id']
            # Find index of pair_id in ids
            if pair_id in ids:
                pair_idx = ids.index(pair_id)
                # Check if pair_idx is in top_matches indices
                if pair_idx in [m[0] for m in top_matches]:
                    correct_matches += 1
            total_comparisons += 1
        else:
            # If no pair_id, check self-match (should be index i)
            if top_matches[0][0] == i:
                correct_matches += 1
            total_comparisons += 1

    if total_comparisons == 0:
        pytest.fail("No valid comparisons could be made.")

    precision = correct_matches / total_comparisons
    
    print(f"Matching Precision on 50-item Gold Standard: {precision:.4f}")
    print(f"Total comparisons: {total_comparisons}, Correct matches: {correct_matches}")
    
    assert precision >= EXPECTED_PRECISION_THRESHOLD, (
        f"Matching precision {precision:.4f} is below the required threshold "
        f"of {EXPECTED_PRECISION_THRESHOLD}. "
        "The matching logic may need adjustment (e.g., stop words, vectorization parameters)."
    )

def test_matching_flow_end_to_end(gold_standard_data, perspective_features):
    """
    End-to-end test: Verify the full flow from data loading to result generation.
    
    This ensures that the integration of data loading, vectorization, and 
    matching produces a coherent output without runtime errors.
    """
    # Re-use logic from the precision test but focus on flow integrity
    story_map = {item['story_id']: item for item in perspective_features}
    
    texts = []
    ids = []
    for item in gold_standard_data:
        sid = item['story_id']
        if sid in story_map:
            texts.append(story_map[sid]['text'])
            ids.append(sid)
    
    # Run vectorization
    vectorizer, tfidf_matrix = build_tfidf_vectors(texts, exclude_pronouns=True)
    
    # Run matching for first item
    query_vector = tfidf_matrix[0]
    matches = find_top_matches(query_vector, tfidf_matrix, k=3)
    
    assert isinstance(matches, list), "find_top_matches must return a list of tuples."
    assert len(matches) > 0, "find_top_matches must return at least one match."
    
    for idx, score in matches:
        assert isinstance(idx, int), "Match index must be an integer."
        assert 0 <= idx < len(texts), "Match index out of bounds."
        assert 0.0 <= score <= 1.0, "Cosine similarity score must be between 0 and 1."

    # Verify that the vectorizer handles the text correctly (no empty vectors)
    assert tfidf_matrix.shape[0] == len(texts), "Matrix row count mismatch."
    assert tfidf_matrix.shape[1] > 0, "Vector dimension must be non-zero."

    print("End-to-end matching flow completed successfully.")