"""
Task T025: Generate structured CSV `data/processed/graph_metrics.csv`
linking `device_id`, `metric_name`, `value`, `is_finite`.

This script reads the processed calibration CSV (produced by T017),
reconstructs coupling graphs using the `graph_builder` module,
computes topological metrics, and writes the results to a long-format
CSV file.
"""
import os
import csv
import logging
from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional

import pandas as pd
import networkx as nx

from code import logger
from code import graph_builder
from code import generate_calibration_csv

# Configure logging
LOG = logger.setup_logger(__name__)

def load_processed_calibration(csv_path: str) -> pd.DataFrame:
    """
    Load the processed calibration CSV generated by T017.
    
    Expected columns include 'device_id', 'coupling_map' (as string/list),
    and performance metrics.
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Processed calibration file not found at {csv_path}. "
            "Please ensure T017 (generate_calibration_csv) has been run first."
        )
    
    LOG.info(f"Loading processed calibration data from {csv_path}")
    df = pd.read_csv(csv_path)
    
    # Ensure coupling_map is parsed if stored as string
    if 'coupling_map' in df.columns:
        # If it's a string representation of a list, parse it
        # Otherwise assume it's already a list or JSON
        def parse_coupling_map(val):
            if isinstance(val, list):
                return val
            if isinstance(val, str):
                # Simple eval for list of lists, or json.loads
                import json
                try:
                    return json.loads(val)
                except (json.JSONDecodeError, ValueError):
                    # Fallback for string representation like "[[0, 1], [1, 2]]"
                    return ast.literal_eval(val)
            return val

        import ast
        df['coupling_map'] = df['coupling_map'].apply(parse_coupling_map)
    
    return df

def compute_device_metrics(device_id: str, coupling_map: List[List[int]]) -> Dict[str, float]:
    """
    Compute all graph metrics for a single device's coupling map.
    
    Returns a dictionary mapping metric_name -> value.
    """
    metrics = {}
    
    try:
        # Build the graph
        G = graph_builder.build_coupling_graph(coupling_map)
        
        if G.number_of_nodes() == 0:
            LOG.warning(f"Device {device_id} has no nodes in coupling map.")
            return metrics

        # 1. Shortest Path Metrics
        path_metrics = graph_builder.compute_shortest_path_metrics(G)
        metrics.update(path_metrics)

        # 2. Clustering and Assortativity
        cluster_metrics = graph_builder.compute_clustering_and_assortativity(G)
        metrics.update(cluster_metrics)

        # 3. Edge Betweenness and Spectral Gap
        spectral_metrics = graph_builder.compute_edge_betweenness_and_spectral_gap(G)
        metrics.update(spectral_metrics)

    except Exception as e:
        LOG.error(f"Error computing metrics for device {device_id}: {e}", exc_info=True)
        # Return empty metrics or handle gracefully
        # We do not raise here to allow processing of other devices
    
    return metrics

def main():
    """
    Main entry point to generate graph_metrics.csv.
    """
    # Paths
    project_root = Path(__file__).resolve().parent.parent
    input_csv = project_root / "data" / "processed" / "raw_calibration.csv"
    output_csv = project_root / "data" / "processed" / "graph_metrics.csv"

    # Ensure output directory exists
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    # Load data
    df = load_processed_calibration(str(input_csv))

    if df.empty:
        LOG.warning("No devices found in input CSV. Exiting.")
        return

    LOG.info(f"Processing {len(df)} devices...")
    
    results = []
    
    for _, row in df.iterrows():
        device_id = row['device_id']
        coupling_map = row.get('coupling_map')
        
        if not isinstance(coupling_map, list):
            LOG.warning(f"Skipping {device_id}: invalid coupling_map type.")
            continue
        
        metrics = compute_device_metrics(device_id, coupling_map)
        
        for metric_name, value in metrics.items():
            is_finite = True
            if value is None:
                is_finite = False
                value = 0.0
            elif not (isinstance(value, (int, float)) and (value == value)): # check NaN
                # Handle NaN explicitly
                if value != value:
                    is_finite = False
                    value = 0.0
            elif not (float('-inf') < value < float('inf')):
                is_finite = False
                value = 0.0
            
            results.append({
                'device_id': device_id,
                'metric_name': metric_name,
                'value': value,
                'is_finite': is_finite
            })

    # Write to CSV
    LOG.info(f"Writing results to {output_csv}")
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['device_id', 'metric_name', 'value', 'is_finite'])
        writer.writeheader()
        writer.writerows(results)

    LOG.info(f"Successfully generated {len(results)} metric records for {len(results)} unique (device, metric) pairs.")

if __name__ == "__main__":
    main()
