import os
import sys
import json
import hashlib
import logging
import time
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple
from datetime import datetime

# Import config to get paths
try:
    from config.settings import get_config
except ImportError:
    # Fallback for direct execution
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from config.settings import get_config

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def compute_file_sha256(file_path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    try:
        with open(file_path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except FileNotFoundError:
        logger.warning(f"File not found for hashing: {file_path}")
        return None

def load_recorded_checksums(checksum_file: Path) -> Dict[str, str]:
    """Load recorded checksums from the YAML/JSON file generated by T027."""
    if not checksum_file.exists():
        raise FileNotFoundError(f"Checksum file not found: {checksum_file}")
    
    # Handle both YAML and JSON formats if necessary, but spec says .yaml
    # We'll try to parse it as JSON first if it looks like JSON, else YAML
    content = checksum_file.read_text(encoding='utf-8')
    
    # Simple check for JSON structure
    if content.strip().startswith('{'):
        return json.loads(content)
    
    # If YAML, we need to parse it. Since we don't want to add yaml as a hard dependency
    # just for this if it's already in requirements, we check if pyyaml is available.
    try:
        import yaml
        data = yaml.safe_load(content)
        # The spec says "map of file paths to SHA-256 hashes"
        # It might be nested under a key like 'artifacts' or 'checksums'
        if isinstance(data, dict):
            if 'artifacts' in data:
                return data['artifacts']
            if 'checksums' in data:
                return data['checksums']
            # Assume top level is the map if all values are strings
            if all(isinstance(v, str) for v in data.values()):
                return data
        return data
    except ImportError:
        logger.error("PyYAML is not installed. Cannot parse YAML checksum file.")
        raise
    except Exception as e:
        logger.error(f"Failed to parse checksum file: {e}")
        raise

def verify_artifacts(recorded_checksums: Dict[str, str]) -> Dict[str, Dict[str, Any]]:
    """
    Verify current artifacts against recorded checksums.
    Returns a dict mapping file path to verification details.
    """
    results = {}
    config = get_config()
    project_root = Path(__file__).parent.parent.parent # code/data/verify_reproducibility.py -> project root
    
    for rel_path, expected_hash in recorded_checksums.items():
        # Construct full path relative to project root
        full_path = project_root / rel_path
        
        if not full_path.exists():
            results[rel_path] = {
                "expected": expected_hash,
                "current": None,
                "match": False,
                "error": "File not found"
            }
            logger.warning(f"Artifact missing: {full_path}")
            continue
        
        current_hash = compute_file_sha256(full_path)
        
        if current_hash is None:
            results[rel_path] = {
                "expected": expected_hash,
                "current": None,
                "match": False,
                "error": "Hash computation failed"
            }
            continue
        
        match = current_hash == expected_hash
        results[rel_path] = {
            "expected": expected_hash,
            "current": current_hash,
            "match": match
        }
        
        if match:
            logger.info(f"Verified: {rel_path}")
        else:
            logger.error(f"MISMATCH: {rel_path}")
    
    return results

def generate_report(results: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Generate a structured report of the verification results."""
    all_passed = all(r.get("match", False) for r in results.values())
    
    report = {
        "timestamp": datetime.now().isoformat(),
        "status": "passed" if all_passed else "failed",
        "total_artifacts": len(results),
        "passed_count": sum(1 for r in results.values() if r.get("match", False)),
        "failed_count": sum(1 for r in results.values() if not r.get("match", False)),
        "verification_results": results
    }
    
    return report

def main():
    """Main entry point for T028."""
    logger.info("Starting Reproducibility Verification (T028)...")
    
    config = get_config()
    state_dir = config.paths.state
    project_root = Path(__file__).parent.parent.parent
    
    # Path to recorded checksums (from T027)
    checksums_path = state_dir / "projects" / "PROJ-139-the-influence-of-emotional-contagion-on-.yaml"
    
    if not checksums_path.exists():
        logger.error(f"Checksums file not found: {checksums_path}")
        logger.error("Please ensure T027 has been run to record checksums.")
        sys.exit(1)
    
    try:
        recorded = load_recorded_checksums(checksums_path)
        logger.info(f"Loaded {len(recorded)} recorded checksums.")
        
        results = verify_artifacts(recorded)
        report = generate_report(results)
        
        # Write report to state directory
        report_path = state_dir / "reproducibility_report.json"
        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)
        
        logger.info(f"Reproducibility report written to: {report_path}")
        
        if report["status"] == "passed":
            logger.info("SUCCESS: All artifacts match recorded checksums.")
            sys.exit(0)
        else:
            logger.error("FAILURE: Some artifacts do not match recorded checksums.")
            sys.exit(1)
            
    except Exception as e:
        logger.error(f"Verification failed with error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()