import json
import logging
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd
import numpy as np

from config import Config
from data_models import PromptItem, ModelResponse, AnalysisResult

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def load_feature_data(features_path: Path) -> pd.DataFrame:
    """
    Load the feature-rich dataset generated by T014/T016.
    Expects 'data/processed/features.csv'.
    """
    if not features_path.exists():
        raise FileNotFoundError(
            f"Feature data file not found at {features_path}. "
            "Ensure T014/T016 has been completed and data/processed/features.csv exists."
        )
    df = pd.read_csv(features_path)
    logger.info(f"Loaded {len(df)} rows from {features_path}")
    return df

def load_annotation_data(annotation_path: Path) -> pd.DataFrame:
    """
    Load the aggregated rater responses from T017c.
    Expects 'data/interim/annotation_pilot_us1.csv'.
    Required columns: 'prompt_id', 'rater_id', 'authority_density_score'.
    """
    if not annotation_path.exists():
        raise FileNotFoundError(
            f"Annotation data file not found at {annotation_path}. "
            "Ensure T017c has been completed and data/interim/annotation_pilot_us1.csv exists."
        )
    df = pd.read_csv(annotation_path)
    logger.info(f"Loaded {len(df)} rows from {annotation_path}")
    
    # Validate required columns
    required_cols = ['prompt_id', 'rater_id', 'authority_density_score']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Annotation data missing required columns: {missing_cols}")
    
    return df

def merge_data_for_correlation(features_df: pd.DataFrame, annotation_df: pd.DataFrame) -> pd.DataFrame:
    """
    Merge feature data with annotation data on 'prompt_id'.
    Computes the mean authority density score per prompt if multiple raters exist.
    """
    # Aggregate annotation scores by prompt_id (mean)
    agg_annotation = annotation_df.groupby('prompt_id')['authority_density_score'].mean().reset_index()
    agg_annotation.rename(columns={'authority_density_score': 'mean_authority_density'}, inplace=True)
    
    # Merge with features
    merged = pd.merge(
        features_df,
        agg_annotation,
        on='prompt_id',
        how='inner'
    )
    
    logger.info(f"Merged dataset size: {len(merged)} rows")
    
    # Drop rows with NaN in critical columns for correlation
    clean_merged = merged.dropna(subset=['mean_authority_density'])
    
    # Identify feature columns for correlation (excluding IDs and the target itself)
    # Assuming T014 generated columns like 'modal_verb_freq', 'imperative_ratio', 'citation_density'
    # We will dynamically select numeric columns that are not IDs
    numeric_cols = clean_merged.select_dtypes(include=[np.number]).columns.tolist()
    feature_cols = [c for c in numeric_cols if c not in ['prompt_id', 'mean_authority_density']]
    
    logger.info(f"Feature columns selected for correlation: {feature_cols}")
    
    return clean_merged, feature_cols

def compute_correlations(df: pd.DataFrame, feature_cols: List[str], target_col: str = 'mean_authority_density') -> Dict[str, Any]:
    """
    Compute Pearson correlation coefficients between each feature and the target.
    Returns a dictionary of results.
    """
    results = {
        "target": target_col,
        "correlations": [],
        "timestamp": datetime.now().isoformat()
    }
    
    for col in feature_cols:
        # Check for zero variance
        if df[col].std() == 0:
            logger.warning(f"Skipping {col}: zero variance")
            continue
        
        if df[target_col].std() == 0:
            logger.warning(f"Skipping {target_col}: zero variance")
            break
        
        corr = df[col].corr(df[target_col])
        results["correlations"].append({
            "feature": col,
            "pearson_r": float(corr),
            "sample_size": len(df)
        })
    
    return results

def run_annotation_analyze_pipeline(config: Config, output_path: Path) -> None:
    """
    Main pipeline for T017d: Analyze correlation between automated features and human ratings.
    1. Load features (T016 output)
    2. Load annotations (T017c output)
    3. Merge data
    4. Compute correlations
    5. Save raw correlation data to JSON
    """
    logger.info("Starting T017d Analysis Pipeline")
    
    features_path = config.DATA_PROCESSED_DIR / "features.csv"
    annotation_path = config.DATA_INTERIM_DIR / "annotation_pilot_us1.csv"
    
    try:
        # Load data
        features_df = load_feature_data(features_path)
        annotation_df = load_annotation_data(annotation_path)
        
        # Merge
        merged_df, feature_cols = merge_data_for_correlation(features_df, annotation_df)
        
        if len(merged_df) == 0:
            raise ValueError("Merged dataset is empty after joining features and annotations.")
        
        # Compute correlations
        correlation_results = compute_correlations(merged_df, feature_cols)
        
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Save results
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(correlation_results, f, indent=2)
        
        logger.info(f"Correlation analysis complete. Results saved to {output_path}")
        logger.info(f"Correlations found: {len(correlation_results['correlations'])}")
        
    except FileNotFoundError as e:
        logger.error(f"Data file missing: {e}")
        raise
    except ValueError as e:
        logger.error(f"Data processing error: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error during analysis: {e}")
        raise

def main():
    """Entry point for T017d execution."""
    config = Config()
    output_path = config.DATA_INTERIM_DIR / "annotation_correlation_raw.json"
    
    logger.info(f"Executing T017d with output target: {output_path}")
    
    run_annotation_analyze_pipeline(config, output_path)

if __name__ == "__main__":
    main()