"""
Validation logic for specific tasks (e.g., T015 - imperative ratio).
"""
import os
import csv
import logging
from typing import List, Dict, Any, Tuple, Optional
from pathlib import Path
import pandas as pd

from features import extract_features, run_feature_extraction

logger = logging.getLogger(__name__)

def flag_undefined_imperative_ratio(row: Dict[str, Any]) -> bool:
    """
    Flag if imperative ratio is undefined (zero total sentences).
    """
    total_sentences = row.get('total_sentences', 0)
    return total_sentences == 0

def validate_features_for_imperative_ratio(input_path: Path, output_path: Path):
    """
    Validate features and flag undefined imperative ratios.
    """
    logger.info(f"Validating features in {input_path}")
    
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    df = pd.read_csv(input_path)
    
    flags = []
    for idx, row in df.iterrows():
        is_undefined = flag_undefined_imperative_ratio(row)
        flags.append({
            'prompt_id': row.get('prompt_id', idx),
            'is_undefined': is_undefined,
            'total_sentences': row.get('total_sentences', 0)
        })

    flags_df = pd.DataFrame(flags)
    flags_df.to_csv(output_path, index=False)
    
    undefined_count = flags_df['is_undefined'].sum()
    logger.info(f"Validation complete. {undefined_count} prompts with undefined imperative ratio.")

def run_t015_validation_pipeline(input_csv: str, output_csv: str):
    """
    Run the full T015 validation pipeline.
    """
    logger.info("Running T015 validation pipeline...")
    
    # Ensure input exists
    if not os.path.exists(input_csv):
        logger.error(f"Input file {input_csv} not found. Cannot run validation.")
        return False

    # Run feature extraction if needed (assuming features.csv is already generated by T014)
    # If input_csv is the features file, skip extraction
    # Here we assume input_csv is the features file
    
    validate_features_for_imperative_ratio(Path(input_csv), Path(output_csv))
    return True

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    # Example usage
    input_file = "data/processed/features.csv"
    output_file = "data/interim/undefined_imperative_flags.csv"
    if os.path.exists(input_file):
        run_t015_validation_pipeline(input_file, output_file)
    else:
        logger.warning(f"Input file {input_file} not found.")
