"""
code/analysis/bias.py
Implementation of Egger's linear regression test for publication bias assessment.
"""
import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# Attempt to import statsmodels; if unavailable, the script will fail loudly as per constraints
try:
    import statsmodels.api as sm
except ImportError:
    raise ImportError(
        "statsmodels is required for Egger's regression. "
        "Install it via: pip install statsmodels"
    )

def get_project_root() -> Path:
    """Return the project root directory (parent of 'code')."""
    current = Path(__file__).resolve()
    # Assumes file is at code/analysis/bias.py
    return current.parent.parent

def load_study_count_from_json() -> int:
    """
    Load the study count N from data/processed/study_count.json.
    Raises FileNotFoundError if the file is missing.
    """
    project_root = get_project_root()
    path = project_root / "data" / "processed" / "study_count.json"
    if not path.exists():
        raise FileNotFoundError(f"Study count file not found: {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    if "N" not in data:
        raise ValueError(f"Expected key 'N' in {path}, got keys: {list(data.keys())}")
    
    return int(data["N"])

def load_effect_sizes_and_se() -> Tuple[List[float], List[float]]:
    """
    Load effect sizes (r) and standard errors (SE) from data/derived/results_quant.json.
    This file is expected to be generated by T014 (meta_analysis.py) when N >= 10.
    
    Returns:
        Tuple of (list of r values, list of SE values).
    
    Raises:
        FileNotFoundError: If results_quant.json is missing.
        ValueError: If required keys are missing or data is invalid.
    """
    project_root = get_project_root()
    path = project_root / "data" / "derived" / "results_quant.json"
    
    if not path.exists():
        raise FileNotFoundError(f"Quantitative results file not found: {path}")
    
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Expected structure: {"studies": [{"r": float, "se": float}, ...], ...}
    if "studies" not in data:
        raise ValueError(f"Expected key 'studies' in {path}")
    
    studies = data["studies"]
    r_values = []
    se_values = []
    
    for i, study in enumerate(studies):
        if "r" not in study or "se" not in study:
            raise ValueError(f"Study at index {i} missing 'r' or 'se' in {path}")
        
        r_val = float(study["r"])
        se_val = float(study["se"])
        
        # Basic validation
        if not (-1.0 <= r_val <= 1.0):
            raise ValueError(f"Invalid r value {r_val} at index {i}. Must be between -1 and 1.")
        if se_val <= 0:
            raise ValueError(f"Invalid SE value {se_val} at index {i}. Must be positive.")
        
        r_values.append(r_val)
        se_values.append(se_val)
    
    return r_values, se_values

def run_eggerr_regression(r_values: List[float], se_values: List[float]) -> Dict[str, Any]:
    """
    Perform Egger's linear regression test.
    
    Model: Z_i / SE_i = beta_0 + beta_1 * (1 / SE_i) + epsilon_i
    Where Z_i is the effect size (r) approximated as normal for large N,
    or we use the standard Egger's formulation: Effect / SE = Intercept + Slope * Precision.
    
    In Egger's test for correlation:
    Dependent variable (Y): r / SE
    Independent variable (X): 1 / SE (Precision)
    
    The intercept (beta_0) is the test statistic for asymmetry.
    
    Args:
        r_values: List of correlation coefficients.
        se_values: List of standard errors.
    
    Returns:
        Dictionary containing:
            - intercept: float
            - p_value: float
            - t_statistic: float
            - n_studies: int
    """
    if len(r_values) < 3:
        raise ValueError("Egger's regression requires at least 3 studies.")
    
    r_arr = np.array(r_values)
    se_arr = np.array(se_values)
    
    # Calculate dependent variable (Y) and independent variable (X)
    # Y = r / SE
    # X = 1 / SE (Precision)
    Y = r_arr / se_arr
    X = 1.0 / se_arr
    
    # Add intercept term for regression
    X_with_intercept = sm.add_constant(X)
    
    # Fit OLS model
    model = sm.OLS(Y, X_with_intercept)
    results = model.fit()
    
    intercept = results.params[0]
    p_value = results.pvalues[0]
    t_statistic = results.tvalues[0]
    
    return {
        "intercept": float(intercept),
        "p_value": float(p_value),
        "t_statistic": float(t_statistic),
        "n_studies": len(r_values)
    }

def run_bias_assessment() -> Dict[str, Any]:
    """
    Main entry point for bias assessment.
    
    Logic:
    1. Read N from data/processed/study_count.json.
    2. If N < 10, return a skipped status with the exact required reason string.
    3. If N >= 10, load effect sizes and perform Egger's regression.
    
    Returns:
        Dictionary to be saved as data/derived/bias_results.json.
    """
    # Step 1: Check Study Count
    try:
        N = load_study_count_from_json()
    except FileNotFoundError as e:
        return {
            "status": "error",
            "error": str(e),
            "egger_skipped_reason": "Skipped: Study count file missing"
        }
    
    # Step 2: Skip Logic
    if N < 10:
        return {
            "status": "skipped",
            "reason": "Insufficient studies",
            "N": N,
            "egger_skipped_reason": "Skipped: Insufficient studies (N < 10) for Egger's regression"
        }
    
    # Step 3: Load Data and Run Regression
    try:
        r_values, se_values = load_effect_sizes_and_se()
    except FileNotFoundError as e:
        return {
            "status": "error",
            "error": str(e),
            "egger_skipped_reason": "Skipped: Quantitative results file missing"
        }
    except ValueError as e:
        return {
            "status": "error",
            "error": str(e),
            "egger_skipped_reason": "Skipped: Invalid data in quantitative results"
        }
    
    # Step 4: Run Regression
    try:
        results = run_eggerr_regression(r_values, se_values)
        return {
            "status": "completed",
            "N": N,
            "egger_intercept": results["intercept"],
            "egger_p_value": results["p_value"],
            "egger_t_statistic": results["t_statistic"],
            "n_studies_analyzed": results["n_studies"]
        }
    except ValueError as e:
        return {
            "status": "error",
            "error": str(e),
            "egger_skipped_reason": f"Skipped: Regression failed - {str(e)}"
        }

def main() -> None:
    """
    Execute bias assessment and save results to data/derived/bias_results.json.
    """
    project_root = get_project_root()
    output_path = project_root / "data" / "derived" / "bias_results.json"
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"Starting Bias Assessment (T021)...")
    print(f"Project Root: {project_root}")
    
    try:
        result = run_bias_assessment()
        
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
        
        print(f"Bias assessment complete. Results saved to: {output_path}")
        print(f"Status: {result.get('status', 'unknown')}")
        
        if result.get("status") == "skipped":
            print(f"Reason: {result.get('egger_skipped_reason', 'Unknown reason')}")
        elif result.get("status") == "completed":
            print(f"Egger's Intercept: {result.get('egger_intercept')}")
            print(f"Egger's P-value: {result.get('egger_p_value')}")
        
    except Exception as e:
        print(f"Error during bias assessment: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()