"""
Heterogeneity analysis module for meta-analysis.
Calculates I² statistic and updates results JSON.
"""

import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# --- Path Utilities (Shared) ---

def get_project_root() -> Path:
    """Returns the project root directory (parent of 'code')."""
    return Path(__file__).resolve().parent.parent.parent

def load_study_count_from_json() -> int:
    """
    Loads the study count N from data/processed/study_count.json.
    Raises FileNotFoundError if the file is missing.
    """
    project_root = get_project_root()
    file_path = project_root / "data" / "processed" / "study_count.json"
    if not file_path.exists():
        raise FileNotFoundError(
            f"Missing study count file: {file_path}. "
            "Run T014a (study_counter.py) first."
        )
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if "N" not in data:
        raise ValueError(f"Missing 'N' key in {file_path}")
    return int(data["N"])

# --- Heterogeneity Logic ---

def load_effect_sizes_and_se() -> Tuple[List[float], List[float]]:
    """
    Loads effect sizes (r) and standard errors (se) from the meta-analysis results.
    Reads from data/derived/results.json (generated by T014).
    Returns a tuple of (effects, ses).
    """
    project_root = get_project_root()
    file_path = project_root / "data" / "derived" / "results.json"
    
    if not file_path.exists():
        # If meta-analysis hasn't run yet, try to load from the intermediate status
        # or raise a clear error. T014 is the prerequisite.
        raise FileNotFoundError(
            f"Missing meta-analysis results file: {file_path}. "
            "Run T014 (meta_analysis.py) first."
        )

    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # The results.json from T014 should contain a list of studies or aggregated data.
    # Assuming T014 outputs a structure where individual study effects are available
    # or we reconstruct them from the meta-analysis input if stored.
    # If T014 only stores the summary, we need to look for the input data used.
    # Based on standard meta-analysis pipelines, we expect 'studies' or 'data' key.
    
    studies = data.get("studies", [])
    if not studies:
        # Fallback: Check if raw data is embedded or if we need to load from extracted_studies.csv
        # However, the task description implies we calculate I2 from the meta-analysis inputs.
        # If T014 didn't save the individual list, we might need to read extracted_studies.csv.
        # Let's try to read from extracted_studies.csv as a fallback source for r and n.
        extracted_path = project_root / "data" / "processed" / "extracted_studies.csv"
        if not extracted_path.exists():
            raise FileNotFoundError(
                f"Neither {file_path} nor {extracted_path} found. "
                "Cannot calculate heterogeneity."
            )
        import csv
        effects = []
        ses = []
        with open(extracted_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row.get("r") and row.get("n"):
                    try:
                        r = float(row["r"])
                        n = int(row["n"])
                        # Standard error of r (approximate for large n)
                        # se_r = 1 / sqrt(n - 3) for Fisher's z, but for r directly:
                        # A common approximation for se of r is sqrt((1-r^2)/(n-2))
                        # But meta-analysis often uses Fisher's Z.
                        # Let's assume the task expects calculation based on r and n directly
                        # or that T014 stored the Z values.
                        # Given the constraint to use existing T014 output, if T014 output
                        # doesn't have the list, we calculate from extracted_studies.csv.
                        
                        # Calculate Fisher's Z
                        # Avoid log domain error
                        r_clipped = max(min(r, 0.9999), -0.9999)
                        z = 0.5 * math.log((1 + r_clipped) / (1 - r_clipped))
                        se_z = 1.0 / math.sqrt(n - 3)
                        
                        effects.append(z)
                        ses.append(se_z)
                    except (ValueError, ZeroDivisionError):
                        continue
        return effects, ses

    # If studies are present in results.json, extract them
    effects = []
    ses = []
    for study in studies:
        if "z_effect" in study and "se_z" in study:
            effects.append(study["z_effect"])
            ses.append(study["se_z"])
        elif "r" in study and "n" in study:
            try:
                r = float(study["r"])
                n = int(study["n"])
                r_clipped = max(min(r, 0.9999), -0.9999)
                z = 0.5 * math.log((1 + r_clipped) / (1 - r_clipped))
                se_z = 1.0 / math.sqrt(n - 3)
                effects.append(z)
                ses.append(se_z)
            except (ValueError, ZeroDivisionError):
                continue
    
    if not effects:
        raise ValueError("No valid effect sizes found in meta-analysis results or extracted studies.")

    return effects, ses

def calculate_i_squared(effects: List[float], ses: List[float]) -> float:
    """
    Calculates the I² statistic for heterogeneity.
    Formula: I² = max(0, (Q - df) / Q) * 100%
    where Q = sum(w_i * (y_i - y_bar)^2)
    w_i = 1 / se_i^2
    y_bar = sum(w_i * y_i) / sum(w_i)
    df = k - 1
    """
    if len(effects) < 3:
        # I² is not meaningful with < 3 studies, but we return 0.0 to avoid division by zero
        return 0.0

    k = len(effects)
    weights = [1.0 / (se ** 2) for se in ses]
    sum_weights = sum(weights)
    
    # Weighted mean
    weighted_sum = sum(w * e for w, e in zip(weights, effects))
    y_bar = weighted_sum / sum_weights

    # Q statistic
    Q = sum(w * (e - y_bar) ** 2 for w, e in zip(weights, effects))
    
    df = k - 1
    i_squared = (Q - df) / Q
    
    if i_squared < 0:
        i_squared = 0.0
    
    # Return as percentage, rounded to exactly two decimal places
    return round(i_squared * 100, 2)

def run_heterogeneity_analysis() -> Dict[str, Any]:
    """
    Runs the heterogeneity analysis and returns the result dictionary.
    """
    n = load_study_count_from_json()
    
    if n < 10:
        return {
            "status": "skipped",
            "reason": "Insufficient studies (N < 10)",
            "i_squared": None
        }

    try:
        effects, ses = load_effect_sizes_and_se()
        if len(effects) < 3:
            return {
                "status": "skipped",
                "reason": "Insufficient valid studies for I² calculation",
                "i_squared": None
            }
        
        i_squared = calculate_i_squared(effects, ses)
        
        return {
            "status": "completed",
            "i_squared": i_squared,
            "n_studies": len(effects)
        }
    except Exception as e:
        return {
            "status": "error",
            "reason": str(e),
            "i_squared": None
        }

def update_output_json(i_squared: Optional[float]) -> None:
    """
    Updates data/derived/results.json with the i_squared field.
    """
    project_root = get_project_root()
    results_path = project_root / "data" / "derived" / "results.json"
    
    if not results_path.exists():
        # Create a new file if it doesn't exist (though it should from T014)
        data = {"i_squared": i_squared}
    else:
        with open(results_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    
    data["i_squared"] = i_squared
    
    with open(results_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

def main() -> None:
    """
    Main entry point for the heterogeneity analysis task.
    """
    print("Running Heterogeneity Analysis (T021b)...")
    
    try:
        result = run_heterogeneity_analysis()
        
        if result["status"] == "completed":
            print(f"I² calculated: {result['i_squared']}%")
            update_output_json(result["i_squared"])
            print("Updated data/derived/results.json")
        elif result["status"] == "skipped":
            print(f"Heterogeneity analysis skipped: {result['reason']}")
            # Still update the results.json to reflect the skip if needed, 
            # or ensure i_squared is set to null/None.
            update_output_json(None)
        else:
            print(f"Heterogeneity analysis failed: {result['reason']}")
            sys.exit(1)
            
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()