"""
code/analysis/narrative.py

Implements the generation of a structured text summary (narrative_summary.md)
based on the output of the narrative engine (narrative_content.md) and the
narrative methodology configuration.

This task handles the specific case where the eligible study count is < 10,
producing a "Data Insufficient" or "Narrative Synthesis" report as required
by Constitution Principle VII.
"""

import json
import os
import csv
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Import utilities from sibling modules as per API surface
from utils.logger import get_logger
from utils.config import get_project_root, ensure_directory

logger = get_logger(__name__)


def load_methodology_config(config_path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Loads the narrative methodology configuration (YAML).
    Falls back to default paths if not provided.
    """
    if config_path is None:
        project_root = get_project_root()
        config_path = project_root / "data" / "config" / "narrative_methodology.yaml"

    if not config_path.exists():
        raise FileNotFoundError(f"Methodology config not found at {config_path}")

    # Simple YAML loader (assuming pyyaml is available as per requirements)
    import yaml
    with open(config_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def load_qualitative_notes(content_path: Optional[Path] = None) -> str:
    """
    Loads the content generated by the narrative engine (T015b).
    This is the source text for the summary.
    """
    if content_path is None:
        project_root = get_project_root()
        content_path = project_root / "data" / "derived" / "narrative_content.md"

    if not content_path.exists():
        raise FileNotFoundError(f"Narrative content not found at {content_path}. "
                                "Ensure T015b has run successfully.")

    with open(content_path, 'r', encoding='utf-8') as f:
        return f.read()


def load_study_count(count_path: Optional[Path] = None) -> int:
    """
    Loads the study count from the study_counter output.
    """
    if count_path is None:
        project_root = get_project_root()
        count_path = project_root / "data" / "processed" / "study_count.json"

    if not count_path.exists():
        raise FileNotFoundError(f"Study count file not found at {count_path}")

    with open(count_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        return int(data.get('N', 0))


def load_themes_json(themes_path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Loads the extracted themes JSON from T015a.
    """
    if themes_path is None:
        project_root = get_project_root()
        themes_path = project_root / "data" / "derived" / "narrative_themes.json"

    if not themes_path.exists():
        # If themes file is missing (e.g., N=0 case), return empty dict
        logger.warning(f"Themes file not found at {themes_path}. Returning empty themes.")
        return {}

    with open(themes_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def extract_themes(themes_data: Dict[str, Any], methodology: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Formats theme data for inclusion in the summary.
    """
    formatted_themes = []
    keywords = methodology.get('keywords', [])

    if not themes_data:
        return formatted_themes

    # Assume themes_data structure: {"theme_name": count, ...} or similar
    # We adapt based on what T015a produces.
    for theme, count in themes_data.items():
        if isinstance(count, dict):
            # Handle nested structures if T015a returns detailed stats
            formatted_themes.append({
                "name": theme,
                "count": count.get('count', 0),
                "details": count
            })
        else:
            formatted_themes.append({
                "name": theme,
                "count": count
            })

    return formatted_themes


def generate_overview(study_count: int, methodology: Dict[str, Any]) -> str:
    """
    Generates the 'Study Overview' section.
    """
    lines = [
        "## Study Overview",
        "",
        f"This report summarizes the findings from **{study_count}** eligible studies.",
        "",
        "### Methodology",
        "The analysis employed a qualitative synthesis approach due to insufficient sample size",
        "for quantitative meta-analysis (N < 10). Thematic coding was applied based on the",
        "following scheme:",
        ""
    ]

    keywords = methodology.get('keywords', [])
    if keywords:
        lines.append(f"- **Keywords**: {', '.join(keywords)}")

    sentiment_rules = methodology.get('sentiment_rules', {})
    if sentiment_rules:
        lines.append("- **Sentiment Rules**: Applied for directional analysis.")

    exclusion = methodology.get('exclusion_criteria', [])
    if exclusion:
        lines.append(f"- **Exclusion Criteria**: {', '.join(exclusion[:3])}...")

    lines.append("")
    return "\n".join(lines)


def generate_themes(formatted_themes: List[Dict[str, Any]], study_count: int) -> str:
    """
    Generates the 'Qualitative Themes' section.
    """
    lines = [
        "## Qualitative Themes",
        "",
        "The following themes were identified through the thematic coding of study descriptors:"
    ]

    if not formatted_themes or study_count == 0:
        lines.append("")
        lines.append("No qualitative themes could be extracted due to lack of data.")
        return "\n".join(lines)

    lines.append("")
    for theme in formatted_themes:
        name = theme.get('name', 'Unknown')
        count = theme.get('count', 0)
        lines.append(f"- **{name}**: Observed in {count} study(ies).")

    lines.append("")
    return "\n".join(lines)


def generate_limitations(study_count: int) -> str:
    """
    Generates the 'Limitations' section.
    """
    lines = [
        "## Limitations",
        "",
        f"**Data Insufficiency**: The analysis is based on {study_count} studies, which is below",
        "the threshold (N >= 10) required for robust quantitative meta-analysis.",
        "",
        "Consequently, statistical measures such as heterogeneity (I²) and publication bias",
        "(Egger's test) could not be reliably calculated.",
        "",
        "### Systematic Review Fallback",
        "In accordance with Constitution Principle VII, this report serves as a",
        "Systematic Review Fallback. The findings should be interpreted as preliminary",
        "and hypothesis-generating rather than conclusive.",
        ""
    ]
    return "\n".join(lines)


def generate_narrative_summary(study_count: int, content: str, themes: List[Dict[str, Any]], methodology: Dict[str, Any]) -> str:
    """
    Assembles the final markdown document.
    """
    timestamp = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

    # Handle Zero Studies Case explicitly
    if study_count == 0:
        header = "# No studies found"
        metadata = {
            "study_count": 0,
            "synthesis_mode": "narrative",
            "timestamp": None,
            "status": "Data Insufficient"
        }
        body = [
            "",
            "## Data Insufficient",
            "",
            "No studies were found to perform analysis.",
            "",
            "The pipeline has entered the 'Data Insufficient' fallback mode as mandated by",
            "Constitution Principle VII.",
            ""
        ]
        return f"{header}\n\n```json\n{json.dumps(metadata, indent=2)}\n```\n\n" + "\n".join(body)

    # Normal Case (N > 0, N < 10)
    header = "# Narrative Synthesis Summary"
    metadata_block = (
        f"```json\n"
        f"{{\n"
        f'  "study_count": {study_count},\n'
        f'  "synthesis_mode": "narrative",\n'
        f'  "timestamp": "{timestamp}"\n'
        f"}}\n"
        f"```\n"
    )

    overview = generate_overview(study_count, methodology)
    themes_section = generate_themes(themes, study_count)
    limitations = generate_limitations(study_count)

    # Combine sections
    # Note: We include the raw content from T015b as the main body of the review
    full_content = f"{header}\n\n{metadata_block}\n\n{overview}\n\n{themes_section}\n\n{limitations}\n\n{content}"

    return full_content


def main():
    """
    Entry point for T015c.
    Generates data/derived/narrative_summary.md
    """
    logger.info("Starting T015c: Narrative Summary Generation")

    try:
        # 1. Load Inputs
        # Determine paths relative to project root
        project_root = get_project_root()
        
        # Load methodology
        methodology_path = project_root / "data" / "config" / "narrative_methodology.yaml"
        methodology = load_methodology_config(methodology_path)
        
        # Load study count
        count_path = project_root / "data" / "processed" / "study_count.json"
        study_count = load_study_count(count_path)
        
        # Load content from T015b
        content_path = project_root / "data" / "derived" / "narrative_content.md"
        content = load_qualitative_notes(content_path)
        
        # Load themes from T015a (optional, but good for structure)
        themes_path = project_root / "data" / "derived" / "narrative_themes.json"
        themes_data = load_themes_json(themes_path)
        formatted_themes = extract_themes(themes_data, methodology)

        # 2. Generate Summary
        summary_md = generate_narrative_summary(study_count, content, formatted_themes, methodology)

        # 3. Write Output
        output_path = project_root / "data" / "derived" / "narrative_summary.md"
        ensure_directory(output_path)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(summary_md)
        
        logger.info(f"Successfully generated {output_path}")
        return 0

    except FileNotFoundError as e:
        logger.error(f"Missing required input file: {e}")
        return 1
    except Exception as e:
        logger.error(f"Error generating narrative summary: {e}")
        raise


if __name__ == "__main__":
    import sys
    sys.exit(main())