"""
Power Analysis Report Generator (Task T036b).

This script integrates the power analysis flags (generated by T036) into a
dedicated Markdown report and updates the main summary report.

It relies on the existence of:
- data/processed/power_flags.json (from T036)
- data/processed/metrics_summary.csv (from T026)
- data/processed/report_summary.txt (from T025d)

If any of these are missing, the script will fail loudly, as per the
project's "no silent fallback" policy.
"""

import os
import sys
import json
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List

# Add project root to path for imports if running as script
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from utils.logger import get_logger

logger = get_logger(__name__)

DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
POWER_FLAGS_FILE = DATA_PROCESSED_DIR / "power_flags.json"
METRICS_SUMMARY_FILE = DATA_PROCESSED_DIR / "metrics_summary.csv"
REPORT_SUMMARY_FILE = DATA_PROCESSED_DIR / "report_summary.txt"
POWER_REPORT_FILE = DATA_PROCESSED_DIR / "power_report.md"

def load_power_flags() -> List[Dict[str, Any]]:
    """Load power flags from JSON file. Fails loudly if file is missing."""
    if not POWER_FLAGS_FILE.exists():
        raise FileNotFoundError(
            f"Power flags file not found at {POWER_FLAGS_FILE}. "
            "Ensure T036 (PowerCalculator) has been executed successfully."
        )
    with open(POWER_FLAGS_FILE, 'r') as f:
        data = json.load(f)
    # Handle both list and dict with 'flags' key
    if isinstance(data, dict) and 'flags' in data:
        return data['flags']
    return data

def load_metrics_summary() -> pd.DataFrame:
    """Load metrics summary CSV. Fails loudly if file is missing."""
    if not METRICS_SUMMARY_FILE.exists():
        raise FileNotFoundError(
            f"Metrics summary file not found at {METRICS_SUMMARY_FILE}. "
            "Ensure T026 (generate_metrics_summary) has been executed."
        )
    return pd.read_csv(METRICS_SUMMARY_FILE)

def generate_power_report_md(power_flags: List[Dict[str, Any]], metrics_df: pd.DataFrame) -> str:
    """
    Generate a Markdown report summarizing the power analysis.

    Args:
        power_flags: List of power analysis results.
        metrics_df: DataFrame containing ANOVA results.

    Returns:
        Markdown string content.
    """
    lines = [
        "# Power Analysis Report",
        "",
        "This report details the statistical power of the conducted analyses.",
        "It is generated based on the Repeated Measures ANOVA results and sample sizes.",
        "",
        "## Methodology",
        "- **Test**: Repeated Measures ANOVA",
        "- **Alpha**: 0.05",
        "- **Effect Size**: Eta-squared (η²) derived from ANOVA",
        "- **Power Calculation**: Based on N, effect size, and alpha",
        "",
        "## Power Analysis Results",
        ""
    ]

    underpowered_count = 0
    ok_count = 0

    if not power_flags:
        lines.append("*No power flags were generated.*")
    else:
        lines.append("| Subgroup | N | Power | Flag | Status |")
        lines.append("| :--- | :--- | :--- | :--- | :--- |")

        for flag in power_flags:
            subgroup = flag.get('subgroup', 'Unknown')
            n = flag.get('N', 0)
            power = flag.get('power', 0.0)
            status = flag.get('flag', 'UNKNOWN')

            if status == 'UNDERPOWERED':
                underpowered_count += 1
                status_icon = "⚠️"
            elif status == 'OK':
                ok_count += 1
                status_icon = "✅"
            else:
                status_icon = "❓"

            lines.append(f"| {subgroup} | {n} | {power:.4f} | {status} | {status_icon} |")

    lines.extend([
        "",
        "## Summary",
        f"- **Total Subgroups Analyzed**: {len(power_flags)}",
        f"- **Adequately Powered (OK)**: {ok_count}",
        f"- **Underpowered**: {underpowered_count}",
        ""
    ])

    if underpowered_count > 0:
        lines.extend([
            "### ⚠️ Warning: Underpowered Study",
            "",
            "One or more subgroups have been flagged as **UNDERPOWERED**. ",
            "This means the study may lack the sensitivity to detect a true effect of the specified size. ",
            "Interpretation of non-significant results in these groups should be done with caution.",
            "",
            "Recommendation: Consider increasing the sample size (N) for future iterations of this study.",
            ""
        ])
    else:
        lines.extend([
            "### ✅ Study Power Status",
            "",
            "All analyzed subgroups have sufficient statistical power.",
            ""
        ])

    # Add reference to ANOVA results
    lines.extend([
        "## Reference: ANOVA Results",
        "",
        "For detailed F-statistics and p-values, please refer to `metrics_summary.csv`.",
        ""
    ])

    return "\n".join(lines)

def update_main_report(power_report_md: str) -> None:
    """
    Append the power analysis section to the main report_summary.txt.
    If report_summary.txt doesn't exist, create it with the power report content.
    """
    if not REPORT_SUMMARY_FILE.exists():
        logger.warning(f"Main report file {REPORT_SUMMARY_FILE} not found. Creating new file with power report.")
        with open(REPORT_SUMMARY_FILE, 'w') as f:
            f.write(power_report_md)
    else:
        # Read existing content
        with open(REPORT_SUMMARY_FILE, 'r') as f:
            existing_content = f.read()

        # Check if we already appended this (simple check)
        if "## Power Analysis Report" in existing_content:
            logger.info("Power analysis section already present in main report. Appending updated version.")
            # Find the start of the section to replace it
            start_idx = existing_content.find("## Power Analysis Report")
            if start_idx != -1:
                new_content = existing_content[:start_idx] + power_report_md
            else:
                new_content = existing_content + "\n\n" + power_report_md
        else:
            new_content = existing_content + "\n\n" + power_report_md

        with open(REPORT_SUMMARY_FILE, 'w') as f:
            f.write(new_content)

def main():
    """Main entry point for the power report generation."""
    try:
        logger.info("Starting Power Analysis Report Generation (T036b)...")

        # 1. Load dependencies
        logger.info(f"Loading power flags from {POWER_FLAGS_FILE}...")
        power_flags = load_power_flags()

        logger.info(f"Loading metrics summary from {METRICS_SUMMARY_FILE}...")
        metrics_df = load_metrics_summary()

        # 2. Generate report content
        logger.info("Generating Markdown report...")
        report_content = generate_power_report_md(power_flags, metrics_df)

        # 3. Write dedicated power report file
        logger.info(f"Writing dedicated report to {POWER_REPORT_FILE}...")
        with open(POWER_REPORT_FILE, 'w') as f:
            f.write(report_content)

        # 4. Update main report
        logger.info(f"Updating main report at {REPORT_SUMMARY_FILE}...")
        update_main_report(report_content)

        logger.info("Power Analysis Report Generation completed successfully.")
        return 0

    except FileNotFoundError as e:
        logger.error(f"Critical dependency missing: {e}")
        logger.error("The pipeline cannot proceed without the required data artifacts.")
        return 1
    except Exception as e:
        logger.error(f"An unexpected error occurred: {e}")
        import traceback
        logger.error(traceback.format_exc())
        return 1

if __name__ == "__main__":
    sys.exit(main())
