"""
Generate Power Analysis Report.

This module integrates the power analysis flags (generated by T036) into a
dedicated Markdown report and optionally updates the main report_summary.txt.

It ensures that the final report accurately reflects the statistical power
of the study, flagging any underpowered subgroups as required by the plan.
"""

import os
import sys
import json
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List

# Add project root to path if running as script
if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.parent
    sys.path.insert(0, str(project_root))

from utils.logger import get_logger

logger = get_logger(__name__)


def load_power_flags(power_flags_path: str) -> List[Dict[str, Any]]:
    """
    Load the power flags from the JSON file generated by T036.

    Args:
        power_flags_path: Path to power_flags.json

    Returns:
        List of dictionaries containing power analysis data.

    Raises:
        FileNotFoundError: If the power flags file does not exist.
        json.JSONDecodeError: If the file is not valid JSON.
    """
    if not os.path.exists(power_flags_path):
        raise FileNotFoundError(
            f"Power flags file not found at {power_flags_path}. "
            "Ensure T036 (PowerCalculator) has been executed successfully."
        )

    with open(power_flags_path, 'r') as f:
        data = json.load(f)

    # The file structure is expected to be a list of objects or a dict with a key
    # Based on T036 description: `{ "subgroup": "...", "N": ..., "power": ..., "flag": "..." }`
    # Assuming the JSON is a list of these objects.
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and 'flags' in data:
        return data['flags']
    else:
        # Treat the whole dict as a single entry or list of items if flattened
        return [data] if isinstance(data, dict) else []


def load_metrics_summary(metrics_summary_path: str) -> pd.DataFrame:
    """
    Load the metrics summary CSV generated by T026.

    Args:
        metrics_summary_path: Path to metrics_summary.csv

    Returns:
        DataFrame containing ANOVA results.
    """
    if not os.path.exists(metrics_summary_path):
        logger.warning(f"Metrics summary not found at {metrics_summary_path}. "
                       "Power report will be generated without ANOVA context.")
        return pd.DataFrame()

    return pd.read_csv(metrics_summary_path)


def generate_power_report_md(power_flags: List[Dict[str, Any]], output_path: str) -> None:
    """
    Generate a dedicated Markdown report for power analysis.

    Args:
        power_flags: List of power analysis flag dictionaries.
        output_path: Path to write the markdown report.
    """
    report_lines = [
        "# Power Analysis Report",
        "",
        "## Overview",
        "This report details the statistical power of the study based on the "
        "sample size (N) and effect sizes (eta-squared) derived from the Repeated Measures ANOVA.",
        "",
        "## Methodology",
        "- **Significance Level (α)**: 0.05",
        "- **Power Threshold**: 0.80",
        "- **Flagging Criteria**: Subgroups with N < 30 or Power < 0.80 are flagged as 'UNDERPOWERED'.",
        "",
        "## Power Analysis Results",
        ""
    ]

    if not power_flags:
        report_lines.append("No power data available. Ensure `data/processed/power_flags.json` exists.")
        report_lines.append("")
    else:
        # Create a table for the results
        report_lines.append("| Subgroup | Sample Size (N) | Estimated Power | Flag |")
        report_lines.append("| :--- | :---: | :---: | :--- |")

        underpowered_count = 0
        for entry in power_flags:
            subgroup = entry.get('subgroup', 'Unknown')
            n_val = entry.get('N', 0)
            power_val = entry.get('power', 0.0)
            flag = entry.get('flag', 'OK')

            if flag == 'UNDERPOWERED':
                underpowered_count += 1
                report_lines.append(f"| {subgroup} | {n_val} | {power_val:.4f} | ❌ **{flag}** |")
            else:
                report_lines.append(f"| {subgroup} | {n_val} | {power_val:.4f} | ✅ {flag} |")

        report_lines.append("")
        report_lines.append("## Interpretation")
        if underpowered_count > 0:
            report_lines.append(
                f"**Warning**: {underpowered_count} subgroup(s) are flagged as **UNDERPOWERED**. "
                "Results for these subgroups should be interpreted with caution. "
                "A larger sample size may be required to detect the observed effect sizes with sufficient power."
            )
        else:
            report_lines.append(
                "All analyzed subgroups appear to have sufficient statistical power (≥ 0.80) "
                "to detect the observed effect sizes."
            )

        report_lines.append("")
        report_lines.append("## Recommendations")
        if underpowered_count > 0:
            report_lines.append("- Consider increasing the sample size for future studies.")
            report_lines.append("- Report effect sizes with confidence intervals to contextualize the findings.")
        else:
            report_lines.append("- The current sample size is adequate for the reported effect sizes.")

    # Ensure directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write('\n'.join(report_lines))

    logger.info(f"Power analysis report written to {output_path}")


def update_main_report(power_report_path: str, main_report_path: str) -> None:
    """
    Append a reference to the power analysis report in the main report_summary.txt.

    Args:
        power_report_path: Path to the generated power report.
        main_report_path: Path to the main report_summary.txt.
    """
    if not os.path.exists(main_report_path):
        logger.warning(f"Main report not found at {main_report_path}. Skipping update.")
        return

    with open(main_report_path, 'r') as f:
        content = f.read()

    # Check if section already exists to avoid duplicates
    if "## Power Analysis" not in content:
        section_content = (
            "\n\n## Power Analysis\n"
            f"A detailed power analysis report has been generated and is available at: "
            f"`{os.path.basename(power_report_path)}`.\n"
            "Please refer to that document for subgroup-specific power estimates and recommendations.\n"
        )
        with open(main_report_path, 'a') as f:
            f.write(section_content)
        logger.info(f"Updated main report at {main_report_path} with power analysis reference.")
    else:
        logger.info("Power analysis section already exists in main report.")


def main():
    """Main entry point for the power report generation."""
    import argparse

    parser = argparse.ArgumentParser(description="Generate Power Analysis Report")
    parser.add_argument(
        "--power-flags",
        type=str,
        default="data/processed/power_flags.json",
        help="Path to the power flags JSON file (T036 output)."
    )
    parser.add_argument(
        "--metrics-summary",
        type=str,
        default="data/processed/metrics_summary.csv",
        help="Path to the metrics summary CSV (T026 output)."
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/processed/power_report.md",
        help="Output path for the power report Markdown file."
    )
    parser.add_argument(
        "--main-report",
        type=str,
        default="data/processed/report_summary.txt",
        help="Path to the main report to update."
    )

    args = parser.parse_args()

    try:
        logger.info("Starting Power Report Generation...")

        # Load data
        power_flags = load_power_flags(args.power_flags)
        # We load metrics summary to verify context, though not strictly needed for the table
        # if power_flags already contains the necessary stats.
        load_metrics_summary(args.metrics_summary)

        # Generate report
        generate_power_report_md(power_flags, args.output)

        # Update main report
        update_main_report(args.output, args.main_report)

        logger.info("Power Report Generation completed successfully.")

    except FileNotFoundError as e:
        logger.error(f"File not found: {e}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in power flags file: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Error generating power report: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()