import json
import os
from pathlib import Path
from typing import List, Dict, Any, Optional
import sys

from src.utils.checksums import (
    compute_file_sha256,
    load_checksums,
    save_checksums,
    update_checksum_for_file,
    ChecksumError
)
from src.utils.config import load_config, Config

class DataWriteError(Exception):
    """Raised when data writing or checksum registration fails."""
    pass

def write_dataset(data: List[Dict[str, Any]], output_path: Path) -> None:
    """
    Writes a list of dataset records to a JSON file.
    
    Args:
        data: List of dictionaries representing dataset records.
        output_path: Path where the JSON file will be saved.
    
    Raises:
        DataWriteError: If writing fails.
    """
    try:
        # Ensure directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except IOError as e:
        raise DataWriteError(f"Failed to write dataset to {output_path}: {e}")

def register_checksum(file_path: Path, checksums_path: Path) -> None:
    """
    Computes the SHA-256 checksum of a file and registers it in the checksums manifest.
    
    Args:
        file_path: Path to the file to checksum.
        checksums_path: Path to the checksums.json manifest.
    
    Raises:
        DataWriteError: If checksum computation or saving fails.
    """
    try:
        checksum = compute_file_sha256(file_path)
        update_checksum_for_file(str(file_path), checksum, checksums_path)
    except ChecksumError as e:
        raise DataWriteError(f"Failed to register checksum for {file_path}: {e}")

def generate_and_save_training_data(
    logic_data: List[Dict[str, Any]],
    grid_data: List[Dict[str, Any]],
    config: Config,
    output_dir: Optional[Path] = None
) -> List[Path]:
    """
    Generates training data files for logic and grid domains, saves them,
    and registers their checksums.
    
    Args:
        logic_data: List of logic proof records.
        grid_data: List of grid world records.
        config: Configuration object containing paths and settings.
        output_dir: Optional override for output directory. Defaults to config.data_dir.
    
    Returns:
        List of paths to the written files.
    
    Raises:
        DataWriteError: If writing or checksumming fails.
    """
    base_dir = output_dir or Path(config.data_dir)
    checksums_path = base_dir / "checksums.json"
    written_files = []

    # Ensure base directory exists
    base_dir.mkdir(parents=True, exist_ok=True)

    # Write Logic Dataset
    logic_path = base_dir / "logic_training.json"
    write_dataset(logic_data, logic_path)
    register_checksum(logic_path, checksums_path)
    written_files.append(logic_path)

    # Write Grid Dataset
    grid_path = base_dir / "grid_training.json"
    write_dataset(grid_data, grid_path)
    register_checksum(grid_path, checksums_path)
    written_files.append(grid_path)

    return written_files

def main() -> None:
    """
    CLI entry point for generating and saving training data.
    Expects config to be loaded from environment or default path.
    """
    try:
        config = load_config()
        
        # Note: In a real pipeline, data would be generated by the generators
        # before calling this writer. For this task, we assume data is passed
        # or generated here for demonstration of the writing logic.
        # However, per constraints, we must not fabricate data.
        # This script is designed to be called by the pipeline orchestration
        # (e.g., cli.py) which passes the generated data.
        
        # If called directly without data, it should fail loudly as per constraints
        # unless it's part of a larger flow. 
        # To satisfy the "write real output" constraint for a standalone run:
        # We will check if data files exist (from T011/T012) or raise error.
        
        # Since T011/T012 are marked as needing redo, we cannot rely on them
        # existing yet. But T014's job is the *writing logic*.
        # We will implement the logic to write IF data is provided via CLI args
        # or environment, otherwise we assume the caller (cli.py) provides it.
        
        # For the purpose of this task implementation:
        # The function `generate_and_save_training_data` is the core implementation.
        # The main() here will load config and prepare, but actual data generation
        # is assumed to be handled by the generators (T011/T012) before this is called.
        # If we must run this script standalone to produce files, we need data.
        # Given the constraints, we will assume this is a utility called by the pipeline.
        
        # To make this script runnable and produce output as per T014 requirement:
        # We will check for existing generated files from T011/T012 if they exist.
        # If not, we raise an error indicating data must be generated first.
        
        logic_path = Path(config.data_dir) / "logic_training.json"
        grid_path = Path(config.data_dir) / "grid_training.json"
        
        if not logic_path.exists() or not grid_path.exists():
            # In a real execution, we would call the generators here.
            # Since T011/T012 are pending, we simulate the call structure
            # but we cannot fabricate data.
            # We will attempt to import generators to run them if available.
            try:
                from src.generators.logic_generator import LogicProofGenerator
                from src.generators.grid_generator import GridWorldGenerator
                
                logic_gen = LogicProofGenerator(seed=config.seed)
                logic_data = logic_gen.generate(count=config.num_logic_proofs)
                
                grid_gen = GridWorldGenerator(seed=config.seed + 1)
                grid_data = grid_gen.generate(count=config.num_grid_worlds)
                
                generate_and_save_training_data(logic_data, grid_data, config)
                print(f"Successfully wrote training data and checksums to {config.data_dir}")
                
            except ImportError as e:
                raise DataWriteError(
                    f"Generators not available (T011/T012 pending): {e}. "
                    "Data generation must be completed before writing."
                )
        
    except DataWriteError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
