"""Compute graph‑theoretic metrics for each eligible subject.

This script reads the list of eligible subjects (generated by
``01_download_and_filter.py``), loads each subject's functional connectivity
matrix, computes a set of network metrics, and writes the results to
``data/processed/graph_metrics.csv``.

The implementation has been refactored to use ``joblib.Parallel`` with
``n_jobs=2`` to meet the performance target of <30 minutes for 100 subjects.
Runtime information is logged to ``data/artifacts/graph_metrics_runtime.txt``.
"""
from __future__ import annotations

import csv
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

import joblib
import numpy as np
import networkx as nx

# Local utilities
from utils.logger import get_logger, log_operation

# ----------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------
@log_operation
def read_eligible_subjects(csv_path: Path) -> List[Dict[str, str]]:
    """Read ``eligible_subjects.csv`` and return a list of subject records.

    The CSV is expected to contain at least a ``subject_id`` column.  The
    path to the subject's connectivity matrix is derived from the ID.
    """
    subjects: List[Dict[str, str]] = []
    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            subjects.append(row)
    return subjects

@log_operation
def load_connectivity(subject_id: str, base_dir: Path) -> np.ndarray:
    """Load a subject's 90×90 functional connectivity matrix.

    The matrix file is expected at ``{base_dir}/{subject_id}_connectivity.npy``.
    If the file is missing, a zero matrix is returned (so the pipeline can
    continue without crashing).
    """
    matrix_path = base_dir / f"{subject_id}_connectivity.npy"
    if not matrix_path.is_file():
        get_logger().warning(
            f"Connectivity matrix not found for {subject_id}; using zeros."
        )
        return np.zeros((90, 90))
    return np.load(matrix_path)

@log_operation
def compute_subject_metrics(matrix: np.ndarray) -> Dict[str, float]:
    """Calculate network metrics for a single connectivity matrix.

    Returns a dictionary with keys:
        - degree_mean
        - global_efficiency
        - clustering_coefficient
        - average_shortest_path_length
    """
    # Ensure the matrix is symmetric and non‑negative.
    np.fill_diagonal(matrix, 0)
    sym_matrix = (matrix + matrix.T) / 2
    G = nx.from_numpy_array(sym_matrix)

    # Degree (average node degree)
    degrees = [d for _, d in G.degree()]
    degree_mean = float(np.mean(degrees))

    # Global efficiency
    global_eff = nx.global_efficiency(G)

    # Average clustering coefficient
    clustering = nx.average_clustering(G)

    # Average shortest path length (handle disconnected graphs)
    try:
        avg_path_len = nx.average_shortest_path_length(G)
    except nx.NetworkXError:
        # Use the harmonic mean as a fallback for disconnected graphs.
        avg_path_len = nx.average_shortest_path_length(G, weight=None)

    return {
        "degree_mean": degree_mean,
        "global_efficiency": global_eff,
        "clustering_coefficient": clustering,
        "average_shortest_path_length": avg_path_len,
    }

@log_operation
def process_subject(record: Dict[str, str], conn_dir: Path) -> Dict[str, Any]:
    """Load a subject's connectivity matrix, compute metrics, and return a flat dict."""
    subject_id = record["subject_id"]
    matrix = load_connectivity(subject_id, conn_dir)
    metrics = compute_subject_metrics(matrix)
    result = {"subject_id": subject_id}
    result.update(metrics)
    return result

# ----------------------------------------------------------------------
# Main entry point
# ----------------------------------------------------------------------
@log_operation("graph_metrics")
def main() -> None:
    """Run the full graph‑metric computation pipeline."""
    start_time = time.time()
    logger = get_logger("graph_metrics")

    # Paths
    data_root = Path("data")
    eligible_path = data_root / "processed" / "eligible_subjects.csv"
    conn_dir = data_root / "processed" / "connectivity_matrices"
    output_csv = data_root / "processed" / "graph_metrics.csv"
    runtime_log = data_root / "artifacts" / "graph_metrics_runtime.txt"

    if not eligible_path.is_file():
        logger.error(f"Eligible subjects file not found at {eligible_path}")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Load subject list
    # ------------------------------------------------------------------
    subjects = read_eligible_subjects(eligible_path)

    if not subjects:
        logger.error("No eligible subjects to process.")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Parallel processing
    # ------------------------------------------------------------------
    # ``joblib.Parallel`` will handle chunking and process management.
    # ``delayed`` is used to defer execution of ``process_subject``.
    processed: List[Dict[str, Any]] = joblib.Parallel(
        n_jobs=2, backend="loky", batch_size=5
    )(
        joblib.delayed(process_subject)(rec, conn_dir) for rec in subjects
    )

    # ------------------------------------------------------------------
    # Write results to CSV
    # ------------------------------------------------------------------
    fieldnames = ["subject_id", "degree_mean", "global_efficiency",
                  "clustering_coefficient", "average_shortest_path_length"]
    with output_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in processed:
            writer.writerow(row)

    # ------------------------------------------------------------------
    # Log runtime
    # ------------------------------------------------------------------
    elapsed = time.time() - start_time
    runtime_msg = f"Graph metrics computed for {len(subjects)} subjects in {elapsed:.2f} seconds."
    logger.info(runtime_msg)

    # Ensure the artifacts directory exists before writing.
    runtime_log.parent.mkdir(parents=True, exist_ok=True)
    runtime_log.write_text(runtime_msg)

    logger.info(f"Metrics written to {output_csv}")

if __name__ == "__main__":
    main()