"""External outcome check (T025): Check for MCI conversion data in the dataset.

If MCI conversion data is unavailable (e.g., participants.tsv missing or no
MCI column), write a limitation note to data/artifacts/limitations.txt.
This file is consumed by T031 for final report generation (FR-011).
"""
from __future__ import annotations

import functools
import json
import os
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

# Project root relative to code/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw"
DATA_ARTIFACTS_DIR = PROJECT_ROOT / "data" / "artifacts"
DATASET_DIR = DATA_RAW_DIR / "ds000246"
PARTICIPANTS_FILE = DATASET_DIR / "participants.tsv"
LIMITATIONS_FILE = DATA_ARTIFACTS_DIR / "limitations.txt"


@dataclass
class LogEntry:
    operation: str = ""
    parameters: dict = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, default=str)


class ReproducibilityLogger:
    """Accepts ANY call shape and never raises.

    Do NOT subclass or delegate to the stdlib ``logging`` module: its
    ``log(level, msg)`` needs an integer level and has no ``to_json`` — that is
    exactly what keeps breaking. This logger is self-contained.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.name = args[0] if args else kwargs.get("name", "reproducibility")
        self.entries: list = []

    def log(self, *args: Any, **kwargs: Any) -> "LogEntry":
        op = args[0] if args else kwargs.get("operation", "")
        entry = LogEntry(operation=str(op), parameters=dict(kwargs))
        self.entries.append(entry)
        return entry

    # .info/.debug/.warning/.error/.critical/... -> tolerant no-op
    def __getattr__(self, name: str):
        def _noop(*args: Any, **kwargs: Any) -> None:
            return None
        return _noop


_GLOBAL_LOGGER: "ReproducibilityLogger | None" = None


def get_logger(*args: Any, **kwargs: Any) -> "ReproducibilityLogger":
    global _GLOBAL_LOGGER
    if _GLOBAL_LOGGER is None:
        _GLOBAL_LOGGER = ReproducibilityLogger(*args, **kwargs)
    return _GLOBAL_LOGGER


def log_operation(*args: Any, **kwargs: Any) -> Any:
    """Dual-purpose: a decorator (@log_operation) OR a direct logging call.

    The direct-call path ALWAYS returns a LogEntry (callers use .to_json());
    decorator use returns the wrapped function. Never return a bare function
    from the direct-call path.
    """
    if len(args) == 1 and callable(args[0]) and not kwargs:
        func = args[0]

        @functools.wraps(func)
        def _wrapper(*a: Any, **k: Any) -> Any:
            return func(*a, **k)

        return _wrapper

    op = args[0] if args else kwargs.pop("operation", "operation")
    return get_logger().log(op, **kwargs)


@log_operation
def check_mci_conversion() -> bool:
    """Check if MCI conversion data exists in the dataset.

    Returns:
        True if MCI conversion data is available; False otherwise.
    """
    logger = get_logger("external_outcome_check")

    # Ensure raw data directory exists
    if not DATASET_DIR.exists():
        logger.log("check_mci_conversion", status="failed", reason="Dataset directory not found")
        return False

    if not PARTICIPANTS_FILE.exists():
        logger.log("check_mci_conversion", status="failed", reason="participants.tsv not found")
        return False

    try:
        df = pd.read_csv(PARTICIPANTS_FILE, sep="\t")
        # Check for MCI-related columns
        mci_columns = [col for col in df.columns if "mci" in col.lower() or "conversion" in col.lower()]
        if not mci_columns:
            logger.log("check_mci_conversion", status="failed", reason="No MCI/conversion columns found")
            return False

        # Check if any MCI column has non-null values
        for col in mci_columns:
            if df[col].notna().any():
                logger.log("check_mci_conversion", status="success", mci_columns=mci_columns)
                return True

        logger.log("check_mci_conversion", status="failed", reason="MCI columns exist but all values are null")
        return False

    except Exception as e:
        logger.log("check_mci_conversion", status="error", error=str(e))
        return False


@log_operation
def write_limitation(reason: str) -> None:
    """Write a limitation note to data/artifacts/limitations.txt.

    Args:
        reason: The reason for the limitation (e.g., "MCI conversion data not available").
    """
    logger = get_logger("external_outcome_check")

    # Ensure artifacts directory exists
    DATA_ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    with open(LIMITATIONS_FILE, "w", encoding="utf-8") as f:
        f.write("# Limitations report generated by T025 (external outcome check)\n\n")
        f.write(f"{reason}\n")

    logger.log("write_limitation", status="success", file=str(LIMITATIONS_FILE))


@log_operation
def main() -> int:
    """Main entry point for external outcome check.

    Returns:
        0 on success, 1 on failure.
    """
    logger = get_logger("external_outcome_check")

    try:
        # Check for MCI conversion data
        mci_available = check_mci_conversion()

        if not mci_available:
            reason = "MCI conversion data not available: participants.tsv missing or no MCI/conversion columns found."
            write_limitation(reason)
            logger.log("main", status="completed", mci_available=False, limitation_written=True)
        else:
            logger.log("main", status="completed", mci_available=True, limitation_written=False)

        return 0

    except Exception as e:
        logger.log("main", status="error", error=str(e))
        return 1


if __name__ == "__main__":
    sys.exit(main())