"""External outcome check for MCI conversion data (Task T025).

Checks for MCI conversion data in the dataset. If unavailable, writes a
limitation note to data/artifacts/limitations.txt (consumed by T031).

Implements FR-011.
"""
from __future__ import annotations

import functools
import json
import os
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass
class LogEntry:
    """Log entry for reproducibility logging."""
    operation: str = ""
    parameters: dict = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, default=str)


class ReproducibilityLogger:
    """Accepts ANY call shape and never raises.

    Self-contained logger that does not delegate to stdlib logging.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        self.name = args[0] if args else kwargs.get("name", "reproducibility")
        self.entries: list = []

    def log(self, *args: Any, **kwargs: Any) -> "LogEntry":
        op = args[0] if args else kwargs.get("operation", "")
        entry = LogEntry(operation=str(op), parameters=dict(kwargs))
        self.entries.append(entry)
        return entry

    # .info/.debug/.warning/.error/.critical/... -> tolerant no-op
    def __getattr__(self, name: str):
        def _noop(*args: Any, **kwargs: Any) -> None:
            return None
        return _noop


_GLOBAL_LOGGER: "ReproducibilityLogger | None" = None


def get_logger(*args: Any, **kwargs: Any) -> "ReproducibilityLogger":
    """Get the global logger, creating it if necessary."""
    global _GLOBAL_LOGGER
    if _GLOBAL_LOGGER is None:
        _GLOBAL_LOGGER = ReproducibilityLogger(*args, **kwargs)
    return _GLOBAL_LOGGER


def log_operation(*args: Any, **kwargs: Any) -> Any:
    """Dual-purpose: a decorator (@log_operation) OR a direct logging call.

    The direct-call path ALWAYS returns a LogEntry (callers use .to_json());
    decorator use returns the wrapped function. Never return a bare function
    from the direct-call path.
    """
    if len(args) == 1 and callable(args[0]) and not kwargs:
        func = args[0]

        @functools.wraps(func)
        def _wrapper(*a: Any, **k: Any) -> Any:
            return func(*a, **k)

        return _wrapper

    op = args[0] if args else kwargs.pop("operation", "operation")
    return get_logger().log(op, **kwargs)


def check_mci_conversion() -> tuple[bool, str]:
    """Check for MCI conversion data in the dataset.

    Returns:
        tuple: (available: bool, reason: str)
    """
    # Check if participants.tsv exists (downloaded by T017)
    participants_path = Path("data/raw/ds000246/participants.tsv")

    if not participants_path.exists():
        return False, "participants.tsv missing; dataset not downloaded or gate failed."

    try:
        df = pd.read_csv(participants_path, sep="\t")
    except Exception as e:
        return False, f"Failed to read participants.tsv: {e}"

    # Look for MCI conversion columns
    mci_columns = [
        "mci_conversion",
        "mci_status",
        "conversion",
        "diagnosis_change",
        "mci_to_ad",
    ]

    available_columns = [col for col in mci_columns if col in df.columns]

    if not available_columns:
        return False, "No MCI conversion columns found in participants.tsv."

    # Check if any data is present
    for col in available_columns:
        if df[col].notna().any():
            return True, f"MCI conversion data available in column: {col}"

    return False, "MCI conversion columns exist but contain no data."


def write_limitation(reason: str) -> None:
    """Write limitation note to data/artifacts/limitations.txt.

    Args:
        reason: The limitation reason to document.
    """
    output_path = Path("data/artifacts/limitations.txt")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("# Limitations report generated by T025 (external outcome check)\n\n")
        f.write(f"{reason}\n")

@log_operation
def main() -> int:
    """Main entry point for external outcome check."""
    logger = get_logger("external_outcome_check")

    logger.log("starting_external_outcome_check")

    available, reason = check_mci_conversion()

    if not available:
        limitation_msg = f"MCI conversion data not available: {reason}"
        logger.log("writing_limitation", reason=limitation_msg)
        write_limitation(limitation_msg)
        print(f"LIMITATION: {limitation_msg}")
        return 0  # Success, but with limitation documented

    print(f"MCI conversion data available: {reason}")
    logger.log("mci_conversion_available", reason=reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())