"""
Reporting module for the Visual Crowding Impact Study.

Generates the final associational analysis report based on GLMM results,
ensuring findings are framed as associational rather than causal (FR-006).
"""
import os
import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional

# Import from project modules using the exact API surface provided
from analysis.glmm_model import load_prepared_data, extract_results, apply_fdr_correction
from config import get_seed, set_all_seeds, ensure_directories, get_env_config

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_regression_results(results_path: Path) -> Dict[str, Any]:
    """
    Load regression results from the JSON file generated by T038.
    
    Args:
        results_path: Path to regression_results.json
        
    Returns:
        Dictionary containing model coefficients, confidence intervals, and p-values
    """
    if not results_path.exists():
        raise FileNotFoundError(f"Regression results file not found: {results_path}")
    
    with open(results_path, 'r') as f:
        return json.load(f)

def load_model_config(config_path: Path) -> Dict[str, Any]:
    """
    Load model configuration from YAML file.
    
    Args:
        config_path: Path to model_config.yaml
        
    Returns:
        Dictionary containing hyperparameters, seeds, and diagnostics
    """
    import yaml
    
    if not config_path.exists():
        raise FileNotFoundError(f"Model config file not found: {config_path}")
    
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def format_statistical_result(coef: float, se: float, p_value: float, fdr_corrected: bool = False) -> str:
    """
    Format a statistical result for the report.
    
    Args:
        coef: Coefficient value
        se: Standard error
        p_value: P-value
        fdr_corrected: Whether FDR correction was applied
        
    Returns:
        Formatted string representation
    """
    fdr_note = " (FDR-corrected)" if fdr_corrected else ""
    significance = "***" if p_value < 0.001 else "**" if p_value < 0.01 else "*" if p_value < 0.05 else ""
    
    return f"β = {coef:.4f}, SE = {se:.4f}, p = {p_value:.4f}{significance}{fdr_note}"

def generate_associational_caveat() -> str:
    """
    Generate the standard associational caveat text for the report.
    
    Returns:
        String containing the associational framing statement
    """
    return """
    IMPORTANT NOTE ON INTERPRETATION:
    
    This analysis employs a Generalized Linear Mixed Model (GLMM) to examine 
    associations between visual clutter metrics and facial emotion recognition 
    accuracy. While the model controls for participant-level and stimulus-level 
    random effects, the findings should be interpreted as ASSOCIATIONAL rather 
    than CAUSAL.
    
    Limitations:
    - Observational nature of the analysis (even with synthetic pilot data)
    - Potential unmeasured confounding variables
    - Correlation does not imply causation
    
    Future experimental work with controlled manipulations would be required 
    to establish causal mechanisms.
    """

def generate_executive_summary(results: Dict[str, Any], config: Dict[str, Any]) -> str:
    """
    Generate an executive summary of the findings.
    
    Args:
        results: Regression results dictionary
        config: Model configuration dictionary
        
    Returns:
        Formatted executive summary string
    """
    fixed_effects = results.get('fixed_effects', [])
    
    # Find key predictors
    clutter_effect = next((fe for fe in fixed_effects if 'clutter' in fe.get('term', '').lower()), None)
    flanker_effect = next((fe for fe in fixed_effects if 'flanker' in fe.get('term', '').lower()), None)
    
    summary_lines = [
        "EXECUTIVE SUMMARY",
        "=" * 50,
        "",
        "This study investigated the relationship between visual clutter metrics and",
        "facial emotion recognition accuracy using a Generalized Linear Mixed Model.",
        "",
        "Key Findings:",
    ]
    
    if clutter_effect:
        summary_lines.append(
            f"  - Visual clutter showed a {('negative' if clutter_effect['estimate'] < 0 else 'positive')} "
            f"association with recognition accuracy: "
            f"{format_statistical_result(clutter_effect['estimate'], clutter_effect['std_error'], clutter_effect['p_value'], clutter_effect.get('fdr_corrected', False))}"
        )
    
    if flanker_effect:
        summary_lines.append(
            f"  - Flanker count showed a {('negative' if flanker_effect['estimate'] < 0 else 'positive')} "
            f"association with recognition accuracy: "
            f"{format_statistical_result(flanker_effect['estimate'], flanker_effect['std_error'], flanker_effect['p_value'], flanker_effect.get('fdr_corrected', False))}"
        )
    
    summary_lines.extend([
        "",
        "Model Diagnostics:",
        f"  - Convergence status: {results.get('convergence_status', 'Unknown')}",
        f"  - Random effects: Participant and Stimulus ID",
        f"  - FDR correction applied: {results.get('fdr_applied', False)}",
        "",
        "See the full report below for detailed statistical results.",
        generate_associational_caveat()
    ])
    
    return "\n".join(summary_lines)

def generate_detailed_results(results: Dict[str, Any]) -> str:
    """
    Generate detailed statistical results section.
    
    Args:
        results: Regression results dictionary
        
    Returns:
        Formatted detailed results string
    """
    lines = [
        "DETAILED STATISTICAL RESULTS",
        "=" * 50,
        "",
        "Fixed Effects:",
        "-" * 30,
        f"{'Term':<30} {'Estimate':>12} {'SE':>12} {'95% CI':>20} {'p-value':>12} {'FDR-corr':>10}",
        "-" * 96
    ]
    
    for effect in results.get('fixed_effects', []):
        term = effect.get('term', 'Unknown')
        estimate = effect.get('estimate', 0)
        se = effect.get('std_error', 0)
        ci_low = effect.get('conf_int_low', 0)
        ci_high = effect.get('conf_int_high', 0)
        p_val = effect.get('p_value', 1.0)
        fdr = effect.get('fdr_corrected', False)
        
        ci_str = f"[{ci_low:.4f}, {ci_high:.4f}]"
        fdr_str = "Yes" if fdr else "No"
        
        lines.append(
            f"{term:<30} {estimate:>12.4f} {se:>12.4f} {ci_str:>20} {p_val:>12.4f} {fdr_str:>10}"
        )
    
    lines.extend([
        "",
        "Random Effects Variance Components:",
        "-" * 30
    ])
    
    for re_name, re_data in results.get('random_effects', {}).items():
        variance = re_data.get('variance', 0)
        sd = re_data.get('std_dev', 0)
        lines.append(f"  {re_name}: Variance = {variance:.4f}, SD = {sd:.4f}")
    
    lines.extend([
        "",
        "Model Fit Statistics:",
        "-" * 30,
        f"  AIC: {results.get('aic', 'N/A')}",
        f"  BIC: {results.get('bic', 'N/A')}",
        f"  Log-Likelihood: {results.get('log_likelihood', 'N/A')}",
        f"  Number of Observations: {results.get('n_obs', 'N/A')}",
        f"  Number of Groups (Participants): {results.get('n_participants', 'N/A')}",
        f"  Number of Groups (Stimuli): {results.get('n_stimuli', 'N/A')}",
    ])
    
    return "\n".join(lines)

def generate_report(results_path: Path, config_path: Path, output_path: Path) -> None:
    """
    Generate the complete associational analysis report.
    
    Args:
        results_path: Path to regression_results.json
        config_path: Path to model_config.yaml
        output_path: Path for the output report file
    """
    logger.info(f"Loading regression results from {results_path}")
    results = load_regression_results(results_path)
    
    logger.info(f"Loading model configuration from {config_path}")
    config = load_model_config(config_path)
    
    # Generate report sections
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_content = [
        "=" * 70,
        "VISUAL CROWDING IMPACT ON FACIAL EMOTION RECOGNITION",
        "Associational Analysis Report",
        f"Generated: {timestamp}",
        "=" * 70,
        "",
        "1. STUDY OVERVIEW",
        "-" * 70,
        "This report presents the findings from a Generalized Linear Mixed Model (GLMM)",
        "analysis examining the relationship between visual clutter metrics and facial",
        "emotion recognition accuracy. The analysis uses synthetic pilot data generated",
        "to simulate human observer responses under varying crowding conditions.",
        "",
        "2. METHODOLOGY",
        "-" * 70,
        f"  - Model Type: Binomial GLMM with logit link",
        f"  - Fixed Effects: Visual clutter metrics, flanker count, eccentricity",
        f"  - Random Effects: Participant ID, Stimulus ID",
        f"  - FDR Correction: {'Applied' if results.get('fdr_applied', False) else 'Not applied'}",
        f"  - Random Seed: {config.get('random_seed', 'N/A')}",
        "",
        generate_executive_summary(results, config),
        "",
        generate_detailed_results(results),
        "",
        "3. LIMITATIONS AND FUTURE DIRECTIONS",
        "-" * 70,
        "  - Synthetic data limitations: While statistically valid, synthetic pilot",
        "    data may not capture all nuances of human observer behavior.",
        "  - Associational nature: Findings indicate correlations but do not establish",
        "    causal mechanisms without experimental manipulation.",
        "  - Generalizability: Results are specific to the RAVDESS dataset and",
        "    the generated stimulus parameters.",
        "",
        "4. RECOMMENDATIONS",
        "-" * 70,
        "  - Conduct empirical studies with human participants to validate findings",
        "  - Explore additional clutter metrics and their individual contributions",
        "  - Investigate interaction effects between emotion categories and crowding",
        "  - Consider longitudinal designs to assess stability of effects",
        "",
        "=" * 70,
        "END OF REPORT",
        "=" * 70
    ]
    
    # Write report to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("\n".join(report_content))
    
    logger.info(f"Report successfully generated: {output_path}")

def main():
    """Main entry point for the reporting script."""
    parser = argparse.ArgumentParser(
        description='Generate final associational analysis report for visual crowding study'
    )
    parser.add_argument(
        '--results',
        type=Path,
        default=Path('data/processed/regression_results.json'),
        help='Path to regression results JSON file'
    )
    parser.add_argument(
        '--config',
        type=Path,
        default=Path('artifacts/model_config.yaml'),
        help='Path to model configuration YAML file'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('artifacts/associational_analysis_report.txt'),
        help='Path for output report file'
    )
    parser.add_argument(
        '--seed',
        type=int,
        default=None,
        help='Random seed for reproducibility'
    )
    
    args = parser.parse_args()
    
    # Set random seed if provided
    if args.seed is not None:
        set_all_seeds(args.seed)
    
    # Ensure output directory exists
    ensure_directories([args.output.parent])
    
    try:
        generate_report(args.results, args.config, args.output)
        logger.info("Report generation completed successfully")
    except FileNotFoundError as e:
        logger.error(f"Required input file not found: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Error generating report: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()