"""
Contract tests for feature engineering logic, specifically focusing on
the calculation of the residual error term R(n) and its handling of edge cases.
"""
import os
import math
import csv
import tempfile
import pytest
import numpy as np

# Import the functions we are testing from the feature engineering module
# Note: We assume the module is in the parent directory of tests/
import sys
import pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / 'code'))

from feature_engineering import load_partition_data, compute_features, get_prime_sieve_and_primes

# Path to the reference values generated by T008
REFERENCE_PATH = "tests/data/reference_values.csv"
# Path to the raw partitions data generated by T011 (if it exists)
RAW_PARTITIONS_PATH = "data/raw/partitions_raw.csv"

class TestResidualCalculation:
    """Tests for R(n) = log(p_P(n)) - log(Q_as(n)) calculation."""

    def test_log_zero_handling(self):
        """
        Verify that R(n) calculation handles log(0) gracefully.
        According to the spec, rows where p_P(n) <= 0 or Q_as(n) <= 0
        should be excluded from the output. This test verifies that
        the feature engineering logic explicitly excludes such rows
        rather than crashing on math domain errors.
        """
        # Create a temporary CSV with a row that would cause log(0)
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['n', 'p_P(n)', 'Q_as(n)'])
            # Valid row
            writer.writerow([10, 2, 1.5])
            # Row with p_P(n) = 0 (should be excluded)
            writer.writerow([1, 0, 0.1])
            # Row with Q_as(n) = 0 (should be excluded)
            writer.writerow([2, 1, 0.0])
            temp_path = f.name

        try:
            # Load the data
            n_values, p_p_n_values, q_as_n_values = load_partition_data(temp_path)

            # Verify that the invalid rows were excluded
            # We expect only the row for n=10
            assert len(n_values) == 1
            assert n_values[0] == 10
            assert p_p_n_values[0] == 2
            assert q_as_n_values[0] == 1.5

            # Verify that no math domain error occurred during loading/validation
            # The exclusion logic should prevent log(0) in the feature computation
        finally:
            os.unlink(temp_path)

    def test_residual_matches_expected_values(self):
        """
        Verify that R(n) calculation matches expected values for sample n.
        We use the reference values from T008 for small n to compute expected R(n).
        """
        if not os.path.exists(REFERENCE_PATH):
            pytest.skip(f"Reference file {REFERENCE_PATH} not found. T008 must be completed first.")

        # Load reference values
        reference_data = {}
        with open(REFERENCE_PATH, 'r', newline='') as f:
            reader = csv.DictReader(f)
            for row in reader:
                n = int(row['n'])
                p_p_n = int(row['p_P(n)'])
                reference_data[n] = p_p_n

        # We need Q_as(n) values. Since we don't have the full raw file yet,
        # we will simulate a small dataset with known Q_as values for testing.
        # In a real integration test, this would use data from T011.
        test_cases = [
            # (n, p_P(n), Q_as(n), expected_R)
            (10, 2, 1.5, math.log(2) - math.log(1.5)),
            (20, 5, 4.2, math.log(5) - math.log(4.2)),
            (50, 20, 18.5, math.log(20) - math.log(18.5)),
        ]

        for n, p_p, q_as, expected_r in test_cases:
            # Calculate R(n)
            r_n = math.log(p_p) - math.log(q_as)
            assert math.isclose(r_n, expected_r, rel_tol=1e-9), \
                f"R({n}) mismatch: got {r_n}, expected {expected_r}"

    def test_edge_cases_excluded(self):
        """
        Verify that rows with n < 5 are excluded from feature output.
        The spec states: "Explicitly exclude rows where n < 5 or p_P(n) <= 0".
        """
        # Create a temporary CSV with edge cases
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['n', 'p_P(n)', 'Q_as(n)'])
            # Edge case: n < 5
            writer.writerow([1, 0, 0.1])
            writer.writerow([2, 0, 0.1])
            writer.writerow([3, 0, 0.1])
            writer.writerow([4, 0, 0.1])
            # Valid case: n >= 5
            writer.writerow([5, 1, 0.9])
            writer.writerow([6, 1, 1.0])
            temp_path = f.name

        try:
            # Load the data
            n_values, p_p_n_values, q_as_n_values = load_partition_data(temp_path)

            # Verify that n < 5 rows were excluded
            assert all(n >= 5 for n in n_values), "Rows with n < 5 should be excluded"
            assert len(n_values) == 2  # Only n=5 and n=6
            assert n_values[0] == 5
            assert n_values[1] == 6

        finally:
            os.unlink(temp_path)

    def test_prime_gap_feature_calculation(self):
        """
        Verify that 'prime_gap_size' and 'distance_to_nearest_prime' are calculated correctly.
        """
        if not os.path.exists(REFERENCE_PATH):
            pytest.skip(f"Reference file {REFERENCE_PATH} not found.")

        # Create a minimal test dataset
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['n', 'p_P(n)', 'Q_as(n)'])
            # n=6 (composite, between 5 and 7)
            writer.writerow([6, 1, 1.0])
            # n=7 (prime, next prime is 11)
            writer.writerow([7, 1, 1.1])
            # n=10 (composite, between 7 and 11)
            writer.writerow([10, 2, 1.9])
            temp_path = f.name

        try:
            n_values, p_p_n_values, q_as_n_values = load_partition_data(temp_path)
            sieve, primes = get_prime_sieve_and_primes(max(n_values) + 20)

            # Test n=6 (composite)
            # Previous prime: 5, Next prime: 7
            # distance_to_nearest_prime = min(|6-5|, |6-7|) = 1
            # prime_gap_size = 7 - 5 = 2
            n = 6
            idx = n_values.index(n)
            features = compute_features(n_values[idx], p_p_n_values[idx], q_as_n_values[idx], sieve, primes)
            assert features['distance_to_nearest_prime'] == 1, f"Expected 1 for n=6, got {features['distance_to_nearest_prime']}"
            assert features['prime_gap_size'] == 2, f"Expected 2 for n=6, got {features['prime_gap_size']}"

            # Test n=7 (prime)
            # Previous prime: 5, Next prime: 11
            # distance_to_nearest_prime = min(|7-5|, |7-11|) = 2
            # prime_gap_size = 11 - 7 = 4 (gap initiated by n)
            n = 7
            idx = n_values.index(n)
            features = compute_features(n_values[idx], p_p_n_values[idx], q_as_n_values[idx], sieve, primes)
            assert features['distance_to_nearest_prime'] == 2, f"Expected 2 for n=7, got {features['distance_to_nearest_prime']}"
            assert features['prime_gap_size'] == 4, f"Expected 4 for n=7, got {features['prime_gap_size']}"

            # Test n=10 (composite)
            # Previous prime: 7, Next prime: 11
            # distance_to_nearest_prime = min(|10-7|, |10-11|) = 1
            # prime_gap_size = 11 - 7 = 4
            n = 10
            idx = n_values.index(n)
            features = compute_features(n_values[idx], p_p_n_values[idx], q_as_n_values[idx], sieve, primes)
            assert features['distance_to_nearest_prime'] == 1, f"Expected 1 for n=10, got {features['distance_to_nearest_prime']}"
            assert features['prime_gap_size'] == 4, f"Expected 4 for n=10, got {features['prime_gap_size']}"

        finally:
            os.unlink(temp_path)

    def test_oscillatory_features(self):
        """
        Verify that oscillatory features sin(log(n)) and cos(log(n)) are computed correctly.
        """
        test_n = 10
        expected_sin = math.sin(math.log(test_n))
        expected_cos = math.cos(math.log(test_n))

        # Create a minimal test dataset
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['n', 'p_P(n)', 'Q_as(n)'])
            writer.writerow([test_n, 2, 1.5])
            temp_path = f.name

        try:
            n_values, p_p_n_values, q_as_n_values = load_partition_data(temp_path)
            sieve, primes = get_prime_sieve_and_primes(test_n + 10)

            features = compute_features(n_values[0], p_p_n_values[0], q_as_n_values[0], sieve, primes)

            assert math.isclose(features['sin_log_n'], expected_sin, rel_tol=1e-9), \
                f"sin(log({test_n})) mismatch"
            assert math.isclose(features['cos_log_n'], expected_cos, rel_tol=1e-9), \
                f"cos(log({test_n})) mismatch"

        finally:
            os.unlink(temp_path)

    def test_feature_columns_present(self):
        """
        Verify that all required feature columns are present in the output.
        """
        required_columns = [
            'n', 'p_P(n)', 'Q_as(n)', 'R(n)',
            'pi_n', 'inv_ln_n', 'distance_to_nearest_prime', 'prime_gap_size',
            'sin_log_n', 'cos_log_n'
        ]

        # Create a minimal test dataset
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.csv', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['n', 'p_P(n)', 'Q_as(n)'])
            writer.writerow([10, 2, 1.5])
            temp_path = f.name

        try:
            n_values, p_p_n_values, q_as_n_values = load_partition_data(temp_path)
            sieve, primes = get_prime_sieve_and_primes(20)

            features = compute_features(n_values[0], p_p_n_values[0], q_as_n_values[0], sieve, primes)

            for col in required_columns:
                assert col in features, f"Missing required column: {col}"

        finally:
            os.unlink(temp_path)