"""
Contract test for T009: Verify p_P(n) matches reference values for n in [1, 100].

This test loads the ground truth reference values generated by T008 and compares
them against the output of the partition logic in generate_partitions.py.
It ensures the distinct prime partition counts are mathematically correct for
the small range where exact values are known.
"""
import os
import sys
import csv
import unittest
from pathlib import Path

# Add the project root to the path to allow imports from code/
# Assuming this file is at tests/test_partition_logic.py
project_root = Path(__file__).resolve().parent.parent
code_dir = project_root / "code"

if str(code_dir) not in sys.path:
    sys.path.insert(0, str(code_dir))

from generate_partitions import load_reference_values, validate_against_reference, compute_partition_counts

class TestPartitionLogicContract(unittest.TestCase):
    """
    Contract tests for the integer partition logic into distinct primes.
    """

    def setUp(self):
        """
        Set up test fixtures.
        """
        self.project_root = project_root
        self.reference_path = self.project_root / "tests" / "data" / "reference_values.csv"
        
        # Ensure the reference file exists (generated by T008)
        self.assertTrue(
            self.reference_path.exists(),
            f"Reference file {self.reference_path} not found. "
            "Ensure T008 (generate_reference.py) has been executed successfully."
        )

    def test_reference_file_loads(self):
        """
        Verify that the reference values can be loaded without error.
        """
        try:
            ref_data = load_reference_values(str(self.reference_path))
            self.assertIsInstance(ref_data, dict)
            self.assertGreater(len(ref_data), 0, "Reference data is empty.")
        except Exception as e:
            self.fail(f"Failed to load reference values: {e}")

    def test_reference_range_coverage(self):
        """
        Verify the reference file covers the required range n in [1, 100].
        """
        ref_data = load_reference_values(str(self.reference_path))
        required_keys = set(range(1, 101))
        actual_keys = set(int(k) for k in ref_data.keys())
        
        missing = required_keys - actual_keys
        self.assertEqual(
            len(missing), 0,
            f"Reference file missing values for n in: {sorted(missing)}"
        )

    def test_partition_counts_match_reference(self):
        """
        Contract test: Compute p_P(n) for n in [1, 100] and verify exact match
        against tests/data/reference_values.csv.
        
        This is the core requirement of T009.
        """
        # Load ground truth
        expected = load_reference_values(str(self.reference_path))
        
        # Compute actual values for the range [1, 100]
        # We use the compute_partition_counts function which implements the DP.
        # We pass n_max=100 to limit computation to the contract range.
        computed = compute_partition_counts(100)
        
        # Validate against reference
        mismatches = []
        for n in range(1, 101):
            n_str = str(n)
            if n_str not in expected:
                mismatches.append(f"n={n}: Reference missing")
                continue
            
            exp_val = int(expected[n_str])
            comp_val = int(computed[n_str])
            
            if exp_val != comp_val:
                mismatches.append(
                    f"n={n}: Expected {exp_val}, got {comp_val}"
                )

        self.assertEqual(
            len(mismatches), 0,
            f"Partition counts do not match reference values:\n" + "\n".join(mismatches)
        )

    def test_validate_against_reference_helper(self):
        """
        Test the validate_against_reference helper function directly.
        """
        computed = compute_partition_counts(100)
        # The helper expects a path to the reference file
        is_valid, details = validate_against_reference(computed, str(self.reference_path))
        
        self.assertTrue(is_valid, f"Validation failed: {details}")

if __name__ == '__main__':
    unittest.main()