import os
import csv
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
from scripts.baseline_runner import ExecutionResult, run_baseline_task
import ast
import sys

def load_baseline_results(baseline_results_path: str) -> Dict[str, ExecutionResult]:
    """Load baseline execution results from a JSON file."""
    if not os.path.exists(baseline_results_path):
        return {}
    with open(baseline_results_path, 'r') as f:
        data = json.load(f)
        return {k: ExecutionResult(**v) for k, v in data.items()}

def load_ingested_tasks(ingested_csv_path: str) -> List[Dict[str, Any]]:
    """Load ingested tasks from the CSV generated by ingest.py."""
    tasks = []
    with open(ingested_csv_path, 'r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            tasks.append(row)
    return tasks

def process_unparseable_tasks(tasks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Identify tasks that cannot be parsed by Python's AST (syntax errors).
    Flag them as 'Unparseable' and return the list with the new status.
    
    This function implements the core logic for T016:
    1. Attempts to parse the 'original_code' or 'code_diff' using ast.parse.
    2. If it fails (SyntaxError), marks the task status as 'Unparseable'.
    3. Returns the modified list so subsequent steps can skip tree-sitter.
    """
    parsed_tasks = []
    for task in tasks:
        task_id = task.get('task_id', 'unknown')
        code_content = task.get('original_code') or task.get('code_diff')
        
        is_unparseable = False
        parse_error = None

        if code_content:
            try:
                # Attempt to parse the code
                ast.parse(code_content)
            except SyntaxError as e:
                is_unparseable = True
                parse_error = str(e)
            except Exception as e:
                # Catch other potential parsing issues
                is_unparseable = True
                parse_error = str(e)
        else:
            # If no code content exists, treat as unparseable
            is_unparseable = True
            parse_error = "No code content found"

        if is_unparseable:
            task['dynamic_execution_outcome'] = 'Unparseable'
            task['parse_error'] = parse_error
            # We retain the row but mark it as Unparseable so T019/T020 can skip it
            # The baseline runner likely didn't run or failed for these, 
            # so we explicitly set the outcome here.
        else:
            # If not unparseable, we rely on baseline runner results for outcome
            # If baseline results are missing for a valid task, we might default to 'Pending'
            # but for this step, we just ensure valid tasks aren't marked Unparseable.
            if 'dynamic_execution_outcome' not in task or task['dynamic_execution_outcome'] is None:
                task['dynamic_execution_outcome'] = 'Pending'

        parsed_tasks.append(task)
    
    return parsed_tasks

def generate_ground_truth(
    ingested_csv_path: str,
    baseline_results_path: str,
    output_csv_path: str
) -> None:
    """
    Main function to generate ground_truth.csv.
    
    1. Loads ingested tasks.
    2. Processes unparseable tasks (T016 logic).
    3. Merges baseline execution results (T012/T013 logic).
    4. Writes the final CSV with 'Unparseable' flags.
    """
    tasks = load_ingested_tasks(ingested_csv_path)
    baseline_results = load_baseline_results(baseline_results_path)

    # Step 1: Handle Syntax Errors (T016)
    tasks = process_unparseable_tasks(tasks)

    # Step 2: Merge Baseline Results for parseable tasks
    for task in tasks:
        task_id = task.get('task_id')
        if task_id and task_id in baseline_results:
            result = baseline_results[task_id]
            # Only update if the task wasn't already marked Unparseable
            # (Unparseable tasks shouldn't have a successful baseline run anyway)
            if task.get('dynamic_execution_outcome') != 'Unparseable':
                task['dynamic_execution_outcome'] = result.outcome
                if result.timeout:
                    task['dynamic_execution_outcome'] = 'Timeout'
                elif result.error:
                    # If there was an error but not a timeout, it's a Fail
                    if task['dynamic_execution_outcome'] != 'Timeout':
                        task['dynamic_execution_outcome'] = 'Fail'

    # Ensure output directory exists
    output_path = Path(output_csv_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to CSV
    fieldnames = ['task_id', 'code_diff', 'original_code', 'dynamic_execution_outcome', 'parse_error']
    with open(output_csv_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        for task in tasks:
            writer.writerow(task)

def main():
    """Entry point for generating ground truth."""
    # Default paths relative to project root
    base_dir = Path(__file__).resolve().parent.parent.parent
    ingested_path = base_dir / 'data' / 'raw' / 'merged_dataset.csv'
    baseline_path = base_dir / 'data' / 'raw' / 'baseline_results.json'
    output_path = base_dir / 'data' / 'processed' / 'ground_truth.csv'

    # Allow override via args
    if len(sys.argv) > 1:
        ingested_path = Path(sys.argv[1])
    if len(sys.argv) > 2:
        baseline_path = Path(sys.argv[2])
    if len(sys.argv) > 3:
        output_path = Path(sys.argv[3])

    if not ingested_path.exists():
        print(f"Error: Ingested CSV not found at {ingested_path}")
        sys.exit(1)

    print(f"Generating ground truth from {ingested_path}...")
    generate_ground_truth(str(ingested_path), str(baseline_path), str(output_path))
    print(f"Ground truth written to {output_path}")

if __name__ == '__main__':
    main()
