import os
import sys
import json
import requests
from pathlib import Path
from typing import Dict, Any

# Attempt to import datasets for streaming
try:
    from datasets import load_dataset
except ImportError:
    raise ImportError("The 'datasets' package is required. Install it via pip install datasets.")

class DataUnavailableError(Exception):
    """Raised when a required dataset cannot be fetched from the real source."""
    pass

def ensure_directories(output_path: str):
    """Ensure the output directory exists."""
    path = Path(output_path)
    path.mkdir(parents=True, exist_ok=True)
    return path

def verify_url_status(url: str) -> bool:
    """Verify that a URL returns a 200 OK status."""
    try:
        response = requests.head(url, timeout=10)
        return response.status_code == 200
    except requests.RequestException:
        return False

def load_verification_report() -> Dict[str, Any]:
    """Load the download status report generated by T012a."""
    report_path = Path("data/download_status.json")
    if not report_path.exists():
        raise FileNotFoundError("Verification report not found. Run T012 first.")
    
    with open(report_path, 'r') as f:
        return json.load(f)

def save_manifest(manifest: Dict[str, Any], output_path: str):
    """Save the dataset manifest to disk."""
    with open(output_path, 'w') as f:
        json.dump(manifest, f, indent=2)

def download_recipe1m_streaming(output_dir: str):
    """
    Stream the Recipe1M dataset from HuggingFace and save it as a Parquet file.
    This implements T013a: Stream & Validate Recipe1M.
    
    Constraint: If T012a failed for Recipe1M, this function must fail loudly.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    final_file = output_path / "recipe1m_raw.parquet"

    # Check T012a status
    status = load_verification_report()
    if status.get("recipe1m") != "SUCCESS":
        raise DataUnavailableError(
            "Recipe1M download status is not SUCCESS in T012a report. "
            "The task specification states: 'If T012a failed for Recipe1M, fail the pipeline (no proxy for Recipe1M itself).' "
            "Failing loudly as required."
        )

    print("Streaming Recipe1M dataset from HuggingFace...")
    # Using the verified real source: HuggingFace Datasets
    # Dataset name: 'marianna123/recipe1m' (or similar verified source)
    # We stream to avoid OOM, then write to parquet in chunks or as a whole if it fits
    # Given the constraint of ~7GB RAM, we will stream and write incrementally if possible,
    # or load a manageable slice if the full stream is too heavy for the runner without chunking.
    # However, Parquet writers often need the whole schema. We will stream, collect a sample
    # if full is too big, or try to write in batches if the library supports it.
    # For strict adherence to "Stream the full... or downsampled subset if T012a failed",
    # and since T012a passed, we attempt the full stream.
    
    # NOTE: Recipe1M is large. We will use streaming=True.
    # To write to parquet efficiently without loading everything into RAM,
    # we will iterate and use pyarrow directly or pandas with chunked writing if supported.
    # For simplicity and robustness in this environment, we will stream and write to a single parquet file.
    # If the dataset is too large for a single pass in this environment, we might need to downsample.
    # But the instruction says "Stream the full...". We attempt it.
    
    try:
        dataset = load_dataset("marianna123/recipe1m", split="train", streaming=True)
        
        # We need to convert the streaming dataset to a format writable to parquet.
        # Since we cannot load the whole thing into memory, we will write row by row or in batches.
        # Pandas to_parquet doesn't support appending easily. We will use pyarrow.
        import pyarrow as pa
        import pyarrow.parquet as pq

        # Define schema based on expected fields or infer from first batch
        writer = None
        batch_count = 0
        total_rows = 0

        for batch in dataset:
            # Convert batch to pyarrow table
            table = pa.Table.from_pydict(batch)
            
            if writer is None:
                writer = pq.ParquetWriter(str(final_file), table.schema)
            
            writer.write_table(table)
            total_rows += len(batch[list(batch.keys())[0]])
            batch_count += 1
            
            if batch_count % 100 == 0:
                print(f"Processed {batch_count} batches, {total_rows} rows...")

        if writer:
            writer.close()
            print(f"Successfully wrote {total_rows} rows to {final_file}")
        
        # Verification
        if not final_file.exists():
            raise FileNotFoundError(f"Output file {final_file} was not created.")
        
        # Basic schema check (T007 compliance)
        # We check if the file is readable and has columns
        pf = pq.read_table(str(final_file), columns=[0]).to_pandas() # Read first column to check
        if pf.empty:
            raise ValueError("Dataset appears to be empty.")
        
        return True

    except Exception as e:
        # If streaming fails for any reason (network, size), we fail loudly.
        # No synthetic fallback.
        raise DataUnavailableError(f"Failed to stream Recipe1M: {str(e)}")

def download_datasets():
    """Main entry point for downloading datasets."""
    # This function is called by the CLI
    output_dir = "data/raw"
    ensure_directories(output_dir)
    
    # Only Recipe1M is handled here for T013a
    success = download_recipe1m_streaming(output_dir)
    
    if success:
        print("Recipe1M download and streaming completed successfully.")
    else:
        raise DataUnavailableError("Recipe1M download failed.")

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Download and stream Recipe1M dataset.")
    parser.add_argument("--dataset", type=str, default="recipe1m", help="Dataset to download")
    parser.add_argument("--output", type=str, default="data/raw", help="Output directory")
    args = parser.parse_args()

    if args.dataset == "recipe1m":
        download_recipe1m_streaming(args.output)
    else:
        print(f"Dataset {args.dataset} not supported in this task.")
        sys.exit(1)

if __name__ == "__main__":
    main()
