#!/bin/bash
# Wrapper script to run commands within the llmxive cgroup memory limit
# This script is generated by setup_limits.sh and should not be edited manually.
#
# Usage:
#   ./scripts/run_with_cgroup.sh [command] [args...]

set -euo pipefail

CGROUP_NAME="llmxive_limit"
CGROUP_PATH="/sys/fs/cgroup/memory/${CGROUP_NAME}"

if [[ ! -d "${CGROUP_PATH}" ]]; then
    echo "ERROR: Cgroup ${CGROUP_NAME} not found."
    echo "Please run scripts/setup_limits.sh first to create the cgroup."
    exit 1
fi

# Move current process to the cgroup
# Note: This requires the cgroup to be set up with proper permissions
if ! echo $$ > "${CGROUP_PATH}/cgroup.procs" 2>/dev/null; then
    echo "WARNING: Could not move process to cgroup. Running without cgroup constraints."
    echo "This may happen if the script is not run with sufficient privileges."
fi

# Execute the command with all arguments
exec "$@"