import os
import sys
import csv
import random
from pathlib import Path
from typing import List, Dict, Any
from datasets import load_dataset
from config import Config

# Set random seed for reproducibility
random.seed(42)

def fetch_diverse_prompts() -> List[Dict[str, Any]]:
    """
    Fetches a diverse set of text prompts from the 'nlpconnect/vit-gpt2-image-captioning'
    dataset on HuggingFace. This dataset contains captions for images from the COCO dataset,
    providing a rich source of diverse text prompts.

    Returns:
        List[Dict[str, Any]]: A list of dictionaries, each containing 'prompt' and 'source'.
    """
    print("Loading diverse prompts from HuggingFace dataset 'nlpconnect/vit-gpt2-image-captioning'...")
    try:
        # Load the dataset with streaming=False to cache locally
        dataset = load_dataset("nlpconnect/vit-gpt2-image-captioning", split="train", streaming=False)
    except Exception as e:
        raise RuntimeError(f"Failed to load dataset 'nlpconnect/vit-gpt2-image-captioning': {e}")

    prompts = []
    count = 0
    # Iterate through the dataset to extract captions
    # The dataset typically has a 'caption' field
    for item in dataset:
        if 'caption' in item and item['caption']:
            prompts.append({
                'prompt': item['caption'],
                'source': 'nlpconnect/vit-gpt2-image-captioning'
            })
            count += 1
            if count >= 5000: # Limit to a reasonable size for this task
                break

    if not prompts:
        raise ValueError("No prompts found in the dataset. Check dataset structure.")

    print(f"Successfully fetched {len(prompts)} diverse prompts.")
    return prompts

def load_coco_captions(config: Config) -> List[Dict[str, Any]]:
    """
    Loads captions from the previously processed MS-COCO data (generated by T006a/b).
    This function assumes data/processed/prompts_test.csv exists.

    Args:
        config: The project configuration object.

    Returns:
        List[Dict[str, Any]]: A list of dictionaries with 'prompt' and 'source'.
    """
    coco_file = config.data_path / "processed" / "prompts_test.csv"
    if not coco_file.exists():
        raise FileNotFoundError(f"COCO captions file not found at {coco_file}. "
                                "Please run T006b first to generate this file.")

    prompts = []
    with open(coco_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if 'caption' in row and row['caption']:
                prompts.append({
                    'prompt': row['caption'],
                    'source': 'ms-coco-validation'
                })
    print(f"Loaded {len(prompts)} captions from MS-COCO.")
    return prompts

def merge_and_deduplicate(coco_prompts: List[Dict], diverse_prompts: List[Dict]) -> List[Dict[str, Any]]:
    """
    Merges the two prompt lists and removes exact duplicates based on the 'prompt' text.

    Args:
        coco_prompts: List of prompts from COCO.
        diverse_prompts: List of prompts from the diverse source.

    Returns:
        List[Dict[str, Any]]: A deduplicated list of prompts.
    """
    seen = set()
    merged = []
    for p in diverse_prompts + coco_prompts:
        text = p['prompt'].strip().lower()
        if text not in seen:
            seen.add(text)
            merged.append(p)
    print(f"Merged and deduplicated prompts: {len(merged)} unique entries.")
    return merged

def write_merged_csv(prompts: List[Dict[str, Any]], output_path: Path) -> None:
    """
    Writes the merged list of prompts to a CSV file.

    Args:
        prompts: The list of prompt dictionaries.
        output_path: The path where the CSV will be saved.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['prompt', 'source'])
        writer.writeheader()
        for p in prompts:
            # Escape newlines in prompts to ensure valid CSV
            clean_prompt = p['prompt'].replace('\n', ' ').replace('\r', ' ')
            writer.writerow({'prompt': clean_prompt, 'source': p['source']})
    print(f"Successfully wrote {len(prompts)} prompts to {output_path}")

def main():
    """
    Main entry point for T006d.
    1. Fetches diverse prompts from HuggingFace.
    2. Loads existing COCO test prompts.
    3. Merges and deduplicates.
    4. Writes to data/processed/diverse_prompts.csv.
    """
    config = Config()
    output_path = config.data_path / "processed" / "diverse_prompts.csv"

    print(f"Starting T006d: Generating diverse prompts file at {output_path}")

    # 1. Fetch diverse prompts
    diverse_prompts = fetch_diverse_prompts()

    # 2. Load COCO prompts
    coco_prompts = load_coco_captions(config)

    # 3. Merge and deduplicate
    final_prompts = merge_and_deduplicate(coco_prompts, diverse_prompts)

    # 4. Write output
    write_merged_csv(final_prompts, output_path)

    print("T006d completed successfully.")

if __name__ == "__main__":
    main()
