"""
Reproducibility verification script for llmXive pipeline.

This script verifies that the data generation process is deterministic by:
1. Running the generator twice with the same seed from Config.
2. Computing SHA256 checksums of the generated CSV files.
3. Comparing the checksums to ensure they are identical.
4. Failing (exiting with code 1) if checksums differ, which will fail CI.

Usage:
    python code/utils/reproducibility_check.py
"""

import os
import sys
import hashlib
import tempfile
import shutil
from pathlib import Path
from typing import List, Tuple, Optional

# Adjust imports to match project structure
# Assuming this file is run from the project root or via python -m
try:
    from config import Config
    from utils.logger import get_logger
except ImportError:
    # Fallback for direct execution if sys.path isn't set up correctly
    # In a real CI environment, the project root should be in sys.path
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from config import Config
    from utils.logger import get_logger

logger = get_logger("reproducibility_check")

# Define the expected output files based on T016/T017
# These must match the paths generated by the data generation script
EXPECTED_OUTPUTS = [
    "data/raw/high_entropy.csv",
    "data/raw/low_entropy.csv",
    "data/raw/target_specific.csv",
    "data/raw/test_set.csv"
]

# The generator script path (T016 implementation)
# We assume the main generator is at code/generators/generate_data.py
# or similar. Since T011-T016 are not yet implemented, we need to
# import the logic or run the script.
# Given the task description "runs the generator twice", we assume
# there is a script entry point.
# Since T011-T016 are not completed yet, we cannot run the real generator.
# However, the task T041 is to ADD the verification script.
# The script must be runnable. If the generator doesn't exist yet,
# we should handle that gracefully or assume the generator will be
# implemented as part of the pipeline.
#
# CRITICAL: The task says "runs the generator twice".
# If the generator script (T016) is not yet implemented, this script
# will fail. But T041 is in Phase 2 (Foundational), while T011-T016 are Phase 3.
# This implies T041 might be a dependency for Phase 3 or a check that runs
# after Phase 3.
#
# Re-reading the task: "Add reproducibility verification script ... that runs the generator twice"
# If the generator doesn't exist, we can't run it.
# However, the task is to IMPLEMENT T041.
# The script must be valid Python.
# We will assume the generator script exists at `code/generators/generate_data.py`
# or similar. If it doesn't, the script will raise an error, which is appropriate
# for a CI step that fails if dependencies are missing.
#
# Let's assume the generator entry point is `code/generators/run_generator.py`
# or we call a function from `code/generators/logic_generator.py`.
# Since T011 is "Implement propositional logic problem generator function",
# the full pipeline script might be `code/generators/generate_all.py`.
#
# To make this robust, we will look for a script that produces the EXPECTED_OUTPUTS.
# We will assume the script is `code/generators/generate_dataset.py`.
GENERATOR_SCRIPT = "code/generators/generate_dataset.py"

def compute_sha256(file_path: str) -> str:
    """Compute SHA256 checksum of a file."""
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def run_generator_and_collect_checksums(seed: int, output_dir: str) -> Tuple[bool, List[Tuple[str, str]]]:
    """
    Runs the generator script with the given seed and collects checksums of output files.

    Args:
        seed: The random seed to use.
        output_dir: Directory where the generator should write outputs.

    Returns:
        Tuple of (success, list of (filename, checksum) tuples)
    """
    # Create a temporary directory for this run to avoid conflicts
    temp_run_dir = tempfile.mkdtemp()
    try:
        # We need to ensure the generator writes to our expected paths relative to project root
        # But since we are running twice, we need to capture the outputs.
        # The generator is expected to write to `data/raw/` relative to project root.
        # We will run the generator, which writes to the project's `data/raw/`.
        # Then we compute checksums.
        # But we need to run it twice and compare.
        # So we run it, save checksums, run it again, compare.

        # However, the generator writes to fixed paths.
        # We can't easily change the output directory of the generator without modifying it.
        # So we assume the generator writes to `data/raw/` in the project root.
        # We will run it, compute checksums, then run it again and compare.

        # But wait, if we run it twice, the second run will overwrite the first.
        # So we need to compute checksums after each run and compare.

        # Let's assume the generator script takes a seed argument.
        # We will run: python code/generators/generate_dataset.py --seed {seed}

        # Check if generator script exists
        if not os.path.exists(GENERATOR_SCRIPT):
            logger.error(f"Generator script not found: {GENERATOR_SCRIPT}")
            return False, []

        # Run the generator
        import subprocess
        cmd = [sys.executable, GENERATOR_SCRIPT, "--seed", str(seed)]
        logger.info(f"Running generator: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            logger.error(f"Generator failed: {result.stderr}")
            return False, []

        # Compute checksums of expected outputs
        checksums = []
        for expected_file in EXPECTED_OUTPUTS:
            full_path = os.path.join(output_dir, expected_file)
            if not os.path.exists(full_path):
                logger.error(f"Expected output file not found: {full_path}")
                return False, []
            checksum = compute_sha256(full_path)
            checksums.append((expected_file, checksum))

        return True, checksums

    finally:
        # Clean up temp directory if created (though we didn't use it for outputs)
        shutil.rmtree(temp_run_dir, ignore_errors=True)

def main():
    """Main entry point for reproducibility check."""
    logger.info("Starting reproducibility verification...")

    # Get seed from Config
    config = Config()
    seed = config.seed
    logger.info(f"Using seed from Config: {seed}")

    # Get project root (assuming this script is at code/utils/reproducibility_check.py)
    project_root = Path(__file__).parent.parent.parent
    os.chdir(project_root)
    logger.info(f"Working directory: {project_root}")

    # Run generator first time
    logger.info("Running generator (first pass)...")
    success1, checksums1 = run_generator_and_collect_checksums(seed, str(project_root))
    if not success1:
        logger.error("First generator run failed or outputs missing.")
        sys.exit(1)

    # Run generator second time
    logger.info("Running generator (second pass)...")
    success2, checksums2 = run_generator_and_collect_checksums(seed, str(project_root))
    if not success2:
        logger.error("Second generator run failed or outputs missing.")
        sys.exit(1)

    # Compare checksums
    logger.info("Comparing checksums...")
    if len(checksums1) != len(checksums2):
        logger.error("Mismatch in number of output files.")
        sys.exit(1)

    all_match = True
    for (file1, hash1), (file2, hash2) in zip(checksums1, checksums2):
        if file1 != file2:
            logger.error(f"File order mismatch: {file1} vs {file2}")
            all_match = False
        if hash1 != hash2:
            logger.error(f"Checksum mismatch for {file1}: {hash1} vs {hash2}")
            all_match = False
        else:
            logger.info(f"Match for {file1}: {hash1}")

    if all_match:
        logger.info("Reproducibility check PASSED. All checksums match.")
        sys.exit(0)
    else:
        logger.error("Reproducibility check FAILED. Checksums do not match.")
        sys.exit(1)

if __name__ == "__main__":
    main()
