"""
HTML Fetcher Module for A/B Test Audit Pipeline.

This module implements robust HTML fetching with retry logic, timeout handling,
and persistence to the data/raw/ directory. It depends on T018 (ingestor)
which provides the list of URLs to process.
"""
import hashlib
import time
import logging
import os
from pathlib import Path
from typing import List, Tuple, Optional
import requests
from requests.exceptions import RequestException, Timeout, ConnectionError

from code.src.utils.logger import get_default_logger, AuditLogger
from code.src.utils.helpers import domain_from_url

# Configuration constants
MAX_RETRIES = 3
RETRY_DELAY = 2.0  # seconds
TIMEOUT_SECONDS = 30
RAW_DATA_DIR = Path("data/raw")

logger: AuditLogger = get_default_logger("fetcher")


def fetch_url_with_retry(url: str, timeout: int = TIMEOUT_SECONDS) -> Optional[str]:
    """
    Fetch HTML content from a URL with retry logic.

    Args:
        url: The URL to fetch.
        timeout: Request timeout in seconds.

    Returns:
        The HTML content as a string, or None if all retries fail.
    """
    attempt = 0
    last_error = None

    while attempt < MAX_RETRIES:
        try:
            logger.info(f"Fetching URL (attempt {attempt + 1}/{MAX_RETRIES}): {url}")
            response = requests.get(
                url,
                timeout=timeout,
                headers={
                    "User-Agent": "Mozilla/5.0 (compatible; ABTestAuditBot/1.0; +https://example.com/bot)"
                }
            )
            response.raise_for_status()
            logger.info(f"Successfully fetched: {url} (Status: {response.status_code})")
            return response.text

        except Timeout:
            last_error = f"Timeout after {timeout}s"
            logger.warning(f"Timeout fetching {url}: {last_error}")
        except ConnectionError as e:
            last_error = f"Connection error: {str(e)}"
            logger.warning(f"Connection error fetching {url}: {last_error}")
        except RequestException as e:
            last_error = f"Request error: {str(e)}"
            logger.error(f"Request error fetching {url}: {last_error}")
            # Non-retryable errors (e.g., 404) should not retry indefinitely
            if hasattr(e, 'response') and e.response is not None:
                if 400 <= e.response.status_code < 500:
                    logger.error(f"Client error {e.response.status_code} for {url}, stopping retries.")
                    return None

        attempt += 1
        if attempt < MAX_RETRIES:
            wait_time = RETRY_DELAY * (2 ** (attempt - 1))  # Exponential backoff
            logger.info(f"Retrying in {wait_time}s...")
            time.sleep(wait_time)

    logger.error(f"Failed to fetch {url} after {MAX_RETRIES} attempts. Last error: {last_error}")
    return None


def fetch_html_to_file(url: str, output_dir: Path = RAW_DATA_DIR) -> Optional[Tuple[str, Path]]:
    """
    Fetch HTML content and save it to a file in the output directory.

    Args:
        url: The URL to fetch.
        output_dir: Directory to save the HTML file.

    Returns:
        A tuple of (url, file_path) if successful, None otherwise.
    """
    html_content = fetch_url_with_retry(url)

    if html_content is None:
        return None

    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate a safe filename based on URL hash
    url_hash = hashlib.sha256(url.encode('utf-8')).hexdigest()[:16]
    domain = domain_from_url(url) or "unknown"
    filename = f"{domain}_{url_hash}.html"
    file_path = output_dir / filename

    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        logger.info(f"Saved HTML to {file_path}")
        return (url, file_path)
    except IOError as e:
        logger.error(f"Failed to write HTML to {file_path}: {str(e)}")
        return None


def fetch_urls_batch(urls: List[str], output_dir: Path = RAW_DATA_DIR) -> List[Tuple[str, Path]]:
    """
    Fetch a batch of URLs and save them to files.

    Args:
        urls: List of URLs to fetch.
        output_dir: Directory to save HTML files.

    Returns:
        List of (url, file_path) tuples for successfully fetched URLs.
    """
    results = []
    for url in urls:
        result = fetch_html_to_file(url, output_dir)
        if result:
            results.append(result)
    return results


def ingest_and_fetch(urls_csv_path: str, output_dir: Path = RAW_DATA_DIR) -> List[Tuple[str, Path]]:
    """
    Read URLs from a CSV file (generated by T018 ingestor) and fetch them.

    Args:
        urls_csv_path: Path to the CSV file containing URLs.
        output_dir: Directory to save HTML files.

    Returns:
        List of (url, file_path) tuples for successfully fetched URLs.
    """
    urls = []
    csv_path = Path(urls_csv_path)

    if not csv_path.exists():
        logger.error(f"URLs CSV file not found: {csv_path}")
        return []

    # Simple CSV reading assuming single column 'url' or just raw lines
    # Depending on T018 output format, we handle both possibilities
    try:
        import csv
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            if 'url' in reader.fieldnames:
                urls = [row['url'] for row in reader if row['url']]
            else:
                # Fallback: assume no header or different structure
                f.seek(0)
                for line in f:
                    line = line.strip()
                    if line and line.startswith('http'):
                        urls.append(line)
    except Exception as e:
        logger.error(f"Error reading URLs CSV: {str(e)}")
        return []

    logger.info(f"Found {len(urls)} URLs to fetch.")
    return fetch_urls_batch(urls, output_dir)


def main():
    """
    Main entry point for the fetcher script.
    Expects an input CSV file path as an argument or uses default 'input/urls.csv'.
    """
    import sys
    input_file = "input/urls.csv"
    if len(sys.argv) > 1:
        input_file = sys.argv[1]

    logger.info(f"Starting fetcher with input: {input_file}")
    results = ingest_and_fetch(input_file)

    logger.info(f"Fetch complete. Successfully fetched {len(results)} URLs.")
    if len(results) == 0:
        logger.warning("No URLs were successfully fetched.")
        sys.exit(1)

    # Log summary
    for url, path in results:
        logger.debug(f"  - {url} -> {path}")


if __name__ == "__main__":
    main()
