"""
Screening module for Expected Loss ranking and baseline comparison.

Implements FR-007: Expected Loss ranking (prediction + variance penalty).
Handles fallback if Sparse GP model fails to load.
"""
import os
import sys
import json
import logging
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple

import pandas as pd
import numpy as np

# Configure logging
logger = logging.getLogger(__name__)

def load_predictions(input_path: str) -> pd.DataFrame:
    """
    Load the UQ predictions CSV generated by T022b.
    
    Args:
        input_path: Path to results/uq_predictions.csv
        
    Returns:
        DataFrame with prediction, variance, and method columns.
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")
    
    df = pd.read_csv(input_path)
    
    # Verify required columns exist
    required_cols = ['sample_id', 'method', 'prediction', 'variance']
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in input: {missing}")
    
    return df

def calculate_expected_loss(
    predictions: pd.Series, 
    variances: pd.Series, 
    risk_aversion: float = 1.0
) -> pd.Series:
    """
    Calculate Expected Loss = prediction + risk_aversion * variance.
    
    This implements the Expected Loss ranking as required by FR-007.
    Lower expected loss indicates a more favorable candidate for screening.
    
    Args:
        predictions: Series of predicted values (e.g., formation energy)
        variances: Series of variance estimates
        risk_aversion: Risk aversion parameter (default 1.0)
        
    Returns:
        Series of expected loss values
    """
    return predictions + risk_aversion * variances

def rank_by_expected_loss(
    df: pd.DataFrame, 
    method: str, 
    risk_aversion: float = 1.0
) -> pd.DataFrame:
    """
    Rank candidates by expected loss for a specific method.
    
    Args:
        df: DataFrame with predictions and variances
        method: Method name to filter (e.g., 'deep_ensemble', 'mc_dropout')
        risk_aversion: Risk aversion parameter
        
    Returns:
        DataFrame sorted by expected loss (ascending)
    """
    method_df = df[df['method'] == method].copy()
    
    if method_df.empty:
        logger.warning(f"No data found for method: {method}")
        return pd.DataFrame()
    
    # Calculate expected loss
    method_df['expected_loss'] = calculate_expected_loss(
        method_df['prediction'], 
        method_df['variance'], 
        risk_aversion
    )
    
    # Sort by expected loss (ascending - lower is better for formation energy)
    method_df = method_df.sort_values('expected_loss', ascending=True)
    
    # Add rank column
    method_df['rank'] = range(1, len(method_df) + 1)
    
    return method_df

def run_baseline_screening(
    df: pd.DataFrame, 
    method: str
) -> pd.DataFrame:
    """
    Run point-prediction baseline screening (no variance penalty).
    
    Args:
        df: DataFrame with predictions
        method: Method name to filter
        
    Returns:
        DataFrame sorted by prediction only
    """
    method_df = df[df['method'] == method].copy()
    
    if method_df.empty:
        logger.warning(f"No data found for method: {method}")
        return pd.DataFrame()
    
    # Sort by prediction only (no variance penalty)
    method_df = method_df.sort_values('prediction', ascending=True)
    
    # Add rank column
    method_df['rank'] = range(1, len(method_df) + 1)
    
    return method_df

def generate_screening_candidates(
    predictions_df: pd.DataFrame,
    methods: List[str],
    risk_aversion: float = 1.0,
    top_k: Optional[int] = None
) -> pd.DataFrame:
    """
    Generate screening candidates for multiple methods.
    
    Implements fallback: if a method fails (e.g., Sparse GP), 
    exclude it and proceed with others.
    
    Args:
        predictions_df: DataFrame with UQ predictions
        methods: List of methods to include
        risk_aversion: Risk aversion parameter
        top_k: Optional limit on number of candidates per method
        
    Returns:
        Combined DataFrame of ranked candidates
    """
    all_candidates = []
    
    for method in methods:
        try:
            logger.info(f"Processing method: {method}")
            
            # Check if method exists in data
            if method not in predictions_df['method'].values:
                logger.warning(f"Method '{method}' not found in predictions. Skipping.")
                continue
            
            # Rank by expected loss
            ranked = rank_by_expected_loss(
                predictions_df, 
                method, 
                risk_aversion
            )
            
            if ranked.empty:
                logger.warning(f"No candidates for method: {method}")
                continue
            
            # Apply top_k limit if specified
            if top_k is not None:
                ranked = ranked.head(top_k)
            
            # Mark uncertainty type
            ranked['uncertainty_type'] = 'total' if method in ['deep_ensemble', 'mc_dropout'] else 'aleatoric'
            
            all_candidates.append(ranked)
            
        except Exception as e:
            logger.error(f"Failed to process method {method}: {str(e)}")
            logger.warning(f"Excluding method {method} from screening due to error")
            continue
    
    if not all_candidates:
        raise RuntimeError("No methods successfully processed for screening")
    
    return pd.concat(all_candidates, ignore_index=True)

def generate_baseline_screening(
    predictions_df: pd.DataFrame,
    methods: List[str],
    top_k: Optional[int] = None
) -> pd.DataFrame:
    """
    Generate baseline screening candidates (point prediction only).
    
    Args:
        predictions_df: DataFrame with UQ predictions
        methods: List of methods to include
        top_k: Optional limit on number of candidates per method
        
    Returns:
        Combined DataFrame of ranked baseline candidates
    """
    all_candidates = []
    
    for method in methods:
        try:
            logger.info(f"Processing baseline for method: {method}")
            
            # Check if method exists in data
            if method not in predictions_df['method'].values:
                logger.warning(f"Method '{method}' not found in predictions. Skipping.")
                continue
            
            # Rank by prediction only
            ranked = run_baseline_screening(predictions_df, method)
            
            if ranked.empty:
                logger.warning(f"No candidates for baseline method: {method}")
                continue
            
            # Apply top_k limit if specified
            if top_k is not None:
                ranked = ranked.head(top_k)
            
            # Mark as baseline
            ranked['uncertainty_type'] = 'point_prediction'
            
            all_candidates.append(ranked)
            
        except Exception as e:
            logger.error(f"Failed to process baseline for method {method}: {str(e)}")
            continue
    
    if not all_candidates:
        raise RuntimeError("No methods successfully processed for baseline screening")
    
    return pd.concat(all_candidates, ignore_index=True)

def main():
    """
    Main entry point for screening module.
    
    Generates:
        - results/screening_candidates.csv (Expected Loss ranking)
        - results/screening_baseline.csv (Point prediction baseline)
    """
    # Setup argument parser
    parser = argparse.ArgumentParser(description='Run UQ-based screening')
    parser.add_argument(
        '--input', 
        type=str, 
        default='results/uq_predictions.csv',
        help='Path to UQ predictions CSV'
    )
    parser.add_argument(
        '--output-candidates',
        type=str,
        default='results/screening_candidates.csv',
        help='Output path for Expected Loss candidates'
    )
    parser.add_argument(
        '--output-baseline',
        type=str,
        default='results/screening_baseline.csv',
        help='Output path for baseline candidates'
    )
    parser.add_argument(
        '--risk-aversion',
        type=float,
        default=1.0,
        help='Risk aversion parameter for Expected Loss'
    )
    parser.add_argument(
        '--methods',
        type=str,
        nargs='+',
        default=['deep_ensemble', 'mc_dropout'],
        help='Methods to include in screening'
    )
    parser.add_argument(
        '--top-k',
        type=int,
        default=None,
        help='Limit number of candidates per method'
    )
    parser.add_argument(
        '--log-file',
        type=str,
        default='logs/screening.log',
        help='Path to log file'
    )
    
    args = parser.parse_args()
    
    # Setup logging
    os.makedirs(os.path.dirname(args.log_file), exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(args.log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )
    
    logger.info("Starting screening process")
    logger.info(f"Input file: {args.input}")
    logger.info(f"Methods: {args.methods}")
    logger.info(f"Risk aversion: {args.risk_aversion}")
    
    try:
        # Load predictions
        predictions_df = load_predictions(args.input)
        logger.info(f"Loaded {len(predictions_df)} predictions")
        
        # Generate Expected Loss ranking
        logger.info("Generating Expected Loss ranking...")
        candidates = generate_screening_candidates(
            predictions_df,
            args.methods,
            args.risk_aversion,
            args.top_k
        )
        
        # Ensure output directory exists
        os.makedirs(os.path.dirname(args.output_candidates), exist_ok=True)
        
        # Save candidates
        candidates.to_csv(args.output_candidates, index=False)
        logger.info(f"Saved {len(candidates)} candidates to {args.output_candidates}")
        
        # Generate baseline ranking
        logger.info("Generating baseline ranking...")
        baseline = generate_baseline_screening(
            predictions_df,
            args.methods,
            args.top_k
        )
        
        # Ensure output directory exists
        os.makedirs(os.path.dirname(args.output_baseline), exist_ok=True)
        
        # Save baseline
        baseline.to_csv(args.output_baseline, index=False)
        logger.info(f"Saved {len(baseline)} baseline candidates to {args.output_baseline}")
        
        # Log summary
        logger.info("Screening process completed successfully")
        logger.info(f"Candidates: {len(candidates)}, Baseline: {len(baseline)}")
        
    except FileNotFoundError as e:
        logger.error(f"File not found: {str(e)}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Screening failed: {str(e)}")
        sys.exit(1)

if __name__ == '__main__':
    main()
