import os
import sys
import json
import numpy as np
import nibabel as nib
from pathlib import Path
from typing import Optional, Tuple, List, Dict, Any

from config import get_config
from utils.logging_config import get_logger, error, warning, info, critical
from utils.checksums import compute_sha256

logger = get_logger(__name__)


def load_mask_from_json(mask_json_path: str) -> np.ndarray:
    """
    Load a mask path from the JSON file generated by T013 and return the mask array.
    """
    if not os.path.exists(mask_json_path):
        error(logger, "E001", f"Mask paths JSON not found: {mask_json_path}")
        raise FileNotFoundError(f"Mask paths JSON not found: {mask_json_path}")

    with open(mask_json_path, 'r') as f:
        mask_paths = json.load(f)

    dlpfc_path = mask_paths.get("dlpfc")
    if not dlpfc_path or not os.path.exists(dlpfc_path):
        error(logger, "E001", f"DLPFC mask file not found or path missing: {dlpfc_path}")
        raise FileNotFoundError(f"DLPFC mask file not found: {dlpfc_path}")

    mask_img = nib.load(dlpfc_path)
    mask_data = mask_img.get_fdata()
    return mask_data


def find_functional_runs(raw_dir: Path, subject_id: str) -> List[Path]:
    """
    Locate functional runs for a given subject in the OpenNeuro ds001495 directory structure.
    Assumes standard OpenNeuro BIDS structure:
    raw_dir/sub-<subject_id>/func/sub-<subject_id>_task-<task>_run-<run>_bold.nii.gz
    """
    sub_dir = raw_dir / f"sub-{subject_id}" / "func"
    if not sub_dir.exists():
        warning(logger, f"Subject directory not found: {sub_dir}")
        return []

    func_files = list(sub_dir.glob("*bold.nii.gz"))
    if not func_files:
        warning(logger, f"No bold files found for subject {subject_id}")
    return sorted(func_files)


def extract_roi_timecourse(func_img: nib.Nifti1Image, mask_data: np.ndarray,
                           mask_affine: np.ndarray, func_affine: np.ndarray) -> Optional[np.ndarray]:
    """
    Extract the mean BOLD timecourse from a functional run using the provided mask.
    Returns a 1D array of timepoints, or None if mask yields no voxels.
    """
    # Resample mask to functional space if necessary
    # For simplicity in this implementation, we assume they are already aligned or
    # rely on nilearn's resampling if needed. Here we do a direct voxel-wise check
    # assuming same space for performance, but in a robust pipeline nilearn.resample_img
    # should be used. Given constraints and existing API, we check overlap.

    func_data = func_img.get_fdata()
    if func_data.ndim != 4:
        warning(logger, "Functional image is not 4D (x,y,z,time). Skipping.")
        return None

    # If the mask and functional have different shapes/affines, we need to handle it.
    # For this specific task, we assume T013 generated masks in the same space or
    # we use a simple intersection approach if shapes match.
    # If shapes differ, we must resample.
    if func_data.shape[:3] != mask_data.shape:
        # Attempt to resample mask to functional space using nibabel or simple interpolation
        # Since we don't have nilearn explicitly imported here (though it is in reqs),
        # we try to use nibabel's resample_to_img if available, or fallback to error.
        # However, T013 logic (not shown but implied) should handle coordinate-based generation.
        # Let's assume for now we need to align.
        try:
            import nilearn.image as nl_img
            mask_nii = nib.Nifti1Image(mask_data, mask_affine)
            func_nii = func_img
            resampled_mask = nl_img.resample_to_img(mask_nii, func_nii, interpolation='nearest')
            mask_data = resampled_mask.get_fdata()
        except ImportError:
            error(logger, "E002", "Nilearn not available for resampling masks.")
            raise ImportError("Nilearn required for mask resampling")
        except Exception as e:
            error(logger, "E002", f"Failed to resample mask: {e}")
            raise RuntimeError(f"Mask resampling failed: {e}")

    # Apply mask
    voxels = func_data[mask_data > 0]
    if voxels.size == 0:
        return None

    # Reshape to (timepoints, voxels) and take mean across voxels
    # voxels shape: (num_voxels * timepoints) if we flatten incorrectly?
    # Correct approach: func_data is (x, y, z, t). mask is (x, y, z).
    # We want mean over voxels for each timepoint.
    # voxels = func_data[mask > 0] -> shape (num_voxels, t) if we index correctly?
    # Actually, boolean indexing flattens.
    # We need to reshape func_data to (num_voxels, t) where num_voxels is count of mask > 0.
    # Better:
    mask_flat = mask_data > 0
    func_flat = func_data[mask_flat, :] # This doesn't work directly on 4D
    
    # Correct 4D extraction:
    # func_data shape: (X, Y, Z, T)
    # mask shape: (X, Y, Z)
    # We want: mean(func_data[mask > 0], axis=0) -> (T,)
    # We can iterate or use advanced indexing.
    # Let's reshape to (X*Y*Z, T)
    func_2d = func_data.reshape(-1, func_data.shape[3])
    mask_1d = mask_flat.flatten()
    selected_voxels = func_2d[mask_1d, :] # Shape: (N_voxels, T)
    
    if selected_voxels.shape[0] == 0:
        return None

    mean_timecourse = np.mean(selected_voxels, axis=0)
    return mean_timecourse


def process_subject(raw_dir: Path, subject_id: str, mask_data: np.ndarray,
                    mask_affine: np.ndarray, func_affine: np.ndarray,
                    output_dir: Path) -> Optional[np.ndarray]:
    """
    Process a single subject: find runs, extract timecourse, average across runs.
    """
    func_files = find_functional_runs(raw_dir, subject_id)
    if not func_files:
        return None

    all_run_timecourses = []
    for f_path in func_files:
        try:
            func_img = nib.load(f_path)
            # Update func_affine if it changes per run (it shouldn't usually, but safe)
            tc = extract_roi_timecourse(func_img, mask_data, mask_affine, func_img.affine)
            if tc is not None:
                all_run_timecourses.append(tc)
        except Exception as e:
            warning(logger, f"Failed to process run {f_path} for subject {subject_id}: {e}")
            continue

    if not all_run_timecourses:
        return None

    # Average across runs (assuming same length for simplicity, or pad? OpenNeuro runs usually same length)
    # If lengths differ, we truncate to min length
    min_len = min(len(tc) for tc in all_run_timecourses)
    if min_len == 0:
        return None

    averaged_tc = np.mean([tc[:min_len] for tc in all_run_timecourses], axis=0)
    return averaged_tc


def main():
    """
    Main entry point for T016: Extract DLPFC timecourses.
    """
    config = get_config()
    raw_dir = Path("data/raw/openneuro_ds001495")
    mask_json_path = "data/processed/mask_paths.json"
    output_path = Path("data/processed/roi_dlpfc.npy")
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Load Mask
    try:
        mask_data = load_mask_from_json(mask_json_path)
        # We need the affine from the mask file to handle resampling if needed
        # Re-load the nii to get affine
        with open(mask_json_path, 'r') as f:
            mask_paths = json.load(f)
        dlpfc_nii_path = mask_paths["dlpfc"]
        dlpfc_img = nib.load(dlpfc_nii_path)
        mask_affine = dlpfc_img.affine
    except Exception as e:
        error(logger, "E001", f"Failed to load DLPFC mask: {e}")
        sys.exit(1)

    # 2. Identify Subjects
    # Assuming standard BIDS structure, find sub-* directories
    if not raw_dir.exists():
        error(logger, "E001", f"Raw data directory not found: {raw_dir}")
        sys.exit(1)

    subjects = [d.name for d in raw_dir.iterdir() if d.is_dir() and d.name.startswith("sub-")]
    if not subjects:
        error(logger, "E002", "No subjects found in raw data directory.")
        sys.exit(1)

    logger.info(f"Found {len(subjects)} subjects to process.")

    # 3. Extract Timecourses
    # We will store a list of (subject_id, timepoint, signal) or a structured array
    # The task asks for roi_dlpfc.npy. Based on T014/T015, it likely expects a 2D array:
    # (subjects, timepoints) or a flattened structure.
    # Given T017 combines them into a CSV with columns: subject_id, roi, timepoint, signal,
    # the .npy file here should probably be a structured array or a 2D array of (N_subjects, N_timepoints).
    # Let's aim for (N_subjects, N_timepoints) and store subject IDs separately or in a dict.
    # However, to be safe and consistent with T014/T015 which likely produce similar shapes:
    # Let's produce a 2D array: rows=subjects, cols=timepoints.
    
    subject_ids = []
    timecourses = []
    valid_count = 0

    for sub in subjects:
        tc = process_subject(raw_dir, sub, mask_data, mask_affine, None, output_path.parent)
        if tc is not None:
            subject_ids.append(sub)
            timecourses.append(tc)
            valid_count += 1

    if valid_count == 0:
        error(logger, "E002", "No valid timecourses extracted for DLPFC.")
        sys.exit(1)

    # Ensure all timecourses are same length (truncate to min if needed)
    min_len = min(len(tc) for tc in timecourses)
    timecourses = [tc[:min_len] for tc in timecourses]

    # Stack into (N_subjects, N_timepoints)
    roi_data = np.stack(timecourses, axis=0)

    # Save
    np.save(output_path, roi_data)
    logger.info(f"Saved DLPFC timecourses to {output_path} (shape: {roi_data.shape})")

    # 4. Update Checksums (Optional but good practice)
    try:
        from utils.checksums import compute_sha256
        checksum = compute_sha256(output_path)
        logger.info(f"Checksum for {output_path}: {checksum}")
    except Exception as e:
        warning(logger, f"Could not compute checksum: {e}")

    logger.info("T016 DLPFC extraction completed successfully.")


if __name__ == "__main__":
    main()