[build]
  # Directory to publish (our GitHub Pages site)
  publish = "docs"

[build.environment]
  # These will be set in Netlify UI for security
  # GITHUB_CLIENT_ID = "your-client-id"
  # GITHUB_CLIENT_SECRET = "your-client-secret"

[[redirects]]
  # Handle OAuth callback
  from = "/callback"
  to = "/"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  # Directory containing serverless functions
  directory = "docs/netlify/functions"