from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4
from pydantic import BaseModel, Field, field_validator
import json

class ObjectNode(BaseModel):
    """Represents a single object entity within a scene graph."""
    id: str = Field(..., description="Unique identifier for the object")
    label: str = Field(..., description="Semantic label of the object (e.g., 'person', 'car')")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Key-value attributes (e.g., color, size)")
    bounding_box: Optional[List[float]] = Field(None, description="Optional bounding box [x, y, w, h]")

    @field_validator('label')
    @classmethod
    def label_must_not_be_empty(cls, v):
        if not v or not v.strip():
            raise ValueError("Label cannot be empty or whitespace")
        return v

class RelationshipEdge(BaseModel):
    """Represents a directed relationship between two object nodes."""
    id: str = Field(..., description="Unique identifier for the relationship")
    subject_id: str = Field(..., description="ID of the subject object")
    predicate: str = Field(..., description="Relationship predicate (e.g., 'on', 'holding', 'near')")
    object_id: str = Field(..., description="ID of the object object")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Optional attributes for the relationship")

    @field_validator('predicate')
    @classmethod
    def predicate_must_not_be_empty(cls, v):
        if not v or not v.strip():
            raise ValueError("Predicate cannot be empty or whitespace")
        return v

class SceneGraph(BaseModel):
    """
    Represents a structured scene description conforming to the contract.
    Used for both ground truth (Human-Annotated) and simulator outputs.
    """
    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique scene identifier")
    objects: List[ObjectNode] = Field(..., description="List of objects in the scene")
    relationships: List[RelationshipEdge] = Field(..., description="List of relationships between objects")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata (source, timestamp, etc.)")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")

    def add_object(self, obj: ObjectNode) -> None:
        self.objects.append(obj)

    def add_relationship(self, rel: RelationshipEdge) -> None:
        self.relationships.append(rel)

    def to_dict(self) -> Dict[str, Any]:
        """Convert the SceneGraph to a dictionary for JSON serialization."""
        return self.model_dump(mode='json')

    def to_json(self, indent: Optional[int] = 2) -> str:
        """Serialize the SceneGraph to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SceneGraph":
        """Construct a SceneGraph from a dictionary."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, json_str: str) -> "SceneGraph":
        """Construct a SceneGraph from a JSON string."""
        return cls.model_validate(json.loads(json_str))

class CritiqueStep(BaseModel):
    """
    Represents a single step in the agentic loop where a Critic evaluates a generation.
    """
    step_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    intent: str = Field(..., description="The current intent or plan being executed")
    generated_output: Optional[Dict[str, Any]] = Field(None, description="The JSON output generated by the Generator")
    critique: str = Field(..., description="The textual critique generated by the Critic")
    score: float = Field(..., ge=0.0, le=1.0, description="Numerical score assigned by the Critic")
    is_accepted: bool = Field(..., description="Whether the generation was accepted based on the score threshold")
    revised_intent: Optional[str] = Field(None, description="New intent if the step was rejected")

class TrajectoryLog(BaseModel):
    """
    Represents the full execution history of an agentic loop for a single sample.
    Conforms to the trajectory contract schema.
    """
    trajectory_id: str = Field(default_factory=lambda: str(uuid4()))
    sample_id: str = Field(..., description="ID of the input sample (e.g., image prompt ID)")
    start_time: datetime = Field(default_factory=datetime.utcnow)
    end_time: Optional[datetime] = Field(None, description="Completion timestamp")
    status: str = Field(..., description="Status: 'completed', 'timeout', 'error'")
    steps: List[CritiqueStep] = Field(default_factory=list, description="Chronological list of critique steps")
    final_generation: Optional[Dict[str, Any]] = Field(None, description="The final accepted SceneGraph JSON")
    error_message: Optional[str] = Field(None, description="Error details if status is 'error'")

    def add_step(self, step: CritiqueStep) -> None:
        self.steps.append(step)

    def complete(self, final_output: Optional[Dict[str, Any]] = None) -> None:
        """Mark the trajectory as completed."""
        self.end_time = datetime.utcnow()
        self.status = "completed"
        self.final_generation = final_output

    def fail(self, error_msg: str) -> None:
        """Mark the trajectory as failed."""
        self.end_time = datetime.utcnow()
        self.status = "error"
        self.error_message = error_msg

    def to_dict(self) -> Dict[str, Any]:
        """Convert the TrajectoryLog to a dictionary for JSON serialization."""
        return self.model_dump(mode='json', exclude_none=True)

    def to_json(self, indent: Optional[int] = 2) -> str:
        """Serialize the TrajectoryLog to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TrajectoryLog":
        """Construct a TrajectoryLog from a dictionary."""
        # Handle datetime parsing if needed, though model_validate usually handles ISO strings
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, json_str: str) -> "TrajectoryLog":
        """Construct a TrajectoryLog from a JSON string."""
        return cls.model_validate(json.loads(json_str))