"""
Mixed Effects Model for Robustness Check of Merged Dataset Approach.

Implements a secondary Mixed Linear Model (MixedLM) using statsmodels to assess
the robustness of the merged dataset approach by including 'Dataset ID' as a
random effect. This addresses the 'Merged Dataset Strategy' pivot defined in the plan.

Distinct from the primary t-test (T023a) which treats groups as fixed effects only.
"""
import argparse
import csv
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.regression.mixed_linear_model import MixedLM

# Ensure consistent logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
ALPHA = 0.05
BONFERRONI_N = 4  # 2 ROIs x 2 events
CORRECTED_ALPHA = ALPHA / BONFERRONI_N

def load_beta_estimates(file_path: str) -> pd.DataFrame:
    """
    Load beta estimates from the CSV generated by T020/T023a.

    Args:
        file_path: Path to data/results/beta_estimates.csv

    Returns:
        DataFrame with columns: participant_id, group, roi, event_type, beta_value, dataset_id
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Beta estimates file not found: {file_path}")

    df = pd.read_csv(file_path)

    # Ensure required columns exist
    required_cols = ['participant_id', 'group', 'roi', 'event_type', 'beta_value']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in beta file: {missing_cols}")

    # Handle dataset_id column - it might be missing if not added in harmonization
    if 'dataset_id' not in df.columns:
        logger.warning("'dataset_id' column missing. Attempting to infer from participant_id or assigning default.")
        # Try to infer from participant_id if it contains dataset prefix (e.g., ds000246_sub-001)
        if df['participant_id'].str.contains('ds000246', na=False).any():
            df['dataset_id'] = df['participant_id'].str.extract(r'^(ds\d+)')
            logger.info("Inferred dataset_id from participant_id prefix.")
        elif df['participant_id'].str.contains('ds004738', na=False).any():
            df['dataset_id'] = df['participant_id'].str.extract(r'^(ds\d+)')
            logger.info("Inferred dataset_id from participant_id prefix.")
        else:
            # Fallback: assume all data comes from a single merged source or assign a placeholder
            # In a real scenario, this indicates a failure in the harmonization step (T010b)
            logger.error("Could not infer dataset_id. Merged dataset analysis requires this column.")
            raise ValueError("Cannot run MixedLM without 'dataset_id'. Please ensure harmonization (T010b) populates this field.")

    # Clean up data types
    df['beta_value'] = pd.to_numeric(df['beta_value'], errors='coerce')
    df = df.dropna(subset=['beta_value'])

    return df

def group_by_roi_event(df: pd.DataFrame) -> List[Tuple[str, str]]:
    """
    Identify unique combinations of ROI and event_type to analyze.

    Returns:
        List of tuples (roi, event_type)
    """
    return df.groupby(['roi', 'event_type']).size().reset_index()[['roi', 'event_type']].values.tolist()

def run_mixedlm_analysis(
    df: pd.DataFrame,
    roi: str,
    event_type: str,
    group_col: str = 'group',
    random_effect_col: str = 'dataset_id'
) -> Optional[Dict]:
    """
    Run a Mixed Linear Model for a specific ROI and event type.

    Model: Beta ~ Group + (1 | Dataset_ID)

    Args:
        df: Full DataFrame of beta estimates
        roi: ROI name (e.g., 'Ventral Striatum')
        event_type: Event type (e.g., 'reward_anticipation')
        group_col: Column name for the group variable (excluded/included)
        random_effect_col: Column name for the random effect (dataset_id)

    Returns:
        Dictionary with model results or None if analysis fails.
    """
    subset = df[(df['roi'] == roi) & (df['event_type'] == event_type)]

    if len(subset) < 3:
        logger.warning(f"Insufficient data for {roi}/{event_type} (N={len(subset)}). Skipping.")
        return None

    # Prepare data
    # Convert group to dummy variable (0/1) for the fixed effect
    # Assuming 'excluded' is the condition of interest, map 'excluded' -> 1, 'included' -> 0
    # Or keep as categorical if statsmodels handles it (it does, but explicit is safer for mixedlm formula)
    subset = subset.copy()
    subset['group_binary'] = (subset[group_col] == 'excluded').astype(int)

    # Check for variance in random effects
    unique_datasets = subset[random_effect_col].nunique()
    if unique_datasets < 2:
        logger.warning(f"Only one dataset ID found for {roi}/{event_type}. MixedLM requires at least 2 groups for random effect. Falling back to simple OLS or skipping.")
        # In a strict implementation, we might skip, but for robustness check, we note the limitation.
        # We will attempt to run, but warn.
    
    try:
        # Formula: beta_value ~ group_binary + (1 | dataset_id)
        # Note: statsmodels MixedLM uses a specific syntax
        endog = subset['beta_value']
        exog = sm.add_constant(subset['group_binary'])
        groups = subset[random_effect_col]

        model = MixedLM(endog, exog, groups=groups)
        result = model.fit(reml=False) # Use ML for comparison, though REML is often preferred for inference

        # Extract key stats
        # Fixed effects: index 0 is const, index 1 is group_binary
        if len(result.params) > 1:
            group_coef = result.params['group_binary']
            group_se = result.bse['group_binary']
            group_t = result.tvalues['group_binary']
            group_p = result.pvalues['group_binary']
        else:
            group_coef = result.params.iloc[0]
            group_se = result.bse.iloc[0]
            group_t = 0.0
            group_p = 1.0

        # Random effects variance
        var_component = result.cov_re.iloc[0, 0] if hasattr(result, 'cov_re') and result.cov_re is not None else 0.0

        return {
            'roi': roi,
            'event_type': event_type,
            'n_subjects': len(subset),
            'n_datasets': unique_datasets,
            'fixed_effect_coef': group_coef,
            'fixed_effect_se': group_se,
            't_statistic': group_t,
            'p_value': group_p,
            'p_value_bonferroni': min(group_p * BONFERRONI_N, 1.0),
            'significant_at_corrected_alpha': min(group_p * BONFERRONI_N, 1.0) < CORRECTED_ALPHA,
            'random_effect_variance': var_component,
            'model_converged': result.converged
        }

    except Exception as e:
        logger.error(f"Error running MixedLM for {roi}/{event_type}: {e}")
        return None

def run_mixedlm_robustness_check(
    data_path: str,
    output_path: str
) -> Dict:
    """
    Main entry point for the robustness check.

    Loads data, iterates over ROI/Event combinations, runs MixedLM, and saves results.

    Args:
        data_path: Path to beta_estimates.csv
        output_path: Path to save results JSON

    Returns:
        Summary dictionary of the analysis.
    """
    logger.info(f"Loading beta estimates from {data_path}")
    df = load_beta_estimates(data_path)

    roi_event_combos = group_by_roi_event(df)
    logger.info(f"Found {len(roi_event_combos)} ROI/Event combinations to analyze.")

    results = []
    for roi, event_type in roi_event_combos:
        logger.info(f"Running MixedLM for {roi} - {event_type}")
        res = run_mixedlm_analysis(df, roi, event_type)
        if res:
            results.append(res)

    # Save results
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)

    logger.info(f"Saved MixedLM results to {output_path}")

    # Summary
    significant_count = sum(1 for r in results if r['significant_at_corrected_alpha'])
    return {
        'total_combinations': len(results),
        'significant_combinations': significant_count,
        'results': results
    }

def main():
    parser = argparse.ArgumentParser(
        description="Run MixedLM robustness check on merged fMRI dataset."
    )
    parser.add_argument(
        '--input',
        type=str,
        default='data/results/beta_estimates.csv',
        help='Path to beta estimates CSV (default: data/results/beta_estimates.csv)'
    )
    parser.add_argument(
        '--output',
        type=str,
        default='data/results/mixedlm_robustness_results.json',
        help='Path to save results JSON (default: data/results/mixedlm_robustness_results.json)'
    )
    args = parser.parse_args()

    try:
        summary = run_mixedlm_robustness_check(args.input, args.output)
        print(json.dumps(summary, indent=2))
    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
