"""
T029: Save consolidated metrics summary to results/metrics.json.

This script consolidates the evaluation results from the trained models
(Random Forest, Gradient Boosting, Mean Baseline) and the statistical
significance tests (paired t-tests with Bonferroni correction) into a
single JSON artifact as required by the specification.

It assumes that T028 has already been run and that the intermediate
metrics (R², MAE, RMSE, p-values, significance flags) are available
either in memory or via a temporary state file produced by the
statistical evaluation step. Since T028 (02_statistical_evaluation.py)
is marked as completed, we assume it produces a state file or the
main entry point of the training pipeline has already aggregated
these values.

For this implementation, we will re-load the predictions and models
to re-compute the metrics and perform the statistical tests to ensure
the final JSON is derived from the actual data on disk, satisfying
the "real data only" constraint.

Workflow:
1. Load the test set data (X_test, y_test).
2. Load the trained models (RF, GB, MeanBaseline) from the state directory.
3. Generate predictions for all models.
4. Compute R², MAE, RMSE for each model.
5. Perform paired t-tests (RF vs Mean, GB vs Mean) using utils.metrics.
6. Apply Bonferroni correction (alpha = 0.05 / 2).
7. Assemble the final dictionary and write to results/metrics.json.
"""

import os
import sys
import json
import logging
import pickle
from pathlib import Path
from typing import Dict, Any, List, Tuple

# Project imports
# Note: We assume the training script saved models to state/projects/PROJ-238.../models
# We need to locate the config or hardcode the path based on project structure.
# Using the config module to get paths is safer.
from config import get_config, log_event
from utils.metrics import paired_t_test, bonferroni_correct
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_model_predictions(model_path: Path) -> Any:
    """Load a pickled model from disk."""
    if not model_path.exists():
        raise FileNotFoundError(f"Model not found at {model_path}")
    with open(model_path, 'rb') as f:
        return pickle.load(f)

def load_test_data(config: Dict[str, str]) -> Tuple[Any, Any, Any]:
    """
    Load test data.
    We assume the data was split and saved by T017.1/T022.
    The training script (02_train_models.py) likely saved the split data
    or we can reload it from the CSV files.
    For this script, we assume the training script saved the X_test, y_test
    arrays or we can infer the path.
    
    However, to be robust and avoid re-parsing CSVs if not needed,
    we look for a 'state' file containing the test split or reload from CSV.
    Given the constraint to use real data, we will reload from the CSV
    if we can't find a pre-saved array, but the most reliable way in
    this pipeline is that 02_train_models.py saved the necessary arrays
    or we can re-load from the processed CSVs.
    
    Let's assume the standard flow:
    1. 02_train_models.py loads train/val/test CSVs.
    2. It trains models and saves them.
    3. It evaluates and might save predictions.
    
    For T029, we need to ensure we have the predictions.
    If 02_statistical_evaluation.py (T028) ran, it might have saved a
    'metrics_state.json' or similar.
    
    Strategy: Try to load from a state file first. If not, re-compute
    by loading the CSV and models.
    """
    # Path to processed test data (generated by T017.1)
    test_csv_path = Path(config['DATA_PATH']) / 'processed' / 'test.csv'
    
    if not test_csv_path.exists():
        raise FileNotFoundError(f"Test data not found at {test_csv_path}")
    
    import pandas as pd
    df = pd.read_csv(test_csv_path)
    
    # Columns: ID, Volume, SurfaceArea, Dipole, HBD, HBA, PSA, packing_coefficient, ...
    feature_cols = ['Volume', 'SurfaceArea', 'Dipole', 'HBD', 'HBA', 'PSA']
    target_col = 'packing_coefficient'
    
    # Filter out rows with missing target (should be done by T016, but double check)
    df = df.dropna(subset=[target_col])
    
    X = df[feature_cols].values
    y = df[target_col].values
    
    return X, y, df['ID'].values

def main():
    config = get_config()
    project_id = config.get('PROJECT_ID', 'PROJ-238-predicting-molecular-crystal-packing-fro')
    state_path = Path(config.get('DATA_PATH', 'data')) / '..' / 'state' / 'projects' / project_id
    results_path = Path(config.get('DATA_PATH', 'data')) / '..' / 'results'
    
    # Ensure results directory exists
    results_path.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Loading test data from {state_path}")
    
    # Paths to models (assumed saved by 02_train_models.py)
    # We need to find where they are saved.
    # Let's assume a standard location: state_path / 'models'
    models_dir = state_path / 'models'
    if not models_dir.exists():
        # Fallback: maybe they are in the root of state/projects
        models_dir = state_path
    
    rf_model_path = models_dir / 'random_forest.pkl'
    gb_model_path = models_dir / 'gradient_boosting.pkl'
    mean_model_path = models_dir / 'mean_baseline.pkl' # Or just the mean value saved

    # Load data
    try:
        X_test, y_test, ids = load_test_data(config)
        logger.info(f"Loaded {len(y_test)} test samples.")
    except Exception as e:
        logger.error(f"Failed to load test data: {e}")
        sys.exit(1)

    # Load models
    models = {}
    try:
        models['random_forest'] = load_model_predictions(rf_model_path)
        models['gradient_boosting'] = load_model_predictions(gb_model_path)
        # For mean baseline, we might have saved the mean value or a dummy object
        if mean_model_path.exists():
            with open(mean_model_path, 'rb') as f:
                mean_val = pickle.load(f)
        else:
            # Compute mean from training data if not saved? 
            # But we only have test data here.
            # We must rely on the training script having saved the mean value.
            # Let's try to find a 'mean_baseline_value.pkl' or similar.
            # If T025 ran, it should have saved the mean.
            # Let's assume the mean was saved in a specific file.
            mean_path_fallback = models_dir / 'mean_baseline_value.pkl'
            if mean_path_fallback.exists():
                with open(mean_path_fallback, 'rb') as f:
                    mean_val = pickle.load(f)
            else:
                # If we can't find it, we can't do the baseline comparison properly.
                # But the task says T025 is done. Let's assume it's in 'mean_baseline.pkl'
                # as a simple float.
                # If the file exists but is not a model object, it might be the value.
                # Let's try to load it as a float.
                with open(mean_model_path, 'rb') as f:
                    mean_val = pickle.load(f)
        models['mean_baseline'] = mean_val
        logger.info("Models loaded successfully.")
    except Exception as e:
        logger.error(f"Failed to load models: {e}")
        sys.exit(1)

    # Generate predictions
    predictions = {}
    for name, model in models.items():
        if name == 'mean_baseline':
            preds = [model] * len(y_test)
        else:
            preds = model.predict(X_test)
        predictions[name] = preds

    # Compute metrics
    metrics_summary = {
        'models': {},
        'statistical_tests': {},
        'config': {
            'alpha': 0.05,
            'n_comparisons': 2,
            'alpha_corrected': 0.05 / 2
        }
    }

    model_names = ['random_forest', 'gradient_boosting']
    baseline_name = 'mean_baseline'

    for name in model_names:
        preds = predictions[name]
        r2 = r2_score(y_test, preds)
        mae = mean_absolute_error(y_test, preds)
        rmse = mean_squared_error(y_test, preds, squared=False)
        
        metrics_summary['models'][name] = {
            'r2': float(r2),
            'mae': float(mae),
            'rmse': float(rmse)
        }
        logger.info(f"{name}: R²={r2:.4f}, MAE={mae:.4f}, RMSE={rmse:.4f}")

    # Statistical tests
    # Paired t-test: RF vs Mean, GB vs Mean
    baseline_preds = predictions[baseline_name]
    
    p_values = {}
    significance_flags = {}
    
    for name in model_names:
        preds = predictions[name]
        # Paired t-test
        t_stat, p_val = paired_t_test(preds, baseline_preds)
        p_values[name] = float(p_val)
        
        # Bonferroni correction (already done in function? No, we do it here for the summary)
        # The function bonferroni_correct takes a list of p-values.
        # We will correct them all at once.
    
    # Correct p-values for all comparisons
    p_vals_list = list(p_values.values())
    corrected_p_vals = bonferroni_correct(p_vals_list, n_comparisons=2)
    
    for i, name in enumerate(model_names):
        corrected_p = corrected_p_vals[i]
        is_significant = corrected_p < metrics_summary['config']['alpha_corrected']
        metrics_summary['statistical_tests'][name] = {
            'p_value_original': p_values[name],
            'p_value_corrected': float(corrected_p),
            'significant': is_significant
        }
        logger.info(f"{name} vs Baseline: p={p_values[name]:.4f}, p_corr={corrected_p:.4f}, sig={is_significant}")

    # Write to JSON
    output_path = results_path / 'metrics.json'
    with open(output_path, 'w') as f:
        json.dump(metrics_summary, f, indent=2)

    logger.info(f"Metrics saved to {output_path}")
    log_event('metrics_saved', {'path': str(output_path)})

if __name__ == '__main__':
    main()