"""
Power Analysis and Sample Size Justification Module.

This module calculates the minimum detectable effect (MDE) for the specified
sample size (n=164) at power >= 0.8, and documents the constraint mismatch
with the specification requirement of n >= 200.
"""
import math
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Tuple

# Constants based on typical statistical assumptions for this type of study
# Assuming a two-tailed test for difference in proportions (pass@1) or means (latency)
DEFAULT_ALPHA = 0.05
DEFAULT_POWER = 0.80
DEFAULT_SIGMA = 1.0  # Standard deviation estimate for standardized effect size

# Specification requirements
SPEC_REQUIRED_N = 200
ACTUAL_N = 164  # HumanEval size

def calculate_minimum_detectable_effect(n: int, alpha: float = DEFAULT_ALPHA, power: float = DEFAULT_POWER) -> float:
    """
    Calculates the Minimum Detectable Effect (MDE) for a given sample size,
    alpha level, and power.

    Uses the approximation for a two-sample z-test (or large-sample t-test):
    MDE = (Z_alpha/2 + Z_beta) * sqrt(2 / n) * sigma

    For a paired test (Wilcoxon/Signed-Rank approximated to normal for large n):
    MDE ≈ (Z_alpha/2 + Z_beta) * sqrt(1 / n) * sigma (simplified for paired)

    Here we use the standard approximation for a paired difference test:
    MDE = (Z_{1-alpha/2} + Z_{power}) * sigma / sqrt(n)

    Args:
        n: Sample size (number of pairs)
        alpha: Significance level (Type I error)
        power: Statistical power (1 - Type II error)

    Returns:
        Minimum Detectable Effect (standardized, assuming sigma=1)
    """
    # Critical values from standard normal distribution
    # Z for alpha/2 (two-tailed)
    z_alpha = 1.96 if alpha == 0.05 else 2.576 # Approx for 0.05 and 0.01
    if alpha == 0.05:
        z_alpha = 1.959963984540054
    
    # Z for power (1 - beta)
    # For power=0.8, beta=0.2, Z_beta ≈ 0.8416
    z_beta = 0.8416212335729143 if power == 0.80 else 1.2815515655446004 # Approx for 0.8 and 0.9

    # Standardized MDE (Cohen's d equivalent for paired)
    # Formula: (Z_alpha/2 + Z_beta) / sqrt(n)
    mde = (z_alpha + z_beta) / math.sqrt(n)
    
    return mde

def generate_power_analysis_report(n: int = ACTUAL_N) -> Dict[str, Any]:
    """
    Generates a comprehensive power analysis report for the current project constraints.

    Returns:
        Dictionary containing MDE, power, sample size, and constraint mismatch details.
    """
    mde = calculate_minimum_detectable_effect(n)
    
    # Calculate MDE for the spec requirement (n=200) for comparison
    mde_spec = calculate_minimum_detectable_effect(SPEC_REQUIRED_N)
    
    # Constraint mismatch calculation
    constraint_mismatch = {
        "spec_requirement": SPEC_REQUIRED_N,
        "actual_sample_size": n,
        "difference": SPEC_REQUIRED_N - n,
        "power_at_spec": DEFAULT_POWER,
        "power_at_actual": DEFAULT_POWER, # We fix power and see MDE change
        "mde_at_spec": mde_spec,
        "mde_at_actual": mde,
        "mde_increase_factor": mde / mde_spec if mde_spec > 0 else float('inf'),
        "status": "CONFLICT" if n < SPEC_REQUIRED_N else "OK"
    }

    report = {
        "timestamp": datetime.utcnow().isoformat(),
        "analysis_type": "Power Analysis for Code Simplification Evaluation",
        "parameters": {
            "alpha": DEFAULT_ALPHA,
            "power": DEFAULT_POWER,
            "standard_deviation_assumption": DEFAULT_SIGMA
        },
        "sample_size_analysis": {
            "n_current": n,
            "n_spec_required": SPEC_REQUIRED_N,
            "minimum_detectable_effect_current": round(mde, 4),
            "minimum_detectable_effect_spec": round(mde_spec, 4),
            "interpretation": f"With n={n}, we can detect an effect size of {mde:.4f} standard deviations with {DEFAULT_POWER*100}% power. "
                            f"This is {mde/mde_spec:.2f}x larger than the effect size detectable with the spec-required n={SPEC_REQUIRED_N}."
        },
        "constraint_mismatch": constraint_mismatch,
        "recommendation": "Proceed with n=164 but explicitly document reduced sensitivity to small effects in the final report."
    }

    return report

def write_research_section3(report: Dict[str, Any]) -> str:
    """
    Formats the power analysis report into the required text for research.md Section 3.

    Args:
        report: The dictionary generated by generate_power_analysis_report.

    Returns:
        Formatted string content for Section 3 of research.md.
    """
    lines = [
        "## Section 3: Power Analysis",
        "",
        "This section documents the power analysis and sample size justification for the evaluation of code simplification.",
        "",
        "### Parameters",
        f"- **Significance Level (Alpha)**: {report['parameters']['alpha']}",
        f"- **Target Power**: {report['parameters']['power']}",
        f"- **Assumed Standard Deviation**: {report['parameters']['standard_deviation_assumption']} (Standardized)",
        "",
        "### Sample Size Justification",
        f"The HumanEval dataset contains **{report['sample_size_analysis']['n_current']}** problems.",
        f"The specification (FR-010) requires a minimum sample size of **{report['sample_size_analysis']['n_spec_required']}**.",
        "",
        "### Minimum Detectable Effect (MDE)",
        f"- **With n={report['sample_size_analysis']['n_current']}**: MDE = **{report['sample_size_analysis']['minimum_detectable_effect_current']}** (Cohen's d)",
        f"- **With n={report['sample_size_analysis']['n_spec_required']}**: MDE = **{report['sample_size_analysis']['minimum_detectable_effect_spec']}** (Cohen's d)",
        "",
        f"Using n=164 allows us to detect effects of size {report['sample_size_analysis']['minimum_detectable_effect_current']:.4f} with power ≥ 0.8.",
        f"This is approximately {report['sample_size_analysis']['interpretation'].split()[-3]} larger than the sensitivity achievable with the required n=200.",
        "",
        "### Constraint Mismatch (FR-010)",
        "There is a **constraint mismatch** between the available dataset size and the specification requirement:",
        "",
        "| Field | Value |",
        "| :--- | :--- |",
        f"| Spec Requirement (n) | {report['constraint_mismatch']['spec_requirement']} |",
        f"| Actual Sample Size (n) | {report['constraint_mismatch']['actual_sample_size']} |",
        f"| Difference | {report['constraint_mismatch']['difference']} |",
        f"| Status | {report['constraint_mismatch']['status']} |",
        f"| MDE Increase Factor | {report['constraint_mismatch']['mde_increase_factor']:.2f}x |",
        "",
        "### Mitigation Strategy",
        "1. **Documentation**: Explicitly state in the final report that the study is powered to detect medium-to-large effects, but may lack power to detect small effects (d < {0:.4f}).".format(report['sample_size_analysis']['minimum_detectable_effect_current']),
        "2. **Limitation Note**: The inability to meet n≥200 is due to the fixed size of the HumanEval benchmark. Results should be interpreted with this limitation in mind.",
        "3. **Confidence Intervals**: Report confidence intervals alongside p-values to better convey the precision of the estimates.",
        ""
    ]
    return "\n".join(lines)

def main():
    """
    Main entry point to generate the power analysis report and save it.
    """
    output_dir = Path("data")
    output_dir.mkdir(exist_ok=True)
    
    # Generate report
    report = generate_power_analysis_report()
    
    # Save JSON report for programmatic use
    json_path = output_dir / "power_analysis_report.json"
    with open(json_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"Power analysis report saved to: {json_path}")
    
    # Generate and print Section 3 content for research.md
    section3_content = write_research_section3(report)
    print("\n--- Content for research.md Section 3 ---\n")
    print(section3_content)
    print("\n--- End Section 3 Content ---\n")
    
    # Optional: Write to a temporary file for easy copy-paste if needed
    # (In a real pipeline, this might be merged into the main research.md)
    # For this task, we ensure the logic exists to produce the content.
    return report

if __name__ == "__main__":
    main()
