"""
Helper script to generate ground truth labels for the synthetic dataset.
This creates a separate file indicating the true statistical validity of each record.
"""
import json
import logging
import sys
from pathlib import Path
from code.src.utils.logger import get_default_logger

logger = get_default_logger()

def main():
    """Load synthetic summaries and write ground truth labels."""
    data_dir = Path("data/synthetic")
    input_file = data_dir / "synthetic_summaries.json"
    output_file = data_dir / "synthetic_ground_truth.csv"

    if not input_file.exists():
        logger.error(f"Input file not found: {input_file}. Run synthetic.py first.")
        sys.exit(1)

    with open(input_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Prepare ground truth data
    # We trust the 'is_inconsistent' field generated by synthetic.py as the ground truth
    # because it was generated with full knowledge of the underlying parameters.
    rows = []
    for record in data:
        rows.append({
            "id": record["id"],
            "url": record["url"],
            "domain": record["domain"],
            "outcome_type": record["outcome_type"],
            "ground_truth_inconsistent": record.get("is_inconsistent", False),
            "ground_truth_inconsistency_reason": record.get("inconsistency_reason", None)
        })

    # Write to CSV
    import csv
    with open(output_file, "w", newline="", encoding="utf-8") as f:
        if rows:
            fieldnames = list(rows[0].keys())
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

    logger.info(f"Ground truth written to {output_file} ({len(rows)} records).")

if __name__ == "__main__":
    main()
