"""
Static All-Layers Baseline Execution for AgenticSTS.

This module implements the "Static All-Layers" baseline strategy (T019).
It invokes the engine_runner to simulate trajectories using the 'Static' policy,
where all available layers are retrieved and processed for every turn.
"""

import os
import sys
import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add parent directory to path to allow imports from code/
# This is standard for running scripts directly from the project root
if "code" not in sys.path:
    sys.path.insert(0, str(Path(__file__).parent))

from engine_runner import load_test_set_ids, run_static_baseline

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("data/processed/baseline_static_execution.log")
    ]
)
logger = logging.getLogger(__name__)


def main():
    """
    Main entry point for the Static All-Layers Baseline execution (T019).

    Logic:
    1. Load the test set IDs (generated by T014a).
    2. Invoke the engine runner with policy="Static".
    3. Write the output to data/processed/simulation_logs_static.json.
    """
    logger.info("Starting Static All-Layers Baseline Execution (T019).")

    # Define paths relative to project root
    project_root = Path(__file__).parent.parent
    processed_dir = project_root / "data" / "processed"
    output_path = processed_dir / "simulation_logs_static.json"

    # Ensure output directory exists
    processed_dir.mkdir(parents=True, exist_ok=True)

    # Check for input file (T014a dependency)
    test_set_ids_path = processed_dir / "validation_set_ids.json"
    # Note: T017/T019/T020 typically run on the TEST set.
    # T014a produces test_set.csv and validation_set_ids.json.
    # We need the list of trajectory IDs for the TEST set.
    # The splitter (T014a) usually outputs test_set_ids.json as well, 
    # but if only validation_set_ids.json is guaranteed, we might need to adapt.
    # However, T014a description says: "Output: ... AND data/processed/validation_set_ids.json".
    # It also says "Test set is reserved for final baseline/dynamic evaluation".
    # Assuming test_set.csv exists and contains the IDs, or test_set_ids.json exists.
    
    test_set_ids_file = processed_dir / "test_set_ids.json"
    if not test_set_ids_file.exists():
        # Fallback: try to load from test_set.csv if IDs are in the first column
        test_set_csv = processed_dir / "test_set.csv"
        if test_set_csv.exists():
            import pandas as pd
            df = pd.read_csv(test_set_csv)
            # Assume first column is trajectory_id
            if 'trajectory_id' in df.columns:
                ids = df['trajectory_id'].tolist()
            else:
                ids = df.iloc[:, 0].tolist()
            logger.info(f"Loaded {len(ids)} test trajectory IDs from test_set.csv.")
        else:
            logger.error("Neither test_set_ids.json nor test_set.csv found. T014a may not have completed.")
            raise FileNotFoundError("Test set IDs not found. Please run T014a first.")
    else:
        with open(test_set_ids_file, 'r') as f:
            ids = json.load(f)
        logger.info(f"Loaded {len(ids)} test trajectory IDs from test_set_ids.json.")

    if not ids:
        logger.error("Test set is empty. Cannot run baseline.")
        raise ValueError("Test set is empty.")

    # Run the static baseline simulation
    # This function is expected to exist in engine_runner.py per the API surface
    try:
        results = run_static_baseline(
            trajectory_ids=ids,
            output_path=str(output_path)
        )
        
        if results is None:
            logger.error("run_static_baseline returned None. Simulation failed.")
            raise RuntimeError("Simulation failed to produce results.")
        
        logger.info(f"Static baseline simulation completed successfully.")
        logger.info(f"Results written to: {output_path}")
        
        # Verify the file was written
        if not output_path.exists():
            logger.error(f"Output file {output_path} was not created on disk.")
            raise RuntimeError(f"Output file {output_path} not found.")
        
        logger.info("T019 completed successfully.")
        return 0

    except Exception as e:
        logger.error(f"Error during static baseline execution: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    sys.exit(main())
