"""
Token Reduction Verification Script (T022a).

Calculates the percentage reduction in token usage between the Static and Dynamic policies
based on the aggregated baseline comparison CSV.

Enforces Success Criterion 002 (SC-002): The Dynamic policy must reduce token usage by >= 30%
compared to the Static All-Layers baseline.

Exit Codes:
  0: Verification passed (reduction >= 30%).
  1: Verification failed (reduction < 30%) or input data missing/invalid.
"""
import os
import sys
import json
import logging
import pandas as pd
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
INPUT_FILE = "data/processed/baseline_comparison.csv"
OUTPUT_FILE = "data/processed/token_reduction_verification.json"
TARGET_REDUCTION_THRESHOLD = 0.30  # 30%

def load_baseline_comparison():
    """
    Loads the baseline comparison CSV generated by T022.
    
    Expected columns: condition, win_rate, avg_tokens, std_dev_tokens
    """
    if not os.path.exists(INPUT_FILE):
        logger.error(f"Input file not found: {INPUT_FILE}")
        raise FileNotFoundError(f"Input file not found: {INPUT_FILE}")
    
    try:
        df = pd.read_csv(INPUT_FILE)
        logger.info(f"Loaded baseline comparison from {INPUT_FILE}")
        logger.info(f"Columns found: {list(df.columns)}")
        logger.info(f"Rows: {len(df)}")
        return df
    except Exception as e:
        logger.error(f"Failed to read or parse {INPUT_FILE}: {e}")
        raise

def calculate_reduction(df):
    """
    Calculates the percentage reduction in token usage.
    
    Logic: (Static_Tokens - Dynamic_Tokens) / Static_Tokens
    
    Args:
        df: DataFrame containing 'condition' and 'avg_tokens' columns.
        
    Returns:
        float: The reduction percentage (0.0 to 1.0+).
        
    Raises:
        ValueError: If required conditions are missing or tokens are zero/negative.
    """
    # Filter for specific conditions
    static_row = df[df['condition'] == 'Static']
    dynamic_row = df[df['condition'] == 'Dynamic']
    
    if static_row.empty:
        raise ValueError("Missing 'Static' condition in baseline comparison.")
    if dynamic_row.empty:
        raise ValueError("Missing 'Dynamic' condition in baseline comparison.")
        
    static_tokens = static_row['avg_tokens'].iloc[0]
    dynamic_tokens = dynamic_row['avg_tokens'].iloc[0]
    
    logger.info(f"Static Avg Tokens: {static_tokens}")
    logger.info(f"Dynamic Avg Tokens: {dynamic_tokens}")
    
    if static_tokens <= 0:
        raise ValueError(f"Static token count must be positive, got {static_tokens}")
        
    reduction = (static_tokens - dynamic_tokens) / static_tokens
    return reduction

def generate_verification_report(reduction_percent):
    """
    Generates the verification report JSON.
    
    Args:
        reduction_percent: The calculated reduction (0.0 to 1.0+).
        
    Returns:
        dict: The report content.
    """
    passed = reduction_percent >= TARGET_REDUCTION_THRESHOLD
    actual_reduction_percent = reduction_percent * 100
    
    report = {
        "passed": passed,
        "actual_reduction_percent": actual_reduction_percent,
        "threshold_percent": TARGET_REDUCTION_THRESHOLD * 100,
        "message": "Success Criterion 002 (SC-002) MET" if passed else "Success Criterion 002 (SC-002) FAILED"
    }
    
    return report

def save_report(report):
    """
    Saves the report to the output JSON file.
    
    Args:
        report: The dictionary to save.
    """
    output_path = Path(OUTPUT_FILE)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        json.dump(report, f, indent=2)
    
    logger.info(f"Verification report saved to {OUTPUT_FILE}")

def main():
    """Main entry point for the verification script."""
    try:
        logger.info("Starting Token Reduction Verification (T022a)...")
        
        # 1. Load Data
        df = load_baseline_comparison()
        
        # 2. Calculate Reduction
        reduction = calculate_reduction(df)
        
        # 3. Generate Report
        report = generate_verification_report(reduction)
        
        # 4. Save Report
        save_report(report)
        
        # 5. Enforce Hard Gate
        if not report["passed"]:
            logger.error(f"VERIFICATION FAILED: Token reduction ({report['actual_reduction_percent']:.2f}%) is below threshold ({report['threshold_percent']}%).")
            logger.error("Pipeline halted due to failure of Success Criterion 002 (SC-002).")
            sys.exit(1)
        
        logger.info(f"VERIFICATION PASSED: Token reduction is {report['actual_reduction_percent']:.2f}%.")
        sys.exit(0)
        
    except FileNotFoundError as e:
        logger.error(f"Data source missing: {e}")
        sys.exit(1)
    except ValueError as e:
        logger.error(f"Data validation error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error during verification: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()