import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime

# Import from sibling modules based on API surface
from config import load_config
from logging_config import get_logger, info, error, warning, debug

# Constants for paths relative to project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

# Ensure output directory exists
DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

logger = get_logger("compute_intervals")

def load_raw_learner_data(input_file: str) -> pd.DataFrame:
    """
    Load the raw learner data from the specified CSV file.
    Expects columns: learner_id, submission_timestamp, response_timestamp, course_id, etc.
    """
    file_path = DATA_RAW_DIR / input_file
    if not file_path.exists():
        error(f"Input file not found: {file_path}")
        raise FileNotFoundError(f"Input file not found: {file_path}")
    
    logger.info(f"Loading raw data from {file_path}")
    df = pd.read_csv(file_path)
    logger.info(f"Loaded {len(df)} records")
    return df

def calculate_intervals(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the time interval in hours between submission and response for each event.
    Adds a new column 'interval_hours' to the dataframe.
    """
    logger.info("Calculating feedback intervals...")
    
    # Ensure timestamp columns are datetime
    df['submission_timestamp'] = pd.to_datetime(df['submission_timestamp'], errors='coerce')
    df['response_timestamp'] = pd.to_datetime(df['response_timestamp'], errors='coerce')
    
    # Calculate difference in hours
    df['interval_hours'] = (df['response_timestamp'] - df['submission_timestamp']).dt.total_seconds() / 3600.0
    
    # Filter out negative intervals (data errors) or infinite values
    initial_count = len(df)
    df = df[(df['interval_hours'] >= 0) & (df['interval_hours'].notna())]
    removed_count = initial_count - len(df)
    if removed_count > 0:
        warning(f"Removed {removed_count} records with invalid (negative or NaN) intervals.")
    
    logger.info(f"Calculated intervals for {len(df)} records")
    return df

def aggregate_to_learner_level(df: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate intervals to the learner level by calculating the median interval.
    Returns a dataframe with learner_id, course_id, median_interval_hours, and count of events.
    """
    logger.info("Aggregating intervals to learner level (calculating median)...")
    
    # Group by learner and course to get representative interval per learner-course
    # Note: The task asks for "median calculation per learner". 
    # If a learner is in multiple courses, we aggregate per course first, then learner?
    # Given the context of "feedback timing" usually being course-specific, 
    # we group by learner_id AND course_id to get the median interval for that learner in that course.
    # If the requirement is strictly per learner across all courses, we would drop course_id.
    # Assuming course context matters for the analysis (as per US3 clustering by course).
    
    agg_df = df.groupby(['learner_id', 'course_id']).agg(
        median_interval_hours=('interval_hours', 'median'),
        event_count=('interval_hours', 'count')
    ).reset_index()
    
    # Filter learners with very few events if necessary (though exclusion logic handled in US1)
    # Just ensuring we have valid medians
    agg_df = agg_df[agg_df['event_count'] > 0]
    
    logger.info(f"Aggregated to {len(agg_df)} learner-course records with median intervals")
    return agg_df

def save_output(df: pd.DataFrame, output_filename: str):
    """
    Save the processed dataframe to the specified CSV file in the processed directory.
    """
    output_path = DATA_PROCESSED_DIR / output_filename
    df.to_csv(output_path, index=False)
    logger.info(f"Saved output to {output_path}")

def main():
    """
    Main entry point for the compute_intervals task.
    1. Loads raw learner data.
    2. Calculates intervals.
    3. Aggregates to learner level (median).
    4. Saves the result.
    """
    logger.info("Starting compute_intervals pipeline...")
    
    # Configuration
    # Assuming the input file is generated by US1 (preprocess.py)
    input_file = "learners_raw.csv"
    output_file = "learners_intervals.csv"
    
    try:
        # 1. Load Data
        df_raw = load_raw_learner_data(input_file)
        
        # 2. Calculate Intervals
        df_intervals = calculate_intervals(df_raw)
        
        # 3. Aggregate to Learner Level (Median)
        df_learner_median = aggregate_to_learner_level(df_intervals)
        
        # 4. Save Output
        save_output(df_learner_median, output_file)
        
        logger.info("compute_intervals pipeline completed successfully.")
        return 0
        
    except Exception as e:
        error(f"Pipeline failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    sys.exit(main())