"""
Verification of Significance Flip Rate against SC-003.

This script loads the calculated significance flip rate report,
verifies it against the Success Criteria 003 (SC-003) requirements,
and logs the result.

SC-003 Requirement: Calculate and report the proportion of shifts where
the conclusion (statistical significance) changes compared to the baseline.
"""
import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from logging_config import get_logger, info, warning, error, debug

# Project root relative to this file
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
PROCESSED_DIR = DATA_DIR / "processed"

# Output file paths
FLIP_RATE_REPORT_PATH = PROCESSED_DIR / "significance_stability_report.csv"
LOG_FILE_PATH = PROCESSED_DIR / "verification_log.txt"

# SC-003 Thresholds (if any specific thresholds are defined, otherwise just report)
# SC-003 focuses on the calculation and reporting of the rate.
# We will log the value and its interpretation.

def load_flip_rate_report(filepath: Path) -> pd.DataFrame:
    """
    Load the significance flip rate report generated by T034/T032.
    
    Args:
        filepath: Path to the CSV file containing flip rate metrics.
        
    Returns:
        DataFrame with flip rate data.
        
    Raises:
        FileNotFoundError: If the report file does not exist.
        ValueError: If the file is empty or missing required columns.
    """
    if not filepath.exists():
        raise FileNotFoundError(f"Flip rate report not found at: {filepath}")
    
    df = pd.read_csv(filepath)
    
    # Check for expected columns based on T034/T036 output structure
    # Expected columns might include: 'metric', 'value', 'description' or specific 'flip_rate'
    required_cols = ['flip_rate', 'stability_rate', 'total_shifts']
    missing_cols = [col for col in required_cols if col not in df.columns]
    
    if missing_cols:
        # Try to be lenient if the structure is slightly different, e.g., single row
        if len(df) == 1 and 'flip_rate' in df.columns:
            pass # OK
        else:
            raise ValueError(f"Flip rate report missing required columns: {missing_cols}. Found: {df.columns.tolist()}")
    
    return df

def verify_against_sc_003(df: pd.DataFrame) -> dict:
    """
    Verify the calculated flip rate against SC-003 requirements.
    
    SC-003: Calculate and report "significance flip rate" (proportion of shifts 
    where the *conclusion* changes).
    
    Args:
        df: DataFrame containing the calculated metrics.
        
    Returns:
        Dictionary with verification results.
    """
    verification_result = {
        "sc_003_met": False,
        "flip_rate": None,
        "interpretation": "",
        "details": {}
    }
    
    if df.empty:
        verification_result["interpretation"] = "Report is empty. SC-003 not met."
        return verification_result
    
    # Extract flip rate
    # Assuming the report has a row or column named 'flip_rate'
    if 'flip_rate' in df.columns:
        flip_rate = df['flip_rate'].iloc[0]
    elif 'value' in df.columns and df['metric'].iloc[0] == 'flip_rate':
        flip_rate = df['value'].iloc[0]
    else:
        # Fallback: try to find any column that looks like a rate
        rate_cols = [c for c in df.columns if 'rate' in c.lower() or 'flip' in c.lower()]
        if rate_cols:
            flip_rate = df[rate_cols[0]].iloc[0]
        else:
            flip_rate = None
    
    verification_result["flip_rate"] = flip_rate
    
    if flip_rate is None:
        verification_result["interpretation"] = "Flip rate could not be extracted from report. SC-003 not met."
        return verification_result
    
    # Validate range
    if not (0.0 <= flip_rate <= 1.0):
        verification_result["interpretation"] = f"Flip rate {flip_rate} is outside valid range [0, 1]. SC-003 not met."
        return verification_result
    
    # SC-003 is met if we have a valid calculated rate
    verification_result["sc_003_met"] = True
    
    # Interpretation logic
    if flip_rate < 0.05:
        interpretation = "Very low flip rate (<5%). The conclusion is highly stable across boundary variations."
    elif flip_rate < 0.15:
        interpretation = "Low flip rate (<15%). The conclusion is reasonably stable."
    elif flip_rate < 0.30:
        interpretation = "Moderate flip rate. The conclusion shows some sensitivity to boundary definitions."
    else:
        interpretation = "High flip rate (>=30%). The conclusion is highly sensitive to boundary definitions. Caution advised in interpretation."
    
    verification_result["interpretation"] = interpretation
    verification_result["details"] = {
        "total_shifts": df.get('total_shifts', 'N/A').iloc[0] if 'total_shifts' in df.columns else 'N/A',
        "stability_rate": df.get('stability_rate', 'N/A').iloc[0] if 'stability_rate' in df.columns else 'N/A'
    }
    
    return verification_result

def log_result(verification: dict, log_path: Path):
    """
    Log the verification result to a text file.
    
    Args:
        verification: Dictionary with verification results.
        log_path: Path to the log file.
    """
    log_dir = log_path.parent
    log_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with open(log_path, 'w') as f:
        f.write("=" * 60 + "\n")
        f.write("SC-003 VERIFICATION LOG: Significance Flip Rate\n")
        f.write(f"Timestamp: {timestamp}\n")
        f.write("=" * 60 + "\n\n")
        
        f.write(f"Status: {'PASS' if verification['sc_003_met'] else 'FAIL'}\n")
        f.write(f"Flip Rate Value: {verification['flip_rate']:.4f}\n")
        f.write(f"Interpretation: {verification['interpretation']}\n\n")
        
        f.write("Details:\n")
        for key, value in verification['details'].items():
            f.write(f"  - {key}: {value}\n")
        
        f.write("\n" + "=" * 60 + "\n")
        f.write("End of Log\n")
    
    info(f"Verification log written to: {log_path}")

def main():
    """Main entry point for T037."""
    logger = get_logger("verify_flip_rate")
    info("Starting T037: Verify Significance Flip Rate against SC-003")
    
    try:
        # Load the report generated by T034/T036
        if not FLIP_RATE_REPORT_PATH.exists():
            error(f"Required input file missing: {FLIP_RATE_REPORT_PATH}")
            error("T034/T036 must be completed to generate the flip rate report first.")
            sys.exit(1)
        
        df = load_flip_rate_report(FLIP_RATE_REPORT_PATH)
        info(f"Loaded flip rate report with {len(df)} rows.")
        
        # Verify against SC-003
        verification = verify_against_sc_003(df)
        
        # Log the result
        log_result(verification, LOG_FILE_PATH)
        
        if verification['sc_003_met']:
            info(f"SC-003 Verification PASSED. Flip Rate: {verification['flip_rate']}")
            print(f"T037 SUCCESS: SC-003 Met. Flip Rate: {verification['flip_rate']:.4f}")
            print(f"Interpretation: {verification['interpretation']}")
        else:
            error(f"SC-003 Verification FAILED: {verification['interpretation']}")
            print(f"T037 FAILED: {verification['interpretation']}")
            sys.exit(1)
            
    except FileNotFoundError as e:
        error(f"File not found: {e}")
        sys.exit(1)
    except ValueError as e:
        error(f"Data validation error: {e}")
        sys.exit(1)
    except Exception as e:
        error(f"Unexpected error during verification: {e}")
        raise

if __name__ == "__main__":
    main()