import os
import sys
import gc
import logging
import traceback
import json
import time
from pathlib import Path
from typing import Optional

from config import get_path, ensure_dirs, MAX_MEMORY_GB, MAX_RUNTIME_HOURS
from utils.logging_config import setup_logging, get_logger, configure_resource_logging
from data_ingestion import run_feature_extraction_pipeline, main as data_main
from modeling import main as model_main
from visualization import main as viz_main
from utils.validity_check import main as validity_main
from utils.final_report import main as report_main
from utils.reporting import load_results, save_results, update_results_with_hypothesis_test

logger = get_logger("main")

def check_memory_usage():
    """
    Check current memory usage. Simple implementation for demo.
    In production, use psutil or similar.
    """
    # Placeholder for memory check
    logger.info("Memory usage check skipped (demo mode).")
    return True

def run_permutation_stage(limit: Optional[int] = None):
    """
    Orchestrate the Paired Permutation Test (T028) and output results.
    This function specifically handles the modeling stage's permutation logic
    and updates the final results.json with R², MAE, and p-value.
    """
    start_time = time.time()
    logger.info("Starting Permutation Test Stage...")

    try:
        # 1. Run the core modeling pipeline (Baseline -> Residual -> Augmented)
        # This ensures the necessary models and residuals are trained before permutation.
        # We pass the limit if provided to keep the dataset size manageable for the permutation loop.
        model_main(limit=limit)

        # 2. Load the results generated by the modeling stage
        results_path = get_path("results_json")
        if not os.path.exists(results_path):
            raise FileNotFoundError(f"Modeling stage did not produce results at {results_path}")

        results = load_results(results_path)

        # 3. Ensure the permutation test was actually run by the modeling stage.
        # If the modeling stage (T028/T029) did not include the permutation results,
        # we might need to trigger it explicitly if not done in model_main.
        # Assuming model_main orchestrates T025-T027 and T028.
        # If T028 is separate, we might need to call it here.
        # Based on T028 description, it outputs to artifacts/permutation_results.json.
        # We need to merge that into results.json.

        perm_results_path = get_path("permutation_results_json")
        if os.path.exists(perm_results_path):
            with open(perm_results_path, 'r') as f:
                perm_data = json.load(f)
            
            # Merge permutation data into main results
            if "hypothesis_test" not in results:
                results["hypothesis_test"] = {}
            
            results["hypothesis_test"].update({
                "p_value": perm_data.get("p_value"),
                "iterations": perm_data.get("iterations"),
                "null_distribution_mean": perm_data.get("null_distribution_mean"),
                "observed_r2_diff": perm_data.get("observed_r2_diff")
            })

            # Determine null result flag (SC-001, SC-004)
            p_val = results["hypothesis_test"].get("p_value", 1.0)
            results["hypothesis_test"]["null_result_flag"] = p_val >= 0.05

            logger.info(f"Permutation test completed. P-value: {p_val:.4f}")
            logger.info(f"Null result flag: {results['hypothesis_test']['null_result_flag']}")

        else:
            logger.warning(f"Permutation results file not found at {perm_results_path}. "
                           "Assuming modeling stage skipped permutation or failed.")
            # If the modeling stage didn't run the permutation, we might need to run it here.
            # However, T028 is implemented in modeling.py. If model_main calls T028, this should exist.
            # If not, we raise an error to prevent silent failure.
            raise RuntimeError("Permutation results missing after modeling stage.")

        # 4. Save the updated results
        save_results(results, results_path)
        logger.info(f"Updated results saved to {results_path}")

        elapsed = time.time() - start_time
        logger.info(f"Permutation Stage completed successfully in {elapsed:.2f} seconds.")
        return True

    except Exception as e:
        logger.error(f"Permutation Stage failed: {e}")
        traceback.print_exc()
        return False

def run_full_pipeline(limit: Optional[int] = None):
    """
    Run the full data and analysis pipeline.
    Orchestrates Data Stage -> Validity Check -> Modeling Stage -> Visualization -> Report.
    """
    start_time = time.time()
    setup_logging()
    configure_resource_logging()
    
    # Ensure all required directories exist
    ensure_dirs([
        "data_processed", 
        "artifacts_logs", 
        "artifacts", 
        "state",
        "data_raw",
        "artifacts_plots"
    ])

    try:
        logger.info("Starting full pipeline...")
        
        # 1. Data Stage
        logger.info("Running Data Stage (Download -> Extract -> Link -> Merge)...")
        run_feature_extraction_pipeline(limit=limit)
        
        # 2. Validity Check
        logger.info("Running Validity Check...")
        validity_main()
        
        # 3. Modeling Stage (Orchestration of Baseline -> Residual -> Augmented -> Permutation)
        logger.info("Running Modeling Stage (Baseline -> Residual -> Augmented -> Permutation)...")
        # The modeling stage now includes the permutation test logic internally or calls the stage below.
        # We ensure the permutation results are finalized here.
        model_main(limit=limit)
        
        # 4. Visualization Stage
        logger.info("Running Visualization Stage...")
        viz_main()
        
        # 5. Final Report
        logger.info("Generating Final Report...")
        report_main()
        
        elapsed = time.time() - start_time
        logger.info(f"Pipeline completed successfully in {elapsed:.2f} seconds.")
        
    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        traceback.print_exc()
        sys.exit(1)

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Plant Disease Severity Prediction Pipeline")
    parser.add_argument("--mode", choices=["full", "dry-run"], default="full")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of records for dry-run")
    parser.add_argument("--stage", choices=["extract_features", "modeling", "visualization", "permutation"], default=None)
    parser.add_argument("--verify-resources", action="store_true", help="Verify resource usage")
    
    args = parser.parse_args()
    
    if args.verify_resources:
        # Placeholder for resource verification
        logger.info("Resource verification skipped (demo mode).")
        return

    if args.stage == "extract_features":
        run_feature_extraction_pipeline(limit=args.limit)
    elif args.stage == "modeling":
        model_main(limit=args.limit)
    elif args.stage == "visualization":
        viz_main()
    elif args.stage == "permutation":
        # Explicitly run the permutation stage orchestration
        run_permutation_stage(limit=args.limit)
    elif args.mode == "dry-run":
        logger.info("Running in dry-run mode with limit.")
        run_full_pipeline(limit=args.limit)
    else:
        run_full_pipeline(limit=args.limit)

if __name__ == "__main__":
    main()