import os
import sys
import json
import pickle
import logging
import time
import numpy as np
import pandas as pd
from pathlib import Path

# Import logging utilities from the project's logging module
try:
    from logging_config import get_module_logger
except ImportError:
    # Fallback if run directly or import path differs, though spec says use logging_config
    import logging
    def get_module_logger(name):
        return logging.getLogger(name)

# Constants
RESULTS_DIR = Path("results")
PERMUTATION_OUTPUT = RESULTS_DIR / "permutation_pvalue.json"

def load_lmm_summary():
    """Load the LMM summary CSV generated by compute_trends."""
    summary_path = Path("data/derived/lmm_summary.csv")
    if not summary_path.exists():
        raise FileNotFoundError(f"Required input file missing: {summary_path}")
    return pd.read_csv(summary_path)

def load_lrt_results():
    """Load the LRT results JSON generated by analyze_drift."""
    lrt_path = Path("data/derived/lrt_results.json")
    if not lrt_path.exists():
        raise FileNotFoundError(f"Required input file missing: {lrt_path}")
    with open(lrt_path, 'r') as f:
        return json.load(f)

def calculate_significance_at_alpha(observed_slope, null_distribution, alpha=0.05):
    """
    Calculate if the observed slope is significant given a null distribution.
    Returns True if the observed value is in the tails (two-tailed) defined by alpha.
    """
    if null_distribution.size == 0:
        return False
    
    # Two-tailed test
    lower_thresh = np.percentile(null_distribution, (alpha / 2) * 100)
    upper_thresh = np.percentile(null_distribution, (1 - alpha / 2) * 100)
    
    return (observed_slope < lower_thresh) or (observed_slope > upper_thresh)

def run_sensitivity_analysis():
    """
    Perform sensitivity analysis by sweeping alpha thresholds.
    Reads permutation results and re-evaluates significance.
    """
    if not PERMUTATION_OUTPUT.exists():
        logging.warning("Permutation results not found. Skipping sensitivity analysis.")
        return None

    with open(PERMUTATION_OUTPUT, 'r') as f:
        perm_results = json.load(f)
    
    # We need the observed slope and the null distribution to re-calculate
    # Since the JSON usually stores p-value and status, we might need to reload
    # the full permutation data if it was saved, or re-run if not.
    # For this implementation, we assume the permutation output contains enough
    # info or we re-load the raw data if available. 
    # However, per T020, the output is JSON. If the full distribution isn't there,
    # we can't re-calculate exact p-values for new alphas without the raw data.
    # We will assume the JSON contains 'iterations_run', 'p_value', 'status'.
    # To do a real sweep, we need the raw null distribution.
    # Let's assume for robustness that we might need to re-run the permutation logic
    # or that the main pipeline saved the distribution elsewhere.
    # Given the constraints, we will simulate the sweep based on the reported p-value
    # if the raw distribution is missing, but ideally we should have it.
    
    # For the purpose of T023 (convergence handling), we focus on the status flag.
    # We will report the significance at different alphas based on the reported p-value.
    p_val = perm_results.get('p_value')
    status = perm_results.get('status', 'unknown')
    
    alphas = [0.01, 0.05, 0.1]
    results = {
        'alpha_thresholds': alphas,
        'is_significant': {},
        'status': status,
        'note': 'Significance derived from reported p-value'
    }
    
    for alpha in alphas:
        results['is_significant'][str(alpha)] = (p_val < alpha) if p_val is not None else False
    
    return results

def save_sensitivity_results(results):
    """Save sensitivity analysis results to JSON."""
    if results is None:
        return
    output_path = RESULTS_DIR / "sensitivity_analysis.json"
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    logging.info(f"Sensitivity results saved to {output_path}")

def handle_convergence_failures(permutation_status):
    """
    T023: Add logic to handle permutation convergence failures.
    
    This function checks the status of the permutation test.
    If the status indicates 'approximate' (due to early termination,
    memory limits, or non-convergence), it logs a warning and ensures
    the results are flagged correctly.
    
    Args:
        permutation_status (str): The status string from the permutation run 
                                  (e.g., 'exact', 'approximate', 'failed').
    
    Returns:
        bool: True if the result is valid for use (even if approximate), 
              False if the result is critically failed and should not be used.
    """
    if permutation_status == 'exact':
        logging.info("Permutation test completed exactly.")
        return True
    
    elif permutation_status == 'approximate':
        logging.warning("Permutation test result is APPROXIMATE. Convergence was not reached or early termination occurred.")
        logging.warning("Results should be interpreted with caution.")
        # The task is to flag it, not to reject it. We return True to allow
        # the pipeline to continue, but the flag is set in the output.
        return True
    
    elif permutation_status == 'failed':
        logging.error("Permutation test FAILED completely. Results are invalid.")
        return False
    
    else:
        logging.error(f"Unknown permutation status: {permutation_status}. Assuming failure.")
        return False

def main():
    """
    Main entry point for robustness checks.
    Orchestrates sensitivity analysis and handles convergence flags.
    """
    logger = get_module_logger(__name__)
    logger.info("Starting robustness analysis (T023: Convergence Handling & Sensitivity)")
    
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    
    # 1. Load LRT results to get the observed drift if needed (though T020 handles p-value)
    try:
        lrt_data = load_lrt_results()
        logger.info("Loaded LRT results.")
    except FileNotFoundError as e:
        logger.error(f"Cannot proceed without LRT results: {e}")
        sys.exit(1)
    
    # 2. Check for existing permutation results (produced by T020)
    # T023 focuses on the logic that handles the 'approximate' flag if it exists
    if PERMUTATION_OUTPUT.exists():
        with open(PERMUTATION_OUTPUT, 'r') as f:
            perm_data = json.load(f)
        
        status = perm_data.get('status', 'unknown')
        
        # T023 Logic: Handle convergence failures and flag results
        is_valid = handle_convergence_failures(status)
        
        if not is_valid:
            logger.critical("Permutation test failed. Stopping robustness analysis.")
            # We might want to write a failure state, but for now we exit
            sys.exit(1)
        
        if status == 'approximate':
            # Ensure the flag is preserved or updated in the output if needed
            # The task requires flagging results as "approximate".
            # The data is already loaded with this flag, we just logged it.
            logger.info(f"Proceeding with approximate results. Status: {status}")
    else:
        logger.warning("No permutation results found. Skipping convergence check.")
        # If T020 hasn't run, we can't check convergence.
        # In a full pipeline, T020 would run first.
        # For this task, we assume T020 ran and produced the file.
    
    # 3. Run Sensitivity Analysis
    try:
        sens_results = run_sensitivity_analysis()
        if sens_results:
            save_sensitivity_results(sens_results)
            logger.info("Sensitivity analysis completed.")
        else:
            logger.warning("Sensitivity analysis could not be performed.")
    except Exception as e:
        logger.error(f"Error during sensitivity analysis: {e}")
        # Non-fatal, continue

    logger.info("Robustness analysis finished.")

if __name__ == "__main__":
    main()