"""
Contract test for statistical report schema (Task T031).

This test verifies that the statistical analysis report generated by
code/analysis/stats.py conforms to the required schema defined in the
project specifications.

The schema is derived from the requirements in specs/001-dynamic-state-injection/
and the task description for T038.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, List

import pytest

# Import the path to the expected output file
# This assumes the stats.py script has been run and generated the report
REPORT_PATH = Path("data/results/statistical_analysis_report.json")

# Define the expected schema structure
# Based on T038 requirements: t-statistic, p-value, Cohen's d, is_significant flag,
# and Holm-Bonferroni correction details.
EXPECTED_SCHEMA = {
    "type": "object",
    "required": [
        "report_metadata",
        "normality_test",
        "statistical_test",
        "effect_size",
        "multiple_comparison_correction",
        "summary"
    ],
    "properties": {
        "report_metadata": {
            "type": "object",
            "required": ["timestamp", "condition_a", "condition_b", "num_comparisons"],
            "properties": {
                "timestamp": {"type": "string"},
                "condition_a": {"type": "string"},
                "condition_b": {"type": "string"},
                "num_comparisons": {"type": "integer", "minimum": 1}
            }
        },
        "normality_test": {
            "type": "object",
            "required": ["method", "p_value", "is_normal"],
            "properties": {
                "method": {"type": "string", "enum": ["Shapiro-Wilk"]},
                "p_value": {"type": "number"},
                "is_normal": {"type": "boolean"}
            }
        },
        "statistical_test": {
            "type": "object",
            "required": ["method", "test_statistic", "p_value", "is_significant"],
            "properties": {
                "method": {"type": "string", "enum": ["Paired t-test", "Wilcoxon signed-rank test"]},
                "test_statistic": {"type": "number"},
                "p_value": {"type": "number"},
                "is_significant": {"type": "boolean"}
            }
        },
        "effect_size": {
            "type": "object",
            "required": ["metric", "value"],
            "properties": {
                "metric": {"type": "string", "enum": ["Cohen's d"]},
                "value": {"type": "number"}
            }
        },
        "multiple_comparison_correction": {
            "type": "object",
            "required": ["method", "adjusted_p_values"],
            "properties": {
                "method": {"type": "string", "enum": ["Holm-Bonferroni"]},
                "adjusted_p_values": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["comparison_id", "raw_p_value", "adjusted_p_value"],
                        "properties": {
                            "comparison_id": {"type": "string"},
                            "raw_p_value": {"type": "number"},
                            "adjusted_p_value": {"type": "number"}
                        }
                    }
                }
            }
        },
        "summary": {
            "type": "object",
            "required": ["conclusion", "key_finding"],
            "properties": {
                "conclusion": {"type": "string"},
                "key_finding": {"type": "string"}
            }
        }
    }
}

def load_report() -> Dict[str, Any]:
    """Load the statistical report from disk."""
    if not REPORT_PATH.exists():
        raise FileNotFoundError(
            f"Statistical report not found at {REPORT_PATH}. "
            "Please run code/analysis/stats.py to generate the report first."
        )
    
    with open(REPORT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def validate_schema(data: Dict[str, Any], schema: Dict[str, Any], path: str = "") -> List[str]:
    """
    Recursively validate data against a JSON schema.
    Returns a list of error messages.
    """
    errors = []
    
    # Check type
    if "type" in schema:
        expected_type = schema["type"]
        actual_type = type(data).__name__
        
        type_mapping = {
            "object": "dict",
            "array": "list",
            "string": "str",
            "number": (int, float),
            "integer": int,
            "boolean": bool
        }
        
        if expected_type in type_mapping:
            expected = type_mapping[expected_type]
            if not isinstance(data, expected):
                errors.append(f"{path}: Expected {expected_type}, got {actual_type}")
                return errors  # Can't validate further if type is wrong
        
        # Special handling for number which can be int or float
        if expected_type == "number" and isinstance(data, bool):
            errors.append(f"{path}: Expected number, got boolean")
            return errors
    
    # Check required fields for objects
    if schema.get("type") == "object" and isinstance(data, dict):
        required = schema.get("required", [])
        for field in required:
            if field not in data:
                errors.append(f"{path}: Missing required field '{field}'")
        
        # Validate properties
        properties = schema.get("properties", {})
        for key, value in data.items():
            if key in properties:
                sub_errors = validate_schema(value, properties[key], f"{path}.{key}")
                errors.extend(sub_errors)
            else:
                # Optional fields are allowed, but we could log them
                pass
    
    # Check array items
    if schema.get("type") == "array" and isinstance(data, list):
        items_schema = schema.get("items")
        if items_schema:
            for i, item in enumerate(data):
                sub_errors = validate_schema(item, items_schema, f"{path}[{i}]")
                errors.extend(sub_errors)
    
    # Check enum
    if "enum" in schema:
        if data not in schema["enum"]:
            errors.append(f"{path}: Value '{data}' not in enum {schema['enum']}")
    
    # Check minimum for integers
    if "minimum" in schema and isinstance(data, (int, float)):
        if data < schema["minimum"]:
            errors.append(f"{path}: Value {data} is less than minimum {schema['minimum']}")
    
    return errors

class TestStatisticalReportSchema:
    """Contract tests for the statistical analysis report."""

    def test_report_file_exists(self):
        """Verify the report file exists."""
        assert REPORT_PATH.exists(), f"Report file not found at {REPORT_PATH}"

    def test_report_is_valid_json(self):
        """Verify the report is valid JSON."""
        try:
            load_report()
        except json.JSONDecodeError as e:
            pytest.fail(f"Report is not valid JSON: {e}")

    def test_report_conforms_to_schema(self):
        """Verify the report structure matches the expected schema."""
        report = load_report()
        errors = validate_schema(report, EXPECTED_SCHEMA, "root")
        
        if errors:
            error_msg = "\n".join(errors)
            pytest.fail(f"Report schema validation failed:\n{error_msg}")

    def test_normality_test_has_correct_method(self):
        """Verify the normality test uses Shapiro-Wilk."""
        report = load_report()
        assert report["normality_test"]["method"] == "Shapiro-Wilk", \
            "Normality test method must be 'Shapiro-Wilk'"

    def test_statistical_test_method_is_valid(self):
        """Verify the statistical test is either t-test or Wilcoxon."""
        report = load_report()
        method = report["statistical_test"]["method"]
        valid_methods = ["Paired t-test", "Wilcoxon signed-rank test"]
        assert method in valid_methods, \
            f"Statistical test method must be one of {valid_methods}, got '{method}'"

    def test_multiple_comparison_correction_is_holm_bonferroni(self):
        """Verify Holm-Bonferroni correction is applied."""
        report = load_report()
        assert report["multiple_comparison_correction"]["method"] == "Holm-Bonferroni", \
            "Multiple comparison correction must use 'Holm-Bonferroni'"

    def test_effect_size_is_cohens_d(self):
        """Verify effect size is reported as Cohen's d."""
        report = load_report()
        assert report["effect_size"]["metric"] == "Cohen's d", \
            "Effect size metric must be 'Cohen's d'"

    def test_summary_contains_conclusion(self):
        """Verify the summary includes a conclusion."""
        report = load_report()
        assert "conclusion" in report["summary"], "Summary must contain a 'conclusion'"
        assert "key_finding" in report["summary"], "Summary must contain a 'key_finding'"
        assert len(report["summary"]["conclusion"]) > 0, "Conclusion cannot be empty"
        assert len(report["summary"]["key_finding"]) > 0, "Key finding cannot be empty"

    def test_adjusted_p_values_exist(self):
        """Verify adjusted p-values are present for all comparisons."""
        report = load_report()
        corrections = report["multiple_comparison_correction"]["adjusted_p_values"]
        assert len(corrections) > 0, "There must be at least one adjusted p-value"
        
        for item in corrections:
            assert "comparison_id" in item, "Each correction must have a 'comparison_id'"
            assert "raw_p_value" in item, "Each correction must have a 'raw_p_value'"
            assert "adjusted_p_value" in item, "Each correction must have an 'adjusted_p_value'"

    def test_is_significant_flag_matches_p_value(self):
        """Verify the is_significant flag is consistent with the p-value."""
        report = load_report()
        p_value = report["statistical_test"]["p_value"]
        is_significant = report["statistical_test"]["is_significant"]
        
        # Standard significance threshold is 0.05
        expected_significance = p_value < 0.05
        
        assert is_significant == expected_significance, \
            f"is_significant ({is_significant}) does not match p-value ({p_value}) < 0.05"

if __name__ == "__main__":
    # Allow running the tests directly
    pytest.main([__file__, "-v"])