"""
Module to validate pairing rates between expression and metabolite data.
Implements FR-009 and SC-005: Abort with E-PAIRING if pairing rate < 95%.
"""
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, Tuple, Optional

# Import from local project API surface
from exceptions import E_PAIRING

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('logs/pairing_validation.log')
    ]
)
logger = logging.getLogger(__name__)

def load_pairing_statistics(pairing_log_path: str) -> Dict[str, Any]:
    """
    Load pairing statistics from the pairing log generated by T004.
    
    Args:
        pairing_log_path: Path to the pairing log JSON file
        
    Returns:
        Dictionary containing pairing statistics
    """
    path = Path(pairing_log_path)
    if not path.exists():
        raise FileNotFoundError(f"Pairing log not found at {pairing_log_path}")
    
    with open(path, 'r') as f:
        data = json.load(f)
    
    return data

def validate_pairing_rate(pairing_stats: Dict[str, Any], threshold: float = 0.95) -> Tuple[bool, float, str]:
    """
    Validate that the pairing rate meets the minimum threshold.
    
    Args:
        pairing_stats: Dictionary containing pairing statistics
        threshold: Minimum required pairing rate (default 0.95 for 95%)
        
    Returns:
        Tuple of (is_valid, actual_rate, message)
    """
    total_samples = pairing_stats.get('total_samples', 0)
    paired_samples = pairing_stats.get('paired_samples', 0)
    
    if total_samples == 0:
        raise ValueError("Total sample count is zero; cannot calculate pairing rate.")
    
    pairing_rate = paired_samples / total_samples
    
    is_valid = pairing_rate >= threshold
    message = f"Pairing rate: {pairing_rate:.2%} ({paired_samples}/{total_samples})"
    
    if is_valid:
        message += f" - PASSED (threshold: {threshold:.2%})"
    else:
        message += f" - FAILED (threshold: {threshold:.2%})"
    
    return is_valid, pairing_rate, message

def log_validation_results(
    pairing_rate: float, 
    is_valid: bool, 
    message: str, 
    log_path: str = 'logs/validation_results.json'
) -> None:
    """
    Log validation results to a JSON file.
    
    Args:
        pairing_rate: The calculated pairing rate
        is_valid: Whether the rate passed the threshold
        message: Human-readable message
        log_path: Path to the log file
    """
    log_entry = {
        'pairing_rate': pairing_rate,
        'is_valid': is_valid,
        'message': message,
        'threshold': 0.95
    }
    
    log_path_obj = Path(log_path)
    log_path_obj.parent.mkdir(parents=True, exist_ok=True)
    
    with open(log_path_obj, 'w') as f:
        json.dump(log_entry, f, indent=2)
    
    logger.info(f"Validation results logged to {log_path}")

def run_pairing_validation(
    pairing_log_path: str = 'data/raw/pairing_log.json',
    threshold: float = 0.95
) -> bool:
    """
    Main function to run pairing validation.
    
    This function:
    1. Loads pairing statistics from the pairing log
    2. Calculates the pairing rate
    3. Validates against the threshold (95%)
    4. Raises E-PAIRING if validation fails
    
    Args:
        pairing_log_path: Path to the pairing log file
        threshold: Minimum required pairing rate
        
    Returns:
        True if validation passes
        
    Raises:
        E_PAIRING: If pairing rate is below threshold
    """
    logger.info("Starting pairing validation...")
    logger.info(f"Loading pairing statistics from {pairing_log_path}")
    
    # Load pairing statistics
    pairing_stats = load_pairing_statistics(pairing_log_path)
    
    # Validate pairing rate
    is_valid, pairing_rate, message = validate_pairing_rate(pairing_stats, threshold)
    
    logger.info(message)
    
    # Log results
    log_validation_results(pairing_rate, is_valid, message)
    
    if not is_valid:
        logger.error(f"Pairing rate {pairing_rate:.2%} is below threshold {threshold:.2%}")
        logger.error("ABORTING with E-PAIRING error code")
        raise E_PAIRING(
            f"Pairing rate {pairing_rate:.2%} is below required threshold {threshold:.2%}. "
            f"Project aborted per FR-009 and SC-005. "
            f"Details: {message}"
        )
    
    logger.info("Pairing validation PASSED")
    return True

def main():
    """Main entry point for the validation script."""
    try:
        # Default paths based on project structure
        pairing_log_path = 'data/raw/pairing_log.json'
        
        # Check if pairing log exists
        if not Path(pairing_log_path).exists():
            logger.error(f"Pairing log not found at {pairing_log_path}")
            logger.error("Please run T004 (pair_samples) first to generate the pairing log.")
            sys.exit(1)
        
        # Run validation
        run_pairing_validation(pairing_log_path)
        
        logger.info("Validation completed successfully")
        sys.exit(0)
        
    except E_PAIRING as e:
        logger.error(f"Pairing validation failed: {e}")
        sys.exit(2)
    except Exception as e:
        logger.error(f"Unexpected error during validation: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
