"""
Regression Analysis Module for T031.

Performs Multiple Regression (Spec FR-005) to assess the sensitivity of
regression coefficients to dataset subset selection.

Outcome: empirical_variance
Predictors: condition_number, violation_severity (encoded), interaction term.
"""
import json
import os
import sys
import argparse
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Constants for artifact paths
ARTIFACT_DIR = Path("artifacts")
STABILITY_DIR = ARTIFACT_DIR / "stability"
PROFILES_DIR = ARTIFACT_DIR / "profiles"
META_ANALYSIS_DIR = ARTIFACT_DIR / "meta_analysis"

# Ensure output directory exists
META_ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

def load_json_file(filepath: Path) -> Dict[str, Any]:
    """Load a JSON file and return its contents as a dictionary."""
    if not filepath.exists():
        raise FileNotFoundError(f"File not found: {filepath}")
    with open(filepath, "r") as f:
        return json.load(f)

def load_stability_data() -> pd.DataFrame:
    """
    Load coefficient standard deviation (empirical variance proxy) from stability results.
    Expects artifacts/stability/coefficient_sd.json or similar structure.
    """
    # T028 outputs StabilityResult CSV/JSON. We look for the standard output.
    # Assuming the structure generated by T028/T048 is a JSON list of dicts or a CSV.
    # We prioritize the JSON file if it exists, otherwise CSV.
    json_path = STABILITY_DIR / "coefficient_sd.json"
    csv_path = STABILITY_DIR / "coefficient_sd.csv"

    if json_path.exists():
        data = load_json_file(json_path)
        if isinstance(data, list):
            df = pd.DataFrame(data)
        elif isinstance(data, dict):
            # If it's a nested structure, flatten or select relevant keys
            # Assuming structure: { "dataset_name": { "tier": { "coef_name": sd } } }
            # We need to flatten this to a row-per-observation format for regression.
            rows = []
            for ds_name, tiers in data.items():
                for tier_name, coeffs in tiers.items():
                    if isinstance(coeffs, dict):
                        for coef_name, sd_val in coeffs.items():
                            rows.append({
                                "dataset_name": ds_name,
                                "tier": tier_name,
                                "coefficient_name": coef_name,
                                "empirical_sd": sd_val
                            })
            df = pd.DataFrame(rows)
    elif csv_path.exists():
        df = pd.read_csv(csv_path)
    else:
        raise FileNotFoundError(
            f"No stability data found. Expected {json_path} or {csv_path}"
        )

    return df

def load_profiles_data() -> pd.DataFrame:
    """
    Load dataset profiles containing condition_number and violation_severity.
    Expects artifacts/profiles/ directory containing JSON files or a consolidated profile.
    """
    profile_files = list(PROFILES_DIR.glob("*.json"))
    if not profile_files:
        raise FileNotFoundError(f"No profile files found in {PROFILES_DIR}")

    profiles = []
    for f in profile_files:
        try:
            data = load_json_file(f)
            # Handle potential list of profiles or single profile dict
            if isinstance(data, list):
                profiles.extend(data)
            elif isinstance(data, dict):
                profiles.append(data)
        except json.JSONDecodeError:
            continue

    if not profiles:
        raise ValueError("No valid profile data loaded.")

    df = pd.DataFrame(profiles)
    # Ensure standard column names if they vary slightly
    if "dataset_name" not in df.columns and "name" in df.columns:
        df.rename(columns={"name": "dataset_name"}, inplace=True)

    return df

def encode_severity(severity: str) -> int:
    """
    Encode violation severity string to numeric ordinal.
    Low -> 0, Medium -> 1, High -> 2
    """
    mapping = {"Low": 0, "Medium": 1, "High": 2, "low": 0, "medium": 1, "high": 2}
    return mapping.get(severity, 0)

def prepare_regression_data(
    stability_df: pd.DataFrame,
    profiles_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Merge stability data with profile data to create the regression dataset.
    Outcome: empirical_variance (calculated as sd^2)
    Predictors: condition_number, violation_severity (encoded), interaction.
    """
    # Merge on dataset_name
    # We assume stability_df has 'dataset_name' and profiles_df has 'dataset_name'
    merged = pd.merge(
        stability_df,
        profiles_df,
        on="dataset_name",
        how="inner"
    )

    if merged.empty:
        raise ValueError("No matching data found between stability and profiles.")

    # Calculate empirical variance from standard deviation
    # The spec asks for 'empirical_variance' as the outcome.
    # If the stability data provides SD, we square it to get Variance.
    if "empirical_sd" in merged.columns:
        merged["empirical_variance"] = merged["empirical_sd"] ** 2
    elif "coefficient_sd" in merged.columns:
        merged["empirical_variance"] = merged["coefficient_sd"] ** 2
    else:
        raise ValueError("Stability data must contain a standard deviation column (e.g., 'empirical_sd').")

    # Encode severity
    merged["severity_encoded"] = merged["violation_severity"].apply(encode_severity)

    # Create interaction term: condition_number * severity_encoded
    merged["interaction_term"] = merged["condition_number"] * merged["severity_encoded"]

    return merged

def run_multiple_regression(df: pd.DataFrame) -> Tuple[Dict[str, Any], Any]:
    """
    Perform Multiple Regression using statsmodels.
    Model: empirical_variance ~ condition_number + severity_encoded + interaction_term
    """
    # Define predictors
    feature_cols = ["condition_number", "severity_encoded", "interaction_term"]

    # Handle missing values in predictors or outcome
    valid_cols = feature_cols + ["empirical_variance"]
    df_clean = df[valid_cols].dropna()

    if len(df_clean) < len(feature_cols) + 1:
        raise ValueError(f"Not enough data points for regression. Need > {len(feature_cols)}, got {len(df_clean)}.")

    X = df_clean[feature_cols]
    y = df_clean["empirical_variance"]

    # Add constant for intercept
    X = sm.add_constant(X)

    # Fit OLS
    model = sm.OLS(y, X)
    results = model.fit()

    # Extract results for JSON output
    summary_dict = {
        "rsquared": results.rsquared,
        "rsquared_adj": results.rsquared_adj,
        "f_pvalue": results.f_pvalue,
        "coefficients": {}
    }

    for param_name, param in results.params.items():
        summary_dict["coefficients"][param_name] = {
            "estimate": float(param),
            "std_err": float(results.bse[param_name]),
            "t_stat": float(results.tvalues[param_name]),
            "p_value": float(results.pvalues[param_name])
        }

    return summary_dict, results

def main(args: Optional[List[str]] = None) -> None:
    """Main entry point for the regression analysis task."""
    parser = argparse.ArgumentParser(description="Run Multiple Regression Analysis (T031)")
    parser.add_argument(
        "--stability-path",
        type=str,
        default=str(STABILITY_DIR / "coefficient_sd.json"),
        help="Path to stability results JSON/CSV"
    )
    parser.add_argument(
        "--profiles-path",
        type=str,
        default=str(PROFILES_DIR),
        help="Path to profiles directory"
    )
    parser.add_argument(
        "--output-path",
        type=str,
        default=str(META_ANALYSIS_DIR / "interaction_model.json"),
        help="Path for output JSON"
    )

    parsed_args = parser.parse_args(args)

    print(f"Loading stability data from {parsed_args.stability_path}...")
    stability_df = load_stability_data()

    print(f"Loading profile data from {parsed_args.profiles_path}...")
    # load_profiles_data scans the directory
    profiles_df = load_profiles_data()

    print("Preparing regression dataset...")
    regression_df = prepare_regression_data(stability_df, profiles_df)

    print(f"Running Multiple Regression on {len(regression_df)} observations...")
    try:
        summary, results = run_multiple_regression(regression_df)
    except Exception as e:
        print(f"Error running regression: {e}")
        sys.exit(1)

    output_path = Path(parsed_args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Add metadata to the output
    final_output = {
        "task_id": "T031",
        "model_specification": {
            "outcome": "empirical_variance",
            "predictors": ["condition_number", "violation_severity", "interaction_term"],
            "formula": "empirical_variance ~ condition_number + violation_severity + (condition_number * violation_severity)"
        },
        "sample_size": len(regression_df),
        "model_results": summary
    }

    with open(output_path, "w") as f:
        json.dump(final_output, f, indent=2)

    print(f"Regression analysis complete. Results saved to {output_path}")
    print(f"R-squared: {summary['rsquared']:.4f}")
    print(f"Interaction Term p-value: {summary['coefficients']['interaction_term']['p_value']:.4f}")

if __name__ == "__main__":
    main()
