"""
Contract test for dynamic score output structure.

This test verifies that the dynamic score output generated by the APPO rollout
(T024) matches the schema defined in contracts/output_schema.yaml (T011).

It ensures:
1. The JSON file exists at the expected path.
2. The top-level structure is a list of records.
3. Each record contains the required fields: task_id, position, score, type.
4. Types and value ranges match the schema constraints.
"""
import json
import os
import sys
import unittest
from pathlib import Path
from typing import Any, Dict, List

# Add project root to path to allow imports if needed, though this test
# primarily validates file content against a known schema.
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Path to the output file generated by T024
OUTPUT_PATH = PROJECT_ROOT / "data" / "processed" / "dynamic_scores.json"

# Path to the schema definition (T011)
SCHEMA_PATH = PROJECT_ROOT / "contracts" / "output_schema.yaml"


class TestDynamicOutputContract(unittest.TestCase):
    """Contract tests for dynamic branching score output."""

    def setUp(self):
        """Load the output data and schema before each test."""
        self.output_path = OUTPUT_PATH
        self.schema_path = SCHEMA_PATH
        
        # Check if output file exists
        if not self.output_path.exists():
            self.skipTest(f"Output file not found at {self.output_path}. "
                          "Ensure T024 has been executed to generate dynamic_scores.json.")
        
        with open(self.output_path, "r", encoding="utf-8") as f:
            self.data = json.load(f)
        
        # Load schema if available for reference (though we hardcode expectations here
        # based on T011 description for robustness)
        if self.schema_path.exists():
            import yaml
            with open(self.schema_path, "r", encoding="utf-8") as f:
                self.schema = yaml.safe_load(f)
        else:
            self.schema = None

    def test_file_is_valid_json_list(self):
        """Verify the output is a JSON list."""
        self.assertIsInstance(self.data, list, 
                              "Dynamic scores output must be a list of records.")
        self.assertGreater(len(self.data), 0, 
                           "Dynamic scores output must contain at least one record.")

    def test_record_structure(self):
        """Verify each record has the required fields: task_id, position, score, type."""
        required_fields = ["task_id", "position", "score", "type"]
        
        for idx, record in enumerate(self.data):
            with self.subTest(record_index=idx):
                self.assertIsInstance(record, dict, 
                                      f"Record at index {idx} must be a dictionary.")
                
                for field in required_fields:
                    self.assertIn(field, record, 
                                  f"Record at index {idx} is missing required field: {field}")

    def test_field_types_and_constraints(self):
        """Verify data types and constraints for each field."""
        for idx, record in enumerate(self.data):
            with self.subTest(record_index=idx):
                # task_id: str
                self.assertIsInstance(record["task_id"], str, 
                                      f"task_id at index {idx} must be a string.")
                self.assertGreater(len(record["task_id"]), 0, 
                                   f"task_id at index {idx} cannot be empty.")
                
                # position: int
                self.assertIsInstance(record["position"], int, 
                                      f"position at index {idx} must be an integer.")
                self.assertGreaterEqual(record["position"], 0, 
                                        f"position at index {idx} cannot be negative.")
                
                # score: float
                self.assertIsInstance(record["score"], (int, float), 
                                      f"score at index {idx} must be a number.")
                # Scores are cumulative binary rewards, typically in [0, 1] or similar range,
                # but schema just says float. We check it's a valid number.
                self.assertTrue(isinstance(record["score"], (int, float)), 
                                f"score at index {idx} must be a valid number.")
                
                # type: str, must be "dynamic"
                self.assertIsInstance(record["type"], str, 
                                      f"type at index {idx} must be a string.")
                self.assertEqual(record["type"], "dynamic", 
                                 f"type at index {idx} must be 'dynamic' for dynamic scores.")

    def test_consistency_with_static_schema_format(self):
        """
        Verify that the dynamic output structure aligns with the static output structure
        as per T011 requirements (same top-level keys, compatible types).
        """
        # We assume static output follows the same list-of-records pattern.
        # The key alignment requirement is that 'task_id' and 'position' exist
        # and are compatible types for joining later.
        
        static_path = PROJECT_ROOT / "data" / "processed" / "static_scores.json"
        if not static_path.exists():
            self.skipTest("Static scores file not found. Cannot verify alignment.")
        
        with open(static_path, "r", encoding="utf-8") as f:
            static_data = json.load(f)
        
        # Check that both are lists
        self.assertIsInstance(static_data, list, "Static scores must be a list.")
        
        # Check that dynamic records have the same primary key type as static
        # (Both should have 'task_id' as string and 'position' as int)
        if len(self.data) > 0 and len(static_data) > 0:
            dynamic_record = self.data[0]
            static_record = static_data[0]
            
            self.assertIsInstance(dynamic_record["task_id"], type(static_record["task_id"]),
                                  "task_id types must match between dynamic and static outputs.")
            self.assertIsInstance(dynamic_record["position"], type(static_record["position"]),
                                  "position types must match between dynamic and static outputs.")

if __name__ == "__main__":
    unittest.main()