import json
import logging
import os
import sys
from typing import Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_model_fits(filepath: str) -> Dict[str, Any]:
    """
    Load the model fits JSON file generated by analysis.
    
    Args:
        filepath: Path to data/model_fits.json
        
    Returns:
        Dictionary containing model fit results
        
    Raises:
        FileNotFoundError: If the file does not exist
        json.JSONDecodeError: If the file is not valid JSON
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Model fits file not found: {filepath}")
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    logger.info(f"Loaded model fits from {filepath}")
    return data

def generate_captions(data: Dict[str, Any]) -> list:
    """
    Generate caption strings for plots based on model fit data.
    
    The captions are strictly data-driven, avoiding subjective metaphors.
    They summarize the key statistical findings for each grid analysis.
    
    Args:
        data: Dictionary containing model fit results (plan_beta, spec_beta, p-values, etc.)
        
    Returns:
        List of formatted caption strings
    """
    captions = []
    
    # Caption for Plan-Primary Analysis (Deviation Ratio)
    plan_beta = data.get('plan_beta')
    plan_beta_se = data.get('plan_beta_se')
    plan_r_squared = data.get('plan_r_squared')
    plan_ks_p = data.get('plan_ks_p')
    
    if plan_beta is not None:
        plan_caption = (
            f"Plan-Primary Analysis: Deviation ratio R scales as h^{plan_beta:.4f} "
            f"(SE: {plan_beta_se:.4f}, R²: {plan_r_squared:.4f}). "
            f"Kolmogorov-Smirnov test p-value: {plan_ks_p:.4f}."
        )
    else:
        plan_caption = (
            f"Plan-Primary Analysis: Power-law regression failed to converge. "
            f"KS test p-value: {plan_ks_p:.4f}."
        )
    captions.append(plan_caption)
    
    # Caption for Spec-Mandatory Analysis (Raw Density)
    spec_beta = data.get('spec_beta')
    spec_beta_se = data.get('spec_beta_se')
    spec_r_squared = data.get('spec_r_squared')
    spec_chi2_p = data.get('spec_chi2_p')
    
    if spec_beta is not None:
        spec_caption = (
            f"Spec-Mandatory Analysis: Raw density ρ scales as h^{spec_beta:.4f} "
            f"(SE: {spec_beta_se:.4f}, R²: {spec_r_squared:.4f}). "
            f"Chi-Square goodness-of-fit p-value: {spec_chi2_p:.4f}."
        )
    else:
        spec_caption = (
            f"Spec-Mandatory Analysis: Power-law regression failed to converge. "
            f"Chi-Square test p-value: {spec_chi2_p:.4f}."
        )
    captions.append(spec_caption)
    
    # General summary caption
    summary_caption = (
        f"Analysis of smooth number distribution across short intervals. "
        f"Plan grid (fixed h) vs. Spec grid (x^α intervals). "
        f"Comparing observed densities against Dickman function predictions."
    )
    captions.append(summary_caption)
    
    return captions

def write_captions(captions: list, output_path: str) -> None:
    """
    Write generated captions to a text file.
    
    Args:
        captions: List of caption strings
        output_path: Path to the output file (e.g., data/captions.txt)
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        for i, caption in enumerate(captions, 1):
            f.write(f"Caption {i}:\n{caption}\n\n")
    
    logger.info(f"Captions written to {output_path}")

def main():
    """Main entry point for generating captions."""
    # Define paths relative to project root
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    model_fits_path = os.path.join(project_root, 'data', 'model_fits.json')
    output_path = os.path.join(project_root, 'data', 'captions.txt')
    
    try:
        # Load model fits
        data = load_model_fits(model_fits_path)
        
        # Generate captions
        captions = generate_captions(data)
        
        # Write captions
        write_captions(captions, output_path)
        
        logger.info("Caption generation completed successfully.")
        
    except FileNotFoundError as e:
        logger.error(f"Error: {e}")
        logger.error("Ensure that T029 has been completed and data/model_fits.json exists.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        logger.error(f"Error: Invalid JSON in model fits file: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error during caption generation: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
