import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, Tuple, Optional, List
import pandas as pd
import numpy as np
from scipy import stats

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
METRIC_COLUMNS = ['cc', 'halstead', 'loc']
TARGET_COLUMN = 'is_buggy'

def load_features_csv(file_path: str) -> pd.DataFrame:
    """
    Load the features CSV file generated by the ingestion pipeline.
    
    Args:
        file_path: Path to the features.csv file
        
    Returns:
        DataFrame containing the features and target variable
        
    Raises:
        FileNotFoundError: If the file does not exist
        ValueError: If required columns are missing
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Features file not found: {file_path}")
    
    df = pd.read_csv(file_path)
    
    required_cols = METRIC_COLUMNS + [TARGET_COLUMN]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns: {missing_cols}")
    
    logger.info(f"Loaded features from {file_path}: {df.shape[0]} rows, {df.shape[1]} columns")
    return df

def compute_point_biserial(df: pd.DataFrame, metric_name: str) -> Tuple[float, float]:
    """
    Compute Point-Biserial correlation between a metric and the binary target.
    
    The Point-Biserial correlation is a special case of the Pearson correlation
    used when one variable is continuous and the other is dichotomous (binary).
    
    Args:
        df: DataFrame containing the data
        metric_name: Name of the metric column to correlate with target
        
    Returns:
        Tuple of (correlation coefficient, p-value)
        
    Raises:
        ValueError: If the metric column or target column is missing or invalid
    """
    if metric_name not in df.columns:
        raise ValueError(f"Metric column '{metric_name}' not found in DataFrame")
    
    if TARGET_COLUMN not in df.columns:
        raise ValueError(f"Target column '{TARGET_COLUMN}' not found in DataFrame")
    
    # Remove rows with NaN values in the metric or target
    clean_data = df[[metric_name, TARGET_COLUMN]].dropna()
    
    if len(clean_data) < 2:
        logger.warning(f"Not enough data to compute Point-Biserial for {metric_name}")
        return (0.0, 1.0)
    
    # Check if target is binary
    unique_targets = clean_data[TARGET_COLUMN].unique()
    if len(unique_targets) != 2:
        logger.warning(f"Target column for {metric_name} is not binary: {unique_targets}")
        return (0.0, 1.0)
    
    # Group by target
    group_0 = clean_data[clean_data[TARGET_COLUMN] == 0][metric_name]
    group_1 = clean_data[clean_data[TARGET_COLUMN] == 1][metric_name]
    
    if len(group_0) == 0 or len(group_1) == 0:
        logger.warning(f"One of the groups is empty for {metric_name}")
        return (0.0, 1.0)
    
    # Compute Point-Biserial correlation using scipy
    try:
        corr, p_value = stats.pointbiserialr(
            group_0, 
            group_1
        )
    except Exception as e:
        logger.error(f"Error computing Point-Biserial for {metric_name}: {e}")
        return (0.0, 1.0)
    
    return (float(corr), float(p_value))

def compute_spearman(df: pd.DataFrame, metric_name: str) -> Tuple[float, float]:
    """
    Compute Spearman rank correlation between a metric and the binary target.
    
    Spearman correlation is a non-parametric measure of rank correlation.
    It assesses how well the relationship between two variables can be described
    using a monotonic function.
    
    Args:
        df: DataFrame containing the data
        metric_name: Name of the metric column to correlate with target
        
    Returns:
        Tuple of (correlation coefficient, p-value)
        
    Raises:
        ValueError: If the metric column or target column is missing or invalid
    """
    if metric_name not in df.columns:
        raise ValueError(f"Metric column '{metric_name}' not found in DataFrame")
    
    if TARGET_COLUMN not in df.columns:
        raise ValueError(f"Target column '{TARGET_COLUMN}' not found in DataFrame")
    
    # Remove rows with NaN values in the metric or target
    clean_data = df[[metric_name, TARGET_COLUMN]].dropna()
    
    if len(clean_data) < 2:
        logger.warning(f"Not enough data to compute Spearman for {metric_name}")
        return (0.0, 1.0)
    
    try:
        corr, p_value = stats.spearmanr(
            clean_data[metric_name],
            clean_data[TARGET_COLUMN]
        )
    except Exception as e:
        logger.error(f"Error computing Spearman for {metric_name}: {e}")
        return (0.0, 1.0)
    
    return (float(corr), float(p_value))

def run_correlation_analysis(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Run correlation analysis for all metrics against the target variable.
    
    Computes both Point-Biserial and Spearman correlations for each metric.
    
    Args:
        df: DataFrame containing the features and target
        
    Returns:
        Dictionary containing correlation results for each metric
    """
    results = {
        'point_biserial': {},
        'spearman': {},
        'metadata': {
            'total_samples': len(df),
            'buggy_samples': int(df[TARGET_COLUMN].sum()),
            'non_buggy_samples': int(len(df) - df[TARGET_COLUMN].sum()),
            'metrics_analyzed': METRIC_COLUMNS.copy()
        }
    }
    
    for metric in METRIC_COLUMNS:
        logger.info(f"Computing correlations for metric: {metric}")
        
        # Point-Biserial
        pb_corr, pb_pval = compute_point_biserial(df, metric)
        results['point_biserial'][metric] = {
            'correlation': pb_corr,
            'p_value': pb_pval,
            'significant': pb_pval < 0.05
        }
        
        # Spearman
        sp_corr, sp_pval = compute_spearman(df, metric)
        results['spearman'][metric] = {
            'correlation': sp_corr,
            'p_value': sp_pval,
            'significant': sp_pval < 0.05
        }
        
        logger.info(f"  Point-Biserial: r={pb_corr:.4f}, p={pb_pval:.4f}")
        logger.info(f"  Spearman: rho={sp_corr:.4f}, p={sp_pval:.4f}")
    
    return results

def save_results(results: Dict[str, Any], output_path: str) -> None:
    """
    Save correlation analysis results to a JSON file.
    
    Args:
        results: Dictionary containing correlation results
        output_path: Path to the output JSON file
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(path, 'w') as f:
        json.dump(results, f, indent=2)
    
    logger.info(f"Results saved to {output_path}")

def main():
    """
    Main entry point for correlation analysis.
    
    Loads features.csv, computes correlations, and saves results.
    """
    # Default paths
    features_path = os.environ.get(
        'FEATURES_PATH', 
        'code/data/processed/features.csv'
    )
    output_path = os.environ.get(
        'OUTPUT_PATH', 
        'code/data/results/correlation_report.json'
    )
    
    logger.info(f"Starting correlation analysis")
    logger.info(f"Features path: {features_path}")
    logger.info(f"Output path: {output_path}")
    
    try:
        # Load data
        df = load_features_csv(features_path)
        
        # Run analysis
        results = run_correlation_analysis(df)
        
        # Save results
        save_results(results, output_path)
        
        logger.info("Correlation analysis completed successfully")
        
    except FileNotFoundError as e:
        logger.error(f"Data file not found: {e}")
        raise
    except ValueError as e:
        logger.error(f"Invalid data: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error during analysis: {e}")
        raise

if __name__ == "__main__":
    main()