import pytest
import json
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock
import sys
import os

# Add code directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from code.src.detection.detect_llm_code import (
    detect_llm_generated_code,
    calculate_confidence,
    process_pr_diffs,
    LLM_SIGNATURE_PATTERNS
)
from code.src.detection.schema import LLMCodeDetectionResult, ConfidenceLevel

class TestDetectLlmCode:
    """Tests for LLM code detection functionality."""

    def test_empty_diff(self):
        """Test detection with empty diff content."""
        result = detect_llm_generated_code("", "PR-001", "test.py")
        assert result.llm_code_flag is False
        assert result.confidence == ConfidenceLevel.UNSURE
        assert result.heuristic_score == 0.0

    def test_no_llm_signatures(self):
        """Test detection with normal code that has no LLM signatures."""
        normal_code = """
        def hello_world():
            print("Hello, World!")
        
        if __name__ == "__main__":
            hello_world()
        """
        result = detect_llm_generated_code(normal_code, "PR-001", "test.py")
        assert result.llm_code_flag is False
        assert result.confidence == ConfidenceLevel.UNSURE
        assert result.heuristic_score == 0.0

    def test_strong_llm_signature(self):
        """Test detection with a strong LLM signature."""
        llm_code = """
        # Here is the fix for the bug
        def fixed_function():
            return True
        """
        result = detect_llm_generated_code(llm_code, "PR-001", "test.py")
        assert result.llm_code_flag is True
        assert result.confidence in [ConfidenceLevel.HIGH, ConfidenceLevel.MEDIUM]
        assert result.heuristic_score >= 1.0

    def test_multiple_llm_signatures(self):
        """Test detection with multiple LLM signatures."""
        llm_code = """
        # Here is the code you requested
        # Generated by AI
        def ai_function():
            pass
        """
        result = detect_llm_generated_code(llm_code, "PR-001", "test.py")
        assert result.llm_code_flag is True
        assert result.confidence == ConfidenceLevel.HIGH
        assert result.heuristic_score >= 2.0

    def test_confidence_calculation_high(self):
        """Test confidence calculation with high score."""
        confidence = calculate_confidence(10.0, 100)
        assert confidence == ConfidenceLevel.HIGH

    def test_confidence_calculation_medium(self):
        """Test confidence calculation with medium score."""
        confidence = calculate_confidence(5.0, 100)
        assert confidence == ConfidenceLevel.MEDIUM

    def test_confidence_calculation_low(self):
        """Test confidence calculation with low score."""
        confidence = calculate_confidence(2.0, 100)
        assert confidence == ConfidenceLevel.LOW

    def test_confidence_calculation_unsure(self):
        """Test confidence calculation with no score."""
        confidence = calculate_confidence(0.0, 100)
        assert confidence == ConfidenceLevel.UNSURE

    def test_detect_llm_generated_code_with_ai_comment(self):
        """Test detection of code with 'AI generated' comment."""
        code = """
        # AI generated code
        def ai_func():
            return 42
        """
        result = detect_llm_generated_code(code, "PR-002", "ai.py")
        assert result.llm_code_flag is True
        assert "ai" in result.detection_reason.lower()

    def test_detect_llm_generated_code_with_assistant(self):
        """Test detection of code with 'assistant:' marker."""
        code = """
        assistant:
        def response():
            return "Hello"
        """
        result = detect_llm_generated_code(code, "PR-003", "chat.py")
        assert result.llm_code_flag is True

class TestProcessPrDiffs:
    """Tests for the process_pr_diffs function."""

    def test_process_pr_diffs_empty_file(self):
        """Test processing an empty PR file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "input.json"
            output_file = Path(tmpdir) / "output.json"
            
            # Write empty list
            with open(input_file, 'w') as f:
                json.dump([], f)
            
            results = process_pr_diffs(input_file, output_file)
            assert len(results) == 0
            assert output_file.exists()

    def test_process_pr_diffs_with_valid_data(self):
        """Test processing PR data with valid diffs."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "input.json"
            output_file = Path(tmpdir) / "output.json"
            
            # Create test data with LLM signatures
            test_data = [{
                "pr_id": "PR-100",
                "files": [
                    {
                        "file_path": "test.py",
                        "diff": "# Here is the fix\ndef fix():\n    pass"
                    }
                ]
            }]
            
            with open(input_file, 'w') as f:
                json.dump(test_data, f)
            
            results = process_pr_diffs(input_file, output_file)
            
            assert len(results) == 1
            assert results[0]['pr_id'] == "PR-100"
            assert results[0]['file_path'] == "test.py"
            assert results[0]['llm_code_flag'] is True
            assert output_file.exists()

    def test_process_pr_diffs_no_files(self):
        """Test processing PR data without files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "input.json"
            output_file = Path(tmpdir) / "output.json"
            
            test_data = [{
                "pr_id": "PR-200"
            }]
            
            with open(input_file, 'w') as f:
                json.dump(test_data, f)
            
            results = process_pr_diffs(input_file, output_file)
            assert len(results) == 0

    def test_process_pr_diffs_file_not_found(self):
        """Test processing with non-existent input file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "nonexistent.json"
            output_file = Path(tmpdir) / "output.json"
            
            with pytest.raises(FileNotFoundError):
                process_pr_diffs(input_file, output_file)

class TestLLMCodeDetectionResult:
    """Tests for the LLMCodeDetectionResult dataclass."""

    def test_result_creation(self):
        """Test creating a detection result."""
        result = LLMCodeDetectionResult(
            pr_id="PR-001",
            file_path="test.py",
            llm_code_flag=True,
            confidence=ConfidenceLevel.HIGH,
            detection_reason="Test reason",
            heuristic_score=5.0,
            matched_patterns=["pattern1"]
        )
        
        assert result.pr_id == "PR-001"
        assert result.llm_code_flag is True
        assert result.confidence == ConfidenceLevel.HIGH

    def test_to_dict(self):
        """Test converting result to dictionary."""
        result = LLMCodeDetectionResult(
            pr_id="PR-001",
            file_path="test.py",
            llm_code_flag=True,
            confidence=ConfidenceLevel.MEDIUM,
            detection_reason="Test",
            heuristic_score=3.0,
            matched_patterns=["p1", "p2"]
        )
        
        d = result.to_dict()
        assert d['pr_id'] == "PR-001"
        assert d['llm_code_flag'] is True
        assert d['confidence'] == "medium"
        assert d['heuristic_score'] == 3.0
        assert len(d['matched_patterns']) == 2

    def test_from_dict(self):
        """Test creating result from dictionary."""
        data = {
            "pr_id": "PR-002",
            "file_path": "other.py",
            "llm_code_flag": False,
            "confidence": "low",
            "detection_reason": "No match",
            "heuristic_score": 1.0,
            "matched_patterns": []
        }
        
        result = LLMCodeDetectionResult.from_dict(data)
        assert result.pr_id == "PR-002"
        assert result.llm_code_flag is False
        assert result.confidence == ConfidenceLevel.LOW

    def test_json_roundtrip(self):
        """Test JSON serialization and deserialization."""
        result = LLMCodeDetectionResult(
            pr_id="PR-003",
            file_path="roundtrip.py",
            llm_code_flag=True,
            confidence=ConfidenceLevel.HIGH,
            detection_reason="Roundtrip test",
            heuristic_score=10.0,
            matched_patterns=["test"]
        )
        
        json_str = result.to_json()
        restored = LLMCodeDetectionResult.from_json(json_str)
        
        assert restored.pr_id == result.pr_id
        assert restored.llm_code_flag == result.llm_code_flag
        assert restored.confidence == result.confidence
        assert restored.heuristic_score == result.heuristic_score
        assert restored.matched_patterns == result.matched_patterns
