"""
T019 Implementation: Verify presence of required metrics in training logs.

This script reads the training log file generated by the SDAR training loop
and verifies the presence of the following keys:
- gate_activation_rate
- kl_divergence
- teacher_update_count

It performs a presence check only, without enforcing hard numeric thresholds.
"""
import os
import json
import sys
from pathlib import Path

# Define the expected log file path based on project structure
LOG_FILE_PATH = Path("outputs/logs/train_log.json")

REQUIRED_KEYS = [
    "gate_activation_rate",
    "kl_divergence",
    "teacher_update_count"
]

def verify_log_presence(log_path: Path) -> bool:
    """
    Reads the JSON log file and checks for the presence of required keys.
    
    Args:
        log_path: Path to the training log JSON file.
        
    Returns:
        True if all required keys are present in at least one log entry, False otherwise.
    """
    if not log_path.exists():
        print(f"ERROR: Log file not found at {log_path}")
        return False

    try:
        with open(log_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            if not content:
                print("ERROR: Log file is empty.")
                return False
            
            # Attempt to parse as JSON lines or a single JSON object
            # The logging_utils.py typically outputs JSON lines or a list of dicts
            try:
                # Try parsing as a single JSON object first (list of dicts)
                data = json.loads(content)
                if isinstance(data, list):
                    log_entries = data
                else:
                    log_entries = [data]
            except json.JSONDecodeError:
                # Fallback: try parsing as JSON Lines (one JSON object per line)
                log_entries = []
                for line in content.splitlines():
                    if line.strip():
                        try:
                            log_entries.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue
                            
            if not log_entries:
                print("ERROR: No valid JSON entries found in log file.")
                return False

            found_keys = set()
            for entry in log_entries:
                if isinstance(entry, dict):
                    for key in REQUIRED_KEYS:
                        if key in entry:
                            found_keys.add(key)
            
            missing_keys = set(REQUIRED_KEYS) - found_keys
            
            if missing_keys:
                print(f"VERIFICATION FAILED: Missing keys: {missing_keys}")
                print(f"Found keys: {found_keys}")
                return False
            else:
                print("VERIFICATION PASSED: All required keys present.")
                print(f"Verified keys: {list(found_keys)}")
                return True

    except Exception as e:
        print(f"ERROR: Failed to process log file: {e}")
        return False

def main():
    """Entry point for the verification script."""
    success = verify_log_presence(LOG_FILE_PATH)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()