"""
Task T006: Validate downloaded dataset for required behavioral fields.

Checks for the existence of 'confidence_rating' and 'source_label' columns
in the dataset downloaded by T005. Outputs a validation report to data/validation_report.json.
"""
import json
import logging
import os
import sys
import pandas as pd
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# Project root relative to this script
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DERIVED_DIR = DATA_DIR / "derived"
RESULTS_DIR = DATA_DIR / "results"
OUTPUT_FILE = DATA_DIR / "validation_report.json"

# Required columns
REQUIRED_COLUMNS = ["confidence_rating", "source_label"]

def find_input_file():
    """
    Locate the downloaded dataset file.
    Looks for common filenames generated by download.py or standard dataset names.
    """
    potential_names = [
        "behavioral_metacognition_sample.csv",
        "sample_behavioral_data.csv",
        "ds004042_behavioral.csv",
        "metacognition_data.csv",
        "trial_data_raw.csv"
    ]
    
    # Check derived directory first (sometimes preprocess puts it there)
    if DERIVED_DIR.exists():
        for name in potential_names:
            path = DERIVED_DIR / name
            if path.exists():
                return path
    
    # Check data directory
    if DATA_DIR.exists():
        for name in potential_names:
            path = DATA_DIR / name
            if path.exists():
                return path
        
        # Also check for any .csv file in data root if specific names fail
        csv_files = list(DATA_DIR.glob("*.csv"))
        if csv_files:
            # Prefer the largest file or the most recent, but for now just take the first
            return csv_files[0]

    logger.error("No valid input dataset found in known locations.")
    return None

def load_dataset(file_path: Path) -> pd.DataFrame:
    """
    Load the dataset from the given file path.
    """
    try:
        logger.info(f"Loading dataset from: {file_path}")
        df = pd.read_csv(file_path)
        logger.info(f"Dataset loaded successfully. Shape: {df.shape}")
        return df
    except Exception as e:
        logger.error(f"Failed to load dataset: {e}")
        raise

def validate_fields(df: pd.DataFrame) -> bool:
    """
    Check if required fields exist in the dataframe.
    Raises ValueError if missing.
    """
    missing = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    
    if missing:
        error_msg = f"Required fields missing: {', '.join(missing)}"
        logger.error(error_msg)
        raise ValueError(error_msg)
    
    logger.info("Validation passed: All required fields present.")
    return True

def write_report(status: str, message: str, details: dict = None):
    """
    Write the validation report to data/validation_report.json.
    """
    report = {
        "task_id": "T006",
        "status": status,
        "message": message,
        "timestamp": pd.Timestamp.now().isoformat(),
        "details": details or {}
    }
    
    # Ensure data directory exists
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    with open(OUTPUT_FILE, 'w') as f:
        json.dump(report, f, indent=2)
    
    logger.info(f"Validation report written to {OUTPUT_FILE}")

def main():
    """
    Main entry point for T006.
    """
    logger.info("Starting data validation (T006)...")
    
    try:
        # 1. Find input file
        input_file = find_input_file()
        if not input_file:
            write_report("FAIL", "No input dataset found.", {"error": "File not found"})
            sys.exit(1)
        
        logger.info(f"Found input file: {input_file}")
        
        # 2. Load dataset
        df = load_dataset(input_file)
        
        # 3. Validate fields
        try:
            validate_fields(df)
            write_report("PASS", "All required fields present.", {
                "columns_found": list(df.columns),
                "row_count": len(df),
                "input_file": str(input_file)
            })
            logger.info("Validation successful. Exiting with code 0.")
            sys.exit(0)
        except ValueError as e:
            write_report("FAIL", str(e), {
                "input_file": str(input_file),
                "available_columns": list(df.columns)
            })
            logger.error("Validation failed due to missing fields.")
            sys.exit(1)
            
    except Exception as e:
        logger.error(f"Unexpected error during validation: {e}")
        write_report("FAIL", "Unexpected error.", {"error": str(e)})
        sys.exit(1)

if __name__ == "__main__":
    main()