import os
import sys
import logging
from pathlib import Path
from typing import List, Set, Dict
import re

# Import from utils as defined in API surface
from utils import check_motion_threshold, log_qc_metrics, get_motion_file

def setup_logging(log_file: Path) -> logging.Logger:
    """Setup logging configuration for the subject filter module."""
    logger = logging.getLogger('subject_filter')
    logger.setLevel(logging.INFO)
    
    # File handler for persistent logs
    fh = logging.FileHandler(log_file, mode='w')
    fh.setLevel(logging.INFO)
    
    # Console handler for immediate feedback
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    fh.setFormatter(formatter)
    ch.setFormatter(formatter)
    
    logger.addHandler(fh)
    logger.addHandler(ch)
    
    return logger

def load_qc_log(qc_log_path: Path) -> Dict[str, float]:
    """
    Load the QC log generated by preprocess.py.
    Expects a log file with lines containing subject IDs and motion metrics.
    Returns a dictionary mapping subject_id -> max_displacement (mm).
    """
    qc_data = {}
    if not qc_log_path.exists():
        raise FileNotFoundError(f"QC log not found at {qc_log_path}. "
                                "Run preprocess.py first to generate QC data.")
    
    with open(qc_log_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            # Expected format from preprocess.py logs:
            # "Subject sub-XX: max_displacement=1.23mm (PASS)" or similar
            # We look for the pattern: sub-XX followed by max_displacement value
            match = re.search(r'(sub-\d+)\D+max_displacement[=:]\s*([\d.]+)', line)
            if match:
                subject_id = match.group(1)
                displacement = float(match.group(2))
                qc_data[subject_id] = displacement
            elif 'subject' in line.lower() and 'motion' in line.lower():
                # Fallback for generic motion log lines if format varies
                parts = line.split()
                # Try to extract subject ID and a float
                for i, part in enumerate(parts):
                    if part.startswith('sub-'):
                        # Look for a float nearby
                        for j in range(i, min(i+5, len(parts))):
                            try:
                                val = float(parts[j])
                                qc_data[part] = val
                                break
                            except ValueError:
                                continue
    
    if not qc_data:
        raise ValueError("No valid subject motion data found in QC log. "
                         "Check the log format or preprocessing output.")
    
    return qc_data

def filter_valid_subjects(qc_data: Dict[str, float], motion_threshold: float = 2.0) -> List[str]:
    """
    Filter subjects based on motion threshold.
    
    Args:
        qc_data: Dictionary of subject_id -> max_displacement
        motion_threshold: Maximum allowed displacement in mm (default 2.0)
    
    Returns:
        List of valid subject IDs that passed the motion threshold.
    """
    valid_subjects = []
    excluded_subjects = []
    
    for subject_id, displacement in sorted(qc_data.items()):
        if displacement <= motion_threshold:
            valid_subjects.append(subject_id)
        else:
            excluded_subjects.append((subject_id, displacement))
    
    return valid_subjects, excluded_subjects

def write_valid_subjects(valid_subjects: List[str], output_path: Path) -> None:
    """
    Write the list of valid subject IDs to a text file.
    One subject ID per line.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        for subject_id in valid_subjects:
            f.write(f"{subject_id}\n")

def main():
    """
    Main entry point for subject exclusion logic.
    Reads QC log, filters subjects by motion, and writes valid subjects list.
    """
    # Define paths relative to project root
    project_root = Path(__file__).resolve().parent.parent
    qc_log_path = project_root / 'data' / 'processed' / 'preprocessing_qc.log'
    output_path = project_root / 'data' / 'processed' / 'valid_subjects.txt'
    log_path = project_root / 'data' / 'processed' / 'subject_filter.log'
    
    logger = setup_logging(log_path)
    logger.info("Starting subject exclusion logic (T015)")
    
    try:
        # Load QC data
        logger.info(f"Loading QC log from {qc_log_path}")
        qc_data = load_qc_log(qc_log_path)
        logger.info(f"Loaded QC data for {len(qc_data)} subjects")
        
        # Filter subjects (default threshold 2.0mm as per spec)
        valid_subjects, excluded_subjects = filter_valid_subjects(qc_data, motion_threshold=2.0)
        
        # Log results
        logger.info(f"Valid subjects (motion <= 2.0mm): {len(valid_subjects)}")
        logger.info(f"Excluded subjects (motion > 2.0mm): {len(excluded_subjects)}")
        
        if excluded_subjects:
            logger.warning("Excluded subjects:")
            for sub_id, disp in excluded_subjects:
                logger.warning(f"  - {sub_id}: {disp:.2f}mm")
        
        # Write output file
        write_valid_subjects(valid_subjects, output_path)
        logger.info(f"Successfully wrote {len(valid_subjects)} valid subjects to {output_path}")
        
    except FileNotFoundError as e:
        logger.error(str(e))
        sys.exit(1)
    except ValueError as e:
        logger.error(str(e))
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
