import os
import sys
import logging
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.impute import IterativeImputer
from scipy.stats import zscore
from datetime import datetime

# Import shared utilities and config from the project
# We assume the project root is added to sys.path or we use relative imports via utils
try:
    from utils import (
        get_project_root_path,
        get_data_processed_path,
        get_data_qc_path,
        ensure_directory,
        setup_logger,
        get_logger
    )
except ImportError:
    # Fallback if running as a script without proper path setup
    # This block ensures the script works even if invoked directly from the root
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from code.utils import (
        get_project_root_path,
        get_data_processed_path,
        get_data_qc_path,
        ensure_directory,
        setup_logger,
        get_logger
    )

# Constants
LOG_FILE = "preprocess.log"
QC_LOG_FILE = "filtering_log.json"
COGNITIVE_RAW_FILE = "data/raw/cognitive_raw.parquet"
COGNITIVE_PROCESSED_FILE = "data/processed/cognitive_processed.parquet"

# Setup logger
logger = setup_logger(LOG_FILE)

def load_cognitive_raw_data(raw_path: str = None) -> pd.DataFrame:
    """
    Load the raw cognitive data from the parquet file generated by T012.
    """
    if raw_path is None:
        raw_path = COGNITIVE_RAW_FILE
    
    if not os.path.exists(raw_path):
        raise FileNotFoundError(f"Raw cognitive data not found at {raw_path}. "
                                "Please ensure T012 (fetch_cognitive_data) has been run.")
    
    logger.info(f"Loading raw cognitive data from {raw_path}")
    try:
        df = pd.read_parquet(raw_path)
        logger.info(f"Loaded {len(df)} rows. Columns: {list(df.columns)}")
        return df
    except Exception as e:
        logger.error(f"Failed to load raw cognitive data: {e}")
        raise

def apply_mice_imputation(df: pd.DataFrame, numeric_cols: list = None) -> pd.DataFrame:
    """
    Apply MICE (Multiple Imputation by Chained Equations) to handle missing values.
    Uses sklearn's IterativeImputer which implements a MICE-like algorithm.
    """
    if numeric_cols is None:
        # Select only numeric columns for imputation
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    
    if not numeric_cols:
        logger.warning("No numeric columns found for MICE imputation.")
        return df

    logger.info(f"Applying MICE imputation to columns: {numeric_cols}")
    
    # Extract data for imputation
    data_to_impute = df[numeric_cols].copy()
    
    # Initialize IterativeImputer
    # max_iter=10, tol=1e-3 are standard defaults
    imputer = IterativeImputer(random_state=42, max_iter=10, tol=1e-3)
    
    try:
        imputed_values = imputer.fit_transform(data_to_impute)
        df[numeric_cols] = imputed_values
        logger.info("MICE imputation completed successfully.")
    except Exception as e:
        logger.error(f"MICE imputation failed: {e}")
        # Fallback to mean imputation if MICE fails (to prevent pipeline crash)
        logger.warning("Falling back to mean imputation.")
        df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
    
    return df

def compute_z_scores(df: pd.DataFrame, target_col: str = None) -> pd.DataFrame:
    """
    Compute z-scores for the cognitive score column(s).
    If target_col is not specified, computes for all numeric columns.
    """
    if target_col:
        if target_col not in df.columns:
            raise ValueError(f"Target column '{target_col}' not found in dataframe.")
        cols_to_score = [target_col]
    else:
        cols_to_score = df.select_dtypes(include=[np.number]).columns.tolist()
    
    logger.info(f"Computing z-scores for columns: {cols_to_score}")
    
    for col in cols_to_score:
        # Check for zero variance
        if df[col].std() == 0:
            logger.warning(f"Column {col} has zero standard deviation. Skipping z-score.")
            continue
        df[col] = zscore(df[col])
    
    return df

def filter_outliers_by_zscore(df: pd.DataFrame, threshold: float = 3.0, 
                              numeric_cols: list = None) -> pd.DataFrame:
    """
    Filter out rows where any numeric column has a z-score > threshold.
    Logs the filtering details.
    """
    if numeric_cols is None:
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    
    if not numeric_cols:
        logger.warning("No numeric columns to filter outliers.")
        return df, []

    logger.info(f"Filtering outliers with z-score > {threshold} in columns: {numeric_cols}")
    
    outlier_mask = pd.Series(False, index=df.index)
    outliers_found = []

    for col in numeric_cols:
        if df[col].std() == 0:
            continue
        
        z_scores = np.abs(zscore(df[col]))
        col_outlier_mask = z_scores > threshold
        outlier_mask |= col_outlier_mask
        
        if col_outlier_mask.any():
            outliers_found.append({
                "column": col,
                "count": int(col_outlier_mask.sum()),
                "threshold": threshold
            })
    
    original_count = len(df)
    df_filtered = df[~outlier_mask].reset_index(drop=True)
    removed_count = original_count - len(df_filtered)
    
    logger.info(f"Removed {removed_count} rows ({removed_count/original_count*100:.2f}%) due to outliers.")
    
    return df_filtered, outliers_found

def save_outlier_log(outliers: list, log_path: str = None) -> None:
    """
    Save the outlier filtering log to a JSON file.
    """
    if log_path is None:
        log_path = str(get_data_qc_path() / QC_LOG_FILE)
    
    ensure_directory(log_path)
    
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "source": "02_preprocess.py",
        "outliers": outliers
    }
    
    # Append to existing log if it exists
    existing_log = []
    if os.path.exists(log_path):
        try:
            import json
            with open(log_path, 'r') as f:
                existing_log = json.load(f)
        except Exception:
            existing_log = []
    
    existing_log.append(log_entry)
    
    import json
    with open(log_path, 'w') as f:
        json.dump(existing_log, f, indent=2)
    
    logger.info(f"Outlier log saved to {log_path}")

def save_processed_data(df: pd.DataFrame, output_path: str = None) -> None:
    """
    Save the processed cognitive data to a parquet file.
    """
    if output_path is None:
        output_path = COGNITIVE_PROCESSED_FILE
    
    ensure_directory(output_path)
    
    logger.info(f"Saving processed cognitive data to {output_path}")
    df.to_parquet(output_path, index=False)
    logger.info(f"Saved {len(df)} rows to {output_path}")

def main():
    """
    Main execution flow for T013:
    1. Load raw cognitive data.
    2. Apply MICE imputation.
    3. Compute z-scores.
    4. Filter outliers.
    5. Save processed data and QC log.
    """
    try:
        # 1. Load Raw Data
        df = load_cognitive_raw_data()
        
        # 2. MICE Imputation
        df = apply_mice_imputation(df)
        
        # 3. Compute Z-scores (assuming a column named 'cognitive_score' or similar exists, 
        #    otherwise we do it for all numeric columns)
        # Check for common cognitive score column names
        score_col = None
        possible_names = ['cognitive_score', 'cognitive_score_z', 'score', 'total_score']
        for name in possible_names:
            if name in df.columns:
                score_col = name
                break
        
        # If we found a specific score column, we might want to focus z-score on it,
        # but the task says "compute z-scores" generally. We'll compute for all numeric
        # to be safe, or specifically if a score column is identified.
        # Let's compute for all numeric columns as per general preprocessing.
        df = compute_z_scores(df)
        
        # 4. Filter Outliers
        df_filtered, outliers = filter_outliers_by_zscore(df, threshold=3.0)
        
        # 5. Save Outlier Log
        save_outlier_log(outliers)
        
        # 6. Save Processed Data
        save_processed_data(df_filtered)
        
        logger.info("T013 Preprocessing completed successfully.")
        return 0
        
    except Exception as e:
        logger.error(f"T013 Preprocessing failed: {e}")
        raise

if __name__ == "__main__":
    sys.exit(main())
