"""
Integration test for scatter-plot output format validation (T039 - US3).

Validates that scatter plots generated by the visualization pipeline:
1. Exist at the correct output paths
2. Are in the correct file formats (PNG and PDF)
3. Contain valid image data with expected structure
4. Include regression lines as specified
5. Have proper axis labels and titles

This test MUST run after the full pipeline produces correlation_results.csv
and visualization.py generates the output figures.
"""
import os
import sys
import struct
import logging
from pathlib import Path
from typing import Tuple, Optional
import pytest

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "code"))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Output paths per T042 specification
FIGURES_DIR = PROJECT_ROOT / "data" / "analysis" / "figures"
EXPECTED_PNG_FORMAT = "png"
EXPECTED_PDF_FORMAT = "pdf"

# Expected plot types per visualization.py API
EXPECTED_PLOTS = [
    "clone_density_vs_perplexity",
    "clone_density_vs_accuracy",
    "sensitivity_analysis"
]

# Required threshold values per T043 (SC-005)
REQUIRED_THRESHOLDS = [0.7, 0.8, 0.9]

# File size minimum to ensure non-empty output
MIN_FILE_SIZE_BYTES = 1000

# PNG signature bytes (8 bytes)
PNG_SIGNATURE = bytes([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])

# PDF signature
PDF_SIGNATURE = b"%PDF"

def get_expected_output_paths(plot_name: str) -> Tuple[Path, Path]:
    """Get expected PNG and PDF paths for a given plot name."""
    png_path = FIGURES_DIR / f"{plot_name}.{EXPECTED_PNG_FORMAT}"
    pdf_path = FIGURES_DIR / f"{plot_name}.{EXPECTED_PDF_FORMAT}"
    return png_path, pdf_path

def validate_png_file(file_path: Path) -> Tuple[bool, Optional[str]]:
    """
    Validate that a file is a valid PNG image.
    
    Checks:
    1. File exists
    2. File size > minimum threshold
    3. PNG signature bytes match
    4. PNG chunk structure is valid (at least IHDR chunk)
    
    Returns:
        Tuple of (is_valid, error_message)
    """
    if not file_path.exists():
        return False, f"File does not exist: {file_path}"
    
    file_size = file_path.stat().st_size
    if file_size < MIN_FILE_SIZE_BYTES:
        return False, f"File too small ({file_size} bytes < {MIN_FILE_SIZE_BYTES} bytes minimum)"
    
    with open(file_path, "rb") as f:
        signature = f.read(8)
        if signature != PNG_SIGNATURE:
            return False, f"Invalid PNG signature: {signature.hex()}"
        
        # Check for IHDR chunk (must be first chunk after signature)
        chunk_type = f.read(4)
        if chunk_type != b"IHDR":
            return False, f"Missing IHDR chunk, found: {chunk_type}"
        
        # IHDR chunk length is 13 bytes
        chunk_length = struct.unpack(">I", f.read(4))[0]
        if chunk_length != 13:
            return False, f"Invalid IHDR length: {chunk_length} (expected 13)"
        
        # Read width and height (4 bytes each)
        width = struct.unpack(">I", f.read(4))[0]
        height = struct.unpack(">I", f.read(4))[0]
        
        if width == 0 or height == 0:
            return False, f"Invalid image dimensions: {width}x{height}"
        
        logger.info(f"Valid PNG: {width}x{height} pixels")
        return True, None

def validate_pdf_file(file_path: Path) -> Tuple[bool, Optional[str]]:
    """
    Validate that a file is a valid PDF document.
    
    Checks:
    1. File exists
    2. File size > minimum threshold
    3. PDF signature matches
    4. Contains basic PDF structure markers
    
    Returns:
        Tuple of (is_valid, error_message)
    """
    if not file_path.exists():
        return False, f"File does not exist: {file_path}"
    
    file_size = file_path.stat().st_size
    if file_size < MIN_FILE_SIZE_BYTES:
        return False, f"File too small ({file_size} bytes < {MIN_FILE_SIZE_BYTES} bytes minimum)"
    
    with open(file_path, "rb") as f:
        signature = f.read(4)
        if signature != PDF_SIGNATURE:
            return False, f"Invalid PDF signature: {signature}"
        
        # Read rest of file to check for PDF structure
        content = f.read()
        if b"endobj" not in content:
            return False, "Missing PDF object termination marker"
        
        if b"endstream" not in content:
            return False, "Missing PDF stream termination marker"
        
        logger.info(f"Valid PDF: {file_size} bytes")
        return True, None

def validate_regression_line_present(file_path: Path) -> Tuple[bool, Optional[str]]:
    """
    Validate that a plot file contains evidence of regression line rendering.
    
    For PNG: Check for sufficient color variation (regression line adds distinct colors)
    For PDF: Check for line drawing commands
    
    Returns:
        Tuple of (has_regression, error_message)
    """
    if not file_path.exists():
        return False, f"File does not exist: {file_path}"
    
    if file_path.suffix.lower() == ".png":
        with open(file_path, "rb") as f:
            content = f.read()
            # Check for color variation - a plot with regression line should have
            # more than just background colors
            unique_colors = set(content[200:2000])  # Sample first few KB
            if len(unique_colors) < 10:
                return False, "Insufficient color variation - regression line may be missing"
        return True, None
    
    elif file_path.suffix.lower() == ".pdf":
        with open(file_path, "rb") as f:
            content = f.read()
            # PDF line drawing commands
            if b"line" not in content.lower() and b"stroke" not in content.lower():
                # Some PDFs may use different encoding, check for path operations
                if b"m " not in content and b"l " not in content:
                    return False, "No line drawing operations found in PDF"
        return True, None
    
    return False, f"Unsupported file format: {file_path.suffix}"

def validate_axis_labels_present(file_path: Path) -> Tuple[bool, Optional[str]]:
    """
    Validate that plot contains axis label markers.
    
    This is a best-effort check since image content parsing is complex.
    For PDF: check for text objects
    For PNG: check for text-like patterns in metadata
    
    Returns:
        Tuple of (has_labels, error_message)
    """
    if not file_path.exists():
        return False, f"File does not exist: {file_path}"
    
    if file_path.suffix.lower() == ".pdf":
        with open(file_path, "rb") as f:
            content = f.read().decode("latin-1", errors="ignore")
            # Check for text objects in PDF
            if "/Tf" not in content:  # Font selection operator
                return False, "No font operations found - axis labels may be missing"
            if "Clone Density" not in content and "Perplexity" not in content:
                logger.warning("Axis label text not found in PDF content (may be embedded as paths)")
        return True, None
    
    elif file_path.suffix.lower() == ".png":
        # PNG text metadata
        with open(file_path, "rb") as f:
            content = f.read()
            # Check for tEXt or iTXt chunks (PNG text metadata)
            if b"tEXt" in content or b"iTXt" in content:
                return True, None
            # matplotlib often embeds title in the image data
        return True, None  # Assume labels present if file is valid
    
    return False, f"Unsupported file format: {file_path.suffix}"

@pytest.fixture(scope="module")
def figures_directory_exists():
    """Fixture to ensure figures directory exists."""
    if not FIGURES_DIR.exists():
        pytest.skip(f"Figures directory does not exist: {FIGURES_DIR}")

@pytest.fixture(scope="module")
def correlation_results_exists():
    """Fixture to ensure correlation results exist (prerequisite for visualization)."""
    correlation_file = PROJECT_ROOT / "data" / "analysis" / "correlation_results.csv"
    if not correlation_file.exists():
        pytest.skip(f"Correlation results not found (visualization prerequisite): {correlation_file}")
    return correlation_file

class TestVisualizationOutputFormat:
    """Integration tests for scatter-plot output format validation (T039)."""
    
    @pytest.mark.integration
    def test_figures_directory_structure(self, figures_directory_exists):
        """Test that the figures directory structure is correct."""
        assert FIGURES_DIR.exists(), f"Figures directory missing: {FIGURES_DIR}"
        assert FIGURES_DIR.is_dir(), f"Figures path is not a directory: {FIGURES_DIR}"
        logger.info(f"Figures directory exists: {FIGURES_DIR}")
    
    @pytest.mark.integration
    def test_all_expected_plots_exist(self, figures_directory_exists):
        """Test that all expected plot files exist."""
        missing_plots = []
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            if not png_path.exists():
                missing_plots.append(f"{plot_name}.png")
            if not pdf_path.exists():
                missing_plots.append(f"{plot_name}.pdf")
        
        if missing_plots:
            pytest.fail(f"Missing expected plot files: {missing_plots}")
        
        logger.info(f"All {len(EXPECTED_PLOTS)} plot types present in both PNG and PDF formats")
    
    @pytest.mark.integration
    def test_png_file_validity(self, figures_directory_exists):
        """Test that all PNG files are valid image files."""
        for plot_name in EXPECTED_PLOTS:
            png_path, _ = get_expected_output_paths(plot_name)
            if not png_path.exists():
                continue  # Skip if file doesn't exist (tested elsewhere)
            
            is_valid, error = validate_png_file(png_path)
            assert is_valid, f"Invalid PNG file {png_path}: {error}"
            logger.info(f"PNG valid: {png_path.name}")
    
    @pytest.mark.integration
    def test_pdf_file_validity(self, figures_directory_exists):
        """Test that all PDF files are valid PDF documents."""
        for plot_name in EXPECTED_PLOTS:
            _, pdf_path = get_expected_output_paths(plot_name)
            if not pdf_path.exists():
                continue  # Skip if file doesn't exist (tested elsewhere)
            
            is_valid, error = validate_pdf_file(pdf_path)
            assert is_valid, f"Invalid PDF file {pdf_path}: {error}"
            logger.info(f"PDF valid: {pdf_path.name}")
    
    @pytest.mark.integration
    def test_regression_lines_present(self, figures_directory_exists):
        """Test that regression lines are present in scatter plots."""
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            
            # Check PNG
            if png_path.exists():
                has_regression, error = validate_regression_line_present(png_path)
                assert has_regression, f"PNG {png_path} may be missing regression line: {error}"
            
            # Check PDF
            if pdf_path.exists():
                has_regression, error = validate_regression_line_present(pdf_path)
                assert has_regression, f"PDF {pdf_path} may be missing regression line: {error}"
        
        logger.info("Regression lines validated in all plot formats")
    
    @pytest.mark.integration
    def test_axis_labels_present(self, figures_directory_exists):
        """Test that axis labels are present in plots."""
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            
            # Check PNG
            if png_path.exists():
                has_labels, error = validate_axis_labels_present(png_path)
                # Log warning but don't fail - some formats may not expose labels
                if not has_labels:
                    logger.warning(f"PNG {png_path} may be missing axis labels: {error}")
            
            # Check PDF
            if pdf_path.exists():
                has_labels, error = validate_axis_labels_present(pdf_path)
                assert has_labels, f"PDF {pdf_path} missing axis labels: {error}"
        
        logger.info("Axis labels validated in all plot formats")
    
    @pytest.mark.integration
    def test_file_sizes_above_minimum(self, figures_directory_exists):
        """Test that all output files meet minimum size requirements."""
        all_files = []
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            if png_path.exists():
                all_files.append(png_path)
            if pdf_path.exists():
                all_files.append(pdf_path)
        
        for file_path in all_files:
            file_size = file_path.stat().st_size
            assert file_size >= MIN_FILE_SIZE_BYTES, (
                f"File {file_path.name} too small: {file_size} bytes "
                f"(minimum: {MIN_FILE_SIZE_BYTES} bytes)"
            )
        
        logger.info(f"All {len(all_files)} files meet minimum size requirements")
    
    @pytest.mark.integration
    def test_output_formats_match_specification(self, figures_directory_exists):
        """Test that output formats match T042 specification (PNG & PDF)."""
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            
            if png_path.exists():
                assert png_path.suffix.lower() == f".{EXPECTED_PNG_FORMAT}", (
                    f"PNG format mismatch for {plot_name}: got {png_path.suffix}"
                )
            
            if pdf_path.exists():
                assert pdf_path.suffix.lower() == f".{EXPECTED_PDF_FORMAT}", (
                    f"PDF format mismatch for {plot_name}: got {pdf_path.suffix}"
                )
        
        logger.info(f"All output formats match specification: {EXPECTED_PNG_FORMAT}, {EXPECTED_PDF_FORMAT}")
    
    @pytest.mark.integration
    def test_sensitivity_analysis_thresholds_documented(self, correlation_results_exists):
        """Test that sensitivity analysis includes all required thresholds (T043, SC-005)."""
        # This test validates that the correlation_results.csv contains
        # data for all required thresholds: 0.7, 0.8, 0.9
        import csv
        
        with open(correlation_results_exists, 'r') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        
        if not rows:
            pytest.fail("Correlation results file is empty")
        
        # Check for threshold column or separate rows per threshold
        has_threshold_info = False
        for row in rows:
            if 'threshold' in row or 'threshold_value' in row:
                has_threshold_info = True
                break
        
        # Alternative: check if multiple correlation values exist
        correlation_columns = [k for k in rows[0].keys() if 'correlation' in k.lower() or 'rho' in k.lower()]
        
        if not has_threshold_info and len(correlation_columns) < len(REQUIRED_THRESHOLDS):
            logger.warning(
                f"Sensitivity analysis may not include all thresholds. "
                f"Required: {REQUIRED_THRESHOLDS}, Found {len(correlation_columns)} correlation columns"
            )
        
        logger.info(f"Correlation results validated with {len(rows)} rows")
    
    @pytest.mark.integration
    def test_visualization_metadata_integrity(self, figures_directory_exists):
        """Test that visualization outputs have proper metadata."""
        # Check that files have reasonable modification times (recent)
        import time
        current_time = time.time()
        
        for plot_name in EXPECTED_PLOTS:
            png_path, pdf_path = get_expected_output_paths(plot_name)
            
            if png_path.exists():
                mtime = png_path.stat().st_mtime
                age_hours = (current_time - mtime) / 3600
                assert age_hours < 720, (  # 30 days max age
                    f"PNG file {png_path.name} is too old ({age_hours:.1f} hours)"
                )
            
            if pdf_path.exists():
                mtime = pdf_path.stat().st_mtime
                age_hours = (current_time - mtime) / 3600
                assert age_hours < 720, (
                    f"PDF file {pdf_path.name} is too old ({age_hours:.1f} hours)"
                )
        
        logger.info("Visualization metadata integrity validated")

class TestVisualizationOutputContent:
    """Additional content validation tests for visualization outputs."""
    
    @pytest.mark.integration
    def test_scatter_plot_data_points_present(self, figures_directory_exists):
        """Test that scatter plots contain data point markers."""
        for plot_name in EXPECTED_PLOTS:
            if "scatter" in plot_name.lower() or "density" in plot_name.lower():
                png_path, pdf_path = get_expected_output_paths(plot_name)
                
                if png_path.exists():
                    # Check for point markers in PNG (simplified check)
                    with open(png_path, "rb") as f:
                        content = f.read()
                        # Scatter plots should have multiple distinct regions
                        if content.count(b'\x00') > len(content) * 0.95:
                            logger.warning(f"{png_path.name} may have uniform data (check scatter plot)")
                
                if pdf_path.exists():
                    # PDF scatter plots should have point drawing operations
                    with open(pdf_path, "rb") as f:
                        content = f.read()
                        if b"point" not in content and b"circle" not in content and b"rect" not in content:
                            logger.warning(f"{pdf_path.name} may not contain point markers")
        
        logger.info("Scatter plot data point validation complete")
    
    @pytest.mark.integration
    def test_regression_line_color_contrast(self, figures_directory_exists):
        """Test that regression lines have sufficient color contrast with data points."""
        # This is a best-effort check for color diversity in PNG files
        for plot_name in EXPECTED_PLOTS:
            png_path, _ = get_expected_output_paths(plot_name)
            
            if png_path.exists():
                with open(png_path, "rb") as f:
                    content = f.read()
                    # Count distinct byte values (proxy for color diversity)
                    unique_bytes = len(set(content))
                    if unique_bytes < 50:
                        logger.warning(
                            f"{png_path.name} has low color diversity "
                            f"({unique_bytes} unique values) - regression line may not be visible"
                        )
        
        logger.info("Regression line color contrast validation complete")

def run_all_tests():
    """Convenience function to run all tests."""
    pytest.main([__file__, "-v", "--tb=short"])

if __name__ == "__main__":
    run_all_tests()
