"""
T017 Implementation: Generate batch-corrected matrix and labels.

This script orchestrates the final steps of the data pipeline:
1. Loads preprocessed metabolite data from data/raw (intermediate outputs from T015).
2. Loads harmonized labels.
3. Performs the final ComBat batch correction if multiple studies exist.
4. Saves `data/processed/batch_corrected_matrix.csv` and `data/processed/labels.csv`.

Dependencies:
- code/data/preprocess.py (for loading intermediate data)
- code/data/harmonize_labels.py (for loading labels)
- code/utils/io.py (for logging and hashing)
- code/utils/constants.py (for paths)

Real Data Requirement:
This script expects real data files to exist in data/raw/ generated by T012-T016.
If data is missing, it will raise an error (fail loudly).
"""
import os
import sys
import glob
import pandas as pd
import numpy as np
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add project root to path to ensure imports work regardless of cwd
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from code.utils.constants import DATA_RAW_DIR, DATA_PROCESSED_DIR, RANDOM_SEED
from code.utils.io import compute_file_hash, log_preprocessing_step, log_artifact
from code.data.preprocess import preprocess_metabolomics
from code.data.harmonize_labels import harmonize_labels

# Attempt to import pycombat if available, otherwise fallback to manual implementation logic
# Note: T015 description mentions ComBat. We assume the environment has pycombat or similar.
# If not installed, we attempt to import it. If missing, we raise a clear error.
try:
    from pycombat import PyCombat
    HAS_PYCOMBAT = True
except ImportError:
    HAS_PYCOMBAT = False
    # Fallback: Check if scanpy or sva is available (less likely in standard env, but possible)
    try:
        from scanpy.external.pp import combat
        HAS_SCANPY = True
    except ImportError:
        HAS_SCANPY = False

def load_preprocessed_data() -> Optional[pd.DataFrame]:
    """
    Loads the intermediate preprocessed matrix from data/raw.
    T015 is supposed to produce an intermediate file. We look for it.
    """
    # Look for the output of T015 (preprocess.py). 
    # Based on T015 description, it produces an aligned and residualized matrix.
    # We assume the filename convention from the pipeline flow.
    # If T015 produces 'aligned_matrix.csv' or similar, we find it.
    
    raw_dir = Path(DATA_RAW_DIR)
    if not raw_dir.exists():
        raise FileNotFoundError(f"Directory {DATA_RAW_DIR} does not exist. Run T012 first.")
    
    # Search for the preprocessed matrix file. 
    # T015 likely outputs a file like 'preprocessed_matrix.csv' or similar.
    # Let's look for any CSV that isn't raw phenotype data.
    candidates = list(raw_dir.glob("*.csv"))
    
    # Filter for likely matrix files (large, many columns)
    matrix_file = None
    for f in candidates:
        if "phenotype" in f.name.lower() or "labels" in f.name.lower():
            continue
        try:
            df = pd.read_csv(f)
            # Heuristic: Matrix should have many columns (metabolites) and rows (samples)
            if df.shape[1] > 10 and df.shape[0] > 10:
                matrix_file = f
                break
        except Exception:
            continue
    
    if matrix_file is None:
        # Fallback: Try to run the preprocessing step again to generate the file
        # This ensures we don't fail if T015 ran but didn't save, or if we need to regenerate.
        # However, T015 is marked done. We assume it saved 'intermediate_matrix.csv' or similar.
        # Let's try a specific expected name based on typical pipeline logic.
        expected_name = raw_dir / "intermediate_matrix.csv"
        if expected_name.exists():
            matrix_file = expected_name
        else:
            # Last resort: try to find ANY CSV that looks like a matrix
            # If still nothing, we raise.
            raise FileNotFoundError(
                f"Could not find preprocessed matrix in {DATA_RAW_DIR}. "
                "Ensure T015 (preprocess.py) has been executed successfully and saved its output."
            )
    
    log_preprocessing_step(f"Loaded intermediate matrix from {matrix_file}")
    return pd.read_csv(matrix_file, index_col=0)

def load_labels() -> pd.DataFrame:
    """
    Loads the harmonized labels.
    """
    # T014 produces harmonized labels.
    raw_dir = Path(DATA_RAW_DIR)
    label_file = raw_dir / "harmonized_labels.csv"
    
    if not label_file.exists():
        # Try to run harmonization if not present
        # But T014 is marked done. We expect the file to exist.
        raise FileNotFoundError(
            f"Label file {label_file} not found. Ensure T014 (harmonize_labels.py) has been executed."
        )
    
    df = pd.read_csv(label_file, index_col=0)
    log_preprocessing_step(f"Loaded labels from {label_file}")
    return df

def apply_batch_correction(df: pd.DataFrame, batch_col: str) -> pd.DataFrame:
    """
    Applies ComBat batch correction.
    """
    if HAS_PYCOMBAT:
        # PyCombat expects a DataFrame with samples as rows, features as columns (or vice versa depending on version)
        # PyCombat typically: data (features x samples), batch, mod
        # Let's assume standard: rows=samples, cols=features
        # We need to transpose for PyCombat if it expects features x samples
        data_matrix = df.values.T  # Features x Samples
        batches = df[batch_col].values
        
        combat = PyCombat()
        corrected_matrix = combat.fit_transform(data_matrix, batches)
        
        # Transpose back to samples x features
        corrected_df = pd.DataFrame(corrected_matrix.T, index=df.index, columns=df.columns)
        return corrected_df
    
    elif HAS_SCANPY:
        # Scanpy combat: expects AnnData or DataFrame with samples x features
        # But scanpy combat is usually for single cell, might not work directly on this matrix shape without conversion
        # For robustness, if PyCombat is missing, we might need to implement a simple version or raise.
        # Given the constraint "Real data only", we must use a real method.
        # If neither is available, we raise an error.
        raise ImportError(
            "Batch correction failed: Neither 'pycombat' nor 'scanpy' is installed. "
            "Install 'pycombat' to proceed with ComBat correction as required by T015/T017."
        )
    else:
        raise ImportError(
            "Batch correction failed: No ComBat implementation found. "
            "Install 'pycombat' (pip install pycombat) to proceed."
        )

def main():
    print("Starting T017: Generating processed outputs...")
    
    # Ensure output directory exists
    processed_dir = Path(DATA_PROCESSED_DIR)
    processed_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Load Data
    try:
        matrix_df = load_preprocessed_data()
        labels_df = load_labels()
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
    
    # 2. Merge Matrix and Labels to ensure alignment
    # The matrix index should match the labels index
    common_idx = matrix_df.index.intersection(labels_df.index)
    if len(common_idx) == 0:
        raise ValueError("No common samples found between matrix and labels. Check indices.")
    
    matrix_df = matrix_df.loc[common_idx]
    labels_df = labels_df.loc[common_idx]
    
    # 3. Identify Batch Column
    # We expect a 'batch' or 'study_id' column in the labels or matrix metadata
    batch_col = None
    possible_batch_cols = ['batch', 'study_id', 'study', 'source']
    for col in possible_batch_cols:
        if col in labels_df.columns:
            batch_col = col
            break
    
    if batch_col is None:
        # If no batch column, we assume no correction needed, or we fail?
        # T015 says "Apply ComBat ... when >=2 studies". If we have 1 study, we skip.
        # Check unique values in any potential study column
        study_cols = [c for c in labels_df.columns if 'study' in c.lower()]
        if study_cols:
            batch_col = study_cols[0]
        else:
            print("WARNING: No batch column found. Skipping ComBat correction. Assuming single batch.")
            batch_corrected_matrix = matrix_df
        # If we found a batch col later, we correct
    
    if batch_col:
        print(f"Applying ComBat correction using batch column: {batch_col}")
        if len(labels_df[batch_col].unique()) < 2:
            print("Only 1 batch found. Skipping ComBat correction.")
            batch_corrected_matrix = matrix_df
        else:
            batch_corrected_matrix = apply_batch_correction(matrix_df, batch_col)
    else:
        batch_corrected_matrix = matrix_df
    
    # 4. Save Outputs
    matrix_path = processed_dir / "batch_corrected_matrix.csv"
    labels_path = processed_dir / "labels.csv"
    
    batch_corrected_matrix.to_csv(matrix_path)
    labels_df.to_csv(labels_path)
    
    # 5. Log Artifacts
    log_artifact(matrix_path, "batch_corrected_matrix")
    log_artifact(labels_path, "labels")
    
    print(f"Successfully generated {matrix_path} and {labels_path}")
    print(f"Matrix shape: {batch_corrected_matrix.shape}")
    print(f"Labels shape: {labels_df.shape}")

if __name__ == "__main__":
    main()
