"""
Naive Mean Baseline Predictor Implementation.

This module implements a simple baseline predictor that always predicts
the mean yield strength value observed in the training set. This serves
as a lower-bound performance metric (FR-004).

The predictor does not learn from input images; it simply outputs the
global mean value for every sample in the test set.
"""

import os
import csv
import logging
import json
import argparse
from pathlib import Path
from typing import List, Dict, Optional, Tuple

# Import config utilities from the project's utils module
from utils.config import get_data_dir, get_processed_dir, get_results_dir, get_seed, set_seed

# Import loader to access dataset manifests if needed
# Note: We rely on the manifest generated by T013 (split.py)
# which contains image_id and yield_strength for each split.

def setup_logging() -> logging.Logger:
    """Initialize logging for the baseline predictor."""
    logger = logging.getLogger("baseline")
    logger.setLevel(logging.INFO)
    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter(
            "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    return logger

def load_training_manifest(manifest_path: Path) -> List[Dict[str, any]]:
    """
    Load the training split manifest to calculate the mean yield strength.

    Args:
        manifest_path: Path to the train manifest CSV/JSON.

    Returns:
        List of dictionaries containing image metadata and labels.
    """
    logger = logging.getLogger("baseline")
    if not manifest_path.exists():
        raise FileNotFoundError(f"Training manifest not found: {manifest_path}")

    data = []
    with open(manifest_path, "r", encoding="utf-8") as f:
        # Assume CSV format based on split.py implementation patterns
        reader = csv.DictReader(f)
        for row in row in reader:
            # Convert yield_strength to float
            if "yield_strength" in row:
                row["yield_strength"] = float(row["yield_strength"])
            elif "label" in row:
                row["yield_strength"] = float(row["label"])
            data.append(row)

    if not data:
        raise ValueError("Training manifest is empty.")

    return data

def calculate_mean_label(training_data: List[Dict[str, any]]) -> float:
    """
    Calculate the mean yield strength from the training data.

    Args:
        training_data: List of training samples with 'yield_strength' keys.

    Returns:
        The mean yield strength value.
    """
    strengths = [sample["yield_strength"] for sample in training_data]
    return sum(strengths) / len(strengths)

def generate_baseline_predictions(
    test_manifest_path: Path, mean_value: float, output_path: Path
) -> List[Dict[str, float]]:
    """
    Generate predictions for the test set using the mean baseline.

    Args:
        test_manifest_path: Path to the test split manifest.
        mean_value: The mean yield strength from the training set.
        output_path: Path to save the predictions CSV.

    Returns:
        List of prediction dictionaries.
    """
    logger = logging.getLogger("baseline")
    logger.info(f"Loading test manifest from {test_manifest_path}")

    if not test_manifest_path.exists():
        raise FileNotFoundError(f"Test manifest not found: {test_manifest_path}")

    predictions = []
    with open(test_manifest_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            image_id = row.get("image_id") or row.get("filename")
            if not image_id:
                raise ValueError("Test manifest missing 'image_id' or 'filename' column.")

            # The baseline predicts the same mean value for every sample
            pred = {
                "image_id": image_id,
                "true_yield_strength": float(row.get("yield_strength") or row.get("label")),
                "predicted_yield_strength": mean_value,
            }
            predictions.append(pred)

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info(f"Saving {len(predictions)} predictions to {output_path}")
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=predictions[0].keys())
        writer.writeheader()
        writer.writerows(predictions)

    return predictions

def save_baseline_stats(mean_value: float, output_dir: Path) -> Path:
    """
    Save the baseline configuration statistics to a JSON file.

    Args:
        mean_value: The calculated mean yield strength.
        output_dir: Directory to save the stats file.

    Returns:
        Path to the saved stats file.
    """
    stats = {
        "model_type": "naive_mean_baseline",
        "mean_yield_strength": mean_value,
        "description": "Predicts the training set mean for all inputs."
    }
    stats_path = output_dir / "baseline_stats.json"
    with open(stats_path, "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)
    return stats_path

def main():
    """Main entry point for running the naive mean baseline."""
    parser = argparse.ArgumentParser(description="Run Naive Mean Baseline Predictor")
    parser.add_argument(
        "--train-manifest",
        type=str,
        default=None,
        help="Path to training manifest. Defaults to auto-discovery."
    )
    parser.add_argument(
        "--test-manifest",
        type=str,
        default=None,
        help="Path to test manifest. Defaults to auto-discovery."
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Directory to save predictions. Defaults to results/"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (though baseline is deterministic)."
    )

    args = parser.parse_args()
    set_seed(args.seed)
    logger = setup_logging()

    # Resolve paths
    data_dir = Path(get_data_dir())
    processed_dir = Path(get_processed_dir())
    results_dir = Path(get_results_dir()) if not args.output_dir else Path(args.output_dir)
    results_dir.mkdir(parents=True, exist_ok=True)

    # Auto-discover manifests if not provided
    # Assuming standard naming from split.py: train_manifest.csv, test_manifest.csv
    if not args.train_manifest:
        args.train_manifest = processed_dir / "train_manifest.csv"
    if not args.test_manifest:
        args.test_manifest = processed_dir / "test_manifest.csv"

    train_path = Path(args.train_manifest)
    test_path = Path(args.test_manifest)

    try:
        # 1. Load training data to calculate mean
        logger.info(f"Loading training data from {train_path}")
        training_data = load_training_manifest(train_path)
        mean_strength = calculate_mean_label(training_data)
        logger.info(f"Calculated training mean yield strength: {mean_strength:.4f} MPa")

        # 2. Generate predictions on test set
        predictions_path = results_dir / "baseline_predictions.csv"
        predictions = generate_baseline_predictions(test_path, mean_strength, predictions_path)

        # 3. Save stats
        stats_path = save_baseline_stats(mean_strength, results_dir)
        logger.info(f"Baseline statistics saved to {stats_path}")
        logger.info(f"Predictions saved to {predictions_path}")

        print(f"Baseline run complete. Mean value: {mean_strength:.4f}")

    except FileNotFoundError as e:
        logger.error(str(e))
        print(f"Error: {e}")
        print("Ensure data processing (T015) has been run to generate manifests.")
        raise SystemExit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        raise

if __name__ == "__main__":
    main()