"""
Integration test for end-to-end evaluation pipeline (US3).

This test verifies the complete flow:
1. Loading extracted features (from T013/T016)
2. Loading and filtering labels (from T024/T025)
3. Training a lightweight classifier (T031)
4. Evaluating metrics against a random baseline (T032)
5. Verifying output artifacts exist and meet schema requirements.

Prerequisites:
- T013/T016: data/processed/features.npy must exist
- T025: data/processed/labels.csv must exist
- T024: data/processed/excluded_samples.log must exist (even if empty)
"""

import os
import json
import tempfile
import shutil
import numpy as np
import pandas as pd
import pytest
from pathlib import Path

# Import pipeline components
# Note: Using relative imports based on project structure assumptions
# In a real run, these would be installed or PYTHONPATH set
try:
    from code.classification.filter_data import filter_null_labels
    from code.classification.train_classifier import train_classifier
    from code.classification.evaluate_metrics import evaluate_metrics
except ImportError:
    # Fallback for direct execution if package structure isn't installed
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from classification.filter_data import filter_null_labels
    from classification.train_classifier import train_classifier
    from classification.evaluate_metrics import evaluate_metrics


class TestPipelineIntegration:
    """Integration tests for the full evaluation pipeline."""

    @pytest.fixture(autouse=True)
    def setup_and_teardown(self, tmp_path):
        """
        Setup: Ensure required input artifacts exist (or are mocked for this test context).
        Since we cannot guarantee T013/T025 have run in this isolated test environment,
        we create minimal valid dummy artifacts to allow the pipeline logic to run.
        
        In a real CI/CD or manual run, these would be replaced by the actual artifacts
        generated by previous tasks.
        """
        self.tmp_dir = tmp_path
        self.data_dir = self.tmp_dir / "data" / "processed"
        self.data_dir.mkdir(parents=True)
        
        # Create dummy features.npy (small mock data for testing logic)
        # Shape: (N_samples, N_features)
        n_samples = 100
        n_features = 512
        mock_features = np.random.randn(n_samples, n_features).astype(np.float32)
        features_path = self.data_dir / "features.npy"
        np.save(features_path, mock_features)
        
        # Create dummy labels.csv
        # Schema: clip_id, label, reason, confidence_score, perturbation_type
        clip_ids = [f"clip_{i:04d}" for i in range(n_samples)]
        labels = ["valid"] * 60 + ["invalid"] * 30 + ["null"] * 10
        reasons = ["simulation_ok"] * 90 + ["low_confidence"] * 10
        conf_scores = [0.95] * 90 + [0.5] * 10
        pert_types = [0] * 90 + [1] * 10 # 0 for natural, 1 for synthetic/perturbed (simplified)
        
        labels_df = pd.DataFrame({
            "clip_id": clip_ids,
            "label": labels,
            "reason": reasons,
            "confidence_score": conf_scores,
            "perturbation_type": pert_types
        })
        labels_path = self.data_dir / "labels.csv"
        labels_df.to_csv(labels_path, index=False)
        
        # Create empty excluded_samples.log (required by T024)
        excluded_path = self.data_dir / "excluded_samples.log"
        excluded_path.touch()
        
        self.output_dir = self.tmp_dir / "output"
        self.output_dir.mkdir()
        
        yield
        
        # Teardown: temp dir auto-cleaned by pytest
        pass

    def test_full_pipeline_execution(self):
        """
        Run the full pipeline: Filter -> Train -> Evaluate.
        Verifies that:
        1. Null labels are correctly filtered.
        2. A classifier is trained and saved.
        3. Metrics are calculated and include a random baseline.
        4. Output artifacts are created.
        """
        features_path = self.data_dir / "features.npy"
        labels_path = self.data_dir / "labels.csv"
        
        # Step 1: Filter Data
        # Expected: 90 samples (60 valid + 30 invalid)
        filtered_train_path = self.output_dir / "filtered_train.csv"
        filtered_test_path = self.output_dir / "filtered_test.csv"
        
        # Split 80/20 for this test
        filter_null_labels(
            labels_path=str(labels_path),
            train_output=str(filtered_train_path),
            test_output=str(filtered_test_path),
            train_ratio=0.8
        )
        
        assert filtered_train_path.exists(), "Filtered train set not created"
        assert filtered_test_path.exists(), "Filtered test set not created"
        
        train_df = pd.read_csv(filtered_train_path)
        test_df = pd.read_csv(filtered_test_path)
        
        assert "null" not in train_df["label"].values, "Null labels found in training set"
        assert "null" not in test_df["label"].values, "Null labels found in test set"
        
        # Step 2: Train Classifier
        model_path = self.output_dir / "classifier.pkl"
        train_classifier(
            train_features=str(features_path),
            train_labels=str(filtered_train_path),
            model_output=str(model_path),
            test_labels=str(filtered_test_path) # Pass test labels for internal validation if needed
        )
        
        assert model_path.exists(), "Trained model not saved"
        
        # Step 3: Evaluate Metrics
        metrics_path = self.output_dir / "metrics.json"
        evaluate_metrics(
            model_path=str(model_path),
            test_features=str(features_path), # In real code, this might be split differently
            test_labels=str(filtered_test_path),
            metrics_output=str(metrics_path)
        )
        
        assert metrics_path.exists(), "Metrics file not created"
        
        with open(metrics_path, "r") as f:
            metrics = json.load(f)
        
        # Verify schema and content
        required_keys = ["accuracy", "precision", "recall", "f1_score", "random_baseline_f1"]
        for key in required_keys:
            assert key in metrics, f"Missing metric key: {key}"
        
        # Verify random baseline logic (should be < model performance usually, or at least present)
        assert isinstance(metrics["random_baseline_f1"], (int, float)), "Random baseline must be numeric"
        
        # Verify model performance is reasonable (not NaN)
        assert not np.isnan(metrics["f1_score"]), "Model F1 score is NaN"
        assert metrics["accuracy"] > 0.0, "Accuracy must be positive"

    def test_pipeline_handles_imbalanced_data(self):
        """
        Test pipeline behavior with imbalanced labels.
        Creates a scenario with very few 'invalid' samples.
        """
        # Overwrite labels with extreme imbalance
        n_samples = 100
        clip_ids = [f"clip_{i:04d}" for i in range(n_samples)]
        # 95 valid, 5 invalid, 0 null
        labels = ["valid"] * 95 + ["invalid"] * 5
        reasons = ["simulation_ok"] * 100
        conf_scores = [0.95] * 100
        pert_types = [0] * 100
        
        labels_df = pd.DataFrame({
            "clip_id": clip_ids,
            "label": labels,
            "reason": reasons,
            "confidence_score": conf_scores,
            "perturbation_type": pert_types
        })
        labels_path = self.data_dir / "labels_imbalanced.csv"
        labels_df.to_csv(labels_path, index=False)
        
        filtered_path = self.output_dir / "filtered_imbalanced.csv"
        
        filter_null_labels(
            labels_path=str(labels_path),
            train_output=str(filtered_path),
            test_output=str(filtered_path), # Just testing the filter logic here
            train_ratio=1.0 # Use all for simplicity
        )
        
        df = pd.read_csv(filtered_path)
        assert len(df) == 100, "Sample count mismatch after filter"
        assert df["label"].value_counts()["invalid"] == 5, "Imbalance not preserved correctly"

    def test_null_label_filtering_logic(self):
        """
        Specific test for T024/T030.1 requirement:
        Ensure 'null' labels are strictly excluded from training data.
        """
        # Create a labels file with explicit nulls
        data = {
            "clip_id": ["c1", "c2", "c3", "c4", "c5"],
            "label": ["valid", "null", "invalid", "null", "valid"],
            "reason": ["ok", "low_conf", "ok", "sim_fail", "ok"],
            "confidence_score": [0.9, 0.4, 0.9, 0.3, 0.95],
            "perturbation_type": [0, 1, 0, 1, 0]
        }
        df = pd.DataFrame(data)
        test_labels_path = self.data_dir / "test_nulls.csv"
        df.to_csv(test_labels_path, index=False)
        
        filtered_path = self.output_dir / "filtered_nulls.csv"
        
        filter_null_labels(
            labels_path=str(test_labels_path),
            train_output=str(filtered_path),
            test_output=str(filtered_path),
            train_ratio=1.0
        )
        
        result = pd.read_csv(filtered_path)
        assert len(result) == 3, f"Expected 3 rows (non-null), got {len(result)}"
        assert "null" not in result["label"].values, "Null labels were not filtered out"
        assert set(result["clip_id"]) == {"c1", "c3", "c5"}, "Incorrect rows retained"

    def test_artifact_integrity(self):
        """
        Verify that the generated artifacts match the expected schema from T036.
        """
        # Run a minimal pipeline to generate artifacts
        features_path = self.data_dir / "features.npy"
        labels_path = self.data_dir / "labels.csv"
        
        filtered_train = self.output_dir / "filtered_train.csv"
        filtered_test = self.output_dir / "filtered_test.csv"
        model_path = self.output_dir / "classifier.pkl"
        metrics_path = self.output_dir / "metrics.json"
        
        filter_null_labels(
            labels_path=str(labels_path),
            train_output=str(filtered_train),
            test_output=str(filtered_test),
            train_ratio=0.8
        )
        
        train_classifier(
            train_features=str(features_path),
            train_labels=str(filtered_train),
            model_output=str(model_path),
            test_labels=str(filtered_test)
        )
        
        evaluate_metrics(
            model_path=str(model_path),
            test_features=str(features_path),
            test_labels=str(filtered_test),
            metrics_output=str(metrics_path)
        )
        
        # Verify schema of metrics.json
        with open(metrics_path, "r") as f:
            metrics = json.load(f)
        
        assert "f1_score" in metrics
        assert "random_baseline_f1" in metrics
        assert "precision" in metrics
        assert "recall" in metrics
        
        # Verify schema of filtered CSVs
        train_df = pd.read_csv(filtered_train)
        assert "clip_id" in train_df.columns
        assert "label" in train_df.columns
        assert "reason" in train_df.columns
        assert "confidence_score" in train_df.columns
        assert "perturbation_type" in train_df.columns
