"""
Statistical Summary Generator (T040)

Generates `results/statistical_summary.json` containing:
- Mean change scores
- 95% Bootstrap Confidence Intervals
- Holm-Bonferroni corrected p-values
- Effect sizes (Cohen's d) with CIs
- Significance flags based on Success Criteria (SC-001 to SC-005)
"""
import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

from config.env_config import get_path
from analysis.change_scores import load_merged_data
from analysis.bootstrap_ci import calculate_bootstrap_ci
from analysis.effect_sizes import calculate_cohens_d
from analysis.holm_bonferroni import calculate_holm_bonferroni

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_p_values_from_json(filepath: Path) -> List[Dict[str, Any]]:
    """Load p-values from a JSON file generated by previous analysis steps."""
    if not filepath.exists():
        logger.error(f"P-values file not found: {filepath}")
        raise FileNotFoundError(f"P-values file not found: {filepath}")
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    # Expecting a list of dicts or a dict with a 'results' key
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and 'results' in data:
        return data['results']
    else:
        logger.warning(f"Unexpected format in {filepath}, treating as raw list")
        return [data] if isinstance(data, dict) else []

def aggregate_results(
    change_scores: Dict[str, Dict[str, List[float]]],
    bootstrap_results: Dict[str, Dict[str, Any]],
    effect_sizes: Dict[str, Dict[str, Any]],
    holm_results: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Aggregate all analysis results into a single summary structure.
    
    Args:
        change_scores: Dict mapping metric -> { 'baseline': [], 'post': [] }
        bootstrap_results: Dict mapping metric -> { 'mean': float, 'ci_low': float, 'ci_high': float }
        effect_sizes: Dict mapping metric -> { 'd': float, 'd_ci_low': float, 'd_ci_high': float }
        holm_results: List of dicts with metric, p_raw, p_corrected, significant
      
    Returns:
        Aggregated summary dictionary
    """
    summary_metrics = []
    
    for metric in change_scores.keys():
        # Get change score stats
        baseline_vals = change_scores[metric]['baseline']
        post_vals = change_scores[metric]['post']
        mean_change = sum(post_vals) - sum(baseline_vals) / len(baseline_vals) if baseline_vals else 0
        # Recalculate mean change properly from the lists
        mean_baseline = sum(baseline_vals) / len(baseline_vals) if baseline_vals else 0
        mean_post = sum(post_vals) / len(post_vals) if post_vals else 0
        mean_diff = mean_post - mean_baseline
        
        # Get bootstrap CI
        boot = bootstrap_results.get(metric, {})
        ci_low = boot.get('ci_low', 0.0)
        ci_high = boot.get('ci_high', 0.0)
        
        # Get effect size
        eff = effect_sizes.get(metric, {})
        cohens_d = eff.get('d', 0.0)
        d_ci_low = eff.get('d_ci_low', 0.0)
        d_ci_high = eff.get('d_ci_high', 0.0)
        
        # Find Holm-Bonferroni result for this metric
        holm_entry = next((h for h in holm_results if h.get('metric') == metric), None)
        p_raw = holm_entry.get('p_raw', 0.0) if holm_entry else 0.0
        p_corrected = holm_entry.get('p_corrected', 0.0) if holm_entry else 0.0
        significant = holm_entry.get('significant', False) if holm_entry else False
        
        # Determine direction based on metric type (Hypothesis: Decluttering improves performance)
        # SART: Lower errors is better (Negative change = improvement)
        # Ospan: Higher span is better (Positive change = improvement)
        # PSS-10: Lower stress is better (Negative change = improvement)
        # PANAS: (Assuming PA higher, NA lower - simplified here to generic)
        
        direction = "mixed"
        if "sart" in metric.lower():
            direction = "negative" # Improvement is decrease
        elif "ospan" in metric.lower():
            direction = "positive" # Improvement is increase
        elif "pss" in metric.lower():
            direction = "negative" # Improvement is decrease
        elif "panas" in metric.lower():
            direction = "positive" # Assuming Positive Affect is the target
        
        metric_summary = {
            "metric": metric,
            "n_baseline": len(baseline_vals),
            "n_post": len(post_vals),
            "mean_baseline": round(mean_baseline, 4),
            "mean_post": round(mean_post, 4),
            "mean_change": round(mean_diff, 4),
            "bootstrap_ci_95": {
                "low": round(ci_low, 4),
                "high": round(ci_high, 4)
            },
            "effect_size": {
                "cohens_d": round(cohens_d, 4),
                "ci_95": {
                    "low": round(d_ci_low, 4),
                    "high": round(d_ci_high, 4)
                }
            },
            "p_values": {
                "raw": round(p_raw, 6),
                "holm_bonferroni_corrected": round(p_corrected, 6)
            },
            "significant_after_correction": significant,
            "hypothesized_direction": direction
        }
        
        summary_metrics.append(metric_summary)
    
    return {
        "analysis_version": "1.0",
        "generated_at": "T040-execution", # Placeholder, actual timestamp handled by runner
        "metrics": summary_metrics,
        "summary_statistics": {
            "total_metrics_tested": len(summary_metrics),
            "significant_count": sum(1 for m in summary_metrics if m['significant_after_correction'])
        }
    }

def write_summary(summary_data: Dict[str, Any], output_path: Path) -> None:
    """Write the summary dictionary to a JSON file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(summary_data, f, indent=2)
    logger.info(f"Statistical summary written to {output_path}")

def main():
    """
    Main entry point for T040: Generate Statistical Summary.
    
    This script assumes that previous tasks (T034-T039) have been executed
    and the necessary intermediate files (change_scores.csv, bootstrap_results.json,
    effect_sizes.json, holm_results.json) exist in the data/processed directory.
    """
    logger.info("Starting T040: Statistical Summary Generation")
    
    # Define paths based on project structure
    processed_dir = Path(get_path('data_processed'))
    results_dir = Path(get_path('results'))
    
    # Expected input files (produced by T034, T036, T039, T038)
    # Note: The exact filenames depend on the output of the previous tasks.
    # We assume standard naming conventions based on the task descriptions.
    change_scores_file = processed_dir / "change_scores.csv"
    bootstrap_file = processed_dir / "bootstrap_results.json"
    effect_size_file = processed_dir / "effect_sizes.json"
    holm_file = processed_dir / "holm_bonferroni_results.json"
    
    output_file = results_dir / "statistical_summary.json"
    
    # 1. Load Merged Data to get baseline/post means for reference (optional but good for context)
    # We actually need the raw lists for the summary, so we load from the CSV generated by T035
    if not change_scores_file.exists():
        logger.error(f"Change scores file not found: {change_scores_file}. Please run T035 first.")
        return
    
    # 2. Load Bootstrap Results
    if not bootstrap_file.exists():
        logger.error(f"Bootstrap results file not found: {bootstrap_file}. Please run T036 first.")
        return
    
    # 3. Load Effect Sizes
    if not effect_size_file.exists():
        logger.error(f"Effect sizes file not found: {effect_size_file}. Please run T039 first.")
        return

    # 4. Load Holm-Bonferroni Results
    if not holm_file.exists():
        logger.error(f"Holm-Bonferroni results file not found: {holm_file}. Please run T038 first.")
        return

    try:
        # Load data structures
        # We need to reconstruct the change_scores dict from the CSV for the summary
        # The CSV has: participant_id, metric, baseline_value, post_value, change
        raw_data = load_merged_data(change_scores_file)
        
        # Re-aggregate by metric to get lists of baseline and post values
        metric_data = {}
        for record in raw_data:
            metric = record['metric']
            if metric not in metric_data:
                metric_data[metric] = {'baseline': [], 'post': []}
            metric_data[metric]['baseline'].append(record['baseline_value'])
            metric_data[metric]['post'].append(record['post_value'])
        
        # Load other results
        with open(bootstrap_file, 'r') as f:
            bootstrap_data = json.load(f)
            # Handle potential wrapping
            if isinstance(bootstrap_data, dict) and 'results' in bootstrap_data:
                bootstrap_data = bootstrap_data['results']
            # Ensure it's a dict keyed by metric
            if isinstance(bootstrap_data, list):
                bootstrap_data = {item['metric']: item for item in bootstrap_data}

        with open(effect_size_file, 'r') as f:
            effect_data = json.load(f)
            if isinstance(effect_data, dict) and 'results' in effect_data:
                effect_data = effect_data['results']
            if isinstance(effect_data, list):
                effect_data = {item['metric']: item for item in effect_data}

        with open(holm_file, 'r') as f:
            holm_data = json.load(f)
            if isinstance(holm_data, dict) and 'results' in holm_data:
                holm_data = holm_data['results']
            # If it's a list, it's fine

        # Aggregate
        summary = aggregate_results(metric_data, bootstrap_data, effect_data, holm_data)
        
        # Write
        write_summary(summary, output_file)
        
        logger.info("T040 completed successfully.")
        
    except Exception as e:
        logger.error(f"Error during T040 execution: {e}", exc_info=True)
        raise

if __name__ == "__main__":
    main()