"""
Decoder Cross-Validation Module for Narrative Archaeology (US3).

Implements K-fold cross-validation (K=5) for narrative element reconstruction
and reports accuracy against a calculated chance baseline.

This module fulfills Task T031.
"""
import numpy as np
import json
import logging
from pathlib import Path
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
import code.config as config

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_roi_features_and_labels(roi_name: str, phase: str = "early"):
    """
    Loads pre-extracted ROI timecourses and corresponding narrative labels.
    
    Expected data source: data/processed/roi_timecourses.h5 (generated by T013)
    and data/processed/events_aligned.csv (generated by T012).
    
    Args:
        roi_name: Name of the ROI (e.g., 'hippocampus', 'mPFC').
        phase: Event phase ('early' or 'late').
        
    Returns:
        X: numpy array of shape (n_samples, n_features)
        y: numpy array of shape (n_samples,) containing narrative labels
    """
    timecourses_path = config.get_data_path() / "processed" / "roi_timecourses.h5"
    events_path = config.get_data_path() / "processed" / "events_aligned.csv"
    
    if not timecourses_path.exists():
        raise FileNotFoundError(
            f"ROI timecourses file not found: {timecourses_path}. "
            "Please ensure T013 (ROI Masker) has completed successfully."
        )
    if not events_path.exists():
        raise FileNotFoundError(
            f"Events alignment file not found: {events_path}. "
            "Please ensure T012 (Segmentation) has completed successfully."
        )

    import h5py
    import pandas as pd

    # Load labels
    events_df = pd.read_csv(events_path)
    # Filter for the specific phase if the dataframe contains both
    if phase in events_df.columns:
        # Assuming the phase column indicates the event type or we filter rows
        # Based on T013 spec: "extract timecourses for ... both Early and Late event phases separately"
        # The h5 file likely has structure like: /{roi}/{phase}/data
        pass
    
    # Load timecourses from HDF5
    with h5py.File(timecourses_path, 'r') as f:
        if roi_name not in f:
            raise ValueError(f"ROI '{roi_name}' not found in {timecourses_path}")
        
        roi_group = f[roi_name]
        if phase not in roi_group:
            raise ValueError(f"Phase '{phase}' not found for ROI '{roi_name}' in {timecourses_path}")
        
        # Assuming structure: /roi/phase/data (n_samples, n_voxels)
        # and /roi/phase/labels (n_samples) or we map via index
        # For robustness, we assume the order matches the events CSV if not stored in h5
        data = roi_group[phase]['data'][:]
        # If labels are stored in the file:
        if 'labels' in roi_group[phase]:
            labels = roi_group[phase]['labels'][:]
        else:
            # Fallback: Load labels from CSV and match indices
            # This assumes the h5 file was written in the same order as events_aligned.csv
            # We filter the CSV for the specific phase if needed, but here we assume 
            # the h5 file already represents the specific phase data.
            # We need the 'narrative_label' column from the CSV corresponding to these rows.
            # Since we can't guarantee row alignment without a shared ID, we assume 
            # the h5 file stores the labels or we use the first N rows of the filtered CSV.
            # For this implementation, we rely on the h5 file storing labels if available,
            # otherwise we raise an error to enforce data integrity.
            raise ValueError(
                f"Labels not found in {timecourses_path} for {roi_name}/{phase}. "
                "The ROI extraction pipeline (T013) must save labels to the HDF5 file."
            )

    # Convert labels to string if they are integers/objects
    y = np.array([str(l) for l in labels])
    X = data.astype(np.float32)

    logger.info(f"Loaded {X.shape[0]} samples for ROI: {roi_name}, Phase: {phase}")
    return X, y

def run_kfold_cross_validation(X, y, n_splits=5, random_state=42):
    """
    Runs K-fold cross-validation using RidgeClassifier.
    
    Args:
        X: Feature matrix (n_samples, n_features)
        y: Label array (n_samples,)
        n_splits: Number of folds (default 5)
        random_state: Random seed for reproducibility
        
    Returns:
        accuracy: Mean cross-validation accuracy
        std_accuracy: Standard deviation of accuracy
        cv_scores: Array of individual fold scores
        chance_baseline: Calculated chance baseline (1 / N_unique_labels)
    """
    # Encode labels to integers if they aren't already
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)
    n_classes = len(le.classes_)
    
    # Calculate chance baseline
    # Per spec: "Metric: Calculate chance baseline as 1 / N_actual"
    chance_baseline = 1.0 / n_classes
    
    logger.info(f"Classes detected: {le.classes_} (N={n_classes})")
    logger.info(f"Chance baseline (1/{n_classes}): {chance_baseline:.4f}")

    # Setup KFold
    kfold = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    
    # Setup Classifier
    clf = RidgeClassifier()
    
    # Run Cross Validation
    # cv_score returns accuracy by default for classifiers
    cv_scores = cross_val_score(clf, X, y_encoded, cv=kfold)
    
    mean_accuracy = np.mean(cv_scores)
    std_accuracy = np.std(cv_scores)
    
    logger.info(f"CV Accuracy: {mean_accuracy:.4f} (+/- {std_accuracy:.4f})")
    logger.info(f"Deviation from chance: {mean_accuracy - chance_baseline:.4f}")
    
    return mean_accuracy, std_accuracy, cv_scores, chance_baseline, le.classes_

def main():
    """
    Main execution entry point for Task T031.
    
    Iterates over defined ROIs and phases, runs K-fold CV, and aggregates
    results into a JSON file at results/decoder_cv_metrics.json.
    """
    # Configuration
    rois = ["hippocampus", "mPFC", "PCC", "lateral_temporal_cortex"]
    phases = ["early", "late"]
    output_path = config.get_output_path() / "decoder_cv_metrics.json"
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    results = {
        "task_id": "T031",
        "description": "K-fold Cross-Validation (K=5) for Narrative Element Reconstruction",
        "k_splits": 5,
        "results": []
    }
    
    logger.info(f"Starting K-fold CV analysis for {len(rois)} ROIs across {len(phases)} phases.")
    
    for roi in rois:
        for phase in phases:
            try:
                logger.info(f"Processing ROI: {roi}, Phase: {phase}")
                
                X, y = load_roi_features_and_labels(roi, phase)
                
                if len(np.unique(y)) < 2:
                    logger.warning(f"Skipping {roi}/{phase}: Only one class present.")
                    continue
                
                mean_acc, std_acc, scores, chance, classes = run_kfold_cross_validation(
                    X, y, n_splits=5
                )
                
                result_entry = {
                    "roi": roi,
                    "phase": phase,
                    "n_samples": X.shape[0],
                    "n_classes": len(classes),
                    "classes": [str(c) for c in classes],
                    "accuracy": float(mean_acc),
                    "std_accuracy": float(std_acc),
                    "chance_baseline": float(chance),
                    "deviation_from_chance": float(mean_acc - chance),
                    "cv_scores": [float(s) for s in scores]
                }
                
                results["results"].append(result_entry)
                
            except Exception as e:
                logger.error(f"Failed to process {roi}/{phase}: {e}", exc_info=True)
                results["results"].append({
                    "roi": roi,
                    "phase": phase,
                    "error": str(e)
                })
    
    # Write results to file
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    
    logger.info(f"Analysis complete. Results written to {output_path}")
    
    # Print summary
    print("\n--- T031 Summary ---")
    for res in results["results"]:
        if "error" not in res:
            print(f"{res['roi']} ({res['phase']}): Acc={res['accuracy']:.3f} "
                  f"(Chance={res['chance_baseline']:.3f}, Diff={res['deviation_from_chance']:.3f})")
        else:
            print(f"{res['roi']} ({res['phase']}): ERROR - {res['error']}")

if __name__ == "__main__":
    main()
