"""
Module: validate_candidate_library.py
Task: T043 [US3] [Rev-Data]

Validates the generated virtual library (from T029a) to ensure:
1. It contains at least 50 unique, chemically valid SMILES strings.
2. Logs a warning if the molecular diversity metric (average pairwise Tanimoto distance)
   falls below a defined threshold (0.3).

Input: data/processed/bio_candidates.csv (generated by T029a)
Output: data/reports/candidate_library_validation.json
"""
import os
import sys
import json
import logging
import pandas as pd
import numpy as np
from typing import List, Dict, Tuple, Optional
from pathlib import Path
from datetime import datetime

# Add project root to path if running as script
if __name__ == "__main__":
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from utils.logging_config import setup_pipeline_logger

# Constants
MIN_UNIQUE_SMILES = 50
DIVERSITY_THRESHOLD = 0.3  # Average Tanimoto distance threshold
INPUT_FILE = "data/processed/bio_candidates.csv"
OUTPUT_FILE = "data/reports/candidate_library_validation.json"

def setup_logger():
    """Setup pipeline logger for this module."""
    return setup_pipeline_logger("validate_candidate_library")

def load_candidates(file_path: str, logger: logging.Logger) -> pd.DataFrame:
    """
    Load the candidate library from CSV.
    
    Args:
        file_path: Path to the CSV file.
        logger: Logger instance.
        
    Returns:
        DataFrame with 'smiles' column.
        
    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If required columns are missing.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Candidate library file not found: {file_path}")
    
    df = pd.read_csv(path)
    if 'smiles' not in df.columns:
        raise ValueError(f"Input file must contain 'smiles' column. Found: {df.columns.tolist()}")
    
    logger.info(f"Loaded {len(df)} candidate records from {file_path}")
    return df

def validate_smiles(smiles_list: List[str], logger: logging.Logger) -> Tuple[int, int, List[str]]:
    """
    Validate a list of SMILES strings using RDKit.
    
    Args:
        smiles_list: List of SMILES strings.
        logger: Logger instance.
        
    Returns:
        Tuple of (valid_count, invalid_count, list of invalid SMILES).
    """
    valid_count = 0
    invalid_count = 0
    invalid_smiles = []
    
    for i, smi in enumerate(smiles_list):
        if pd.isna(smi) or not isinstance(smi, str) or not smi.strip():
            invalid_count += 1
            invalid_smiles.append(f"Row {i}: Empty/NaN")
            continue
        
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            invalid_count += 1
            invalid_smiles.append(f"Row {i}: {smi[:50]}...")
        else:
            valid_count += 1
    
    logger.info(f"SMILES Validation: {valid_count} valid, {invalid_count} invalid")
    return valid_count, invalid_count, invalid_smiles

def calculate_diversity_metric(smiles_list: List[str], logger: logging.Logger) -> float:
    """
    Calculate the average pairwise Tanimoto distance (diversity metric) for the library.
    Uses Morgan fingerprints (radius=2, nBits=2048).
    
    Args:
        smiles_list: List of valid SMILES strings.
        logger: Logger instance.
        
    Returns:
        Average Tanimoto distance (float). Returns 0.0 if fewer than 2 valid molecules.
    """
    if len(smiles_list) < 2:
        logger.warning("Insufficient molecules (<2) to calculate diversity metric.")
        return 0.0
    
    mols = []
    for smi in smiles_list:
        mol = Chem.MolFromSmiles(smi)
        if mol:
            mols.append(mol)
    
    if len(mols) < 2:
        logger.warning("Insufficient valid molecules after filtering to calculate diversity.")
        return 0.0
    
    fps = [AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=2048) for mol in mols]
    
    # Calculate average pairwise distance
    # Tanimoto distance = 1 - Tanimoto similarity
    total_distance = 0.0
    count = 0
    
    # Sample pairs if dataset is too large to avoid O(N^2) explosion in validation step
    # For N=50 to 500, O(N^2) is acceptable. If N > 1000, sample.
    if len(fps) > 1000:
        logger.info("Large library detected (>1000). Sampling 1000 random pairs for diversity estimate.")
        import random
        pairs = []
        for _ in range(1000):
            i, j = random.sample(range(len(fps)), 2)
            pairs.append((i, j))
    else:
        pairs = [(i, j) for i in range(len(fps)) for j in range(i+1, len(fps))]
    
    for i, j in pairs:
        sim = DataStructs.TanimotoSimilarity(fps[i], fps[j])
        total_distance += (1.0 - sim)
        count += 1
    
    avg_distance = total_distance / count if count > 0 else 0.0
    logger.info(f"Calculated diversity metric (avg Tanimoto distance): {avg_distance:.4f}")
    return avg_distance

def validate_library(file_path: str, output_path: str, logger: logging.Logger) -> Dict:
    """
    Main validation logic.
    
    Args:
        file_path: Path to input CSV.
        output_path: Path to output JSON report.
        logger: Logger instance.
        
    Returns:
        Dictionary containing validation results.
    """
    # Load data
    df = load_candidates(file_path, logger)
    
    # Extract SMILES list
    raw_smiles = df['smiles'].tolist()
    total_count = len(raw_smiles)
    
    # 1. Uniqueness Check
    unique_smiles = list(set([s for s in raw_smiles if isinstance(s, str) and s.strip()]))
    unique_count = len(unique_smiles)
    logger.info(f"Unique SMILES count: {unique_count} / {total_count}")
    
    # 2. Chemical Validity Check
    valid_count, invalid_count, invalid_list = validate_smiles(unique_smiles, logger)
    
    # 3. Diversity Check (on valid unique SMILES)
    valid_unique_smiles = [s for i, s in enumerate(unique_smiles) if i < valid_count] 
    # Note: validate_smiles returns count, but we need the actual valid list. 
    # Re-filtering based on RDKit parse for the actual valid set for diversity calc.
    valid_mol_smiles = []
    for s in unique_smiles:
        if Chem.MolFromSmiles(s):
            valid_mol_smiles.append(s)
    
    diversity_score = calculate_diversity_metric(valid_mol_smiles, logger)
    
    # Determine Status
    is_valid_count = valid_count >= MIN_UNIQUE_SMILES
    is_diverse = diversity_score >= DIVERSITY_THRESHOLD
    
    status = "PASS"
    warnings = []
    
    if not is_valid_count:
        status = "FAIL"
        warnings.append(f"Insufficient unique valid SMILES: {valid_count} < {MIN_UNIQUE_SMILES}")
    
    if not is_diverse:
        status = "WARNING" if status == "PASS" else status
        warnings.append(f"Diversity metric below threshold: {diversity_score:.4f} < {DIVERSITY_THRESHOLD}")
    
    # Prepare Report
    report = {
        "timestamp": datetime.now().isoformat(),
        "input_file": file_path,
        "validation_status": status,
        "metrics": {
            "total_records": total_count,
            "unique_smiles_count": unique_count,
            "chemically_valid_count": valid_count,
            "invalid_smiles_count": invalid_count,
            "diversity_metric_tanimoto_avg": float(diversity_score),
            "min_required_unique": MIN_UNIQUE_SMILES,
            "diversity_threshold": DIVERSITY_THRESHOLD
        },
        "checks": {
            "sufficient_count": is_valid_count,
            "sufficient_diversity": is_diverse
        },
        "warnings": warnings,
        "sample_invalid_smiles": invalid_list[:10] if invalid_list else []
    }
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Save report
    with open(output_path, 'w') as f:
        json.dump(report, f, indent=2)
    
    logger.info(f"Validation report saved to {output_path}")
    return report

def main():
    """Entry point for the script."""
    logger = setup_logger()
    logger.info("Starting Candidate Library Validation (T043)")
    
    try:
        # Resolve paths relative to project root
        project_root = Path(__file__).resolve().parents[2]
        input_path = project_root / INPUT_FILE
        output_path = project_root / OUTPUT_FILE
        
        if not input_path.exists():
            logger.error(f"Input file not found: {input_path}")
            logger.error("Ensure T029a (generate_bio_candidates.py) has been run successfully.")
            sys.exit(1)
        
        report = validate_library(str(input_path), str(output_path), logger)
        
        if report['validation_status'] == "FAIL":
            logger.error("Validation FAILED. See report for details.")
            sys.exit(1)
        elif report['validation_status'] == "WARNING":
            logger.warning("Validation completed with warnings. See report.")
        else:
            logger.info("Validation PASSED.")
            
    except Exception as e:
        logger.exception(f"Validation process failed with exception: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()