"""
Missingness injection logic for MNAR simulation.

This module implements the Missingness Mechanism for the simulation study.
Crucially, it documents the nature of the "ground truth" in this context:

Ground Truth Definition:
The term "ground truth" in this simulation refers to the GENERATIVE PARAMETERS
(specifically the true Average Treatment Effect, tau_true, and the MNAR
mechanism parameter beta) used to create the synthetic data.

Identifiability Warning:
Under the Missing Not At Random (MNAR) mechanism implemented here, the outcome
variable Y directly influences the missingness mask M. Consequently, the true
Average Treatment Effect (ATE) is NOT IDENTIFIABLE from the observed (incomplete)
data alone without strong, untestable assumptions about the missingness mechanism.
The "ground truth" ATE is known only because we generated the data with it; it
cannot be recovered from the observed data using standard causal inference methods
that assume Missing At Random (MAR) or Missing Completely At Random (MCAR).

This simulation quantifies the bias introduced when standard imputation methods
(which typically assume MAR) are applied to data generated under an MNAR mechanism.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Union, Dict, Any, Tuple
import numpy as np
import pandas as pd
from scipy.special import expit
import logging

# Configure logging for the module
logger = logging.getLogger(__name__)

@dataclass
class MissingnessPattern:
    """
    Represents a specific missingness pattern generated by an injector.

    Attributes:
        mask: Boolean array where True indicates missing data.
        alpha: Intercept parameter for the missingness logistic model.
        beta: Slope parameter for the missingness logistic model (MNAR intensity).
        target_rate: The intended proportion of missing values.
    """
    mask: np.ndarray
    alpha: float
    beta: float
    target_rate: float

class MissingnessInjector(ABC):
    """Abstract base class for missingness injection strategies."""

    @abstractmethod
    def inject(self, data: pd.DataFrame, **kwargs) -> Tuple[pd.DataFrame, MissingnessPattern]:
        """
        Inject missingness into the provided dataset.

        Args:
            data: The complete dataset (DataFrame).
            **kwargs: Additional parameters specific to the injection strategy.

        Returns:
            A tuple containing:
                - The dataset with missing values (NaN) applied.
                - A MissingnessPattern object describing the injection.
        """
        pass

class MNARInjector(MissingnessInjector):
    """
    Injects missingness based on the outcome variable Y (MNAR mechanism).

    The probability of missingness is modeled as:
    P(M=1 | Y) = expit(alpha + beta * Y)

    Where:
    - alpha controls the baseline missingness rate.
    - beta controls the dependence on Y (MNAR intensity).
    """

    def inject(self, data: pd.DataFrame, beta: float, target_rate: float, 
               outcome_col: str = 'Y', rng: Optional[np.random.Generator] = None) -> Tuple[pd.DataFrame, MissingnessPattern]:
        """
        Inject MNAR missingness based on the outcome column.

        Args:
            data: Complete dataset.
            beta: MNAR intensity parameter.
            target_rate: Target proportion of missing values.
            outcome_col: Name of the column to base missingness on (default 'Y').
            rng: NumPy random generator for reproducibility.

        Returns:
            Tuple of (incomplete dataset, MissingnessPattern).
        """
        if rng is None:
            rng = np.random.default_rng()

        if outcome_col not in data.columns:
            raise ValueError(f"Outcome column '{outcome_col}' not found in data.")

        y_values = data[outcome_col].values
        
        # Calculate alpha to achieve the target missingness rate
        alpha = tune_alpha(y_values, beta, target_rate, rng)

        # Calculate probabilities of missingness
        log_odds = alpha + beta * y_values
        probs = expit(log_odds)

        # Generate mask
        mask = rng.random(len(y_values)) < probs
        missingness_pattern = MissingnessPattern(
            mask=mask,
            alpha=alpha,
            beta=beta,
            target_rate=target_rate
        )

        # Apply mask to create incomplete data
        incomplete_data = data.copy()
        # Set the outcome column to NaN where mask is True
        # In a more general case, we might mask other columns too, but the spec
        # implies MNAR on Y specifically for the bias quantification.
        incomplete_data.loc[mask, outcome_col] = np.nan

        logger.info(f"MNAR Injection: alpha={alpha:.4f}, beta={beta:.4f}, "
                    f"actual_rate={mask.mean():.4f}, target_rate={target_rate}")

        return incomplete_data, missingness_pattern

def tune_alpha(y_values: np.ndarray, beta: float, target_rate: float, 
               rng: Optional[np.random.Generator] = None, 
               tol: float = 1e-4, max_iter: int = 100) -> float:
    """
    Finds the alpha parameter that yields the desired missingness rate for a given beta.

    Uses a simple binary search over alpha values.

    Args:
        y_values: Array of outcome values.
        beta: MNAR intensity parameter.
        target_rate: Desired proportion of missing values.
        rng: Random generator (not strictly needed for binary search but kept for signature).
        tol: Tolerance for convergence.
        max_iter: Maximum iterations.

    Returns:
        The alpha value that achieves the target rate.
    """
    if rng is None:
        rng = np.random.default_rng()

    # Search range for alpha
    alpha_low, alpha_high = -10.0, 10.0
    
    for _ in range(max_iter):
        alpha_mid = (alpha_low + alpha_high) / 2
        log_odds = alpha_mid + beta * y_values
        probs = expit(log_odds)
        current_rate = probs.mean()

        if abs(current_rate - target_rate) < tol:
            return alpha_mid

        if current_rate < target_rate:
            alpha_low = alpha_mid
        else:
            alpha_high = alpha_mid

    logger.warning(f"tune_alpha did not converge within {max_iter} iterations. "
                   f"Final rate: {probs.mean():.4f}, Target: {target_rate}")
    return alpha_mid

def inject_mnar(data: pd.DataFrame, beta: float, target_rate: float, 
                outcome_col: str = 'Y', seed: Optional[int] = None) -> Tuple[pd.DataFrame, MissingnessPattern]:
    """
    Convenience function to inject MNAR missingness.

    Args:
        data: Complete dataset.
        beta: MNAR intensity parameter.
        target_rate: Target missingness rate.
        outcome_col: Column name for outcome.
        seed: Random seed for reproducibility.

    Returns:
        Tuple of (incomplete dataset, MissingnessPattern).
    """
    rng = np.random.default_rng(seed)
    injector = MNARInjector()
    return injector.inject(data, beta=beta, target_rate=target_rate, 
                           outcome_col=outcome_col, rng=rng)
