"""
Integration test for report generation (Task T028).

This test verifies the end-to-end generation of the final evaluation report
by executing the report generation pipeline on the outputs produced by
previous tasks (T022, T023, T024, T025, T026, T029, T030).

It ensures that:
1. The report generation script runs without error.
2. The expected output files (summary table, calibration plot, final report)
   are created in the correct locations.
3. The content of the generated files matches the expected schema.
"""

import os
import sys
import json
import pytest
import pandas as pd
from pathlib import Path

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent.parent
CODE_DIR = PROJECT_ROOT / "code"
DATA_DIR = PROJECT_ROOT / "data"
FIGURES_DIR = PROJECT_ROOT / "figures"

sys.path.insert(0, str(CODE_DIR))

from evaluation.report import generate_report
from evaluation.metrics import calculate_metrics, generate_calibration_plot


@pytest.fixture(scope="module")
def setup_test_environment():
    """Ensure required directories exist."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "processed").mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "final").mkdir(parents=True, exist_ok=True)
    return True


@pytest.mark.integration
def test_report_generation_pipeline(setup_test_environment, tmp_path):
    """
    Integration test: Run the full report generation pipeline.

    This test simulates the execution of T030, T031, and T032 by calling
    the main entry point of the report generation module.
    """
    # Define expected input/output paths based on tasks.md
    # Inputs (produced by previous tasks)
    logistic_results_path = DATA_DIR / "final" / "logistic_model_results.json"
    bayesian_results_path = DATA_DIR / "final" / "bayesian_model_results.json"
    vif_results_path = DATA_DIR / "final" / "vif_results.json"
    lrt_results_path = DATA_DIR / "final" / "lrt_results.json"
    metrics_path = DATA_DIR / "final" / "evaluation_metrics.json"

    # Outputs (to be generated by this task)
    summary_table_path = DATA_DIR / "final" / "report_summary.csv"
    calibration_plot_path = FIGURES_DIR / "calibration_plot.png"
    final_report_path = DATA_DIR / "final" / "final_report.md"

    # Mock input files if they don't exist (for CI/CD isolation)
    # In a real run, these would be produced by T022-T026 and T029
    if not logistic_results_path.exists():
        logistic_results_path.parent.mkdir(parents=True, exist_ok=True)
        with open(logistic_results_path, 'w') as f:
            json.dump({
                "model_type": "LogisticRegression",
                "auc": 0.75,
                "coefficients": {"similarity": 0.5, "role": 0.3, "frequency": 0.2},
                "p_values": {"similarity": 0.01, "role": 0.02, "frequency": 0.03}
            }, f)

    if not bayesian_results_path.exists():
        bayesian_results_path.parent.mkdir(parents=True, exist_ok=True)
        with open(bayesian_results_path, 'w') as f:
            json.dump({
                "model_type": "BayesianHierarchical",
                "auc": 0.78,
                "posterior_means": {"similarity": 0.52, "role": 0.31, "frequency": 0.21},
                "convergence": True
            }, f)

    if not vif_results_path.exists():
        vif_results_path.parent.mkdir(parents=True, exist_ok=True)
        with open(vif_results_path, 'w') as f:
            json.dump({
                "vif_scores": {"similarity": 1.2, "role": 1.1, "frequency": 1.05},
                "status": "PASS"
            }, f)

    if not lrt_results_path.exists():
        lrt_results_path.parent.mkdir(parents=True, exist_ok=True)
        with open(lrt_results_path, 'w') as f:
            json.dump({
                "p_value": 0.005,
                "chi2_statistic": 12.5,
                "status": "SIGNIFICANT"
            }, f)

    if not metrics_path.exists():
        metrics_path.parent.mkdir(parents=True, exist_ok=True)
        with open(metrics_path, 'w') as f:
            json.dump({
                "logistic": {"auc": 0.75, "precision": 0.72, "recall": 0.68},
                "bayesian": {"auc": 0.78, "precision": 0.74, "recall": 0.70}
            }, f)

    # Execute the report generation
    # This corresponds to the main logic in code/evaluation/report.py
    try:
        generate_report(
            logistic_results_path=logistic_results_path,
            bayesian_results_path=bayesian_results_path,
            vif_results_path=vif_results_path,
            lrt_results_path=lrt_results_path,
            metrics_path=metrics_path,
            output_summary_path=summary_table_path,
            output_plot_path=calibration_plot_path,
            output_report_path=final_report_path
        )
    except Exception as e:
        pytest.fail(f"Report generation failed with error: {str(e)}")

    # Assertions: Verify output files exist and are non-empty
    assert summary_table_path.exists(), "Summary table CSV not generated"
    assert summary_table_path.stat().st_size > 0, "Summary table CSV is empty"

    assert calibration_plot_path.exists(), "Calibration plot not generated"
    assert calibration_plot_path.stat().st_size > 0, "Calibration plot is empty"

    assert final_report_path.exists(), "Final report markdown not generated"
    assert final_report_path.stat().st_size > 0, "Final report markdown is empty"

    # Assertions: Verify content structure
    # 1. Check Summary Table
    df_summary = pd.read_csv(summary_table_path)
    expected_columns = ["metric", "logistic_value", "bayesian_value", "delta", "significance"]
    assert list(df_summary.columns) == expected_columns, f"Unexpected columns in summary: {df_summary.columns}"

    # 2. Check Final Report Content
    with open(final_report_path, 'r') as f:
        report_content = f.read()

    required_sections = [
        "Statistical Analysis Report",
        "Executive Summary",
        "Model Performance",
        "Statistical Significance",
        "Conclusion"
    ]

    for section in required_sections:
        assert section in report_content, f"Missing section '{section}' in final report"

    # 3. Verify specific evidence claims (T031, T032)
    # Check for mention of p-values and AUC delta
    assert "p-value" in report_content.lower(), "Report missing p-value discussion"
    assert "auc" in report_content.lower(), "Report missing AUC discussion"

    print("Integration test for report generation passed successfully.")
    print(f"  - Summary Table: {summary_table_path}")
    print(f"  - Calibration Plot: {calibration_plot_path}")
    print(f"  - Final Report: {final_report_path}")