"""
T015: Apply Bonferroni Correction for Full Family of Widths.

Reads scaling fit results (localization lengths and p-values) from all disorder widths,
applies Bonferroni correction to control Family-Wise Error Rate (FWER) at alpha=0.05
across the full family of 10 widths, and outputs the corrected results.

Output: data/processed/bonferroni_results.json
"""
import json
import os
import logging
from pathlib import Path
from typing import Dict, Any, List, Tuple
import numpy as np

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Constants defined by task T015
ALPHA_BASE = 0.05
NUM_WIDTHS = 10  # Full family of widths as per SC-005

def load_scaling_fits(input_path: str) -> Dict[str, Any]:
    """
    Load the scaling fits JSON file generated by T013.
    Expected structure: { "widths": { "W_val": { "xi": float, "p_value": float, ... } } }
    """
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"Scaling fits file not found: {input_path}")

    with open(path, 'r') as f:
        data = json.load(f)

    if "widths" not in data:
        raise ValueError(f"Invalid format in {input_path}: missing 'widths' key")

    return data

def apply_bonferroni_correction(p_values: List[float], alpha: float = ALPHA_BASE, n: int = NUM_WIDTHS) -> Tuple[List[float], float]:
    """
    Apply Bonferroni correction to a list of p-values.
    Corrected alpha = alpha / n.
    Returns corrected p-values (clipped at 1.0) and the new threshold.
    """
    corrected_alpha = alpha / n
    corrected_p_values = [min(p * n, 1.0) for p in p_values]
    return corrected_p_values, corrected_alpha

def analyze_scaling_slopes(widths_data: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """
    Analyze the scaling slopes (p-values) across widths to determine significance
    under the Bonferroni-corrected threshold.
    """
    # Extract p-values and corresponding widths
    # Assuming the data structure from T013: widths_data[W] contains 'p_value'
    width_keys = sorted(widths_data.keys(), key=lambda x: float(x))
    
    p_values = []
    width_list = []
    
    for w_str in width_keys:
        w_val = float(w_str)
        data = widths_data[w_str]
        if 'p_value' not in data:
            logger.warning(f"No p_value found for W={w_val}, skipping")
            continue
        
        p_values.append(data['p_value'])
        width_list.append(w_val)

    if not p_values:
        raise ValueError("No valid p-values found in scaling fits.")

    # Apply Bonferroni correction
    corrected_p_values, corrected_alpha = apply_bonferroni_correction(p_values)

    # Determine significance
    results = []
    significant_count = 0
    for w, p_orig, p_corr in zip(width_list, p_values, corrected_p_values):
        is_significant = p_corr < corrected_alpha
        if is_significant:
            significant_count += 1
        results.append({
            "width": w,
            "original_p_value": p_orig,
            "bonferroni_corrected_p_value": p_corr,
            "threshold": corrected_alpha,
            "is_significant": is_significant
        })

    return {
        "family_wise_error_rate_control": "Bonferroni",
        "alpha_base": ALPHA_BASE,
        "num_comparisons": len(p_values),
        "corrected_alpha": corrected_alpha,
        "significant_results": significant_count,
        "total_results": len(p_values),
        "detailed_results": results
    }

def main():
    """Main entry point for T015."""
    # Paths relative to project root
    input_path = "data/processed/scaling_fits.json"
    output_path = "data/processed/bonferroni_results.json"

    logger.info(f"Loading scaling fits from {input_path}...")
    try:
        raw_data = load_scaling_fits(input_path)
    except (FileNotFoundError, ValueError) as e:
        logger.error(f"Failed to load input data: {e}")
        raise

    widths_data = raw_data.get("widths", {})
    if not widths_data:
        logger.error("No width data found in input file.")
        raise ValueError("No width data found.")

    logger.info(f"Processing {len(widths_data)} disorder widths...")
    analysis_results = analyze_scaling_slopes(widths_data)

    # Ensure output directory exists
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    # Write results
    with open(output_path, 'w') as f:
        json.dump(analysis_results, f, indent=2)

    logger.info(f"Bonferroni correction analysis complete. Results written to {output_path}")
    logger.info(f"Corrected Alpha Threshold: {analysis_results['corrected_alpha']:.6f}")
    logger.info(f"Significant Results: {analysis_results['significant_results']}/{analysis_results['total_results']}")

    return analysis_results

if __name__ == "__main__":
    main()