"""
Minimal report generator for the SpatialClaw restriction pipeline.

The full statistical report generation (T048) will later replace this placeholder
with a comprehensive markdown document. For now, the module provides a ``main``
function that creates a simple placeholder report so that the full pipeline
runner can execute without error.
"""

import os
import json
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def _load_final_paired_dataset(csv_path: str) -> bool:
    """
    Very light validation that the final paired dataset CSV exists.
    Returns True if the file is present and non‑empty.
    """
    if not os.path.exists(csv_path):
        logger.warning(f"Paired dataset not found at {csv_path}")
        return False
    try:
        with open(csv_path, "r") as f:
            first_line = f.readline()
            return bool(first_line.strip())
    except Exception as e:
        logger.error(f"Error reading paired dataset: {e}")
        return False

def main() -> None:
    """
    Entry point for the report generation step.

    It creates a minimal markdown report at
    ``results/analysis/final_statistical_report.md`` containing a timestamp
    and a note that the detailed report will be produced by a later task.
    """
    report_path = os.path.join(
        "results", "analysis", "final_statistical_report.md"
    )
    os.makedirs(os.path.dirname(report_path), exist_ok=True)

    paired_csv = os.path.join(
        "results", "analysis", "final_paired_dataset.csv"
    )
    dataset_exists = _load_final_paired_dataset(paired_csv)

    with open(report_path, "w") as f:
        f.write(f"# Final Statistical Report\n")
        f.write(f"Generated on: {datetime.utcnow().isoformat()}Z\\n\\n")
        if dataset_exists:
            f.write(
                "The paired dataset was found and will be analyzed in subsequent steps.\\n"
            )
        else:
            f.write(
                "⚠️ Paired dataset not found – statistical analysis could not be performed.\\n"
            )
        f.write(
            "\\n*This placeholder report is generated by ``code/stats/report_generator.py``.*\\n"
        )

    logger.info(f"Report written to {report_path}")
