import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional, List

import pandas as pd
import numpy as np

from config import get_config
from utils import setup_logging

logger = logging.getLogger(__name__)

def load_regression_results() -> Optional[pd.DataFrame]:
    """
    Load the regression results generated by T027.
    Expected file: data/processed/regression_results.json
    """
    config = get_config()
    input_path = config["paths"]["processed"] / "regression_results.json"

    if not input_path.exists():
        logger.error(f"Regression results file not found: {input_path}")
        return None

    try:
        with open(input_path, "r") as f:
            data = json.load(f)

        # The T027 output structure is a dict with keys like 'coefficients', 'p_values', etc.
        # We need to convert this into a DataFrame or a structured dict for the stats report.
        # Assuming the structure from T027:
        # {
        #   "coefficients": {"temp": 0.5, "mass": -0.2, ...},
        #   "p_values": {"temp": 0.01, "mass": 0.05, ...},
        #   "model_fit": {"r_squared": 0.45, ...},
        #   "fallback_triggered": false
        # }
        
        if not isinstance(data, dict):
            logger.error("Regression results JSON is not a dictionary.")
            return None

        return data

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse regression results JSON: {e}")
        return None
    except Exception as e:
        logger.error(f"Unexpected error loading regression results: {e}")
        return None

def compute_regression_stats(regression_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compute summary statistics from the regression results.
    Returns a dictionary with:
      - coefficients: dict of variable -> coefficient
      - p_values: dict of variable -> p-value
      - model_fit: dict of fit metrics (R^2, etc.)
      - fallback_triggered: boolean
      - n_observations: estimated number of observations used (if available)
      - summary: a brief textual summary
    """
    if not regression_data:
        return {}

    coefficients = regression_data.get("coefficients", {})
    p_values = regression_data.get("p_values", {})
    model_fit = regression_data.get("model_fit", {})
    fallback_triggered = regression_data.get("fallback_triggered", False)

    # Count significant predictors (p < 0.05)
    significant_count = sum(1 for p in p_values.values() if p < 0.05)
    total_predictors = len(p_values)

    # Construct summary
    summary_parts = []
    summary_parts.append(f"Regression model used: {'Survival (Cox/AFT)' if fallback_triggered else 'Tobit'}")
    summary_parts.append(f"Total predictors: {total_predictors}")
    summary_parts.append(f"Significant predictors (p < 0.05): {significant_count}")
    
    if model_fit:
        r2 = model_fit.get("r_squared", model_fit.get("pseudo_r_squared", "N/A"))
        summary_parts.append(f"Model fit (R^2/Pseudo-R^2): {r2}")

    summary = ". ".join(summary_parts) + "."

    stats = {
        "coefficients": coefficients,
        "p_values": p_values,
        "model_fit": model_fit,
        "fallback_triggered": fallback_triggered,
        "significant_predictors_count": significant_count,
        "total_predictors_count": total_predictors,
        "summary": summary
    }

    return stats

def save_regression_stats(stats: Dict[str, Any], output_path: Path) -> bool:
    """
    Save the computed regression statistics to a JSON file.
    """
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(stats, f, indent=2)
        logger.info(f"Regression statistics saved to: {output_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to save regression statistics: {e}")
        return False

def main():
    """
    Main entry point for T030b: Output regression statistics.
    """
    setup_logging()
    config = get_config()
    output_path = config["paths"]["processed"] / "regression_stats.json"

    logger.info("Starting T030b: Output regression statistics.")

    # Load regression results from T027
    regression_data = load_regression_results()
    
    if regression_data is None:
        logger.error("Could not load regression results. T030b cannot proceed.")
        return 1

    # Compute statistics
    stats = compute_regression_stats(regression_data)

    if not stats:
        logger.error("Failed to compute regression statistics.")
        return 1

    # Save to file
    success = save_regression_stats(stats, output_path)

    if success:
        logger.info("T030b completed successfully.")
        return 0
    else:
        logger.error("T030b failed to save output.")
        return 1

if __name__ == "__main__":
    exit(main())