import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Set, Tuple, Optional
import pandas as pd

from utils.logging import get_logger
from utils.exceptions import DataInsufficientError, SchemaMismatchError
from utils.config import get_processed_dataset_path, get_split_indices_path, get_split_validation_path, get_log_path

logger = get_logger(__name__)


def load_processed_data() -> pd.DataFrame:
    """Load the preprocessed dataset."""
    path = get_processed_dataset_path()
    if not path.exists():
        raise DataInsufficientError(f"Processed dataset not found at {path}")
    logger.info(f"Loading processed dataset from {path}")
    return pd.read_parquet(path)


def load_split_indices() -> List[Tuple[List[int], List[int]]]:
    """Load the train/test indices generated by the split module."""
    path = get_split_indices_path()
    if not path.exists():
        raise DataInsufficientError(f"Split indices not found at {path}")
    logger.info(f"Loading split indices from {path}")
    with open(path, 'r') as f:
        data = json.load(f)
    # Expected format: [{"train": [idxs], "test": [idxs]}, ...]
    return [(fold["train"], fold["test"]) for fold in data]


def validate_split_integrity(
    df: pd.DataFrame,
    split_indices: List[Tuple[List[int], List[int]]],
    group_col: str = "specific_alloy_designation"
) -> Dict[str, Any]:
    """
    Verify strict LOSO constraint: ensure zero overlap of specific_alloy_designation
    between train and test sets for every fold.

    Returns a dictionary containing fold statistics and global validation status.
    """
    if group_col not in df.columns:
        raise SchemaMismatchError(f"Group column '{group_col}' not found in dataset. Columns: {list(df.columns)}")

    results = {
        "total_folds": len(split_indices),
        "folds": [],
        "global_status": "PASS",
        "details": []
    }

    all_failures = []

    for i, (train_idx, test_idx) in enumerate(split_indices):
        train_alloys = set(df.iloc[train_idx][group_col].unique())
        test_alloys = set(df.iloc[test_idx][group_col].unique())

        overlap = train_alloys.intersection(test_alloys)
        overlap_count = len(overlap)
        overlap_alloys = sorted(list(overlap))

        fold_status = "PASS" if overlap_count == 0 else "FAIL"
        if fold_status == "FAIL":
            results["global_status"] = "FAIL"
            all_failures.append(f"Fold {i} has {overlap_count} overlapping alloys: {overlap_alloys}")

        fold_report = {
            "fold_id": i,
            "train_count": len(train_idx),
            "test_count": len(test_idx),
            "unique_train_alloys": len(train_alloys),
            "unique_test_alloys": len(test_alloys),
            "overlap_count": overlap_count,
            "overlap_alloys": overlap_alloys,
            "status": fold_status
        }
        results["folds"].append(fold_report)
        results["details"].append(f"Fold {i}: Train({len(train_idx)}) vs Test({len(test_idx)}) -> Overlap: {overlap_count}")

    if all_failures:
        logger.error(f"Split integrity check FAILED. {len(all_failures)} folds violated LOSO constraint.")
        raise DataInsufficientError(f"LOSO constraint violated in {len(all_failures)} folds: {all_failures}")
    
    logger.info("Split integrity check PASSED. No alloy overlap detected between train/test sets.")
    return results


def save_split_results(results: Dict[str, Any]) -> Path:
    """Save the validation results to the designated JSON file."""
    output_path = get_split_validation_path()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    
    logger.info(f"Split validation results saved to {output_path}")
    return output_path


def main():
    """
    Main entry point for T017: Verify split integrity.
    1. Load processed data.
    2. Load split indices.
    3. Validate LOSO constraint (zero overlap).
    4. Save results to data/logs/split_validation.json.
    """
    logger.info("Starting split integrity verification (T017)...")
    
    try:
        df = load_processed_data()
        split_indices = load_split_indices()
        
        if not split_indices:
            raise DataInsufficientError("No split indices found to validate.")
        
        validation_results = validate_split_integrity(df, split_indices)
        output_path = save_split_results(validation_results)
        
        logger.info(f"Verification complete. Global Status: {validation_results['global_status']}")
        logger.info(f"Output written to: {output_path}")
        
        if validation_results['global_status'] == "FAIL":
            return 1
        return 0

    except (DataInsufficientError, SchemaMismatchError) as e:
        logger.error(f"Verification failed with error: {e}")
        return 1
    except Exception as e:
        logger.exception(f"Unexpected error during verification: {e}")
        return 1


if __name__ == "__main__":
    import sys
    sys.exit(main())