"""
Patch entity definition for the llmXive bug fix explainability project.

This module defines the Patch dataclass which represents an LLM-generated
patch for a specific bug, including the diff content and the generated rationale.
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Patch:
    """
    Represents a patch generated by an LLM to fix a specific bug.

    Attributes:
        id (str): Unique identifier for the patch (typically derived from bug_id + run_id).
        bug_id (str): The identifier of the bug this patch attempts to fix.
        diff_content (str): The unified diff string representing the code changes.
        rationale_text (str): The natural language explanation generated by the LLM
                             describing why this patch fixes the bug.
    """
    id: str
    bug_id: str
    diff_content: str
    rationale_text: str

    def __post_init__(self):
        """Validate that required fields are not empty."""
        if not self.id:
            raise ValueError("Patch id cannot be empty")
        if not self.bug_id:
            raise ValueError("Patch bug_id cannot be empty")
        if self.diff_content is None:
            raise ValueError("Patch diff_content cannot be None")
        # rationale_text can be empty string if not generated, but not None
        if self.rationale_text is None:
            self.rationale_text = ""

    def to_dict(self) -> dict:
        """Convert the Patch object to a dictionary representation."""
        return {
            "id": self.id,
            "bug_id": self.bug_id,
            "diff_content": self.diff_content,
            "rationale_text": self.rationale_text
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Patch":
        """Create a Patch object from a dictionary."""
        return cls(
            id=data["id"],
            bug_id=data["bug_id"],
            diff_content=data["diff_content"],
            rationale_text=data.get("rationale_text", "")
        )