"""
T024 Implementation: Generate dynamic_scores.json with aligned task IDs.

This script consumes the dynamic scores calculated by T022/T023 and the
static scores from T017, aligns them by task_id, and writes the final
aggregated JSON output to data/processed/dynamic_scores.json.
"""
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, List, Any, Optional

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from code.utils.logger import get_logger, log_metric
from code.utils.config import get_config

# Setup logging
logger = get_logger("T024_GENERATE_OUTPUT", log_level=logging.INFO)

def load_static_scores(static_path: Path) -> Dict[str, Any]:
    """Load static scores generated by T017."""
    if not static_path.exists():
        raise FileNotFoundError(f"Static scores file not found at {static_path}. "
                                "Ensure T017 has been completed successfully.")
    
    logger.info(f"Loading static scores from {static_path}")
    with open(static_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Handle different possible structures (list of dicts or dict of dicts)
    if isinstance(data, list):
        return {item['task_id']: item for item in data}
    return data

def load_dynamic_scores(dynamic_path: Path) -> Dict[str, Any]:
    """Load dynamic scores generated by T023 (intermediate output)."""
    if not dynamic_path.exists():
        raise FileNotFoundError(f"Dynamic scores file not found at {dynamic_path}. "
                                "Ensure T022/T023 have been completed successfully.")
    
    logger.info(f"Loading dynamic scores from {dynamic_path}")
    with open(dynamic_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    if isinstance(data, list):
        return {item['task_id']: item for item in data}
    return data

def align_and_merge_scores(
    static_data: Dict[str, Any], 
    dynamic_data: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Align static and dynamic scores by task_id.
    
    Returns a list of merged records containing:
    - task_id
    - static_scores (vector)
    - dynamic_scores (cumulative reward)
    - decision_points (from dynamic rollout)
    - alignment_status (matched, missing_static, missing_dynamic)
    """
    all_task_ids = set(static_data.keys()) | set(dynamic_data.keys())
    merged_results = []
    
    stats = {'matched': 0, 'missing_static': 0, 'missing_dynamic': 0}
    
    for task_id in sorted(all_task_ids):
        record = {
            'task_id': task_id,
            'alignment_status': 'matched',
            'static_scores': None,
            'dynamic_scores': None,
            'decision_points': None,
            'metadata': {}
        }
        
        if task_id in static_data:
            static_entry = static_data[task_id]
            record['static_scores'] = static_entry.get('scores', [])
            record['metadata']['static_tokens'] = len(static_entry.get('tokens', []))
        else:
            record['alignment_status'] = 'missing_static'
            stats['missing_static'] += 1
        
        if task_id in dynamic_data:
            dynamic_entry = dynamic_data[task_id]
            record['dynamic_scores'] = dynamic_entry.get('cumulative_reward', 0.0)
            record['decision_points'] = dynamic_entry.get('decision_points', [])
            record['metadata']['rollout_steps'] = len(dynamic_entry.get('decision_points', []))
        else:
            if record['alignment_status'] == 'matched':
                record['alignment_status'] = 'missing_dynamic'
            stats['missing_dynamic'] += 1
        
        if record['alignment_status'] == 'matched':
            stats['matched'] += 1
        
        merged_results.append(record)
    
    # Log alignment statistics
    total = len(all_task_ids)
    log_metric(logger, "alignment_match_rate", stats['matched'] / total if total > 0 else 0.0)
    log_metric(logger, "alignment_missing_static_count", stats['missing_static'])
    log_metric(logger, "alignment_missing_dynamic_count", stats['missing_dynamic'])
    
    logger.info(f"Alignment complete: {stats['matched']} matched, "
                f"{stats['missing_static']} missing static, "
                f"{stats['missing_dynamic']} missing dynamic")
    
    return merged_results

def save_merged_output(merged_data: List[Dict[str, Any]], output_path: Path) -> None:
    """Save the merged alignment to the final output file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Saving merged output to {output_path}")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(merged_data, f, indent=2, ensure_ascii=False)
    
    logger.info(f"Successfully wrote {len(merged_data)} records to {output_path}")

def main() -> int:
    """Main entry point for T024."""
    config = get_config()
    
    # Define paths relative to project root
    static_input_path = PROJECT_ROOT / "data" / "processed" / "static_scores.json"
    # T023 likely outputs to a temp location or we assume it's in the same processed dir
    # Based on T022/T023 description, they generate dynamic scores. We assume an intermediate file
    # named dynamic_scores_intermediate.json or similar, or we read from the same location if T023
    # already wrote there but we need to merge.
    # However, T024's specific job is to "Generate ... with aligned task IDs".
    # T023 calculates the reward. T022 runs the rollout.
    # We assume T023 wrote to data/processed/dynamic_scores_raw.json or similar.
    # Let's assume the intermediate output from T023 is at:
    dynamic_input_path = PROJECT_ROOT / "data" / "processed" / "dynamic_scores_raw.json"
    
    output_path = PROJECT_ROOT / "data" / "processed" / "dynamic_scores.json"
    
    # Check prerequisites
    if not static_input_path.exists():
        logger.error(f"Prerequisite failed: {static_input_path} does not exist. Run T017 first.")
        return 1
    
    if not dynamic_input_path.exists():
        # Try alternative name if T023 used a different one
        alt_path = PROJECT_ROOT / "data" / "processed" / "dynamic_scores_intermediate.json"
        if alt_path.exists():
            dynamic_input_path = alt_path
        else:
            logger.error(f"Prerequisite failed: Dynamic scores not found at {dynamic_input_path} or {alt_path}. Run T022/T023 first.")
            return 1
    
    try:
        static_data = load_static_scores(static_input_path)
        dynamic_data = load_dynamic_scores(dynamic_input_path)
        
        merged_results = align_and_merge_scores(static_data, dynamic_data)
        
        save_merged_output(merged_results, output_path)
        
        logger.info("T024 completed successfully.")
        return 0
        
    except Exception as e:
        logger.error(f"Error during T024 execution: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())
