import json
import logging
import numpy as np
from pathlib import Path
from typing import Dict, Any, List, Optional
from config import load_config, get_path, get_hyperparameter, ensure_dirs

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_similarity_data(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Load the similarity matrix generated by the US1 pipeline.
    
    Args:
        config: The configuration dictionary.
        
    Returns:
        A dictionary containing the similarity matrix and metadata.
    """
    similarity_path = get_path(config, "processed_similarity_matrix")
    logger.info(f"Loading similarity data from {similarity_path}")
    
    if not Path(similarity_path).exists():
        raise FileNotFoundError(f"Similarity matrix file not found at {similarity_path}. "
                                "Ensure T014 has run successfully.")
    
    with open(similarity_path, 'r') as f:
        data = json.load(f)
        
    return data

def generate_null_bootstrap_distribution(similarities: Dict[str, float], 
                                         n_bootstrap: int, 
                                         seed: int) -> List[float]:
    """
    Generate a null distribution of similarity scores via bootstrap resampling.
    
    This simulates the variance expected under the null hypothesis that the 
    observed similarity is due to random chance in the edge spectrum alignment.
    
    Args:
        similarities: The dictionary of observed similarity scores.
        n_bootstrap: Number of bootstrap iterations.
        seed: Random seed for reproducibility.
        
    Returns:
        A list of bootstrapped similarity scores.
    """
    np.random.seed(seed)
    values = list(similarities.values())
    if not values:
        raise ValueError("No similarity values found to bootstrap.")
    
    null_dist = []
    for _ in range(n_bootstrap):
        # Resample with replacement from the observed similarities
        # This estimates the distribution of the mean similarity under the null
        sample = np.random.choice(values, size=len(values), replace=True)
        null_dist.append(float(np.mean(sample)))
        
    return null_dist

def bootstrap_confidence_interval(data: List[float], 
                                  confidence_level: float = 0.95) -> Dict[str, float]:
    """
    Compute the confidence interval using the bootstrap percentile method.
    
    Args:
        data: The bootstrap distribution data.
        confidence_level: The desired confidence level (e.g., 0.95).
        
    Returns:
        A dictionary with 'lower', 'upper', and 'mean' of the interval.
    """
    if not data:
        raise ValueError("Data list is empty.")
        
    sorted_data = sorted(data)
    n = len(sorted_data)
    
    lower_idx = int((1 - confidence_level) / 2 * n)
    upper_idx = int((1 + confidence_level) / 2 * n)
    
    lower = sorted_data[lower_idx]
    upper = sorted_data[upper_idx]
    mean_val = float(np.mean(data))
    
    return {
        "lower": lower,
        "upper": upper,
        "mean": mean_val
    }

def calculate_anisotropy_deviation(observed_similarity: float, 
                                   null_threshold: float) -> float:
    """
    Calculate the anisotropy deviation from the hypothesized null.
    
    Formula: deviation = |observed_similarity - null_threshold|
    
    Args:
        observed_similarity: The actual similarity score observed.
        null_threshold: The expected similarity under the null hypothesis.
        
    Returns:
        The absolute deviation.
    """
    return abs(observed_similarity - null_threshold)

def compute_anisotropy_report(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Compute the full anisotropy deviation report.
    
    This function:
    1. Loads the similarity matrix from T014.
    2. Generates a null bootstrap distribution.
    3. Calculates the deviation from the null threshold.
    4. Computes the confidence interval.
    5. Returns a structured report.
    
    Args:
        config: The configuration dictionary.
        
    Returns:
        A dictionary containing the anisotropy analysis results.
    """
    logger.info("Starting anisotropy deviation analysis.")
    
    # Load data
    similarity_data = load_similarity_data(config)
    similarities = similarity_data.get("similarity_scores", {})
    
    if not similarities:
        raise ValueError("No similarity scores found in the loaded data.")
    
    # Parameters
    n_bootstrap = get_hyperparameter(config, "n_bootstrap", 1000)
    seed = get_hyperparameter(config, "seed", 42)
    confidence_level = get_hyperparameter(config, "confidence_level", 0.95)
    
    # The null threshold is typically the mean of the bootstrap distribution
    # representing the expected similarity under random alignment.
    # Alternatively, it could be a theoretical value (e.g., 0.0 for orthogonality).
    # Here we derive it from the bootstrap of the observed data to estimate 
    # the center of the null distribution if we assume the observed data 
    # is a sample from the null (conservative approach) or use a theoretical 
    # baseline if defined in config. 
    # Per task description: "null_threshold represents the expected similarity 
    # under the null hypothesis". We will calculate the mean of the bootstrap 
    # distribution as our empirical null threshold estimate.
    
    null_dist = generate_null_bootstrap_distribution(similarities, n_bootstrap, seed)
    null_threshold = float(np.mean(null_dist))
    
    # Calculate deviations for each pair
    deviations = {}
    for pair, score in similarities.items():
        dev = calculate_anisotropy_deviation(score, null_threshold)
        deviations[pair] = dev
    
    # Overall deviation (mean of all pair deviations)
    overall_deviation = float(np.mean(list(deviations.values())))
    
    # Compute confidence interval for the null distribution
    ci = bootstrap_confidence_interval(null_dist, confidence_level)
    
    report = {
        "null_threshold": null_threshold,
        "overall_anisotropy_deviation": overall_deviation,
        "pairwise_deviations": deviations,
        "confidence_interval": ci,
        "bootstrap_iterations": n_bootstrap,
        "confidence_level": confidence_level,
        "seed": seed,
        "method": "bootstrap_percentile"
    }
    
    logger.info(f"Anisotropy analysis complete. Deviation: {overall_deviation:.4f}")
    return report

def main():
    """Main entry point for the statistical analyzer."""
    config = load_config()
    ensure_dirs(config)
    
    try:
        report = compute_anisotropy_report(config)
        
        output_path = get_path(config, "anisotropy_deviation")
        logger.info(f"Writing report to {output_path}")
        
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2)
            
        logger.info("Successfully wrote anisotropy deviation report.")
        
    except FileNotFoundError as e:
        logger.error(f"Missing input data: {e}")
        raise
    except Exception as e:
        logger.error(f"Error during anisotropy analysis: {e}")
        raise

if __name__ == "__main__":
    main()
