"""
Null Model Comparison Module (T031)

Implements the comparison of observed bias trends against the Null Model baseline
to ensure independence and quantify systematic bias beyond random chance.

Depends on:
  - T029a: data/results/bias_summary.csv (Observed Bias)
  - T014b: data/derived/null_model/ (Null Model Baseline Data)
"""

import os
import sys
import json
import logging
import csv
from pathlib import Path
from typing import Dict, List, Tuple, Any, Optional

import numpy as np
import scipy.stats as stats

# Project imports
from config import DATA_RESULTS_DIR, DATA_DERIVED_DIR, N_SIDE

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_null_model_baseline() -> Dict[str, Any]:
    """
    Load the Null Model baseline statistics from the pre-computed directory.

    Expected file: data/derived/null_model/baseline_stats.json
    Contains: mean_bias, std_bias, confidence_intervals, etc.
    """
    baseline_path = DATA_DERIVED_DIR / "null_model" / "baseline_stats.json"

    if not baseline_path.exists():
        raise FileNotFoundError(
            f"Null Model baseline not found at {baseline_path}. "
            "Ensure T014b (generate_null_model) has been executed successfully."
        )

    with open(baseline_path, 'r') as f:
        data = json.load(f)

    logger.info(f"Loaded Null Model baseline from {baseline_path}")
    return data


def load_bias_summary() -> List[Dict[str, Any]]:
    """
    Load the observed bias summary from the results CSV generated by T029a.

    Expected file: data/results/bias_summary.csv
    """
    summary_path = DATA_RESULTS_DIR / "bias_summary.csv"

    if not summary_path.exists():
        raise FileNotFoundError(
            f"Bias summary not found at {summary_path}. "
            "Ensure T029a (bias_analysis) has been executed successfully."
        )

    results = []
    with open(summary_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Parse numeric fields
            row['gap_fraction'] = float(row['gap_fraction'])
            row['bias_magnitude'] = float(row['bias_magnitude'])
            row['algorithm_idx'] = int(row['algorithm_idx'])
            results.append(row)

    logger.info(f"Loaded {len(results)} bias records from {summary_path}")
    return results


def compare_bias_distributions(
    observed_bias: List[float],
    null_mean: float,
    null_std: float,
    alpha: float = 0.05
) -> Dict[str, Any]:
    """
    Perform statistical comparison between observed bias and Null Model baseline.

    Uses a one-sample t-test to determine if the observed bias differs significantly
    from the Null Model expectation.

    Args:
        observed_bias: List of bias magnitude values from the main experiment.
        null_mean: Mean bias expected under the Null Model.
        null_std: Standard deviation of bias under the Null Model.
        alpha: Significance level for the test.

    Returns:
        Dictionary containing test statistics and conclusion.
    """
    if not observed_bias:
        return {
            "valid": False,
            "reason": "No observed bias data provided."
        }

    obs_array = np.array(observed_bias)
    n = len(obs_array)
    obs_mean = float(np.mean(obs_array))
    obs_std = float(np.std(obs_array, ddof=1)) if n > 1 else 0.0

    # One-sample t-test against the Null Model mean
    # H0: Observed mean == Null Model mean
    # H1: Observed mean != Null Model mean
    if obs_std == 0:
        # If no variance, check if mean equals null mean exactly
        t_stat = 0.0 if obs_mean == null_mean else float('inf')
        p_value = 0.0 if obs_mean == null_mean else 1.0
    else:
        t_stat = (obs_mean - null_mean) / (obs_std / np.sqrt(n))
        # Two-tailed p-value
        p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=n-1))

    significant = p_value < alpha
    effect_size = (obs_mean - null_mean) / null_std if null_std > 0 else 0.0

    return {
        "valid": True,
        "n_observations": n,
        "observed_mean": obs_mean,
        "observed_std": obs_std,
        "null_mean": null_mean,
        "null_std": null_std,
        "t_statistic": float(t_stat),
        "p_value": float(p_value),
        "is_significant": significant,
        "alpha": alpha,
        "effect_size": float(effect_size),
        "conclusion": (
            f"Significant bias detected (p={p_value:.4f})" if significant
            else "No significant bias detected (p={:.4f})".format(p_value)
        )
    }


def run_null_model_comparison() -> Dict[str, Any]:
    """
    Main execution function for T031.

    1. Loads Null Model baseline.
    2. Loads Observed Bias Summary.
    3. Groups observed bias by gap fraction and algorithm to compare against Null.
    4. Computes statistical significance.
    5. Saves detailed comparison results to data/results/null_model_comparison.json.
    """
    logger.info("Starting Null Model Comparison (T031)...")

    # 1. Load Baselines
    try:
        null_baseline = load_null_model_baseline()
    except FileNotFoundError as e:
        logger.error(str(e))
        return {"status": "failed", "error": str(e)}

    try:
        bias_summary = load_bias_summary()
    except FileNotFoundError as e:
        logger.error(str(e))
        return {"status": "failed", "error": str(e)}

    # 2. Group Observed Data
    # We compare the aggregate observed bias against the null distribution.
    # If the task requires per-gap-fraction comparison, we can do that too.
    observed_magnitudes = [row['bias_magnitude'] for row in bias_summary]

    # Extract Null Model parameters
    null_mean = null_baseline.get('mean_bias', 0.0)
    null_std = null_baseline.get('std_bias', 1.0)

    # 3. Perform Comparison
    comparison_results = compare_bias_distributions(
        observed_magnitudes,
        null_mean,
        null_std
    )

    # 4. Detailed Breakdown (Optional but useful)
    # Group by gap fraction to see if bias scales differently than null
    breakdown = []
    gap_fractions = sorted(list(set([row['gap_fraction'] for row in bias_summary])))
    
    for gf in gap_fractions:
        gf_data = [row['bias_magnitude'] for row in bias_summary if row['gap_fraction'] == gf]
        if gf_data:
            gf_mean = float(np.mean(gf_data))
            gf_std = float(np.std(gf_data, ddof=1)) if len(gf_data) > 1 else 0.0
            
            # Compare this specific fraction to null
            # Note: If null model is global, we compare global mean. 
            # If null model has fraction-specific stats, we would use those.
            # Assuming global null baseline for now as per T014b description.
            t_stat = (gf_mean - null_mean) / (gf_std / np.sqrt(len(gf_data))) if gf_std > 0 else 0.0
            p_val = 2 * (1 - stats.t.cdf(abs(t_stat), df=len(gf_data)-1)) if len(gf_data) > 1 else 1.0
            
            breakdown.append({
                "gap_fraction": gf,
                "n_samples": len(gf_data),
                "observed_mean": gf_mean,
                "observed_std": gf_std,
                "t_statistic": float(t_stat),
                "p_value": float(p_val),
                "is_significant": p_val < 0.05
            })

    comparison_results["breakdown_by_gap_fraction"] = breakdown

    # 5. Save Results
    output_path = DATA_RESULTS_DIR / "null_model_comparison.json"
    with open(output_path, 'w') as f:
        json.dump(comparison_results, f, indent=2)

    logger.info(f"Null Model Comparison saved to {output_path}")
    logger.info(f"Conclusion: {comparison_results['conclusion']}")

    return comparison_results


def main():
    """Entry point for script execution."""
    result = run_null_model_comparison()
    if result.get('status') == 'failed':
        sys.exit(1)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()