import os
import json
from typing import Any, Dict, Optional

# Configuration loaded from simulation parameters
# These are populated by T000b-Params and T010a
# Values are loaded dynamically from code/simulation_parameters.json

# Default placeholders - will be overwritten by load_simulation_params
effect_size_high_low: float = 0.5
effect_size_interaction: float = 0.3
sample_size: int = 100
random_seed: int = 42

# Decision record path
DECISION_RECORD_PATH: str = "data/processed/decision_record.json"

# Binning flag - set by T012b if binning strategy is applied
binning_flag: bool = False

# Regression family configuration - set by T014b / T020c
# 'binomial' for binary outcomes, 'gaussian' for continuous
regression_family: str = "gaussian"

# Cache for loaded parameters to avoid repeated file I/O
_params_cache: Optional[Dict[str, Any]] = None

def load_decision_record(path: Optional[str] = None) -> Dict[str, Any]:
    """Load the decision record JSON file."""
    if path is None:
        path = DECISION_RECORD_PATH
    if not os.path.exists(path):
        return {}
    with open(path, 'r') as f:
        return json.load(f)

def save_decision_record(data: Dict[str, Any], path: Optional[str] = None) -> None:
    """Save the decision record JSON file."""
    if path is None:
        path = DECISION_RECORD_PATH
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)

def load_simulation_params(path: str = "code/simulation_parameters.json") -> Dict[str, Any]:
    """
    Load simulation parameters from JSON file.
    
    This function reads the verified effect sizes and sample size N
    generated by T000a-Generate and T000b-Params.
    
    Args:
        path: Path to the simulation parameters JSON file.
        
    Returns:
        Dictionary containing simulation parameters.
        
    Raises:
        FileNotFoundError: If the parameters file does not exist.
        json.JSONDecodeError: If the file contains invalid JSON.
    """
    global _params_cache
    if not os.path.exists(path):
        raise FileNotFoundError(f"Simulation parameters file not found: {path}")
    
    with open(path, 'r') as f:
        params = json.load(f)
    
    _params_cache = params
    return params

def get_effect_size_high_low() -> float:
    """
    Retrieve the effect size for High vs Low status.
    
    This value is loaded from code/simulation_parameters.json
    and represents the verified Cohen's d from meta-analysis.
    
    Returns:
        The effect size value (float).
    """
    global effect_size_high_low
    if _params_cache is None:
        try:
            load_simulation_params()
        except FileNotFoundError:
            # Fallback to default if file not found (should not happen in normal flow)
            return effect_size_high_low
    
    effect_size_high_low = _params_cache.get('effect_size_high_low', 0.5)
    return effect_size_high_low

def get_effect_size_interaction() -> float:
    """
    Retrieve the interaction effect size.
    
    This value is loaded from code/simulation_parameters.json
    and represents the verified Cohen's d for the interaction term.
    
    Returns:
        The interaction effect size value (float).
    """
    global effect_size_interaction
    if _params_cache is None:
        try:
            load_simulation_params()
        except FileNotFoundError:
            return effect_size_interaction
    
    effect_size_interaction = _params_cache.get('effect_size_interaction', 0.3)
    return effect_size_interaction

def get_sample_size() -> int:
    """
    Retrieve the calculated sample size N.
    
    This value is loaded from code/simulation_parameters.json
    and represents the minimum N required for 80% power.
    
    Returns:
        The sample size (int).
    """
    global sample_size
    if _params_cache is None:
        try:
            load_simulation_params()
        except FileNotFoundError:
            return sample_size
    
    sample_size = _params_cache.get('sample_size', 100)
    return sample_size

def get_random_seed() -> int:
    """
    Retrieve the random seed for reproducibility.
    
    This value is loaded from code/simulation_parameters.json
    and ensures deterministic data generation.
    
    Returns:
        The random seed (int).
    """
    global random_seed
    if _params_cache is None:
        try:
            load_simulation_params()
        except FileNotFoundError:
            return random_seed
    
    random_seed = _params_cache.get('random_seed', 42)
    return random_seed

def set_regression_family(family_type: str) -> None:
    """
    Configure the regression family for the model based on outcome type detection.
    
    Args:
        family_type: Either 'binomial' (for binary outcomes) or 'gaussian' (for continuous).
    """
    global regression_family
    valid_families = {'binomial', 'gaussian'}
    if family_type not in valid_families:
        raise ValueError(f"Invalid regression family '{family_type}'. Must be one of {valid_families}")
    regression_family = family_type

def get_regression_family() -> str:
    """Retrieve the currently configured regression family."""
    return regression_family

def load_family_config(config_path: str = "data/processed/analysis_config.json") -> None:
    """
    Load the family type from the analysis config file generated by T014b/T020a.
    This function consumes the 'family_type' flag and updates the global configuration.
    
    Args:
        config_path: Path to the analysis config JSON file.
    """
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Analysis config file not found: {config_path}")
    
    with open(config_path, 'r') as f:
        config = json.load(f)
    
    if 'family_type' not in config:
        raise KeyError("Analysis config missing 'family_type' key.")
    
    set_regression_family(config['family_type'])

def initialize_config() -> None:
    """
    Initialize all configuration values from the simulation parameters file.
    
    This function should be called at the start of the pipeline to ensure
    all global constants are populated with verified values.
    """
    try:
        load_simulation_params()
        # Force update of global variables
        _ = get_effect_size_high_low()
        _ = get_effect_size_interaction()
        _ = get_sample_size()
        _ = get_random_seed()
    except FileNotFoundError as e:
        raise RuntimeError(f"Failed to initialize config: {e}")