import os
import sys
import logging
import pandas as pd
from pathlib import Path

from src.utils import get_logger, ensure_directories, write_csv
from src.data.config import get_processed_data_path, get_data_root

logger = get_logger(__name__)

def load_sensitivity_data(input_path: str):
    """
    Load the sensitivity analysis results from the CSV generated by T027.
    Expected columns: ['dimension', 'threshold', 'status', 'flip_rate']
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Sensitivity analysis file not found: {input_path}")
    
    logger.info(f"Loading sensitivity data from {input_path}")
    df = pd.read_csv(input_path)
    
    required_cols = ['dimension', 'threshold', 'status', 'flip_rate']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Sensitivity data missing required columns: {missing_cols}")
    
    return df

def generate_full_matrix(sensitivity_df: pd.DataFrame, output_path: str):
    """
    Generate the full sensitivity matrix table showing classification outcome
    for each dimension at all tested thresholds.
    
    The output CSV will have dimensions as rows and thresholds as columns,
    with the 'status' (feature-sufficient / VLM-required) as the cell value.
    """
    if sensitivity_df.empty:
        logger.warning("Input sensitivity dataframe is empty. Creating empty output.")
        ensure_directories(output_path)
        # Create an empty CSV with the expected schema
        empty_df = pd.DataFrame(columns=['dimension'] + sorted(sensitivity_df['threshold'].unique().tolist()))
        write_csv(empty_df, output_path)
        return

    # Pivot the data to create the matrix
    # Rows: dimension, Columns: threshold, Values: status
    matrix_df = sensitivity_df.pivot(index='dimension', columns='threshold', values='status')
    
    # Ensure columns are sorted numerically
    matrix_df = matrix_df.sort_index(axis=1)
    
    # Reset index to make 'dimension' a column
    matrix_df = matrix_df.reset_index()
    
    logger.info(f"Generated sensitivity matrix with shape {matrix_df.shape}")
    logger.info(f"Dimensions: {list(matrix_df['dimension'])}")
    logger.info(f"Thresholds: {list(matrix_df.columns[1:])}")
    
    ensure_directories(output_path)
    write_csv(matrix_df, output_path)
    logger.info(f"Full sensitivity matrix written to {output_path}")

def main():
    """
    Main entry point for T028: Generate full sensitivity matrix table.
    
    Reads: data/sensitivity_analysis.csv (from T027)
    Writes: data/sensitivity_matrix_full.csv
    """
    logger.info("Starting T028: Generate full sensitivity matrix table")
    
    # Define paths
    data_root = get_data_root()
    input_path = os.path.join(data_root, 'sensitivity_analysis.csv')
    output_path = os.path.join(data_root, 'sensitivity_matrix_full.csv')
    
    try:
        # Load data from T027
        sensitivity_df = load_sensitivity_data(input_path)
        
        # Generate the full matrix
        generate_full_matrix(sensitivity_df, output_path)
        
        logger.info("T028 completed successfully")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"Required input file missing: {e}")
        logger.error("Ensure T027 has completed and generated data/sensitivity_analysis.csv")
        return 1
    except Exception as e:
        logger.error(f"Error generating sensitivity matrix: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())