import os
import json
import math
import random
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple

import numpy as np
import pandas as pd

# Import from sibling modules as per API surface
# Note: The API surface lists `load_processed_data` in `code/analysis/bootstrapping.py`
# but also in `code/analysis/trends.py` and `code/analysis/decomposition.py`.
# We will define it here to satisfy the import `from analysis.bootstrapping import ...`
# and ensure it reads the processed data generated by T013/T014.

PROJECT_ROOT = Path(__file__).parent.parent.parent
PROCESSED_DATA_PATH = PROJECT_ROOT / "data" / "processed" / "monthly_tag_frequencies.csv"
TREND_RESULTS_PATH = PROJECT_ROOT / "data" / "processed" / "trend_analysis_results.json"
OUTPUT_PATH = PROJECT_ROOT / "data" / "processed" / "confidence_interval.json"

def load_processed_data() -> pd.DataFrame:
    """
    Load the preprocessed monthly tag frequencies.
    Expects a CSV with columns: tag, date (YYYY-MM), count.
    """
    if not PROCESSED_DATA_PATH.exists():
        raise FileNotFoundError(
            f"Processed data file not found at {PROCESSED_DATA_PATH}. "
            "Please run data/preprocess.py (T013) first."
        )
    df = pd.read_csv(PROCESSED_DATA_PATH)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(['tag', 'date'])
    return df

def load_trend_results() -> Dict[str, Any]:
    """
    Load the trend analysis results (slopes, p-values, classifications) from T014.
    """
    if not TREND_RESULTS_PATH.exists():
        raise FileNotFoundError(
            f"Trend results file not found at {TREND_RESULTS_PATH}. "
            "Please run analysis/trends.py (T014) first."
        )
    with open(TREND_RESULTS_PATH, 'r') as f:
        return json.load(f)

def theil_sen_slope(x: np.ndarray, y: np.ndarray) -> float:
    """
    Calculate Theil-Sen estimator slope manually to ensure consistency
    with the implementation in trends.py if needed, or use a robust method.
    Median of all pairwise slopes.
    """
    n = len(x)
    if n < 2:
        return 0.0
    
    slopes = []
    for i in range(n):
        for j in range(i + 1, n):
            if x[j] != x[i]:
                slope = (y[j] - y[i]) / (x[j] - x[i])
                slopes.append(slope)
    
    if not slopes:
        return 0.0
    return float(np.median(slopes))

def bootstrap_theil_sen(
    x: np.ndarray, 
    y: np.ndarray, 
    n_bootstrap: int = 1000, 
    random_state: Optional[int] = None
) -> Tuple[float, float, float]:
    """
    Perform bootstrapping to calculate 95% confidence intervals for Theil-Sen slope.
    
    Args:
        x: Independent variable (e.g., time indices)
        y: Dependent variable (e.g., tag counts)
        n_bootstrap: Number of bootstrap iterations
        random_state: Random seed for reproducibility
    
    Returns:
        Tuple of (original_slope, lower_ci, upper_ci)
    """
    if random_state is not None:
        np.random.seed(random_state)
    
    if len(x) != len(y) or len(x) < 2:
        raise ValueError("x and y must have same length >= 2")
    
    # Calculate original slope
    original_slope = theil_sen_slope(x, y)
    
    # Bootstrap
    bootstrap_slopes = []
    n = len(x)
    
    for _ in range(n_bootstrap):
        # Resample with replacement (indices)
        indices = np.random.choice(n, size=n, replace=True)
        x_boot = x[indices]
        y_boot = y[indices]
        
        # Sort by x to ensure correct pairing for slope calculation
        sort_idx = np.argsort(x_boot)
        x_boot = x_boot[sort_idx]
        y_boot = y_boot[sort_idx]
        
        slope = theil_sen_slope(x_boot, y_boot)
        bootstrap_slopes.append(slope)
    
    bootstrap_slopes = np.array(bootstrap_slopes)
    lower_ci = float(np.percentile(bootstrap_slopes, 2.5))
    upper_ci = float(np.percentile(bootstrap_slopes, 97.5))
    
    return original_slope, lower_ci, upper_ci

def save_confidence_intervals(results: Dict[str, Any], output_path: Path) -> None:
    """
    Save the confidence interval results to a JSON file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)

def run_bootstrapping_analysis(
    n_bootstrap: int = 1000, 
    random_state: int = 42
) -> Dict[str, Any]:
    """
    Main function to run the bootstrapping analysis on all tags found in trend results.
    
    1. Loads processed data.
    2. Loads trend results to identify which tags to analyze.
    3. For each tag, calculates Theil-Sen slope CI via bootstrapping.
    4. Saves results to data/processed/confidence_interval.json.
    """
    # Load dependencies
    df_processed = load_processed_data()
    trend_results = load_trend_results()
    
    # Structure for output
    # Assuming trend_results is a list of dicts or a dict of dicts.
    # Based on T014, it likely contains tag-level stats.
    # We need to handle the structure robustly.
    
    if isinstance(trend_results, list):
        tags_to_analyze = [item.get('tag') for item in trend_results if 'tag' in item]
    elif isinstance(trend_results, dict):
        # If it's a dict of tags -> stats
        tags_to_analyze = list(trend_results.keys())
    else:
        raise ValueError("Unexpected format for trend_results")
    
    if not tags_to_analyze:
        raise ValueError("No tags found in trend results to analyze.")
    
    confidence_interval_results = []
    
    print(f"Starting bootstrapping analysis for {len(tags_to_analyze)} tags...")
    
    for tag in tags_to_analyze:
        try:
            # Filter data for this tag
            tag_data = df_processed[df_processed['tag'] == tag].sort_values('date')
            
            if len(tag_data) < 2:
                confidence_interval_results.append({
                    "tag": tag,
                    "status": "skipped",
                    "reason": "Insufficient data points for bootstrapping"
                })
                continue
            
            # Prepare x (time) and y (count)
            # Convert dates to ordinal or float for slope calculation
            x = tag_data['date'].astype(np.int64) // 10**9  # Unix timestamp
            y = tag_data['count'].values
            
            # Run bootstrap
            slope, lower_ci, upper_ci = bootstrap_theil_sen(
                x, y, n_bootstrap=n_bootstrap, random_state=random_state
            )
            
            confidence_interval_results.append({
                "tag": tag,
                "theil_sen_slope": slope,
                "ci_95_lower": lower_ci,
                "ci_95_upper": upper_ci,
                "n_iterations": n_bootstrap,
                "status": "success"
            })
            
        except Exception as e:
            confidence_interval_results.append({
                "tag": tag,
                "status": "error",
                "reason": str(e)
            })
    
    output_data = {
        "metadata": {
            "n_bootstrap": n_bootstrap,
            "random_state": random_state,
            "tags_processed": len([r for r in confidence_interval_results if r.get('status') == 'success']),
            "timestamp": str(pd.Timestamp.now())
        },
        "results": confidence_interval_results
    }
    
    save_confidence_intervals(output_data, OUTPUT_PATH)
    print(f"Confidence intervals saved to {OUTPUT_PATH}")
    
    return output_data

def main():
    """
    Entry point for the bootstrapping analysis script.
    """
    try:
        run_bootstrapping_analysis(n_bootstrap=1000, random_state=42)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        exit(1)
    except Exception as e:
        print(f"Unexpected error during analysis: {e}")
        exit(1)

if __name__ == "__main__":
    main()