import json
import logging
import os
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Hardcoded paths relative to project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
STAT_SUMMARY_PATH = PROJECT_ROOT / "artifacts" / "reports" / "stat_summary.json"
FAILURE_LOG_PATH = PROJECT_ROOT / "artifacts" / "reports" / "failure_log.json"
CHECKLIST_OUTPUT_PATH = PROJECT_ROOT / "artifacts" / "reports" / "reproducibility_checklist.md"

# Guideline Templates: Maps failure categories to actionable recommendations
# These templates enforce the "Actionable" requirement (US-3 Scenario 1)
ACTIONABLE_GUIDELINES = {
    "missing_seed": {
        "title": "Report Random Seed Explicitly",
        "action": "Set and document the random seed (e.g., `random.seed(42)`, `torch.manual_seed(42)`) for all stochastic processes.",
        "reference": "Guideline: Reproducibility in ML (Nature Methods, 2021)",
        "failure_context": "Missing or inconsistent random seeds"
    },
    "version_mismatch": {
        "title": "Version-Pin All Dependencies",
        "action": "Use a `requirements.txt` or `environment.yml` with exact version pins (e.g., `torch==2.2.0`) and include the Python version.",
        "reference": "Guideline: Software Sustainability Institute",
        "failure_context": "Library version mismatches or environment drift"
    },
    "reaction_conditions": {
        "title": "Specify Reaction Conditions Precisely",
        "action": "Record and publish exact reaction parameters: temperature, solvent, catalyst loading, and stoichiometry in machine-readable format (e.g., CSV/JSON).",
        "reference": "Guideline: IUPAC Recommendations for Chemical Data",
        "failure_context": "Missing or ambiguous reaction condition details"
    },
    "data_availability": {
        "title": "Provide Raw and Processed Data Access",
        "action": "Host datasets in a persistent repository (e.g., Zenodo, Figshare) with a DOI, and include a manifest linking raw inputs to processed features.",
        "reference": "Guideline: FAIR Data Principles",
        "failure_context": "Data unavailable or inaccessible"
    },
    "model_architecture": {
        "title": "Document Model Architecture and Parameters",
        "action": "Publish the full model architecture definition (layers, activation functions) and hyperparameters (learning rate, batch size) used for training.",
        "reference": "Guideline: ML Reproducibility Checklist (ICLR)",
        "failure_context": "Model substitution or architecture ambiguity"
    },
    "metric_reporting": {
        "title": "Report Statistical Uncertainty",
        "action": "Report metrics with standard deviations or confidence intervals derived from multiple independent experimental replicates or cross-validation folds.",
        "reference": "Guideline: Statistical Best Practices in ML",
        "failure_context": "Single-point metric reporting without variance"
    }
}

def load_json_file(file_path: Path) -> Optional[Dict[str, Any]]:
    """Load a JSON file and return its contents."""
    if not file_path.exists():
        logger.warning(f"File not found: {file_path}. Returning empty dict.")
        return {}
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to decode JSON from {file_path}: {e}")
        return {}

def load_failure_log() -> List[Dict[str, Any]]:
    """Load the failure log generated by failure_logger.py."""
    return load_json_file(FAILURE_LOG_PATH)

def load_stat_summary() -> Dict[str, Any]:
    """Load the statistical summary generated by stats.py."""
    return load_json_file(STAT_SUMMARY_PATH)

def analyze_statistical_findings(stat_summary: Dict[str, Any]) -> List[str]:
    """
    Analyze statistical summary to identify specific failure modes.
    Returns a list of failure mode keys found.
    """
    failure_modes = []
    if not stat_summary:
        return failure_modes

    # Check for high heterogeneity (I2) indicating reproducibility issues
    if "heterogeneity" in stat_summary:
        i2 = stat_summary.get("heterogeneity", {}).get("I2", 0)
        if i2 > 50: # Threshold for substantial heterogeneity
            failure_modes.append("version_mismatch") # Proxy for environmental drift
            failure_modes.append("reaction_conditions")

    # Check for significant t-test results (p < 0.05) indicating deviation
    if "t_tests" in stat_summary:
        for test_name, result in stat_summary["t_tests"].items():
            if result.get("p_value", 1.0) < 0.05:
                # Significant deviation detected
                failure_modes.append("metric_reporting")

    return list(set(failure_modes))

def map_failures_to_guidelines(failures: List[Dict[str, Any]], stat_findings: List[str]) -> List[Dict[str, str]]:
    """
    Map identified failures and statistical findings to actionable guideline items.
    Ensures every item is actionable per US-3 Scenario 1.
    """
    guideline_items = []
    seen_keys = set()

    # Process qualitative failure log
    for failure in failures:
        category = failure.get("category", "unknown")
        # Normalize category keys to match ACTIONABLE_GUIDELINES
        key_map = {
            "missing_seed": "missing_seed",
            "seed_missing": "missing_seed",
            "version": "version_mismatch",
            "version_mismatch": "version_mismatch",
            "missing_conditions": "reaction_conditions",
            "data_unavailable": "data_availability",
            "model_unavailable": "model_architecture"
        }
        mapped_key = key_map.get(category.lower(), category.lower())

        if mapped_key in ACTIONABLE_GUIDELINES and mapped_key not in seen_keys:
            guideline = ACTIONABLE_GUIDELINES[mapped_key]
            guideline_items.append({
                "title": guideline["title"],
                "action": guideline["action"],
                "reference": guideline["reference"],
                "context": failure.get("message", f"Detected {category} issue")
            })
            seen_keys.add(mapped_key)

    # Process statistical findings
    for finding in stat_findings:
        if finding in ACTIONABLE_GUIDELINES and finding not in seen_keys:
            guideline = ACTIONABLE_GUIDELINES[finding]
            guideline_items.append({
                "title": guideline["title"],
                "action": guideline["action"],
                "reference": guideline["reference"],
                "context": f"Statistical analysis indicated {finding} (e.g., high heterogeneity or significant deviation)."
            })
            seen_keys.add(finding)

    return guideline_items

def generate_checklist(items: List[Dict[str, str]]) -> str:
    """
    Generate a Markdown checklist string from the list of guideline items.
    Format:
    # Reproducibility Checklist
    1. **Title**: Actionable text. (Ref: Citation)
       - Context: ...
    """
    lines = [
        "# Reproducibility Checklist for Machine-Learned Reaction Yield Models",
        "",
        "This checklist synthesizes best-practice recommendations derived from identified failure modes and statistical analysis.",
        ""
    ]

    for idx, item in enumerate(items, 1):
        lines.append(f"{idx}. **{item['title']}**: {item['action']}")
        lines.append(f"   - *Reference*: {item['reference']}")
        lines.append(f"   - *Context*: {item['context']}")
        lines.append("")

    return "\n".join(lines)

def main():
    """
    Main entry point for generating the reproducibility checklist.
    Loads stat_summary and failure_log, maps them to actionable guidelines,
    and writes the result to artifacts/reports/reproducibility_checklist.md.
    """
    logger.info("Starting checklist generation...")

    # Load inputs
    stat_summary = load_stat_summary()
    failure_log = load_failure_log()

    # Analyze statistical findings
    stat_findings = analyze_statistical_findings(stat_summary)
    logger.info(f"Identified statistical findings: {stat_findings}")

    # Map failures to guidelines
    guideline_items = map_failures_to_guidelines(failure_log, stat_findings)

    if not guideline_items:
        logger.warning("No failure modes or statistical findings detected. Generating a generic checklist.")
        # Fallback to generic actionable items if no specific failures found
        guideline_items = [
            {
                "title": "Report Random Seed Explicitly",
                "action": "Set and document the random seed (e.g., `random.seed(42)`) for all stochastic processes.",
                "reference": "Guideline: Reproducibility in ML",
                "context": "General best practice for reproducibility."
            },
            {
                "title": "Version-Pin All Dependencies",
                "action": "Use a `requirements.txt` with exact version pins.",
                "reference": "Guideline: Software Sustainability Institute",
                "context": "General best practice for environment stability."
            },
            {
                "title": "Specify Reaction Conditions Precisely",
                "action": "Record and publish exact reaction parameters.",
                "reference": "Guideline: IUPAC Recommendations",
                "context": "General best practice for chemical data."
            },
            {
                "title": "Provide Raw and Processed Data Access",
                "action": "Host datasets in a persistent repository with a DOI.",
                "reference": "Guideline: FAIR Data Principles",
                "context": "General best practice for data sharing."
            },
            {
                "title": "Document Model Architecture and Parameters",
                "action": "Publish the full model architecture definition and hyperparameters.",
                "reference": "Guideline: ML Reproducibility Checklist",
                "context": "General best practice for model transparency."
            }
        ]

    # Generate content
    checklist_content = generate_checklist(guideline_items)

    # Ensure output directory exists
    CHECKLIST_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    with open(CHECKLIST_OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(checklist_content)

    logger.info(f"Checklist successfully written to {CHECKLIST_OUTPUT_PATH}")
    return checklist_content

if __name__ == "__main__":
    main()