import json
import logging
import os
import platform
import subprocess
import sys
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional

# Import from sibling modules based on provided API surface
from metrics import calculate_deviation_index, calculate_all_metrics
from manifest_loader import load_manifest, validate_manifest
from failure_logger import load_existing_failure_log, record_failure, compile_failure_summary, write_failure_report, FailureReason
from model_runner import run_reproducibility_assessment

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('artifacts/logs/pipeline.log')
    ]
)
logger = logging.getLogger(__name__)

def get_docker_hash() -> Optional[str]:
    """Attempt to retrieve the Docker container hash if running in Docker."""
    try:
        if os.path.exists('/.dockerenv'):
            result = subprocess.run(
                ['cat', '/etc/hostname'],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                return result.stdout.strip()
    except Exception as e:
        logger.warning(f"Could not retrieve Docker hash: {e}")
    return None

def log_environment(output_path: str = "artifacts/logs/env.log") -> None:
    """Log environment details (Python, libs, OS, Docker hash) to a file."""
    env_info = {
        "timestamp": datetime.now().isoformat(),
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "os": platform.system(),
        "os_version": platform.version(),
        "machine": platform.machine(),
        "docker_hash": get_docker_hash(),
        "libraries": {
            "numpy": __import__('numpy').__version__,
            "scipy": __import__('scipy').__version__,
            "pandas": __import__('pandas').__version__,
            "sklearn": __import__('sklearn').__version__,
            "rdkit": __import__('rdkit').__version__,
        }
    }

    # Ensure log directory exists
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        json.dump(env_info, f, indent=2)
    
    logger.info(f"Environment logged to {output_path}")

def aggregate_results(
    results_dir: str = "artifacts/reports",
    manifest_path: str = "data/manifest.yaml",
    output_path: str = "artifacts/reports/repro_results.json"
) -> Dict[str, Any]:
    """
    Aggregate individual ReproResult objects into a final report.
    
    This function:
    1. Loads the manifest to identify target papers.
    2. Runs the reproducibility assessment for each paper (or loads existing results if T013 is run separately).
       Since T013 is marked completed, we assume individual results might exist or we run the assessment here.
       To satisfy T018's requirement to "aggregate", we will run the assessment for each entry in the manifest
       and compile the final JSON with deviations and score S.
    3. Calculates the Deviation Index (S) for each paper comparing against reported metrics.
    4. Writes the aggregated results to `output_path`.
    5. Logs any failures using the failure logger.
    
    FR-005: Aggregation of results.
    FR-009: Calculation of Deviation Index (S).
    """
    
    # Ensure output directories exist
    Path(results_dir).mkdir(parents=True, exist_ok=True)
    Path("artifacts/logs").mkdir(parents=True, exist_ok=True)

    logger.info(f"Starting aggregation from manifest: {manifest_path}")

    # Load and validate manifest
    try:
        manifest = load_manifest(manifest_path)
        if not validate_manifest(manifest):
            record_failure(FailureReason.MANIFEST_INVALID, "Manifest validation failed.")
            raise ValueError("Invalid manifest")
    except Exception as e:
        logger.error(f"Failed to load manifest: {e}")
        raise

    # If individual results are not pre-generated by T013 (since we are implementing the pipeline end-to-end here),
    # we run the assessment for each paper.
    # Note: T013 is marked completed, but in a fresh run, we need to ensure data is processed.
    # We will call run_reproducibility_assessment which handles the full pipeline for a paper.
    
    aggregated_results = []
    failure_summary = []

    for paper_entry in manifest.get('papers', []):
        paper_id = paper_entry.get('id', 'unknown')
        logger.info(f"Processing paper: {paper_id}")

        try:
            # Run the full reproducibility assessment for this paper
            # This function (from model_runner) returns a ReproResult dict
            result = run_reproducibility_assessment(paper_entry)
            
            if result:
                # Calculate Deviation Index (S)
                # result should contain: reported_metrics, reproduced_metrics
                reported = result.get('reported_metrics', {})
                reproduced = result.get('reproduced_metrics', {})
                
                if reported and reproduced:
                    s_score = calculate_deviation_index(
                        reported_mae=reported.get('mae', 0),
                        reported_r2=reported.get('r2', 0),
                        reported_rho=reported.get('rho', 0),
                        reproduced_mae=reproduced.get('mae', 0),
                        reproduced_r2=reproduced.get('r2', 0),
                        reproduced_rho=reproduced.get('rho', 0)
                    )
                    result['deviation_index_s'] = s_score
                    result['status'] = 'completed'
                else:
                    result['status'] = 'incomplete_metrics'
                    record_failure(FailureReason.DATA_UNAVAILABLE, f"Missing metrics for {paper_id}")

                aggregated_results.append(result)
            else:
                record_failure(FailureReason.RUNTIME_ERROR, f"Assessment returned None for {paper_id}")

        except Exception as e:
            logger.error(f"Error processing paper {paper_id}: {e}")
            record_failure(FailureReason.RUNTIME_ERROR, f"Error processing {paper_id}: {str(e)}")
            aggregated_results.append({
                "paper_id": paper_id,
                "status": "failed",
                "error": str(e)
            })

    # Write aggregated results
    output_data = {
        "generated_at": datetime.now().isoformat(),
        "total_papers": len(manifest.get('papers', [])),
        "successful": len([r for r in aggregated_results if r.get('status') == 'completed']),
        "results": aggregated_results
    }

    with open(output_path, 'w') as f:
        json.dump(output_data, f, indent=2)

    logger.info(f"Aggregated results written to {output_path}")

    # Compile and write failure report if any failures occurred
    if failure_summary or any(r.get('status') != 'completed' for r in aggregated_results):
        write_failure_report("artifacts/logs/failure_report.json")

    return output_data

def main():
    """Main entry point for the pipeline."""
    logger.info("Starting Reproducibility Assessment Pipeline")
    
    # Log environment
    log_environment()
    
    # Run aggregation
    try:
        results = aggregate_results()
        logger.info(f"Pipeline completed. Success rate: {results['successful']}/{results['total_papers']}")
    except Exception as e:
        logger.critical(f"Pipeline failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()