"""
Error Codes Enum for the Alloy Phase Diagram Pipeline.
"""
from enum import Enum

class ErrorCode(Enum):
    DATA_SOURCE_MISSING = "DATA_SOURCE_MISSING"
    INVALID_DATA_SCHEMA = "INVALID_DATA_SCHEMA"
    MISSING_TEMP_COORDS = "MISSING_TEMP_COORDS"
    LOW_DATA_DENSITY = "LOW_DATA_DENSITY"
    API_RATE_LIMIT_EXCEEDED = "API_RATE_LIMIT_EXCEEDED"
    INSUFFICIENT_POWER = "INSUFFICIENT_POWER"
    INVALID_SCOPE = "INVALID_SCOPE"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
    NO_SIGNIFICANT_IMPROVEMENT = "NO_SIGNIFICANT_IMPROVEMENT"
    LOW_DATA_FIDELITY = "LOW_DATA_FIDELITY"
    DATA_SCHEMA_MISMATCH = "DATA_SCHEMA_MISMATCH"
    TEMPERATURE_RANGE_VIOLATION = "TEMPERATURE_RANGE_VIOLATION"
    COMPOSITION_SUM_ERROR = "COMPOSITION_SUM_ERROR"
    POTENTIAL_MEMORY_LEAK = "POTENTIAL_MEMORY_LEAK"
    LOW_TEST_SET_SIZE = "LOW_TEST_SET_SIZE"
    MISSING_GROUND_TRUTH = "MISSING_GROUND_TRUTH"
    DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION"
    LOW_RESOLUTION_PLOT = "LOW_RESOLUTION_PLOT"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    def __str__(self):
        return self.value
