from enum import Enum

class ErrorCode(Enum):
    DATA_SOURCE_MISSING = "DATA_SOURCE_MISSING"
    INVALID_DATA_SCHEMA = "INVALID_DATA_SCHEMA"
    API_RATE_LIMIT_EXCEEDED = "API_RATE_LIMIT_EXCEEDED"
    LOW_DATA_FIDELITY = "LOW_DATA_FIDELITY"
    MISSING_TEMP_COORDS = "MISSING_TEMP_COORDS"
    LOW_DATA_DENSITY = "LOW_DATA_DENSITY"
    INSUFFICIENT_POWER = "INSUFFICIENT_POWER"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
