import os
import json
import hashlib
import logging
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional

# Add parent directory to path to allow imports from sibling modules
sys.path.insert(0, str(Path(__file__).parent))

from utils.logger import get_logger
from utils.checksum import compute_file_checksum, save_checksums
from utils.schema_validator import validate_artifact
import config

logger = get_logger(__name__)

def load_or_fetch_real_data() -> List[Dict[str, Any]]:
    """
    Loads real polymer blend data from the verified source.
    This implementation assumes the data has been pre-fetched by T014/T019
    into `data/raw/` or fetched from a verified URL if not present.
    
    For this specific task (T020), we assume the raw data exists in `data/raw/`
    as a JSON file generated by the ingestion pipeline (T018).
    If no data exists, we attempt to trigger a fetch or raise an error.
    """
    raw_dir = Path(config.RAW_DATA_DIR)
    raw_dir.mkdir(parents=True, exist_ok=True)
    
    # Look for the primary raw data file produced by ingestion
    # Based on T018, this is typically a JSON or CSV. We support both.
    candidates = [
        raw_dir / "polymer_blend_raw.json",
        raw_dir / "polymer_blend_raw.csv",
        raw_dir / "ingested_data.json"
    ]
    
    data_file = None
    for candidate in candidates:
        if candidate.exists():
            data_file = candidate
            break
    
    if not data_file:
        # If no data file exists, we cannot proceed with checksums.
        # This indicates T018 (Data Quality Report generation) or T014 (Fetcher)
        # has not run or failed to write data.
        logger.error(f"No raw data file found in {raw_dir}. Pipeline halted.")
        raise FileNotFoundError(
            f"Raw data file not found in {raw_dir}. "
            "Ensure T014 (fetch) and T018 (report/write) have completed successfully."
        )
    
    logger.info(f"Loading raw data from {data_file}")
    
    if data_file.suffix == '.json':
        with open(data_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
    elif data_file.suffix == '.csv':
        import pandas as pd
        df = pd.read_csv(data_file)
        data = df.to_dict(orient='records')
    else:
        raise ValueError(f"Unsupported file format: {data_file.suffix}")
    
    if not isinstance(data, list):
        # If it's a dict (e.g. {"data": [...]}), try to extract the list
        if "records" in data:
            data = data["records"]
        elif "data" in data:
            data = data["data"]
        else:
            raise ValueError("Raw data file does not contain a list of records.")
    
    return data, data_file

def save_raw_data(data: List[Dict[str, Any]], output_file: Optional[Path] = None) -> Path:
    """
    Saves the raw data to a canonical location if it wasn't already saved.
    Returns the path to the saved file.
    """
    raw_dir = Path(config.RAW_DATA_DIR)
    raw_dir.mkdir(parents=True, exist_ok=True)
    
    if output_file is None:
        output_file = raw_dir / "polymer_blend_raw.json"
    
    # Only save if the file doesn't exist or if we are overwriting (not implemented here)
    if not output_file.exists():
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str)
        logger.info(f"Saved raw data to {output_file}")
    else:
        logger.info(f"Raw data already exists at {output_file}, skipping write.")
    
    return output_file

def compute_and_save_checksum(file_path: Path, state_dir: Path) -> str:
    """
    Computes the SHA-256 checksum of a file and saves it to the state directory.
    Returns the checksum string.
    """
    if not file_path.exists():
        raise FileNotFoundError(f"File not found for checksum: {file_path}")
    
    checksum = compute_file_checksum(file_path)
    logger.info(f"Computed checksum for {file_path.name}: {checksum[:16]}...")
    
    # Save checksum to state directory
    checksum_file = state_dir / f"{file_path.name}.sha256"
    save_checksums({str(file_path): checksum}, checksum_file)
    
    return checksum

def update_project_state(checksums: Dict[str, str], state_file: Path):
    """
    Updates the project state YAML file with the new artifact hashes.
    """
    import yaml
    from datetime import datetime
    
    state_file.parent.mkdir(parents=True, exist_ok=True)
    
    if state_file.exists():
        with open(state_file, 'r', encoding='utf-8') as f:
            state = yaml.safe_load(f) or {}
    else:
        state = {
            "project_id": "PROJ-122-identifying-structure-property-relations",
            "artifacts": {},
            "last_updated": None
        }
    
    # Update artifacts section with new checksums
    if "artifacts" not in state:
        state["artifacts"] = {}
    
    for file_path, checksum in checksums.items():
        # Store relative path for portability
        rel_path = str(Path(file_path).relative_to(Path(config.PROJECT_ROOT)))
        state["artifacts"][rel_path] = {
            "sha256": checksum,
            "updated_at": datetime.utcnow().isoformat()
        }
    
    state["last_updated"] = datetime.utcnow().isoformat()
    
    with open(state_file, 'w', encoding='utf-8') as f:
        yaml.dump(state, f, default_flow_style=False, sort_keys=False)
    
    logger.info(f"Updated project state at {state_file}")

def main():
    """
    Main entry point for T020: Save raw data and compute checksums.
    """
    logger.info("Starting T020: Save raw data and compute checksums")
    
    # 1. Load or Fetch Real Data
    try:
        data, source_file = load_or_fetch_real_data()
    except FileNotFoundError as e:
        logger.error(str(e))
        sys.exit(1)
    
    # 2. Ensure data is saved in canonical location (if not already)
    raw_dir = Path(config.RAW_DATA_DIR)
    canonical_file = raw_dir / "polymer_blend_raw.json"
    saved_file = save_raw_data(data, canonical_file)
    
    # 3. Compute Checksum
    state_dir = Path(config.STATE_DIR)
    checksum = compute_and_save_checksum(saved_file, state_dir)
    
    # 4. Update Project State
    state_file = Path(config.PROJECT_STATE_FILE)
    update_project_state({str(saved_file): checksum}, state_file)
    
    logger.info("T020 completed successfully.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
