import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any

# Configure logging to match project standards
def setup_logger() -> logging.Logger:
    logger = logging.getLogger("validation_report")
    logger.setLevel(logging.INFO)
    if not logger.handlers:
        handler = logging.StreamHandler(sys.stdout)
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    return logger

logger = setup_logger()

def load_exclusion_log(input_path: str) -> Dict[str, Any]:
    """
    Loads the exclusion log generated by the preprocessing step (T006b2).
    Expects a JSON file with schema: {"excluded_count": int, "missing_columns": [str]}
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(
            f"Exclusion log not found at {input_path}. "
            "Ensure T006b2 (preprocess exclusion logic) has been executed successfully."
        )

    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Validate schema presence
    if 'excluded_count' not in data or 'missing_columns' not in data:
        raise ValueError(
            f"Invalid schema in {input_path}. Expected keys: 'excluded_count', 'missing_columns'. "
            f"Found keys: {list(data.keys())}"
        )

    return data

def generate_validation_report(
    input_path: str,
    output_path: str
) -> Dict[str, Any]:
    """
    Consumes the exclusion log and writes a validation report adhering to FR-010 schema.
    
    FR-010 Schema:
    {
        "excluded_count": int,
        "missing_columns": [str]
    }
    
    This function effectively transforms the internal exclusion log into the 
    formal validation report artifact required by the pipeline.
    """
    logger.info(f"Loading exclusion log from: {input_path}")
    exclusion_data = load_exclusion_log(input_path)

    # The validation report schema matches the exclusion log schema exactly per FR-010
    validation_report = {
        "excluded_count": exclusion_data["excluded_count"],
        "missing_columns": exclusion_data["missing_columns"]
    }

    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    logger.info(f"Writing validation report to: {output_path}")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(validation_report, f, indent=2)

    logger.info(f"Validation report generated successfully. Excluded rows: {validation_report['excluded_count']}")
    return validation_report

def main():
    """
    Entry point for the validation report generation script.
    Reads from data/processed/exclusion_log.json and writes to data/validation_report.json.
    """
    # Define paths relative to project root
    # Assuming script is run from project root or code directory
    base_dir = Path(__file__).resolve().parent.parent.parent
    input_path = base_dir / "data" / "processed" / "exclusion_log.json"
    output_path = base_dir / "data" / "validation_report.json"

    try:
        generate_validation_report(str(input_path), str(output_path))
        logger.info("Task T007 completed successfully.")
    except FileNotFoundError as e:
        logger.error(f"File missing: {e}")
        sys.exit(1)
    except ValueError as e:
        logger.error(f"Schema validation error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error during report generation: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()