import os
import sys
import json
import yaml
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path

# Ensure code root is in path if running as script
code_root = Path(__file__).resolve().parent.parent
if str(code_root) not in sys.path:
    sys.path.insert(0, str(code_root))

def load_config(config_path: str = "code/config.yaml") -> dict:
    """Load configuration from YAML file."""
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Configuration file not found: {config_path}")
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

def load_data(parquet_path: str = "data/raw/oqmd.parquet") -> pd.DataFrame:
    """
    Load the OQMD dataset from the materialized parquet file.
    Expects the file to exist (generated by T005).
    """
    if not os.path.exists(parquet_path):
        raise FileNotFoundError(
            f"Data file not found: {parquet_path}. "
            "Please run T005 (download.py) to materialize the dataset first."
        )
    return pd.read_parquet(parquet_path)

def apply_quantile_binning(df: pd.DataFrame, target_col: str, n_bins: int = 10) -> pd.DataFrame:
    """
    Apply quantile binning to the target variable to create discrete bins
    for stratification. Returns a copy of the dataframe with a 'target_bin' column.
    """
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in dataframe.")
    
    # Use pd.qcut to create equal-frequency bins
    # We use labels=False to get integer bin IDs directly
    # duplicates are handled by allowing them (since quantiles might not be unique for small datasets)
    try:
        bins = pd.qcut(df[target_col], q=n_bins, labels=False, duplicates='drop')
    except ValueError:
        # Fallback if unique values are fewer than bins
        n_unique = df[target_col].nunique()
        if n_unique < 2:
            raise ValueError("Target variable has insufficient variance for stratification.")
        bins = pd.qcut(df[target_col], q=n_unique, labels=False, duplicates='drop')
    
    df_copy = df.copy()
    df_copy['target_bin'] = bins
    return df_copy

def stratified_split(df: pd.DataFrame, config: dict) -> tuple:
    """
    Perform a stratified random split based on the target variable using quantile binning.
    
    Args:
        df: Input dataframe with features and target.
        config: Configuration dictionary containing split_ratio, split_type, and seed.
    
    Returns:
        Tuple of (train_df, val_df, test_df)
    """
    if config.get("split_type") != "stratified":
        raise ValueError("This function only supports 'stratified' split type.")
    
    seed = config.get("seed", 42)
    ratios = config.get("split_ratio", [0.8, 0.1, 0.1])
    target_col = "formation_energy" # Standard target for OQMD formation energy task
    
    if target_col not in df.columns:
        raise KeyError(f"Target column '{target_col}' not found. Available columns: {list(df.columns)}")
    
    # Apply quantile binning for stratification
    df_binned = apply_quantile_binning(df, target_col, n_bins=10)
    
    # First split: Train vs (Val + Test)
    train_ratio = ratios[0]
    val_ratio = ratios[1]
    test_ratio = ratios[2]
    
    # Calculate intermediate ratio for the second split
    # (Val + Test) = 1 - train_ratio
    # Val = val_ratio / (1 - train_ratio) of the remainder
    remainder_ratio = 1.0 - train_ratio
    val_ratio_intermediate = val_ratio / remainder_ratio if remainder_ratio > 0 else 0
    
    # Split 1: Train
    train_df, temp_df = train_test_split(
        df_binned, 
        train_size=train_ratio, 
        stratify=df_binned['target_bin'],
        random_state=seed
    )
    
    # Split 2: Val vs Test
    val_df, test_df = train_test_split(
        temp_df,
        train_size=val_ratio_intermediate,
        stratify=temp_df['target_bin'],
        random_state=seed
    )
    
    # Do NOT drop the target_bin column as per T006a requirements
    # The output CSVs MUST include a new column 'target_bin'
    return train_df, val_df, test_df

def save_split_data(train_df: pd.DataFrame, val_df: pd.DataFrame, test_df: pd.DataFrame, output_dir: str = "data/processed"):
    """
    Save the split dataframes to CSV files.
    Creates the output directory if it does not exist.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    train_path = os.path.join(output_dir, "raw_train.csv")
    val_path = os.path.join(output_dir, "raw_val.csv")
    test_path = os.path.join(output_dir, "raw_test.csv")
    
    train_df.to_csv(train_path, index=False)
    val_df.to_csv(val_path, index=False)
    test_df.to_csv(test_path, index=False)
    
    print(f"Saved train split: {train_path} (shape: {train_df.shape})")
    print(f"Saved val split: {val_path} (shape: {val_df.shape})")
    print(f"Saved test split: {test_path} (shape: {test_df.shape})")

def main():
    """
    Main entry point for the preprocessing script.
    Reads config, loads data, performs stratified split, and saves results.
    """
    # Load configuration
    config = load_config()
    print(f"Loaded config: {config}")
    
    # Load data
    print("Loading data...")
    df = load_data()
    print(f"Loaded data with shape: {df.shape}")
    
    # Perform split
    print("Performing stratified split...")
    train_df, val_df, test_df = stratified_split(df, config)
    
    # Save results
    print("Saving split data...")
    save_split_data(train_df, val_df, test_df)
    
    print("Preprocessing complete.")

if __name__ == "__main__":
    main()