[metadata]
name = solder-hardness-pipeline
version = 0.1.0
description = Predicting the impact of composition on the Vickers hardness of solder alloys

[options]
packages = find:
python_requires = >=3.9
install_requires =
    pandas
    scikit-learn
    xgboost
    shap
    numpy
    matplotlib
    pyyaml
    requests
    compositional==0.2.0
    pdfplumber
    pytest
    flake8
    black
    statsmodels
    seaborn

[options.packages.find]
where = .
exclude =
    tests*
    data*
    models*
    docs*

[isort]
profile = black
line_length = 100
known_first_party = seed,config,utils,models,features,ingestion,evaluation,visualization
