import os
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple, Optional
from pathlib import Path
from sklearn.metrics import mean_squared_error
from src.config import get_data_root, get_state_root
from src.utils import write_csv, read_json, get_logger
import json

logger = get_logger(__name__)

def calculate_baseline_mean(y_true: np.ndarray) -> float:
    """Calculate MSE of predicting the mean."""
    if len(y_true) == 0:
        return 0.0
    mean_pred = np.mean(y_true)
    return float(np.mean((y_true - mean_pred) ** 2))

def calculate_baseline_shuffled(y_true: np.ndarray, n_iter: int = 1000) -> float:
    """Calculate average MSE of shuffled predictions."""
    if len(y_true) == 0:
        return 0.0
    mse_scores = []
    for _ in range(n_iter):
        shuffled = np.random.permutation(y_true)
        mse_scores.append(np.mean((y_true - shuffled) ** 2))
    return float(np.mean(mse_scores))

def calculate_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    """Calculate regression metrics."""
    if len(y_true) == 0 or len(y_pred) == 0:
        return {"mse": 0.0, "rmse": 0.0, "mae": 0.0}
    mse = mean_squared_error(y_true, y_pred)
    return {
        "mse": float(mse),
        "rmse": float(np.sqrt(mse)),
        "mae": float(np.mean(np.abs(y_true - y_pred)))
    }

def run_baseline_comparisons(y_true: np.ndarray) -> Dict[str, float]:
    """Run baseline comparisons."""
    return {
        "mean_predictor_mse": calculate_baseline_mean(y_true),
        "shuffled_predictor_mse": calculate_baseline_shuffled(y_true)
    }

def save_baseline_results(results: Dict[str, float], output_path: str) -> None:
    """Save baseline results to CSV."""
    df = pd.DataFrame([results])
    write_csv(df, output_path)

def load_scaling_profile() -> Optional[pd.DataFrame]:
    """
    Load the scaling profile from the data directory.
    Expects data/scaling_profile.csv generated by T022 (batch processing).
    """
    data_root = get_data_root()
    scaling_file = os.path.join(data_root, "scaling_profile.csv")
    
    if not os.path.exists(scaling_file):
        logger.warning(f"Scaling profile not found at {scaling_file}. "
                       "Ensure T022 has been run successfully.")
        return None
    
    try:
        df = pd.read_csv(scaling_file)
        required_cols = ["batch_size", "total_time_seconds", "avg_time_per_clip"]
        if not all(col in df.columns for col in required_cols):
            logger.error(f"Scaling profile missing required columns: {required_cols}")
            return None
        return df
    except Exception as e:
        logger.error(f"Failed to load scaling profile: {e}")
        return None

def calculate_inference_time_projection(
    scaling_df: pd.DataFrame, 
    target_n: int = 10000
) -> Dict[str, float]:
    """
    Calculate projected inference time for N clips based on linear scaling.
    
    Args:
        scaling_df: DataFrame with batch processing stats (from T022).
        target_n: Target number of clips (default 10,000).
    
    Returns:
        Dict with projected_total_seconds, projected_total_hours, 
        avg_time_per_clip, and validation status.
    """
    if scaling_df is None or scaling_df.empty:
        raise ValueError("Scaling profile is empty or None. Cannot project time.")
    
    # Use the most recent/largest batch for projection (most stable estimate)
    # Or perform a linear regression if multiple points exist
    if len(scaling_df) > 1:
        # Linear regression to ensure linearity assumption holds
        x = scaling_df["batch_size"].values
        y = scaling_df["total_time_seconds"].values
        
        # Simple linear fit: time = slope * n + intercept
        # Force intercept through 0 for physical realism (0 clips = 0 time)
        # slope = sum(x*y) / sum(x^2)
        slope = np.sum(x * y) / np.sum(x ** 2)
        
        projected_seconds = slope * target_n
        avg_time_per_clip = slope
    else:
        # Single data point: use the average time per clip directly
        avg_time_per_clip = scaling_df["avg_time_per_clip"].iloc[0]
        projected_seconds = avg_time_per_clip * target_n
    
    projected_hours = projected_seconds / 3600.0
    
    return {
        "target_n": target_n,
        "avg_time_per_clip_seconds": float(avg_time_per_clip),
        "projected_total_seconds": float(projected_seconds),
        "projected_total_hours": float(projected_hours),
        "method": "linear_scaling"
    }

def generate_timing_profile(
    scaling_df: Optional[pd.DataFrame] = None, 
    target_n: int = 10000
) -> pd.DataFrame:
    """
    Generate the timing profile CSV.
    
    This function calculates per-clip inference time and projects total time
    for N=10,000 clips based on T022 results (validated by T021b).
    
    Args:
        scaling_df: Optional DataFrame with scaling data. If None, loads from disk.
        target_n: Target number of clips for projection.
    
    Returns:
        DataFrame containing the timing profile.
    """
    if scaling_df is None:
        scaling_df = load_scaling_profile()
    
    if scaling_df is None:
        raise RuntimeError(
            "Could not load scaling profile. "
            "Ensure T022 (batch processing) and T021b (scaling validation) have run."
        )
    
    # Calculate projection
    projection = calculate_inference_time_projection(scaling_df, target_n)
    
    # Create output DataFrame
    # Columns: batch_size, avg_time_per_clip, projected_total_seconds, projected_total_hours
    output_data = {
        "batch_size": [target_n],
        "avg_time_per_clip_seconds": [projection["avg_time_per_clip_seconds"]],
        "projected_total_seconds": [projection["projected_total_seconds"]],
        "projected_total_hours": [projection["projected_total_hours"]],
        "method": [projection["method"]]
    }
    
    df_output = pd.DataFrame(output_data)
    
    # Save to data/timing_profile.csv
    data_root = get_data_root()
    output_path = os.path.join(data_root, "timing_profile.csv")
    write_csv(df_output, output_path)
    
    logger.info(f"Timing profile generated and saved to {output_path}")
    logger.info(f"Projected total time for {target_n} clips: {projection['projected_total_hours']:.2f} hours")
    
    return df_output

def main():
    """Entry point for T024: Generate timing profile."""
    logger.info("Starting T024: Inference time projection and timing profile generation")
    
    try:
        # Load scaling profile (output of T022)
        scaling_df = load_scaling_profile()
        
        if scaling_df is None:
            logger.error("Scaling profile not found. T022 must be run first.")
            return 1
        
        logger.info(f"Loaded scaling profile with {len(scaling_df)} data points")
        
        # Generate timing profile for 10,000 clips
        target_n = 10000
        result_df = generate_timing_profile(scaling_df, target_n)
        
        # Print summary
        print("\n--- Timing Profile Summary ---")
        print(f"Target Clips: {target_n}")
        print(f"Projected Total Time: {result_df['projected_total_hours'].iloc[0]:.2f} hours")
        print(f"Average Time per Clip: {result_df['avg_time_per_clip_seconds'].iloc[0]:.4f} seconds")
        print("------------------------------")
        
        return 0
        
    except Exception as e:
        logger.error(f"Error during T024 execution: {e}")
        raise

if __name__ == "__main__":
    exit(main())
