import os
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import numpy as np

from src.utils.logging import get_logger
from src.models.entities import TopicVector

# Define the five 5-year windows as per project specification
WINDOWS = [
    "2000-2004",
    "2005-2009",
    "2010-2014",
    "2015-2019",
    "2020-2024"
]

# Expected number of topics (k=10) based on T020/T022
K_TOPICS = 10

logger = get_logger(__name__)


def load_topic_distributions(input_dir: Optional[Path] = None) -> Dict[str, Dict[str, List[float]]]:
    """
    Load topic distributions (proportions) from JSON files generated by the LDA fitter.
    
    The LDA fitter (T020) is expected to save topic distributions per window.
    We assume a standard naming convention: topic_distributions_<window>.json
    
    Args:
        input_dir: Directory containing the topic distribution files. Defaults to 'results/stats/'.
        
    Returns:
        Dictionary mapping window names to their topic distribution vectors.
        
    Raises:
        FileNotFoundError: If expected files are missing.
        ValueError: If data format is invalid.
    """
    if input_dir is None:
        input_dir = Path("results/stats")
        
    distributions = {}
    
    for window in WINDOWS:
        file_path = input_dir / f"topic_distributions_{window}.json"
        
        if not file_path.exists():
            # If the file doesn't exist, we might need to compute them first
            # However, T020 should have produced these. If missing, we raise.
            logger.error(f"Topic distribution file not found: {file_path}")
            raise FileNotFoundError(f"Missing topic distribution file for window {window}: {file_path}")
        
        try:
            with open(file_path, 'r') as f:
                data = json.load(f)
            
            # Expected format: {"topics": [ [prob_0, prob_1, ...], ... ]}
            # where each inner list is a document's topic distribution
            if "topics" not in data:
                raise ValueError(f"Invalid format in {file_path}: missing 'topics' key")
            
            distributions[window] = data["topics"]
            logger.info(f"Loaded {len(data['topics'])} topic distributions for window {window}")
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON in {file_path}: {e}")
            raise
            
    return distributions


def compute_topic_proportions(doc_topic_dists: List[List[float]], k: int = K_TOPICS) -> np.ndarray:
    """
    Compute the aggregate topic proportion vector for a set of documents.
    
    This aggregates the topic distributions of individual documents to get
    the overall topic proportions for the window.
    
    Args:
        doc_topic_dists: List of topic distribution vectors, one per document.
        k: Number of topics (default 10).
        
    Returns:
        Normalized topic proportion vector of length k.
        
    Raises:
        ValueError: If input is invalid or dimensions don't match.
    """
    if not doc_topic_dists:
        raise ValueError("Cannot compute proportions from empty document list")
        
    doc_topic_dists = np.array(doc_topic_dists, dtype=np.float64)
    
    if doc_topic_dists.shape[1] != k:
        raise ValueError(f"Expected {k} topics per document, got {doc_topic_dists.shape[1]}")
        
    # Sum across documents to get total topic counts
    topic_sums = np.sum(doc_topic_dists, axis=0)
    
    # Normalize to get proportions (sum to 1.0)
    total_sum = np.sum(topic_sums)
    
    if total_sum == 0:
        raise ValueError("Total topic sum is zero; cannot normalize")
        
    proportions = topic_sums / total_sum
    
    # Validate: no NaN, sum to 1.0
    if np.any(np.isnan(proportions)):
        raise ValueError("Computed proportions contain NaN values")
        
    # Due to floating point, sum might not be exactly 1.0, but should be very close
    if not np.isclose(np.sum(proportions), 1.0, rtol=1e-5):
        logger.warning(f"Proportion sum is {np.sum(proportions)}, expected ~1.0")
        
    return proportions


def validate_proportion_vector(proportion_vector: np.ndarray) -> bool:
    """
    Validate a topic proportion vector.
    
    Checks:
    - No NaN values
    - Sum is approximately 1.0
    - All values are non-negative
    - Length matches expected k_topics
    
    Args:
        proportion_vector: The vector to validate.
        
    Returns:
        True if valid, False otherwise.
    """
    if proportion_vector is None:
        logger.error("Proportion vector is None")
        return False
        
    if np.any(np.isnan(proportion_vector)):
        logger.error("Proportion vector contains NaN values")
        return False
        
    if np.any(proportion_vector < 0):
        logger.error("Proportion vector contains negative values")
        return False
        
    if not np.isclose(np.sum(proportion_vector), 1.0, rtol=1e-5):
        logger.error(f"Proportion vector sum is {np.sum(proportion_vector)}, expected ~1.0")
        return False
        
    if len(proportion_vector) != K_TOPICS:
        logger.error(f"Proportion vector length is {len(proportion_vector)}, expected {K_TOPICS}")
        return False
        
    return True


def compute_all_window_proportions(
    input_dir: Optional[Path] = None,
    k: int = K_TOPICS
) -> Dict[str, np.ndarray]:
    """
    Compute topic proportion vectors for all windows.
    
    Args:
        input_dir: Directory containing topic distribution files.
        k: Number of topics.
        
    Returns:
        Dictionary mapping window names to their topic proportion vectors.
    """
    distributions = load_topic_distributions(input_dir)
    proportions = {}
    
    for window, doc_dists in distributions.items():
        logger.info(f"Computing proportions for window {window}")
        prop_vector = compute_topic_proportions(doc_dists, k)
        
        if not validate_proportion_vector(prop_vector):
            raise ValueError(f"Invalid proportion vector computed for window {window}")
            
        proportions[window] = prop_vector
        logger.info(f"Window {window} proportions: {prop_vector}")
        
    return proportions


def save_topic_vectors(
    proportions: Dict[str, np.ndarray],
    output_path: Optional[Path] = None
) -> Path:
    """
    Save topic proportion vectors to a JSON file.
    
    Args:
        proportions: Dictionary mapping window names to proportion vectors.
        output_path: Path to save the file. Defaults to 'results/stats/topic_vectors.json'.
        
    Returns:
        The path to the saved file.
    """
    if output_path is None:
        output_path = Path("results/stats/topic_vectors.json")
        
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Convert numpy arrays to lists for JSON serialization
    data = {
        "k_topics": K_TOPICS,
        "windows": list(proportions.keys()),
        "topic_vectors": {
            window: prop_vector.tolist()
            for window, prop_vector in proportions.items()
        }
    }
    
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=2)
        
    logger.info(f"Saved topic vectors to {output_path}")
    return output_path


def main():
    """
    Main entry point for computing and saving topic proportions.
    
    This function:
    1. Loads topic distributions from LDA output files
    2. Computes aggregate topic proportions for each window
    3. Validates the proportions (sum=1.0, no NaN)
    4. Saves the results to results/stats/topic_vectors.json
    """
    logger.info("Starting topic proportion computation")
    
    try:
        # Compute proportions for all windows
        proportions = compute_all_window_proportions()
        
        # Save to file
        output_path = save_topic_vectors(proportions)
        
        logger.info(f"Successfully computed and saved topic vectors to {output_path}")
        
        # Print summary
        for window, prop in proportions.items():
            logger.info(f"  {window}: sum={np.sum(prop):.6f}, min={np.min(prop):.6f}, max={np.max(prop):.6f}")
            
    except FileNotFoundError as e:
        logger.error(f"Required input files not found: {e}")
        raise
    except ValueError as e:
        logger.error(f"Invalid data encountered: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error during proportion computation: {e}")
        raise


if __name__ == "__main__":
    main()
