"""
Script to generate sensory modalities (RGB, Depth, Occupancy Grid) from raw sensor data.

This script:
1. Loads validated calibration parameters from results/calibration_report.json (produced by T008b).
2. Processes raw sensor data using the pipeline modules (T020, T021, T022).
3. Saves the generated modalities to data/modalities/.
4. Ensures spatial alignment using the calibration data.
"""
import os
import sys
import json
import logging
import numpy as np
from pathlib import Path
from typing import Dict, Any, Optional

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.utils.config import get_path, get_hyperparameter, set_seed
from src.data.calibration import CalibrationReport, validate_calibration
from src.data.pipeline import (
    RGBPreprocessor,
    DepthDownsampler,
    OccupancyGridGenerator,
    create_rgb_preprocessor,
    create_depth_downsampler,
    create_occupancy_grid_generator
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_calibration_report(report_path: Path) -> CalibrationReport:
    """
    Load and validate the calibration report generated by T008b.
    
    Args:
        report_path: Path to the calibration_report.json file
        
    Returns:
        Validated CalibrationReport object
        
    Raises:
        FileNotFoundError: If the report file doesn't exist
        ValueError: If validation fails
    """
    if not report_path.exists():
        raise FileNotFoundError(
            f"Calibration report not found at {report_path}. "
            "Run T008b (validate_calibration.py) first."
        )
    
    with open(report_path, 'r') as f:
        report_data = json.load(f)
    
    # Convert to CalibrationReport object
    report = CalibrationReport(
        extrinsic_params=report_data['extrinsic_params'],
        validation_metrics=report_data['validation_metrics'],
        is_valid=report_data['is_valid'],
        timestamp=report_data.get('timestamp', '')
    )
    
    if not report.is_valid:
        raise ValueError(
            f"Calibration validation failed. "
            f"Metrics: {report.validation_metrics}"
        )
    
    logger.info(f"Calibration loaded and validated successfully. "
               f"Timestamp: {report.timestamp}")
    return report

def generate_sample_sensor_data(
    num_samples: int,
    rgb_shape: tuple = (480, 640, 3),
    depth_shape: tuple = (480, 640)
) -> Dict[str, np.ndarray]:
    """
    Generate realistic sample sensor data for testing.
    In production, this would be replaced with actual sensor data loading.
    
    Args:
        num_samples: Number of samples to generate
        rgb_shape: Shape of RGB images (H, W, C)
        depth_shape: Shape of depth maps (H, W)
        
    Returns:
        Dictionary with 'rgb' and 'depth' keys containing numpy arrays
    """
    logger.info(f"Generating {num_samples} sample sensor data points...")
    
    # Generate RGB data (simulating camera images)
    rgb_data = np.random.randint(0, 255, (num_samples, *rgb_shape), dtype=np.uint8)
    
    # Generate depth data (simulating LiDAR/depth camera)
    # Create realistic depth patterns with obstacles
    depth_data = np.zeros((num_samples, *depth_shape), dtype=np.float32)
    for i in range(num_samples):
        # Base depth gradient
        y, x = np.ogrid[:depth_shape[0], :depth_shape[1]]
        base_depth = 5.0 + 0.01 * x + 0.005 * y
        
        # Add some obstacles (higher depth values = closer objects)
        obstacle_mask = (np.random.random(depth_shape) > 0.8)
        depth_data[i] = np.where(obstacle_mask, base_depth * 0.3, base_depth)
        
        # Add noise
        depth_data[i] += np.random.normal(0, 0.1, depth_shape)
        depth_data[i] = np.clip(depth_data[i], 0.1, 20.0)
    
    return {
        'rgb': rgb_data,
        'depth': depth_data
    }

def process_sensor_data(
    sensor_data: Dict[str, np.ndarray],
    calibration_report: CalibrationReport,
    rgb_preprocessor: RGBPreprocessor,
    depth_downsampler: DepthDownsampler,
    occupancy_grid_generator: OccupancyGridGenerator
) -> Dict[str, np.ndarray]:
    """
    Process raw sensor data through the pipeline to generate modalities.
    
    Args:
        sensor_data: Dictionary with 'rgb' and 'depth' keys
        calibration_report: Validated calibration parameters
        rgb_preprocessor: RGB preprocessing instance
        depth_downsampler: Depth downsampling instance
        occupancy_grid_generator: Occupancy grid generation instance
        
    Returns:
        Dictionary with processed modalities
    """
    logger.info("Processing sensor data through pipeline...")
    
    # Process RGB
    processed_rgb = rgb_preprocessor.process_batch(sensor_data['rgb'])
    logger.info(f"RGB processed: {processed_rgb.shape}")
    
    # Process Depth
    processed_depth = depth_downsampler.process_batch(sensor_data['depth'])
    logger.info(f"Depth processed: {processed_depth.shape}")
    
    # Generate Occupancy Grid using calibrated depth
    occupancy_grid = occupancy_grid_generator.process_batch(
        processed_depth,
        calibration_report=calibration_report
    )
    logger.info(f"Occupancy grid generated: {occupancy_grid.shape}")
    
    return {
        'rgb': processed_rgb,
        'depth': processed_depth,
        'occupancy_grid': occupancy_grid
    }

def save_modalities(
    modalities: Dict[str, np.ndarray],
    output_dir: Path,
    seed: int
):
    """
    Save generated modalities to disk.
    
    Args:
        modalities: Dictionary with processed modality arrays
        output_dir: Directory to save the modalities
        seed: Random seed used for generation
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Save each modality
    for modality_name, modality_data in modalities.items():
        output_path = output_dir / f"{modality_name}_seed_{seed}.npy"
        np.save(output_path, modality_data)
        logger.info(f"Saved {modality_name} to {output_path}")
    
    # Save metadata
    metadata = {
        'seed': seed,
        'modality_shapes': {
            name: data.shape for name, data in modalities.items()
        },
        'calibration_timestamp': calibration_report.timestamp if 'calibration_report' in locals() else 'unknown'
    }
    
    metadata_path = output_dir / f"metadata_seed_{seed}.json"
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=2)
    logger.info(f"Saved metadata to {metadata_path}")

def main():
    """Main execution function."""
    logger.info("Starting modality generation pipeline...")
    
    # Set random seed for reproducibility
    seed = get_hyperparameter("seed", default=42)
    set_seed(seed)
    logger.info(f"Using seed: {seed}")
    
    # Load calibration report
    calibration_path = get_path("calibration_report")
    logger.info(f"Loading calibration from: {calibration_path}")
    calibration_report = load_calibration_report(Path(calibration_path))
    
    # Initialize pipeline components
    logger.info("Initializing pipeline components...")
    rgb_preprocessor = create_rgb_preprocessor()
    depth_downsampler = create_depth_downsampler()
    occupancy_grid_generator = create_occupancy_grid_generator()
    
    # Generate sample sensor data (replace with real data loading in production)
    num_samples = get_hyperparameter("num_samples", default=10)
    sensor_data = generate_sample_sensor_data(num_samples)
    logger.info(f"Generated {num_samples} samples of sensor data")
    
    # Process data
    modalities = process_sensor_data(
        sensor_data,
        calibration_report,
        rgb_preprocessor,
        depth_downsampler,
        occupancy_grid_generator
    )
    
    # Save results
    output_dir = Path(get_path("modalities_output"))
    logger.info(f"Saving modalities to: {output_dir}")
    save_modalities(modalities, output_dir, seed)
    
    logger.info("Modality generation completed successfully!")
    print(f"Modalities saved to {output_dir}")
    print(f"Files generated:")
    for file in sorted(output_dir.glob("*")):
        print(f"  - {file.name}")

if __name__ == "__main__":
    main()