import json
import os
import sys
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd
import numpy as np

# Constants for heuristic thresholds
OCR_DENSITY_THRESHOLD = 0.005  # Minimum characters per pixel to be considered text
ASPECT_RATIO_THRESHOLD = 2.0   # Width/height ratio > 2.0 suggests horizontal text line

def load_raw_dataset(raw_path: Path) -> pd.DataFrame:
    """
    Loads the raw dataset from the parquet file generated by T006.
    
    Args:
        raw_path: Path to the raw parquet file (data/raw/omnidoc_tokenbench.parquet)
        
    Returns:
        DataFrame containing the raw dataset
    """
    if not raw_path.exists():
        raise FileNotFoundError(f"Raw dataset not found at {raw_path}. "
                              "Please run T006 (download.py) first.")
    return pd.read_parquet(raw_path)

def extract_ground_truth_labels(df: pd.DataFrame) -> pd.DataFrame:
    """
    Extracts ground-truth labels from bounding box annotations.
    
    Args:
        df: DataFrame with raw dataset containing bbox and modality info
        
    Returns:
        DataFrame with region_id, modality_label, bbox
    """
    # Implementation depends on specific schema of OmniDoc-TokenBench
    # Assuming columns: 'region_id', 'bbox', 'modality' or similar
    # This is a placeholder for the actual logic defined in T008
    if 'modality' in df.columns:
        labels_df = df[['region_id', 'bbox', 'modality']].copy()
        labels_df.columns = ['region_id', 'bbox', 'modality_label', 'bbox']
        return labels_df
    else:
        # Fallback: attempt to infer from structure
        raise NotImplementedError("Schema mapping for ground-truth extraction not fully defined in context.")

def derive_heuristic_labels(df: pd.DataFrame) -> pd.DataFrame:
    """
    Derives 'text'/'image' labels using OCR density and aspect ratio heuristics.
    
    Logic:
    1. Calculate OCR density: char_count / (bbox_width * bbox_height)
    2. Calculate aspect ratio: width / height
    3. Label as 'text' if density > OCR_DENSITY_THRESHOLD OR aspect_ratio > ASPECT_RATIO_THRESHOLD
    4. Otherwise label as 'image'
    
    Args:
        df: DataFrame with region data including bbox and optionally text content
        
    Returns:
        DataFrame with region_id, heuristic_label, bbox, density, aspect_ratio
    """
    if df.empty:
        return pd.DataFrame(columns=['region_id', 'heuristic_label', 'bbox', 'density', 'aspect_ratio'])
    
    # Ensure bbox is processed (assume it's a string or tuple of [x, y, w, h] or [x1, y1, x2, y2])
    # Standardizing bbox format to [x, y, width, height]
    def parse_bbox(bbox_val):
        if isinstance(bbox_val, str):
            try:
                parts = list(map(float, bbox_val.strip('[]()').split(',')))
                if len(parts) == 4:
                    # Assuming x, y, w, h or x1, y1, x2, y2
                    if parts[2] < parts[0]: # Likely x1, y1, x2, y2
                        return [parts[0], parts[1], parts[2] - parts[0], parts[3] - parts[1]]
                    return parts
            except:
                return [0, 0, 1, 1]
        elif isinstance(bbox_val, (list, tuple)):
            if len(bbox_val) == 4:
                if bbox_val[2] < bbox_val[0]:
                    return [bbox_val[0], bbox_val[1], bbox_val[2] - bbox_val[0], bbox_val[3] - bbox_val[1]]
                return list(bbox_val)
        return [0, 0, 1, 1]

    # Apply parsing
    bboxes = df['bbox'].apply(parse_bbox)
    df_expanded = df.copy()
    df_expanded['bbox_x'] = bboxes.apply(lambda b: b[0])
    df_expanded['bbox_y'] = bboxes.apply(lambda b: b[1])
    df_expanded['bbox_w'] = bboxes.apply(lambda b: b[2])
    df_expanded['bbox_h'] = bboxes.apply(lambda b: b[3])
    
    # Calculate Area
    df_expanded['area'] = df_expanded['bbox_w'] * df_expanded['bbox_h']
    
    # Calculate Aspect Ratio (width / height)
    # Avoid division by zero
    df_expanded['aspect_ratio'] = np.where(
        df_expanded['bbox_h'] > 0,
        df_expanded['bbox_w'] / df_expanded['bbox_h'],
        0
    )
    
    # Calculate OCR Density
    # We need a character count. If 'text' or 'content' column exists, use it.
    # Otherwise, we assume 'char_count' might be pre-computed or we must estimate.
    # Given the task description implies "OCR density", we assume a text column exists
    # or we simulate the density calculation based on available text data.
    # If no text column, we cannot compute density, so we rely on aspect ratio only.
    
    text_col = None
    if 'text' in df.columns:
        text_col = 'text'
    elif 'content' in df.columns:
        text_col = 'content'
    elif 'char_count' in df.columns:
        # Direct use
        df_expanded['char_count'] = df['char_count']
    else:
        # Fallback: If no text data, density is 0. 
        # We must rely on aspect ratio or mark as unknown.
        # For this heuristic to work as a "sanity check" without OCR engine,
        # we assume the dataset has a 'text' column. If not, we set density to 0.
        df_expanded['char_count'] = 0
        text_col = None

    if text_col:
        df_expanded['char_count'] = df_expanded[text_col].astype(str).str.len()
    
    df_expanded['density'] = np.where(
        df_expanded['area'] > 0,
        df_expanded['char_count'] / df_expanded['area'],
        0
    )
    
    # Apply Heuristic Logic
    # Label as 'text' if density > threshold OR aspect_ratio > threshold
    is_text = (df_expanded['density'] > OCR_DENSITY_THRESHOLD) | \
              (df_expanded['aspect_ratio'] > ASPECT_RATIO_THRESHOLD)
    
    df_expanded['heuristic_label'] = np.where(is_text, 'text', 'image')
    
    # Select and clean output columns
    result = df_expanded[['region_id', 'heuristic_label', 'bbox', 'density', 'aspect_ratio']].copy()
    
    return result

def run_extraction(
    raw_path: Path,
    output_path: Path,
    mode: str = 'heuristic'
) -> Path:
    """
    Main entry point for running extraction logic.
    
    Args:
        raw_path: Path to raw dataset
        output_path: Path to save the output file
        mode: 'ground_truth' or 'heuristic'
        
    Returns:
        Path to the created output file
    """
    print(f"Loading raw dataset from {raw_path}...")
    df = load_raw_dataset(raw_path)
    
    print(f"Processing {len(df)} regions...")
    if mode == 'ground_truth':
        result_df = extract_ground_truth_labels(df)
        output_path = output_path.with_suffix('.parquet')
    elif mode == 'heuristic':
        result_df = derive_heuristic_labels(df)
        output_path = output_path.with_suffix('.csv')
    else:
        raise ValueError(f"Unknown mode: {mode}. Use 'ground_truth' or 'heuristic'.")
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    if output_path.suffix == '.parquet':
        result_df.to_parquet(output_path, index=False)
    else:
        result_df.to_csv(output_path, index=False)
        
    print(f"Saved {mode} labels to {output_path}")
    return output_path

def main():
    """
    CLI entry point for T008b: Heuristic Label Derivation.
    
    Usage:
    python code/data/preprocess.py --mode heuristic
    """
    import argparse
    
    parser = argparse.ArgumentParser(description="Preprocess dataset for label extraction")
    parser.add_argument("--mode", type=str, default="heuristic", 
                      choices=["ground_truth", "heuristic"],
                      help="Extraction mode: 'ground_truth' (T008) or 'heuristic' (T008b)")
    parser.add_argument("--input", type=str, default="data/raw/omnidoc_tokenbench.parquet",
                      help="Path to raw dataset")
    parser.add_argument("--output", type=str, default="data/interim/heuristic_labels.csv",
                      help="Path for output file (suffix ignored if mode specified)")
                      
    args = parser.parse_args()
    
    input_path = Path(args.input)
    output_path = Path(args.output)
    
    if not input_path.exists():
        print(f"Error: Input file not found at {input_path}")
        sys.exit(1)
        
    # If mode is heuristic, ensure output suffix is csv
    if args.mode == 'heuristic':
        output_path = output_path.with_suffix('.csv')
    else:
        output_path = output_path.with_suffix('.parquet')

    run_extraction(input_path, output_path, mode=args.mode)

if __name__ == "__main__":
    main()