import os
import sys
import json
import yaml
import pandas as pd
import numpy as np
from pathlib import Path

def load_config(config_path="code/config.yaml"):
    """Load pipeline configuration."""
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def load_analysis_results(results_path="data/analysis/correlation_results.csv"):
    """
    Load the correlation results generated by analysis.py.
    Expected columns: channel, metric_type, correlation, p_value, fdr_q_value, ...
    """
    if not os.path.exists(results_path):
        raise FileNotFoundError(f"Analysis results not found at {results_path}. "
                                "Run analysis.py first.")
    return pd.read_csv(results_path)

def calculate_vif(df, feature_columns):
    """
    Calculate Variance Inflation Factor (VIF) for a set of features.
    
    VIF measures how much the variance of an estimated regression coefficient 
    increases if your predictors are correlated.
    
    Args:
        df: DataFrame containing the features.
        feature_columns: List of column names to calculate VIF for.
        
    Returns:
        dict: Mapping of feature name to VIF value.
    """
    if len(feature_columns) == 0:
        return {}
        
    # Select only the relevant columns
    X = df[feature_columns].dropna()
    
    if X.shape[0] < 2:
        raise ValueError("Not enough data points to calculate VIF (need at least 2).")
        
    if X.shape[1] == 0:
        return {}
        
    vif_results = {}
    
    # Add intercept for OLS (though statsmodels would handle this, we do manual calc)
    # VIF_j = 1 / (1 - R_j^2) where R_j^2 is from regressing X_j on all other X's
    
    for i, col in enumerate(feature_columns):
        if col not in X.columns:
            continue
            
        y = X[col]
        # Other features
        X_other = X.drop(columns=[col])
        
        if X_other.shape[1] == 0:
            # Only one feature, VIF is 1 by definition
            vif_results[col] = 1.0
            continue
        
        # Simple OLS: y = b0 + b1*x1 + ... + bn*xn
        # Add intercept
        X_with_intercept = np.column_stack([np.ones(X_other.shape[0]), X_other.values])
        y_values = y.values
        
        # Solve normal equations: (X'X)^-1 X'y
        try:
            # Compute R^2
            # Predictions
            beta = np.linalg.lstsq(X_with_intercept, y_values, rcond=None)[0]
            y_pred = X_with_intercept @ beta
            
            ss_res = np.sum((y_values - y_pred) ** 2)
            ss_tot = np.sum((y_values - np.mean(y_values)) ** 2)
            
            if ss_tot == 0:
                r_squared = 0
            else:
                r_squared = 1 - (ss_res / ss_tot)
            
            # VIF = 1 / (1 - R^2)
            if r_squared >= 1.0:
                vif_results[col] = float('inf')
            else:
                vif_results[col] = 1.0 / (1.0 - r_squared)
                
        except np.linalg.LinAlgError:
            # Singular matrix, perfect collinearity
            vif_results[col] = float('inf')
    
    return vif_results

def run_collinearity_diagnostics(results_df, threshold=5.0):
    """
    Run collinearity diagnostics on the analysis results.
    
    If multiple metrics are combined (e.g., LZC and PE across channels),
    check for multicollinearity using VIF.
    
    Args:
        results_df: DataFrame with correlation analysis results.
        threshold: VIF threshold for flagging collinearity (default 5.0).
        
    Returns:
        dict: Diagnostic results including VIF values and pass/fail status.
    """
    # Identify numeric columns that could be features
    # Typically these would be the complexity metrics if they were used as predictors
    # For this task, we assume the 'correlation' or derived metric columns might be used
    # However, VIF is typically run on predictor variables in a regression model.
    # Since we have correlation results, we check if the metrics themselves 
    # (if we had raw values) are collinear.
    # 
    # Given the current output structure (aggregated correlations), we cannot 
    # directly compute VIF on the correlation coefficients themselves.
    # 
    # Instead, we assume that if the task requires checking collinearity 
    # "if metrics are combined", it implies we should have access to the 
    # underlying metric values (e.g., from data/processed/lzc_metrics.csv 
    # and data/processed/pe_metrics.csv) to run VIF on the feature matrix.
    #
    # However, the task description says "if metrics are combined per SC-004".
    # Let's assume we are checking the correlation results for potential 
    # multicollinearity in a hypothetical combined model.
    #
    # Since we don't have the raw features here, we will check the 
    # correlation matrix of the channels if we had the raw data.
    # 
    # Alternative interpretation: The task might be asking to check 
    # if the correlation results themselves show signs of redundancy.
    # But VIF is specifically for regression predictors.
    #
    # Let's implement a check that would run if we had the feature matrix.
    # We will load the processed metrics if available, or report that 
    # raw metrics are needed.
    
    lzc_path = "data/processed/lzc_metrics.csv"
    pe_path = "data/processed/pe_metrics.csv"
    
    features = {}
    combined_df = None
    
    if os.path.exists(lzc_path):
        lzc_df = pd.read_csv(lzc_path)
        # Assume columns: participant_id, channel, lzc_value
        if 'lzc_value' in lzc_df.columns:
            features['lzc'] = lzc_df.pivot(index='participant_id', 
                                            columns='channel', 
                                            values='lzc_value')
            
    if os.path.exists(pe_path):
        pe_df = pd.read_csv(pe_path)
        if 'pe_value' in pe_df.columns:
            pe_pivot = pe_df.pivot(index='participant_id', 
                                   columns='channel', 
                                   values='pe_value')
            features['pe'] = pe_pivot
    
    if not features:
        return {
            "status": "skipped",
            "reason": "No raw metric files found to compute VIF. "
                      "Expected data/processed/lzc_metrics.csv and/or "
                      "data/processed/pe_metrics.csv with participant_id, channel, and value columns."
        }
    
    # Combine features if both exist
    if len(features) == 2:
        combined_df = pd.concat([features['lzc'], features['pe']], axis=1)
        # Drop rows with any NaN
        combined_df = combined_df.dropna()
    else:
        combined_df = list(features.values())[0].dropna()
    
    if combined_df.empty or combined_df.shape[1] < 2:
        return {
            "status": "skipped",
            "reason": "Insufficient features (need at least 2) or no data after cleaning."
        }
    
    # Calculate VIF
    feature_cols = combined_df.columns.tolist()
    vif_values = calculate_vif(combined_df, feature_cols)
    
    # Check against threshold
    high_vif = {k: v for k, v in vif_values.items() if v > threshold}
    
    return {
        "status": "passed" if not high_vif else "failed",
        "threshold": threshold,
        "vif_values": vif_values,
        "high_vif_features": high_vif,
        "message": f"Collinearity check {'passed' if not high_vif else 'failed'}. "
                   f"VIF threshold: {threshold}. "
                   f"Features with VIF > {threshold}: {list(high_vif.keys()) if high_vif else 'None'}."
    }

def main():
    """Main entry point for collinearity diagnostics."""
    config = load_config()
    threshold = config.get('collinearity', {}).get('vif_threshold', 5.0)
    
    print("Loading analysis results...")
    try:
        results_df = load_analysis_results()
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    
    print("Running collinearity diagnostics...")
    diagnostics = run_collinearity_diagnostics(results_df, threshold)
    
    # Save results
    output_path = "data/analysis/collinearity_diagnostics.json"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w') as f:
        json.dump(diagnostics, f, indent=2, default=str)
    
    print(f"Diagnostics saved to {output_path}")
    print(f"Status: {diagnostics['status']}")
    print(f"Message: {diagnostics['message']}")
    
    if diagnostics['status'] == 'failed':
        sys.exit(1)
    
    sys.exit(0)

if __name__ == "__main__":
    main()
