import os
import sys
import csv
from pathlib import Path
import pandas as pd
import numpy as np
import yaml

def load_config():
    config_path = Path("code/config.yaml")
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

def load_analysis_results():
    """
    Loads the analysis results from the expected location.
    This function expects 'data/analysis/correlation_results.csv' to exist,
    which should be generated by code/analysis.py.
    """
    results_path = Path("data/analysis/correlation_results.csv")
    if not results_path.exists():
        raise FileNotFoundError(
            f"Analysis results file not found: {results_path}. "
            "Ensure code/analysis.py has been run successfully."
        )
    return pd.read_csv(results_path)

def run_sensitivity_analysis(results_df, thresholds=[0.05, 0.01]):
    """
    Runs sensitivity analysis by counting significant electrodes at different p-value thresholds.

    Args:
        results_df (pd.DataFrame): DataFrame containing correlation results with a 'p_value' column.
        thresholds (list): List of p-value thresholds to test.

    Returns:
        pd.DataFrame: A DataFrame with columns 'threshold' and 'count_significant'.
    """
    if 'p_value' not in results_df.columns:
        raise ValueError("Input DataFrame must contain a 'p_value' column.")

    results = []
    for threshold in thresholds:
        # Count rows where p_value <= threshold
        significant_count = (results_df['p_value'] <= threshold).sum()
        results.append({
            'threshold': float(threshold),
            'count_significant': int(significant_count)
        })

    return pd.DataFrame(results)

def generate_sensitivity_table(results_df, output_path="data/analysis/sensitivity_table.csv"):
    """
    Generates the sensitivity analysis table and saves it to a CSV file.

    Args:
        results_df (pd.DataFrame): DataFrame containing correlation results.
        output_path (str): Path to save the output CSV file.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df = run_sensitivity_analysis(results_df)
    df.to_csv(output_path, index=False)
    print(f"Sensitivity table written to {output_path}")
    return df

def main():
    """
    Main entry point for the sensitivity analysis script.
    """
    print("Starting sensitivity analysis pipeline.")
    try:
        config = load_config()
        results_df = load_analysis_results()
        output_file = Path("data/analysis/sensitivity_table.csv")
        generate_sensitivity_table(results_df, str(output_file))
        print("Sensitivity analysis completed successfully.")
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
