"""
Feature Engineering Module for Climate-Smart Agriculture Optimization.

This module handles the extraction of raw NDVI time-series, calculation of
CSA Index and Stability Score, derivation of Village IDs, and village-level
aggregation.
"""
import logging
import json
import sys
from pathlib import Path
from typing import Dict, Any, Optional, Tuple, List

import pandas as pd
import numpy as np
import pyarrow.parquet as pq

# Import constants from the project configuration
import src.config.constants as constants
from src.utils.io_helpers import (
    setup_logging,
    read_csv_strict,
    write_parquet_strict,
    write_csv_strict,
    load_json_strict,
    write_json_strict,
    FatalError
)

# Setup logging for this module
logger = setup_logging("feature_engineering")


def load_linkage_validation(validation_path: Path) -> Dict[str, Any]:
    """
    Load the linkage validation JSON file generated by the spatial join step.

    Args:
        validation_path: Path to linkage_validation.json

    Returns:
        Dictionary containing linkage status and metadata.
    """
    if not validation_path.exists():
        logger.error(f"Linkage validation file not found: {validation_path}")
        raise FileNotFoundError(f"Linkage validation file not found: {validation_path}")

    logger.info(f"Loading linkage validation from {validation_path}")
    return load_json_strict(validation_path)


def extract_raw_ndvi_timeseries(
    spatial_joined_data: pd.DataFrame,
    synthetic_mode: bool = False,
    noise_std: float = 0.1
) -> pd.DataFrame:
    """
    Extract raw NDVI time-series for each household.

    Logic:
    - Map survey_year + country to growing season months.
    - If synthetic_mode is True, generate synthetic NDVI time-series using
      a sinusoidal function with stochastic noise.
    - If real granules were used (not implemented in this synthetic-only path),
      extract from satellite granules.

    Args:
        spatial_joined_data: DataFrame containing spatially joined household data.
        synthetic_mode: Boolean flag indicating if synthetic data generation is active.
        noise_std: Standard deviation for stochastic noise in synthetic generation.

    Returns:
        DataFrame with columns: household_id, timestamp, ndvi_value.
    """
    logger.info("Extracting raw NDVI time-series...")

    if synthetic_mode:
        logger.info("Generating synthetic NDVI time-series (Structural Validation Mode).")
        return _generate_synthetic_ndvi_timeseries(spatial_joined_data, noise_std)
    else:
        # TODO: Implement real NDVI extraction from satellite granules
        # This path requires T016a (Real Sentinel-2 Collector) to be implemented
        # and actual granules to be present in data/raw/sentinel2/
        raise NotImplementedError(
            "Real NDVI extraction from satellite granules is not yet implemented. "
            "Please enable synthetic_mode=True for Structural Validation."
        )


def _generate_synthetic_ndvi_timeseries(
    df: pd.DataFrame,
    noise_std: float
) -> pd.DataFrame:
    """
    Generate synthetic NDVI time-series using a sinusoidal function with noise.

    Args:
        df: Input DataFrame with household data.
        noise_std: Standard deviation for noise.

    Returns:
        Long-format DataFrame with household_id, timestamp, ndvi_value.
    """
    if df.empty:
        logger.warning("Input DataFrame is empty. Returning empty NDVI timeseries.")
        return pd.DataFrame(columns=['household_id', 'timestamp', 'ndvi_value'])

    # Define growing season months (e.g., April to October for Malawi/Tanzania)
    # We will simulate monthly NDVI values for a 12-month cycle to ensure CV calculation is robust
    months = list(range(1, 13))
    month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    results = []

    for _, row in df.iterrows():
        household_id = row['household_id']
        # Use land_size to modulate the amplitude slightly for variety
        base_ndvi = 0.3 + (row.get('land_size', 1.0) * 0.05)
        # Ensure base is within realistic bounds [0.1, 0.8]
        base_ndvi = np.clip(base_ndvi, 0.1, 0.8)

        # Sinusoidal pattern: Peak in growing season (approx month 6-8)
        # Phase shift to align peak with July (month 7)
        phase = 2 * np.pi * (np.array(months) - 7) / 12
        seasonal_component = 0.4 * np.cos(phase)

        # Add stochastic noise
        noise = np.random.normal(0, noise_std, size=len(months))

        # Calculate NDVI
        ndvi_values = base_ndvi + seasonal_component + noise
        # Clip to valid NDVI range [-1, 1], though typically [0, 1] for vegetation
        ndvi_values = np.clip(ndvi_values, 0.0, 1.0)

        for m_idx, m in enumerate(months):
            results.append({
                'household_id': household_id,
                'timestamp': f"{row.get('survey_year', 2020)}-{m:02d}-01",
                'ndvi_value': round(ndvi_values[m_idx], 4)
            })

    ndvi_df = pd.DataFrame(results)
    logger.info(f"Generated synthetic NDVI time-series for {df['household_id'].nunique()} households.")
    return ndvi_df


def calculate_csa_index(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the CSA Index for each household.

    Logic:
    Sum binary practice indicators and extension_visits.
    Formula: CSA_Index = practice_mixed_farming + practice_terracing +
             practice_conservation_tillage + practice_agroforestry + extension_visits

    Args:
        df: Input DataFrame with practice columns.

    Returns:
        DataFrame with added 'CSA_Index' column.
    """
    logger.info("Calculating CSA Index...")

    practice_cols = [
        'practice_mixed_farming',
        'practice_terracing',
        'practice_conservation_tillage',
        'practice_agroforestry'
    ]

    # Ensure boolean columns are treated as integers (0/1)
    for col in practice_cols:
        if col in df.columns:
            df[col] = df[col].astype(int)
        else:
            logger.warning(f"Missing practice column: {col}, assuming 0")
            df[col] = 0

    # Handle extension_visits (ensure numeric)
    if 'extension_visits' in df.columns:
        df['extension_visits'] = pd.to_numeric(df['extension_visits'], errors='coerce').fillna(0)
    else:
        logger.warning("Missing extension_visits column, assuming 0")
        df['extension_visits'] = 0

    df['CSA_Index'] = (
        df['practice_mixed_farming'] +
        df['practice_terracing'] +
        df['practice_conservation_tillage'] +
        df['practice_agroforestry'] +
        df['extension_visits']
    )

    logger.info(f"CSA Index calculated. Range: [{df['CSA_Index'].min()}, {df['CSA_Index'].max()}]")
    return df


def calculate_stability_score(ndvi_timeseries: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the Stability Score based on NDVI time-series Coefficient of Variation (CV).

    Logic:
    1. Group by household_id.
    2. Compute standard deviation and mean of ndvi_value.
    3. CV = std / mean.
    4. Stability_Score = 1 / CV (or 0 if mean is 0 or CV is undefined).

    Args:
        ndvi_timeseries: DataFrame with household_id, timestamp, ndvi_value.

    Returns:
        DataFrame with household_id and Stability_Score.
    """
    logger.info("Calculating Stability Score from NDVI time-series...")

    if ndvi_timeseries.empty:
        logger.warning("NDVI timeseries is empty. Returning empty stability scores.")
        return pd.DataFrame(columns=['household_id', 'Stability_Score'])

    # Group by household
    stats = ndvi_timeseries.groupby('household_id')['ndvi_value'].agg(['mean', 'std']).reset_index()

    # Calculate CV
    # Avoid division by zero
    stats['cv'] = stats.apply(
        lambda row: row['std'] / row['mean'] if row['mean'] > 0 else 0.0,
        axis=1
    )

    # Stability Score = 1 / CV
    # Add a small epsilon to avoid division by zero if CV is 0
    epsilon = 1e-6
    stats['Stability_Score'] = 1.0 / (stats['cv'] + epsilon)

    # Handle infinite values if any
    stats['Stability_Score'] = np.where(
        np.isinf(stats['Stability_Score']),
        0.0,
        stats['Stability_Score']
    )

    # Select only necessary columns
    result = stats[['household_id', 'Stability_Score']]

    logger.info(f"Stability Score calculated for {len(result)} households.")
    return result


def derive_village_id(df: pd.DataFrame) -> pd.DataFrame:
    """
    Derive village_id by rounding coordinates to the nearest grid cell.

    Logic:
    village_id = f'{int(lat / grid_resolution_km)}_{int(lon / grid_resolution_km)}'

    Args:
        df: Input DataFrame with latitude and longitude.

    Returns:
        DataFrame with added 'village_id' column.
    """
    logger.info("Deriving Village IDs...")

    grid_res = constants.GRID_RESOLUTION_KM

    if 'latitude' not in df.columns or 'longitude' not in df.columns:
        raise FatalError("Missing latitude or longitude columns for village ID derivation.")

    df['village_id'] = df.apply(
        lambda row: f"{int(row['latitude'] / grid_res)}_{int(row['longitude'] / grid_res)}",
        axis=1
    )

    logger.info(f"Village IDs derived using grid resolution {grid_res} km.")
    return df


def perform_village_aggregation(df: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate dataset to village level.

    Logic:
    Group by village_id and calculate mean of CSA_Index and Stability_Score.

    Args:
        df: Input DataFrame with village_id, CSA_Index, Stability_Score.

    Returns:
        Aggregated DataFrame at village level.
    """
    logger.info("Performing village-level aggregation...")

    agg_cols = ['CSA_Index', 'Stability_Score']
    # Ensure columns exist
    for col in agg_cols:
        if col not in df.columns:
            raise FatalError(f"Missing column {col} for aggregation.")

    aggregated = df.groupby('village_id')[agg_cols].mean().reset_index()
    logger.info(f"Aggregated data to {len(aggregated)} villages.")
    return aggregated


def check_and_aggregate_if_needed(
    linkage_validation: Dict[str, Any],
    feature_engineered_df: pd.DataFrame
) -> Tuple[pd.DataFrame, bool]:
    """
    Check linkage validation status and trigger aggregation if needed.

    Logic:
    If linkage_percentage < 95% OR total_valid_households < 300,
    trigger village aggregation.

    Args:
        linkage_validation: Dictionary from linkage_validation.json.
        feature_engineered_df: DataFrame with feature engineered data.

    Returns:
        Tuple of (final_dataset, aggregation_triggered).
    """
    linkage_pct = linkage_validation.get('linkage_percentage', 100.0)
    total_households = linkage_validation.get('total_valid_households', 0)
    triggered = linkage_validation.get('triggered_aggregation', False)

    # Override based on current data if not explicitly set in validation
    if not triggered:
        if linkage_pct < 95.0 or total_households < 300:
            triggered = True
            logger.warning(f"Linkage criteria not met (Pct: {linkage_pct}, N: {total_households}). Triggering aggregation.")
        else:
            logger.info("Linkage criteria met. No aggregation needed.")

    if triggered:
        logger.info("Performing village aggregation...")
        aggregated_df = perform_village_aggregation(feature_engineered_df)
        return aggregated_df, True
    else:
        return feature_engineered_df, False


def main():
    """
    Main entry point for feature engineering pipeline.

    Expected inputs:
    - data/processed/spatial_joined_data.csv (from T017b)
    - data/logs/linkage_validation.json (from T017b)
    - data/processed/raw_ndvi_timeseries.parquet (Output of T018b step 1)

    Outputs:
    - data/processed/raw_ndvi_timeseries.parquet
    - data/processed/feature_engineered_data.csv
    - data/processed/analysis_dataset.csv (or _village_aggregated.csv)
    """
    logger.info("Starting Feature Engineering Pipeline.")

    # Define paths
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    data_raw = project_root / 'data' / 'raw'
    data_processed = project_root / 'data' / 'processed'
    data_logs = project_root / 'data' / 'logs'

    # Ensure directories exist
    data_processed.mkdir(parents=True, exist_ok=True)
    data_logs.mkdir(parents=True, exist_ok=True)

    # 1. Load Linkage Validation
    linkage_path = data_logs / 'linkage_validation.json'
    if not linkage_path.exists():
        logger.error(f"Linkage validation file missing: {linkage_path}")
        # Fallback for structural validation if file is missing but we are in synthetic mode
        # This might happen if T017b hasn't run yet in a fresh environment
        linkage_status = {
            'linkage_percentage': 100.0,
            'total_valid_households': 500,
            'triggered_aggregation': False,
            'data_source_type': 'Synthetic'
        }
        logger.warning("Using default linkage status (Synthetic Mode).")
    else:
        linkage_status = load_linkage_validation(linkage_path)

    # 2. Load Spatial Joined Data
    spatial_joined_path = data_processed / 'spatial_joined_data.csv'
    if not spatial_joined_path.exists():
        raise FatalError(f"Spatial joined data missing: {spatial_joined_path}")

    df_spatial = read_csv_strict(spatial_joined_path)
    logger.info(f"Loaded spatial joined data: {len(df_spatial)} records.")

    # 3. Extract Raw NDVI Time-Series (T018b Core Task)
    ndvi_timeseries_path = data_processed / 'raw_ndvi_timeseries.parquet'
    
    # Check if we need to regenerate or if it exists
    # For this task, we always regenerate to ensure consistency with current synthetic logic
    is_synthetic = linkage_status.get('data_source_type', 'Real') == 'Synthetic'
    
    df_ndvi = extract_raw_ndvi_timeseries(df_spatial, synthetic_mode=is_synthetic)
    write_parquet_strict(df_ndvi, ndvi_timeseries_path)
    logger.info(f"Saved raw NDVI time-series to {ndvi_timeseries_path}")

    # 4. Calculate Stability Score from NDVI
    df_stability = calculate_stability_score(df_ndvi)

    # 5. Merge Stability Score back to spatial data
    df_merged = pd.merge(df_spatial, df_stability, on='household_id', how='left')

    # 6. Calculate CSA Index
    df_merged = calculate_csa_index(df_merged)

    # 7. Derive Village ID
    df_merged = derive_village_id(df_merged)

    # 8. Check Aggregation Need
    final_df, aggregation_triggered = check_and_aggregate_if_needed(linkage_status, df_merged)

    # 9. Save Outputs
    feature_engineered_path = data_processed / 'feature_engineered_data.csv'
    write_csv_strict(final_df, feature_engineered_path)
    logger.info(f"Saved feature engineered data to {feature_engineered_path}")

    if aggregation_triggered:
        agg_path = data_processed / 'analysis_dataset_village_aggregated.csv'
        write_csv_strict(final_df, agg_path)
        # Copy to main analysis dataset
        analysis_path = data_processed / 'analysis_dataset.csv'
        write_csv_strict(final_df, analysis_path)
        logger.info(f"Saved aggregated analysis dataset to {analysis_path}")
    else:
        analysis_path = data_processed / 'analysis_dataset.csv'
        write_csv_strict(final_df, analysis_path)
        logger.info(f"Saved analysis dataset to {analysis_path}")

    logger.info("Feature Engineering Pipeline completed successfully.")
    return 0


if __name__ == '__main__':
    sys.exit(main())