"""
Unit test for the final validation report aggregator (T126).

The test creates a minimal set of required JSON/MD files in a temporary
directory, runs the ``aggregate_validation_results`` function, and checks
that the resulting dictionary contains the expected keys and that the
output file is written.

The test purposefully does **not** mock any data – it writes tiny but
syntactically correct JSON objects so that the aggregation logic can run
without raising errors.
"""

import json
import os
import shutil
import tempfile
from pathlib import Path

# Import the function directly from the implementation file.
from code.final_validation_report import aggregate_validation_results, main

def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f)

def _write_md(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def test_aggregate_validation_results_creates_correct_structure():
    # Create a temporary project‑like layout
    tmp_dir = Path(tempfile.mkdtemp())
    try:
        # Mimic the repository root structure expected by the script
        output_dir = tmp_dir / "output"
        output_dir.mkdir(parents=True, exist_ok=True)

        # Minimal but valid JSON artifacts
        _write_json(output_dir / "manifest.json", {"project": "test", "version": "0.1"})
        _write_json(output_dir / "metrics.json", {"rf": {"r2": 0.85}, "linear": {"r2": 0.60}})
        _write_json(output_dir / "pipeline_runtime.json", {"total_runtime_seconds": 123, "status": "pass"})
        _write_json(output_dir / "stability_rankings.json", {"run1": [], "run2": [], "run3": []})

        # Minimal markdown report (first three non‑empty lines will be captured)
        _write_md(output_dir / "report.md", "## HEA Yield Strength Report\\n\\nGenerated by pipeline.\\n\\n---\\n")

        # Patch the script's path resolution to treat ``tmp_dir`` as the repo root
        original_cwd = Path.cwd()
        os.chdir(tmp_dir)
        try:
            # Run the aggregation (this will also write the final JSON)
            result = aggregate_validation_results()
            # Verify top‑level keys
            expected_keys = {"manifest", "report_md", "metrics", "pipeline_runtime", "stability_rankings", "generated_at"}
            assert set(result.keys()) == expected_keys

            # Ensure the excerpt from the markdown contains the first line
            assert "HEA Yield Strength Report" in result["report_md"]["excerpt"]

            # Run the CLI entry point to ensure the file is written
            main()
            final_path = output_dir / "final_validation_report.json"
            assert final_path.is_file()
            with final_path.open() as f:
                loaded = json.load(f)
            assert loaded["manifest"]["project"] == "test"
        finally:
            os.chdir(original_cwd)
    finally:
        # Clean up the temporary directory
        shutil.rmtree(tmp_dir, ignore_errors=True)