import numpy as np
from typing import List, Dict, Any, Optional, Tuple
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_val_score
import logging
from data_models import RegressionModel
import pandas as pd
from scipy import stats as scipy_stats

logger = logging.getLogger(__name__)

def calculate_vif(X: np.ndarray, feature_names: Optional[List[str]] = None) -> Dict[str, float]:
    """
    Calculate Variance Inflation Factor (VIF) for each feature.
    
    Args:
        X: Feature matrix (n_samples, n_features)
        feature_names: Optional list of feature names for the output dictionary
    
    Returns:
        Dictionary mapping feature names (or indices) to VIF values.
    """
    if X.shape[1] == 0:
        return {}
    
    if feature_names is None:
        feature_names = [f"feature_{i}" for i in range(X.shape[1])]
    
    vif_data = {}
    for i in range(X.shape[1]):
        # Fit a linear regression of feature i against all other features
        y = X[:, i]
        X_other = np.delete(X, i, axis=1)
        
        if X_other.shape[1] == 0:
            # Only one feature, VIF is 1 by definition
            vif_data[feature_names[i]] = 1.0
            continue
        
        model = LinearRegression()
        model.fit(X_other, y)
        r_squared = model.score(X_other, y)
        
        # VIF = 1 / (1 - R^2)
        if r_squared >= 1.0:
            vif_data[feature_names[i]] = float('inf')
        else:
            vif_data[feature_names[i]] = 1.0 / (1.0 - r_squared)
    
    return vif_data

def run_regression(
    X: np.ndarray,
    y: np.ndarray,
    degree: int = 1,
    vif_threshold: float = 5.0,
    ridge_alpha: float = 1.0,
    use_intercept: bool = True
) -> Dict[str, Any]:
    """
    Run linear or polynomial regression with VIF checking and Ridge fallback.
    
    Args:
        X: Feature matrix (n_samples, n_features)
        y: Target vector (n_samples,)
        degree: Degree of polynomial features (1 for linear)
        vif_threshold: Threshold for VIF; if any feature exceeds this, switch to Ridge
        ridge_alpha: Regularization strength for Ridge regression
        use_intercept: Whether to include an intercept term
    
    Returns:
        Dictionary containing model results, coefficients, R², and metadata.
    """
    logger.info(f"Running regression with degree={degree}, vif_threshold={vif_threshold}")
    
    # Generate polynomial features if requested
    if degree > 1:
        poly = PolynomialFeatures(degree=degree, include_bias=False)
        X_poly = poly.fit_transform(X)
        feature_names = poly.get_feature_names_out()
        X_used = X_poly
    else:
        X_used = X
        feature_names = [f"x_{i}" for i in range(X.shape[1])]
    
    # Check VIF
    vif_results = calculate_vif(X_used, feature_names)
    max_vif = max(vif_results.values()) if vif_results else 0.0
    high_vif_features = [name for name, v in vif_results.items() if v > vif_threshold]
    
    model_type = "LinearRegression"
    if max_vif > vif_threshold:
        logger.warning(f"[VIF_ALERT] Max VIF {max_vif:.2f} exceeds threshold {vif_threshold}. "
                     f"High VIF features: {high_vif_features}. Switching to Ridge Regression with alpha={ridge_alpha}.")
        model = Ridge(alpha=ridge_alpha, fit_intercept=use_intercept)
        model_type = "Ridge"
    else:
        model = LinearRegression(fit_intercept=use_intercept)
    
    model.fit(X_used, y)
    
    # Calculate R²
    r2 = model.score(X_used, y)
    
    # Calculate p-values (approximate using t-test for coefficients)
    # This is a simplified approach; for rigorous stats, use statsmodels
    n = len(y)
    p_features = X_used.shape[1]
    residuals = y - model.predict(X_used)
    
    # Standard error of residuals
    if n - p_features - 1 > 0:
        mse = np.sum(residuals**2) / (n - p_features - 1)
    else:
        mse = 0.0
    
    # Standard errors of coefficients
    if use_intercept:
        # X_used includes bias column if generated by PolynomialFeatures with include_bias=True,
        # but we set include_bias=False, so we handle intercept separately if needed.
        # For simplicity, we assume the model handles intercept internally.
        # We need to compute (X^T X)^-1
        try:
            XtX_inv = np.linalg.inv(X_used.T @ X_used)
            se = np.sqrt(np.diag(XtX_inv) * mse)
        except np.linalg.LinAlgError:
            logger.warning("Could not invert X^T X. Setting p-values to 1.0.")
            se = np.ones_like(model.coef_)
            p_values = [1.0] * len(model.coef_)
        else:
            # t-statistics
            t_stats = model.coef_ / se
            # p-values (two-tailed)
            p_values = [2 * (1 - scipy_stats.t.cdf(abs(t), n - p_features - 1)) for t in t_stats]
    else:
        # No intercept
        try:
            XtX_inv = np.linalg.inv(X_used.T @ X_used)
            se = np.sqrt(np.diag(XtX_inv) * mse)
            t_stats = model.coef_ / se
            p_values = [2 * (1 - scipy_stats.t.cdf(abs(t), n - p_features)) for t in t_stats]
        except np.linalg.LinAlgError:
            p_values = [1.0] * len(model.coef_)
    
    # Construct result
    result = {
        "model_type": model_type,
        "degree": degree,
        "r_squared": float(r2),
        "coefficients": {
            "intercept": float(model.intercept_) if model.intercept_ is not None else 0.0,
            "features": {name: float(coef) for name, coef in zip(feature_names, model.coef_)}
        },
        "p_values": {name: float(p) for name, p in zip(feature_names, p_values)},
        "vif_check": {
            "threshold": vif_threshold,
            "max_vif": float(max_vif),
            "high_vif_features": high_vif_features,
            "switched_to_ridge": max_vif > vif_threshold
        },
        "ridge_alpha_used": ridge_alpha if max_vif > vif_threshold else None,
        "n_samples": int(n),
        "n_features": int(p_features)
    }
    
    logger.info(f"Regression complete. R²={r2:.4f}, Model={model_type}")
    return result

def run_cross_validation(
    X: np.ndarray,
    y: np.ndarray,
    degree: int = 1,
    cv_folds: int = 5,
    vif_threshold: float = 5.0,
    ridge_alpha: float = 1.0,
    scoring: str = 'r2'
) -> Dict[str, Any]:
    """
    Run k-fold cross-validation for the regression model.
    
    Args:
        X: Feature matrix (n_samples, n_features)
        y: Target vector (n_samples,)
        degree: Degree of polynomial features
        cv_folds: Number of folds for cross-validation
        vif_threshold: VIF threshold for Ridge fallback
        ridge_alpha: Regularization strength for Ridge
        scoring: Scoring metric for cross-validation (default 'r2')
    
    Returns:
        Dictionary containing CV results: mean score, std dev, and individual fold scores.
    """
    logger.info(f"Running {cv_folds}-fold cross-validation with degree={degree}")
    
    # Generate polynomial features if requested
    if degree > 1:
        poly = PolynomialFeatures(degree=degree, include_bias=False)
        X_poly = poly.fit_transform(X)
        X_used = X_poly
    else:
        X_used = X
    
    # Determine model type based on VIF (using full data for estimation)
    vif_results = calculate_vif(X_used)
    max_vif = max(vif_results.values()) if vif_results else 0.0
    
    if max_vif > vif_threshold:
        model = Ridge(alpha=ridge_alpha, fit_intercept=True)
        model_type = "Ridge"
    else:
        model = LinearRegression(fit_intercept=True)
        model_type = "LinearRegression"
    
    # Run cross-validation
    cv_scores = cross_val_score(model, X_used, y, cv=cv_folds, scoring=scoring)
    
    result = {
        "model_type": model_type,
        "degree": degree,
        "cv_folds": cv_folds,
        "scoring_metric": scoring,
        "mean_score": float(np.mean(cv_scores)),
        "std_score": float(np.std(cv_scores)),
        "fold_scores": [float(s) for s in cv_scores],
        "stability_flag": "UNSTABLE" if np.std(cv_scores) > 0.1 else "STABLE",
        "vif_check": {
            "threshold": vif_threshold,
            "max_vif": float(max_vif),
            "switched_to_ridge": max_vif > vif_threshold
        }
    }
    
    logger.info(f"CV complete. Mean {scoring}={result['mean_score']:.4f}, Std={result['std_score']:.4f}")
    return result
