"""
GLM Analysis for Coverage Robustness Study (T026).

Fits a Generalized Linear Model (GLM) with binomial link to test the effects
of epsilon and noise type on confidence interval coverage.

Formula: covered ~ epsilon + noise_type + epsilon:noise_type
"""
import os
import sys
import logging
import json
from pathlib import Path
from typing import Tuple, Optional, Dict, Any, List

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import glm as smf_glm

# Import project config for paths
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import get_artifact_path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_coverage_results() -> pd.DataFrame:
    """
    Load the coverage results CSV generated by T013c.

    Returns:
        pd.DataFrame: The loaded coverage results.

    Raises:
        FileNotFoundError: If the results file is missing.
        ValueError: If the file is empty or missing required columns.
    """
    results_path = get_artifact_path("coverage_results.csv")
    
    if not os.path.exists(results_path):
        raise FileNotFoundError(
            f"Results file not found at {results_path}. "
            "Did you run the main simulation (T013a/T042)?"
        )
    
    df = pd.read_csv(results_path)
    
    if df.empty:
        raise ValueError(f"Results file {results_path} is empty. No data to analyze.")
    
    required_cols = ['dataset', 'epsilon', 'noise_type', 'statistic', 'coverage_rate']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in {results_path}: {missing_cols}")
    
    logger.info(f"Loaded {len(df)} rows from {results_path}")
    return df

def prepare_glm_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepare data for GLM analysis.
    
    The GLM models binary outcomes (covered/not covered). Since we have
    coverage rates (proportions) and potentially counts, we use a binomial
    family with weights (number of trials).
    
    However, the raw data from T013c contains aggregated rates. We need to
    reconstruct the binary-like structure or use a quasibinomial/gaussian
    approximation if counts are unavailable.
    
    Strategy:
    1. If 'seed_count' (number of simulations) is available, use binomial family
       with 'coverage_rate' as the response and 'seed_count' as weights.
    2. If not, assume a fixed N_sim (from config) and proceed.
    3. Ensure 'epsilon' is numeric and 'noise_type' is categorical.
    
    Args:
        df: Raw coverage results DataFrame.
        
    Returns:
        pd.DataFrame: Prepared DataFrame for GLM.
    """
    # Work on a copy
    data = df.copy()
    
    # Ensure epsilon is numeric
    data['epsilon'] = pd.to_numeric(data['epsilon'], errors='coerce')
    data = data.dropna(subset=['epsilon'])
    
    # Ensure noise_type is categorical
    data['noise_type'] = data['noise_type'].astype('category')
    
    # Check for seed_count (number of trials per condition)
    if 'seed_count' in data.columns:
        trials = data['seed_count']
    else:
        # Fallback to a standard N_sim if not present, though T013c should write it
        # We assume N_sim=1000 based on T002/T013a spec if missing
        logger.warning("'seed_count' column missing. Assuming N_sim=1000 for weights.")
        trials = 1000
    
    # For statsmodels GLM with binomial family, the endog can be:
    # 1. Binary (0/1)
    # 2. Proportion (0-1) with weights=n_trials
    # We use the proportion approach.
    
    data['weights'] = trials
    
    # Filter out any rows where coverage_rate is exactly 0 or 1 if it causes convergence issues,
    # though statsmodels usually handles it. We keep them for now.
    
    logger.info(f"Prepared {len(data)} rows for GLM. Columns: {list(data.columns)}")
    return data

def fit_coverage_glm(data: pd.DataFrame) -> sm.GLMResultsWrapper:
    """
    Fit the GLM model: covered ~ epsilon + noise_type + epsilon:noise_type
    
    Args:
        data: Prepared DataFrame with 'coverage_rate', 'epsilon', 'noise_type', 'weights'.
        
    Returns:
        sm.GLMResultsWrapper: Fitted model results.
        
    Raises:
        ValueError: If the model fails to converge or data is insufficient.
    """
    if len(data) < 10:
        raise ValueError(f"Insufficient data for GLM: {len(data)} rows. Need at least 10.")
    
    formula = "coverage_rate ~ epsilon + C(noise_type) + epsilon:C(noise_type)"
    
    logger.info(f"Fitting GLM with formula: {formula}")
    
    try:
        # Use binomial family with weights
        model = smf_glm(
            formula=formula,
            data=data,
            family=sm.families.Binomial(),
            var_weights=data['weights']
        )
        results = model.fit()
        
        if not results.converged:
            logger.warning("GLM did not converge. Check data distribution or try quasibinomial.")
            # Try quasi to handle overdispersion if convergence fails
            logger.info("Retrying with Binomial (no convergence guarantee) or Quasibinomial if available.")
            # statsmodels doesn't have a direct QuasiBinomial in glm formula API easily without custom families,
            # so we proceed with the results we have, noting the warning.
        
        logger.info("GLM fitted successfully.")
        return results
        
    except Exception as e:
        logger.error(f"Failed to fit GLM: {e}")
        raise ValueError(f"GLM fitting failed: {e}")

def extract_glm_summary(results: sm.GLMResultsWrapper) -> Dict[str, Any]:
    """
    Extract key statistics from the GLM results.
    
    Args:
        results: Fitted GLM results.
        
    Returns:
        Dict containing p-values, coefficients, and residuals.
    """
    pvalues = results.pvalues
    params = results.params
    
    # Identify specific terms
    # Expected terms: Intercept, epsilon, C(noise_type)[T.Gaussian], epsilon:C(noise_type)[T.Gaussian]
    # (Assuming Laplace is reference or first alphabetically)
    
    p_val_epsilon = pvalues.get('epsilon', np.nan)
    
    # Noise type term
    noise_terms = [k for k in pvalues.index if 'C(noise_type)' in k and 'interaction' not in k]
    p_val_noise_type = pvalues[noise_terms[0]] if noise_terms else np.nan
    
    # Interaction term
    interaction_terms = [k for k in pvalues.index if 'epsilon:C(noise_type)' in k]
    p_val_interaction = pvalues[interaction_terms[0]] if interaction_terms else np.nan
    
    summary = {
        "p_value_epsilon": float(p_val_epsilon),
        "p_value_noise_type": float(p_val_noise_type),
        "p_value_interaction": float(p_val_interaction),
        "coefficients": {k: float(v) for k, v in params.items()},
        "deviance_residuals": results.deviance_residuals.tolist() if hasattr(results, 'deviance_residuals') else [],
        "converged": bool(results.converged),
        "aic": float(results.aic) if hasattr(results, 'aic') else None,
        "bic": float(results.bic) if hasattr(results, 'bic') else None
    }
    
    return summary

def run_glm_analysis() -> Tuple[sm.GLMResultsWrapper, Dict[str, Any]]:
    """
    Main entry point for T026.
    Loads data, fits GLM, and extracts summary.
    
    Returns:
        Tuple of (GLMResults, SummaryDict)
    """
    logger.info("Starting GLM Analysis (T026).")
    
    # 1. Load Data
    df = load_coverage_results()
    
    # 2. Prepare Data
    prepared_df = prepare_glm_data(df)
    
    # 3. Fit Model
    results = fit_coverage_glm(prepared_df)
    
    # 4. Extract Summary
    summary = extract_glm_summary(results)
    
    # 5. Save Summary to JSON (T027 dependency, but we do it here to ensure file exists)
    summary_path = get_artifact_path("glm_summary.json")
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    logger.info(f"GLM summary saved to {summary_path}")
    
    return results, summary

def main():
    """Script entry point."""
    try:
        results, summary = run_glm_analysis()
        print("GLM Analysis Complete.")
        print(f"P-value (epsilon): {summary['p_value_epsilon']:.4f}")
        print(f"P-value (noise_type): {summary['p_value_noise_type']:.4f}")
        print(f"P-value (interaction): {summary['p_value_interaction']:.4f}")
        return 0
    except Exception as e:
        logger.error(f"GLM Analysis failed: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
