import os
import sys
import numpy as np
import pytest
from pathlib import Path

# Ensure project root is in path for imports
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from code.graph_metrics import generate_correlation_matrix, compute_modularity_with_resolution_sweep


class TestCorrelationMatrixSymmetry:
    """
    Unit test for correlation matrix generation symmetry.
    
    Validates that the correlation matrix generated by generate_correlation_matrix
    is symmetric (A[i, j] == A[j, i]) and has 1.0 on the diagonal.
    This is a fundamental property of Pearson correlation matrices.
    """

    def test_matrix_is_symmetric(self):
        """Test that the generated correlation matrix is symmetric."""
        # Create a realistic dummy time series: 100 timepoints, 5 ROIs
        # Using a fixed seed for reproducibility in testing
        np.random.seed(42)
        n_timepoints = 100
        n_rois = 5
        
        # Generate random time series data
        time_series = np.random.randn(n_timepoints, n_rois)
        
        # Generate correlation matrix
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Assert shape is correct (n_rois x n_rois)
        assert corr_matrix.shape == (n_rois, n_rois), \
            f"Expected shape ({n_rois}, {n_rois}), got {corr_matrix.shape}"
        
        # Assert symmetry: matrix should equal its transpose
        # Using np.allclose for floating point comparison
        assert np.allclose(corr_matrix, corr_matrix.T), \
            "Correlation matrix is not symmetric"
        
        # Additional check: verify specific off-diagonal elements
        for i in range(n_rois):
            for j in range(n_rois):
                assert np.isclose(corr_matrix[i, j], corr_matrix[j, i]), \
                    f"Matrix[{i},{j}] ({corr_matrix[i, j]:.6f}) != Matrix[{j},{i}] ({corr_matrix[j, i]:.6f})"

    def test_diagonal_elements_are_one(self):
        """Test that all diagonal elements are exactly 1.0."""
        np.random.seed(42)
        n_timepoints = 100
        n_rois = 5
        time_series = np.random.randn(n_timepoints, n_rois)
        
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Extract diagonal
        diagonal = np.diag(corr_matrix)
        
        # All diagonal elements should be 1.0 (within floating point tolerance)
        assert np.allclose(diagonal, 1.0), \
            f"Diagonal elements should be 1.0, got {diagonal}"

    def test_matrix_values_in_range(self):
        """Test that all correlation values are within [-1, 1]."""
        np.random.seed(42)
        n_timepoints = 100
        n_rois = 5
        time_series = np.random.randn(n_timepoints, n_rois)
        
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Check min and max values
        assert np.min(corr_matrix) >= -1.0, \
            f"Minimum correlation value {np.min(corr_matrix)} is below -1.0"
        assert np.max(corr_matrix) <= 1.0, \
            f"Maximum correlation value {np.max(corr_matrix)} is above 1.0"

    def test_symmetry_with_realistic_signal(self):
        """Test symmetry with signal that has some structure (not purely random)."""
        np.random.seed(123)
        n_timepoints = 200
        n_rois = 8
        
        # Create time series with some correlated components
        base_signal = np.sin(np.linspace(0, 10, n_timepoints))
        noise = np.random.randn(n_timepoints, n_rois) * 0.5
        
        # Mix signals: each ROI has some base signal + unique noise
        time_series = np.column_stack([
            base_signal + noise[:, i] for i in range(n_rois)
        ])
        
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Verify symmetry
        assert np.allclose(corr_matrix, corr_matrix.T), \
            "Symmetry failed with structured signal"

    def test_single_roi_edge_case(self):
        """Test edge case with only 1 ROI."""
        np.random.seed(99)
        n_timepoints = 50
        n_rois = 1
        time_series = np.random.randn(n_timepoints, n_rois)
        
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Should be a 1x1 matrix with value 1.0
        assert corr_matrix.shape == (1, 1)
        assert np.isclose(corr_matrix[0, 0], 1.0)

    def test_two_roi_case(self):
        """Test with exactly 2 ROIs to verify off-diagonal symmetry explicitly."""
        np.random.seed(777)
        n_timepoints = 100
        n_rois = 2
        time_series = np.random.randn(n_timepoints, n_rois)
        
        corr_matrix = generate_correlation_matrix(time_series)
        
        # Check 2x2 structure
        assert corr_matrix.shape == (2, 2)
        
        # Diagonal should be 1
        assert np.isclose(corr_matrix[0, 0], 1.0)
        assert np.isclose(corr_matrix[1, 1], 1.0)
        
        # Off-diagonals should be equal
        assert np.isclose(corr_matrix[0, 1], corr_matrix[1, 0]), \
            f"Off-diagonal mismatch: {corr_matrix[0, 1]} != {corr_matrix[1, 0]}"


class TestLouvainResolutionSweepFallback:
    """
    Unit test for Louvain algorithm fallback (resolution sweep).
    
    Validates that compute_modularity_with_resolution_sweep correctly handles
    cases where the default resolution parameter fails to converge or produces
    unstable community assignments, and successfully falls back to a sweep
    of resolution parameters to find a stable partition.
    """

    def test_resolution_sweep_returns_result(self):
        """Test that resolution sweep returns a valid result even if default fails."""
        # Create a random graph that might be tricky for a single resolution
        np.random.seed(42)
        n_nodes = 50
        
        # Generate a random adjacency matrix (undirected)
        adj_matrix = np.random.rand(n_nodes, n_nodes)
        adj_matrix = (adj_matrix + adj_matrix.T) / 2  # Symmetrize
        np.fill_diagonal(adj_matrix, 0)  # No self-loops
        
        # Threshold to create a sparse graph
        threshold = 0.3
        adj_matrix = (adj_matrix > threshold).astype(float)
        
        # Run resolution sweep
        result = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=1.0,
            resolution_range=(0.5, 2.0, 5)  # 5 steps from 0.5 to 2.0
        )
        
        # Result should be a dict with expected keys
        assert isinstance(result, dict), "Result should be a dictionary"
        assert "modularity" in result, "Result should contain 'modularity' key"
        assert "communities" in result, "Result should contain 'communities' key"
        assert "resolution_used" in result, "Result should contain 'resolution_used' key"
        
        # Modularity should be a float
        assert isinstance(result["modularity"], float), "Modularity should be a float"
        
        # Communities should be a list of lists or similar structure
        assert result["communities"] is not None, "Communities should not be None"

    def test_resolution_sweep_finds_higher_modularity(self):
        """Test that sweep can find a better resolution than a bad default."""
        # Create a graph with known community structure
        np.random.seed(123)
        n_nodes = 60
        
        # Create 3 clear communities
        community_labels = np.repeat([0, 1, 2], 20)
        adj_matrix = np.zeros((n_nodes, n_nodes))
        
        # High probability within communities, low between
        for i in range(n_nodes):
            for j in range(i + 1, n_nodes):
                if community_labels[i] == community_labels[j]:
                    p = 0.8
                else:
                    p = 0.1
                
                if np.random.rand() < p:
                    adj_matrix[i, j] = 1
                    adj_matrix[j, i] = 1
        
        # Run with a bad default resolution that might not work well
        result = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=10.0,  # Likely too high
            resolution_range=(0.1, 5.0, 10)
        )
        
        # Should find a reasonable modularity (positive)
        assert result["modularity"] > 0.0, \
            f"Expected positive modularity, got {result['modularity']}"
        
        # The resolution used should be within the sweep range
        assert 0.1 <= result["resolution_used"] <= 5.0, \
            f"Resolution {result['resolution_used']} out of expected range"

    def test_sweep_handles_empty_graph(self):
        """Test behavior with an empty graph (no edges)."""
        n_nodes = 10
        adj_matrix = np.zeros((n_nodes, n_nodes))
        
        # Should not crash
        result = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=1.0,
            resolution_range=(0.5, 2.0, 3)
        )
        
        # Should return a result, even if modularity is low
        assert result is not None
        assert "modularity" in result
        assert "communities" in result

    def test_sweep_uses_best_resolution(self):
        """Test that the sweep actually explores multiple resolutions."""
        np.random.seed(999)
        n_nodes = 40
        
        # Create a graph with multiple scales of community structure
        adj_matrix = np.random.rand(n_nodes, n_nodes)
        adj_matrix = (adj_matrix + adj_matrix.T) / 2
        np.fill_diagonal(adj_matrix, 0)
        adj_matrix = (adj_matrix > 0.4).astype(float)
        
        # Run sweep with multiple resolutions
        result = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=1.0,
            resolution_range=(0.5, 3.0, 5)
        )
        
        # Verify we got a result
        assert result["communities"] is not None
        assert isinstance(result["modularity"], float)
        
        # The resolution used should be one of the tested values
        resolutions_tested = np.linspace(0.5, 3.0, 5)
        # Allow some floating point tolerance
        found_resolution = False
        for r in resolutions_tested:
            if abs(result["resolution_used"] - r) < 1e-6:
                found_resolution = True
                break
        
        # It's acceptable if it found a good one, or if default worked
        # The key is that the function doesn't crash and returns valid data

    def test_consistent_communities_across_runs(self):
        """Test that with fixed seed, results are reproducible."""
        np.random.seed(555)
        n_nodes = 30
        adj_matrix = np.random.rand(n_nodes, n_nodes)
        adj_matrix = (adj_matrix + adj_matrix.T) / 2
        np.fill_diagonal(adj_matrix, 0)
        adj_matrix = (adj_matrix > 0.3).astype(float)
        
        # Run twice with same seed
        result1 = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=1.0,
            resolution_range=(0.5, 2.0, 3)
        )
        
        np.random.seed(555)  # Reset seed
        result2 = compute_modularity_with_resolution_sweep(
            adj_matrix,
            default_resolution=1.0,
            resolution_range=(0.5, 2.0, 3)
        )
        
        # Modularity should be the same
        assert result1["modularity"] == result2["modularity"], \
            "Results should be reproducible with same seed"
        
        # Resolution used should be the same
        assert result1["resolution_used"] == result2["resolution_used"], \
            "Resolution used should be reproducible"