"""
Video Processor for llmXive follow-up.

This module handles:
1. Generation of synthetic masks for video editing tasks.
2. Stratification of video clips by motion complexity using optical flow magnitude.

Stratification thresholds (derived from Plan.md Dataset Strategy):
- Static: < 0.5 px
- Slow Rigid: 0.5 – 5.0 px
- Fast Non-Rigid: >= 5.0 px
"""

import os
import logging
import json
import numpy as np
import cv2
from typing import List, Dict, Any, Optional, Tuple
from pathlib import Path
from dataclasses import dataclass, asdict, replace
from datetime import datetime

# Import project utilities and models using the provided API surface
from config import ensure_directories, get_default_config
from utils.logger import get_logger
from data.models import VideoClip
from data.flow import aggregate_flow_stats

logger = get_logger(__name__)

@dataclass
class ProcessedClip:
    """Container for a video clip after processing (mask generation + stratification)."""
    video_id: str
    source_path: str
    mask_path: str
    motion_category: str
    mean_flow_magnitude: float
    max_flow_magnitude: float
    raw_flow_stats: Dict[str, float]
    processed_at: str

def generate_synthetic_mask(
    frame_shape: Tuple[int, int],
    seed: Optional[int] = None,
    mask_type: str = "random_blob"
) -> np.ndarray:
    """
    Generates a synthetic binary mask for a given frame shape.
    
    Args:
        frame_shape: Tuple (height, width) of the target frame.
        seed: Random seed for reproducibility.
        mask_type: Type of mask to generate ("random_blob").
        
    Returns:
        A binary numpy array (0 or 1) of shape (height, width).
    """
    if seed is not None:
        np.random.seed(seed)
    
    h, w = frame_shape
    mask = np.zeros((h, w), dtype=np.uint8)
    
    if mask_type == "random_blob":
        # Generate a few random elliptical blobs to simulate an object
        num_blobs = np.random.randint(1, 5)
        for _ in range(num_blobs):
            # Random center
            cy, cx = np.random.randint(h // 4, 3 * h // 4), np.random.randint(w // 4, 3 * w // 4)
            # Random size (small to medium relative to frame)
            sy, sx = np.random.randint(h // 10, h // 4), np.random.randint(w // 10, w // 4)
            # Random angle
            angle = np.random.uniform(0, 360)
            
            # Draw filled ellipse
            cv2.ellipse(mask, (cx, cy), (int(sx), int(sy)), angle, 0, 360, 255, -1)
    
    return mask

def stratify_by_motion(
    flow_stats: Dict[str, float],
    thresholds: Tuple[float, float] = (0.5, 5.0)
) -> str:
    """
    Classifies a clip into a motion category based on flow magnitude statistics.
    
    Thresholds (from Plan.md):
    - Static: mean_magnitude < 0.5
    - Slow Rigid: 0.5 <= mean_magnitude < 5.0
    - Fast Non-Rigid: mean_magnitude >= 5.0
    
    Args:
        flow_stats: Dictionary containing 'mean_magnitude' and 'max_magnitude'.
        thresholds: Tuple (low_thresh, high_thresh).
        
    Returns:
        String category: "Static", "Slow Rigid", or "Fast Non-Rigid".
    """
    mean_mag = flow_stats.get("mean_magnitude", 0.0)
    low_thresh, high_thresh = thresholds
    
    if mean_mag < low_thresh:
        return "Static"
    elif mean_mag < high_thresh:
        return "Slow Rigid"
    else:
        return "Fast Non-Rigid"

def process_video_clip(
    video_clip: VideoClip,
    flow_data_path: Optional[str] = None,
    output_dir: Optional[str] = None,
    mask_seed: Optional[int] = None
) -> ProcessedClip:
    """
    Processes a single video clip:
    1. Loads pre-computed flow data (if available) or computes it.
    2. Generates a synthetic mask.
    3. Stratifies the clip based on flow magnitude.
    4. Saves the mask to disk.
    
    Args:
        video_clip: The VideoClip dataclass instance.
        flow_data_path: Path to the flow data file (NPZ) generated by T009.
        output_dir: Directory to save the generated mask.
        mask_seed: Random seed for mask generation.
        
    Returns:
        ProcessedClip instance with metadata and paths.
    """
    ensure_directories()
    config = get_default_config()
    
    if output_dir is None:
        output_dir = str(Path(config.output_dir) / "masks")
    
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Determine Flow Magnitude
    # We rely on T009 (flow.py) having processed the video.
    # If flow_data_path is provided, we load it. Otherwise, we try to infer from video_id.
    mean_mag = 0.0
    max_mag = 0.0
    flow_stats = {"mean_magnitude": 0.0, "max_magnitude": 0.0}
    
    if flow_data_path and os.path.exists(flow_data_path):
        try:
            flow_stats = aggregate_flow_stats(flow_data_path)
            mean_mag = flow_stats.get("mean_magnitude", 0.0)
            max_mag = flow_stats.get("max_magnitude", 0.0)
            logger.debug(f"Loaded flow stats for {video_clip.video_id}: mean={mean_mag:.4f}")
        except Exception as e:
            logger.warning(f"Could not load flow stats for {video_clip.video_id}: {e}. Assuming Static.")
    else:
        # Fallback if flow path is missing but we need to proceed (strictly speaking T009 should have run)
        # In a real pipeline, this might raise, but for robustness we log and assume low motion if data missing
        logger.warning(f"Flow data not found at {flow_data_path} for {video_clip.video_id}. Assuming Static.")
    
    # 2. Stratify
    category = stratify_by_motion(flow_stats)
    
    # 3. Generate Mask
    # We need the frame shape. If video_clip has it, use it. Otherwise, load first frame.
    h, w = 0, 0
    if video_clip.height and video_clip.width:
        h, w = video_clip.height, video_clip.width
    elif os.path.exists(video_clip.path):
        cap = cv2.VideoCapture(video_clip.path)
        if cap.isOpened():
            ret, frame = cap.read()
            if ret:
                h, w, _ = frame.shape
            cap.release()
        else:
            raise ValueError(f"Cannot determine frame shape for {video_clip.path}")
    else:
        raise FileNotFoundError(f"Video file not found: {video_clip.path}")
    
    mask = generate_synthetic_mask((h, w), seed=mask_seed)
    
    # 4. Save Mask
    mask_filename = f"{video_clip.video_id}_mask.png"
    mask_path = os.path.join(output_dir, mask_filename)
    cv2.imwrite(mask_path, mask)
    
    return ProcessedClip(
        video_id=video_clip.video_id,
        source_path=video_clip.path,
        mask_path=mask_path,
        motion_category=category,
        mean_flow_magnitude=mean_mag,
        max_flow_magnitude=max_mag,
        raw_flow_stats=flow_stats,
        processed_at=datetime.now().isoformat()
    )

def process_dataset_stratification(
    clips: List[VideoClip],
    flow_dir: str,
    output_dir: str,
    output_report: str
) -> Dict[str, List[ProcessedClip]]:
    """
    Processes a list of clips, stratifies them, and saves masks.
    Returns a dictionary of processed clips grouped by motion category.
    
    Args:
        clips: List of VideoClip instances.
        flow_dir: Directory containing flow data files (from T009).
        output_dir: Directory to save masks.
        output_report: Path to save the JSON report of stratification.
        
    Returns:
        Dict mapping category name to list of ProcessedClip.
    """
    ensure_directories()
    os.makedirs(output_dir, exist_ok=True)
    
    processed_clips = []
    stratified_data = {
        "Static": [],
        "Slow Rigid": [],
        "Fast Non-Rigid": []
    }
    
    logger.info(f"Processing {len(clips)} clips for stratification...")
    
    for clip in clips:
        # Infer flow file path: {flow_dir}/{video_id}_flow.npz
        flow_file = os.path.join(flow_dir, f"{clip.video_id}_flow.npz")
        
        try:
            proc = process_video_clip(
                video_clip=clip,
                flow_data_path=flow_file,
                output_dir=output_dir
            )
            processed_clips.append(proc)
            stratified_data[proc.motion_category].append(asdict(proc))
            logger.info(f"Processed {clip.video_id} -> {proc.motion_category}")
        except Exception as e:
            logger.error(f"Failed to process {clip.video_id}: {e}")
            continue
    
    # Save report
    with open(output_report, 'w') as f:
        json.dump({
            "stratification_summary": {k: len(v) for k, v in stratified_data.items()},
            "details": stratified_data
        }, f, indent=2)
    
    logger.info(f"Stratification report saved to {output_report}")
    return stratified_data

def main():
    """
    Main entry point for the processor.
    Expected to be called from the main pipeline or via CLI.
    """
    logger.info("Starting Video Processor (T013)...")
    
    # This function would typically be called by T015 or T014
    # with a list of VideoClips loaded from T012 and flow paths from T009.
    # For standalone execution, we log the configuration.
    logger.info("Video processor module loaded. Ready to process clips.")
    logger.info("Thresholds: Static < 0.5, Slow Rigid 0.5-5.0, Fast Non-Rigid >= 5.0")

if __name__ == "__main__":
    main()