"""
T037: Save all analysis artifacts (plots, reports, SHAP values) to data/processed/analysis/.

This module orchestrates the final saving of all artifacts generated by the
interpretation and stability analysis pipeline. It ensures the analysis directory
exists, saves SHAP values (JSON/Parquet), stability reports (JSON), and copies
generated plots (PNG) to the designated output location.

Artifacts saved:
  - data/processed/analysis/shap_values.json (or .parquet)
  - data/processed/analysis/stability_report.json
  - data/processed/analysis/shap_summary_plot.png
  - data/processed/analysis/feature_importance_report.json
  - data/processed/analysis/metadata.json
"""
import os
import sys
import json
import logging
import pickle
import shutil
from pathlib import Path
from typing import Dict, Any, Optional

# Import project configuration and logging
from utils.config import get_config_summary
from utils.logging_config import get_logger

# Import functions from sibling modules that generate the artifacts
# Note: These functions are assumed to have generated the files in temporary
# or default locations, or we re-run the generation logic here to ensure
# the final save is atomic and correct.
# Based on the API surface provided:
# - models.generate_shap_report generates plots and reports
# - models.generate_stability_report generates stability JSON
# - models.interpret might have generated raw SHAP values

logger = get_logger(__name__)

def ensure_analysis_dir() -> Path:
    """Create the analysis output directory if it doesn't exist."""
    analysis_dir = Path("data/processed/analysis")
    analysis_dir.mkdir(parents=True, exist_ok=True)
    logger.info(f"Ensured analysis directory exists: {analysis_dir}")
    return analysis_dir

def save_shap_artifacts(
    shap_values: Optional[Dict[str, Any]] = None,
    shap_summary_plot_path: Optional[Path] = None,
    feature_report_path: Optional[Path] = None,
    analysis_dir: Optional[Path] = None
) -> None:
    """
    Save SHAP values, summary plot, and feature reports to the analysis directory.

    Args:
        shap_values: Dictionary containing SHAP values and feature names.
        shap_summary_plot_path: Path to the generated PNG plot.
        feature_report_path: Path to the generated feature importance report JSON.
        analysis_dir: Target directory for saving artifacts.
    """
    if analysis_dir is None:
        analysis_dir = ensure_analysis_dir()

    # Save SHAP values if provided
    if shap_values is not None:
        shap_json_path = analysis_dir / "shap_values.json"
        with open(shap_json_path, "w", encoding="utf-8") as f:
            # Convert numpy types to native Python types for JSON serialization
            def convert_numpy(obj):
                if hasattr(obj, 'tolist'):
                    return obj.tolist()
                if isinstance(obj, (np.ndarray,)):
                    return obj.tolist()
                return obj

            import numpy as np
            json.dump(shap_values, f, default=convert_numpy, indent=2)
        logger.info(f"Saved SHAP values to {shap_json_path}")

    # Move/Copy SHAP summary plot if provided
    if shap_summary_plot_path and shap_summary_plot_path.exists():
        dest_plot = analysis_dir / "shap_summary_plot.png"
        shutil.copy2(shap_summary_plot_path, dest_plot)
        logger.info(f"Copied SHAP summary plot to {dest_plot}")

    # Move/Copy feature report if provided
    if feature_report_path and feature_report_path.exists():
        dest_report = analysis_dir / "feature_importance_report.json"
        shutil.copy2(feature_report_path, dest_report)
        logger.info(f"Copied feature importance report to {dest_report}")

def save_stability_artifacts(
    stability_report_path: Optional[Path] = None,
    analysis_dir: Optional[Path] = None
) -> None:
    """
    Save stability analysis report to the analysis directory.

    Args:
        stability_report_path: Path to the generated stability report JSON.
        analysis_dir: Target directory for saving artifacts.
    """
    if analysis_dir is None:
        analysis_dir = ensure_analysis_dir()

    if stability_report_path and stability_report_path.exists():
        dest_stability = analysis_dir / "stability_report.json"
        shutil.copy2(stability_report_path, dest_stability)
        logger.info(f"Copied stability report to {dest_stability}")
    else:
        logger.warning("Stability report path not provided or file does not exist.")

def save_metadata(analysis_dir: Optional[Path] = None) -> None:
    """
    Save metadata about the analysis run (config, timestamps, etc.) to the analysis directory.

    Args:
        analysis_dir: Target directory for saving artifacts.
    """
    if analysis_dir is None:
        analysis_dir = ensure_analysis_dir()

    metadata = {
        "task_id": "T037",
        "description": "Save all analysis artifacts",
        "config_summary": get_config_summary(),
        "artifacts_saved": [
            "shap_values.json",
            "shap_summary_plot.png",
            "feature_importance_report.json",
            "stability_report.json"
        ]
    }

    metadata_path = analysis_dir / "metadata.json"
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    logger.info(f"Saved metadata to {metadata_path}")

def main() -> int:
    """
    Main entry point for T037: Save all analysis artifacts.

    This function assumes that T032 (interpret.py), T034a, T035, and T036
    have already run and produced their respective artifacts in default
    locations (e.g., data/processed/ or temp directories). This script
    collects them and moves them to the final `data/processed/analysis/` directory.

    Returns:
        int: 0 on success, 1 on failure.
    """
    try:
        analysis_dir = ensure_analysis_dir()

        # 1. Retrieve paths to artifacts generated by previous tasks.
        #    We assume standard output paths based on T032, T035, T036 specs.
        #    If the previous tasks wrote to specific locations, we copy from there.
        #    For robustness, we check common locations.

        # SHAP values (likely generated by interpret.py or generate_shap_report.py)
        # Assuming they might be in data/processed/ or a temp location.
        # If T032/033a saved them to data/processed/shap_values.json, we pick that up.
        shap_vals_path = Path("data/processed/shap_values.json")
        if not shap_vals_path.exists():
            # Fallback: check if interpret.py saved it elsewhere or we need to re-run logic
            # For this task, we assume the pipeline flow places it here or we skip if missing
            # but log a warning. In a real pipeline, T032 would ensure this exists.
            logger.warning("shap_values.json not found in data/processed/. Skipping SHAP values save.")
            shap_vals_data = None
        else:
            with open(shap_vals_path, "r") as f:
                shap_vals_data = json.load(f)

        # SHAP Summary Plot (generated by T036)
        shap_plot_path = Path("data/processed/shap_summary_plot.png")
        if not shap_plot_path.exists():
            logger.warning("shap_summary_plot.png not found. Skipping plot save.")

        # Feature Importance Report (generated by T036)
        feature_report_path = Path("data/processed/feature_importance_report.json")
        if not feature_report_path.exists():
            logger.warning("feature_importance_report.json not found. Skipping report save.")

        # Stability Report (generated by T035)
        stability_report_path = Path("data/processed/stability_report.json")
        if not stability_report_path.exists():
            # Check for failure file as well
            failed_path = Path("data/processed/stability_failed.json")
            if failed_path.exists():
                # If the pipeline failed stability, we still save the failure artifact
                # but the task T037 is about saving artifacts, so we save what we have.
                shutil.copy2(failed_path, analysis_dir / "stability_failed.json")
                logger.info("Saved stability failure artifact.")
            else:
                logger.warning("stability_report.json not found. Skipping stability save.")

        # 2. Execute save operations
        save_shap_artifacts(
            shap_values=shap_vals_data,
            shap_summary_plot_path=shap_plot_path,
            feature_report_path=feature_report_path,
            analysis_dir=analysis_dir
        )

        save_stability_artifacts(
            stability_report_path=stability_report_path,
            analysis_dir=analysis_dir
        )

        # 3. Save metadata
        save_metadata(analysis_dir)

        logger.info("T037 completed successfully: All analysis artifacts saved to data/processed/analysis/")
        return 0

    except Exception as e:
        logger.error(f"T037 failed with error: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())