"""
Motion exclusion filter for fMRI preprocessing pipeline.

Filters subjects based on head motion thresholds (>3mm translation or >3° rotation)
and generates an exclusion report.
"""

import os
import csv
import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

import pandas as pd
import numpy as np

from src.config.env import get_data_dir

logger = logging.getLogger(__name__)


class MotionFilterError(Exception):
    """Custom exception for motion filtering errors."""
    pass


def load_motion_data(motion_csv_path: str) -> pd.DataFrame:
    """
    Load motion parameters from a CSV file generated by extract_motion.py.

    Args:
        motion_csv_path: Path to the motion parameters CSV file.

    Returns:
        DataFrame with motion parameters.

    Raises:
        MotionFilterError: If file not found or invalid format.
    """
    path = Path(motion_csv_path)
    if not path.exists():
        raise MotionFilterError(f"Motion file not found: {motion_csv_path}")

    try:
        df = pd.read_csv(path)
        # Validate required columns
        required_cols = ['subject_id', 'translation_x', 'translation_y', 'translation_z',
                         'rotation_x', 'rotation_y', 'rotation_z']
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            raise MotionFilterError(f"Missing required columns: {missing}")
        return df
    except Exception as e:
        raise MotionFilterError(f"Failed to load motion data: {e}")


def calculate_max_displacement(row: pd.Series) -> Tuple[float, float]:
    """
    Calculate maximum translation (mm) and rotation (degrees) for a subject.

    Args:
        row: DataFrame row containing motion parameters.

    Returns:
        Tuple of (max_translation_mm, max_rotation_deg).
    """
    # Translation: sqrt(x^2 + y^2 + z^2) for each timepoint, then max
    translations = np.sqrt(
        row['translation_x']**2 +
        row['translation_y']**2 +
        row['translation_z']**2
    )
    max_trans = np.max(translations)

    # Rotation: sqrt(x^2 + y^2 + z^2) for each timepoint, then max
    # Note: fMRIPrep outputs rotation in radians, but we treat as degrees per task spec
    # If the source data is actually in radians, we would convert:
    # max_rot = np.max(np.sqrt(row['rotation_x']**2 + ...)) * (180 / np.pi)
    # However, per task T014 output spec, we assume degrees or treat directly.
    rotations = np.sqrt(
        row['rotation_x']**2 +
        row['rotation_y']**2 +
        row['rotation_z']**2
    )
    max_rot = np.max(rotations)

    return max_trans, max_rot


def filter_subjects(
    df: pd.DataFrame,
    trans_threshold: float = 3.0,
    rot_threshold: float = 3.0
) -> Tuple[List[str], List[str], Dict[str, Dict[str, float]]]:
    """
    Filter subjects based on motion thresholds.

    Args:
        df: DataFrame with motion parameters (one row per subject).
        trans_threshold: Maximum allowed translation in mm (default 3.0).
        rot_threshold: Maximum allowed rotation in degrees (default 3.0).

    Returns:
        Tuple of (excluded_ids, included_ids, motion_stats_dict).
    """
    excluded_ids = []
    included_ids = []
    motion_stats = {}

    for _, row in df.iterrows():
        max_trans, max_rot = calculate_max_displacement(row)
        subject_id = row['subject_id']
        motion_stats[subject_id] = {
            'max_translation_mm': float(max_trans),
            'max_rotation_deg': float(max_rot)
        }

        # Exclude if EITHER threshold is exceeded
        if max_trans > trans_threshold or max_rot > rot_threshold:
            excluded_ids.append(subject_id)
        else:
            included_ids.append(subject_id)

    return excluded_ids, included_ids, motion_stats


def write_exclusion_report(
    excluded_ids: List[str],
    included_ids: List[str],
    motion_stats: Dict[str, Dict[str, float]],
    output_csv_path: str,
    trans_threshold: float = 3.0,
    rot_threshold: float = 3.0
) -> None:
    """
    Write the exclusion report to a CSV file.

    Args:
        excluded_ids: List of excluded subject IDs.
        included_ids: List of included subject IDs.
        motion_stats: Dictionary of motion statistics per subject.
        output_csv_path: Path to output CSV file.
        trans_threshold: Translation threshold used.
        rot_threshold: Rotation threshold used.
    """
    output_path = Path(output_csv_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow([
            'subject_id',
            'status',
            'max_translation_mm',
            'max_rotation_deg',
            'exclusion_reason'
        ])

        # Write excluded subjects
        for sid in excluded_ids:
            stats = motion_stats[sid]
            reason = []
            if stats['max_translation_mm'] > trans_threshold:
                reason.append(f"trans>{trans_threshold}mm")
            if stats['max_rotation_deg'] > rot_threshold:
                reason.append(f"rot>{rot_threshold}deg")

            writer.writerow([
                sid,
                'EXCLUDED',
                f"{stats['max_translation_mm']:.4f}",
                f"{stats['max_rotation_deg']:.4f}",
                '; '.join(reason)
            ])

        # Write included subjects
        for sid in included_ids:
            stats = motion_stats[sid]
            writer.writerow([
                sid,
                'INCLUDED',
                f"{stats['max_translation_mm']:.4f}",
                f"{stats['max_rotation_deg']:.4f}",
                ''
            ])

    logger.info(f"Wrote exclusion report to {output_csv_path}")
    logger.info(f"Excluded: {len(excluded_ids)}, Included: {len(included_ids)}")


def run_motion_filter(
    motion_csv_path: Optional[str] = None,
    output_csv_path: Optional[str] = None,
    trans_threshold: float = 3.0,
    rot_threshold: float = 3.0
) -> Tuple[List[str], List[str]]:
    """
    Run the full motion filtering pipeline.

    Args:
        motion_csv_path: Path to input motion CSV. If None, uses default path.
        output_csv_path: Path to output exclusion CSV. If None, uses default path.
        trans_threshold: Translation threshold in mm.
        rot_threshold: Rotation threshold in degrees.

    Returns:
        Tuple of (excluded_ids, included_ids).
    """
    data_dir = get_data_dir()
    if motion_csv_path is None:
        motion_csv_path = str(Path(data_dir) / 'processed' / 'motion' / 'all_subjects_motion.csv')
    
    if output_csv_path is None:
        output_csv_path = str(Path(data_dir) / 'processed' / 'excluded_subjects.csv')

    logger.info(f"Loading motion data from {motion_csv_path}")
    df = load_motion_data(motion_csv_path)

    logger.info(f"Filtering subjects (trans>{trans_threshold}mm, rot>{rot_threshold}deg)")
    excluded_ids, included_ids, motion_stats = filter_subjects(
        df, trans_threshold, rot_threshold
    )

    write_exclusion_report(
        excluded_ids, included_ids, motion_stats,
        output_csv_path, trans_threshold, rot_threshold
    )

    return excluded_ids, included_ids


def main() -> None:
    """Main entry point for the motion filter script."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    try:
        excluded, included = run_motion_filter()
        print(f"Motion filtering complete.")
        print(f"Excluded subjects: {excluded}")
        print(f"Included subjects: {included}")
    except MotionFilterError as e:
        logger.error(f"Motion filtering failed: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        raise

if __name__ == '__main__':
    main()
