"""
Sensitivity Runner for User Story 3 (T028a, T028b, T028c).
Executes the intervention runner logic with specific checkpoint intervals.
"""
import os
import sys
import json
import argparse
import time
from pathlib import Path

# Add project root to path if not already present
project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from intervention.runner import run_intervention_execution, load_golden_set, generate_synthetic_traces_for_execution
from utils.seeds import set_seed
from utils.logging_config import get_logger

logger = get_logger(__name__)


def run_experiment_for_n(n: int, seed: int, output_path: str, model_path: str = None):
    """
    Run the sensitivity experiment for a specific checkpoint interval N.

    Args:
        n (int): The checkpoint interval (steps between state summaries).
        seed (int): Random seed for reproducibility.
        output_path (str): Path to write the results JSON.
        model_path (str): Path to the model file (optional, defaults to env var or config).
    """
    logger.info(f"Starting sensitivity experiment for N={n} with seed={seed}")
    set_seed(seed)

    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load or generate the golden set if needed for execution context
    # The runner expects a set of tasks to execute.
    # We use the synthetic traces generated by T015/T015b as the source of truth for execution.
    try:
        # Attempt to load the human annotated subset which serves as the execution source
        golden_path = Path("data/raw/human_annotated_subset.json")
        if golden_path.exists():
            with open(golden_path, 'r') as f:
                tasks = json.load(f)
            logger.info(f"Loaded {len(tasks)} tasks from {golden_path}")
        else:
            logger.warning("Golden set not found. Generating synthetic traces for execution.")
            tasks = generate_synthetic_traces_for_execution(num_tasks=10, seed=seed)
    except Exception as e:
        logger.error(f"Failed to load/generate tasks: {e}")
        raise

    results = []
    total_tasks = len(tasks)

    for idx, task in enumerate(tasks):
        task_id = task.get('trace_id', f"task_{idx}")
        logger.info(f"Executing task {idx+1}/{total_tasks}: {task_id} (N={n})")

        try:
            result = run_intervention_execution(
                task=task,
                checkpoint_interval=n,
                seed=seed,
                model_path=model_path
            )
            results.append({
                "task_id": task_id,
                "pass": result.passed,
                "steps": result.steps_executed,
                "checkpoint_interval": n,
                "memory_peak_mb": result.memory_peak_mb,
                "duration_seconds": result.duration_seconds
            })
        except Exception as e:
            logger.error(f"Task {task_id} failed during execution: {e}")
            # Record failure
            results.append({
                "task_id": task_id,
                "pass": False,
                "steps": 0,
                "checkpoint_interval": n,
                "memory_peak_mb": 0,
                "duration_seconds": 0,
                "error": str(e)
            })

    # Write results to disk
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)

    logger.info(f"Sensitivity experiment N={n} complete. Results written to {output_path}")
    return results


def main():
    parser = argparse.ArgumentParser(description="Run sensitivity experiment for a specific N")
    parser.add_argument('--n', type=int, required=True, help="Checkpoint interval N (e.g., 1, 3, 5)")
    parser.add_argument('--seed', type=int, default=42, help="Random seed")
    parser.add_argument('--output', type=str, required=True, help="Output JSON path")
    parser.add_argument('--model', type=str, default=None, help="Path to model GGUF file")

    args = parser.parse_args()

    run_experiment_for_n(
        n=args.n,
        seed=args.seed,
        output_path=args.output,
        model_path=args.model
    )


if __name__ == "__main__":
    main()