"""Utilities package for data handling and validation."""
from .io import (
    get_file_size_mb,
    calculate_md5,
    verify_checksum,
    check_memory_limit,
    load_parquet,
    load_csv,
    save_parquet,
    save_csv,
    process_in_batches,
    validate_memory_requirements,
)
from .memory_profiler import (
    start_profiling,
    stop_profiling,
    get_current_memory_mb,
    get_peak_memory_mb,
    check_memory_limit as profile_check_limit,
    force_gc,
    profile_training_block,
    save_memory_profile_log,
    main as memory_main,
)
from .schema_validator import (
    load_schema,
    validate_column_schema,
    validate_fingerprint_dimensions,
    validate_record_content,
    validate_dataset,
    save_validation_report,
)
from .validators import (
    DatasetRecord,
    DatasetSchema,
    MetricsRecord,
    SplitRatiosRecord,
    OutputRecord,
    OutputSchema,
    load_schema as load_validator_schema,
    validate_column_schema as validate_col_schema,
    validate_fingerprint_dimensions as validate_fp_dims,
    validate_record_content as validate_rec_content,
    validate_dataset as validate_ds,
    validate_output_file,
    validate_dataset_file,
    save_validation_report as save_val_report,
)

__all__ = [
    "get_file_size_mb",
    "calculate_md5",
    "verify_checksum",
    "check_memory_limit",
    "load_parquet",
    "load_csv",
    "save_parquet",
    "save_csv",
    "process_in_batches",
    "validate_memory_requirements",
    "start_profiling",
    "stop_profiling",
    "get_current_memory_mb",
    "get_peak_memory_mb",
    "profile_check_limit",
    "force_gc",
    "profile_training_block",
    "save_memory_profile_log",
    "memory_main",
    "load_schema",
    "validate_column_schema",
    "validate_fingerprint_dimensions",
    "validate_record_content",
    "validate_dataset",
    "save_validation_report",
    "DatasetRecord",
    "DatasetSchema",
    "MetricsRecord",
    "SplitRatiosRecord",
    "OutputRecord",
    "OutputSchema",
    "load_validator_schema",
    "validate_col_schema",
    "validate_fp_dims",
    "validate_rec_content",
    "validate_ds",
    "validate_output_file",
    "validate_dataset_file",
    "save_val_report",
]
