import os
import sys
import json
import time
import psutil
import logging
import numpy as np
import pandas as pd
from statsmodels.formula.api import mixedlm
from statsmodels.regression.mixed_linear_model import MixedLMResults
from pathlib import Path

# Import from sibling modules as per API surface
from config_loader import load_config
from logging_config import get_logger, log_step, log_artifact
from utils import set_global_seed

# Define custom exception
class FeasibilityError(Exception):
    """Raised when resource constraints (time/memory) are exceeded."""
    pass

def load_processed_data():
    """
    Load the preprocessed EEG and behavioral data from disk.
    Expects data to be in data/processed/ as generated by preprocess.py.
    """
    config = load_config()
    data_dir = Path(config.get('paths', {}).get('processed_data', 'data/processed'))
    
    # Look for the primary processed dataset
    # Assuming preprocess.py outputs a consolidated CSV or parquet file
    # We will look for 'epochs_with_behavior.csv' or similar
    candidates = [
        data_dir / 'epochs_with_behavior.csv',
        data_dir / 'processed_data.csv',
        data_dir / 'mfn_epochs.csv'
    ]
    
    data_path = None
    for candidate in candidates:
        if candidate.exists():
            data_path = candidate
            break
    
    if data_path is None:
        # Fallback: try to find any csv in the directory
        csv_files = list(data_dir.glob('*.csv'))
        if csv_files:
            data_path = csv_files[0]
        else:
            raise FileNotFoundError(f"No processed data found in {data_dir}")
    
    logger = get_logger(__name__)
    logger.info(f"Loading processed data from {data_path}")
    
    df = pd.read_csv(data_path)
    
    # Ensure required columns exist
    required_cols = ['participant_id', 'error_magnitude', 'mean_amplitude', 'electrode']
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        # If columns are missing, we might need to aggregate or pivot.
        # For now, we assume the preprocessing pipeline (T014) created this structure.
        # If not, we attempt to infer or raise a specific error.
        logger.warning(f"Missing expected columns: {missing}. Attempting to proceed with available columns.")
    
    return df

def fit_linear_mixed_effects_model(df, formula="mean_amplitude ~ error_magnitude + (1|participant_id)"):
    """
    Fit a Linear Mixed-Effects Model using statsmodels.
    
    Args:
        df: DataFrame containing the data.
        formula: Statsmodels formula string.
        
    Returns:
        model_results: Fitted model results object.
    """
    logger = get_logger(__name__)
    logger.info(f"Fitting LME model with formula: {formula}")
    
    try:
        # Handle potential NaNs in the specific columns used
        model_df = df.dropna(subset=['mean_amplitude', 'error_magnitude', 'participant_id'])
        
        if len(model_df) == 0:
            raise ValueError("No valid data points remaining after dropping NaNs for LME fitting.")
        
        model = mixedlm.from_formula(formula, groups="participant_id", data=model_df)
        result = model.fit()
        
        logger.info("Model fitting successful.")
        return result
    except Exception as e:
        logger.error(f"Model fitting failed: {str(e)}")
        raise

def run_sensitivity_sweep(df, thresholds=None, output_path=None):
    """
    Perform a sensitivity sweep on the minimum error magnitude threshold.
    
    For each threshold:
    1. Filter error events where error_magnitude >= threshold.
    2. Refit the primary LME model.
    3. Record the correlation coefficient (approximated by fixed effect slope t-stat or correlation) 
       and the p-value of the error_magnitude predictor.
    
    Args:
        df: Full processed DataFrame.
        thresholds: List of float thresholds to test. Defaults to [5, 10, 15, 20].
        output_path: Path to save the results CSV.
        
    Returns:
        results_df: DataFrame with columns [threshold, correlation, p_value, n_samples].
    """
    logger = get_logger(__name__)
    log_step("Starting sensitivity sweep analysis")
    
    if thresholds is None:
        thresholds = [5.0, 10.0, 15.0, 20.0]
    
    results = []
    
    for thresh in thresholds:
        logger.info(f"Processing threshold: {thresh}")
        
        # Filter data
        filtered_df = df[df['error_magnitude'] >= thresh].copy()
        
        if len(filtered_df) < 10:
            logger.warning(f"Threshold {thresh} resulted in too few samples ({len(filtered_df)}). Skipping or recording NaN.")
            results.append({
                'threshold': thresh,
                'correlation': np.nan,
                'p_value': np.nan,
                'n_samples': len(filtered_df)
            })
            continue
        
        try:
            # Fit model
            # Note: We use the standard formula from the primary analysis
            model_result = fit_linear_mixed_effects_model(
                filtered_df, 
                formula="mean_amplitude ~ error_magnitude + (1|participant_id)"
            )
            
            # Extract statistics for 'error_magnitude'
            # The summary table in statsmodels mixedlm is accessed via model_result.params and model_result.pvalues
            # We need to find the row corresponding to 'error_magnitude'
            
            # Get the parameter estimates
            params = model_result.params
            pvalues = model_result.pvalues
            
            # The index of the params series includes the variable name
            # Usually formatted as 'error_magnitude' or 'Group var' etc.
            # We look for the exact name
            if 'error_magnitude' in params.index:
                slope = params['error_magnitude']
                p_val = pvalues['error_magnitude']
                
                # Calculate correlation coefficient as a proxy for effect size direction/magnitude
                # Since LME slope is not exactly Pearson r, we calculate Pearson r on the residuals or raw data for reporting
                # per the task requirement "record correlation coefficient".
                # We calculate simple Pearson correlation between error_magnitude and mean_amplitude for the filtered subset.
                corr, _ = scipy.stats.pearsonr(filtered_df['error_magnitude'], filtered_df['mean_amplitude'])
                
                results.append({
                    'threshold': thresh,
                    'correlation': corr,
                    'p_value': p_val,
                    'n_samples': len(filtered_df)
                })
            else:
                logger.warning(f"'error_magnitude' not found in model parameters for threshold {thresh}.")
                results.append({
                    'threshold': thresh,
                    'correlation': np.nan,
                    'p_value': np.nan,
                    'n_samples': len(filtered_df)
                })
                
        except Exception as e:
            logger.error(f"Failed to fit model for threshold {thresh}: {str(e)}")
            results.append({
                'threshold': thresh,
                'correlation': np.nan,
                'p_value': np.nan,
                'n_samples': len(filtered_df),
                'error': str(e)
            })
    
    results_df = pd.DataFrame(results)
    
    # Save to output path if provided
    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        results_df.to_csv(output_path, index=False)
        log_artifact(f"Sensitivity sweep results saved to {output_path}")
    
    log_step("Sensitivity sweep completed")
    return results_df

def main():
    """
    Main entry point for the analysis module.
    Orchestrates data loading, model fitting, and sensitivity analysis.
    """
    logger = get_logger(__name__)
    start_time = time.time()
    process = psutil.Process(os.getpid())
    initial_memory = process.memory_info().rss
    
    try:
        # 1. Load Configuration
        config = load_config()
        set_global_seed(config.get('random_seed', 42))
        
        # 2. Load Data
        df = load_processed_data()
        
        # 3. Run Sensitivity Sweep (Task T023)
        # Output path from config or default
        output_path = config.get('paths', {}).get('sensitivity_results', 'results/diagnostics/sensitivity_summary.csv')
        
        results = run_sensitivity_sweep(df, output_path=output_path)
        
        # 4. Feasibility Check (SC-005)
        end_time = time.time()
        runtime_seconds = end_time - start_time
        current_memory = process.memory_info().rss
        peak_memory_mb = (current_memory - initial_memory) / (1024 * 1024)
        
        if runtime_seconds > 21600 or peak_memory_mb > 7168:
            raise FeasibilityError(f"Resource limits exceeded: Runtime={runtime_seconds}s, Memory={peak_memory_mb}MB")
        
        # 5. Save Feasibility Report (T018 requirement, executed here if not done elsewhere)
        feasibility_report = {
            "runtime_seconds": runtime_seconds,
            "peak_memory_mb": peak_memory_mb,
            "status": "completed"
        }
        feasibility_path = Path("results/diagnostics/feasibility_report.json")
        feasibility_path.parent.mkdir(parents=True, exist_ok=True)
        with open(feasibility_path, 'w') as f:
            json.dump(feasibility_report, f, indent=2)
        
        logger.info(f"Analysis complete. Feasibility report saved to {feasibility_path}")
        
    except FeasibilityError as e:
        logger.critical(f"Feasibility check failed: {str(e)}")
        sys.exit(1)
    except Exception as e:
        logger.critical(f"Analysis failed: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    main()
