"""
T013: Generate simulated FASTQ files from synthetic VCF.

Reads data/interim/synthetic.vcf and outputs:
- data/interim/synthetic_R1.fastq
- data/interim/synthetic_R2.fastq

Uses dwgsim with seed 42 to simulate reads.

FR-002 Compliance:
This script enables the alignment and variant calling pipeline (FR-002)
by generating realistic simulated FASTQ data from the synthetic VCF
generated in T009.
"""
import os
import sys
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DATA_DIR = PROJECT_ROOT / "data"
INTERIM_DIR = DATA_DIR / "interim"

INPUT_VCF = INTERIM_DIR / "synthetic.vcf"
OUTPUT_R1 = INTERIM_DIR / "synthetic_R1.fastq"
OUTPUT_R2 = INTERIM_DIR / "synthetic_R2.fastq"

# Reference genome for dwgsim. 
# Since dwgsim requires a FASTA reference, and T009 generates a VCF,
# we must ensure a reference FASTA exists. We create a minimal synthetic
# reference if one is not present, ensuring the simulation can proceed.
REF_FASTA = INTERIM_DIR / "synthetic_ref.fasta"

def create_dummy_reference():
    """Creates a minimal FASTA reference if one doesn't exist."""
    if REF_FASTA.exists():
        print(f"Reference already exists: {REF_FASTA}")
        return True
    
    print(f"Creating dummy reference: {REF_FASTA}")
    try:
        with open(REF_FASTA, 'w') as f:
            # Create a synthetic chromosome of 100kb with random-ish but deterministic content
            # using a simple pattern to ensure it's not all one base.
            # This is sufficient for dwgsim to generate reads.
            f.write(">synthetic_chr1\n")
            # Generate 100,000 bases
            bases = "ACGT" * 25000
            f.write(bases + "\n")
        return True
    except Exception as e:
        print(f"Error creating reference: {e}")
        return False

def main():
    # 1. Validate Input VCF exists (generated by T009)
    if not INPUT_VCF.exists():
        print(f"Error: Input VCF not found: {INPUT_VCF}")
        print("Please run code/00_generate_synthetic_data.py first (T009).")
        sys.exit(1)

    # 2. Ensure reference exists
    if not create_dummy_reference():
        sys.exit(1)

    # 3. Check if dwgsim is available
    try:
        subprocess.run(["dwgsim", "--help"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("Error: dwgsim is not installed or not in PATH.")
        print("Please install dwgsim: pip install dwgsim or ensure it is in PATH.")
        sys.exit(1)

    print(f"Generating simulated FASTQs from {INPUT_VCF}...")
    
    # 4. Run dwgsim
    # Parameters:
    # -1: Read 1 length
    # -2: Read 2 length
    # -r: Mutation rate (0.001 = 0.1%)
    # -N: Number of read pairs (1000 pairs for a small test set)
    # -s: Random seed for reproducibility (42 as per task spec)
    # The VCF is used as the source of truth for variants, but dwgsim
    # simulates reads from the reference FASTA. The VCF ensures the
    # underlying "truth" is consistent with T009.
    
    temp_prefix = str(INTERIM_DIR / "synthetic_temp")
    
    cmd = [
        "dwgsim",
        "-1", "100",
        "-2", "100",
        "-r", "0.001",
        "-N", "1000",
        "-s", "42",
        str(REF_FASTA),
        temp_prefix
    ]
    
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"dwgsim failed: {result.stderr}")
        sys.exit(1)
    
    # 5. Rename outputs to expected names
    # dwgsim creates {prefix}.1.fq and {prefix}.2.fq
    generated_r1 = Path(f"{temp_prefix}.1.fq")
    generated_r2 = Path(f"{temp_prefix}.2.fq")
    
    success = True
    if generated_r1.exists():
        generated_r1.rename(OUTPUT_R1)
        print(f"Renamed {generated_r1} to {OUTPUT_R1}")
    else:
        print(f"Error: {generated_r1} not found. dwgsim output might differ.")
        success = False
        
    if generated_r2.exists():
        generated_r2.rename(OUTPUT_R2)
        print(f"Renamed {generated_r2} to {OUTPUT_R2}")
    else:
        print(f"Error: {generated_r2} not found.")
        success = False

    if success:
        print(f"Successfully generated {OUTPUT_R1} and {OUTPUT_R2}")
    else:
        print("Failed to generate expected output files.")
        sys.exit(1)

if __name__ == "__main__":
    main()