import os
import logging
import numpy as np
from typing import List, Dict, Tuple, Optional, Any
from pathlib import Path
from dataclasses import dataclass, field

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

@dataclass
class DistortionConfig:
    """Configuration for distortion generation."""
    snr_range: Tuple[float, float] = (-20.0, 20.0)
    rt60_range: Tuple[float, float] = (0.1, 1.5)
    num_points: int = 10
    snr_step: Optional[float] = None
    rt60_step: Optional[float] = None

@dataclass
class DistortionVector:
    """A single distortion vector defined by SNR and RT60."""
    snr: float
    rt60: float
    id: str = field(init=False)
    
    def __post_init__(self):
        self.id = f"snr_{self.snr:.2f}_rt60_{self.rt60:.2f}"

class DistortionEngine:
    """Engine to generate and apply distortion vectors."""
    
    def __init__(self, config: DistortionConfig):
        self.config = config
        self.vectors: List[DistortionVector] = []
    
    def generate_vectors(self) -> List[DistortionVector]:
        """Generate a grid of distortion vectors."""
        snr_start, snr_end = self.config.snr_range
        rt60_start, rt60_end = self.config.rt60_range
        
        if self.config.snr_step is None:
            snr_step = (snr_end - snr_start) / self.config.num_points
        else:
            snr_step = self.config.snr_step
            
        if self.config.rt60_step is None:
            rt60_step = (rt60_end - rt60_start) / self.config.num_points
        else:
            rt60_step = self.config.rt60_step
        
        vectors = []
        snr_values = np.arange(snr_start, snr_end + snr_step/2, snr_step)
        rt60_values = np.arange(rt60_start, rt60_end + rt60_step/2, rt60_step)
        
        for snr in snr_values:
            for rt60 in rt60_values:
                vectors.append(DistortionVector(snr=float(snr), rt60=float(rt60)))
        
        self.vectors = vectors
        logger.info(f"Generated {len(vectors)} distortion vectors.")
        return vectors

def generate_all_distortion_vectors(config: DistortionConfig) -> List[DistortionVector]:
    """Helper to generate vectors from a config."""
    engine = DistortionEngine(config)
    return engine.generate_vectors()

def validate_distortion_coverage(vectors: List[DistortionVector], expected_count: int) -> bool:
    """Validate that the number of vectors matches expectations."""
    if len(vectors) < expected_count:
        logger.warning(f"Expected at least {expected_count} vectors, got {len(vectors)}.")
        return False
    return True

def check_distortion_coverage_applied(
    applied_vectors: List[DistortionVector],
    expected_vectors: List[DistortionVector],
    output_path: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Validator for Distortion Coverage (FR-001).
    
    Compares the set of distortion vectors that were successfully applied
    against the set of expected vectors generated by the engine.
    
    Args:
        applied_vectors: List of DistortionVector objects that were actually applied.
        expected_vectors: List of DistortionVector objects that were supposed to be applied.
        output_path: Optional path to write a detailed JSON report.
    
    Returns:
        A dictionary containing:
            - 'total_expected': int
            - 'total_applied': int
            - 'total_skipped': int
            - 'skipped_ids': List[str]
            - 'applied_ids': List[str]
            - 'coverage_ratio': float
    """
    applied_ids = set(v.id for v in applied_vectors)
    expected_ids = set(v.id for v in expected_vectors)
    
    skipped_ids = list(expected_ids - applied_ids)
    applied_ids_list = sorted(list(applied_ids))
    
    total_expected = len(expected_vectors)
    total_applied = len(applied_vectors)
    total_skipped = len(skipped_ids)
    
    coverage_ratio = total_applied / total_expected if total_expected > 0 else 0.0
    
    report = {
        "total_expected": total_expected,
        "total_applied": total_applied,
        "total_skipped": total_skipped,
        "coverage_ratio": coverage_ratio,
        "applied_ids": applied_ids_list,
        "skipped_ids": sorted(skipped_ids),
        "details": {
            "missing_vectors": [
                {"id": v.id, "snr": v.snr, "rt60": v.rt60}
                for v in expected_vectors if v.id in skipped_ids
            ]
        }
    }
    
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            import json
            json.dump(report, f, indent=2)
        logger.info(f"Distortion coverage report written to {output_path}")
    
    if total_skipped > 0:
        logger.warning(f"Distortion Coverage Warning: {total_skipped}/{total_expected} scenarios were skipped.")
        logger.warning(f"Skipped IDs: {skipped_ids[:10]}{'...' if len(skipped_ids) > 10 else ''}")
    else:
        logger.info("Distortion Coverage Check: All expected scenarios were successfully applied.")
        
    return report

def main():
    """Test the distortion engine."""
    config = DistortionConfig(num_points=5)
    vectors = generate_all_distortion_vectors(config)
    for v in vectors[:3]:
        print(v)
    validate_distortion_coverage(vectors, 5)
    
    # Test the new coverage validator with a mock scenario
    # Simulate that one vector failed to apply
    applied_subset = vectors[:-1] 
    report = check_distortion_coverage_applied(
        applied_subset, 
        vectors, 
        output_path=Path("data/derived/distortion_coverage_report.json")
    )
    print(f"Coverage Ratio: {report['coverage_ratio']:.2%}")

if __name__ == "__main__":
    main()