"""
Cox Proportional Hazards analysis for convergence time on small-world graphs.

Implements survival analysis using lifelines to test the interaction between
loss type (InfoNCE vs CE) and graph beta (rewiring probability) on convergence steps.

Handles censored data where runs reached MAX_EPOCHS without converging.
"""
import pandas as pd
import numpy as np
import sys
import os
from pathlib import Path
from typing import Dict, Any, Optional, Tuple
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from utils import MAX_EPOCHS, CONVERGENCE_THRESHOLD

# Constants
DATA_FILE = "data/processed/convergence_logs.csv"
OUTPUT_FILE = "data/analysis/cox_results.json"
COX_MODEL_FILE = "data/analysis/cox_model_fitted.pkl"

def load_convergence_data() -> pd.DataFrame:
    """
    Load the aggregated convergence data from the CSV generated by T033.
    
    Returns:
        DataFrame with columns: steps_to_convergence, loss_type, beta, event
        
    Raises:
        FileNotFoundError: If the convergence logs CSV does not exist.
        ValueError: If required columns are missing.
    """
    data_path = Path(DATA_FILE)
    if not data_path.exists():
        raise FileNotFoundError(
            f"Convergence data file not found: {DATA_FILE}. "
            "Run T033 (aggregate_training_runs) first."
        )
    
    df = pd.read_csv(data_path)
    
    required_cols = {'steps_to_convergence', 'loss_type', 'beta', 'convergence_status'}
    if not required_cols.issubset(df.columns):
        missing = required_cols - set(df.columns)
        raise ValueError(f"Missing required columns in {DATA_FILE}: {missing}")
    
    return df

def prepare_cox_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepare the DataFrame for Cox PH analysis.
    
    - Renames 'convergence_status' to 'event' (1 if converged, 0 if censored).
    - Ensures 'loss_type' is categorical for proper encoding.
    - Validates that 'event' is binary (0 or 1).
    
    Args:
        df: Raw DataFrame from load_convergence_data.
        
    Returns:
        DataFrame ready for CoxPHFitter.fit().
    """
    cox_df = df.copy()
    
    # Map convergence_status to event: "converged" -> 1, "censored" -> 0
    cox_df['event'] = cox_df['convergence_status'].map({
        'converged': 1,
        'censored': 0
    })
    
    # Verify mapping succeeded
    if cox_df['event'].isna().any():
        unique_statuses = df['convergence_status'].unique()
        raise ValueError(f"Unknown convergence_status values found: {unique_statuses}")
    
    # Ensure loss_type is categorical
    cox_df['loss_type'] = cox_df['loss_type'].astype('category')
    
    # Select only columns needed for the model
    # Formula: steps_to_convergence ~ C(loss_type) * beta
    # We need: T (time), E (event), loss_type, beta
    return cox_df[['steps_to_convergence', 'event', 'loss_type', 'beta']]

def run_cox_ph(df: pd.DataFrame) -> Tuple[CoxPHFitter, Dict[str, Any]]:
    """
    Fit the Cox Proportional Hazards model with interaction term.
    
    Formula: steps_to_convergence ~ C(loss_type) * beta
    
    Args:
        df: Prepared DataFrame with 'event' column.
        
    Returns:
        Tuple of (fitted model, results dictionary with p-values and coefficients)
    """
    # Initialize the fitter
    cph = CoxPHFitter()
    
    try:
        # Fit the model
        # Using the formula interface for clarity of interaction term
        cph.fit(df, duration_col='steps_to_convergence', event_col='event')
    except Exception as e:
        # If fitting fails, try a simpler approach without formula string
        # to handle potential issues with categorical encoding in lifelines
        print(f"Initial fit failed: {e}. Attempting manual encoding...")
        
        # Manual encoding: One-hot encode loss_type
        df_encoded = pd.get_dummies(df, columns=['loss_type'], drop_first=True)
        
        # Identify the columns for the model
        # We need: steps_to_convergence, event, beta, and one-hot loss_type columns
        model_cols = ['steps_to_convergence', 'event', 'beta']
        loss_cols = [col for col in df_encoded.columns if col.startswith('loss_type_')]
        model_cols.extend(loss_cols)
        
        # Create interaction terms manually
        for col in loss_cols:
            interaction_col = f"{col}_beta"
            df_encoded[interaction_col] = df_encoded[col] * df_encoded['beta']
            model_cols.append(interaction_col)
        
        # Ensure event is present
        if 'event' not in model_cols:
            model_cols.append('event')
            
        cph.fit(df_encoded, duration_col='steps_to_convergence', event_col='event')
    
    # Extract results
    results = {
        'concordance_index': cph.concordance_index_,
        'coefficients': cph.params_.to_dict(),
        'p_values': cph.summary['p'].to_dict(),
        'hazard_ratios': cph.hazard_ratios_.to_dict(),
        'log_likelihood': cph.log_likelihood_,
        'formula': "steps_to_convergence ~ C(loss_type) * beta"
    }
    
    # Specifically extract the interaction term p-value
    # The interaction term in the formula C(loss_type) * beta will be named something like:
    # "loss_type_InfoNCE:beta" or similar depending on encoding
    interaction_key = None
    for col in results['p_values'].keys():
        if ':' in col and 'beta' in col:
            interaction_key = col
            break
    
    if interaction_key:
        results['interaction_p_value'] = results['p_values'][interaction_key]
        results['interaction_term'] = interaction_key
    else:
        # Fallback: look for any term containing both loss and beta
        for col in results['p_values'].keys():
            if ('loss' in col.lower() or 'ce' in col.lower() or 'infonce' in col.lower()) and 'beta' in col:
                interaction_key = col
                results['interaction_p_value'] = results['p_values'][interaction_key]
                results['interaction_term'] = interaction_key
                break
    
    if not interaction_key:
        raise RuntimeError("Could not identify interaction term in Cox model results.")
    
    return cph, results

def save_results(results: Dict[str, Any], model: CoxPHFitter) -> None:
    """
    Save the Cox PH analysis results to JSON and the model to pickle.
    
    Args:
        results: Dictionary of analysis results.
        model: Fitted CoxPHFitter instance.
    """
    output_path = Path(OUTPUT_FILE)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Save JSON results
    import json
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2, default=str)
    
    # Save model (optional, for inspection)
    model_path = Path(COX_MODEL_FILE)
    import pickle
    with open(model_path, 'wb') as f:
        pickle.dump(model, f)
    
    print(f"Cox PH results saved to {OUTPUT_FILE}")
    print(f"Model saved to {COX_MODEL_FILE}")

def main() -> None:
    """Main entry point for Cox PH analysis."""
    print("Starting Cox Proportional Hazards Analysis...")
    
    try:
        # Load data
        df = load_convergence_data()
        print(f"Loaded {len(df)} records from {DATA_FILE}")
        
        # Prepare data
        cox_df = prepare_cox_dataframe(df)
        print(f"Prepared DataFrame with {len(cox_df)} samples")
        
        # Run analysis
        model, results = run_cox_ph(cox_df)
        
        # Display key findings
        print("\n--- Cox PH Results ---")
        print(f"Concordance Index: {results['concordance_index']:.4f}")
        print(f"Interaction Term: {results['interaction_term']}")
        print(f"Interaction P-value: {results['interaction_p_value']:.6f}")
        
        # Save results
        save_results(results, model)
        
        print("\nCox PH analysis completed successfully.")
        
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Data validation error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error during Cox PH analysis: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
