"""
Integration test for FR-002: Extracted fields exist for > 95% of valid pages.

This test verifies that the extraction logic successfully populates required fields
for the vast majority of valid HTML pages in the corpus.
"""
import json
import logging
import sys
from pathlib import Path
from typing import List, Dict, Any

# Add project root to path for imports
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from code.src.audit.extractor import extract_all, write_summaries_to_json
from code.src.utils.logger import get_default_logger

# Configure logger
logger = get_default_logger(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# Required fields defined in the ABTestSummary model / FR-002 requirements
REQUIRED_FIELDS = [
    "url",
    "domain",
    "test_type",
    "outcome_type",
    "baseline_n",
    "treatment_n",
    "baseline_conversions",
    "treatment_conversions",
    "reported_p_value",
    "reported_effect_size"
]

def load_real_corpus_json(corpus_path: Path) -> List[Dict[str, Any]]:
    """
    Load the real extracted summaries from the corpus.
    Expects the file generated by the extractor pipeline (T020).
    """
    if not corpus_path.exists():
        raise FileNotFoundError(f"Corpus file not found at {corpus_path}. "
                                "Please run the extraction pipeline (T020) first.")
    
    with open(corpus_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Handle both list and dict with 'summaries' key
    if isinstance(data, dict):
        return data.get("summaries", [])
    return data

def calculate_field_coverage(summaries: List[Dict[str, Any]]) -> Dict[str, float]:
    """
    Calculates the percentage of summaries that have all required fields populated.
    """
    if not summaries:
        return {"coverage": 0.0, "total": 0, "valid": 0}

    valid_count = 0
    for summary in summaries:
        if not isinstance(summary, dict):
            continue
        
        all_present = True
        for field in REQUIRED_FIELDS:
            if field not in summary or summary[field] is None:
                all_present = False
                break
        
        if all_present:
            valid_count += 1

    coverage = (valid_count / len(summaries)) * 100
    return {
        "coverage": coverage,
        "total": len(summaries),
        "valid": valid_count
    }

def run_extractor_accuracy_test():
    """
    Main test execution for FR-002.
    """
    logger.info("Starting FR-002 Verification: Extracted fields coverage check.")
    
    # Define paths relative to project root
    # The extractor (T020) writes to output/extracted_summaries.json
    # We look for it in the standard output location
    output_dir = project_root / "output"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    corpus_path = output_dir / "extracted_summaries.json"
    
    # If the file doesn't exist, we try to extract from the raw data if available
    # This ensures the test is self-contained if the pipeline was run previously
    if not corpus_path.exists():
        logger.warning(f"Corpus not found at {corpus_path}. Attempting to re-extract from data/raw...")
        raw_dir = project_root / "data" / "raw"
        if not raw_dir.exists():
            logger.error("Raw data directory not found. Cannot run extraction test.")
            raise FileNotFoundError("Raw data directory missing. Run T019 first.")
        
        # Run extraction on the raw directory
        summaries = extract_all(raw_dir, logger)
        write_summaries_to_json(summaries, corpus_path, logger)
        logger.info(f"Extraction complete. Wrote {len(summaries)} summaries to {corpus_path}")
    
    # Load the real data
    summaries = load_real_corpus_json(corpus_path)
    logger.info(f"Loaded {len(summaries)} summaries from corpus.")
    
    if len(summaries) == 0:
        logger.error("No summaries found in corpus. Test cannot proceed.")
        raise ValueError("Corpus is empty.")

    # Calculate coverage
    results = calculate_field_coverage(summaries)
    
    logger.info(f"Coverage Results: {results['valid']}/{results['total']} ({results['coverage']:.2f}%)")
    
    # Assert threshold (FR-002: > 95%)
    threshold = 95.0
    if results["coverage"] >= threshold:
        logger.info(f"SUCCESS: Field coverage ({results['coverage']:.2f}%) meets threshold ({threshold}%).")
        return True
    else:
        logger.error(f"FAILURE: Field coverage ({results['coverage']:.2f}%) is below threshold ({threshold}%).")
        raise AssertionError(
            f"FR-002 Verification Failed: Extracted fields coverage is {results['coverage']:.2f}%, "
            f"which is below the required > 95% threshold. "
            f"Valid: {results['valid']}, Total: {results['total']}"
        )

def main():
    try:
        success = run_extractor_accuracy_test()
        if success:
            print("T036 PASSED")
            sys.exit(0)
        else:
            print("T036 FAILED")
            sys.exit(1)
    except Exception as e:
        logger.exception("Test execution failed with exception")
        print(f"T036 FAILED: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
