"""
T022: Implement logic to compare MSE of interaction model vs. additive binary null hypothesis.

This script computes the Mean Squared Error (MSE) for two models:
1. Interaction Model: Uses features + interaction terms (generated in T021a).
2. Additive Binary Null Hypothesis: Uses only main effects (no interactions).

It calculates the percentage reduction in MSE. If the reduction is > 10%,
it confirms cooperative effects. Otherwise, it raises a warning.

Dependencies:
- T021a (generate_interaction_terms.py): Produces data/processed/interaction_terms.csv
- T021b (regression.py): Logic for fitting linear models
"""
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, List, Tuple

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from code.config import DATA_PROCESSED_PATH, get_logger
from code.errors import ValidationError

# Configure logging
logger = get_logger(__name__)

def load_interaction_terms() -> pd.DataFrame:
    """Load the interaction terms dataset generated by T021a."""
    path = DATA_PROCESSED_PATH / "interaction_terms.csv"
    if not path.exists():
        raise FileNotFoundError(f"Interaction terms file not found at {path}. "
                                "Ensure T021a has been executed.")
    logger.info(f"Loading interaction terms from {path}")
    return pd.read_csv(path)

def prepare_data(df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
    """
    Prepare features (X) and target (y) from the interaction terms dataframe.
    
    Assumes the last column is the target (segregation_energy or similar) 
    and all preceding columns are features.
    """
    # Identify target column (usually 'segregation_energy' or the last column)
    # Based on T021a output description: columns [Cr, Mo, Cr_Mo, ...]
    # We assume the target is explicitly named or the last column.
    # Let's assume the target is 'segregation_energy' based on context, 
    # or fallback to the last column if not present.
    target_col = 'segregation_energy'
    if target_col not in df.columns:
        if df.shape[1] > 0:
            target_col = df.columns[-1]
            logger.warning(f"Target column '{target_col}' not found, using last column: {target_col}")
        else:
            raise ValueError("DataFrame is empty or has no target column.")
    
    y = df[target_col].values
    X = df.drop(columns=[target_col]).values
    
    return X, y

def fit_model(X: np.ndarray, y: np.ndarray, use_interactions: bool = True) -> Tuple[LinearRegression, float]:
    """
    Fit a linear regression model.
    
    Args:
        X: Feature matrix.
        y: Target vector.
        use_interactions: If True, uses all columns in X. 
                          If False, assumes X contains only main effects (no interaction columns).
                          Note: This function assumes the caller has already filtered X appropriately
                          or that the 'use_interactions' flag is handled by slicing X.
                          For T022, we will slice X in the caller to separate main effects from interactions.
    
    Returns:
        Tuple of (fitted model, MSE on training data)
    """
    model = LinearRegression()
    model.fit(X, y)
    y_pred = model.predict(X)
    mse = mean_squared_error(y, y_pred)
    return model, mse

def split_features(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split the dataframe into main effects and interaction effects.
    
    Assumes interaction columns contain underscores (e.g., 'Cr_Mo') 
    and main effects do not (e.g., 'Cr', 'Mo'), or follows the naming convention from T021a.
    """
    # Identify target
    target_col = 'segregation_energy'
    if target_col not in df.columns:
        target_col = df.columns[-1]
    
    feature_cols = [c for c in df.columns if c != target_col]
    
    main_effects_cols = []
    interaction_cols = []
    
    for col in feature_cols:
        # Heuristic: Interaction terms usually have underscores in this project's convention (Cr_Mo)
        # Main effects are typically single element symbols or simple names.
        if '_' in col:
            interaction_cols.append(col)
        else:
            main_effects_cols.append(col)
    
    if not interaction_cols:
        logger.warning("No interaction columns found. The dataset might not have interaction terms.")
    
    X_main = df[main_effects_cols].values
    X_full = df[feature_cols].values
    
    return X_main, X_full

def compute_mse_reduction() -> Dict[str, Any]:
    """
    Main logic to compute MSE reduction and determine if cooperative effects exist.
    """
    # 1. Load Data
    df = load_interaction_terms()
    X_main, X_full = split_features(df)
    _, y = prepare_data(df)
    
    if len(y) == 0:
        raise ValueError("No data points found for regression.")
    
    logger.info(f"Loaded {len(y)} data points. Main effects: {X_main.shape[1]}, Full features: {X_full.shape[1]}")

    # 2. Fit Additive Binary Null Hypothesis (Main Effects Only)
    logger.info("Fitting Additive Binary Null Hypothesis model (Main Effects only)...")
    _, mse_null = fit_model(X_main, y, use_interactions=False)
    logger.info(f"Null Model MSE: {mse_null:.6f}")

    # 3. Fit Interaction Model (Main Effects + Interactions)
    logger.info("Fitting Interaction Model (Main Effects + Interactions)...")
    _, mse_interaction = fit_model(X_full, y, use_interactions=True)
    logger.info(f"Interaction Model MSE: {mse_interaction:.6f}")

    # 4. Calculate Reduction
    if mse_null == 0:
        # Avoid division by zero; if null is perfect, reduction is 0%
        reduction_percent = 0.0
    else:
        reduction_percent = ((mse_null - mse_interaction) / mse_null) * 100.0

    logger.info(f"MSE reduction: {reduction_percent:.2f}% (Threshold: 10%)")

    # 5. Determine Result
    threshold = 10.0
    cooperative_detected = reduction_percent > threshold
    
    result = {
        "mse_null_model": float(mse_null),
        "mse_interaction_model": float(mse_interaction),
        "mse_reduction_percent": float(reduction_percent),
        "threshold_percent": threshold,
        "cooperative_effects_detected": cooperative_detected,
        "num_samples": len(y),
        "num_main_effects": X_main.shape[1],
        "num_interactions": X_full.shape[1] - X_main.shape[1]
    }

    if not cooperative_detected:
        logger.warning(f"Threshold not met. MSE reduction ({reduction_percent:.2f}%) is not greater than {threshold}%. "
                       "Cooperative effects not confirmed statistically by this metric.")
    else:
        logger.info("Cooperative effects confirmed: Interaction model significantly reduces error.")

    return result

def save_results(result: Dict[str, Any], output_path: Path):
    """Save the results to a JSON file."""
    with open(output_path, 'w') as f:
        json.dump(result, f, indent=2)
    logger.info(f"Results saved to {output_path}")

def main():
    """Entry point for T022."""
    logger.info("Starting T022: MSE Reduction Analysis for Cooperative Effects")
    
    try:
        result = compute_mse_reduction()
        
        output_file = DATA_PROCESSED_PATH / "mse_reduction_analysis.json"
        save_results(result, output_file)
        
        logger.info("T022 completed successfully.")
        return 0
        
    except Exception as e:
        logger.error(f"T022 failed: {e}", exc_info=True)
        raise

if __name__ == "__main__":
    sys.exit(main())