"""
Task T019: Tune semantic matching threshold on pilot data.

Iterates cosine similarity threshold across a fine-grained range to maximize
agreement rate between automated semantic matching and human expert labels.

Dependencies:
- data/pilot/pilot_ground_truth_labels.jsonl (Required)
- data/pilot/pilot_traces.jsonl (Generated by pilot_study.py)

Output:
- data/pilot/tuned_threshold.json
"""
import argparse
import json
import logging
import sys
from pathlib import Path
from typing import List, Dict, Tuple, Any, Optional

import numpy as np
from sentence_transformers import SentenceTransformer

# Import project utilities
from utils.logging_config import get_logger, setup_root_logger

# Constants
THRESHOLD_START = 0.0
THRESHOLD_END = 1.0
THRESHOLD_STEP = 0.01
MODEL_NAME = "all-MiniLM-L6-v2"
PILOT_TRACES_PATH = Path("data/pilot/pilot_traces.jsonl")
PILOT_LABELS_PATH = Path("data/pilot/pilot_ground_truth_labels.jsonl")
OUTPUT_PATH = Path("data/pilot/tuned_threshold.json")

logger = get_logger(__name__)


def load_pilot_traces(path: Path) -> List[Dict[str, Any]]:
    """Load pilot traces from JSONL file."""
    if not path.exists():
        raise FileNotFoundError(f"Pilot traces not found at {path}. Run pilot_study.py first.")
    
    traces = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                traces.append(json.loads(line))
    
    if not traces:
        raise ValueError(f"No traces found in {path}")
    
    logger.info(f"Loaded {len(traces)} pilot traces from {path}")
    return traces


def load_pilot_labels(path: Path) -> List[Dict[str, Any]]:
    """Load pilot ground truth labels from JSONL file."""
    if not path.exists():
        raise FileNotFoundError(
            f"Pilot ground truth labels not found at {path}. "
            "Ensure human experts have annotated the pilot set (Manual Step)."
        )
    
    labels = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                labels.append(json.loads(line))
    
    if not labels:
        raise ValueError(f"No labels found in {path}")
    
    logger.info(f"Loaded {len(labels)} pilot labels from {path}")
    return labels


def align_traces_and_labels(traces: List[Dict], labels: List[Dict]) -> List[Tuple[Dict, Dict]]:
    """Align traces with their corresponding human labels using task_id."""
    label_map = {label["task_id"]: label for label in labels}
    aligned = []
    
    for trace in traces:
        task_id = trace.get("task_id")
        if task_id not in label_map:
            logger.warning(f"Task {task_id} in traces has no corresponding label. Skipping.")
            continue
        
        aligned.append((trace, label_map[task_id]))
    
    if not aligned:
        raise ValueError("No aligned trace-label pairs found. Check task_id matching.")
    
    logger.info(f"Aligned {len(aligned)} trace-label pairs")
    return aligned


def compute_agreement(
    threshold: float,
    aligned_pairs: List[Tuple[Dict, Dict]],
    model: SentenceTransformer
) -> Tuple[int, int, float]:
    """
    Compute agreement between automated semantic match and human labels at a given threshold.
    
    Returns:
        Tuple of (agreements, total, agreement_rate)
    """
    agreements = 0
    total = len(aligned_pairs)
    
    for trace, label in aligned_pairs:
        # Extract constraint text from task
        constraint_text = trace.get("constraint", "")
        # Extract the relevant segment from the trace (e.g., the generated CoT)
        trace_text = trace.get("cot_trace", "")
        
        if not constraint_text or not trace_text:
            # Cannot compute match if text is missing
            # Treat as disagreement if human says "Yes" but we can't match
            # or agreement if human says "No" and we can't match (assuming no mention)
            # For robustness, we skip pairs with missing text in agreement calculation
            # or count as disagreement if human expects a match.
            # Here, we skip to avoid bias, but log it.
            logger.debug(f"Skipping pair {label['task_id']}: missing text")
            total -= 1
            continue
        
        # Encode texts
        embeddings = model.encode([constraint_text, trace_text], convert_to_numpy=True)
        embedding_constraint = embeddings[0]
        embedding_trace = embeddings[1]
        
        # Compute cosine similarity
        similarity = np.dot(embedding_constraint, embedding_trace) / (
            np.linalg.norm(embedding_constraint) * np.linalg.norm(embedding_trace)
        )
        
        # Automated decision
        automated_mention = similarity >= threshold
        
        # Human label (1 = Yes/Mention, 0 = No/No Mention)
        human_mention = label.get("constraint_mention", -1)
        
        if human_mention not in [0, 1]:
            logger.warning(f"Invalid human label for {label['task_id']}: {human_mention}. Skipping.")
            total -= 1
            continue
        
        # Check agreement
        if automated_mention == (human_mention == 1):
            agreements += 1
    
    if total == 0:
        return 0, 0, 0.0
    
    return agreements, total, agreements / total


def tune_threshold(
    aligned_pairs: List[Tuple[Dict, Dict]],
    model: SentenceTransformer
) -> Tuple[float, float, List[Dict]]:
    """
    Iterate thresholds to find the one maximizing agreement rate.
    
    Returns:
        Tuple of (optimal_threshold, max_agreement_rate, results_history)
    """
    best_threshold = 0.0
    best_agreement = -1.0
    results_history = []
    
    logger.info(f"Tuning threshold from {THRESHOLD_START} to {THRESHOLD_END} step {THRESHOLD_STEP}")
    
    current = THRESHOLD_START
    while current <= THRESHOLD_END + 1e-9:  # Small epsilon for float comparison
        agreements, total, rate = compute_agreement(current, aligned_pairs, model)
        
        if total == 0:
            history_entry = {
                "threshold": current,
                "agreements": 0,
                "total": 0,
                "rate": 0.0,
                "status": "skipped_no_data"
            }
        else:
            history_entry = {
                "threshold": current,
                "agreements": agreements,
                "total": total,
                "rate": rate,
                "status": "evaluated"
            }
            
            if rate > best_agreement:
                best_agreement = rate
                best_threshold = current
        
        results_history.append(history_entry)
        current += THRESHOLD_STEP
    
    logger.info(f"Best threshold: {best_threshold:.2f} with agreement rate: {best_agreement:.4f}")
    return best_threshold, best_agreement, results_history


def save_results(
    best_threshold: float,
    best_agreement: float,
    results_history: List[Dict],
    output_path: Path
):
    """Save the tuning results to JSON."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    result_data = {
        "best_threshold": best_threshold,
        "best_agreement_rate": best_agreement,
        "total_evaluated_thresholds": len(results_history),
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "results_history": results_history
    }
    
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result_data, f, indent=2)
    
    logger.info(f"Saved tuning results to {output_path}")


def main():
    """Main entry point for threshold tuning."""
    setup_root_logger()
    
    parser = argparse.ArgumentParser(description="Tune semantic matching threshold on pilot data.")
    parser.add_argument(
        "--traces",
        type=str,
        default=str(PILOT_TRACES_PATH),
        help="Path to pilot traces JSONL"
    )
    parser.add_argument(
        "--labels",
        type=str,
        default=str(PILOT_LABELS_PATH),
        help="Path to pilot ground truth labels JSONL"
    )
    parser.add_argument(
        "--output",
        type=str,
        default=str(OUTPUT_PATH),
        help="Path to output JSON file"
    )
    parser.add_argument(
        "--model",
        type=str,
        default=MODEL_NAME,
        help="SentenceTransformer model name"
    )
    
    args = parser.parse_args()
    
    try:
        # Load data
        logger.info("Loading pilot traces...")
        traces = load_pilot_traces(Path(args.traces))
        
        logger.info("Loading pilot labels...")
        labels = load_pilot_labels(Path(args.labels))
        
        # Align data
        logger.info("Aligning traces and labels...")
        aligned_pairs = align_traces_and_labels(traces, labels)
        
        # Load model
        logger.info(f"Loading model: {args.model}")
        model = SentenceTransformer(args.model)
        
        # Tune threshold
        logger.info("Starting threshold tuning...")
        best_threshold, best_agreement, history = tune_threshold(aligned_pairs, model)
        
        # Save results
        logger.info("Saving results...")
        save_results(best_threshold, best_agreement, history, Path(args.output))
        
        logger.info("Threshold tuning completed successfully.")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"Data file missing: {e}")
        return 1
    except ValueError as e:
        logger.error(f"Data validation error: {e}")
        return 1
    except Exception as e:
        logger.exception(f"Unexpected error during tuning: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
