import os
import sys
import json
import pickle
import warnings
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split
import shap
import matplotlib.pyplot as plt

# Ensure we can import from the project root if run as a script
if 'code' not in sys.path:
    sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.config import get_config

def ensure_dirs():
    """Ensure required output directories exist."""
    results_dir = Path("data/results")
    results_dir.mkdir(parents=True, exist_ok=True)
    return results_dir

def load_model_and_features():
    """Load the trained model and feature names from the model artifact."""
    model_path = Path("data/models/random_forest.pkl")
    if not model_path.exists():
        raise FileNotFoundError(f"Model artifact not found at {model_path}. Run T024 first.")
    
    with open(model_path, 'rb') as f:
        data = pickle.load(f)
    
    model = data.get('model')
    feature_names = data.get('feature_names')
    if model is None or feature_names is None:
        raise ValueError("Model artifact is missing 'model' or 'feature_names' keys.")
    
    return model, feature_names

def load_processed_data():
    """Load the processed merged dataset."""
    data_path = Path("data/processed/merged_dataset.csv")
    if not data_path.exists():
        raise FileNotFoundError(f"Processed data not found at {data_path}. Run US1 first.")
    
    df = pd.read_csv(data_path)
    return df

def run_permutation_importance(model, X, y, feature_names, n_repeats=10, random_state=42):
    """
    Run permutation importance and return results including p-values.
    
    Calculates p-values by comparing the drop in score against a null distribution
    generated by the permutation repeats.
    """
    if X.shape[0] < 10:
        raise ValueError("Dataset too small for permutation importance.")

    # Calculate permutation importance
    perm_result = permutation_importance(
        model, X, y, 
        n_repeats=n_repeats, 
        random_state=random_state,
        n_jobs=-1,
        scoring='r2'
    )
    
    importance_means = perm_result.importances_mean
    importance_stds = perm_result.importances_std
    importance_raw = perm_result.importances  # Shape: (n_features, n_repeats)
    
    # Calculate p-values
    # H0: The feature has no importance (importance <= 0).
    # We use the distribution of importance scores from the repeats.
    # p-value = (number of repeats with importance <= 0 + 1) / (n_repeats + 1)
    # This is a conservative estimate.
    
    p_values = []
    for i in range(len(importance_means)):
        # Count how many repeats resulted in a non-positive importance
        count_le_0 = np.sum(importance_raw[i, :] <= 0)
        p_val = (count_le_0 + 1) / (n_repeats + 1)
        p_values.append(p_val)
    
    return {
        'feature_names': feature_names,
        'importance_mean': importance_means.tolist(),
        'importance_std': importance_stds.tolist(),
        'p_values': p_values
    }

def benjamini_hochberg_correction(p_values, alpha=0.05):
    """
    Apply Benjamini-Hochberg correction to a list of p-values.
    
    Returns:
        corrected_p_values: List of adjusted p-values (FDR).
        significant: List of booleans indicating significance.
    """
    p_values = np.array(p_values)
    n = len(p_values)
    if n == 0:
        return [], []
    
    # Sort p-values and keep track of original indices
    sorted_indices = np.argsort(p_values)
    sorted_p_values = p_values[sorted_indices]
    
    # Calculate adjusted p-values ensuring monotonicity
    # adj_p[i] = min( (n / i) * p[i], adj_p[i+1] ) for sorted p-values
    adjusted_p_values = np.zeros(n)
    
    # Start from the largest p-value (index n-1)
    # rank is 1-based index in sorted list
    # For the largest p-value (rank n): adj = p * n / n = p
    adjusted_p_values[-1] = min(sorted_p_values[-1] * n / n, 1.0)
    
    for i in range(n - 2, -1, -1):
        # rank is i+1 (1-based)
        rank = i + 1
        adj = sorted_p_values[i] * n / rank
        # Ensure monotonicity: adjusted p-value cannot be smaller than the one for a larger p-value
        adjusted_p_values[i] = min(adj, adjusted_p_values[i+1], 1.0)
    
    # Map back to original order
    final_adjusted = np.zeros(n)
    final_adjusted[sorted_indices] = adjusted_p_values
    
    significant = final_adjusted <= alpha
    
    return final_adjusted.tolist(), significant.tolist()

def generate_shap_plot(model, X, feature_names, output_path):
    """Generate and save SHAP summary plot."""
    # Sample if dataset is too large for SHAP
    if X.shape[0] > 5000:
        X_sample = X[:5000]
    else:
        X_sample = X
    
    explainer = shap.Explainer(model, X_sample)
    shap_values = explainer(X_sample)
    
    plt.figure(figsize=(10, 8))
    shap.summary_plot(shap_values, X_sample, feature_names=feature_names, show=False)
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    return output_path

def main():
    """
    Main execution for T030: Apply Benjamini-Hochberg correction to permutation p-values.
    """
    print("Starting T030: Benjamini-Hochberg Correction")
    
    try:
        # 1. Load model and features
        model, feature_names = load_model_and_features()
        print(f"Loaded model with {len(feature_names)} features.")
        
        # 2. Load data
        df = load_processed_data()
        
        # Identify target column (assuming last column)
        target_col = df.columns[-1]
        X = df.drop(columns=[target_col]).values
        y = df[target_col].values
        
        print(f"Data shape: {X.shape}, Target shape: {y.shape}")
        
        # 3. Run Permutation Importance
        print("Running permutation importance...")
        perm_results = run_permutation_importance(
            model, X, y, feature_names, 
            n_repeats=10, 
            random_state=42
        )
        
        raw_p_values = perm_results['p_values']
        
        # 4. Apply Benjamini-Hochberg Correction
        print("Applying Benjamini-Hochberg correction...")
        corrected_p_values, significant = benjamini_hochberg_correction(raw_p_values, alpha=0.05)
        
        # 5. Prepare output
        output_data = {
            "task": "T030_Benjamini_Hochberg_Correction",
            "description": "FDR-corrected p-values for feature importance",
            "alpha": 0.05,
            "features": []
        }
        
        for i, fname in enumerate(feature_names):
            output_data["features"].append({
                "feature_name": fname,
                "raw_p_value": raw_p_values[i],
                "corrected_p_value": corrected_p_values[i],
                "is_significant": significant[i],
                "importance_mean": perm_results['importance_mean'][i]
            })
        
        # 6. Save to JSON
        results_dir = ensure_dirs()
        output_path = results_dir / "feature_importance_pvalues.json"
        
        with open(output_path, 'w') as f:
            json.dump(output_data, f, indent=2)
        
        print(f"Successfully saved corrected p-values to {output_path}")
        
        # 7. Generate SHAP plot (T029) if missing
        shap_output = results_dir / "shap_summary.png"
        if not shap_output.exists():
            print("Generating SHAP summary plot...")
            generate_shap_plot(model, X, feature_names, shap_output)
            print(f"SHAP plot saved to {shap_output}")
        
    except Exception as e:
        print(f"Error during T030 execution: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
