"""
T017b Implementation: Save transition-probability tables and Markov model state.

This module computes transition probability matrices from the standardized dataset
and saves them as versioned JSON artifacts in data/processed/.
"""
import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, List, Tuple
from datetime import datetime

import pandas as pd
import numpy as np

from config import get_data_dir, set_seed

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_standardized_data() -> pd.DataFrame:
    """
    Load the standardized dataset generated by T017.

    Returns:
        pd.DataFrame: The standardized dataset.

    Raises:
        FileNotFoundError: If the standardized CSV does not exist.
        ValueError: If required columns are missing.
    """
    data_dir = get_data_dir()
    standardized_path = data_dir / "processed" / "standardized.csv"

    if not standardized_path.exists():
        raise FileNotFoundError(
            f"Standardized dataset not found at {standardized_path}. "
            "Run T017 (generate_standardized_output.py) first."
        )

    df = pd.read_csv(standardized_path)

    required_columns = ['stimulus_sequence', 'surprisal', 'participant_id', 'duration_estimate']
    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(
            f"Standardized dataset missing required columns: {missing_cols}"
        )

    logger.info(f"Loaded standardized dataset with {len(df)} rows from {standardized_path}")
    return df

def compute_transition_matrices(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Compute transition probability matrices for each participant.

    The transition probability P(next | current) is calculated based on the
    'stimulus_sequence' column.

    Args:
        df (pd.DataFrame): The standardized dataset.

    Returns:
        Dict[str, Any]: A dictionary containing:
            - 'participants': List of participant IDs
            - 'transition_matrices': Dict mapping participant_id to their transition matrix
            - 'global_transition_matrix': Aggregated transition matrix across all participants
            - 'sequence_alphabet': The set of unique stimulus symbols found
    """
    if df.empty:
        raise ValueError("Input dataframe is empty. Cannot compute transition matrices.")

    participants = df['participant_id'].unique()
    sequence_col = 'stimulus_sequence'

    # Determine the alphabet of stimuli
    # Assuming stimulus_sequence is a string of symbols or a list encoded as string
    # We need to handle both cases: "ABC" -> ['A', 'B', 'C'] or "A,B,C" -> ['A', 'B', 'C']
    # For robustness, we'll extract all unique characters/symbols found in the sequence column.
    # If the column contains lists (unlikely in CSV unless stringified), we handle string parsing.
    
    all_symbols = set()
    for seq in df[sequence_col]:
        if isinstance(seq, str):
            # Heuristic: if it contains commas, split; otherwise treat as char sequence
            if ',' in seq:
                symbols = [s.strip() for s in seq.split(',')]
            else:
                symbols = list(seq)
            all_symbols.update(symbols)
        else:
            # If it's a number or other type, convert to string
            all_symbols.add(str(seq))
    
    sequence_alphabet = sorted(list(all_symbols))
    logger.info(f"Detected sequence alphabet ({len(sequence_alphabet)} symbols): {sequence_alphabet[:10]}...")

    participant_matrices = {}
    global_counts = {s: {t: 0 for t in sequence_alphabet} for s in sequence_alphabet}
    global_totals = {s: 0 for s in sequence_alphabet}

    for pid in participants:
        p_df = df[df['participant_id'] == pid]
        
        # Extract sequences for this participant
        # We assume sequences are continuous streams. If there are trial breaks,
        # we treat the whole participant's data as one long sequence for simplicity,
        # or we split by known trial boundaries if available. 
        # For T017b, we assume 'stimulus_sequence' represents the full sequence for that participant
        # or we iterate row by row if it's a single symbol per row.
        
        # Case 1: 'stimulus_sequence' is a single symbol per row (long format)
        # Case 2: 'stimulus_sequence' is the full sequence string per row (unlikely for long format)
        
        # Check if the column contains single symbols or full sequences
        sample_val = p_df[sequence_col].iloc[0]
        is_full_sequence = isinstance(sample_val, str) and len(sample_val) > 1 and ',' not in sample_val and len(p_df) > 10
        
        transitions = {s: {t: 0 for t in sequence_alphabet} for s in sequence_alphabet}
        totals = {s: 0 for s in sequence_alphabet}

        if not is_full_sequence:
            # Long format: each row is a step
            current_seq = p_df[sequence_col].tolist()
            for i in range(len(current_seq) - 1):
                curr = str(current_seq[i])
                nxt = str(current_seq[i+1])
                if curr in transitions and nxt in transitions[curr]:
                    transitions[curr][nxt] += 1
                    totals[curr] += 1
                    global_counts[curr][nxt] += 1
                    global_totals[curr] += 1
        else:
            # If the column contains the full sequence string, we might have one row per participant
            # or multiple rows where we need to concatenate.
            # For safety, we treat the column as a list of symbols if it looks like a sequence.
            # If it's a single string per row and we have multiple rows, we might need to concatenate.
            # Let's assume standard long format where 'stimulus_sequence' is the symbol.
            # If the data is actually wide (one string per row), we parse it.
            
            # Re-evaluating: If is_full_sequence is true, we likely have one row per participant
            # or we need to join them.
            # Let's just iterate through the unique values if it's a list of strings.
            # Actually, let's stick to the most common case: long format where each row is a stimulus.
            # If the data is weird, the logic below handles string splitting if needed.
            
            # Fallback: treat the whole column as a sequence of strings
            all_vals = p_df[sequence_col].tolist()
            # If they are long strings, we might need to split them if they represent sequences
            # But usually in long format, they are single tokens.
            # If we have a list of strings that are actually sequences "A,B,C", we split.
            
            flat_seq = []
            for val in all_vals:
                if isinstance(val, str):
                    if ',' in val:
                        flat_seq.extend([s.strip() for s in val.split(',')])
                    else:
                        flat_seq.append(val)
                else:
                    flat_seq.append(str(val))
            
            for i in range(len(flat_seq) - 1):
                curr = flat_seq[i]
                nxt = flat_seq[i+1]
                if curr in transitions and nxt in transitions[curr]:
                    transitions[curr][nxt] += 1
                    totals[curr] += 1
                    global_counts[curr][nxt] += 1
                    global_totals[curr] += 1

        # Convert counts to probabilities
        prob_matrix = {}
        for s in sequence_alphabet:
            if totals[s] > 0:
                prob_matrix[s] = {t: transitions[s][t] / totals[s] for t in sequence_alphabet}
            else:
                prob_matrix[s] = {t: 0.0 for t in sequence_alphabet}
        
        participant_matrices[str(pid)] = prob_matrix

    # Compute global matrix
    global_prob_matrix = {}
    for s in sequence_alphabet:
        if global_totals[s] > 0:
            global_prob_matrix[s] = {t: global_counts[s][t] / global_totals[s] for t in sequence_alphabet}
        else:
            global_prob_matrix[s] = {t: 0.0 for t in sequence_alphabet}

    return {
        'sequence_alphabet': sequence_alphabet,
        'participant_transition_matrices': participant_matrices,
        'global_transition_matrix': global_prob_matrix,
        'metadata': {
            'total_participants': len(participants),
            'total_transitions_computed': sum(global_totals.values()),
            'calculation_timestamp': datetime.utcnow().isoformat()
        }
    }

def save_markov_artifacts(transition_data: Dict[str, Any], version: str = "v1.0") -> List[str]:
    """
    Save transition probability tables and Markov model state to data/processed/.

    Args:
        transition_data (Dict[str, Any]): The computed transition data.
        version (str): Version string for the artifact.

    Returns:
        List[str]: Paths to the saved files.
    """
    data_dir = get_data_dir()
    processed_dir = data_dir / "processed"
    processed_dir.mkdir(parents=True, exist_ok=True)

    saved_files = []

    # 1. Save Global Transition Matrix
    global_matrix_path = processed_dir / f"transition_matrix_global_{version}.json"
    with open(global_matrix_path, 'w') as f:
        json.dump(transition_data['global_transition_matrix'], f, indent=2)
    saved_files.append(str(global_matrix_path))
    logger.info(f"Saved global transition matrix to {global_matrix_path}")

    # 2. Save Participant Transition Matrices
    participant_matrix_path = processed_dir / f"transition_matrices_participants_{version}.json"
    with open(participant_matrix_path, 'w') as f:
        json.dump(transition_data['participant_transition_matrices'], f, indent=2)
    saved_files.append(str(participant_matrix_path))
    logger.info(f"Saved participant transition matrices to {participant_matrix_path}")

    # 3. Save Full Markov Model State (including metadata and alphabet)
    model_state_path = processed_dir / f"markov_model_state_{version}.json"
    state_data = {
        'version': version,
        'alphabet': transition_data['sequence_alphabet'],
        'metadata': transition_data['metadata'],
        'global_matrix': transition_data['global_transition_matrix'],
        'participant_matrices_count': len(transition_data['participant_transition_matrices'])
    }
    with open(model_state_path, 'w') as f:
        json.dump(state_data, f, indent=2)
    saved_files.append(str(model_state_path))
    logger.info(f"Saved Markov model state to {model_state_path}")

    return saved_files

def run_t017b(seed: int = 42) -> Dict[str, Any]:
    """
    Main entry point for T017b task.

    1. Sets the random seed.
    2. Loads standardized data.
    3. Computes transition matrices.
    4. Saves artifacts.

    Args:
        seed (int): Random seed for reproducibility.

    Returns:
        Dict[str, Any]: Summary of the operation.
    """
    set_seed(seed)
    logger.info(f"Starting T017b with seed {seed}")

    try:
        df = load_standardized_data()
        transition_data = compute_transition_matrices(df)
        saved_files = save_markov_artifacts(transition_data)

        return {
            'status': 'success',
            'files_saved': saved_files,
            'participants_processed': transition_data['metadata']['total_participants'],
            'alphabet_size': len(transition_data['sequence_alphabet'])
        }
    except FileNotFoundError as e:
        logger.error(f"Data not found: {e}")
        return {'status': 'failed', 'reason': str(e)}
    except Exception as e:
        logger.error(f"Error during T017b execution: {e}", exc_info=True)
        return {'status': 'failed', 'reason': str(e)}

if __name__ == "__main__":
    result = run_t017b()
    print(json.dumps(result, indent=2))
    if result['status'] == 'failed':
        sys.exit(1)
