"""
FLOPs estimation and savings calculation for dynamic router vs static baseline.

Implements FR-006 (FLOPs savings) and SC-002 (statistical significance).
Uses the formula from T005c: FLOPs = parameters * sequence_length * k
"""
import csv
import json
import logging
import os
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
import numpy as np
from scipy import stats

from src.utils import calculate_flops, get_model_param_count
from src.logging_utils import ensure_output_dir, save_results_to_json

logger = logging.getLogger(__name__)

# Configuration constants
DEFAULT_MODEL_PARAMS = 1_300_000_000  # CodeLlama-1.3b default
DEFAULT_SEQ_LENGTH = 512
STATIC_BASELINE_K = 2
NON_INFERIORITY_MARGIN = 0.05  # 5% margin for non-inferiority test

def load_router_predictions(file_path: str) -> List[Dict[str, Any]]:
    """Load router predictions from the CSV generated by T019/T020."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Router predictions file not found: {file_path}")
    
    results = []
    with open(file_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            results.append({
                'task_id': row['task_id'],
                'predicted_k': int(row['predicted_k']),
                'actual_converged_k': int(row['actual_converged_k']),
                'is_correct': row['is_correct'] == 'True',
                'entropy': float(row['entropy']) if row.get('entropy') else None
            })
    return results

def load_convergence_results(file_path: str) -> List[Dict[str, Any]]:
    """Load convergence results to get actual sequence lengths and k values."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Convergence results file not found: {file_path}")
    
    results = []
    with open(file_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            results.append({
                'task_id': row['task_id'],
                'k_used': int(row['k_used']),
                'sequence_length': int(row['sequence_length']),
                'is_correct': row['is_correct'] == 'True'
            })
    return results

def align_data_for_flops(
    router_preds: List[Dict[str, Any]], 
    conv_results: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """Align router predictions with convergence results by task_id."""
    conv_map = {r['task_id']: r for r in conv_results}
    aligned = []
    
    for pred in router_preds:
        task_id = pred['task_id']
        if task_id in conv_map:
            conv = conv_map[task_id]
            aligned.append({
                'task_id': task_id,
                'predicted_k': pred['predicted_k'],
                'actual_k': pred['actual_converged_k'],
                'sequence_length': conv['sequence_length'],
                'is_correct': pred['is_correct'] and conv['is_correct'],
                'entropy': pred.get('entropy')
            })
        else:
            logger.warning(f"No convergence result found for task_id: {task_id}")
    
    return aligned

def calculate_flops_for_scenario(
    data: List[Dict[str, Any]], 
    k_value: int,
    model_params: float,
    default_seq_length: int = DEFAULT_SEQ_LENGTH
) -> float:
    """
    Calculate total FLOPs for a given k value across all samples.
    FLOPs = parameters * sequence_length * k
    """
    total_flops = 0.0
    for item in data:
        seq_len = item.get('sequence_length', default_seq_length)
        total_flops += model_params * seq_len * k_value
    return total_flops

def calculate_flops_dynamic_router(data: List[Dict[str, Any]], model_params: float) -> float:
    """Calculate FLOPs when using the dynamic router (predicted_k per sample)."""
    total_flops = 0.0
    for item in data:
        k = item['predicted_k']
        seq_len = item.get('sequence_length', DEFAULT_SEQ_LENGTH)
        total_flops += model_params * seq_len * k
    return total_flops

def calculate_accuracy(data: List[Dict[str, Any]]) -> float:
    """Calculate accuracy (proportion of correct solutions)."""
    if not data:
        return 0.0
    correct = sum(1 for item in data if item['is_correct'])
    return correct / len(data)

def non_inferiority_test(
    router_acc: float, 
    baseline_acc: float, 
    margin: float = NON_INFERIORITY_MARGIN,
    n_samples: int = 1000
) -> Dict[str, Any]:
    """
    Perform a non-inferiority test to check if router accuracy is not worse 
    than baseline by more than the margin.
    
    Uses a bootstrap approach to estimate the confidence interval of the 
    accuracy difference.
    """
    if router_acc is None or baseline_acc is None:
        return {
            'is_non_inferior': False,
            'p_value': None,
            'confidence_interval': None,
            'margin': margin,
            'note': 'Missing accuracy values'
        }
    
    # Bootstrap resampling to estimate distribution of accuracy difference
    bootstrap_diffs = []
    n = len(data) if (data := []) else 100  # Placeholder for actual data size
    
    # Since we don't have individual binary outcomes here, we approximate
    # using the normal approximation for the difference in proportions
    # Router: p1, Baseline: p2
    # H0: p1 - p2 <= -margin (router is inferior)
    # H1: p1 - p2 > -margin (router is non-inferior)
    
    # For a proper test, we would need the raw binary outcomes.
    # Here we use a simplified Z-test for the difference in proportions.
    # Note: This is an approximation. For rigorous testing, raw data is needed.
    
    # Assuming equal sample sizes for simplicity (n per group)
    # In reality, we are comparing the same samples under two strategies.
    # A paired test would be more appropriate, but we lack the paired binary outcomes
    # in this aggregated view. We proceed with a conservative approximation.
    
    p1, p2 = router_acc, baseline_acc
    # Estimate standard error for difference (conservative, assuming independence)
    # SE = sqrt(p1(1-p1)/n + p2(1-p2)/n)
    # We need n. If not available, we cannot compute a valid p-value.
    # We will return a status based on the point estimate difference vs margin.
    
    diff = p1 - p2
    lower_bound = diff - margin
    
    # Heuristic: If the point estimate difference is > 0 (or > -margin), 
    # we might claim non-inferiority, but without n we can't compute p-value.
    # We will assume a large enough N for the CI to be tight if we don't have it,
    # or return a warning.
    
    # Let's assume a fallback N if not passed (not ideal, but necessary for code flow)
    # In a real scenario, 'data' would be passed to get n.
    # Here we just check the point estimate against the margin.
    
    is_non_inferior = diff >= -margin
    p_value = None # Cannot compute without raw data/n
    
    return {
        'is_non_inferior': is_non_inferior,
        'accuracy_difference': diff,
        'margin': margin,
        'p_value': p_value,
        'note': 'Point estimate check only. Raw data required for exact p-value.'
    }

def calculate_flops_savings(
    static_flops: float, 
    dynamic_flops: float
) -> Dict[str, float]:
    """Calculate absolute and percentage FLOPs savings."""
    if static_flops <= 0:
        return {'absolute_savings': 0.0, 'percentage_savings': 0.0}
    
    absolute_savings = static_flops - dynamic_flops
    percentage_savings = (absolute_savings / static_flops) * 100.0
    
    return {
        'absolute_savings': absolute_savings,
        'percentage_savings': percentage_savings
    }

def run_flops_analysis(
    router_predictions_path: str,
    convergence_results_path: str,
    output_path: str,
    model_params: Optional[float] = None
) -> Dict[str, Any]:
    """
    Main function to run FLOPs estimation and savings calculation.
    
    Steps:
    1. Load router predictions and convergence results.
    2. Align data by task_id.
    3. Calculate static baseline FLOPs (k=2).
    4. Calculate dynamic router FLOPs (predicted_k).
    5. Calculate accuracies for both strategies.
    6. Perform non-inferiority test.
    7. Calculate FLOPs savings.
    8. Save results.
    """
    model_params = model_params or get_model_param_count(DEFAULT_MODEL_PARAMS)
    
    logger.info(f"Loading router predictions from {router_predictions_path}")
    router_preds = load_router_predictions(router_predictions_path)
    
    logger.info(f"Loading convergence results from {convergence_results_path}")
    conv_results = load_convergence_results(convergence_results_path)
    
    logger.info("Aligning data...")
    aligned_data = align_data_for_flops(router_preds, conv_results)
    
    if not aligned_data:
        raise ValueError("No aligned data found. Check input files.")
    
    logger.info("Calculating FLOPs...")
    static_flops = calculate_flops_for_scenario(
        aligned_data, 
        STATIC_BASELINE_K, 
        model_params
    )
    dynamic_flops = calculate_flops_dynamic_router(aligned_data, model_params)
    
    logger.info("Calculating accuracies...")
    # For static baseline (k=2), we assume the model runs for k=2 and we check correctness
    # In the alignment, 'is_correct' is based on the actual convergence.
    # For a fair comparison, we need to know if the solution at k=2 was correct.
    # However, our data only has the 'actual_converged_k'.
    # If actual_converged_k <= 2, then k=2 would have found the solution.
    # If actual_converged_k > 2, then k=2 would have failed (assuming monotonic convergence).
    # We will approximate static baseline accuracy as the proportion where actual_k <= 2.
    
    static_accuracy = sum(1 for item in aligned_data if item['actual_k'] <= STATIC_BASELINE_K) / len(aligned_data)
    dynamic_accuracy = sum(1 for item in aligned_data if item['is_correct']) / len(aligned_data)
    
    logger.info("Running non-inferiority test...")
    # We need the raw binary outcomes for a proper test. 
    # We construct a list of outcomes for the approximation.
    # Static: 1 if actual_k <= 2 else 0
    # Dynamic: 1 if is_correct (based on predicted k) else 0
    static_outcomes = [1 if item['actual_k'] <= STATIC_BASELINE_K else 0 for item in aligned_data]
    dynamic_outcomes = [1 if item['is_correct'] else 0 for item in aligned_data]
    
    n = len(aligned_data)
    
    # Paired t-test approximation for accuracy difference
    # Since we are comparing the same items under two conditions
    diff = [d - s for d, s in zip(dynamic_outcomes, static_outcomes)]
    mean_diff = np.mean(diff)
    std_diff = np.std(diff, ddof=1) if n > 1 else 0
    
    # T-statistic for non-inferiority (H0: mean_diff <= -margin)
    # t = (mean_diff - (-margin)) / (std_diff / sqrt(n))
    if std_diff > 0 and n > 1:
        t_stat = (mean_diff + NON_INFERIORITY_MARGIN) / (std_diff / np.sqrt(n))
        # One-tailed p-value
        p_value = 1 - stats.t.cdf(t_stat, df=n-1)
    else:
        t_stat = 0
        p_value = 1.0
    
    is_non_inferior = p_value < 0.05 and mean_diff >= -NON_INFERIORITY_MARGIN
    
    logger.info("Calculating FLOPs savings...")
    flops_savings = calculate_flops_savings(static_flops, dynamic_flops)
    
    results = {
        'model_params': model_params,
        'static_baseline_k': STATIC_BASELINE_K,
        'sample_size': n,
        'static_flops': static_flops,
        'dynamic_flops': dynamic_flops,
        'flops_savings': flops_savings,
        'static_accuracy': static_accuracy,
        'dynamic_accuracy': dynamic_accuracy,
        'accuracy_difference': dynamic_accuracy - static_accuracy,
        'non_inferiority_test': {
            'margin': NON_INFERIORITY_MARGIN,
            't_statistic': t_stat,
            'p_value': p_value,
            'is_non_inferior': is_non_inferior,
            'mean_difference': mean_diff,
            'std_difference': std_diff
        },
        'timestamp': None # Will be set by logger or system
    }
    
    ensure_output_dir(output_path)
    save_results_to_json(results, output_path)
    
    logger.info(f"FLOPs analysis complete. Results saved to {output_path}")
    return results

def main():
    """Entry point for FLOPs analysis script."""
    import argparse
    parser = argparse.ArgumentParser(description="Calculate FLOPs savings for dynamic router.")
    parser.add_argument("--router-preds", type=str, required=True, help="Path to router predictions CSV")
    parser.add_argument("--convergence", type=str, required=True, help="Path to convergence results CSV")
    parser.add_argument("--output", type=str, required=True, help="Path to output JSON file")
    parser.add_argument("--model-params", type=float, default=DEFAULT_MODEL_PARAMS, help="Model parameters count")
    
    args = parser.parse_args()
    
    logging.basicConfig(level=logging.INFO)
    
    try:
        results = run_flops_analysis(
            router_predictions_path=args.router_preds,
            convergence_results_path=args.convergence,
            output_path=args.output,
            model_params=args.model_params
        )
        print(json.dumps(results, indent=2))
    except Exception as e:
        logger.error(f"Analysis failed: {e}")
        raise

if __name__ == "__main__":
    main()
