import hashlib
import json
import os
import sys
import gc
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional

# Add project root to path for imports if running as script
project_root = Path(__file__).resolve().parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

try:
    from datasets import load_dataset
except ImportError:
    print("ERROR: 'datasets' package is not installed. Please run: pip install datasets")
    sys.exit(1)

from src.utils.logging import get_logger

# Configure logging
logger = get_logger("download")

# Constants
DATASETS = {
    "gsm8k": {
        "name": "gsm8k",
        "config": "main",
        "split": "train",
        "output_file": "gsm8k_train.jsonl"
    },
    "math": {
        "name": "lighteval/math",
        "config": "default",
        "split": "train",
        "output_file": "math_train.jsonl"
    }
}

def ensure_data_dirs() -> Path:
    """Ensure raw data directories exist."""
    raw_dir = project_root / "data" / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    return raw_dir

def ensure_state_dir() -> Path:
    """Ensure state directory exists for manifest."""
    state_dir = project_root / "state"
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir

def compute_file_hash(file_path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def load_manifest(state_dir: Path) -> Dict[str, Any]:
    """Load existing manifest if it exists."""
    manifest_path = state_dir / "artifact_hashes.yaml"
    if manifest_path.exists():
        # Simple YAML parser for our specific format (no external dependency)
        manifest = {}
        with open(manifest_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    if ":" in line:
                        key, value = line.split(":", 1)
                        manifest[key.strip()] = value.strip()
        return manifest
    return {}

def save_manifest(manifest: Dict[str, Any], state_dir: Path) -> None:
    """Save manifest to YAML file."""
    manifest_path = state_dir / "artifact_hashes.yaml"
    with open(manifest_path, "w") as f:
        f.write("# Artifact Hashes - Generated by download.py\n")
        f.write("# Format: filename: sha256_hash\n\n")
        for key, value in manifest.items():
            f.write(f"{key}: {value}\n")
    logger.info(f"Manifest saved to {manifest_path}")

def download_dataset(dataset_name: str, raw_dir: Path) -> Optional[Path]:
    """
    Download a dataset from HuggingFace and save as JSONL.
    Returns the path to the downloaded file, or None if failed.
    """
    if dataset_name not in DATASETS:
        logger.error(f"Unknown dataset: {dataset_name}")
        return None

    config = DATASETS[dataset_name]
    output_file = raw_dir / config["output_file"]

    # Skip if file already exists (idempotent)
    if output_file.exists():
        logger.info(f"Dataset {dataset_name} already exists at {output_file}")
        return output_file

    try:
        logger.info(f"Loading dataset {config['name']} (config: {config['config']})...")
        dataset = load_dataset(
            config["name"],
            config["config"],
            split=config["split"],
            trust_remote_code=True
        )

        logger.info(f"Dataset loaded. Writing to {output_file}...")
        with open(output_file, "w", encoding="utf-8") as f:
            for item in dataset:
                # Convert item to JSON string
                import json
                json_str = json.dumps(item, ensure_ascii=False)
                f.write(json_str + "\n")

        logger.info(f"Successfully downloaded {dataset_name} to {output_file}")
        # Force garbage collection to free memory
        gc.collect()
        return output_file

    except Exception as e:
        logger.error(f"Failed to download {dataset_name}: {e}")
        return None

def download_all_datasets() -> Dict[str, Path]:
    """Download all configured datasets."""
    raw_dir = ensure_data_dirs()
    downloaded = {}

    for name in DATASETS:
        path = download_dataset(name, raw_dir)
        if path:
            downloaded[name] = path

    return downloaded

def main() -> None:
    """Main entry point for dataset download and manifest generation."""
    logger.info("Starting dataset download process...")

    # Download datasets
    downloaded_files = download_all_datasets()

    if not downloaded_files:
        logger.error("No datasets were downloaded successfully.")
        sys.exit(1)

    # Generate checksums
    state_dir = ensure_state_dir()
    manifest = load_manifest(state_dir)

    logger.info("Generating SHA-256 checksums...")
    for name, path in downloaded_files.items():
        file_hash = compute_file_hash(path)
        manifest[f"{name}_hash"] = file_hash
        manifest[f"{name}_path"] = str(path.relative_to(project_root))
        logger.info(f"  {name}: {file_hash[:16]}...")

    # Save manifest
    save_manifest(manifest, state_dir)

    logger.info("Download process completed successfully.")

if __name__ == "__main__":
    main()
