import os
import sys
import csv
import time
from pathlib import Path
from code.config import DATA_PROCESSED_DIR, LOGS_DIR

# Expected artifacts for T035 verification
EXPECTED_ARTIFACTS = [
    "data/processed/energy_results_aggregated.csv",
    "data/processed/stats_report.csv",
    "data/processed/energy_bar.png",
    "data/processed/tradeoff_scatter.png",
    "logs/pipeline_duration.log"
]

def check_file_exists(filepath: str) -> bool:
    """Check if a file exists and is non-empty."""
    path = Path(filepath)
    if not path.exists():
        print(f"FAIL: File missing: {filepath}")
        return False
    if path.stat().st_size == 0:
        print(f"FAIL: File empty: {filepath}")
        return False
    print(f"OK: File exists and non-empty: {filepath}")
    return True

def check_csv_content(filepath: str, required_columns: list) -> bool:
    """Check if a CSV file has the required columns and at least one data row."""
    try:
        with open(filepath, 'r', newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            if reader.fieldnames is None:
                print(f"FAIL: CSV file {filepath} has no header.")
                return False
            
            missing_cols = set(required_columns) - set(reader.fieldnames)
            if missing_cols:
                print(f"FAIL: CSV {filepath} missing columns: {missing_cols}")
                return False
            
            # Check for at least one data row
            rows = list(reader)
            if len(rows) == 0:
                print(f"FAIL: CSV {filepath} has no data rows.")
                return False
            
            # Check for non-null values in key columns (basic sanity)
            for col in required_columns:
                if col in reader.fieldnames:
                    # Check if any row has a non-null value for this column
                    non_null_count = sum(1 for row in rows if row.get(col) not in (None, '', 'null', 'NaN'))
                    if non_null_count == 0:
                        print(f"FAIL: CSV {filepath} column '{col}' has no non-null values.")
                        return False

            print(f"OK: CSV {filepath} has valid structure and data.")
            return True
    except Exception as e:
        print(f"FAIL: Error reading CSV {filepath}: {e}")
        return False

def check_log_content(filepath: str) -> bool:
    """Check if a log file exists and contains duration info."""
    if not check_file_exists(filepath):
        return False
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            if "duration" not in content.lower() and "seconds" not in content.lower():
                print(f"FAIL: Log file {filepath} does not appear to contain duration info.")
                return False
            print(f"OK: Log file {filepath} contains duration info.")
            return True
    except Exception as e:
        print(f"FAIL: Error reading log {filepath}: {e}")
        return False

def main():
    """
    Final validation for T035:
    Run checks on all required artifacts generated by the pipeline.
    """
    print("Starting Final Validation (T035)...")
    all_passed = True

    # 1. Check energy_results_aggregated.csv
    agg_path = "data/processed/energy_results_aggregated.csv"
    if not check_file_exists(agg_path):
        all_passed = False
    else:
        # Required columns based on T016 and T021
        required_cols = ['model_id', 'problem_id', 'tokens_generated', 'energy_kwh', 'runtime_seconds', 'pass_fail_status']
        if not check_csv_content(agg_path, required_cols):
            all_passed = False

    # 2. Check stats_report.csv
    stats_path = "data/processed/stats_report.csv"
    if not check_file_exists(stats_path):
        all_passed = False
    else:
        # Basic check: must have content
        if not check_csv_content(stats_path, []): # No specific columns enforced here, just existence of data
            all_passed = False

    # 3. Check plots (just existence and non-empty)
    plots = [
        "data/processed/energy_bar.png",
        "data/processed/tradeoff_scatter.png"
    ]
    for plot_path in plots:
        if not check_file_exists(plot_path):
            all_passed = False

    # 4. Check logs/pipeline_duration.log
    log_path = "logs/pipeline_duration.log"
    if not check_log_content(log_path):
        all_passed = False

    print("\n" + "="*50)
    if all_passed:
        print("VALIDATION PASSED: All required artifacts exist and are valid.")
        return 0
    else:
        print("VALIDATION FAILED: One or more artifacts are missing or invalid.")
        return 1

if __name__ == "__main__":
    sys.exit(main())
