"""
Data Extraction Module for DanceOPD Teacher Ground Truth.

This module implements the logic to extract features (prompt_embedding, noise_level,
routing_label, velocity_vector) from the teacher inference outputs and stream them
to a Parquet file.

It depends on the output of T013a (teacher_ground_truth.parquet) or a fallback dataset.
"""
import argparse
import sys
import json
import signal
import time
from pathlib import Path
from typing import Optional, Dict, Any, List, Tuple
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import numpy as np

# Import project utilities
from utils.config import get_config, get_path
from utils.check_weights import load_manifest

# Global timeout state
_timeout_active = False
_start_time = 0

class TimeoutError(Exception):
    """Custom timeout exception for data extraction."""
    pass

def timeout_handler(signum, frame):
    """Signal handler for timeout."""
    raise TimeoutError("Data extraction timed out")

def setup_timeout(seconds: int):
    """Setup a hard timeout for the extraction process."""
    global _timeout_active, _start_time
    _start_time = time.time()
    if hasattr(signal, 'SIGALRM'):
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(seconds)
        _timeout_active = True

def cancel_timeout():
    """Cancel the active timeout."""
    global _timeout_active
    if _timeout_active:
        signal.alarm(0)
        _timeout_active = False

def get_project_root() -> Path:
    """Return the project root directory."""
    return Path(__file__).resolve().parent.parent

def get_known_expert_ids() -> List[str]:
    """
    Retrieve the list of known expert IDs from the configuration.
    Falls back to a standard list if not explicitly defined in config.
    """
    config = get_config()
    # Attempt to load from config first
    if hasattr(config, 'TEACHER_EXPERT_IDS') and config.TEACHER_EXPERT_IDS:
        return config.TEACHER_EXPERT_IDS
    
    # Fallback: Standard DanceOPD expert names based on typical architecture
    # These should match the labels generated by the teacher model in T013a
    return [
        "expert_style_transfer",
        "expert_super_resolution",
        "expert_inpainting",
        "expert_deblurring",
        "expert_colorization",
        "expert_fallback"
    ]

def load_inference_outputs(input_path: Path) -> pd.DataFrame:
    """
    Load the teacher ground truth or fallback dataset.
    
    Args:
        input_path: Path to the parquet file (teacher_ground_truth.parquet or fallback)
        
    Returns:
        DataFrame containing the inference outputs.
        
    Raises:
        FileNotFoundError: If the input file does not exist.
        ValueError: If the file format is invalid.
    """
    if not input_path.exists():
        raise FileNotFoundError(f"Inference output file not found: {input_path}")
    
    try:
        df = pd.read_parquet(input_path)
        return df
    except Exception as e:
        raise ValueError(f"Failed to load parquet file {input_path}: {e}")

def validate_routing_labels(df: pd.DataFrame, known_ids: List[str]) -> pd.DataFrame:
    """
    Validate that routing labels match known expert IDs.
    Assigns fallback label for undefined paths if configured.
    
    Args:
        df: Input DataFrame with 'routing_label' column.
        known_ids: List of valid expert IDs.
        
    Returns:
        DataFrame with validated/adjusted routing labels.
    """
    config = get_config()
    use_fallback = getattr(config, 'USE_FALLBACK_LABEL', False)
    
    # Identify undefined labels
    valid_mask = df['routing_label'].isin(known_ids)
    undefined_count = (~valid_mask).sum()
    
    if undefined_count > 0:
        print(f"Warning: Found {undefined_count} samples with undefined routing labels.")
        if use_fallback:
            df.loc[~valid_mask, 'routing_label'] = "expert_fallback"
            print("Assigned 'expert_fallback' to undefined labels.")
        else:
            # Filter out undefined rows
            df = df[valid_mask].copy()
            print(f"Filtered out {undefined_count} samples with undefined labels.")
    
    return df

def filter_valid_rows(df: pd.DataFrame) -> pd.DataFrame:
    """
    Filter rows to ensure all required columns exist and contain valid data.
    Handles cases where embeddings might be stored as lists or numpy arrays.
    """
    required_cols = ['prompt_embedding', 'noise_level', 'routing_label', 'velocity_vector']
    
    # Check for existence of columns
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in input data: {missing_cols}")
    
    # Ensure no null values in critical columns
    null_counts = df[required_cols].isnull().sum()
    if null_counts.any():
        print(f"Warning: Found null values in columns: {null_counts[null_counts > 0].to_dict()}")
        # Drop rows with nulls in critical columns
        df = df.dropna(subset=required_cols)
    
    return df

def write_exclusion_log(exclusion_count: int, reason: str, output_path: Path):
    """Write exclusion log to JSON."""
    log_entry = {
        "count": exclusion_count,
        "reason": reason,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
    }
    with open(output_path, 'w') as f:
        json.dump(log_entry, f, indent=2)
    print(f"Exclusion log written to {output_path}")

def extract_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Extract and normalize features from the raw inference data.
    
    This function ensures that embeddings are in a consistent format (lists or arrays)
    suitable for Parquet storage.
    
    Args:
        df: DataFrame containing raw inference outputs.
        
    Returns:
        DataFrame with extracted and normalized features.
    """
    # Create a copy to avoid modifying the original
    result_df = df.copy()
    
    # Ensure prompt_embedding is a list (Parquet compatible)
    if isinstance(result_df['prompt_embedding'].iloc[0], np.ndarray):
        result_df['prompt_embedding'] = result_df['prompt_embedding'].apply(lambda x: x.tolist())
    elif isinstance(result_df['prompt_embedding'].iloc[0], list):
        pass # Already a list
    else:
        # If it's a tensor, convert to list
        import torch
        if isinstance(result_df['prompt_embedding'].iloc[0], torch.Tensor):
            result_df['prompt_embedding'] = result_df['prompt_embedding'].apply(lambda x: x.cpu().numpy().tolist())
    
    # Ensure velocity_vector is a list
    if isinstance(result_df['velocity_vector'].iloc[0], np.ndarray):
        result_df['velocity_vector'] = result_df['velocity_vector'].apply(lambda x: x.tolist())
    elif isinstance(result_df['velocity_vector'].iloc[0], torch.Tensor):
        result_df['velocity_vector'] = result_df['velocity_vector'].apply(lambda x: x.cpu().numpy().tolist())
    
    # Ensure noise_level is numeric
    if not pd.api.types.is_numeric_dtype(result_df['noise_level']):
        result_df['noise_level'] = pd.to_numeric(result_df['noise_level'], errors='coerce')
    
    return result_df

def stream_to_parquet(df: pd.DataFrame, output_path: Path):
    """
    Stream the processed DataFrame to a Parquet file.
    
    Args:
        df: Processed DataFrame.
        output_path: Path to the output Parquet file.
    """
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write to Parquet
    # Using 'pyarrow' engine for better compatibility with complex types
    df.to_parquet(
        output_path,
        engine='pyarrow',
        index=False,
        compression='snappy'
    )
    print(f"Successfully wrote {len(df)} rows to {output_path}")

def run_data_extraction(
    input_path: Path,
    output_path: Path,
    timeout_seconds: int = 3600
) -> Tuple[int, int]:
    """
    Main execution function for data extraction.
    
    1. Loads inference outputs.
    2. Validates routing labels.
    3. Filters valid rows.
    4. Extracts features.
    5. Streams to Parquet.
    
    Args:
        input_path: Path to input parquet (teacher_ground_truth.parquet).
        output_path: Path to output parquet (teacher_routing_dataset.parquet).
        timeout_seconds: Timeout in seconds for the operation.
        
    Returns:
        Tuple of (total_rows_processed, rows_written).
    """
    config = get_config()
    exclusion_log_path = get_path("EXCLUSION_LOG")
    
    # Setup timeout
    setup_timeout(timeout_seconds)
    
    try:
        print(f"Loading inference outputs from {input_path}...")
        df = load_inference_outputs(input_path)
        total_rows = len(df)
        print(f"Loaded {total_rows} rows.")
        
        # Validate routing labels
        print("Validating routing labels...")
        known_ids = get_known_expert_ids()
        df = validate_routing_labels(df, known_ids)
        
        # Filter valid rows
        print("Filtering valid rows...")
        df = filter_valid_rows(df)
        filtered_rows = total_rows - len(df)
        
        # Log exclusions if any
        if filtered_rows > 0:
            write_exclusion_log(
                exclusion_count=filtered_rows,
                reason="Undefined routing labels or missing data",
                output_path=exclusion_log_path
            )
        
        # Extract features
        print("Extracting features...")
        df = extract_features(df)
        
        # Stream to Parquet
        print(f"Streaming to {output_path}...")
        stream_to_parquet(df, output_path)
        
        cancel_timeout()
        return total_rows, len(df)
        
    except TimeoutError:
        print("ERROR: Data extraction timed out.")
        cancel_timeout()
        # Save partial results if possible
        partial_path = output_path.parent / "partial_extraction.json"
        partial_data = {
            "status": "timeout",
            "processed_rows": len(df) if 'df' in locals() else 0,
            "total_rows": total_rows if 'total_rows' in locals() else 0
        }
        with open(partial_path, 'w') as f:
            json.dump(partial_data, f)
        raise
    except Exception as e:
        print(f"ERROR: Data extraction failed: {e}")
        cancel_timeout()
        raise

def main():
    """CLI entry point for data extraction."""
    parser = argparse.ArgumentParser(description="Extract teacher routing dataset.")
    parser.add_argument(
        "--input",
        type=str,
        default=None,
        help="Path to input parquet (teacher_ground_truth.parquet). Defaults to config."
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Path to output parquet. Defaults to config."
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=3600,
        help="Timeout in seconds."
    )
    
    args = parser.parse_args()
    
    # Resolve paths
    config = get_config()
    
    if args.input:
        input_path = Path(args.input)
    else:
        # Default path for T013a output
        input_path = get_path("TEACHER_GROUND_TRUTH")
        # Fallback if config path is not set
        if not input_path.exists():
            # Try standard location relative to project root
            project_root = get_project_root()
            input_path = project_root / "data" / "processed" / "teacher_ground_truth.parquet"
    
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = get_path("TEACHER_ROUTING_DATASET")
        if not output_path:
            project_root = get_project_root()
            output_path = project_root / "data" / "processed" / "teacher_routing_dataset.parquet"
    
    print(f"Input: {input_path}")
    print(f"Output: {output_path}")
    
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        print("Did you run T013a to generate teacher_ground_truth.parquet?")
        sys.exit(1)
    
    try:
        total, written = run_data_extraction(input_path, output_path, args.timeout)
        print(f"Extraction complete. Processed {total}, wrote {written} rows.")
        
        # Verify output
        if not output_path.exists():
            print("ERROR: Output file was not created.")
            sys.exit(1)
            
        # Validate output schema
        df_out = pd.read_parquet(output_path)
        required_cols = ['prompt_embedding', 'noise_level', 'routing_label', 'velocity_vector']
        missing = [c for c in required_cols if c not in df_out.columns]
        if missing:
            print(f"ERROR: Output missing columns: {missing}")
            sys.exit(1)
            
        print(f"Output validation passed. Shape: {df_out.shape}")
        
    except Exception as e:
        print(f"Task failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()