import os
import logging
import numpy as np
import pandas as pd
from pathlib import Path
from typing import List, Dict, Tuple, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def calculate_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    """
    Calculate R², MAE, and RMSE for a given set of predictions.

    Args:
        y_true: Array of true target values.
        y_pred: Array of predicted target values.

    Returns:
        Dictionary containing 'r2', 'mae', and 'rmse'.
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    if len(y_true) != len(y_pred):
        raise ValueError("y_true and y_pred must have the same length.")

    if np.any(np.isnan(y_true)) or np.any(np.isnan(y_pred)):
        raise ValueError("y_true and y_pred must not contain NaN values.")

    # R² Score
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    r2 = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0.0

    # MAE
    mae = np.mean(np.abs(y_true - y_pred))

    # RMSE
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    return {
        'r2': float(r2),
        'mae': float(mae),
        'rmse': float(rmse)
    }

def aggregate_fold_metrics(fold_metrics: List[Dict[str, float]]) -> Dict[str, Dict[str, float]]:
    """
    Aggregate metrics across multiple folds to compute mean and std.

    Args:
        fold_metrics: List of dictionaries, each containing 'r2', 'mae', 'rmse' for a fold.

    Returns:
        Dictionary with mean and std for each metric.
        Format: {'r2': {'mean': ..., 'std': ...}, 'mae': ..., 'rmse': ...}
    """
    if not fold_metrics:
        raise ValueError("fold_metrics list cannot be empty.")

    df = pd.DataFrame(fold_metrics)

    result = {}
    for metric in ['r2', 'mae', 'rmse']:
        result[metric] = {
            'mean': float(df[metric].mean()),
            'std': float(df[metric].std())
        }

    return result

def save_predictions(predictions_list: List[Dict], output_path: str) -> None:
    """
    Save predictions from all folds to a CSV file.

    Args:
        predictions_list: List of dictionaries, where each dictionary represents
                          a row of predictions (e.g., {'smiles': '...', 'true': ..., 'pred': ..., 'fold': ...}).
        output_path: Path to the output CSV file.
    """
    if not predictions_list:
        logger.warning("No predictions to save.")
        return

    df = pd.DataFrame(predictions_list)
    
    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    df.to_csv(output_path, index=False)
    logger.info(f"Predictions saved to {output_path}")

def main():
    """
    Main entry point for metrics calculation and saving predictions.
    This function assumes that training has already occurred and predictions
    are available in a structured format (e.g., loaded from training output or passed as arguments).
    
    For the purpose of this task implementation, this function demonstrates the logic
    that would be called by the training pipeline to aggregate metrics and save results.
    """
    # Example usage (to be replaced by actual integration with training.py)
    # In a real scenario, this would load predictions generated by run_scaffold_cv
    
    # Simulated fold results for demonstration of the API
    mock_predictions = [
        {'smiles': 'CCO', 'true': 0.5, 'pred': 0.52, 'fold': 1, 'model': 'GCN'},
        {'smiles': 'CCCO', 'true': 0.4, 'pred': 0.38, 'fold': 1, 'model': 'GCN'},
        {'smiles': 'CCCCO', 'true': 0.3, 'pred': 0.32, 'fold': 2, 'model': 'RF'},
        {'smiles': 'CCCCCO', 'true': 0.2, 'pred': 0.21, 'fold': 2, 'model': 'RF'},
    ]
    
    output_file = "data/processed/predictions.csv"
    
    # Save predictions
    save_predictions(mock_predictions, output_file)
    
    # Calculate metrics for each fold (simulated)
    fold_1_metrics = calculate_metrics([0.5, 0.4], [0.52, 0.38])
    fold_2_metrics = calculate_metrics([0.3, 0.2], [0.32, 0.21])
    
    all_metrics = [fold_1_metrics, fold_2_metrics]
    aggregated = aggregate_fold_metrics(all_metrics)
    
    logger.info(f"Aggregated Metrics: {aggregated}")
    
    # In a full pipeline, the aggregated metrics would be saved to a separate file
    # or returned to the reporting module.
    return aggregated

if __name__ == "__main__":
    main()