import os
import logging
import pandas as pd
from pathlib import Path
from typing import Optional

from analysis.feature_selection import save_selection_frequency, load_split_data
from config import get_artifacts_path

logger = logging.getLogger(__name__)

def load_selection_frequency_input(file_path: Optional[str] = None) -> pd.DataFrame:
    """
    Load the selection frequency CSV generated by feature_selection.py.
    
    Args:
        file_path: Optional path to the CSV file. If None, uses default path from config.
        
    Returns:
        DataFrame containing selection frequency data.
        
    Raises:
        FileNotFoundError: If the file does not exist.
    """
    if file_path is None:
        base_path = get_artifacts_path()
        file_path = os.path.join(base_path, "reports", "selection_frequency.csv")
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Selection frequency file not found: {file_path}")
    
    df = pd.read_csv(file_path)
    logger.info(f"Loaded selection frequency data from {file_path} with {len(df)} rows")
    return df

def generate_selection_frequency_report(
    input_file: Optional[str] = None,
    output_file: Optional[str] = None
) -> str:
    """
    Generate the final selection_frequency.csv report for T023.
    
    This function ensures the output file exists at the correct location
    with the required columns: feature_id, threshold, frequency.
    
    Args:
        input_file: Path to source selection frequency data (if different from default).
        output_file: Path to write the final report. Defaults to artifacts/reports/selection_frequency.csv.
        
    Returns:
        Path to the generated report file.
    """
    # Load the data generated by the feature selection pipeline
    try:
        df = load_selection_frequency_input(input_file)
    except FileNotFoundError as e:
        logger.error(str(e))
        # If the file doesn't exist yet, we assume the pipeline hasn't run.
        # However, T023 is to GENERATE the file. If the source is missing, 
        # we cannot fabricate data. We raise the error.
        raise e

    # Validate required columns
    required_cols = {'feature_id', 'threshold', 'frequency'}
    if not required_cols.issubset(df.columns):
        missing = required_cols - set(df.columns)
        raise ValueError(f"Selection frequency data missing required columns: {missing}")

    # Ensure correct data types
    df['feature_id'] = df['feature_id'].astype(str)
    df['threshold'] = df['threshold'].astype(float)
    df['frequency'] = df['frequency'].astype(float)

    # Sort for readability: by threshold, then by frequency descending
    df_sorted = df.sort_values(by=['threshold', 'frequency'], ascending=[True, False])

    # Determine output path
    if output_file is None:
        base_path = get_artifacts_path()
        output_file = os.path.join(base_path, "reports", "selection_frequency.csv")
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    # Write the file
    df_sorted.to_csv(output_file, index=False)
    logger.info(f"Selection frequency report generated: {output_file} ({len(df_sorted)} rows)")
    
    return output_file

def main():
    """
    CLI entry point for generating the selection frequency report.
    """
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    try:
        output_path = generate_selection_frequency_report()
        print(f"Success: Report generated at {output_path}")
    except Exception as e:
        logger.error(f"Failed to generate selection frequency report: {e}")
        raise

if __name__ == "__main__":
    main()