"""
Modeling module for Plant Disease Resistance Prediction.

Implements Elastic-Net (for continuous phenotypes) and Gradient-Boosting
(for categorical/binary phenotypes) with 5-fold cross-validation as per FR-004.
Also implements null model baseline generation (random labels) for comparison.
"""
import os
import json
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, Any, Tuple, Optional, List
from sklearn.linear_model import ElasticNet, LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import accuracy_score, roc_auc_score, r2_score, make_scorer
from sklearn.preprocessing import StandardScaler
import warnings

from config import get_artifacts_path, get_reports_path
from utils.logging import get_logger, log_pipeline_step

logger = get_logger(__name__)


def load_split_data(
    processed_dir: Optional[Path] = None
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series]:
    """
    Load the split data from the preprocessing/split stage.
    Expects files generated by code/data/split.py:
    - train_X.csv, train_y.csv, val_X.csv, val_y.csv
    Returns:
      train_X, train_y, val_X (Note: val_y is returned as y for consistency with previous tasks, but modeling focuses on train)
      Actually, returning train_X, train_y, val_X, val_y to be complete.
    """
    if processed_dir is None:
        processed_dir = Path(get_reports_path()).parent.parent / "data" / "processed"

    train_X = pd.read_csv(processed_dir / "train_X.csv", index_col=0)
    train_y = pd.read_csv(processed_dir / "train_y.csv", index_col=0).squeeze()
    val_X = pd.read_csv(processed_dir / "val_X.csv", index_col=0)
    val_y = pd.read_csv(processed_dir / "val_y.csv", index_col=0).squeeze()

    return train_X, train_y, val_X, val_y


def detect_problem_type(y: pd.Series) -> str:
    """
    Detects if the problem is regression (continuous) or classification (categorical).
    Returns 'classification' if unique values <= 10 and dtype is not float64, else 'regression'.
    """
    unique_vals = y.nunique()
    if unique_vals <= 10 and y.dtype != 'float64':
        return 'classification'
    return 'regression'


def train_model(
    X: pd.DataFrame,
    y: pd.Series,
    problem_type: str,
    n_folds: int = 5,
    random_state: int = 42
) -> Dict[str, Any]:
    """
    Trains a model based on problem type with 5-fold CV.
    - Classification: Gradient Boosting Classifier
    - Regression: Elastic Net

    Returns a dict containing the model, cv_scores, and best_params.
    """
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    kfold = KFold(n_splits=n_folds, shuffle=True, random_state=random_state)

    if problem_type == 'classification':
        # Using GradientBoostingClassifier for robust performance
        # Hyperparameters can be tuned later, using defaults for now
        model = GradientBoostingClassifier(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=3,
            random_state=random_state
        )

        # Metric for CV
        if y.nunique() == 2:
            scoring = 'roc_auc'
        else:
            scoring = 'accuracy'

        cv_scores = cross_val_score(model, X_scaled, y, cv=kfold, scoring=scoring)
        model.fit(X_scaled, y)

        metric_name = "AUC" if y.nunique() == 2 else "Accuracy"
        mean_score = cv_scores.mean()
        std_score = cv_scores.std()

        return {
            "model": model,
            "scaler": scaler,
            "cv_scores": cv_scores,
            "mean_score": mean_score,
            "std_score": std_score,
            "metric_name": metric_name,
            "problem_type": problem_type
        }

    else:
        # Regression: Elastic Net
        model = ElasticNet(
            alpha=0.1,
            l1_ratio=0.5,
            random_state=random_state,
            max_iter=1000
        )

        cv_scores = cross_val_score(model, X_scaled, y, cv=kfold, scoring='r2')
        model.fit(X_scaled, y)

        return {
            "model": model,
            "scaler": scaler,
            "cv_scores": cv_scores,
            "mean_score": cv_scores.mean(),
            "std_score": cv_scores.std(),
            "metric_name": "R²",
            "problem_type": problem_type
        }


def train_null_model(
    X: pd.DataFrame,
    y: pd.Series,
    problem_type: str,
    n_folds: int = 5,
    random_state: int = 42
) -> Dict[str, Any]:
    """
    Trains a null model by shuffling labels (random permutation) to establish baseline.
    """
    logger.info(f"Training null model baseline with {y.nunique()} unique labels.")
    y_shuffled = y.sample(frac=1, random_state=random_state).reset_index(drop=True)

    return train_model(X, y_shuffled, problem_type, n_folds, random_state)


def evaluate_on_holdout(
    model_result: Dict[str, Any],
    X_test: pd.DataFrame,
    y_test: pd.Series
) -> Dict[str, float]:
    """
    Evaluates the trained model on the hold-out set.
    """
    model = model_result["model"]
    scaler = model_result["scaler"]
    problem_type = model_result["problem_type"]

    X_test_scaled = scaler.transform(X_test)

    y_pred = model.predict(X_test_scaled)

    if problem_type == 'classification':
        if y_test.nunique() == 2:
            # Ensure probabilities exist for AUC
            try:
                y_prob = model.predict_proba(X_test_scaled)[:, 1]
                auc = roc_auc_score(y_test, y_prob)
            except ValueError:
                auc = 0.5 # Fallback if singular
            accuracy = accuracy_score(y_test, y_pred)
            return {"accuracy": accuracy, "auc": auc}
        else:
            return {"accuracy": accuracy_score(y_test, y_pred)}
    else:
        r2 = r2_score(y_test, y_pred)
        return {"r2": r2}


def run_modeling_pipeline(
    train_X: pd.DataFrame,
    train_y: pd.Series,
    val_X: pd.DataFrame,
    val_y: pd.Series,
    output_dir: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Orchestrates the modeling process:
    1. Detect problem type.
    2. Train primary model with 5-fold CV.
    3. Train null model baseline.
    4. Evaluate primary model on hold-out set.
    5. Save metrics to artifacts/reports/model_metrics.json.
    """
    if output_dir is None:
        output_dir = Path(get_reports_path())
    output_dir.mkdir(parents=True, exist_ok=True)

    problem_type = detect_problem_type(train_y)
    logger.info(f"Detected problem type: {problem_type}")

    # Train Primary Model
    logger.info("Training primary model with 5-fold CV...")
    primary_result = train_model(train_X, train_y, problem_type)

    # Train Null Model
    logger.info("Training null model baseline...")
    null_result = train_null_model(train_X, train_y, problem_type)

    # Evaluate on Hold-out
    logger.info("Evaluating primary model on hold-out set...")
    holdout_metrics = evaluate_on_holdout(primary_result, val_X, val_y)

    # Compile Results
    metrics = {
        "problem_type": problem_type,
        "primary_model": {
            "metric_name": primary_result["metric_name"],
            "cv_mean": float(primary_result["mean_score"]),
            "cv_std": float(primary_result["std_score"]),
            "cv_scores": primary_result["cv_scores"].tolist()
        },
        "null_model": {
            "metric_name": null_result["metric_name"],
            "cv_mean": float(null_result["mean_score"]),
            "cv_std": float(null_result["std_score"]),
            "cv_scores": null_result["cv_scores"].tolist()
        },
        "holdout_metrics": {k: float(v) for k, v in holdout_metrics.items()},
        "comparison": {
            "cv_improvement": float(primary_result["mean_score"] - null_result["mean_score"])
        }
    }

    # Save Model Artifacts (pkl) and Metrics
    import pickle
    model_path = output_dir.parent / "models" / "final_model.pkl"
    model_path.parent.mkdir(parents=True, exist_ok=True)
    with open(model_path, "wb") as f:
        pickle.dump({
            "model": primary_result["model"],
            "scaler": primary_result["scaler"],
            "problem_type": problem_type
        }, f)

    metrics_path = output_dir / "model_metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)

    logger.info(f"Modeling complete. Metrics saved to {metrics_path}")
    logger.info(f"Model saved to {model_path}")

    return metrics


def main():
    """
    Main entry point for the modeling task.
    Loads split data, runs pipeline, and outputs metrics.
    """
    log_pipeline_step("START_MODELING")

    try:
        train_X, train_y, val_X, val_y = load_split_data()
        metrics = run_modeling_pipeline(train_X, train_y, val_X, val_y)
        print(json.dumps(metrics, indent=2))
    except Exception as e:
        logger.error(f"Modeling pipeline failed: {str(e)}")
        raise

    log_pipeline_step("END_MODELING")


if __name__ == "__main__":
    main()