"""
Success Criteria Check Module (T028b)

Implements logic to verify that at least 10 SNPs and 10 metabolites
remain significant across the entire sensitivity sweep (intersection
of significant features across all three thresholds).

Writes success status to artifacts/reports/success_criteria.json.
"""
import os
import logging
import json
from pathlib import Path
from typing import Dict, Set, List, Tuple
import pandas as pd

from config import get_artifacts_path, get_reports_path
from utils.logging import get_logger, log_pipeline_step

# Configure logger
logger = get_logger(__name__)

def load_selection_frequency(file_path: str = None) -> pd.DataFrame:
    """
    Load the selection frequency CSV generated by feature selection.

    Expected columns: feature_id, threshold, frequency
    """
    if file_path is None:
        reports_path = get_reports_path()
        file_path = str(reports_path / "selection_frequency.csv")

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Selection frequency file not found: {file_path}")

    df = pd.read_csv(file_path)
    logger.info(f"Loaded selection frequency data from {file_path} with {len(df)} rows")
    return df

def get_significant_features(df: pd.DataFrame, threshold: float) -> Set[str]:
    """
    Get the set of feature IDs that were selected at a specific threshold.

    A feature is considered selected if its frequency > 0 at the given threshold.
    """
    mask = (df['threshold'] == threshold) & (df['frequency'] > 0)
    features = set(df.loc[mask, 'feature_id'].unique())
    logger.info(f"Found {len(features)} significant features at threshold {threshold}")
    return features

def categorize_features(feature_ids: Set[str]) -> Tuple[Set[str], Set[str]]:
    """
    Separate features into SNPs and metabolites based on naming convention.

    Convention:
    - SNPs: feature_id starts with 'snp_'
    - Metabolites: feature_id starts with 'met_'
    """
    snps = set()
    metabolites = set()

    for fid in feature_ids:
        if fid.startswith('snp_'):
            snps.add(fid)
        elif fid.startswith('met_'):
            metabolites.add(fid)
        else:
            # Log unknown feature type but don't fail
            logger.warning(f"Unknown feature type for ID: {fid}")

    return snps, metabolize

def check_success_criteria(
    snp_count: int,
    metabolite_count: int,
    min_required: int = 10
) -> Tuple[bool, str]:
    """
    Check if the success criteria (SC-002) are met.

    Criteria: At least 10 SNPs AND 10 metabolites must remain significant
    across the entire sensitivity sweep.

    Returns:
        Tuple of (is_success, status_message)
    """
    snp_ok = snp_count >= min_required
    metabolite_ok = metabolite_count >= min_required
    is_success = snp_ok and metabolite_ok

    status_msg = (
        f"SNPs: {snp_count}/{min_required}, "
        f"Metabolites: {metabolite_count}/{min_required} -> "
        f"{'PASSED' if is_success else 'FAILED'}"
    )

    return is_success, status_msg

def write_success_report(
    is_success: bool,
    status_message: str,
    snp_count: int,
    metabolite_count: int,
    total_intersection: int,
    output_path: str = None
) -> str:
    """
    Write the success criteria check result to a JSON file.

    Output format:
    {
        "success_status": "PASSED" | "FAILED",
        "criteria": "SC-002",
        "details": {
            "min_required": 10,
            "snp_count": int,
            "metabolite_count": int,
            "total_intersection": int
        },
        "message": str,
        "timestamp": str
    }
    """
    if output_path is None:
        reports_path = get_reports_path()
        output_path = str(reports_path / "success_criteria.json")

    report = {
        "success_status": "PASSED" if is_success else "FAILED",
        "criteria": "SC-002",
        "details": {
            "min_required": 10,
            "snp_count": snp_count,
            "metabolite_count": metabolite_count,
            "total_intersection": total_intersection
        },
        "message": status_message,
        "timestamp": pd.Timestamp.now().isoformat()
    }

    # Ensure directory exists
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        json.dump(report, f, indent=2)

    logger.info(f"Success criteria report written to {output_path}")
    return output_path

def main():
    """
    Main entry point for the success criteria check.

    This function:
    1. Loads the selection frequency data
    2. Identifies features significant at each threshold
    3. Computes the intersection across all thresholds
    4. Categorizes into SNPs and metabolites
    5. Checks if counts meet the minimum requirement (>=10 each)
    6. Writes the result to success_criteria.json
    """
    log_pipeline_step("success_criteria_check", "start")

    try:
        # Load selection frequency data
        df = load_selection_frequency()

        # Get unique thresholds
        thresholds = sorted(df['threshold'].unique())
        if len(thresholds) < 3:
            logger.warning(f"Expected 3 thresholds, found {len(thresholds)}. Proceeding with available thresholds.")

        # Get significant features at each threshold
        significant_sets = []
        for thresh in thresholds:
          sig_set = get_significant_features(df, thresh)
          significant_sets.append(sig_set)
          logger.info(f"Threshold {thresh}: {len(sig_set)} features")

        # Compute intersection across ALL thresholds
        if len(significant_sets) > 0:
            intersection = set.intersection(*significant_sets)
        else:
            intersection = set()

        logger.info(f"Intersection across {len(thresholds)} thresholds: {len(intersection)} features")

        # Categorize into SNPs and metabolites
        snps, metabolites = categorize_features(intersection)

        # Check success criteria
        is_success, status_msg = check_success_criteria(
            snp_count=len(snps),
            metabolite_count=len(metabolites)
        )

        # Log warning if failed
        if not is_success:
            logger.warning(f"SC-002 FAILED: {status_msg}")
        else:
            logger.info(f"SC-002 PASSED: {status_msg}")

        # Write report
        output_path = write_success_report(
            is_success=is_success,
            status_message=status_msg,
            snp_count=len(snps),
            metabolite_count=len(metabolites),
            total_intersection=len(intersection)
        )

        log_pipeline_step("success_criteria_check", "complete", {"output_file": output_path})

    except Exception as e:
        logger.error(f"Error during success criteria check: {e}", exc_info=True)
        # Re-raise to allow pipeline to handle the error appropriately
        raise

if __name__ == "__main__":
    main()
