"""
Contract tests to validate the project's data schema and directory structure.
This ensures that the project adheres to the defined data model and file organization.
Specifically validates the structure of the final report as defined in data-model.md.
"""
import os
import pytest
from pathlib import Path
import json
from typing import Any, Dict, List

# Import config to resolve paths consistently with the pipeline
import sys
# Add the code directory to the path to allow importing config
code_root = Path(__file__).resolve().parent.parent.parent / "code"
if str(code_root) not in sys.path:
    sys.path.insert(0, str(code_root))

from config import get_env

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

def test_required_directories_exist():
    """
    Contract test: Verify that all required directories exist at the project root.
    This is a hard requirement for the pipeline to function.
    """
    required_dirs = [
        "output",
        "output/figures",
        "tests",
        "tests/unit",
        "tests/contract",
        "logs",
        "data/processed",
    ]

    missing_dirs = []
    for dir_path in required_dirs:
        full_path = PROJECT_ROOT / dir_path
        if not full_path.exists() or not full_path.is_dir():
            missing_dirs.append(dir_path)

    assert len(missing_dirs) == 0, f"Missing required directories: {missing_dirs}"

def test_output_schema_structure():
    """
    Contract test: Verify that output files follow the expected naming convention.
    This test passes if the directory exists; specific file validation happens
    when the files are generated by the pipeline tasks.
    """
    output_dir = PROJECT_ROOT / "output"

    assert output_dir.exists(), "output/ directory must exist"
    assert output_dir.is_dir(), "output/ must be a directory"

def test_data_processed_schema():
    """
    Contract test: Verify that data/processed/ exists for storing intermediate results.
    """
    processed_dir = PROJECT_ROOT / "data" / "processed"

    assert processed_dir.exists(), "data/processed/ directory must exist"
    assert processed_dir.is_dir(), "data/processed/ must be a directory"

def _load_final_report() -> Dict[str, Any]:
    """
    Helper to load the final report. Returns None if the file does not exist.
    """
    report_path = PROJECT_ROOT / "output" / "final_report.json"
    if not report_path.exists():
        return None
    with open(report_path, 'r') as f:
        return json.load(f)

def test_final_report_structure():
    """
    Contract test: Validate the structure of output/final_report.json against data-model.md.
    The final report must contain specific top-level keys and nested structures
    reflecting the correlation, timescale, and sensitivity analyses.
    """
    report = _load_final_report()

    # If the report doesn't exist yet, this test might be skipped or expected to fail
    # depending on the CI state. However, per strict contract testing, we assert existence
    # if the pipeline is expected to have run (T038 completes before T039).
    assert report is not None, "output/final_report.json must exist for contract validation"

    # Top-level keys required by data-model.md
    required_top_keys = [
        "metadata",
        "correlation_results",
        "timescale_alignment",
        "sensitivity_analysis",
        "stability_check",
        "status"
    ]

    missing_keys = [k for k in required_top_keys if k not in report]
    assert len(missing_keys) == 0, f"Final report missing required top-level keys: {missing_keys}"

    # Validate metadata structure
    metadata = report["metadata"]
    assert "pipeline_version" in metadata
    assert "timestamp" in metadata
    assert "datasets_included" in metadata
    assert isinstance(metadata["datasets_included"], list)

    # Validate correlation_results structure
    corr = report["correlation_results"]
    assert "overall" in corr
    assert "by_condition" in corr
    # Overall must have rho and p-value
    assert "rho" in corr["overall"]
    assert "p_value" in corr["overall"]
    assert "permutation_p_value" in corr["overall"]

    # Validate timescale_alignment structure
    timescale = report["timescale_alignment"]
    assert "alignment_status" in timescale
    assert "temporal_validation_status" in timescale
    assert timescale["temporal_validation_status"] in ["VALID", "INSUFFICIENT"]

    # Validate sensitivity_analysis structure
    sens = report["sensitivity_analysis"]
    assert "thresholds_tested" in sens
    assert isinstance(sens["thresholds_tested"], list)
    assert "results_by_threshold" in sens
    assert "stability_flag" in sens

    # Validate stability_check structure
    stab = report["stability_check"]
    assert "significant_count" in stab
    assert "max_rho_diff" in stab
    assert "is_stable" in stab

def test_final_report_data_types():
    """
    Contract test: Ensure numeric fields in the final report are actually numeric.
    """
    report = _load_final_report()
    if report is None:
        pytest.skip("final_report.json not yet generated")

    # Check correlation numeric fields
    rho = report["correlation_results"]["overall"]["rho"]
    assert isinstance(rho, (int, float)), "rho must be numeric"

    p_val = report["correlation_results"]["overall"]["p_value"]
    assert isinstance(p_val, (int, float)), "p_value must be numeric"

    # Check timescale alignment numeric fields (if present)
    if "drift_timescale_slope" in report["timescale_alignment"]:
        slope = report["timescale_alignment"]["drift_timescale_slope"]
        assert isinstance(slope, (int, float)), "drift_timescale_slope must be numeric"

    # Check sensitivity numeric fields
    if "results_by_threshold" in report["sensitivity_analysis"]:
        for threshold, res in report["sensitivity_analysis"]["results_by_threshold"].items():
            if "rho" in res:
                assert isinstance(res["rho"], (int, float)), f"rho for threshold {threshold} must be numeric"
                assert isinstance(res["p_value"], (int, float)), f"p_value for threshold {threshold} must be numeric"