"""
CLI entry point for the llmXive Predicting Chemical Reaction Yields project.
Provides argument parsing and dispatching for state management and other tasks.
"""
import argparse
import sys
import logging
from pathlib import Path

from src.utils.state_manager import update_state, load_state, log_task_start, log_task_complete
from src.utils.seeds import set_seed

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

def parse_args(args=None):
    """
    Parse command line arguments.
    
    Args:
        args: List of arguments (defaults to sys.argv[1:])
        
    Returns:
        Parsed namespace object
    """
    parser = argparse.ArgumentParser(
        prog='main',
        description='CLI tool for managing the llmXive chemical reaction yield prediction pipeline.'
    )
    
    # Global options
    parser.add_argument(
        '--seed',
        type=int,
        default=None,
        help='Random seed for reproducibility. If not provided, uses config or environment.'
    )
    
    # Subcommands
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # update-state command
    update_parser = subparsers.add_parser(
        'update-state',
        help='Update project state (hashes, timestamps) after a task or pipeline run.'
    )
    update_parser.add_argument(
        '--task-id',
        type=str,
        required=True,
        help='Task ID being completed (e.g., T009)'
    )
    update_parser.add_argument(
        '--status',
        type=str,
        choices=['start', 'complete', 'fail'],
        default='complete',
        help='Task status to log'
    )
    update_parser.add_argument(
        '--output-files',
        type=str,
        nargs='*',
        default=[],
        help='List of output file paths generated by this task (relative to project root)'
    )
    update_parser.add_argument(
        '--force',
        action='store_true',
        help='Force update even if state file is missing or corrupted'
    )
    
    # status command
    status_parser = subparsers.add_parser(
        'status',
        help='Display current project state summary.'
    )
    
    # reset-state command
    reset_parser = subparsers.add_parser(
        'reset-state',
        help='Reset project state to initial conditions.'
    )
    
    if args is None:
        args = sys.argv[1:]
        
    return parser.parse_args(args)

def handle_update_state(args):
    """
    Handle the update-state subcommand.
    
    Args:
        args: Parsed arguments namespace
        
    Returns:
        0 on success, 1 on failure
    """
    logger.info(f"Updating state for task {args.task_id} with status {args.status}")
    
    try:
        # Set seed if provided
        if args.seed is not None:
            set_seed(args.seed)
            logger.info(f"Set random seed to {args.seed}")
        
        # Load current state
        state = load_state()
        
        # Log task start or complete
        if args.status == 'start':
            log_task_start(state, args.task_id)
        elif args.status == 'complete':
            log_task_complete(state, args.task_id, output_files=args.output_files)
        elif args.status == 'fail':
            log_task_complete(state, args.task_id, status='failed')
        
        # Update state hash and timestamp
        update_state(state, force=args.force)
        
        # Save updated state
        from src.utils.state_manager import save_state
        save_state(state)
        
        logger.info(f"State updated successfully for task {args.task_id}")
        return 0
        
    except Exception as e:
        logger.error(f"Failed to update state: {e}")
        return 1

def handle_status(args):
    """
    Handle the status subcommand.
    
    Args:
        args: Parsed arguments namespace
        
    Returns:
        0 on success, 1 on failure
    """
    try:
        state = load_state()
        from src.utils.state_manager import get_state_summary
        summary = get_state_summary(state)
        print(summary)
        return 0
    except Exception as e:
        logger.error(f"Failed to load state: {e}")
        return 1

def handle_reset_state(args):
    """
    Handle the reset-state subcommand.
    
    Args:
        args: Parsed arguments namespace
        
    Returns:
        0 on success, 1 on failure
    """
    try:
        from src.utils.state_manager import reset_state
        reset_state()
        logger.info("Project state reset successfully")
        return 0
    except Exception as e:
        logger.error(f"Failed to reset state: {e}")
        return 1

def main(args=None):
    """
    Main entry point for the CLI.
    
    Args:
        args: List of arguments (defaults to sys.argv[1:])
        
    Returns:
        Exit code (0 for success, non-zero for failure)
    """
    parsed_args = parse_args(args)
    
    if parsed_args.seed is not None:
        set_seed(parsed_args.seed)
    
    if parsed_args.command == 'update-state':
        return handle_update_state(parsed_args)
    elif parsed_args.command == 'status':
        return handle_status(parsed_args)
    elif parsed_args.command == 'reset-state':
        return handle_reset_state(parsed_args)
    else:
        # No command provided, show help
        parsed_args_parser = parse_args(['--help'])
        return 0

if __name__ == '__main__':
    sys.exit(main())