"""
Schema validation utilities for the llmXive pipeline.

This module defines dataclasses for TokenSequence, ValidityLabel, and EntropyProfile,
along with validation functions to ensure data integrity against expected schemas.
"""
import json
import re
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any, Union, Tuple
from pathlib import Path
import logging

# Configure logger
logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# Data Classes (Schemas)
# -----------------------------------------------------------------------------

@dataclass
class TokenSequence:
    """
    Represents a sequence of tokens generated by the model.
    
    Attributes:
        prompt_id: Unique identifier for the prompt.
        tokens: List of token strings.
        task_type: Type of task (e.g., 'gsm8k', 'minigrid').
        sequence_id: Optional unique ID for this specific sequence instance.
    """
    prompt_id: str
    tokens: List[str]
    task_type: str
    sequence_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'TokenSequence':
        required = ['prompt_id', 'tokens', 'task_type']
        for key in required:
            if key not in data:
                raise ValueError(f"Missing required field in TokenSequence: {key}")
        
        # Validate types
        if not isinstance(data['prompt_id'], str):
            raise TypeError("TokenSequence.prompt_id must be a string")
        if not isinstance(data['tokens'], list) or not all(isinstance(t, str) for t in data['tokens']):
            raise TypeError("TokenSequence.tokens must be a list of strings")
        if not isinstance(data['task_type'], str):
            raise TypeError("TokenSequence.task_type must be a string")
        
        return cls(
            prompt_id=data['prompt_id'],
            tokens=data['tokens'],
            task_type=data['task_type'],
            sequence_id=data.get('sequence_id')
        )

@dataclass
class ValidityLabel:
    """
    Represents the validity label for a token sequence or individual tokens.
    
    Attributes:
        prompt_id: ID of the prompt this label belongs to.
        sequence_id: ID of the sequence this label belongs to.
        validity: Boolean indicating if the sequence/tokens are valid (True) or not (False).
        reason: Optional string explaining the validity decision.
        ground_truth_match: Boolean indicating if a match with ground truth was found.
    """
    prompt_id: str
    validity: bool
    sequence_id: Optional[str] = None
    reason: Optional[str] = None
    ground_truth_match: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ValidityLabel':
        required = ['prompt_id', 'validity']
        for key in required:
            if key not in data:
                raise ValueError(f"Missing required field in ValidityLabel: {key}")
        
        if not isinstance(data['prompt_id'], str):
            raise TypeError("ValidityLabel.prompt_id must be a string")
        if not isinstance(data['validity'], bool):
            raise TypeError("ValidityLabel.validity must be a boolean")
        
        return cls(
            prompt_id=data['prompt_id'],
            validity=data['validity'],
            sequence_id=data.get('sequence_id'),
            reason=data.get('reason'),
            ground_truth_match=data.get('ground_truth_match', False)
        )

@dataclass
class LayerEntropy:
    """
    Represents entropy for a single layer.
    """
    layer_index: int
    entropy_value: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'LayerEntropy':
        required = ['layer_index', 'entropy_value']
        for key in required:
            if key not in data:
                raise ValueError(f"Missing required field in LayerEntropy: {key}")
        
        if not isinstance(data['layer_index'], int):
            raise TypeError("LayerEntropy.layer_index must be an integer")
        if not isinstance(data['entropy_value'], (int, float)):
            raise TypeError("LayerEntropy.entropy_value must be a number")
        
        return cls(
            layer_index=data['layer_index'],
            entropy_value=float(data['entropy_value'])
        )

@dataclass
class EntropyProfile:
    """
    Represents the entropy profile for a sequence across all layers.
    
    Attributes:
        prompt_id: ID of the prompt.
        sequence_id: ID of the sequence.
        layers: List of LayerEntropy objects.
        token_index: Optional index of the token this profile corresponds to (for per-token entropy).
        avg_entropy: Optional pre-calculated average entropy.
    """
    prompt_id: str
    layers: List[LayerEntropy]
    sequence_id: Optional[str] = None
    token_index: Optional[int] = None
    avg_entropy: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            'prompt_id': self.prompt_id,
            'sequence_id': self.sequence_id,
            'token_index': self.token_index,
            'layers': [l.to_dict() for l in self.layers],
            'avg_entropy': self.avg_entropy
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'EntropyProfile':
        required = ['prompt_id', 'layers']
        for key in required:
            if key not in data:
                raise ValueError(f"Missing required field in EntropyProfile: {key}")
        
        if not isinstance(data['prompt_id'], str):
            raise TypeError("EntropyProfile.prompt_id must be a string")
        
        if not isinstance(data['layers'], list):
            raise TypeError("EntropyProfile.layers must be a list")
        
        parsed_layers = []
        for i, layer_data in enumerate(data['layers']):
            if not isinstance(layer_data, dict):
                raise TypeError(f"EntropyProfile.layers[{i}] must be a dict")
            parsed_layers.append(LayerEntropy.from_dict(layer_data))
        
        return cls(
            prompt_id=data['prompt_id'],
            sequence_id=data.get('sequence_id'),
            token_index=data.get('token_index'),
            layers=parsed_layers,
            avg_entropy=data.get('avg_entropy')
        )

# -----------------------------------------------------------------------------
# Validation Functions
# -----------------------------------------------------------------------------

def validate_token_sequence(data: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """
    Validates a dictionary against the TokenSequence schema.
    
    Returns:
        Tuple of (is_valid, error_message). If valid, error_message is None.
    """
    try:
        TokenSequence.from_dict(data)
        return True, None
    except (ValueError, TypeError) as e:
        return False, str(e)

def validate_validity_label(data: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """
    Validates a dictionary against the ValidityLabel schema.
    
    Returns:
        Tuple of (is_valid, error_message). If valid, error_message is None.
    """
    try:
        ValidityLabel.from_dict(data)
        return True, None
    except (ValueError, TypeError) as e:
        return False, str(e)

def validate_entropy_profile(data: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """
    Validates a dictionary against the EntropyProfile schema.
    
    Returns:
        Tuple of (is_valid, error_message). If valid, error_message is None.
    """
    try:
        profile = EntropyProfile.from_dict(data)
        # Additional check: ensure layers are not empty if present
        if not profile.layers:
            return False, "EntropyProfile must have at least one layer"
        
        # Check for None values in entropy values (constraint from T023)
        for layer in profile.layers:
            if layer.entropy_value is None:
                return False, f"Layer {layer.layer_index} has None entropy value"
            
        return True, None
    except (ValueError, TypeError) as e:
        return False, str(e)

def validate_merged_record(data: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """
    Validates a merged record containing TokenSequence, ValidityLabel, and EntropyProfile data.
    Expected fields: prompt_id, tokens, validity, layers (or entropy_layers).
    
    Returns:
        Tuple of (is_valid, error_message).
    """
    required_fields = ['prompt_id', 'tokens', 'validity']
    for field_name in required_fields:
        if field_name not in data:
            return False, f"Missing required field in merged record: {field_name}"
    
    # Validate prompt_id type
    if not isinstance(data['prompt_id'], str):
        return False, "prompt_id must be a string"
    
    # Validate tokens type
    if not isinstance(data['tokens'], list):
        return False, "tokens must be a list"
    
    # Validate validity type
    if not isinstance(data['validity'], bool):
        return False, "validity must be a boolean"
    
    # Validate entropy layers if present
    if 'layers' in data:
        is_valid, err = validate_entropy_profile({'prompt_id': data['prompt_id'], 'layers': data['layers']})
        if not is_valid:
            return False, f"Invalid entropy layers: {err}"
    
    return True, None

def validate_json_schema(data: Dict[str, Any], schema_type: str) -> Tuple[bool, Optional[str]]:
    """
    Generic dispatcher to validate data against a specific schema type.
    
    Args:
        data: The dictionary to validate.
        schema_type: One of 'token_sequence', 'validity_label', 'entropy_profile', 'merged'.
        
    Returns:
        Tuple of (is_valid, error_message).
    """
    if schema_type == 'token_sequence':
        return validate_token_sequence(data)
    elif schema_type == 'validity_label':
        return validate_validity_label(data)
    elif schema_type == 'entropy_profile':
        return validate_entropy_profile(data)
    elif schema_type == 'merged':
        return validate_merged_record(data)
    else:
        return False, f"Unknown schema type: {schema_type}"

def load_and_validate_jsonl(file_path: Union[str, Path], schema_type: str) -> List[Dict[str, Any]]:
    """
    Loads a JSONL file and validates each record against the specified schema.
    
    Args:
        file_path: Path to the JSONL file.
        schema_type: The schema type to validate against.
        
    Returns:
        List of validated records.
        
    Raises:
        ValueError: If any record fails validation.
        FileNotFoundError: If the file does not exist.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    
    records = []
    with open(path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                raise ValueError(f"JSON decode error at line {line_num}: {e}")
            
            is_valid, error_msg = validate_json_schema(record, schema_type)
            if not is_valid:
                raise ValueError(f"Validation failed at line {line_num}: {error_msg}")
            
            records.append(record)
    
    logger.info(f"Loaded and validated {len(records)} records from {path} ({schema_type})")
    return records