"""
data_loader.py
----------------
Downloads a small, reproducible sample from the HuggingFace ``codeparrot/github-code``
dataset (or whatever dataset name is configured) and stores it as a CSV
``data/raw/github-code-sample.csv``.  The function ``download_and_save_sample``
is deliberately tolerant to a variety of call signatures required by the
contract tests.
"""
from __future__ import annotations

import csv
import logging
from pathlib import Path
from typing import Optional

from datasets import load_dataset

from config import get_all_config

logger = logging.getLogger(__name__)


def download_and_save_sample(
    sample_size: int = 100,
    output_path: Optional[Path] = None,
    *,
    dataset_name: Optional[str] = None,
) -> Path:
    """
    Download a streaming subset of the configured dataset and write it to CSV.

    Parameters
    ----------
    sample_size: int, optional
        Number of files to sample.  Defaults to 100.
    output_path: Path or None, optional
        Destination CSV file.  If omitted the default
        ``data/raw/github-code-sample.csv`` is used.
    dataset_name: str or None, optional (keyword‑only)
        Override the dataset name from the config.  Primarily useful for tests.

    Returns
    -------
    Path
        Path to the generated CSV file.
    """
    cfg = get_all_config()
    dataset_name = dataset_name or cfg.get("dataset_name", "codeparrot/github-code")
    output_path = Path(output_path) if output_path else Path(
        "data/raw/github-code-sample.csv"
    )

    logger.info(
        "Downloading %d samples from %s → %s",
        sample_size,
        dataset_name,
        output_path,
    )

    # ``load_dataset`` with ``streaming=True`` avoids pulling the whole 500 MB.
    ds = load_dataset(dataset_name, split="train", streaming=True)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["file_path", "content"])

        for idx, item in enumerate(ds):
            if idx >= sample_size:
                break
            # The dataset provides a ``content`` field (the raw source) and a
            # ``path`` or ``filename`` field.  We fall back to an autogenerated
            # name if none is present.
            file_path = item.get("path") or item.get("filename") or f"sample_{idx}.py"
            content = item.get("content") or ""
            writer.writerow([file_path, content])

    logger.info("Sample saved to %s", output_path)
    return output_path