import os
import json
import logging
import pandas as pd
import numpy as np
import pymc as pm
import arviz as az
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple

from config import load_config
from state_manager import load_artifacts_state, save_artifacts_state, register_artifact, compute_sha256

# Ensure logging is configured
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_results_data(results_path: str = "data/results.csv") -> pd.DataFrame:
    """Load the results CSV file generated by the main pipeline."""
    if not os.path.exists(results_path):
        raise FileNotFoundError(f"Results file not found at {results_path}. Run the main pipeline first.")
    df = pd.read_csv(results_path)
    logger.info(f"Loaded {len(df)} rows from {results_path}")
    return df

def load_subspace_ranks(ranks_path: str = "data/subspace_ranks.json") -> Dict[str, Any]:
    """Load the subspace ranks computed from the LoRA adapter."""
    if not os.path.exists(ranks_path):
        raise FileNotFoundError(f"Subspace ranks file not found at {ranks_path}. Run T009b first.")
    with open(ranks_path, 'r') as f:
        data = json.load(f)
    logger.info(f"Loaded subspace ranks for {len(data.get('ranks', {}))} effects")
    return data

def prepare_correlation_data(results_df: pd.DataFrame, ranks_data: Dict[str, Any]) -> pd.DataFrame:
    """Merge results with subspace ranks for correlation analysis."""
    ranks = ranks_data.get('ranks', {})
    # Create a mapping from effect name to rank
    rank_map = {k: v for k, v in ranks.items()}
    
    # Add rank column to results if effect is present
    results_df['subspace_rank'] = results_df['effect'].map(rank_map)
    
    # Drop rows where rank is missing (effect not in ranks data)
    results_df = results_df.dropna(subset=['subspace_rank'])
    logger.info(f"Prepared {len(results_df)} rows for correlation analysis")
    return results_df

def run_bayesian_hierarchical_model(
    data: pd.DataFrame,
    model_path: str = "state/bayesian_model.nc",
    posterior_samples: int = 1000,
    tune: int = 1000
) -> Dict[str, Any]:
    """
    Run the Bayesian Hierarchical Model to analyze quantization effects.
    Returns a dictionary containing model diagnostics and posterior statistics.
    """
    logger.info("Starting Bayesian Hierarchical Model...")
    
    # Prepare data for PyMC
    # We model: similarity_score ~ Normal(mu_quant, sigma)
    # where mu_quant = beta_0 + beta_quant * quantization_level
    # and we include random effects for prompts to account for nested structure
    
    # Extract unique levels
    quant_levels = data['quantization_level'].unique()
    prompt_levels = data['prompt'].unique()
    
    # Map to integers for PyMC
    data = data.copy()
    data['quant_idx'] = pd.Categorical(data['quantization_level']).codes
    data['prompt_idx'] = pd.Categorical(data['prompt']).codes
    
    # Define the model
    with pm.Model() as model:
        # Priors
        beta_0 = pm.Normal('beta_0', mu=0, sigma=1)  # Intercept
        beta_quant = pm.Normal('beta_quant', mu=0, sigma=1)  # Quantization effect
        sigma = pm.HalfNormal('sigma', sigma=1)  # Residual std
        
        # Random effects for prompts
        sigma_prompt = pm.HalfNormal('sigma_prompt', sigma=1)
        prompt_effects = pm.Normal('prompt_effects', mu=0, sigma=sigma_prompt, 
                                 shape=len(prompt_levels))
        
        # Linear predictor
        mu = (beta_0 + 
              beta_quant * data['quant_idx'].values + 
              prompt_effects[data['prompt_idx'].values])
        
        # Likelihood
        y_obs = pm.Normal('y_obs', mu=mu, sigma=sigma, observed=data['similarity_score'].values)
        
        # Sample
        logger.info(f"Sampling {posterior_samples} posterior samples with {tune} tune steps...")
        trace = pm.sample(
            draws=posterior_samples,
            tune=tune,
            chains=2,
            target_accept=0.9,
            random_seed=42,
            progressbar=True
        )
    
    # Compute diagnostics
    logger.info("Computing posterior statistics and diagnostics...")
    
    # Posterior width for the quantization effect (beta_quant)
    beta_quant_samples = trace.posterior['beta_quant'].values.flatten()
    posterior_width = np.ptp(beta_quant_samples)  # max - min
    # Or use credible interval width:
    ci = az.hdi(trace, var_names=['beta_quant'])
    credible_interval_width = float(ci['beta_quant']['beta_quant'].diff().values[0])
    
    # Store posterior width for T026 check
    posterior_stats = {
        'beta_quant_mean': float(np.mean(beta_quant_samples)),
        'beta_quant_std': float(np.std(beta_quant_samples)),
        'credible_interval_95': {
            'lower': float(ci['beta_quant']['beta_quant'].values[0]),
            'upper': float(ci['beta_quant']['beta_quant'].values[1])
        },
        'credible_interval_width': credible_interval_width,
        'posterior_width_max_minus_min': float(posterior_width),
        'r_hat': float(az.rhat(trace)['beta_quant'].values[0]),
        'n_eff': float(az.ess(trace)['beta_quant'].values[0])
    }
    
    # Check for underpowered result (FR-014)
    # Using credible interval width as the metric for "width"
    is_underpowered = credible_interval_width > 0.2
    
    model_info = {
        'model_path': model_path,
        'posterior_stats': posterior_stats,
        'underpowered': is_underpowered,
        'underpowered_reason': f"Credible interval width ({credible_interval_width:.4f}) > 0.2 threshold" if is_underpowered else None,
        'samples': posterior_samples,
        'tune': tune,
        'convergence': {
            'r_hat': posterior_stats['r_hat'],
            'effective_n': posterior_stats['n_eff']
        }
    }
    
    # Save trace for future reference
    if model_path:
        Path(model_path).parent.mkdir(parents=True, exist_ok=True)
        az.to_netcdf(trace, model_path)
        logger.info(f"Saved model trace to {model_path}")
    
    return model_info

def compute_correlation_stats(data: pd.DataFrame) -> Dict[str, Any]:
    """
    Compute correlation between subspace rank and concept bleeding magnitude.
    Concept bleeding is measured by CESR score (higher = more bleeding).
    """
    logger.info("Computing correlation between subspace rank and concept bleeding...")
    
    # Filter for quantized results (INT8, INT4) to measure bleeding
    quant_data = data[data['quantization_level'].isin(['INT8', 'INT4'])].copy()
    
    if len(quant_data) < 2:
        logger.warning("Not enough data points for correlation analysis")
        return {
            'correlation': None,
            'p_value': None,
            'n_samples': len(quant_data),
            'message': "Insufficient data"
        }
    
    # Compute correlation
    correlation, p_value = pearsonr(quant_data['subspace_rank'], quant_data['cesr_score'])
    
    # Bayesian correlation estimation (optional but more robust)
    # For simplicity, we'll use the frequentist result here
    # In a full implementation, we could use pymc to estimate the posterior of the correlation coefficient
    
    result = {
        'correlation': float(correlation),
        'p_value': float(p_value),
        'n_samples': len(quant_data),
        'interpretation': "Significant" if p_value < 0.05 else "Not significant",
        'direction': "Positive" if correlation > 0 else "Negative" if correlation < 0 else "None"
    }
    
    logger.info(f"Correlation: {correlation:.4f}, p-value: {p_value:.4f}")
    return result

def main(
    results_path: str = "data/results.csv",
    ranks_path: str = "data/subspace_ranks.json",
    output_path: str = "data/analysis_results.json",
    model_path: str = "state/bayesian_model.nc"
) -> Dict[str, Any]:
    """
    Main function to run the full statistical analysis pipeline.
    
    1. Load results and subspace ranks
    2. Run Bayesian Hierarchical Model
    3. Check posterior width (FR-014) and flag if underpowered
    4. Compute correlation between subspace rank and concept bleeding
    5. Save results to analysis_results.json
    """
    logger.info("Starting statistical analysis pipeline...")
    
    # Load data
    results_df = load_results_data(results_path)
    ranks_data = load_subspace_ranks(ranks_path)
    
    # Prepare correlation data
    correlation_data = prepare_correlation_data(results_df, ranks_data)
    
    # Run Bayesian model
    model_results = run_bayesian_hierarchical_model(correlation_data, model_path=model_path)
    
    # Compute correlation stats
    correlation_results = compute_correlation_stats(correlation_data)
    
    # Compile final results
    analysis_results = {
        'model_results': model_results,
        'correlation_results': correlation_results,
        'fr14_status': {
            'is_underpowered': model_results['underpowered'],
            'reason': model_results.get('underpowered_reason'),
            'threshold': 0.2,
            'metric_value': model_results['posterior_stats']['credible_interval_width']
        },
        'data_summary': {
            'total_samples': len(results_df),
            'quantized_samples': len(results_df[results_df['quantization_level'].isin(['INT8', 'INT4'])]),
            'fp16_samples': len(results_df[results_df['quantization_level'] == 'FP16']),
            'unique_effects': results_df['effect'].nunique(),
            'unique_prompts': results_df['prompt'].nunique()
        }
    }
    
    # Save results
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(analysis_results, f, indent=2)
    
    logger.info(f"Analysis results saved to {output_path}")
    
    # Log FR-014 status
    if analysis_results['fr14_status']['is_underpowered']:
        logger.warning(f"FR-014: Result is UNDERPOWERED. {analysis_results['fr14_status']['reason']}")
    else:
        logger.info("FR-014: Result is adequately powered.")
    
    return analysis_results

if __name__ == "__main__":
    # Default paths
    results_file = "data/results.csv"
    ranks_file = "data/subspace_ranks.json"
    output_file = "data/analysis_results.json"
    model_file = "state/bayesian_model.nc"
    
    results = main(
        results_path=results_file,
        ranks_path=ranks_file,
        output_path=output_file,
        model_path=model_file
    )
    
    print("\n=== Analysis Summary ===")
    print(f"Total samples: {results['data_summary']['total_samples']}")
    print(f"Quantized samples: {results['data_summary']['quantized_samples']}")
    print(f"FP16 samples: {results['data_summary']['fp16_samples']}")
    print(f"Unique effects: {results['data_summary']['unique_effects']}")
    print(f"Unique prompts: {results['data_summary']['unique_prompts']}")
    print(f"\nBayesian Model:")
    print(f"  Quantization effect mean: {results['model_results']['posterior_stats']['beta_quant_mean']:.4f}")
    print(f"  95% CI: [{results['model_results']['posterior_stats']['credible_interval_95']['lower']:.4f}, "
          f"{results['model_results']['posterior_stats']['credible_interval_95']['upper']:.4f}]")
    print(f"  Credible interval width: {results['model_results']['posterior_stats']['credible_interval_width']:.4f}")
    print(f"  Underpowered (width > 0.2): {results['fr14_status']['is_underpowered']}")
    if results['fr14_status']['is_underpowered']:
        print(f"  Reason: {results['fr14_status']['reason']}")
    print(f"\nCorrelation Analysis:")
    print(f"  Correlation (rank vs CESR): {results['correlation_results'].get('correlation', 'N/A')}")
    print(f"  P-value: {results['correlation_results'].get('p_value', 'N/A')}")
    print(f"  Interpretation: {results['correlation_results'].get('interpretation', 'N/A')}")
    print(f"  Direction: {results['correlation_results'].get('direction', 'N/A')}")
    print(f"  Samples: {results['correlation_results'].get('n_samples', 'N/A')}")