import os
import sys
from pathlib import Path

def ensure_directories():
    """
    Create the required data directory structure for the project.
    This includes:
      - data/raw/
      - data/processed/
      - data/results/
      - figures/
    
    Also creates a schema definition file in data/raw/README.md to document
    the expected structure of raw data files.
    """
    # Define the project root relative to this script's location
    # Assuming this script is in code/
    base_dir = Path(__file__).parent.parent
    
    # Define required directories
    directories = [
        base_dir / "data" / "raw",
        base_dir / "data" / "processed",
        base_dir / "data" / "results",
        base_dir / "figures",
        base_dir / "data" / "temp"
    ]
    
    created_count = 0
    for directory in directories:
        if not directory.exists():
            directory.mkdir(parents=True, exist_ok=True)
            print(f"Created directory: {directory}")
            created_count += 1
        else:
            print(f"Directory already exists: {directory}")
    
    # Create schema documentation for raw data
    raw_readme_path = base_dir / "data" / "raw" / "README.md"
    if not raw_readme_path.exists():
        readme_content = """# Raw Data Directory

This directory contains the raw, unprocessed data files downloaded from external sources.

## Schema and Structure

### Data Sources
1. **zhehuderek/textual_decisionmaking_data** (HuggingFace)
   - Contains textual decision-making records
   - Expected columns: `participant_id`, `trial_id`, `options`, `choice`, `response_time`, `deferral_flag`
   
2. **PhillyMac/Decision_Making_Content_1** (HuggingFace)
   - Secondary dataset for robustness checks
   - Expected columns: `subject`, `scenario`, `options`, `decision`, `time_elapsed`

## File Naming Convention
- `{source_name}_{date}_{version}.csv` or `{source_name}_{date}_{version}.parquet`
- Example: `zhehuderek_textual_decisionmaking_2024_01.csv`

## Data Integrity
- All files in this directory are read-only after initial ingestion
- Checksums are stored in `data/raw/checksums.json`
- Do not modify files in this directory directly

## Processing Pipeline
Raw data flows: `data/raw/` → `code/ingest.py` → `data/processed/`
"""
        with open(raw_readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        print(f"Created schema documentation: {raw_readme_path}")
    else:
        print(f"Schema documentation already exists: {raw_readme_path}")
    
    # Create schema documentation for processed data
    processed_readme_path = base_dir / "data" / "processed" / "README.md"
    if not processed_readme_path.exists():
        readme_content = """# Processed Data Directory

This directory contains cleaned, transformed, and feature-engineered datasets ready for analysis.

## Schema and Structure

### Primary Output Files
1. **regret_proxy_v1.csv**
   - Generated by: `code/features.py` (calculate_min_max_regret)
   - Columns: `participant_id`, `trial_id`, `regret_proxy`, `deferral`, `option_count`, `perceived_risk`
   - Description: Main dataset for User Story 1 analysis

2. **excluded_participants.csv**
   - Generated by: `code/modeling.py` (T028)
   - Columns: `participant_id`, `reason`
   - Description: List of participants excluded from random effect estimation

## Data Integrity
- Processed data is derived deterministically from raw data
- Versioning is applied via filename suffixes (e.g., `_v1`, `_v2`)
- Do not manually edit files in this directory

## Processing Pipeline
Raw data flows: `data/raw/` → `code/ingest.py` → `data/processed/` → `code/modeling.py` → `data/results/`
"""
        with open(processed_readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        print(f"Created schema documentation: {processed_readme_path}")
    else:
        print(f"Schema documentation already exists: {processed_readme_path}")
    
    print(f"Setup complete. Created {created_count} new directories.")
    return True

if __name__ == "__main__":
    ensure_directories()