"""
Integration test for end-to-end statistical validation (US3).

This test verifies the full statistical validation pipeline:
1. Loads topological features (data/processed/features.csv)
2. Loads retrieval scores (data/results/retrieval_scores.csv)
3. Computes Spearman correlation between features and Recall@10
4. Performs paired t-test on Graph vs Neural Recall@10
5. Validates metrics are written to data/results/metrics.json
6. Validates correlation data is written to data/results/correlation.csv
"""
import json
import csv
import os
import sys
import pytest
from pathlib import Path

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from code.config import RESULTS_DIR, PROCESSED_DIR
from code.evaluator import calculate_recall_at_k, load_retrieval_scores, load_hotpotqa_ground_truth
from code.t_test_metrics import perform_paired_t_test, calculate_ratio, load_retrieved_features
from code.final_metrics_writer import write_metrics_json, write_correlation_csv, load_spearman_correlation_results, load_latency_metrics, load_recall_metrics, load_correlation_data_for_csv


class TestStatisticalValidationPipeline:
    """Integration tests for the statistical validation pipeline."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Ensure required artifacts exist before running tests."""
        # Check that prerequisite files exist (generated by T016, T022, T024, T028, T029)
        assert (PROCESSED_DIR / "features.csv").exists(), "Prerequisite: data/processed/features.csv missing"
        assert (RESULTS_DIR / "retrieval_scores.csv").exists(), "Prerequisite: data/results/retrieval_scores.csv missing"
        assert (RESULTS_DIR / "retrieved_features.csv").exists(), "Prerequisite: data/results/retrieved_features.csv missing"
        assert (RESULTS_DIR / "metrics.json").exists(), "Prerequisite: data/results/metrics.json missing (T031)"
        assert (RESULTS_DIR / "correlation.csv").exists(), "Prerequisite: data/results/correlation.csv missing (T031)"

    def test_01_spearman_correlation_computation(self):
        """Test that Spearman correlation is correctly computed and stored."""
        # Load the correlation results (expected to be generated by T028/evaluator)
        # We verify the file exists and contains valid numeric data
        corr_csv_path = RESULTS_DIR / "correlation.csv"
        
        with open(corr_csv_path, 'r') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        
        assert len(rows) > 0, "Correlation CSV is empty"
        
        # Verify required columns exist
        required_cols = {'feature_name', 'spearman_r', 'p_value', 'n_samples'}
        assert required_cols.issubset(set(rows[0].keys())), f"Missing required columns in correlation.csv. Found: {rows[0].keys()}"
        
        # Verify numeric values are parseable and within expected ranges
        for row in rows:
            r_val = float(row['spearman_r'])
            p_val = float(row['p_value'])
            n_val = int(row['n_samples'])
            
            assert -1.0 <= r_val <= 1.0, f"Spearman r out of range: {r_val}"
            assert 0.0 <= p_val <= 1.0, f"P-value out of range: {p_val}"
            assert n_val > 0, f"Sample size must be positive: {n_val}"

    def test_02_paired_ttest_execution(self):
        """Test that paired t-test is correctly executed and results are valid."""
        # Load retrieval scores to verify t-test inputs exist
        retrieval_scores = load_retrieval_scores()
        assert len(retrieval_scores) > 0, "No retrieval scores found for t-test"
        
        # Verify that t-test metrics are present in metrics.json
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        # Check for t-test related fields
        assert 't_statistic' in metrics, "t-statistic missing from metrics.json"
        assert 'p_value_ttest' in metrics, "p-value for t-test missing from metrics.json"
        assert 'ratio_graph_neural' in metrics, "Ratio of Graph/Neural recall missing from metrics.json"
        
        # Validate numeric constraints
        t_stat = float(metrics['t_statistic'])
        p_ttest = float(metrics['p_value_ttest'])
        ratio = float(metrics['ratio_graph_neural'])
        
        assert isinstance(t_stat, float), "t-statistic must be float"
        assert 0.0 <= p_ttest <= 1.0, f"P-value for t-test out of range: {p_ttest}"
        assert ratio >= 0.0, f"Ratio must be non-negative: {ratio}"

    def test_03_metrics_json_structure(self):
        """Test that metrics.json contains all required fields for US3."""
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        required_fields = [
            'task_id', 'correlation_r', 'correlation_p_value', 
            'recall_graph_at_10', 'recall_neural_at_10',
            't_statistic', 'p_value_ttest', 'ratio_graph_neural',
            'latency_reduction_pct', 'hypothesis_supported'
        ]
        
        missing = [f for f in required_fields if f not in metrics]
        assert len(missing) == 0, f"Missing required fields in metrics.json: {missing}"

    def test_04_hypothesis_validation_logic(self):
        """Test that hypothesis validation logic is correctly applied."""
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        r = float(metrics['correlation_r'])
        hypothesis_supported = metrics['hypothesis_supported']
        
        # Verify the logic: hypothesis_supported should be True iff r > 0.6
        expected_status = r > 0.6
        assert hypothesis_supported == expected_status, (
            f"Hypothesis status mismatch: r={r}, expected {expected_status}, got {hypothesis_supported}"
        )

    def test_05_ratio_threshold_check(self):
        """Test that the ratio threshold (>= 0.70) is correctly evaluated."""
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        ratio = float(metrics['ratio_graph_neural'])
        # The task requires logging whether the ratio meets the threshold
        # We verify the ratio is present and valid
        assert ratio >= 0.0, "Ratio must be non-negative"
        # We do not assert the threshold is met, only that the value is computed correctly

    def test_06_end_to_end_data_flow(self):
        """Test that the entire statistical validation flow produces consistent results."""
        # 1. Load raw data
        retrieval_scores = load_retrieval_scores()
        retrieved_features = load_retrieved_features()
        
        # 2. Verify data counts match
        score_queries = set(s['query_id'] for s in retrieval_scores)
        feature_queries = set(f['query_id'] for f in retrieved_features)
        
        # Queries should align (or be a subset if some were dropped)
        assert score_queries.issubset(feature_queries) or feature_queries.issubset(score_queries), \
            "Query sets between scores and features are disjoint"
        
        # 3. Load computed metrics
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        # 4. Verify Recall@10 values are present and non-trivial
        recall_graph = float(metrics['recall_graph_at_10'])
        recall_neural = float(metrics['recall_neural_at_10'])
        
        assert 0.0 <= recall_graph <= 1.0, f"Graph Recall@10 out of range: {recall_graph}"
        assert 0.0 <= recall_neural <= 1.0, f"Neural Recall@10 out of range: {recall_neural}"
        
        # 5. Verify ratio matches the individual recalls
        computed_ratio = recall_graph / recall_neural if recall_neural > 0 else 0.0
        stored_ratio = float(metrics['ratio_graph_neural'])
        
        # Allow small floating point tolerance
        assert abs(computed_ratio - stored_ratio) < 1e-5, \
            f"Ratio mismatch: computed {computed_ratio}, stored {stored_ratio}"

    def test_07_latency_metrics_integration(self):
        """Test that latency metrics are correctly integrated into the final report."""
        metrics_path = RESULTS_DIR / "metrics.json"
        with open(metrics_path, 'r') as f:
            metrics = json.load(f)
        
        assert 'latency_reduction_pct' in metrics, "Latency reduction missing"
        reduction = float(metrics['latency_reduction_pct'])
        assert -100.0 <= reduction <= 1000.0, f"Latency reduction out of plausible range: {reduction}"

    def test_08_correlation_csv_integrity(self):
        """Test that correlation.csv is properly formatted and complete."""
        corr_path = RESULTS_DIR / "correlation.csv"
        with open(corr_path, 'r') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        
        assert len(rows) > 0, "Correlation CSV is empty"
        
        # Check for expected feature names (from topology_extractor)
        expected_features = {'modularity', 'avg_path_length', 'degree_centrality', 'betweenness_centrality'}
        found_features = set(row['feature_name'] for row in rows)
        
        # At least some of the expected features should be present
        assert len(expected_features.intersection(found_features)) > 0, \
            f"No expected topological features found in correlation.csv. Found: {found_features}"