"""
Descriptor calculation and Normal Mode Analysis (NMA) for molecular flexibility.

This module implements the calculation of internal coordinate variances (bond, angle, dihedral)
using Normal Mode Analysis via the pyvib library. It processes conformer ensembles generated
in T013 to produce the primary flexibility metric (dihedral_variance) and diagnostic metrics.

Traceability:
- FR-004: Compute torsional variance (dihedral) as the primary metric for flexibility.
- Plan Constitution Check VI: Ensure all computational steps are documented and reproducible.
"""

import logging
import sys
import pickle
import tempfile
import os
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

import numpy as np
import pandas as pd

# Import logging utilities from the project
from utils.logging import get_logger, configure_root_logger
from utils.config import get_project_root

# Configure logging
configure_root_logger()
logger = get_logger(__name__)

# Constants
MIN_VALID_DESCRIPTORS = 450
CONFORMERS_PATH = "data/processed/conformers.pkl"
PROCESSED_DATA_PATH = "data/processed/filtered_data.csv"
OUTPUT_PATH = "data/processed/descriptors_raw.csv"


def load_processed_data() -> pd.DataFrame:
    """
    Load the filtered dataset containing SMILES strings.

    Returns:
        pd.DataFrame: The filtered dataset with SMILES and logPapp columns.
    """
    project_root = get_project_root()
    file_path = project_root / PROCESSED_DATA_PATH

    if not file_path.exists():
        raise FileNotFoundError(f"Required input file not found: {file_path}")

    logger.info(f"Loading processed data from {file_path}")
    df = pd.read_csv(file_path)
    
    if 'smiles' not in df.columns:
        raise ValueError("Input data must contain a 'smiles' column.")
    
    return df


def load_conformers() -> Dict[str, Any]:
    """
    Load the conformer ensembles generated by T013.

    Returns:
        Dict[str, Any]: Dictionary mapping SMILES to conformer data (energies, coordinates).
    """
    project_root = get_project_root()
    file_path = project_root / CONFORMERS_PATH

    if not file_path.exists():
        raise FileNotFoundError(f"Required input file not found: {file_path}")

    logger.info(f"Loading conformers from {file_path}")
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    
    return data


def get_conformer_count(smiles: str, conformers_data: Dict[str, Any]) -> int:
    """
    Get the number of conformers for a specific molecule.

    Args:
        smiles: The SMILES string of the molecule.
        conformers_data: The dictionary of conformer data.

    Returns:
        int: Number of conformers.
    """
    if smiles not in conformers_data:
        return 0
    # Assuming structure is {'energies': [...], 'coords': [...]} or similar
    # We check for the 'energies' key as a proxy for count
    if 'energies' in conformers_data[smiles]:
        return len(conformers_data[smiles]['energies'])
    return 0


def calculate_internal_coordinate_variance(
    xyz_content: str,
    pyvib_module: Any
) -> Tuple[Optional[float], Optional[float], Optional[float]]:
    """
    Analyze a single molecule's XYZ content using pyvib to extract variance metrics.

    This function writes the XYZ content to a temporary file, calls pyvib.analyze_molecule,
    and extracts the eigenvalues to compute bond, angle, and dihedral variances.

    Args:
        xyz_content: String content of the XYZ file.
        pyvib_module: The imported pyvib module.

    Returns:
        Tuple[Optional[float], Optional[float], Optional[float]]:
            (bond_variance, angle_variance, dihedral_variance) in rad^2.
            Returns (None, None, None) if analysis fails.
    """
    # Create a temporary file for the XYZ content
    with tempfile.NamedTemporaryFile(mode='w', suffix='.xyz', delete=False) as tmp_file:
        tmp_file.write(xyz_content)
        tmp_path = tmp_file.name

    try:
        # Call pyvib analysis
        # Note: We assume pyvib.analyze_molecule returns a result object or dict
        # containing eigenvalues/frequencies.
        result = pyvib_module.analyze_molecule(tmp_path)
        
        # Extract eigenvalues (frequencies)
        # The structure of 'result' depends on pyvib's output.
        # We assume it has a 'frequencies' or 'eigenvalues' attribute.
        if hasattr(result, 'frequencies'):
            frequencies = result.frequencies
        elif hasattr(result, 'eigenvalues'):
            frequencies = result.eigenvalues
        else:
            logger.warning(f"Could not extract frequencies from pyvib result: {type(result)}")
            return None, None, None

        # Convert frequencies to rad/s if necessary (assuming input is cm-1 or similar)
        # For variance calculation, we typically look at the distribution of low-frequency modes.
        # A simplified approach for "torsional variance" often involves the variance of the
        # lowest 3-6 non-translational/rotational modes.
        
        # Filter out zero/near-zero frequencies (translational/rotational)
        valid_freqs = [f for f in frequencies if abs(f) > 10.0] # Threshold in cm-1 or similar
        
        if len(valid_freqs) < 3:
            logger.warning("Not enough valid low-frequency modes to calculate variance.")
            return None, None, None

        # Convert to angular frequency (rad/s) if needed, but for variance in 'rad^2'
        # we often work with the variance of the mode amplitudes or the inverse of force constants.
        # Given the task description "Compute torsional variance (dihedral) in rad^2",
        # and standard NMA outputs, we assume the library or the logic maps frequencies to variance.
        # A common proxy: Variance ~ kT / (frequency^2) or simply the variance of the mode coordinates.
        # Here, we will assume the 'frequencies' provided are sufficient to compute a proxy variance.
        # If pyvib returns a specific 'variance' metric, we would use that.
        # For this implementation, we compute the variance of the low-frequency modes as a proxy.
        
        # Note: The exact physical interpretation depends on the specific pyvib implementation.
        # We assume the user wants the statistical variance of the low-frequency modes.
        freq_array = np.array(valid_freqs)
        
        # Calculate variances based on mode types (simplified heuristic)
        # In a full implementation, we would map modes to bond/angle/dihedral types.
        # Since pyvib might not do this automatically, we assume the task implies
        # extracting these specific variances from the NMA result.
        # If pyvib returns a dictionary with 'bond_variance', etc., we use that.
        
        if isinstance(result, dict):
            bond_var = result.get('bond_variance')
            angle_var = result.get('angle_variance')
            dihedral_var = result.get('dihedral_variance')
            
            if dihedral_var is None:
                # Fallback: compute from frequencies if not provided
                # This is a placeholder for the actual physics-based calculation
                # which requires mapping modes to internal coordinates.
                # For now, we assume the library provides these or we calculate a proxy.
                # If the library doesn't provide them, we might need to compute them manually.
                # Given the constraint "Call pyvib.analyze_molecule", we assume it returns these.
                # If not, we return None.
                logger.warning("pyvib result does not contain explicit variance metrics.")
                return None, None, None
            else:
                return float(bond_var), float(angle_var), float(dihedral_var)
        else:
            # If result is an object, try to access attributes
            bond_var = getattr(result, 'bond_variance', None)
            angle_var = getattr(result, 'angle_variance', None)
            dihedral_var = getattr(result, 'dihedral_variance', None)
            
            if dihedral_var is None:
                logger.warning("pyvib result object does not contain explicit variance metrics.")
                return None, None, None
            else:
                return float(bond_var), float(angle_var), float(dihedral_var)

    except Exception as e:
        logger.error(f"Error analyzing molecule with pyvib: {e}")
        return None, None, None
    finally:
        # Clean up temporary file
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def calculate_variance_metrics(
    smiles: str,
    conformers_data: Dict[str, Any]
) -> Optional[Dict[str, Any]]:
    """
    Calculate variance metrics for a single molecule.

    1. Load the lowest energy conformer.
    2. Convert to XYZ format.
    3. Call pyvib.analyze_molecule.
    4. Extract eigenvalues and compute variances.

    Args:
        smiles: SMILES string.
        conformers_data: Dictionary of conformer data.

    Returns:
        Optional[Dict[str, Any]]: Dictionary with metrics if successful, None otherwise.
    """
    if smiles not in conformers_data:
        logger.warning(f"No conformer data for {smiles}")
        return None

    data = conformers_data[smiles]
    
    # 1. Load the lowest energy conformer
    # Assuming 'energies' is a list and 'coords' is a list of coordinate arrays
    if 'energies' not in data or 'coords' not in data:
        logger.warning(f"Invalid conformer data structure for {smiles}")
        return None

    energies = data['energies']
    coords = data['coords']
    
    if len(energies) == 0:
        return None

    min_idx = int(np.argmin(energies))
    lowest_energy_coords = coords[min_idx]

    # 2. Convert to XYZ format
    # We need atom symbols. Assuming the original data has 'atoms' or we infer from SMILES.
    # Since we don't have the atoms list here, we assume the coords include symbols or
    # we need to reconstruct them from the SMILES.
    # For RDKit conformers, we usually have the molecule object.
    # If 'coords' is just a numpy array of shape (N, 3), we need symbols.
    # Let's assume the data structure includes 'atoms' or we can derive it.
    # If not, we might need to pass the SMILES to a function that generates the XYZ with symbols.
    
    # Alternative: If the conformer data was generated with RDKit, we might have the Mol object.
    # But here we have 'coords' and 'energies'.
    # We will assume 'data' also contains 'atoms' (list of symbols).
    if 'atoms' not in data:
        # Try to infer from SMILES? This is complex without RDKit in this specific function context
        # or if we don't want to re-parse SMILES.
        # Let's assume the data structure is complete.
        logger.error(f"Missing 'atoms' in conformer data for {smiles}")
        return None

    atoms = data['atoms']
    n_atoms = len(atoms)
    
    xyz_lines = [f"{n_atoms}", f"Lowest energy conformer of {smiles}"]
    for i, atom in enumerate(atoms):
        x, y, z = lowest_energy_coords[i]
        xyz_lines.append(f"{atom:2s} {x:15.6f} {y:15.6f} {z:15.6f}")
    
    xyz_content = "\n".join(xyz_lines) + "\n"

    # 3. Call pyvib
    try:
        import pyvib
    except ImportError:
        logger.error("pyvib is not installed. Please install it via requirements.txt.")
        return None

    bond_var, angle_var, dihedral_var = calculate_internal_coordinate_variance(
        xyz_content, pyvib
    )

    # 4. Check constraint: If dihedral_variance fails, skip entirely.
    if dihedral_var is None:
        logger.warning(f"Failed to calculate dihedral variance for {smiles}. Skipping.")
        return None

    return {
        'smiles': smiles,
        'bond_variance': bond_var,
        'angle_variance': angle_var,
        'dihedral_variance': dihedral_var
    }


def flag_outliers(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Flag outliers in the calculated variances (optional, for diagnostics).
    
    Args:
        results: List of result dictionaries.
        
    Returns:
        List[Dict[str, Any]]: Results with an 'outlier' flag.
    """
    if not results:
        return results
    
    df = pd.DataFrame(results)
    
    # Simple IQR method for flagging outliers
    for col in ['bond_variance', 'angle_variance', 'dihedral_variance']:
        if col in df.columns:
            Q1 = df[col].quantile(0.25)
            Q3 = df[col].quantile(0.75)
            IQR = Q3 - Q1
            df[f'{col}_outlier'] = (df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))
    
    return df.to_dict('records')


def process_molecules(
    smiles_list: List[str],
    conformers_data: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Process a list of molecules to calculate descriptors.

    Args:
        smiles_list: List of SMILES strings.
        conformers_data: Dictionary of conformer data.

    Returns:
        List[Dict[str, Any]]: List of dictionaries with calculated metrics.
    """
    results = []
    for smiles in smiles_list:
        result = calculate_variance_metrics(smiles, conformers_data)
        if result is not None:
            results.append(result)
        # If None, it is skipped as per constraint
    return results


def calculate_success_rate(total: int, successful: int) -> float:
    """Calculate the success rate of descriptor calculation."""
    if total == 0:
        return 0.0
    return successful / total


def validate_success_rate(success_rate: float) -> bool:
    """
    Validate that the success rate meets the threshold.
    
    Args:
        success_rate: The calculated success rate.
        
    Returns:
        bool: True if success rate is sufficient, False otherwise.
    """
    # We need at least MIN_VALID_DESCRIPTORS valid records.
    # This function is called after processing, so we check the count.
    # The actual check is done in main() based on the count.
    return True # Placeholder, actual check is in main


def write_descriptors(results: List[Dict[str, Any]]) -> Path:
    """
    Write the calculated descriptors to a CSV file.

    Args:
        results: List of result dictionaries.

    Returns:
        Path: Path to the output file.
    """
    project_root = get_project_root()
    output_file = project_root / OUTPUT_PATH
    
    if not results:
        logger.error("No results to write.")
        raise ValueError("No valid descriptors calculated.")

    df = pd.DataFrame(results)
    
    # Ensure columns are in the correct order
    columns = ['smiles', 'bond_variance', 'angle_variance', 'dihedral_variance']
    # Filter to only existing columns to avoid errors
    existing_cols = [c for c in columns if c in df.columns]
    df = df[existing_cols]
    
    df.to_csv(output_file, index=False)
    logger.info(f"Wrote {len(df)} descriptors to {output_file}")
    
    return output_file


def main():
    """
    Main entry point for the descriptor calculation pipeline.
    """
    logger.info("Starting descriptor calculation (T014)...")
    
    # 1. Load data
    try:
        df_processed = load_processed_data()
        conformers_data = load_conformers()
    except Exception as e:
        logger.error(f"Failed to load data: {e}")
        sys.exit(1)

    smiles_list = df_processed['smiles'].tolist()
    total_molecules = len(smiles_list)
    logger.info(f"Processing {total_molecules} molecules.")

    # 2. Process molecules
    results = process_molecules(smiles_list, conformers_data)
    valid_count = len(results)
    
    logger.info(f"Successfully calculated descriptors for {valid_count} molecules.")

    # 3. Threshold Check
    if valid_count < MIN_VALID_DESCRIPTORS:
        error_msg = f"ERROR: Only {valid_count} valid descriptors generated. Threshold is {MIN_VALID_DESCRIPTORS}. Halting pipeline."
        logger.error(error_msg)
        sys.exit(1)

    # 4. Write output
    try:
        output_path = write_descriptors(results)
    except Exception as e:
        logger.error(f"Failed to write descriptors: {e}")
        sys.exit(1)

    # 5. Invoke checksum utility
    try:
        from utils.checksum import scan_and_register_data_files
        # Scan the specific output file
        scan_and_register_data_files([output_path])
        logger.info("Checksum utility invoked successfully.")
    except Exception as e:
        logger.warning(f"Checksum utility failed: {e}")
        # Do not halt for checksum failure, but log it.

    logger.info("Descriptor calculation completed successfully.")


if __name__ == "__main__":
    main()