"""
generate_processed_checksums.py

This script computes SHA256 checksums for all files produced after the
feature‑engineering step (i.e. everything under ``data/processed``) and
records them in ``data/checksums.txt``.  It appends to the existing
checksums file so that raw‑data entries generated by T008a remain intact.

The implementation re‑uses the helper functions defined in
``code/utils/checksum.py``:
  * ``compute_sha256`` – returns the hex digest of a single file.
The script is deliberately lightweight and has no external dependencies
beyond the project's own utilities and the Python standard library.

Usage
-----
Run the module directly:

    python code/data/generate_processed_checksums.py

The script will exit with status 0 on success or raise any exception
encountered (e.g. missing files, permission errors).  This behaviour
satisfies the project's requirement that data‑loader scripts must fail
loudly rather than silently falling back to synthetic data.
"""

import logging
from pathlib import Path

# Import the project's checksum utility.
from utils.checksum import compute_sha256

# Configure a module‑level logger using the project's logger utility.
# If the central logger is not yet configured, fall back to a basic config.
try:
    from utils.logger import get_pipeline_logger
    logger = get_pipeline_logger(__name__)
except Exception:  # pragma: no cover
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

def _iter_processed_files(base_dir: Path):
    """
    Yield all regular files under ``base_dir`` (recursively).

    Parameters
    ----------
    base_dir: Path
        The directory that contains the processed artefacts (e.g. ``data/processed``).

    Yields
    ------
    Path
        Path objects for each file found.
    """
    if not base_dir.is_dir():
        raise FileNotFoundError(f"Processed data directory not found: {base_dir}")

    for path in base_dir.rglob("*"):
        if path.is_file():
            yield path

def generate_processed_checksums(
    processed_dir: Path = Path("data/processed"),
    checksums_file: Path = Path("data/checksums.txt"),
) -> None:
    """
    Compute SHA256 checksums for every file in ``processed_dir`` and
    append them to ``checksums_file``.

    The output format mirrors the classic ``sha256sum`` utility:
    ``<checksum><two spaces><relative_path>``.

    Parameters
    ----------
    processed_dir: Path, optional
        Directory containing processed data files. Defaults to ``data/processed``.
    checksums_file: Path, optional
        Destination file for checksum entries. Defaults to ``data/checksums.txt``.
    """
    logger.info("Starting checksum generation for processed data.")
    logger.debug(f"Processed directory: {processed_dir}")
    logger.debug(f"Checksums output file: {checksums_file}")

    # Ensure the output directory exists.
    checksums_file.parent.mkdir(parents=True, exist_ok=True)

    # Open the checksums file in append mode so raw‑data entries are preserved.
    with checksums_file.open("a", encoding="utf-8") as out_f:
        for file_path in _iter_processed_files(processed_dir):
            # Compute checksum.
            checksum = compute_sha256(file_path)
            # Store paths relative to the project root for reproducibility.
            relative_path = file_path.relative_to(Path.cwd())
            line = f"{checksum}  {relative_path}\n"
            out_f.write(line)
            logger.debug(f"Wrote checksum for {relative_path}")

    logger.info(
        f"Checksum generation complete. Entries appended to {checksums_file}"
    )

def main() -> None:
    """
    Entry‑point for ``python -m code.data.generate_processed_checksums``.

    It simply forwards to :func:`generate_processed_checksums` with the
    default locations.
    """
    generate_processed_checksums()

if __name__ == "__main__":
    # When executed as a script, run the main routine.
    main()