"""
Aggregate spatial metrics from autocorrelation and Fourier analysis into a unified DataFrame.

This module implements Task T024: Aggregate all spatial metrics into a structured DataFrame
in `data/processed/spatial_metrics.csv`. It loads results from autocorrelation analysis
(T019-T021) and Fourier analysis (T022), merges them by sample_id, and writes the final
aggregated dataset.
"""

import os
import logging
import pandas as pd
from pathlib import Path
from typing import List, Optional

# Import from sibling modules as per API surface
from analysis.spatial_metrics import process_dataset_and_write_metrics
from analysis.fourier_metrics import compute_spatial_frequency_metrics

logger = logging.getLogger(__name__)

def load_autocorrelation_metrics(filepath: str) -> pd.DataFrame:
    """
    Load autocorrelation metrics from the spatial_metrics.csv generated by T019-T021.
    
    Args:
        filepath: Path to the autocorrelation metrics CSV file.
        
    Returns:
        DataFrame with columns: sample_id, element, correlation_length, model_type, AIC
    """
    path = Path(filepath)
    if not path.exists():
        logger.warning(f"Autocorrelation metrics file not found: {filepath}")
        return pd.DataFrame()
    
    try:
        df = pd.read_csv(filepath)
        logger.info(f"Loaded {len(df)} rows from autocorrelation metrics: {filepath}")
        return df
    except Exception as e:
        logger.error(f"Failed to load autocorrelation metrics from {filepath}: {e}")
        return pd.DataFrame()

def load_fourier_metrics(filepath: str) -> pd.DataFrame:
    """
    Load Fourier metrics from the spatial_metrics_fourier.csv generated by T022.
    
    Args:
        filepath: Path to the Fourier metrics CSV file.
        
    Returns:
        DataFrame with columns: sample_id, element, low_freq_power, total_power, 
                               dominant_frequency_x, dominant_frequency_y
    """
    path = Path(filepath)
    if not path.exists():
        logger.warning(f"Fourier metrics file not found: {filepath}")
        return pd.DataFrame()
    
    try:
        df = pd.read_csv(filepath)
        logger.info(f"Loaded {len(df)} rows from Fourier metrics: {filepath}")
        return df
    except Exception as e:
        logger.error(f"Failed to load Fourier metrics from {filepath}: {e}")
        return pd.DataFrame()

def aggregate_spatial_metrics(
    autocorr_path: str,
    fourier_path: str,
    output_path: str
) -> pd.DataFrame:
    """
    Aggregate autocorrelation and Fourier metrics into a single DataFrame.
    
    This function implements the core logic for T024:
    1. Loads autocorrelation metrics (correlation lengths, model fits)
    2. Loads Fourier metrics (spectral power, frequency components)
    3. Merges on sample_id and element
    4. Writes the unified DataFrame to the output path
    
    Args:
        autocorr_path: Path to autocorrelation metrics CSV
        fourier_path: Path to Fourier metrics CSV
        output_path: Path where the aggregated DataFrame will be written
        
    Returns:
        Aggregated DataFrame containing all spatial metrics
    """
    logger.info(f"Aggregating spatial metrics from {autocorr_path} and {fourier_path}")
    
    # Load source data
    autocorr_df = load_autocorrelation_metrics(autocorr_path)
    fourier_df = load_fourier_metrics(fourier_path)
    
    if autocorr_df.empty and fourier_df.empty:
        logger.error("Both input files are empty or missing. Cannot aggregate.")
        # Create empty output with expected schema
        output_df = pd.DataFrame(columns=[
            'sample_id', 'element', 'correlation_length', 'model_type', 'AIC',
            'low_freq_power', 'total_power', 'dominant_frequency_x', 'dominant_frequency_y'
        ])
        output_df.to_csv(output_path, index=False)
        logger.info(f"Created empty aggregated file: {output_path}")
        return output_df
    
    # Determine merge keys
    merge_keys = ['sample_id', 'element']
    
    # Ensure merge keys exist in both DataFrames
    autocorr_available = all(col in autocorr_df.columns for col in merge_keys)
    fourier_available = all(col in fourier_df.columns for col in merge_keys)
    
    if not autocorr_available:
        logger.warning("Autocorrelation DataFrame missing required merge keys")
        autocorr_df = pd.DataFrame()
    
    if not fourier_available:
        logger.warning("Fourier DataFrame missing required merge keys")
        fourier_df = pd.DataFrame()
    
    # Perform outer join to preserve all samples
    if not autocorr_df.empty and not fourier_df.empty:
        agg_df = pd.merge(
            autocorr_df, 
            fourier_df, 
            on=merge_keys, 
            how='outer'
        )
    elif not autocorr_df.empty:
        agg_df = autocorr_df.copy()
    elif not fourier_df.empty:
        agg_df = fourier_df.copy()
    else:
        agg_df = pd.DataFrame()
    
    # Reorder columns for consistency
    expected_columns = [
        'sample_id', 'element', 'correlation_length', 'model_type', 'AIC',
        'low_freq_power', 'total_power', 'dominant_frequency_x', 'dominant_frequency_y'
    ]
    
    # Filter to only columns that exist in agg_df
    available_columns = [col for col in expected_columns if col in agg_df.columns]
    agg_df = agg_df[available_columns]
    
    # Sort by sample_id and element
    if not agg_df.empty:
        sort_cols = [col for col in ['sample_id', 'element'] if col in agg_df.columns]
        if sort_cols:
            agg_df = agg_df.sort_values(by=sort_cols).reset_index(drop=True)
    
    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Write aggregated results
    agg_df.to_csv(output_path, index=False)
    logger.info(f"Aggregated {len(agg_df)} rows to {output_path}")
    
    return agg_df

def main():
    """
    Main entry point for T024: Aggregate all spatial metrics.
    
    Reads autocorrelation and Fourier metrics from their respective output files
    and writes a unified DataFrame to data/processed/spatial_metrics.csv.
    """
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Define paths relative to project root
    project_root = Path(__file__).resolve().parents[2]
    data_processed_dir = project_root / "data" / "processed"
    
    # Ensure directories exist
    data_processed_dir.mkdir(parents=True, exist_ok=True)
    
    # Input paths (generated by previous tasks)
    autocorr_input = str(data_processed_dir / "spatial_metrics_autocorr.csv")
    fourier_input = str(data_processed_dir / "spatial_metrics_fourier.csv")
    
    # Output path (T024 requirement)
    output_path = str(data_processed_dir / "spatial_metrics.csv")
    
    logger.info(f"Starting spatial metrics aggregation...")
    logger.info(f"  Autocorrelation input: {autocorr_input}")
    logger.info(f"  Fourier input: {fourier_input}")
    logger.info(f"  Output: {output_path}")
    
    # Perform aggregation
    result_df = aggregate_spatial_metrics(
        autocorr_path=autocorr_input,
        fourier_path=fourier_input,
        output_path=output_path
    )
    
    if result_df.empty:
        logger.warning("Aggregation completed but resulted in empty DataFrame")
    else:
        logger.info(f"Successfully aggregated {len(result_df)} samples")
        logger.info(f"Columns: {list(result_df.columns)}")
    
    return result_df

if __name__ == "__main__":
    main()