import os
import sys
import logging
import json
from pathlib import Path
from typing import List, Dict, Any

# Ensure project root is in path for imports
project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(project_root))

from utils.config import get_processed_dir, get_data_dir

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_species_profiles() -> pd.DataFrame:
    """
    Load the species profiles CSV generated by aggregate.py.
    
    Returns:
        pd.DataFrame: The species profiles dataframe.
    
    Raises:
        FileNotFoundError: If the input file does not exist.
        ValueError: If the file is empty or missing required columns.
    """
    import pandas as pd
    
    input_path = get_processed_dir() / "species_profiles.csv"
    
    if not input_path.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_path}. "
            "Ensure T016 (aggregate.py) has been run successfully."
        )
    
    df = pd.read_csv(input_path)
    
    if df.empty:
        raise ValueError("Input file is empty. No species profiles to process.")
    
    required_cols = ['species_id', 'observation_count']
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(
            f"Input file is missing required columns: {missing_cols}. "
            f"Found columns: {list(df.columns)}"
        )
    
    logger.info(f"Loaded {len(df)} species profiles from {input_path}")
    return df

def extract_top_species(df: pd.DataFrame, n: int = 25) -> List[Dict[str, Any]]:
    """
    Extract the top N species by observation count.
    
    Handles ties at the cutoff rank by including all species with the 
    same count as the Nth species.
    
    Args:
        df: The species profiles dataframe.
        n: The target number of top species (default 25).
    
    Returns:
        List of dictionaries containing species_id and observation_count 
        for the top species.
    """
    if df.empty:
        return []
    
    # Sort by observation_count descending, then by species_id for stability
    sorted_df = df.sort_values(
        by=['observation_count', 'species_id'], 
        ascending=[False, True]
    ).reset_index(drop=True)
    
    if len(sorted_df) <= n:
        # If fewer than n species, return all
        logger.warning(f"Only {len(sorted_df)} species available, returning all.")
        return sorted_df[['species_id', 'observation_count']].to_dict(orient='records')
    
    # Determine the cutoff value at rank n (0-indexed n-1)
    cutoff_count = sorted_df.iloc[n - 1]['observation_count']
    
    # Filter to include all species with count >= cutoff_count
    # This handles ties at the cutoff
    top_species_df = sorted_df[sorted_df['observation_count'] >= cutoff_count]
    
    # Log if we included more than n due to ties
    if len(top_species_df) > n:
        logger.warning(
            f"Tie detected at rank {n} with count {cutoff_count}. "
            f"Including {len(top_species_df)} species instead of {n}."
        )
    
    result = top_species_df[['species_id', 'observation_count']].to_dict(orient='records')
    logger.info(f"Extracted top {len(result)} species (target: {n}).")
    
    return result

def save_top_species(top_species: List[Dict[str, Any]], output_path: Path) -> None:
    """
    Save the list of top species to a JSON file.
    
    Args:
        top_species: List of species dictionaries.
        output_path: Path to save the JSON file.
    """
    # Ensure directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        json.dump(top_species, f, indent=2)
    
    logger.info(f"Saved {len(top_species)} top species to {output_path}")

def main():
    """
    Main entry point for the extract_top_species script.
    """
    logger.info("Starting extract_top_species.py")
    
    try:
        # Load data
        df = load_species_profiles()
        
        # Extract top species
        top_species = extract_top_species(df)
        
        # Define output path
        output_dir = get_processed_dir()
        output_path = output_dir / "top_species.json"
        
        # Save results
        save_top_species(top_species, output_path)
        
        logger.info("extract_top_species.py completed successfully.")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"File not found: {e}")
        return 1
    except ValueError as e:
        logger.error(f"Value error: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())
