import os
import sys
import json
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from pathlib import Path
import logging
from typing import Tuple, List, Dict, Any

# Import shared utilities from sibling modules
try:
    from models.baseline_nn import HeteroscedasticNN, load_config, load_processed_data
except ImportError:
    # Fallback for execution context where relative imports might differ
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
    from models.baseline_nn import HeteroscedasticNN, load_config, load_processed_data

# Setup logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
if not logger.handlers:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(handler)

class MCDropoutModel(HeteroscedasticNN):
    """
    A wrapper around HeteroscedasticNN that enables dropout during inference
    for Monte Carlo Dropout uncertainty estimation.
    """
    def __init__(self, input_dim: int, hidden_dims: List[int], dropout_rate: float = 0.2):
        super().__init__(input_dim, hidden_dims)
        self.dropout_rate = dropout_rate
        # Apply dropout to all linear layers (except the output head which is handled differently)
        self._apply_dropout()

    def _apply_dropout(self):
        """Apply dropout layers to existing linear layers in the network."""
        # We need to reconstruct the network with dropout layers
        # Since HeteroscedasticNN defines specific layers, we recreate them here with dropout
        layers = []
        in_dim = self.input_dim
        
        for hidden_dim in self.hidden_dims:
            layers.append(nn.Linear(in_dim, hidden_dim))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(p=self.dropout_rate))
            in_dim = hidden_dim
        
        # Replace the existing layers
        self.feature_extractor = nn.Sequential(*layers)
        
        # Output head (mean and log_var) - typically no dropout on output
        self.mean_head = nn.Linear(in_dim, 1)
        self.log_var_head = nn.Linear(in_dim, 1)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Forward pass. Returns mean and log_variance.
        Note: Dropout is active during inference if model is in train() mode.
        """
        features = self.feature_extractor(x)
        mean = self.mean_head(features)
        log_var = self.log_var_head(features)
        return mean, log_var

def load_data(config: Dict[str, Any]) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Load processed data from CSV files.
    Returns: X_train, y_train, X_test, y_test as torch tensors
    """
    # Load from processed files generated by T006b1
    train_path = Path(config['data']['processed_dir']) / 'features_train_20pca.csv'
    test_path = Path(config['data']['processed_dir']) / 'features_test_20pca.csv'
    
    if not train_path.exists() or not test_path.exists():
        raise FileNotFoundError(
            f"Processed data files not found. Expected:\n"
            f"  Train: {train_path}\n"
            f"  Test: {test_path}"
        )
    
    df_train = pd.read_csv(train_path)
    df_test = pd.read_csv(test_path)
    
    # Assume 'target' column exists after preprocessing
    feature_cols = [col for col in df_train.columns if col != 'target']
    
    X_train = torch.tensor(df_train[feature_cols].values, dtype=torch.float32)
    y_train = torch.tensor(df_train['target'].values, dtype=torch.float32).unsqueeze(1)
    X_test = torch.tensor(df_test[feature_cols].values, dtype=torch.float32)
    y_test = torch.tensor(df_test['target'].values, dtype=torch.float32).unsqueeze(1)
    
    return X_train, y_train, X_test, y_test

def train_mc_dropout(model: MCDropoutModel, X_train: torch.Tensor, y_train: torch.Tensor, 
                    config: Dict[str, Any], device: torch.device) -> MCDropoutModel:
    """
    Train the MC Dropout model.
    Note: We train the model first, then enable dropout only at inference time.
    """
    criterion = nn.MSELoss()  # We use MSE for training, heteroscedastic loss can be used but MSE is standard for initial training
    optimizer = optim.Adam(model.parameters(), lr=config['training']['lr'])
    
    epochs = config['training']['epochs']
    batch_size = config['training']['batch_size']
    
    model.train()
    dataset = torch.utils.data.TensorDataset(X_train, y_train)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    logger.info(f"Training MC Dropout model for {epochs} epochs...")
    
    for epoch in range(epochs):
        total_loss = 0.0
        for batch_X, batch_y in dataloader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            
            optimizer.zero_grad()
            mean, log_var = model(batch_X)
            
            # Heteroscedastic loss: 0.5 * (exp(-log_var) * (y - mean)^2 + log_var)
            loss = torch.mean(0.5 * torch.exp(-log_var) * (batch_y - mean) ** 2 + 0.5 * log_var)
            
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        if (epoch + 1) % 10 == 0:
            avg_loss = total_loss / len(dataloader)
            logger.info(f"Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.6f}")
    
    return model

def run_mc_dropout_inference(model: MCDropoutModel, X_test: torch.Tensor, 
                            y_test: torch.Tensor, config: Dict[str, Any], 
                            device: torch.device) -> pd.DataFrame:
    """
    Run MC Dropout inference with stochastic forward passes.
    
    Args:
        model: Trained MC Dropout model
        X_test: Test features
        y_test: Test targets
        config: Configuration dictionary
        device: Torch device
        
    Returns:
        DataFrame with predictions and variances
    """
    num_samples = X_test.shape[0]
    num_passes = config['uq']['mc_dropout_passes']  # Should be 30
    dropout_rate = config['uq']['mc_dropout_dropout_rate']  # Should be 0.2
    
    logger.info(f"Running MC Dropout inference with {num_passes} stochastic passes...")
    
    # Ensure model is in train mode to keep dropout active
    model.train()
    
    predictions = []
    variances = []
    
    with torch.no_grad():
        for pass_idx in range(num_passes):
            # Forward pass with dropout enabled (model.train() is active)
            mean, log_var = model(X_test.to(device))
            
            # Convert to CPU and numpy
            pred_mean = mean.cpu().numpy().flatten()
            pred_var = torch.exp(log_var).cpu().numpy().flatten()
            
            predictions.append(pred_mean)
            variances.append(pred_var)
    
    # Stack all passes
    predictions = np.stack(predictions, axis=1)  # shape: (n_samples, n_passes)
    variances = np.stack(variances, axis=1)     # shape: (n_samples, n_passes)
    
    # Calculate mean prediction and total variance across passes
    # Total variance = E[Var] + Var[E] (law of total variance)
    # For MC Dropout: 
    #   - Predictive mean = mean of predictions across passes
    #   - Predictive variance = mean of variances + variance of means
    
    predictive_mean = np.mean(predictions, axis=1)
    predictive_variance = np.mean(variances, axis=1) + np.var(predictions, axis=1)
    
    # Create DataFrame
    results_df = pd.DataFrame({
        'sample_id': range(num_samples),
        'prediction': predictive_mean,
        'variance': predictive_variance,
        'true_value': y_test.cpu().numpy().flatten()
    })
    
    return results_df

def main():
    """Main entry point for MC Dropout training and inference."""
    # Load configuration
    config_path = Path(__file__).parent.parent / 'config.yaml'
    config = load_config(config_path)
    
    # Set device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    logger.info(f"Using device: {device}")
    
    # Load data
    X_train, y_train, X_test, y_test = load_data(config)
    logger.info(f"Loaded data: Train={X_train.shape}, Test={X_test.shape}")
    
    # Initialize model
    input_dim = X_train.shape[1]
    hidden_dims = config['model']['hidden_dims']
    dropout_rate = config['uq']['mc_dropout_dropout_rate']
    
    model = MCDropoutModel(input_dim, hidden_dims, dropout_rate)
    model = model.to(device)
    
    # Train model
    model = train_mc_dropout(model, X_train, y_train, config, device)
    
    # Run inference
    results_df = run_mc_dropout_inference(model, X_test, y_test, config, device)
    
    # Save results
    output_dir = Path(__file__).parent.parent.parent / 'results'
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / 'uq_predictions_mc_dropout.csv'
    
    results_df.to_csv(output_path, index=False)
    logger.info(f"Saved MC Dropout predictions to {output_path}")
    
    # Log summary
    logger.info(f"Predictions summary:")
    logger.info(f"  Mean prediction: {results_df['prediction'].mean():.4f}")
    logger.info(f"  Mean variance: {results_df['variance'].mean():.6f}")
    logger.info(f"  Std variance: {results_df['variance'].std():.6f}")

if __name__ == '__main__':
    main()
