"""
Contract test for regression output schema (T020).

Verifies that the regression results produced by code/analysis.py
conform to the expected output schema defined in specs/001-gene-regulation/contracts/output.schema.yaml.

This test ensures the presence of required fields:
- coefficients (dict)
- p_values (dict)
- interaction_terms (list of strings)
- model_summary (dict containing R2, adjusted_R2, etc.)
- causality_warning (bool)
"""

import os
import json
import pytest
from pathlib import Path
import yaml

# Import project paths helper
from code.config import get_project_root, get_path

# Import the function that generates the regression output
# Note: T027 implements the regression logic. T029 writes the files.
# We test the output file structure as generated by the pipeline.
# If the pipeline hasn't run yet, we test against a mock structure
# that matches what T027/T029 are contractually obligated to produce.
# However, for a true contract test, we should verify the file exists
# and matches the schema.

# Path to the expected output file
PROJECT_ROOT = get_project_root()
OUTPUT_FILE_PATH = PROJECT_ROOT / "reports" / "regression_results.json"

# Path to the schema file
SCHEMA_PATH = PROJECT_ROOT / "specs" / "001-gene-regulation" / "contracts" / "output.schema.yaml"


def load_schema():
    """Load the output schema definition."""
    if not SCHEMA_PATH.exists():
        pytest.fail(f"Schema file not found at {SCHEMA_PATH}. "
                    "Ensure T006 (Create base data schemas) is complete.")
    with open(SCHEMA_PATH, 'r') as f:
        return yaml.safe_load(f)


def load_output_data():
    """Load the generated regression results."""
    if not OUTPUT_FILE_PATH.exists():
        pytest.fail(f"Output file not found at {OUTPUT_FILE_PATH}. "
                    "Ensure T029 (Output structured report) has been executed.")
    with open(OUTPUT_FILE_PATH, 'r') as f:
        return json.load(f)


def test_output_schema_compliance():
    """
    Contract test: Verify regression output matches the schema.

    Checks:
    1. Top-level keys exist (coefficients, p_values, interaction_terms, model_summary, causality_warning)
    2. Types match expectations
    3. Interaction terms are present and non-empty if interaction model was used
    4. Causality warning flag is present
    """
    schema = load_schema()
    data = load_output_data()

    # Define required top-level keys based on T029 spec and output.schema.yaml
    required_keys = [
        "coefficients",
        "p_values",
        "interaction_terms",
        "model_summary",
        "causality_warning"
    ]

    missing_keys = [k for k in required_keys if k not in data]
    assert not missing_keys, f"Output missing required keys: {missing_keys}"

    # Check types
    assert isinstance(data["coefficients"], dict), "coefficients must be a dict"
    assert isinstance(data["p_values"], dict), "p_values must be a dict"
    assert isinstance(data["interaction_terms"], list), "interaction_terms must be a list"
    assert isinstance(data["model_summary"], dict), "model_summary must be a dict"
    assert isinstance(data["causality_warning"], bool), "causality_warning must be a bool"

    # Check interaction terms content (T027 spec: PathologyStatus * BrainRegion)
    # The list should contain strings representing the interaction terms
    if data["interaction_terms"]:
        for term in data["interaction_terms"]:
            assert isinstance(term, str), "Each interaction term must be a string"
            # Basic sanity check for interaction term format
            assert "*" in term or "interaction" in term.lower(), \
                f"Interaction term '{term}' does not appear to contain an interaction operator (*)"

    # Check model summary keys (T027/T029 spec)
    summary_keys = ["r_squared", "adj_r_squared", "f_statistic", "p_value"]
    for key in summary_keys:
        assert key in data["model_summary"], f"model_summary missing key: {key}"

    # Verify causality warning logic (T028 spec)
    # The warning should be True unless randomization is explicitly flagged (which is rare in this context)
    # We verify the flag exists and is a boolean. The actual value depends on input metadata.
    assert data["causality_warning"] in [True, False], "causality_warning must be a boolean"


def test_interaction_terms_match_spec():
    """
    Verify that the specific interaction terms defined in the task (PathologyStatus * BrainRegion)
    are present in the output.
    """
    data = load_output_data()
    terms = data.get("interaction_terms", [])

    # The task T027 specifies: "multiple linear regression with PathologyStatus * BrainRegion interaction terms"
    # We expect at least one interaction term involving these variables.
    has_expected_interaction = False
    for term in terms:
        # Check if the term string contains both variable names
        if "PathologyStatus" in term and "BrainRegion" in term:
            has_expected_interaction = True
            break

    # If the model was run with interactions (which it should be per T027), this should be true.
    # If the dataset had only one region or one pathology status, interactions might be dropped by statsmodels,
    # but the schema should still reflect the attempt or the lack thereof.
    # For the contract test, we assert that if interactions were requested, they appear or are explicitly noted as dropped.
    # Given the spec, we expect the list to be populated if the data supports it.
    # We'll assert that the list is not empty if the model_summary indicates a valid model was fit.
    if data["model_summary"].get("f_statistic") is not None:
        # If the model ran, we expect the schema to reflect the interaction terms defined in the formula.
        # Even if dropped due to collinearity, the 'interaction_terms' list in the output should reflect
        # what was *attempted* or what *remained*.
        # For this contract test, we verify the field exists and is a list.
        # We add a soft assertion that if the list is empty, it's noted.
        pass

    # Strict check: The task requires outputting these terms.
    # If the data allows, they must be there.
    assert len(terms) > 0, "interaction_terms list is empty; expected at least one interaction term per T027"