import os
import sys
import time
import json
import tempfile
import shutil
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error, r2_score

# Ensure project root is in path if running from tests/
if "code" not in sys.path:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "code"))

from src.models.train import train_models
from src.utils.manifest_manager import load_manifest, register_artifact, save_manifest, compute_file_hash

# Constants
MAX_CV_TIME_SECONDS = 3600 * 6  # 6 hours CI limit
MIN_TRAIN_RATIO = 0.80


def create_sample_dataset(n_samples=200):
    """
    Create a realistic mock dataset for integration testing.
    In real execution, this data would come from data/processed/processed_data.csv
    generated by T013/T014.
    """
    np.random.seed(42)
    data = {
        "composition": [f"Glass_{i}" for i in range(n_samples)],
        "Tg": np.random.uniform(300, 600, n_samples),
        "mean_coordination_number": np.random.uniform(2.0, 3.5, n_samples),
        "electronegativity_variance": np.random.uniform(0.1, 1.5, n_samples),
        "atomic_radius_variance": np.random.uniform(0.05, 0.8, n_samples),
        "chemical_family": np.random.choice(["Chalcogenide_A", "Chalcogenide_B", "Chalcogenide_C"], n_samples),
    }
    return pd.DataFrame(data)


@pytest.fixture
def temp_project_root():
    """Create a temporary project structure for integration tests."""
    tmpdir = tempfile.mkdtemp()
    root = Path(tmpdir)
    # Create necessary directories
    (root / "data").mkdir(parents=True)
    (root / "data" / "processed").mkdir(parents=True)
    (root / "state").mkdir(parents=True)
    (root / "artifacts").mkdir(parents=True)
    (root / "code").mkdir(parents=True)
    
    # Initialize manifest
    manifest_path = root / "state" / "manifest.json"
    manifest = {
        "artifacts": {},
        "metadata": {"created": "2023-01-01", "version": "1.0"}
    }
    with open(manifest_path, "w") as f:
        json.dump(manifest, f)
    
    # Write sample data
    df = create_sample_dataset()
    data_path = root / "data" / "processed" / "processed_data.csv"
    df.to_csv(data_path, index=False)
    
    # Update manifest with data hash
    data_hash = compute_file_hash(data_path)
    manifest["artifacts"]["data/processed/processed_data.csv"] = {
        "hash": data_hash,
        "type": "data",
        "path": str(data_path)
    }
    with open(manifest_path, "w") as f:
        json.dump(manifest, f)
    
    yield root
    
    # Cleanup
    shutil.rmtree(tmpdir)


@pytest.fixture
def mock_manifest_path(temp_project_root):
    return temp_project_root / "state" / "manifest.json"


def test_cross_validation_timing(temp_project_root, mock_manifest_path):
    """
    Integration Test: Verify that 5-fold cross-validation completes within the 6-hour CI limit.
    
    This test:
    1. Loads the processed dataset from data/processed/processed_data.csv
    2. Trains the Linear Regression and Gradient Boosting models with 5-fold CV
    3. Measures the total time taken
    4. Asserts time < 6 hours (MAX_CV_TIME_SECONDS)
    """
    # Patch the project root path resolution in the train module if necessary
    # For this test, we assume the train module uses relative paths or we set the env
    os.environ["PROJECT_ROOT"] = str(temp_project_root)
    
    start_time = time.time()
    
    # Run the training pipeline
    # The train_models function is expected to:
    # - Load data from data/processed/processed_data.csv
    # - Perform 5-fold CV
    # - Save metrics to artifacts/performance_metrics.json
    try:
        metrics = train_models(project_root=str(temp_project_root))
    except Exception as e:
        pytest.fail(f"Training pipeline failed unexpectedly: {e}")
    
    elapsed_time = time.time() - start_time
    
    # Assert timing constraint
    assert elapsed_time < MAX_CV_TIME_SECONDS, \
        f"Cross-validation took {elapsed_time:.2f}s, exceeding the 6-hour limit."
    
    # Verify metrics structure
    assert "linear_regression" in metrics
    assert "gradient_boosting" in metrics
    assert "rmse" in metrics["gradient_boosting"]
    assert "r2" in metrics["gradient_boosting"]
    
    # Verify artifact was written
    metrics_file = temp_project_root / "artifacts" / "performance_metrics.json"
    assert metrics_file.exists(), "performance_metrics.json was not created."
    
    with open(metrics_file, "r") as f:
        saved_metrics = json.load(f)
    
    assert saved_metrics["gradient_boosting"]["rmse"] > 0
    assert saved_metrics["gradient_boosting"]["r2"] <= 1.0


def test_metrics_accuracy(temp_project_root, mock_manifest_path):
    """
    Integration Test: Verify that RMSE and R2 metrics are computed correctly
    and that the Gradient Boosting model outperforms or matches the Linear Baseline
    on the held-out test set (or via CV average).
    """
    os.environ["PROJECT_ROOT"] = str(temp_project_root)
    
    metrics = train_models(project_root=str(temp_project_root))
    
    # Basic sanity checks on metrics
    lr_rmse = metrics["linear_regression"]["rmse"]
    gb_rmse = metrics["gradient_boosting"]["rmse"]
    lr_r2 = metrics["linear_regression"]["r2"]
    gb_r2 = metrics["gradient_boosting"]["r2"]
    
    # RMSE must be positive
    assert lr_rmse > 0, "Linear Regression RMSE must be positive."
    assert gb_rmse > 0, "Gradient Boosting RMSE must be positive."
    
    # R2 must be <= 1.0 (can be negative for poor models)
    assert lr_r2 <= 1.0, "Linear Regression R2 cannot exceed 1.0."
    assert gb_r2 <= 1.0, "Gradient Boosting R2 cannot exceed 1.0."
    
    # Log results for manual verification if needed
    print(f"Linear Regression - RMSE: {lr_rmse:.4f}, R2: {lr_r2:.4f}")
    print(f"Gradient Boosting - RMSE: {gb_rmse:.4f}, R2: {gb_r2:.4f}")
    
    # Optional: Assert GB is not drastically worse (heuristic check)
    # In real data, GB should generally perform better or similar to Linear
    if lr_r2 > -10: # Avoid cases where linear is completely broken
        assert gb_r2 >= lr_r2 - 0.1, \
            "Gradient Boosting R2 is significantly worse than Linear Regression (unexpected)."


def test_manifest_update_after_training(temp_project_root, mock_manifest_path):
    """
    Integration Test: Verify that the manifest is updated with the new model artifacts
    and their checksums after training completes.
    """
    os.environ["PROJECT_ROOT"] = str(temp_project_root)
    
    train_models(project_root=str(temp_project_root))
    
    # Load updated manifest
    with open(mock_manifest_path, "r") as f:
        manifest = json.load(f)
    
    # Check that model artifacts are registered
    # The train module should register models and metrics
    assert "artifacts" in manifest
    
    # Check for specific expected artifacts (paths may vary slightly based on implementation)
    expected_artifacts = [
        "artifacts/performance_metrics.json",
        "data/models/linear_regression.pkl",
        "data/models/gradient_boosting.pkl"
    ]
    
    for artifact_path in expected_artifacts:
        full_path = temp_project_root / artifact_path
        # If the artifact exists on disk, it must be in the manifest
        if full_path.exists():
            assert artifact_path in manifest["artifacts"], \
                f"Artifact {artifact_path} exists on disk but not in manifest."
            # Verify hash matches
            recorded_hash = manifest["artifacts"][artifact_path].get("hash")
            actual_hash = compute_file_hash(full_path)
            assert recorded_hash == actual_hash, \
                f"Hash mismatch for {artifact_path}: recorded={recorded_hash}, actual={actual_hash}"


def test_cpu_only_execution(temp_project_root, mock_manifest_path):
    """
    Integration Test: Ensure that the training process runs without GPU/CUDA dependencies.
    This is verified by checking that no CUDA-related errors occur and that the code
    explicitly uses CPU devices (scikit-learn defaults to CPU).
    """
    os.environ["PROJECT_ROOT"] = str(temp_project_root)
    os.environ["CUDA_VISIBLE_DEVICES"] = ""  # Force CPU context
    
    try:
        metrics = train_models(project_root=str(temp_project_root))
    except RuntimeError as e:
        if "CUDA" in str(e) or "gpu" in str(e).lower():
            pytest.fail("Training failed due to GPU/CUDA dependency: " + str(e))
        else:
            raise e
    
    # If we reach here, CPU execution was successful
    assert metrics is not None, "Metrics were not returned."
    assert "gradient_boosting" in metrics, "Gradient Boosting metrics missing."