import os
import csv
import logging
import math
from pathlib import Path
from typing import List, Dict, Tuple, Optional
import pandas as pd
import numpy as np

from src.utils.config import get_project_root, get_processed_data_dir, get_interim_data_dir
from src.analysis.sensitivity import pearson_correlation

logger = logging.getLogger(__name__)

def load_sensitivity_threshold_data(thresholds: List[float]) -> List[pd.DataFrame]:
    """
    Load the sensitivity datasets generated by T030a for each SNR threshold.
    Returns a list of DataFrames corresponding to the input thresholds.
    """
    processed_dir = get_processed_data_dir()
    dataframes = []
    
    for th in thresholds:
        # T030a specified filenames: sensitivity_5db.csv, sensitivity_10db.csv, etc.
        # Construct filename based on threshold value
        filename = f"sensitivity_{int(th)}db.csv"
        filepath = processed_dir / filename
        
        if not filepath.exists():
            logger.warning(f"Threshold file not found: {filepath}. Skipping.")
            continue
        
        try:
            df = pd.read_csv(filepath)
            dataframes.append(df)
        except Exception as e:
            logger.error(f"Error loading {filepath}: {e}")
            continue
    
    return dataframes

def calculate_variation_percent(base_value: float, values: List[float]) -> float:
    """
    Calculate the percentage variation of a list of values relative to a base value.
    Variation = (max(|val - base|) / |base|) * 100
    """
    if base_value == 0:
        return 0.0 if not values else float('inf')
    
    deviations = [abs(v - base_value) for v in values]
    max_deviation = max(deviations) if deviations else 0.0
    return (max_deviation / abs(base_value)) * 100

def calculate_stability_metrics(
    thresholds: List[float], 
    correlation_results: List[Dict]
) -> List[Dict]:
    """
    Calculate stability metrics across thresholds.
    Returns a list of dictionaries containing:
    threshold, sample_size, correlation_r, variation_percent
    """
    results = []
    
    if len(thresholds) != len(correlation_results):
        logger.error("Mismatch between thresholds and correlation results count.")
        return results

    # Extract sample sizes and correlations for all thresholds
    sample_sizes = [res['sample_size'] for res in correlation_results]
    correlations = [res['correlation_r'] for res in correlation_results]

    if not sample_sizes or not correlations:
        return results

    # Use the median or first valid entry as a reference for variation if multiple exist
    # The task asks for variation across thresholds. We calculate variation relative
    # to the first threshold (or a baseline if specified, but here we compare across the set).
    # SC-005: Verify variation <= 10%. We calculate variation relative to the first entry 
    # as the baseline for the sweep.
    baseline_r = correlations[0] if correlations else 0.0
    
    for i, th in enumerate(thresholds):
        n = sample_sizes[i]
        r = correlations[i]
        
        # Calculate variation of correlation relative to the baseline (first threshold)
        # Alternatively, calculate variation of the whole set. 
        # Interpretation: "variation in effect size... across thresholds".
        # We compute the % deviation of the current point from the baseline (threshold 5dB usually).
        # Or, more robustly, the max deviation from the mean? 
        # Let's stick to deviation from the baseline (first threshold) to detect drift.
        if i == 0:
            var_pct = 0.0
        else:
            if baseline_r == 0:
                var_pct = 0.0 if r == 0 else 100.0 # Avoid div by zero
            else:
                var_pct = abs(r - baseline_r) / abs(baseline_r) * 100
        
        results.append({
            'threshold': th,
            'sample_size': n,
            'correlation_r': r,
            'variation_percent': round(var_pct, 4)
        })

    return results

def save_stability_summary(results: List[Dict], output_filename: str = "sensitivity_summary.csv") -> Path:
    """
    Save the stability metrics to a CSV file.
    """
    processed_dir = get_processed_data_dir()
    output_path = processed_dir / output_filename
    
    if not results:
        logger.warning("No results to save for stability summary.")
        return output_path

    with open(output_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['threshold', 'sample_size', 'correlation_r', 'variation_percent'])
        writer.writeheader()
        writer.writerows(results)
    
    logger.info(f"Stability summary saved to {output_path}")
    return output_path

def main():
    """
    Main entry point for T031: Stability Metric calculation.
    1. Load sensitivity data for thresholds (5, 10, 15 dB).
    2. Retrieve correlation results (calculated in T030b).
    3. Calculate variation metrics.
    4. Save to data/processed/sensitivity_summary.csv.
    5. Verify variation <= 10% (log warning if exceeded).
    """
    # Define the thresholds used in T030a
    thresholds = [5.0, 10.0, 15.0]
    
    # Load the datasets
    logger.info(f"Loading sensitivity datasets for thresholds: {thresholds}")
    dfs = load_sensitivity_threshold_data(thresholds)
    
    if not dfs:
        logger.error("No sensitivity datasets found. T030a might not have run.")
        return

    # We need the correlation results. 
    # T030b generated 'sensitivity_counts.csv' and individual 'filtered_records.csv' (or similar).
    # The correlation values (r) are typically stored in a results file or need to be recalculated.
    # The task T030b says "Compute correlation (r) for each threshold dataset".
    # Let's assume T030b saved these correlations. If not, we calculate them here from the loaded DataFrames.
    
    # Check if we have a correlation file from T030b, otherwise calculate on the fly.
    # T030b output: "save_correlation_results" -> likely a file. 
    # Let's try to load from a standard location or recalculate.
    # Recalculating is safer to ensure we have the values corresponding to the loaded data.
    
    correlation_results = []
    processed_dir = get_processed_data_dir()
    
    # Re-calculate correlations to ensure consistency with the loaded data
    for i, df in enumerate(dfs):
        th = thresholds[i]
        if df.empty:
            logger.warning(f"Dataset for threshold {th} is empty.")
            correlation_results.append({'threshold': th, 'sample_size': 0, 'correlation_r': 0.0})
            continue
        
        # Ensure required columns exist
        if 'noise_level_db' not in df.columns or 'complexity_score' not in df.columns:
            # Try to find complexity metric column
            complexity_cols = [c for c in df.columns if 'complexity' in c.lower() or 'entropy' in c.lower()]
            if complexity_cols:
                y_col = complexity_cols[0]
            else:
                logger.error(f"Complexity column not found in threshold {th} dataset.")
                continue
        else:
            y_col = 'complexity_score'
        
        x_col = 'noise_level_db'
        
        # Calculate Pearson r
        # Filter out NaNs
        valid_data = df[[x_col, y_col]].dropna()
        if len(valid_data) < 2:
            r = 0.0
        else:
            r, _ = pearson_correlation(valid_data[x_col], valid_data[y_col])
        
        correlation_results.append({
            'threshold': th,
            'sample_size': len(valid_data),
            'correlation_r': r
        })
    
    # Calculate stability metrics
    stability_metrics = calculate_stability_metrics(thresholds, correlation_results)
    
    # Save results
    output_path = save_stability_summary(stability_metrics)
    
    # Verification
    max_variation = max([m['variation_percent'] for m in stability_metrics]) if stability_metrics else 0.0
    if max_variation > 10.0:
        logger.warning(f"Variation exceeds 10% threshold (Max: {max_variation:.2f}%). SC-005 check failed.")
    else:
        logger.info(f"Variation is within 10% threshold (Max: {max_variation:.2f}%). SC-005 check passed.")

    return output_path

if __name__ == "__main__":
    main()
