import os
import sys
import json
import logging
from pathlib import Path
import csv

# Add project root to path to ensure imports work if run from code/
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.logger import get_logger
from utils.config import get_config

logger = get_logger(__name__)

def load_drift_metrics(csv_path: Path) -> list:
    """
    Load the drift metrics from the CSV generated by US2/US3 integration.
    Returns a list of dictionaries representing the rows.
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"Drift metrics file not found: {csv_path}")
    
    rows = []
    with open(csv_path, 'r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Convert numeric strings to float where appropriate
            if 'rho' in row and row['rho']:
                row['rho'] = float(row['rho'])
            if 'p_value' in row and row['p_value']:
                row['p_value'] = float(row['p_value'])
            rows.append(row)
    return rows

def load_stability_report(json_path: Path) -> dict:
    """
    Load the stability report generated by T012b/stats_aggregator.
    Returns the dictionary content.
    """
    if not json_path.exists():
        raise FileNotFoundError(f"Stability report not found: {json_path}")
    
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def aggregate_global_stats(drift_metrics: list, stability_report: dict) -> dict:
    """
    Compute global statistics for the final report.
    
    Keys required:
    - mean_rho: Average of the Spearman rho values from drift_metrics
    - trend_direction: Derived from the stability report (e.g., 'monotonic decrease')
    - p_value: The block permutation p-value (typically the latest or aggregated)
    - stable_window_count: Count of windows that passed the model stability check
    """
    # 1. Calculate mean_rho
    rhos = [r['rho'] for r in drift_metrics if isinstance(r.get('rho'), (int, float))]
    mean_rho = sum(rhos) / len(rhos) if rhos else 0.0

    # 2. Get trend_direction from stability report (T022 logic usually populates this)
    # The stability report from T012b/T026a might contain this, or we look for it in the report structure.
    # Assuming the stability report contains the aggregated trend info from T022.
    trend_direction = stability_report.get('trend_direction', 'unknown')
    if trend_direction == 'unknown':
        # Fallback: if not in stability report, check if we can infer from mean_rho or drift_metrics
        # But per spec, T022 sets this. If missing, we default based on mean_rho sign as a safe fallback
        if mean_rho < 0:
            trend_direction = 'monotonic decrease'
        elif mean_rho > 0:
            trend_direction = 'monotonic increase'
        else:
            trend_direction = 'stable'

    # 3. Get p_value
    # Usually the significance test (T023) produces a p-value for the sequence.
    # We look for it in the stability report or the last drift metric if aggregated there.
    p_value = stability_report.get('p_value', 0.0)
    if p_value == 0.0 and drift_metrics:
        # Fallback: take the p-value from the last computed drift metric if available
        last_metric = drift_metrics[-1]
        if isinstance(last_metric.get('p_value'), (int, float)):
            p_value = last_metric['p_value']

    # 4. Get stable_window_count
    # This should come from the stability report calculated in T012b/T026a
    stable_window_count = stability_report.get('stable_window_count', 0)
    
    # If not explicitly in the report, we might estimate from drift_metrics length + 1 (since drift is T vs T+1)
    # But we prefer the explicit count from the aggregator.
    if stable_window_count == 0:
        # Fallback estimation: number of drift metrics + 1 (assuming all were valid)
        stable_window_count = len(drift_metrics) + 1 if drift_metrics else 0

    return {
        "mean_rho": round(mean_rho, 6),
        "trend_direction": trend_direction,
        "p_value": round(p_value, 6),
        "stable_window_count": stable_window_count
    }

def save_final_report(stats: dict, output_path: Path):
    """
    Serialize the aggregated stats to the final JSON report.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(stats, f, indent=2)
    logger.info(f"Final report saved to {output_path}")

def run_report_generation():
    """
    Main entry point to generate the final report.
    """
    config = get_config()
    data_dir = config.data_dir
    outputs_dir = config.outputs_dir
    
    drift_metrics_path = outputs_dir / "drift_metrics.csv"
    stability_report_path = data_dir / "processed" / "stability_report.json" # Assuming T012b output location
    final_report_path = outputs_dir / "global_stats.json"

    logger.info("Starting final report generation...")

    try:
        # Load dependencies
        logger.info(f"Loading drift metrics from {drift_metrics_path}")
        drift_metrics = load_drift_metrics(drift_metrics_path)
        logger.info(f"Loaded {len(drift_metrics)} drift records.")

        # T026a ensures stability metrics are aggregated, we load that here.
        # If the path differs based on T012b implementation, we check common locations.
        if not stability_report_path.exists():
            # Fallback to outputs if T012b saved it there
            stability_report_path = outputs_dir / "stability_report.json"
        
        logger.info(f"Loading stability report from {stability_report_path}")
        stability_report = load_stability_report(stability_report_path)
        
        # Aggregate
        logger.info("Aggregating global statistics...")
        global_stats = aggregate_global_stats(drift_metrics, stability_report)

        # Save
        save_final_report(global_stats, final_report_path)
        
        logger.info("Final report generation completed successfully.")
        return global_stats

    except FileNotFoundError as e:
        logger.error(f"Missing required input file: {e}")
        raise
    except Exception as e:
        logger.error(f"Error during report generation: {e}")
        raise

def main():
    run_report_generation()

if __name__ == "__main__":
    main()