"""
Sensitivity Analysis Module for PROJ-071.

This module implements the sensitivity analysis requirement (FR-005) via LASSO regression
with K-fold cross-validation. It loads the standard subset of data, performs bootstrap
    resampling to assess correlation stability, and evaluates the robustness of the regression
    models against data perturbations.

    Note: This task (T022a) fulfills the "Sensitivity Analysis" requirement explicitly rejected
    in the task list because T024 (LASSO) was thought to cover it. However, FR-005 requires
    explicit sensitivity analysis (stability of results under perturbation), which is distinct
    from the model selection process of LASSO. This script provides that specific analysis.
    """

import os
import sys
import json
import logging
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional
from sklearn.linear_model import LassoCV, Lasso
from sklearn.model_selection import cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from scipy.stats import pearsonr, spearmanr
import itertools

from config import get_config, ensure_directories
from logging_config import get_logger

# Setup logger
logger = get_logger(__name__)

def get_data_path() -> Path:
    """Return the path to the processed data directory."""
    config = get_config()
    return Path(config['paths']['data_processed'])

def load_standard_subset() -> pd.DataFrame:
    """
    Load the standard_subset.csv generated by T021.
    Raises FileNotFoundError if the file does not exist.
    """
    data_path = get_data_path()
    file_path = data_path / "standard_subset.csv"
    
    if not file_path.exists():
        raise FileNotFoundError(
            f"Standard subset file not found at {file_path}. "
            "Please ensure T021 (standardize.py) has been executed successfully."
        )
    
    logger.info(f"Loading standard subset from {file_path}")
    df = pd.read_csv(file_path)
    
    # Log shape and columns
    logger.info(f"Loaded dataset shape: {df.shape}, columns: {list(df.columns)}")
    return df

def bootstrap_correlation(
    df: pd.DataFrame, 
    target_col: str, 
    feature_cols: List[str], 
    n_iterations: int = 1000, 
    random_state: Optional[int] = None
) -> Dict[str, Any]:
    """
    Perform bootstrap resampling to assess the stability of correlations.
    
    Args:
        df: The dataframe containing the data.
        target_col: The target variable column name (e.g., 'half_life_hours').
        feature_cols: List of feature column names to test against the target.
        n_iterations: Number of bootstrap iterations.
        random_state: Random seed for reproducibility.
        
    Returns:
        A dictionary containing the mean, std, and confidence intervals for 
        the correlation coefficients of each feature.
    """
    if random_state is not None:
        np.random.seed(random_state)
        
    n_samples = len(df)
    results = {col: [] for col in feature_cols}
    
    logger.info(f"Starting bootstrap correlation analysis with {n_iterations} iterations.")
    
    for i in range(n_iterations):
        # Resample with replacement
        indices = np.random.choice(n_samples, size=n_samples, replace=True)
        sample_df = df.iloc[indices]
        
        for col in feature_cols:
            # Drop rows with NaN in target or feature
            valid = sample_df[[target_col, col]].dropna()
            if len(valid) > 2:
                r, _ = pearsonr(valid[target_col], valid[col])
                results[col].append(r)
            else:
                results[col].append(np.nan)
    
    summary = {}
    for col, vals in results.items():
        valid_vals = [v for v in vals if not np.isnan(v)]
        if len(valid_vals) > 0:
            summary[col] = {
                "mean": float(np.mean(valid_vals)),
                "std": float(np.std(valid_vals)),
                "ci_lower": float(np.percentile(valid_vals, 2.5)),
                "ci_upper": float(np.percentile(valid_vals, 97.5)),
                "n_valid": len(valid_vals)
            }
        else:
            summary[col] = {
                "mean": None,
                "std": None,
                "ci_lower": None,
                "ci_upper": None,
                "n_valid": 0
            }
            
    return summary

def run_sensitivity_analysis(
    df: pd.DataFrame,
    target_col: str = 'half_life_hours',
    feature_cols: Optional[List[str]] = None,
    n_bootstrap: int = 1000
) -> Dict[str, Any]:
    """
    Run the full sensitivity analysis pipeline:
    1. Bootstrap correlation stability.
    2. LASSO coefficient stability (via cross-validation variance).
    
    Args:
        df: Input dataframe.
        target_col: Target variable name.
        feature_cols: List of feature names. If None, selects numeric columns excluding target.
        n_bootstrap: Number of bootstrap iterations.
        
    Returns:
        Dictionary containing analysis results.
    """
    if feature_cols is None:
        # Select numeric columns that are not the target
        feature_cols = [c for c in df.select_dtypes(include=[np.number]).columns if c != target_col]
        
    logger.info(f"Running sensitivity analysis on features: {feature_cols}")
    
    # 1. Bootstrap Correlation
    logger.info("Performing bootstrap correlation analysis...")
    boot_results = bootstrap_correlation(df, target_col, feature_cols, n_iterations=n_bootstrap)
    
    # 2. LASSO Stability (using CV scores variance as a proxy for sensitivity)
    # We use the LassoCV from T024 logic but explicitly report the stability of the alpha selection
    # and the variance of coefficients if we were to retrain on subsets.
    logger.info("Performing LASSO coefficient stability analysis...")
    
    X = df[feature_cols].dropna().values
    y = df.loc[X[:, 0].nonzero()[0], target_col].values # Align indices roughly, better to dropna on both
    
    # Robust alignment for LASSO
    mask = ~df[feature_cols + [target_col]].isna().any(axis=1)
    X_clean = df.loc[mask, feature_cols].values
    y_clean = df.loc[mask, target_col].values
    
    if len(X_clean) < 5:
        logger.warning("Insufficient data for LASSO sensitivity analysis.")
        lasso_stability = {"error": "Insufficient data"}
    else:
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X_clean)
        
        # Use a subset of alphas for speed if dataset is large, but keep standard grid
        alphas = [0.01, 0.1, 1.0]
        
        lasso_cv = LassoCV(alphas=alphas, cv=min(5, len(X_clean)-1), random_state=42)
        lasso_cv.fit(X_scaled, y_clean)
        
        # Calculate coefficient variance via K-Fold (internal to LassoCV)
        # We can't easily access per-fold coeffs from LassoCV directly, so we simulate
        # by training on K-folds manually or using the cv_scores_ variance.
        # A robust sensitivity metric is the variance of the selected alpha's coefficients
        # across different random seeds or data splits.
        
        # Simulate split sensitivity: Train on 80% of data, check coefficient variance
        n_splits = 5
        kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
        coef_variance = np.zeros(len(feature_cols))
        coef_means = np.zeros(len(feature_cols))
        
        for train_idx, test_idx in kf.split(X_scaled):
            X_tr, X_te = X_scaled[train_idx], X_scaled[test_idx]
            y_tr, y_te = y_clean[train_idx], y_clean[test_idx]
            
            # Retrain with optimal alpha found globally
            lasso_temp = Lasso(alpha=lasso_cv.alpha_, random_state=42)
            lasso_temp.fit(X_tr, y_tr)
            
            coef_variance += lasso_temp.coef_
            coef_means += lasso_temp.coef_
            
        coef_variance /= n_splits
        coef_means /= n_splits
        
        # Variance of the mean coefficients across folds
        # We compute the variance of the coefficients themselves across the folds
        # (This is a simplified proxy; full bootstrapping of coefficients is heavy)
        # Instead, let's report the range of coefficients observed across folds
        all_coefs = []
        for train_idx, test_idx in kf.split(X_scaled):
            X_tr = X_scaled[train_idx]
            y_tr = y_clean[train_idx]
            lasso_temp = Lasso(alpha=lasso_cv.alpha_, random_state=42)
            lasso_temp.fit(X_tr, y_tr)
            all_coefs.append(lasso_temp.coef_)
        
        all_coefs = np.array(all_coefs)
        coef_std = np.std(all_coefs, axis=0)
        
        lasso_stability = {
            "alpha_selected": float(lasso_cv.alpha_),
            "coef_mean": coef_means.tolist(),
            "coef_std": coef_std.tolist(),
            "cv_r2_mean": float(np.mean(lasso_cv.cv_scores_.mean(axis=1))), # Approximate
            "cv_r2_std": float(np.std(lasso_cv.cv_scores_.mean(axis=1)))
        }
    
    return {
        "bootstrap_correlation": boot_results,
        "lasso_stability": lasso_stability,
        "parameters": {
            "n_bootstrap": n_bootstrap,
            "n_splits": 5,
            "target": target_col,
            "features": feature_cols
        }
    }

def save_sensitivity_results(results: Dict[str, Any], output_path: Optional[Path] = None) -> Path:
    """Save sensitivity analysis results to JSON."""
    if output_path is None:
        output_dir = get_data_path() / "outputs"
        ensure_directories([output_dir])
        output_path = output_dir / "sensitivity_analysis_results.json"
    else:
        output_dir = output_path.parent
        ensure_directories([output_dir])
        
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
        
    logger.info(f"Sensitivity analysis results saved to {output_path}")
    return output_path

def main():
    """Main entry point for T022a Sensitivity Analysis."""
    try:
        # Ensure directories
        config = get_config()
        ensure_directories([Path(config['paths']['data_processed']), Path(config['paths']['data_output'])])
        
        # Load data
        df = load_standard_subset()
        
        # Define target and features
        target = 'half_life_hours'
        if target not in df.columns:
            logger.error(f"Target column '{target}' not found in dataset. Columns: {list(df.columns)}")
            sys.exit(1)
            
        # Run analysis
        results = run_sensitivity_analysis(df, target_col=target, n_bootstrap=500)
        
        # Save results
        save_path = save_sensitivity_results(results)
        
        # Log summary
        logger.info("Sensitivity Analysis Complete.")
        logger.info(f"Bootstrap Correlation Summary: {results['bootstrap_correlation']}")
        logger.info(f"LASSO Stability: Alpha={results['lasso_stability'].get('alpha_selected', 'N/A')}")
        
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"Data file missing: {e}")
        return 1
    except Exception as e:
        logger.exception(f"An error occurred during sensitivity analysis: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())