import json
import os
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import logging

# Import shared logging configuration
from logging_config import setup_logging, get_logger, VisualizationError

# Configure logger
logger = get_logger(__name__)
setup_logging()

# Ensure output directory exists
OUTPUT_DIR = Path("data/outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def load_analysis_results() -> Dict[str, Any]:
    """
    Load the analysis results from the JSON file generated by T026.
    Returns the dictionary containing regression coefficients, p-values, R2, etc.
    """
    results_path = Path("data/processed/analysis_results.json")
    if not results_path.exists():
        raise FileNotFoundError(f"Analysis results not found at {results_path}. "
                                "Please run the analysis pipeline (T026) first.")
    
    with open(results_path, 'r') as f:
        return json.load(f)

def load_residuals_data() -> pd.DataFrame:
    """
    Load the residual data required for diagnostic plots.
    This assumes the analysis pipeline (T025) saved residuals to a specific file
    or that we can reconstruct them from the analysis results and the standard subset.
    
    For this implementation, we expect the analysis_results.json to contain 
    'residuals' key or we load from a dedicated residuals file if created by T025.
    Given the task dependency T025, we assume T025 saved residuals to 
    data/processed/residuals.csv or embedded them in analysis_results.json.
    
    We will try to load from analysis_results.json first, then fallback to CSV.
    """
    results = load_analysis_results()
    
    if 'residuals' in results:
        logger.info("Loading residuals from analysis_results.json")
        return pd.DataFrame(results['residuals'])
    
    # Fallback: Check for a dedicated residuals file created by T025
    residuals_path = Path("data/processed/residuals.csv")
    if residuals_path.exists():
        logger.info(f"Loading residuals from {residuals_path}")
        return pd.read_csv(residuals_path)
    
    # If neither exists, we cannot proceed without data
    # In a real pipeline, T025 should have created this.
    # We will raise an error to fail loudly as per constraints.
    raise FileNotFoundError(
        "Residual data not found. T025 (Residual Diagnostics) must save residuals "
        "to 'data/processed/residuals.csv' or include them in 'data/processed/analysis_results.json'."
    )

def plot_residual_histogram(residuals: pd.Series, output_path: Path) -> None:
    """
    Generate a histogram of residuals with a KDE overlay.
    """
    plt.figure(figsize=(10, 6))
    sns.histplot(residuals, kde=True, color='skyblue', edgecolor='black')
    plt.axvline(x=0, color='red', linestyle='--', linewidth=2, label='Zero Residual')
    plt.title('Histogram of Residuals', fontsize=14)
    plt.xlabel('Residual Value', fontsize=12)
    plt.ylabel('Frequency', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    logger.info(f"Saved residual histogram to {output_path}")

def plot_qq_plot(residuals: pd.Series, output_path: Path) -> None:
    """
    Generate a Quantile-Quantile (QQ) plot to check normality of residuals.
    """
    plt.figure(figsize=(10, 6))
    # Use statsmodels or scipy for QQ plot
    # Using scipy's ppf and sorted data
    sorted_residuals = np.sort(residuals)
    theoretical_quantiles = stats.norm.ppf(np.arange(1, len(sorted_residuals) + 1) / (len(sorted_residuals) + 1))
    
    plt.scatter(theoretical_quantiles, sorted_residuals, alpha=0.7, color='darkblue')
    
    # Add reference line
    min_q, max_q = theoretical_quantiles.min(), theoretical_quantiles.max()
    min_r, max_r = sorted_residuals.min(), sorted_residuals.max()
    plt.plot([min_q, max_q], [min_r, max_r], 'r--', linewidth=2, label='Normal Reference')
    
    plt.title('Normal Q-Q Plot', fontsize=14)
    plt.xlabel('Theoretical Quantiles', fontsize=12)
    plt.ylabel('Sample Quantiles', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    logger.info(f"Saved QQ plot to {output_path}")

def plot_residuals_vs_fitted(fitted_values: pd.Series, residuals: pd.Series, output_path: Path) -> None:
    """
    Generate a scatter plot of residuals vs fitted values to check homoscedasticity.
    """
    plt.figure(figsize=(10, 6))
    plt.scatter(fitted_values, residuals, alpha=0.7, color='darkgreen', edgecolors='black')
    plt.axhline(y=0, color='red', linestyle='--', linewidth=2, label='Zero Residual')
    
    # Optional: Add a lowess smooth line to detect patterns
    # Since lowess might not be available in all environments without extra deps,
    # we stick to scatter + reference line for robustness, or use a simple trend line if needed.
    # For simplicity and compliance with standard libs, we omit complex smoothing if not critical.
    
    plt.title('Residuals vs Fitted Values', fontsize=14)
    plt.xlabel('Fitted Values', fontsize=12)
    plt.ylabel('Residuals', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    logger.info(f"Saved residuals vs fitted plot to {output_path}")

def generate_residual_diagnostic_plots() -> Dict[str, str]:
    """
    Main function to generate all residual diagnostic plots.
    Returns a dictionary of output file paths.
    """
    try:
        # Load data
        logger.info("Loading residuals data...")
        residuals_df = load_residuals_data()
        
        # Ensure we have the necessary columns
        # Expected columns: 'residuals' and 'fitted' (or similar)
        # If the dataframe has 'residuals' and 'fitted', use them.
        # If it's a Series, we need fitted values too.
        
        if isinstance(residuals_df, pd.DataFrame):
            if 'residuals' not in residuals_df.columns:
                raise KeyError("Column 'residuals' not found in residuals data.")
            if 'fitted' not in residuals_df.columns:
                # Try to find fitted values or reconstruct if possible
                # For now, assume 'fitted' exists or we load it from analysis_results if separate
                # If T025 saved them together, this should be fine.
                # If not, we might need to load fitted values separately.
                # Let's assume the structure from T025 includes 'fitted' or we calculate from data.
                # If missing, we raise an error to fail loudly.
                raise KeyError("Column 'fitted' not found in residuals data. T025 must provide fitted values.")
            
            residuals = residuals_df['residuals']
            fitted_values = residuals_df['fitted']
        elif isinstance(residuals_df, pd.Series):
            # If it's a series, we assume fitted values are stored elsewhere or need to be loaded
            # This is less ideal, but we handle it by looking for a 'fitted' key in the original results
            results = load_analysis_results()
            if 'fitted' in results:
                fitted_values = pd.Series(results['fitted'])
            else:
                raise KeyError("Residuals provided as Series but 'fitted' values not found in analysis results.")
            residuals = residuals_df
        else:
            raise ValueError("Unexpected type for residuals data.")
        
        # Define output paths
        hist_path = OUTPUT_DIR / "residuals_histogram.png"
        qq_path = OUTPUT_DIR / "qq_plot.png"
        fitted_path = OUTPUT_DIR / "residuals_vs_fitted.png"
        
        # Generate plots
        logger.info("Generating residual histogram...")
        plot_residual_histogram(residuals, hist_path)
        
        logger.info("Generating QQ plot...")
        plot_qq_plot(residuals, qq_path)
        
        logger.info("Generating residuals vs fitted plot...")
        plot_residuals_vs_fitted(fitted_values, residuals, fitted_path)
        
        return {
            "histogram": str(hist_path),
            "qq_plot": str(qq_path),
            "residuals_vs_fitted": str(fitted_path)
        }
        
    except Exception as e:
        logger.error(f"Failed to generate residual diagnostic plots: {e}", exc_info=True)
        raise VisualizationError(f"Error generating residual plots: {e}") from e

def main() -> None:
    """
    Entry point for the visualization task T033.
    Generates residual diagnostic plots and saves them to data/outputs/.
    """
    logger.info("Starting T033: Residual Diagnostic Plots Generation")
    
    try:
        results = generate_residual_diagnostic_plots()
        
        logger.info("T033 completed successfully. Generated files:")
        for plot_type, path in results.items():
            logger.info(f"  - {plot_type}: {path}")
            
    except Exception as e:
        logger.error(f"T033 failed: {e}")
        raise

if __name__ == "__main__":
    main()