import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error

# Local imports matching API surface
from utils.logging import get_logger
from utils.config import get_model_results_path, get_processed_dataset_path, get_split_indices_path, get_config
from utils.exceptions import SchemaMismatchError

logger = get_logger(__name__)

def load_split_indices() -> Dict[str, Any]:
    """Load the LOSO split indices generated by T015/T017."""
    config = get_config()
    split_path = Path(get_split_indices_path())
    
    if not split_path.exists():
        raise FileNotFoundError(f"Split indices file not found at {split_path}. "
                                "Ensure T015 (split.py) has been executed.")
    
    with open(split_path, 'r') as f:
        return json.load(f)

def load_processed_data() -> pd.DataFrame:
    """Load the preprocessed dataset generated by T013."""
    config = get_config()
    data_path = get_processed_dataset_path()
    
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"Processed dataset not found at {data_path}. "
                                "Ensure T013 (preprocess.py) has been executed.")
    
    df = pd.read_parquet(data_path)
    logger.info(f"Loaded processed dataset with {len(df)} records.")
    return df

def load_model_predictions() -> Tuple[pd.DataFrame, pd.Series, pd.Series]:
    """
    Load predictions and targets from the trained model artifacts.
    Assumes T020 (train.py) has saved predictions for each fold.
    
    Returns:
        y_true: All true values concatenated
        y_pred: All predicted values concatenated
        fold_ids: Fold assignment for each record
    """
    model_results_path = get_model_results_path()
    
    # Check if temporary results exist (created by train.py)
    # If train.py saves a specific 'predictions' artifact, load from there.
    # Based on T020, it saves model artifacts. We assume train.py also 
    # emits a temporary predictions file or we reconstruct from model artifacts.
    # To be robust, we look for a specific predictions file generated by train.py.
    
    # Strategy: train.py should have saved a file like data/processed/temp_predictions.parquet
    # or similar. If not, we might need to re-infer or the task T020 must have produced it.
    # Let's assume train.py produced 'data/processed/train_predictions.parquet' with columns:
    # 'record_id', 'potential_mV', 'predicted_mV', 'fold_id'
    
    pred_path = Path(get_processed_dataset_path()).parent / "processed" / "train_predictions.parquet"
    if not pred_path.exists():
        # Fallback: try to load from model_results.json if it contains predictions
        # But usually, we need a separate file for large arrays.
        # Let's check if model_results.json has the data (unlikely for full arrays).
        # We will raise a clear error if the expected file is missing.
        raise FileNotFoundError(
            f"Predictions file not found at {pred_path}. "
            "Ensure T020 (train.py) has generated predictions and saved them to "
            "data/processed/train_predictions.parquet."
        )
    
    df_preds = pd.read_parquet(pred_path)
    
    required_cols = ['potential_mV', 'predicted_mV', 'fold_id']
    if not all(col in df_preds.columns for col in required_cols):
        raise SchemaMismatchError(
            f"Predictions file missing required columns. Expected {required_cols}, "
            f"found {df_preds.columns.tolist()}"
        )
    
    y_true = df_preds['potential_mV']
    y_pred = df_preds['predicted_mV']
    fold_ids = df_preds['fold_id']
    
    logger.info(f"Loaded predictions for {len(y_true)} records.")
    return y_true, y_pred, fold_ids

def calculate_fold_metrics(y_true: pd.Series, y_pred: pd.Series, fold_ids: pd.Series) -> Dict[str, Dict[str, float]]:
    """
    Calculate R² and RMSE for each fold and aggregate metrics.
    
    Returns:
        dict: Metrics per fold and overall aggregate
    """
    results = {
        "per_fold": {},
        "aggregate": {}
    }
    
    unique_folds = sorted(fold_ids.unique())
    all_r2 = []
    all_rmse = []
    
    for fold in unique_folds:
        mask = fold_ids == fold
        y_t = y_true[mask]
        y_p = y_pred[mask]
        
        if len(y_t) == 0:
            logger.warning(f"Fold {fold} has no records.")
            continue
        
        r2 = r2_score(y_t, y_p)
        rmse = np.sqrt(mean_squared_error(y_t, y_p))
        
        results["per_fold"][str(fold)] = {
            "r2": float(r2),
            "rmse_mV": float(rmse),
            "n_samples": int(len(y_t))
        }
        
        all_r2.append(r2)
        all_rmse.append(rmse)
        
        logger.info(f"Fold {fold}: R²={r2:.4f}, RMSE={rmse:.4f} mV")
    
    # Aggregate metrics (mean and std across folds)
    if all_r2:
        results["aggregate"] = {
            "r2_mean": float(np.mean(all_r2)),
            "r2_std": float(np.std(all_r2)),
            "rmse_mean_mV": float(np.mean(all_rmse)),
            "rmse_std_mV": float(np.std(all_rmse)),
            "total_samples": int(len(y_true))
        }
    else:
        raise SchemaMismatchError("No valid folds found to calculate aggregate metrics.")
        
    return results

def save_evaluation_results(metrics: Dict[str, Any], output_path: Optional[str] = None):
    """
    Save evaluation metrics to the project's model results file.
    Merges with existing model results if they exist (e.g., from train.py).
    """
    if output_path is None:
        output_path = get_model_results_path()
    
    output_file = Path(output_path)
    
    # Ensure directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Load existing results if present to merge
    existing_results = {}
    if output_file.exists():
        with open(output_file, 'r') as f:
            existing_results = json.load(f)
    
    # Update with new evaluation metrics
    existing_results["evaluation"] = metrics
    existing_results["evaluation_timestamp"] = pd.Timestamp.now().isoformat()
    
    with open(output_file, 'w') as f:
        json.dump(existing_results, f, indent=2)
    
    logger.info(f"Evaluation results saved to {output_file}")

def main():
    """
    Main entry point for T021: Evaluate model performance.
    
    1. Load split indices (from T015/T017)
    2. Load predictions (from T020)
    3. Calculate R² and RMSE per fold and aggregate
    4. Save results to data/processed/model_results.json
    """
    logger.info("Starting evaluation pipeline (T021)...")
    
    try:
        # 1. Verify splits exist (dependency check)
        split_indices = load_split_indices()
        logger.info(f"Loaded split indices with {len(split_indices.get('folds', []))} folds.")
        
        # 2. Load predictions
        y_true, y_pred, fold_ids = load_model_predictions()
        
        # 3. Calculate metrics
        metrics = calculate_fold_metrics(y_true, y_pred, fold_ids)
        
        # 4. Save results
        save_evaluation_results(metrics)
        
        logger.info("Evaluation completed successfully.")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"Data file missing: {e}")
        logger.error("Ensure T015 (split) and T020 (train) have been executed successfully.")
        return 1
    except SchemaMismatchError as e:
        logger.error(f"Schema validation failed: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error during evaluation: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())