"""
T032: Generate performance_metrics.json artifact.

Aggregates metrics from:
- Evaluation (RMSE, R²) from src/models/evaluate.py
- VIF and collinearity mitigation from src/utils/metrics.py
- Power analysis (MDES) from src/data/preprocess.py
- SHAP confidence intervals from src/utils/metrics.py
- Transferability flags from src/models/explain.py
"""
import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional

# Add project root to path if running as script
if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    sys.path.insert(0, str(project_root))

from src.utils.manifest_manager import load_manifest, save_manifest
from src.data.preprocess import perform_power_analysis
from src.utils.metrics import compute_vif, update_performance_metrics
from src.models.evaluate import calculate_rmse, calculate_r2

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_json_artifact(path: Path, default: Optional[Dict] = None) -> Dict:
    """Load a JSON artifact, returning default if missing or invalid."""
    if not path.exists():
        if default is not None:
            logger.warning(f"Artifact {path} not found. Using default: {default}")
            return default
        raise FileNotFoundError(f"Required artifact {path} not found")
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse {path}: {e}")
        if default is not None:
            return default
        raise

def aggregate_metrics(project_root: Path) -> Dict[str, Any]:
    """
    Aggregate all required metrics into a single dictionary.
    """
    metrics = {
        "rmse": None,
        "r2": None,
        "mdes": None,
        "vif": {},
        "ci_lower": None,
        "ci_upper": None,
        "is_significant": None,
        "transferability_flags": {},
        "collinearity_mitigation": None,
        "power_limitation_message": None
    }

    # 1. Load Evaluation Metrics (RMSE, R²)
    eval_path = project_root / "artifacts" / "performance_metrics.json"
    # Note: T019/T021 likely saved a preliminary metrics file here.
    # If T021 saved specific RMSE/R2, we read them.
    # If not, we assume the model training script saved them or we need to re-calculate.
    # Based on task T021 description, it saves results. Let's assume a standard location
    # or reconstruct if T021 output is in a specific format.
    # The prompt says T021 computes RMSE/R2. Let's look for a generic metrics file
    # or the one T021 might have created.
    
    # Fallback: Try to find the metrics file generated by T021 (evaluate.py)
    # Assuming it was saved as 'artifacts/performance_metrics.json' or similar.
    # If T021 didn't run or saved elsewhere, we might need to re-run evaluation.
    # However, T030 and T031 are marked complete, implying models exist.
    # Let's try to load from artifacts/performance_metrics.json first.
    
    eval_file = project_root / "artifacts" / "performance_metrics.json"
    if eval_file.exists():
        eval_data = load_json_artifact(eval_file)
        if "rmse" in eval_data:
            metrics["rmse"] = eval_data["rmse"]
        if "r2" in eval_data:
            metrics["r2"] = eval_data["r2"]
        if "collinearity_mitigation" in eval_data:
            metrics["collinearity_mitigation"] = eval_data["collinearity_mitigation"]
        if "ci_lower" in eval_data:
            metrics["ci_lower"] = eval_data["ci_lower"]
        if "ci_upper" in eval_data:
            metrics["ci_upper"] = eval_data["ci_upper"]
        if "is_significant" in eval_data:
            metrics["is_significant"] = eval_data["is_significant"]
    else:
        logger.warning("Evaluation metrics file not found. Metrics may be incomplete.")

    # 2. Load Power Analysis (MDES)
    power_path = project_root / "state" / "power_analysis.json"
    if power_path.exists():
        power_data = load_json_artifact(power_path)
        if "mdes" in power_data:
            metrics["mdes"] = power_data["mdes"]
        if "power" in power_data:
            # Store power value if needed, but task asks for MDES
            pass
        if "power_limitation_message" in power_data:
            metrics["power_limitation_message"] = power_data["power_limitation_message"]
    else:
        logger.warning("Power analysis file not found. MDES will be null.")

    # 3. Compute/Load VIF
    # T022 computes VIF. We need the processed data to compute it again or load it.
    # If T022 saved VIF to performance_metrics.json, we have it.
    # If not, we compute it from the processed data.
    processed_data_path = project_root / "data" / "processed" / "chalcogenide_processed.csv"
    if processed_data_path.exists():
        import pandas as pd
        df = pd.read_csv(processed_data_path)
        # Identify feature columns (exclude composition, Tg, family)
        feature_cols = [c for c in df.columns if c not in ['composition', 'Tg', 'chemical_family']]
        if len(feature_cols) > 1:
            try:
                vif_values = compute_vif(df[feature_cols])
                metrics["vif"] = vif_values
            except Exception as e:
                logger.error(f"Failed to compute VIF: {e}")
    else:
        logger.warning("Processed data not found. Cannot compute VIF.")

    # 4. Load Transferability Flags
    # T030 (explain.py) should have generated transferability metrics.
    # It likely saved them in artifacts/ or data/models/
    transfer_path = project_root / "artifacts" / "transferability_results.json"
    if transfer_path.exists():
        transfer_data = load_json_artifact(transfer_path)
        metrics["transferability_flags"] = transfer_data.get("flags", {})
    else:
        # Check if T030 saved it elsewhere or if we need to reconstruct
        logger.warning("Transferability results not found. Flags will be empty.")

    return metrics

def main():
    """
    Main entry point for T032.
    Generates artifacts/performance_metrics.json with aggregated metrics.
    """
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    logger.info(f"Project root: {project_root}")

    # Ensure artifacts directory exists
    artifacts_dir = project_root / "artifacts"
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    # Aggregate metrics
    metrics = aggregate_metrics(project_root)

    # Write to artifacts/performance_metrics.json
    output_path = artifacts_dir / "performance_metrics.json"
    with open(output_path, 'w') as f:
        json.dump(metrics, f, indent=2)

    logger.info(f"Successfully generated {output_path}")

    # Update manifest
    try:
        manifest_path = project_root / "state" / "manifest.json"
        if manifest_path.exists():
            from src.utils.manifest_manager import register_artifact
            register_artifact(str(output_path), str(project_root))
            logger.info("Updated manifest with new artifact.")
        else:
            logger.warning("Manifest not found. Skipping manifest update.")
    except Exception as e:
        logger.error(f"Failed to update manifest: {e}")

    return 0

if __name__ == "__main__":
    sys.exit(main())