"""
T025: Generate the summary CSV file at results/analysis/paired_comparison.csv.

This script loads the paired comparison results generated by T024 (comparator.py),
aggregates them by task_type, calculates mean success rates, and outputs a summary CSV.

Output Schema:
  - task_id: Unique identifier for the task instance (or 'AGGREGATE' for summary rows)
  - task_type: Type of spatial task (occlusion, depth, relative)
  - success_flag: Mean success rate for this task_type (0.0 to 1.0)
  - wall_clock_time_ms: Mean wall-clock time for this task_type
  - agent_type: '2D' or '3D' (aggregated per agent type per task_type)
"""

import csv
import os
import logging
from typing import List, Dict, Any, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Ensure output directory exists
OUTPUT_DIR = "results/analysis"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "paired_comparison.csv")
INPUT_FILE = "results/analysis/paired_comparison_raw.csv"  # Assumed output from T024 comparator

def load_comparison_results(input_path: str) -> List[Dict[str, Any]]:
    """Load the raw paired comparison results CSV."""
    if not os.path.exists(input_path):
        raise FileNotFoundError(
            f"Input file not found: {input_path}. "
            "Ensure T024 (comparator.py) has been executed to generate this file."
        )

    results = []
    with open(input_path, 'r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Parse numeric fields
            try:
                row['success_flag'] = float(row['success_flag']) if row['success_flag'] else None
                row['wall_clock_time_ms'] = float(row['wall_clock_time_ms']) if row['wall_clock_time_ms'] else None
            except ValueError as e:
                logger.warning(f"Skipping row due to parsing error: {e}")
                continue
            results.append(row)
    return results

def aggregate_by_task_type(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Group by task_type and agent_type, calculate mean(success_flag) and mean(wall_clock_time_ms).
    Exclude rows where success_flag is null.
    """
    aggregates: Dict[str, Dict[str, Any]] = {}

    for row in results:
        # Skip rows with null success_flag as per requirement
        if row['success_flag'] is None:
            logger.debug(f"Skipping row {row.get('task_id')} due to null success_flag")
            continue

        task_type = row.get('task_type', 'unknown')
        agent_type = row.get('agent_type', 'unknown')
        key = (task_type, agent_type)

        if key not in aggregates:
            aggregates[key] = {
                'task_type': task_type,
                'agent_type': agent_type,
                'success_flags': [],
                'times': [],
                'task_ids': []
            }

        aggregates[key]['success_flags'].append(row['success_flag'])
        if row['wall_clock_time_ms'] is not None:
            aggregates[key]['times'].append(row['wall_clock_time_ms'])
        aggregates[key]['task_ids'].append(row.get('task_id', 'N/A'))

    summary_rows = []
    for (task_type, agent_type), data in aggregates.items():
        mean_success = sum(data['success_flags']) / len(data['success_flags'])
        mean_time = sum(data['times']) / len(data['times']) if data['times'] else 0.0

        # Use 'AGGREGATE' for task_id as this is a summary row
        summary_rows.append({
            'task_id': 'AGGREGATE',
            'task_type': task_type,
            'success_flag': round(mean_success, 4),
            'wall_clock_time_ms': round(mean_time, 2),
            'agent_type': agent_type
        })

    return summary_rows

def write_summary_csv(summary_rows: List[Dict[str, Any]], output_path: str) -> None:
    """Write the aggregated summary to a CSV file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    fieldnames = ['task_id', 'task_type', 'success_flag', 'wall_clock_time_ms', 'agent_type']

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(summary_rows)

    logger.info(f"Summary written to {output_path} with {len(summary_rows)} rows.")

def main():
    logger.info("Starting T025: Generate Paired Comparison Summary")

    try:
        # Load raw results
        logger.info(f"Loading results from {INPUT_FILE}")
        raw_results = load_comparison_results(INPUT_FILE)
        logger.info(f"Loaded {len(raw_results)} raw result rows.")

        # Aggregate
        logger.info("Aggregating by task_type and agent_type...")
        summary = aggregate_by_task_type(raw_results)

        # Write output
        logger.info(f"Writing summary to {OUTPUT_FILE}")
        write_summary_csv(summary, OUTPUT_FILE)

        logger.info("T025 completed successfully.")
        return 0

    except FileNotFoundError as e:
        logger.error(f"Data dependency missing: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error during aggregation: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    exit(main())
