"""
Permutation Test for Model Significance (T025)

Implements a permutation test on fold-level MAE differences to verify that the
Random Forest model provides a statistically significant reduction in MAE 
compared to the null baseline (global mean).

Hypothesis:
  H0: The distribution of MAE differences (Null - RF) is symmetric around 0.
  H1: The RF model significantly reduces MAE (difference > 0).

Method:
  1. Calculate observed mean difference in MAE across LOSO folds.
  2. Permute the labels of the differences (or simply shuffle the assignment of 
     which model produced which error) to simulate the null hypothesis.
  3. Repeat N times to build a null distribution.
  4. Calculate p-value as the proportion of permuted means >= observed mean.
"""
import os
import sys
import json
import pickle
import argparse
import numpy as np
from typing import Dict, Any, List, Optional, Tuple
from scipy import stats

# Project imports
from utils.logging import get_logger, log_info, log_error, log_warning
from utils.error_codes import ErrorCode

logger = get_logger(__name__)

def load_processed_data() -> Tuple[np.ndarray, np.ndarray]:
    """
    Loads the processed descriptor data and targets from data/processed/descriptors.csv.
    Returns X (features) and y (target).
    """
    import csv
    file_path = "data/processed/descriptors.csv"
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Processed data file not found: {file_path}. "
                                "Run T018 (generate_descriptors) first.")
    
    X_list = []
    y_list = []
    feature_cols = None

    with open(file_path, 'r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if feature_cols is None:
                # Identify feature columns (exclude metadata/target)
                feature_cols = [k for k in row.keys() if k not in ['system_id', 'composition', 'temperature', 'phase']]
                # Ensure we have numeric targets
            
            try:
                # Extract features
                features = [float(row[col]) for col in feature_cols]
                X_list.append(features)
                
                # Extract target (assuming 'temperature' is the target for phase boundary prediction in this context)
                # If 'temperature' is not the target, adjust based on actual schema
                target_key = 'temperature'
                if target_key in row:
                    y_list.append(float(row[target_key]))
                else:
                    # Fallback: assume last column is target if schema varies
                    # But strict adherence to schema suggests specific keys
                    raise ValueError(f"Target key '{target_key}' not found in row.")
            except (ValueError, KeyError) as e:
                log_warning(f"Skipping row due to parsing error: {e}")
                continue
    
    if len(X_list) == 0:
        raise ValueError("No valid data rows found in processed data.")
        
    return np.array(X_list), np.array(y_list)

def load_loso_results() -> Dict[str, Any]:
    """
    Loads the LOSO cross-validation results from the report generated by train.py.
    Expected path: state/PROJ-485/loso_report.json or similar.
    """
    # The train.py script should have saved a report. 
    # We assume it saves to state/PROJ-485/loso_results.json based on standard patterns.
    report_path = "state/PROJ-485/loso_results.json"
    
    if not os.path.exists(report_path):
        raise FileNotFoundError(f"LOSO results not found at {report_path}. "
                                "Run T021 (train.py) first.")
    
    with open(report_path, 'r') as f:
        return json.load(f)

def load_null_results() -> Dict[str, Any]:
    """
    Loads the null baseline results from the report generated by null_baseline.py.
    """
    report_path = "state/PROJ-485/null_baseline_results.json"
    
    if not os.path.exists(report_path):
        raise FileNotFoundError(f"Null baseline results not found at {report_path}. "
                                "Run T024 (null_baseline) first.")
    
    with open(report_path, 'r') as f:
        return json.load(f)

def run_permutation_test(
    rf_mae_list: List[float], 
    null_mae_list: List[float], 
    n_iterations: int = 10000, 
    random_seed: int = 42
) -> Dict[str, Any]:
    """
    Performs the permutation test on the fold-level MAE differences.
    
    Args:
        rf_mae_list: List of MAE values for the Random Forest model per fold.
        null_mae_list: List of MAE values for the Null model per fold.
        n_iterations: Number of permutations.
        random_seed: Random seed for reproducibility.
        
    Returns:
        Dictionary containing test statistics and p-value.
    """
    if len(rf_mae_list) != len(null_mae_list):
        raise ValueError("RF and Null MAE lists must have the same length (same folds).")
    
    np.random.seed(random_seed)
    
    # Calculate observed difference: Null MAE - RF MAE (Positive means RF is better)
    observed_diffs = np.array(null_mae_list) - np.array(rf_mae_list)
    observed_mean_diff = np.mean(observed_diffs)
    
    log_info(f"Observed Mean MAE Difference (Null - RF): {observed_mean_diff:.6f}")
    
    # Permutation logic:
    # Under H0, the label "which model produced this error" is exchangeable.
    # We have pairs of (null_mae, rf_mae). The difference is d_i = n_i - r_i.
    # If H0 is true, then d_i and -d_i are equally likely.
    # We can permute by randomly flipping the sign of each difference.
    
    n_folds = len(observed_diffs)
    permuted_means = np.zeros(n_iterations)
    
    log_info(f"Running {n_iterations} permutation iterations...")
    
    for i in range(n_iterations):
        # Randomly flip signs
        signs = np.random.choice([-1, 1], size=n_folds)
        permuted_diffs = observed_diffs * signs
        permuted_means[i] = np.mean(permuted_diffs)
    
    # Calculate p-value (one-tailed: is RF significantly better?)
    # p = P(permuted_mean >= observed_mean)
    p_value = np.sum(permuted_means >= observed_mean_diff) / n_iterations
    
    # Calculate effect size (Cohen's d equivalent for paired differences)
    std_diff = np.std(observed_diffs, ddof=1)
    if std_diff > 0:
        effect_size = observed_mean_diff / std_diff
    else:
        effect_size = 0.0
        
    return {
        "observed_mean_difference": float(observed_mean_diff),
        "p_value": float(p_value),
        "effect_size": float(effect_size),
        "n_folds": n_folds,
        "n_iterations": n_iterations,
        "significant": p_value < 0.05
    }

def main():
    """
    Main entry point for the permutation test.
    """
    parser = argparse.ArgumentParser(description="Run permutation test for model significance.")
    parser.add_argument("--iterations", type=int, default=10000, help="Number of permutation iterations")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()
    
    log_info("Starting Permutation Test (T025)...")
    
    try:
        # 1. Load Results
        # We expect train.py and null_baseline.py to have generated these reports.
        # If they haven't, we raise an error to fail loudly (as per constraints).
        loso_report = load_loso_results()
        null_report = load_null_results()
        
        # Extract MAE lists
        # Assuming the reports have a structure like: {"folds": [{"mae": ...}, ...]}
        rf_mae_list = [fold["mae"] for fold in loso_report.get("folds", [])]
        null_mae_list = [fold["mae"] for fold in null_report.get("folds", [])]
        
        if not rf_mae_list or not null_mae_list:
            raise ValueError("Could not extract fold-level MAE lists from reports.")
        
        log_info(f"Loaded {len(rf_mae_list)} folds for comparison.")
        
        # 2. Run Test
        results = run_permutation_test(
            rf_mae_list, 
            null_mae_list, 
            n_iterations=args.iterations, 
            random_seed=args.seed
        )
        
        # 3. Save Results
        output_path = "state/PROJ-485/permutation_test_results.json"
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)
        
        log_info(f"Permutation test results saved to {output_path}")
        log_info(f"P-value: {results['p_value']:.6f}")
        log_info(f"Significant (p < 0.05): {results['significant']}")
        
        if results['significant']:
            log_info("Conclusion: The Random Forest model shows a statistically significant "
                     "reduction in MAE compared to the null baseline.")
        else:
            log_warning("Conclusion: The reduction in MAE is NOT statistically significant "
                        "(p >= 0.05). The model may not be better than the null baseline.")
        
        return 0
        
    except Exception as e:
        log_error(f"Permutation test failed: {str(e)}")
        # Fail loudly as per constraint: do not return success if it fails.
        return 1

if __name__ == "__main__":
    sys.exit(main())
