"""
Synthetic Data Generation Module for Visual Motion Agency Study.

This module generates synthetic human-avatar interaction data strictly for
pipeline stress-testing when real data is unavailable. It enforces strict
independence between the 'user_response_trigger' and 'agency_score' to
prevent tautological coupling (FR-012).

Dependencies:
    - pandas, numpy (from requirements.txt)
"""
import os
import json
import sys
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime

# Ensure project root is in path if running as script
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utils.logging_config import get_logger

logger = get_logger(__name__)

# Constants
TARGET_N = 150  # Target sample size to ensure >= 100 after cleaning
CORRELATION_THRESHOLD = 0.05  # Max allowed correlation between trigger and agency


def check_download_status(status_path: Path) -> str:
    """
    Reads the download status file generated by T012.

    Args:
        status_path: Path to data/raw/download_status.json

    Returns:
        str: The status string ("unavailable", "success", "invalid")

    Raises:
        SystemExit: If status is "invalid" (FR-009 compliance)
        FileNotFoundError: If the status file does not exist
    """
    if not status_path.exists():
        logger.error(f"Status file not found: {status_path}. Has T012 run?")
        raise FileNotFoundError(f"Status file missing: {status_path}")

    try:
        with open(status_path, 'r') as f:
            data = json.load(f)
        status = data.get("status", "").lower()
    except json.JSONDecodeError:
        logger.error(f"Invalid JSON in status file: {status_path}")
        raise ValueError(f"Invalid JSON in status file: {status_path}")

    if status == "invalid":
        error_msg = "Dataset excluded: Unvalidated instrument (FR-009)"
        logger.critical(error_msg)
        raise SystemExit(1)

    return status


def generate_synthetic_data(n_samples: int = TARGET_N, seed: int = 42) -> pd.DataFrame:
    """
    Generates synthetic human-avatar interaction data with known ground-truth
    relationships between motion features and perceived agency.

    CRITICAL: Ensures 'user_response_trigger' is statistically independent
    of 'agency_score' to satisfy FR-012.

    Args:
        n_samples: Number of samples to generate.
        seed: Random seed for reproducibility.

    Returns:
        pd.DataFrame: The generated dataset.
    """
    rng = np.random.default_rng(seed)
    logger.info(f"Generating {n_samples} synthetic samples with seed {seed}...")

    # 1. Generate Motion Features (Independent Predictors)
    # Latency: Normal distribution (ms)
    latency = rng.normal(loc=150, scale=40, size=n_samples)
    latency = np.clip(latency, 50, 300)  # Realistic bounds

    # Smoothness (Jerk): Log-normal distribution (normalized 0-1, lower is smoother)
    smoothness = rng.lognormal(mean=-0.5, sigma=0.6, size=n_samples)
    smoothness = np.clip(smoothness, 0.05, 0.95)

    # Lead Time: Normal distribution (ms, positive means avatar leads)
    lead_time = rng.normal(loc=20, scale=30, size=n_samples)
    lead_time = np.clip(lead_time, -50, 100)

    # 2. Generate Agency Score (Dependent Variable)
    # Constructed based on motion features + noise (Ground Truth Model)
    # FR-011: Known ground-truth motion-agency relationships
    # Latency: Negative correlation (higher latency -> lower agency)
    # Smoothness: Negative correlation (higher jerk -> lower agency)
    # Lead Time: Positive correlation (avatar leading slightly -> higher agency)

    base_agency = 0.5
    # Normalize features for coefficient scaling
    norm_latency = (latency - 150) / 40
    norm_smoothness = (smoothness - 0.3) / 0.3
    norm_lead_time = (lead_time - 20) / 30

    # Linear combination with known coefficients
    agency_raw = (
        base_agency
        - 0.35 * norm_latency   # Latency hurts agency
        - 0.40 * norm_smoothness # Jerk hurts agency
        + 0.25 * norm_lead_time  # Lead time helps agency
        + rng.normal(0, 0.15, n_samples) # Noise
    )

    # Scale to 0-1 range
    agency_score = (agency_raw - agency_raw.min()) / (agency_raw.max() - agency_raw.min())
    agency_score = np.clip(agency_score, 0.0, 1.0)

    # 3. Generate User Response Trigger (INDEPENDENT)
    # FR-012: Must be statistically independent of agency_score.
    # We generate this from a completely different random process unrelated to motion.
    # e.g., Simulated random user click timing or external stimulus.
    user_response_trigger = rng.uniform(0.0, 1.0, size=n_samples)

    # 4. Verification: Check Correlation
    # We must ensure correlation(trigger, agency) < 0.05
    corr = np.corrcoef(user_response_trigger, agency_score)[0, 1]
    logger.info(f"Initial correlation between trigger and agency: {corr:.4f}")

    if abs(corr) >= CORRELATION_THRESHOLD:
        logger.warning(f"Correlation {corr:.4f} exceeds threshold. Regenerating trigger...")
        # If by chance they correlate, regenerate trigger until independent
        # (In practice with uniform vs normal mix, this is rare, but we enforce it)
        attempts = 0
        while abs(corr) >= CORRELATION_THRESHOLD and attempts < 100:
            user_response_trigger = rng.uniform(0.0, 1.0, size=n_samples)
            corr = np.corrcoef(user_response_trigger, agency_score)[0, 1]
            attempts += 1

        if abs(corr) >= CORRELATION_THRESHOLD:
            raise RuntimeError(
                f"Failed to generate independent trigger after {attempts} attempts. "
                f"Final correlation: {corr}"
            )

    logger.info(f"Verified independence: Correlation = {corr:.4f} (< {CORRELATION_THRESHOLD})")

    # 5. Assemble DataFrame
    # Add a synthetic participant ID
    participant_ids = [f"P{str(i).zfill(4)}" for i in range(n_samples)]

    df = pd.DataFrame({
        "participant_id": participant_ids,
        "latency": np.round(latency, 2),
        "smoothness": np.round(smoothness, 4),
        "lead_time": np.round(lead_time, 2),
        "agency_score": np.round(agency_score, 4),
        "user_response_trigger": np.round(user_response_trigger, 4)
    })

    return df


def main():
    """
    Main entry point for T013.

    Logic:
    1. Check data/raw/download_status.json.
    2. If "invalid", exit(1).
    3. If "unavailable", generate synthetic data and write to data/raw/synthetic_data.csv.
    4. If "success", do nothing (real data exists).
    """
    status_file = PROJECT_ROOT / "data" / "raw" / "download_status.json"
    output_file = PROJECT_ROOT / "data" / "raw" / "synthetic_data.csv"

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        status = check_download_status(status_file)
    except SystemExit:
        # Re-raise SystemExit to propagate the error code 1
        raise
    except FileNotFoundError:
        # If status file is missing, we assume unavailable (fallback for T012 failure)
        # But strictly, T012 should have created it. We log and proceed to generate.
        logger.warning("Status file missing. Assuming 'unavailable' and generating synthetic data.")
        status = "unavailable"

    if status == "success":
        logger.info("Real data available. Skipping synthetic generation.")
        return

    if status == "unavailable":
        logger.info("Real data unavailable. Generating synthetic dataset...")
        df = generate_synthetic_data()

        # Write to disk
        df.to_csv(output_file, index=False)
        logger.info(f"Successfully wrote synthetic data to: {output_file}")
        logger.info(f"Dataset shape: {df.shape}")
        logger.info(f"Columns: {list(df.columns)}")

        # Quick sanity check on output
        if len(df) < 100:
            logger.error(f"Generated dataset has {len(df)} rows, expected >= 100.")
            sys.exit(1)

        return

    logger.error(f"Unknown status: {status}")
    sys.exit(1)


if __name__ == "__main__":
    main()