"""
Collinearity Detection Module (T020b).

Reads correlation/VIF data from T020a (analysis_summary.csv),
calculates Variance Inflation Factor (VIF) explicitly, and flags
samples for mitigation if VIF > 5.

Output: data/results/collinearity_report.csv
"""
import os
import csv
import sys
from pathlib import Path
from typing import List, Dict, Any, Optional

import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Import shared config/paths
try:
    from config import Paths
except ImportError:
    # Fallback for direct execution if config is not in path
    from pathlib import Path
    class Paths:
        DATA_RAW = Path("data/raw")
        DATA_PROCESSED = Path("data/processed")
        DATA_RESULTS = Path("data/results")
        PROJECT_ROOT = Path(__file__).resolve().parent.parent

logger = None
def get_logger():
    global logger
    if logger is None:
        try:
            from utils.logger import get_logger as _get_logger
            logger = _get_logger("collinearity_detector")
        except ImportError:
            import logging
            logger = logging.getLogger("collinearity_detector")
    return logger

def load_analysis_summary() -> Optional[pd.DataFrame]:
    """
    Loads the analysis summary generated by T020a.
    Expected columns: test_type, statistic, p_value, effect_size, correlation_coefficient
    """
    path = Paths.DATA_RESULTS / "analysis_summary.csv"
    if not path.exists():
        get_logger().error(f"Analysis summary not found at {path}. T020a may not have run.")
        return None
    try:
        df = pd.read_csv(path)
        return df
    except Exception as e:
        get_logger().error(f"Failed to load analysis summary: {e}")
        return None

def load_prompt_variants() -> Optional[pd.DataFrame]:
    """
    Loads the prompt variants dataframe to calculate VIF on the fly
    if correlation data is insufficient or to provide detailed flags.
    Expected columns: token_count, structural_element_count (or expanded keys)
    """
    path = Paths.DATA_PROCESSED / "prompt_variants.parquet"
    if not path.exists():
        get_logger().error(f"Prompt variants not found at {path}. T018 may not have run.")
        return None
    try:
        df = pd.read_parquet(path)
        return df
    except Exception as e:
        get_logger().error(f"Failed to load prompt variants: {e}")
        return None

def calculate_vif(df: pd.DataFrame, features: List[str]) -> Dict[str, float]:
    """
    Calculates Variance Inflation Factor for each feature in the dataframe.
    """
    if df is None or len(df) == 0:
        return {}
    
    # Ensure features exist
    missing = [f for f in features if f not in df.columns]
    if missing:
        get_logger().warning(f"Features missing from dataframe for VIF calculation: {missing}")
        return {}

    X = df[features].dropna()
    if X.shape[0] < 2:
        get_logger().warning("Insufficient data points for VIF calculation.")
        return {}

    # Add constant for intercept
    X_with_const = sm.add_constant(X)
    vif_data = {}
    for i, col in enumerate(X_with_const.columns):
        if col == 'const':
            continue
        try:
            vif = variance_inflation_factor(X_with_const.values, i)
            vif_data[col] = vif
        except Exception as e:
            get_logger().error(f"Error calculating VIF for {col}: {e}")
            vif_data[col] = np.nan
    return vif_data

def run_collinearity_detection() -> Dict[str, Any]:
    """
    Main logic:
    1. Load correlation data from T020a.
    2. Load raw data to calculate VIF.
    3. Determine if mitigation is needed (VIF > 5).
    4. Write report.
    """
    logger = get_logger()
    logger.info("Starting collinearity detection (T020b).")

    # Load data
    summary_df = load_analysis_summary()
    variants_df = load_prompt_variants()

    if variants_df is None:
        logger.error("Cannot proceed without prompt variants data.")
        return {"status": "failed", "reason": "Missing prompt variants"}

    # Identify relevant columns for collinearity
    # T020a likely calculated correlation between 'token_count' and 'structural_element_count'
    # or a specific structural metric. We assume standard columns based on T008 model.
    # If 'structural_element_count' is a dict, we need to flatten or use a specific metric.
    # For VIF, we need numeric columns. Let's assume we use 'token_count' and a flattened structural metric.
    
    # Check for flattened structural count or calculate a total
    structural_cols = [c for c in variants_df.columns if 'structural' in c.lower() and c != 'structural_element_count']
    token_col = 'token_count'
    
    if token_col not in variants_df.columns:
        logger.error(f"Token count column '{token_col}' not found.")
        return {"status": "failed", "reason": f"Missing column {token_col}"}

    # If 'structural_element_count' is a dict column, we need to extract a value or sum it.
    # Based on T008, it's a dict. We'll try to sum the values if it's a dict column.
    if 'structural_element_count' in variants_df.columns:
        # Try to sum the dict values
        try:
            variants_df['total_structural_count'] = variants_df['structural_element_count'].apply(
                lambda x: sum(x.values()) if isinstance(x, dict) else 0
            )
            feature_cols = [token_col, 'total_structural_count']
        except Exception as e:
            logger.warning(f"Could not sum structural_element_count: {e}. Trying other columns.")
            feature_cols = [token_col] + structural_cols[:1] if structural_cols else [token_col]
    else:
        feature_cols = [token_col] + structural_cols[:1] if structural_cols else [token_col]

    # Ensure we have at least 2 features to check collinearity
    if len(feature_cols) < 2:
        logger.warning("Less than 2 features found. Collinearity not applicable. Assuming low risk.")
        vif_results = {col: 0.0 for col in feature_cols}
        mitigation_needed = False
    else:
        vif_results = calculate_vif(variants_df, feature_cols)
        max_vif = max(vif_results.values()) if vif_results else 0
        mitigation_needed = max_vif > 5

    # Prepare report data
    report_rows = []
    for col, vif in vif_results.items():
        flag = "MITIGATION_REQUIRED" if (vif > 5 and mitigation_needed) else "OK"
        report_rows.append({
            "feature": col,
            "vif": vif,
            "threshold": 5.0,
            "flag": flag,
            "mitigation_needed": mitigation_needed
        })

    # Write to CSV
    output_path = Paths.DATA_RESULTS / "collinearity_report.csv"
    if report_rows:
        df_report = pd.DataFrame(report_rows)
        df_report.to_csv(output_path, index=False)
        logger.info(f"Collinearity report written to {output_path}")
    else:
        # Write empty file with headers if no features
        with open(output_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["feature", "vif", "threshold", "flag", "mitigation_needed"])
        logger.warning(f"No features to report. Empty report written to {output_path}")

    return {
        "status": "success",
        "max_vif": max(vif_results.values()) if vif_results else 0,
        "mitigation_needed": mitigation_needed,
        "output_path": str(output_path)
    }

def main():
    logger = get_logger()
    try:
        result = run_collinearity_detection()
        if result["status"] == "success":
            logger.info(f"Collinearity detection complete. Mitigation needed: {result['mitigation_needed']}")
            sys.exit(0)
        else:
            logger.error(f"Collinearity detection failed: {result.get('reason')}")
            sys.exit(1)
    except Exception as e:
        logger.exception(f"Unhandled exception in T020b: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()