import os
import sys
import argparse
import json
import numpy as np
import pandas as pd
from scipy import stats
from pathlib import Path

# Add project root to path if running as script
project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from config import get_path, ensure_dirs

def load_features():
    """
    Load the processed features dataset containing relative band powers and median RT.
    Expects 'data/processed/features.csv' as generated by T015/T016.
    """
    input_path = get_path("data/processed/features.csv")
    
    if not os.path.exists(input_path):
        raise FileNotFoundError(
            f"Required input file not found: {input_path}. "
            "Please ensure T015 and T016 have completed successfully."
        )
    
    df = pd.read_csv(input_path)
    
    # Verify required columns exist
    required_cols = ['participant_id', 'median_rt']
    band_cols = ['delta_rel', 'theta_rel', 'alpha_rel', 'low_beta_rel', 'high_beta_rel', 'gamma_rel']
    
    missing = [c for c in required_cols + band_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in features file: {missing}")
    
    return df

def run_correlations(df):
    """
    Compute Pearson correlation coefficients and p-values between each relative band power
    and the median reaction time (RT).
    
    Returns a DataFrame with columns:
    - band: Band name
    - r: Pearson correlation coefficient
    - p_value: Raw p-value
    - n: Sample size
    """
    results = []
    
    # Define the relative power columns corresponding to the 6 bands
    band_cols = ['delta_rel', 'theta_rel', 'alpha_rel', 'low_beta_rel', 'high_beta_rel', 'gamma_rel']
    band_names = ['delta', 'theta', 'alpha', 'low_beta', 'high_beta', 'gamma']
    
    # Drop rows with any NaN in the relevant columns to ensure valid correlation
    clean_df = df.dropna(subset=['median_rt'] + band_cols)
    n = len(clean_df)
    
    if n < 3:
        raise ValueError(f"Insufficient data points for correlation analysis (N={n}).")
    
    for col, name in zip(band_cols, band_names):
        x = clean_df[col].values
        y = clean_df['median_rt'].values
        
        r, p_value = stats.pearsonr(x, y)
        
        results.append({
            'band': name,
            'r': r,
            'p_value': p_value,
            'n': n
        })
    
    return pd.DataFrame(results)

def main():
    """
    Main entry point for T020: Pearson correlation tests between relative band powers and median RT.
    
    Output:
    - data/interim/correlations_raw.csv: Raw correlation results (before Bonferroni correction).
      This will be used by T021 for correction.
    """
    parser = argparse.ArgumentParser(description="T020: Compute Pearson correlations between EEG band powers and RT.")
    parser.add_argument("--output", type=str, default=None, help="Path to output CSV (default: data/interim/correlations_raw.csv)")
    args = parser.parse_args()
    
    # Ensure output directory exists
    ensure_dirs()
    
    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = get_path("data/interim/correlations_raw.csv")
    
    print(f"Loading features from {get_path('data/processed/features.csv')}...")
    df = load_features()
    
    print(f"Running Pearson correlations on {len(df)} participants...")
    corr_results = run_correlations(df)
    
    print(f"Saving results to {output_path}...")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    corr_results.to_csv(output_path, index=False)
    
    print("Correlation analysis complete.")
    print(f"Results summary:\n{corr_results.to_string(index=False)}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
