"""
Permutation Test for Model Significance (FR-007)

This script implements a permutation test to assess the significance of the full model's R².
It shuffles the target labels (median RT) N times, re-runs 5-fold CV for each shuffle,
and generates an R² distribution to compare against the observed R².

Input:
    - data/interim/split_indices.json (from T017)
    - data/processed/model_results.json (from T019)
    - data/processed/features.csv (from T015/T016)

Output:
    - Appends permutation results to data/processed/model_results.json
"""
import os
import sys
import json
import argparse
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
from config import get_path, ensure_dirs, get_seed, set_global_seed
from utils.stats_helpers import permutation_test

# Ensure project root is in path
sys.path.insert(0, str(Path(__file__).parent.parent))

def load_features():
    """Load the processed features dataset."""
    path = get_path("processed/features.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Input file not found: {path}. Please run T016 first.")
    return pd.read_csv(path)

def load_split_indices():
    """Load the CV split indices generated by T017."""
    path = get_path("interim/split_indices.json")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Split indices not found: {path}. Please run T017 first.")
    with open(path, 'r') as f:
        return json.load(f)

def prepare_test_data(df, feature_cols, target_col):
    """Prepare X and y arrays from the dataframe."""
    X = df[feature_cols].values
    y = df[target_col].values
    return X, y

def run_permutation_test(X, y, splits, n_permutations=10000, n_folds=5, seed=42):
    """
    Run the permutation test.

    For each permutation:
        1. Shuffle y
        2. Run CV using the pre-defined splits
        3. Calculate R² for each fold
        4. Store the mean R² for this permutation

    Returns:
        observed_r2: The R² from the original (non-shuffled) data (calculated here for consistency)
        permuted_r2s: List of mean R² scores from permuted data
    """
    set_global_seed(seed)
    n = len(y)
    permuted_r2s = []
    
    # Calculate observed R² using the provided splits (5-fold CV)
    # We use the splits to ensure we are comparing apples to apples
    observed_scores = []
    for fold_idx in range(n_folds):
        train_idx = []
        test_idx = []
        for f in range(n_folds):
            if f == fold_idx:
                test_idx.extend(splits[str(f)])
            else:
                train_idx.extend(splits[str(f)])
        
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        
        model = LinearRegression()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        observed_scores.append(r2_score(y_test, y_pred))
    
    observed_r2 = np.mean(observed_scores)

    # Run permutations
    print(f"Starting permutation test with {n_permutations} shuffles...")
    for i in range(n_permutations):
        # Shuffle y
        y_perm = y.copy()
        np.random.shuffle(y_perm)
        
        fold_scores = []
        for fold_idx in range(n_folds):
            train_idx = []
            test_idx = []
            for f in range(n_folds):
                if f == fold_idx:
                    test_idx.extend(splits[str(f)])
                else:
                    train_idx.extend(splits[str(f)])
            
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y_perm[train_idx], y_perm[test_idx]
            
            model = LinearRegression()
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            fold_scores.append(r2_score(y_test, y_pred))
        
        permuted_r2s.append(np.mean(fold_scores))
        
        if (i + 1) % 1000 == 0:
            print(f"  Completed {i + 1}/{n_permutations} permutations...")

    return observed_r2, np.array(permuted_r2s)

def save_results(observed_r2, permuted_r2s, n_permutations, output_path):
    """
    Calculate p-value and append results to the existing model_results.json.
    
    P-value = (count(permuted_r2 >= observed_r2) + 1) / (n_permutations + 1)
    """
    # Calculate p-value
    # Count how many permuted R² values are greater than or equal to observed
    count_greater_equal = np.sum(permuted_r2s >= observed_r2)
    p_value = (count_greater_equal + 1) / (n_permutations + 1)
    
    # Load existing results
    if os.path.exists(output_path):
        with open(output_path, 'r') as f:
            results = json.load(f)
    else:
        results = {}
    
    # Prepare permutation results
    permutation_results = {
        "permutation_test": {
            "n_permutations": n_permutations,
            "observed_r2": float(observed_r2),
            "mean_permuted_r2": float(np.mean(permuted_r2s)),
            "std_permuted_r2": float(np.std(permuted_r2s)),
            "p_value": float(p_value),
            "significant_at_0.05": p_value < 0.05,
            "description": "Permutation test to assess significance of model R² by shuffling target labels."
        }
    }
    
    # Merge into results
    results.update(permutation_results)
    
    # Ensure directory exists
    ensure_dirs(Path(output_path).parent)
    
    # Save updated results
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"Results saved to {output_path}")
    print(f"Observed R²: {observed_r2:.4f}")
    print(f"Mean Permuted R²: {np.mean(permuted_r2s):.4f}")
    print(f"P-value: {p_value:.4f}")
    print(f"Significant (p < 0.05): {p_value < 0.05}")

def main():
    parser = argparse.ArgumentParser(description="Run permutation test for model significance.")
    parser.add_argument("--n-permutations", type=int, default=10000, help="Number of permutations (default: 10000)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    try:
        # Load data
        df = load_features()
        splits = load_split_indices()
        
        # Identify feature columns (exclude participant_id and target)
        feature_cols = [c for c in df.columns if c not in ['participant_id', 'median_rt']]
        target_col = 'median_rt'
        
        # Prepare data
        X, y = prepare_test_data(df, feature_cols, target_col)
        
        # Run permutation test
        observed_r2, permuted_r2s = run_permutation_test(
            X, y, splits, 
            n_permutations=args.n_permutations, 
            n_folds=5, 
            seed=args.seed
        )
        
        # Save results
        output_path = get_path("processed/model_results.json")
        save_results(observed_r2, permuted_r2s, args.n_permutations, output_path)
        
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error during permutation test: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()