"""
Task T023: Perform post-hoc power analysis to estimate required sample size.

Reads model results from T019 (model_results.json), extracts the observed R-squared,
and calculates the required sample size (N) to achieve 80% power for a target R-squared
of 0.10 (or the observed R-squared if lower, depending on interpretation of FR-011).

FR-011: Perform post-hoc power analysis to estimate the required sample size (N) for R²=0.10 
with power ≥ 0.80 and report in results.

Uses the stats_helpers utility function calculate_sample_size_for_r2.
"""
import os
import sys
import json
import argparse
from pathlib import Path
from typing import Dict, Any, Optional

# Add parent directory to path for imports if running as script
sys.path.insert(0, str(Path(__file__).parent))

from config import get_path, get_seed
from utils.stats_helpers import calculate_sample_size_for_r2


def load_model_results(results_path: Path) -> Dict[str, Any]:
    """Load the model results JSON file generated by T019."""
    if not results_path.exists():
        raise FileNotFoundError(f"Model results file not found at {results_path}")
    
    with open(results_path, 'r') as f:
        return json.load(f)


def perform_power_analysis(
    observed_r2: float,
    target_r2: float = 0.10,
    power: float = 0.80,
    alpha: float = 0.05,
    n_predictors: int = 6
) -> Dict[str, Any]:
    """
    Perform post-hoc power analysis.
    
    Calculates the required sample size to detect an effect size corresponding
    to the target R-squared (0.10) with the specified power.
    
    Args:
        observed_r2: The observed R-squared from the model.
        target_r2: The target R-squared for power calculation (default 0.10 per FR-011).
        power: Desired statistical power (default 0.80).
        alpha: Significance level (default 0.05).
        n_predictors: Number of predictors in the model (default 6 bands).
        
    Returns:
        Dictionary containing power analysis results.
    """
    # Calculate required sample size for the target R-squared
    required_n = calculate_sample_size_for_r2(
        r2=target_r2,
        power=power,
        alpha=alpha,
        n_predictors=n_predictors
    )
    
    # Calculate achieved power with current sample size for the target effect
    current_n = 0  # Will be populated from data if available
    achieved_power = None
    
    if current_n > 0:
        achieved_power = calculate_sample_size_for_r2(
            r2=target_r2,
            n=current_n,
            alpha=alpha,
            n_predictors=n_predictors,
            return_power=True
        )
    
    return {
        "target_r2": target_r2,
        "observed_r2": observed_r2,
        "desired_power": power,
        "alpha": alpha,
        "n_predictors": n_predictors,
        "required_sample_size": required_n,
        "interpretation": (
            f"To detect an R² of {target_r2} with {power*100:.0%} power at α={alpha}, "
            f"a sample size of N={required_n} is required."
        )
    }


def save_results(results: Dict[str, Any], output_path: Path) -> None:
    """Save power analysis results to JSON file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)


def main():
    """Main entry point for the post-hoc power analysis."""
    parser = argparse.ArgumentParser(
        description="Perform post-hoc power analysis for EEG-RT prediction model."
    )
    parser.add_argument(
        "--results-file",
        type=str,
        default=None,
        help="Path to model_results.json (default: from config)"
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default=None,
        help="Path for output power_analysis.json (default: from config)"
    )
    args = parser.parse_args()
    
    # Set seed for reproducibility
    seed = get_seed()
    import random
    random.seed(seed)
    import numpy as np
    np.random.seed(seed)
    
    # Determine file paths
    results_path = Path(args.results_file) if args.results_file else get_path("model_results")
    output_path = Path(args.output_file) if args.output_file else get_path("power_analysis")
    
    print(f"Loading model results from: {results_path}")
    model_results = load_model_results(results_path)
    
    # Extract observed R-squared (try multiple possible keys)
    observed_r2 = None
    if "adjusted_r2" in model_results:
        observed_r2 = model_results["adjusted_r2"]
    elif "r2" in model_results:
        observed_r2 = model_results["r2"]
    elif "metrics" in model_results and "adjusted_r2" in model_results["metrics"]:
        observed_r2 = model_results["metrics"]["adjusted_r2"]
    elif "metrics" in model_results and "r2" in model_results["metrics"]:
        observed_r2 = model_results["metrics"]["r2"]
    
    if observed_r2 is None:
        raise ValueError("Could not find R-squared value in model results.")
    
    print(f"Observed R²: {observed_r2:.4f}")
    
    # Perform power analysis
    # FR-011 specifies target R² = 0.10
    power_results = perform_power_analysis(
        observed_r2=observed_r2,
        target_r2=0.10,  # Per FR-011
        power=0.80,
        alpha=0.05,
        n_predictors=6  # 6 frequency bands
    )
    
    # Add metadata
    power_results["analysis_type"] = "post_hoc_power_analysis"
    power_results["task_id"] = "T023"
    power_results["fr_id"] = "FR-011"
    
    print(f"Required sample size for R²=0.10, power=0.80: N={power_results['required_sample_size']}")
    print(f"Interpretation: {power_results['interpretation']}")
    
    # Save results
    save_results(power_results, output_path)
    print(f"Power analysis results saved to: {output_path}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
