"""
Duplicate Audit Script (T028d)

Implements post-hoc duplicate detection by scanning `data/raw/submissions.csv`
for repeated `hashed_ip` values and logging them to `data/raw/duplicate_audit.csv`.

This script must be run after data collection to audit the dataset.
It relies on the existence of `data/raw/submissions.csv` generated by the survey app.
"""

import os
import sys
import csv
import json
from pathlib import Path
from datetime import datetime

# Add project root to path for imports if running as script
def get_project_root():
    """Return the root path of the project."""
    current = Path(__file__).resolve()
    while not current.joinpath("project_root_marker").exists():
        current = current.parent
        if current == current.parent:
            # Fallback if marker not found: assume standard structure
            return Path(__file__).resolve().parent.parent.parent
    return current

PROJECT_ROOT = get_project_root()
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
SUBMISSIONS_PATH = RAW_DATA_DIR / "submissions.csv"
AUDIT_PATH = RAW_DATA_DIR / "duplicate_audit.csv"

def load_submissions_data():
    """
    Load the submissions CSV file.
    Raises FileNotFoundError if the file does not exist.
    """
    if not SUBMISSIONS_PATH.exists():
        raise FileNotFoundError(
            f"Input file not found: {SUBMISSIONS_PATH}. "
            "Please ensure data collection has run and generated submissions.csv."
        )

    rows = []
    with open(SUBMISSIONS_PATH, mode='r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows, reader.fieldnames

def detect_duplicates(rows):
    """
    Identify rows with duplicate hashed_ip values.
    Returns a list of rows that are duplicates (excluding the first occurrence).
    """
    ip_counts = {}
    duplicate_rows = []

    for row in rows:
        ip = row.get('hashed_ip', '')
        if not ip:
            continue

        if ip in ip_counts:
            ip_counts[ip] += 1
            # Mark this row as a duplicate
            row['duplicate_flag'] = 'TRUE'
            row['duplicate_reason'] = f"IP seen {ip_counts[ip]} times"
            duplicate_rows.append(row)
        else:
            ip_counts[ip] = 1
            # Explicitly mark the first occurrence as not duplicate for clarity
            row['duplicate_flag'] = 'FALSE'

    return duplicate_rows, ip_counts

def write_audit_log(duplicate_rows, ip_counts, fieldnames):
    """
    Write the duplicate audit log to data/raw/duplicate_audit.csv.
    """
    RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)

    audit_data = {
        "audit_timestamp": datetime.now().isoformat(),
        "total_submissions": sum(ip_counts.values()),
        "unique_ips": len(ip_counts),
        "duplicate_count": len(duplicate_rows),
        "audit_file": str(AUDIT_PATH),
        "details": duplicate_rows
    }

    # Write the CSV file with duplicates
    if duplicate_rows:
        with open(AUDIT_PATH, mode='w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for row in duplicate_rows:
                writer.writerow(row)
    else:
        # Write an empty file with headers if no duplicates found
        with open(AUDIT_PATH, mode='w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()

    # Also write a summary JSON for programmatic access
    summary_path = RAW_DATA_DIR / "duplicate_audit_summary.json"
    with open(summary_path, mode='w', encoding='utf-8') as f:
        json.dump(audit_data, f, indent=2)

    return audit_data

def main():
    """Main entry point for the duplicate audit script."""
    print(f"Scanning for duplicates in {SUBMISSIONS_PATH}...")

    try:
        rows, fieldnames = load_submissions_data()
        print(f"Loaded {len(rows)} submissions.")

        if not rows:
            print("No submissions found. Audit complete.")
            return

        duplicate_rows, ip_counts = detect_duplicates(rows)

        print(f"Found {len(duplicate_rows)} duplicate entries.")
        print(f"Unique IPs: {len(ip_counts)}")

        audit_result = write_audit_log(duplicate_rows, ip_counts, fieldnames)

        print(f"Audit log written to: {AUDIT_PATH}")
        print(f"Summary written to: {RAW_DATA_DIR / 'duplicate_audit_summary.json'}")

        if duplicate_rows:
            print("WARNING: Duplicate IPs detected. Please review the audit log.")
        else:
            print("No duplicates detected.")

    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
