"""
Module to generate the sensitivity thresholds comparison table.

This module loads the results from the sensitivity analysis (T025),
formats the data, and writes a CSV file `data/processed/sensitivity_thresholds.csv`
with columns: `threshold_hop`, `p_value`, `effect_size`, `is_significant`.
"""

import csv
import json
import logging
import sys
from pathlib import Path
from typing import List, Dict, Any

from utils.config import get_project_root, get_path, ensure_dir

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)


def load_sensitivity_results() -> List[Dict[str, Any]]:
    """
    Load the sensitivity analysis results from the JSON file generated by T025.

    Returns:
        List of dictionaries containing threshold analysis results.

    Raises:
        FileNotFoundError: If the sensitivity results file does not exist.
        json.JSONDecodeError: If the file is not valid JSON.
    """
    project_root = get_project_root()
    input_path = get_path(project_root, "data/processed/sensitivity_results.json")

    logger.info(f"Loading sensitivity results from: {input_path}")

    if not input_path.exists():
        raise FileNotFoundError(f"Sensitivity results file not found: {input_path}")

    with open(input_path, 'r') as f:
        data = json.load(f)

    # The JSON structure is expected to be a list of results or a dict with a 'results' key
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and 'results' in data:
        return data['results']
    else:
        raise ValueError(f"Unexpected JSON structure in {input_path}: {data}")


def format_p_value(p_value: float) -> str:
    """Format p-value to 4 decimal places."""
    return f"{p_value:.4f}"


def format_effect_size(effect_size: float) -> str:
    """Format effect size to 4 decimal places."""
    return f"{effect_size:.4f}"


def format_significance(is_significant: bool) -> str:
    """Format significance as 'Yes' or 'No'."""
    return "Yes" if is_significant else "No"


def generate_table_csv(results: List[Dict[str, Any]], output_path: Path) -> None:
    """
    Generate the CSV file with sensitivity threshold comparison.

    Args:
        results: List of result dictionaries from sensitivity analysis.
        output_path: Path to the output CSV file.
    """
    logger.info(f"Generating CSV table at: {output_path}")

    # Define the expected columns
    fieldnames = ['threshold_hop', 'p_value', 'effect_size', 'is_significant']

    with open(output_path, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        for result in results:
            row = {
                'threshold_hop': result.get('threshold_hop', ''),
                'p_value': format_p_value(result.get('p_value', 0.0)),
                'effect_size': format_effect_size(result.get('effect_size', 0.0)),
                'is_significant': format_significance(result.get('is_significant', False))
            }
            writer.writerow(row)

    logger.info(f"Successfully wrote {len(results)} rows to {output_path}")


def main() -> None:
    """Main entry point for generating the sensitivity table."""
    try:
        project_root = get_project_root()
        output_path = get_path(project_root, "data/processed/sensitivity_thresholds.csv")

        # Ensure the output directory exists
        ensure_dir(output_path.parent)

        # Load results
        results = load_sensitivity_results()

        if not results:
            logger.warning("No sensitivity results found. Generating empty CSV.")

        # Generate CSV
        generate_table_csv(results, output_path)

        logger.info("Sensitivity threshold table generation completed successfully.")

    except Exception as e:
        logger.error(f"Error generating sensitivity table: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
