"""
T022c: Generate Binned Summary & Plot.

This script generates a summary table of accuracy per hop bin and creates
a binned bar plot visualization (data/processed/accuracy_binned.png).

It depends on T019 (stratify_accuracy.py) which produces the binned accuracy data.
"""
import csv
import json
import logging
import sys
from collections import defaultdict
from pathlib import Path

# Import from project utils
from utils.config import get_project_root, get_path, ensure_dir

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_binned_accuracy_data() -> dict:
    """
    Load binned accuracy data from T019 output.
    
    Expected input: data/processed/binned_accuracy.json
    (Generated by code/analysis/stratify_accuracy.py)
    
    Returns:
        dict: Dictionary containing bin statistics (accuracy, count, etc.)
    """
    project_root = get_project_root()
    input_path = get_path(project_root, "data/processed/binned_accuracy.json")
    
    if not input_path.exists():
        raise FileNotFoundError(
            f"Binned accuracy data not found at {input_path}. "
            "Please run T019 (stratify_accuracy.py) first."
        )
    
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    logger.info(f"Loaded binned accuracy data from {input_path}")
    return data

def generate_summary_table(binned_data: dict) -> list:
    """
    Generate a summary table from binned accuracy data.
    
    Args:
        binned_data: Dictionary containing bin statistics.
        
    Returns:
        list: List of dictionaries representing the summary table rows.
    """
    summary = []
    
    bins = binned_data.get('bins', [])
    for bin_info in bins:
        bin_name = bin_info.get('bin_name', 'Unknown')
        accuracy = bin_info.get('accuracy', 0.0)
        count = bin_info.get('count', 0)
        confidence_interval = bin_info.get('confidence_interval', None)
        
        row = {
            'bin': bin_name,
            'accuracy': accuracy,
            'count': count,
            'ci_lower': confidence_interval[0] if confidence_interval else None,
            'ci_upper': confidence_interval[1] if confidence_interval else None
        }
        summary.append(row)
    
    logger.info(f"Generated summary table with {len(summary)} rows")
    return summary

def save_summary_table(summary: list, output_path: Path):
    """
    Save the summary table to a CSV file.
    
    Args:
        summary: List of dictionaries representing table rows.
        output_path: Path to the output CSV file.
    """
    ensure_dir(output_path.parent)
    
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        if summary:
            writer = csv.DictWriter(f, fieldnames=summary[0].keys())
            writer.writeheader()
            writer.writerows(summary)
    
    logger.info(f"Saved summary table to {output_path}")

def generate_binned_plot(summary: list, output_path: Path):
    """
    Generate a binned bar plot of accuracy vs. hop bin.
    
    Args:
        summary: List of dictionaries containing bin statistics.
        output_path: Path to save the plot image.
    """
    import matplotlib.pyplot as plt
    
    if not summary:
        logger.warning("No data to plot. Skipping plot generation.")
        return
    
    # Extract data for plotting
    bins = [row['bin'] for row in summary]
    accuracies = [row['accuracy'] for row in summary]
    counts = [row['count'] for row in summary]
    
    # Create the figure and axis
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Create bar plot
    colors = ['#4c72b0', '#55a868', '#c44e52']  # Distinct colors for bins
    bars = ax.bar(bins, accuracies, color=colors, edgecolor='black', alpha=0.8)
    
    # Add count labels on top of bars
    for i, (bar, count) in enumerate(zip(bars, counts)):
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.,
            height + 0.01,
            f'n={count}',
            ha='center',
            va='bottom',
            fontsize=10,
            fontweight='bold'
        )
    
    # Add accuracy labels on bars
    for i, (bar, acc) in enumerate(zip(bars, accuracies)):
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.,
            height / 2,
            f'{acc:.2f}',
            ha='center',
            va='center',
            fontsize=12,
            fontweight='bold',
            color='white' if height > 0.5 else 'black'
        )
    
    # Configure plot
    ax.set_xlabel('Hop Bin', fontsize=12, fontweight='bold')
    ax.set_ylabel('Accuracy', fontsize=12, fontweight='bold')
    ax.set_title('Accuracy vs. Hop Bin (Binned Summary)', fontsize=14, fontweight='bold')
    ax.set_ylim(0, max(accuracies) * 1.2 if accuracies else 1.0)
    ax.grid(axis='y', linestyle='--', alpha=0.3)
    
    # Add a note about sample size if any bin is small
    min_count = min(counts) if counts else 0
    if min_count < 50:
        ax.text(
            0.5, -0.15,
            f'Note: Some bins have <50 samples (min n={min_count}). '
            'Results may be less reliable.',
            transform=ax.transAxes,
            fontsize=10,
            style='italic',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5)
        )
    
    plt.tight_layout()
    
    # Save the plot
    ensure_dir(output_path.parent)
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    logger.info(f"Saved binned accuracy plot to {output_path}")

def main():
    """
    Main entry point for T022c.
    
    Generates:
        - data/processed/binned_summary.csv: Summary table of accuracy per bin
        - data/processed/accuracy_binned.png: Bar plot of accuracy vs. hop bin
    """
    logger.info("Starting T022c: Generate Binned Summary & Plot")
    
    try:
        # Step 1: Load binned accuracy data from T019
        binned_data = load_binned_accuracy_data()
        
        # Step 2: Generate summary table
        summary_table = generate_summary_table(binned_data)
        
        # Step 3: Save summary table to CSV
        project_root = get_project_root()
        summary_csv_path = get_path(project_root, "data/processed/binned_summary.csv")
        save_summary_table(summary_table, summary_csv_path)
        
        # Step 4: Generate and save binned plot
        plot_path = get_path(project_root, "data/processed/accuracy_binned.png")
        generate_binned_plot(summary_table, plot_path)
        
        logger.info("T022c completed successfully")
        logger.info(f"  - Summary table: {summary_csv_path}")
        logger.info(f"  - Binned plot: {plot_path}")
        
    except FileNotFoundError as e:
        logger.error(f"Missing required input data: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Error during T022c execution: {e}")
        raise

if __name__ == "__main__":
    main()