[lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # Pyflakes
  "I",  # isort
  "C",  # flake8-comprehensions
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = [
  "E501", # line too long (handled by black)
  "B008", # do not perform function calls in argument defaults (common in data pipelines)
]

[lint.per-file-ignores]
"code/tests/*" = ["S101"] # allow assert in tests

[format]
line-length = 88
indent-width = 4
target-version = "py311"
