"""
Data models for the llmXive Edit-Compass follow-up project.

Defines Pydantic models for EditInstance (raw data) and ScoreRecord (analysis output).
"""
from pathlib import Path
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, field_validator
import json


class EditInstance(BaseModel):
    """
    Represents a single image editing instance from the Edit-Compass dataset.

    Attributes:
        source_image_path: Path to the original source image.
        edited_image_path: Path to the edited image.
        instruction: The text instruction used for the edit.
        category: The category of the edit (e.g., "World Knowledge Reasoning").
        human_judgment_score: The score assigned by human evaluators.
    """
    source_image_path: str = Field(..., description="Path to the source image")
    edited_image_path: str = Field(..., description="Path to the edited image")
    instruction: str = Field(..., description="The editing instruction")
    category: str = Field(..., description="Category of the edit")
    human_judgment_score: float = Field(..., ge=0.0, le=1.0, description="Human evaluation score")

    @field_validator('source_image_path', 'edited_image_path')
    @classmethod
    def validate_paths(cls, v: str) -> str:
        """Ensure paths are valid strings (basic check)."""
        if not v:
            raise ValueError("Path cannot be empty")
        return v

    @field_validator('human_judgment_score')
    @classmethod
    def validate_score_range(cls, v: float) -> float:
        """Ensure score is between 0 and 1."""
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"human_judgment_score must be between 0 and 1, got {v}")
        return v

    def to_dict(self) -> Dict[str, Any]:
        """Convert instance to dictionary."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'EditInstance':
        """Create instance from dictionary."""
        return cls(**data)

    @classmethod
    def from_json_file(cls, file_path: str) -> 'EditInstance':
        """Load instance from a JSON file."""
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return cls(**data)

    def save_to_json_file(self, file_path: str) -> None:
        """Save instance to a JSON file."""
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(self.model_dump(), f, indent=2)


class ScoreRecord(BaseModel):
    """
    Represents the computed scores and metadata for a single EditInstance.

    Attributes:
        instance_id: Unique identifier for the instance (usually source image path or hash).
        logic_score: Score representing logic consistency (VLM-based).
        fidelity_score: Score representing image fidelity (SSIM/LPIPS based).
        ssim: Structural Similarity Index Measure value.
        lpips: Learned Perceptual Image Patch Similarity value.
        vllm_description: Text description generated by the VLM.
        p_value_logic: P-value for the logic score significance.
        p_value_fidelity: P-value for the fidelity score significance.
        beta_logic: Standardized regression coefficient for logic score.
        beta_fidelity: Standardized regression coefficient for fidelity score.
    """
    instance_id: str = Field(..., description="Unique identifier for the instance")
    logic_score: float = Field(..., ge=-1.0, le=1.0, description="Logic consistency score")
    fidelity_score: float = Field(..., ge=0.0, le=1.0, description="Fidelity score")
    ssim: float = Field(..., ge=0.0, le=1.0, description="SSIM value")
    lpips: float = Field(..., ge=0.0, le=1.0, description="LPIPS value")
    vllm_description: str = Field(..., description="VLM generated description")
    p_value_logic: Optional[float] = Field(None, ge=0.0, le=1.0, description="P-value for logic score")
    p_value_fidelity: Optional[float] = Field(None, ge=0.0, le=1.0, description="P-value for fidelity score")
    beta_logic: Optional[float] = Field(None, description="Standardized beta for logic score")
    beta_fidelity: Optional[float] = Field(None, description="Standardized beta for fidelity score")

    @field_validator('logic_score')
    @classmethod
    def validate_logic_range(cls, v: float) -> float:
        """Ensure logic score is between -1 and 1."""
        if not (-1.0 <= v <= 1.0):
            raise ValueError(f"logic_score must be between -1 and 1, got {v}")
        return v

    @field_validator('fidelity_score', 'ssim', 'lpips')
    @classmethod
    def validate_metric_range(cls, v: float, info) -> float:
        """Ensure metric scores are between 0 and 1."""
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"{info.field_name} must be between 0 and 1, got {v}")
        return v

    def to_dict(self) -> Dict[str, Any]:
        """Convert record to dictionary."""
        return self.model_dump(exclude_none=True)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ScoreRecord':
        """Create record from dictionary."""
        return cls(**data)

    def to_json(self) -> str:
        """Convert record to JSON string."""
        return json.dumps(self.model_dump(exclude_none=True), indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> 'ScoreRecord':
        """Create record from JSON string."""
        data = json.loads(json_str)
        return cls(**data)