"""
T016: Write generated instances to data/raw/logical_puzzles.jsonl.

This script reads the in-memory generated puzzle data (produced by T012-T015),
applies the ground truth perturbation (T015), and writes the final dataset
to data/raw/logical_puzzles.jsonl with the required metadata fields.
"""

import os
import json
import logging
from pathlib import Path
from typing import List, Dict, Any

# Import from existing API surface
from utils.logging_utils import configure_logging, generate_checksum, write_checksum_file
from perturb_ground_truth import load_puzzles, process_puzzles

# Configure logging
logger = logging.getLogger(__name__)
configure_logging(level=logging.INFO)

def main():
    """
    Main entry point for T016.
    1. Loads generated puzzles (from T012-T015 pipeline).
    2. Ensures ground truth paths are perturbed (T015 logic).
    3. Writes to data/raw/logical_puzzles.jsonl.
    4. Generates checksum.
    """
    # Ensure output directory exists
    output_dir = Path("data/raw")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "logical_puzzles.jsonl"
    checksum_file = Path("data/checksums.txt")

    logger.info(f"Starting T016: Writing puzzles to {output_file}")

    # Load the intermediate data generated by previous steps.
    # Since T015 produces the perturbed ground truths, we rely on the
    # perturb_ground_truth module to handle the loading and processing.
    # We assume the generator output was saved to a temp file or memory
    # that perturb_ground_truth can access, or we re-generate if needed.
    # However, based on the task flow, T015 likely produced a JSONL or
    # we need to call the generator again here to ensure we have the data
    # to write.
    
    # To strictly follow the "extend" constraint and avoid re-implementation:
    # We assume the generator logic (T012-T014) produced a list of dicts
    # and T015 processed them. 
    # Since we cannot access the in-memory state of previous tasks, 
    # we will re-instantiate the generator to produce the data needed for writing,
    # ensuring we use the same parameters as T012-T015.
    
    # Import generator components
    from graph_generator import LogicalPuzzleGenerator
    
    # Configuration matching T012-T015
    # We use a small sample for this specific task demonstration if no file exists,
    # but in a real pipeline, this would read from the output of T015.
    # Since T015 is "completed" in the list, we assume the data exists or 
    # we regenerate with the same seed.
    
    # Let's assume the standard generation parameters:
    # N=500, depth 3-6, branching 1-5 (from T010 description)
    N = 500
    min_depth, max_depth = 3, 6
    min_branch, max_branch = 1, 5
    
    generator = LogicalPuzzleGenerator(
        min_nesting_depth=min_depth,
        max_nesting_depth=max_depth,
        min_branching_factor=min_branch,
        max_branching_factor=max_branch,
        target_orthogonalization=0.2
    )
    
    logger.info(f"Generating {N} puzzles with orthogonalization...")
    puzzles = generator.generate_batch(N)
    
    if not puzzles:
        logger.error("No puzzles generated. Aborting.")
        return

    # Apply ground truth perturbation (T015 logic)
    # The perturb_ground_truth module expects a list of puzzle dicts.
    # We simulate the file-based interaction if needed, or pass directly.
    # Since perturb_ground_truth.load_puzzles expects a file, we might need 
    # a temporary file or modify the flow.
    # However, T015 description says it writes cycle rate to validation_metrics.json.
    # Let's assume we have the raw data here and apply perturbation.
    
    # Re-using process_puzzles logic:
    # We need to ensure the 'ground_truth_path' is the perturbed one.
    # The perturb_ground_truth module likely handles the logic of selecting 
    # a path different from the longest path.
    
    # To integrate cleanly without modifying perturb_ground_truth (which is T015),
    # we will assume the 'puzzles' list from the generator has the raw graph
    # and the 'longest_path' as ground truth initially.
    # We need to apply the perturbation logic now.
    
    # Since we cannot easily call the internal logic of T015 without a file,
    # and T015 is marked complete, we assume the 'puzzles' list is ready 
    # OR we need to write a temporary file for process_puzzles to read.
    
    # Strategy: Write temp file -> process -> write final.
    # But T016 is about writing the FINAL file.
    # Let's implement the perturbation logic inline here to ensure T016 
    # produces the correct output without dependency on external file IO 
    # that might be flaky in this context, while respecting the API surface.
    
    # Actually, the prompt says "extend existing API". 
    # perturb_ground_truth has 'process_puzzles'. Let's use that.
    # We need a source file.
    
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
        for p in puzzles:
            f.write(json.dumps(p) + '\n')
        temp_path = f.name

    try:
        # Load and process (perturb ground truth)
        processed_puzzles = process_puzzles(temp_path)
    finally:
        os.unlink(temp_path)

    if not processed_puzzles:
        logger.error("Processing failed or returned empty. Aborting.")
        return

    # Write to final destination
    logger.info(f"Writing {len(processed_puzzles)} puzzles to {output_file}")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        for puzzle in processed_puzzles:
            # Ensure all required fields are present
            required_fields = [
                'instance_id', 'text', 'ground_truth_path', 
                'nesting_depth', 'branching_factor', 'graph_structure'
            ]
            for field in required_fields:
                if field not in puzzle:
                    logger.warning(f"Missing field {field} in puzzle {puzzle.get('instance_id', 'unknown')}")
            
            f.write(json.dumps(puzzle) + '\n')

    # Generate checksum
    logger.info(f"Generating checksum for {output_file}")
    checksum = generate_checksum(output_file)
    write_checksum_file(output_file, checksum, checksum_file)
    
    logger.info(f"T016 Complete. Output: {output_file}, Checksum: {checksum}")

if __name__ == "__main__":
    main()
