import os
import sys
import csv
import logging
import argparse
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

# Import from local config if needed, though standard library is sufficient here
from config import ensure_dirs, AnalysisConfig

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def verify_file_exists_and_non_empty(path: Path) -> Tuple[bool, str]:
    """
    Verifies that a file exists and has non-zero size.
    Returns (True, "") if valid, (False, error_message) otherwise.
    """
    if not path.exists():
        return False, f"File does not exist: {path}"
    
    if path.stat().st_size == 0:
        return False, f"File is empty: {path}"
    
    return True, ""

def verify_csv_columns(path: Path, required_columns: List[str]) -> Tuple[bool, str]:
    """
    Verifies that a CSV file exists, is non-empty, and contains the required columns.
    Returns (True, "") if valid, (False, error_message) otherwise.
    """
    exists, err = verify_file_exists_and_non_empty(path)
    if not exists:
        return False, err

    try:
        with open(path, 'r', newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            if reader.fieldnames is None:
                return False, f"CSV file {path} has no headers."
            
            missing = set(required_columns) - set(reader.fieldnames)
            if missing:
                return False, f"Missing columns in {path}: {missing}"
            
            # Verify at least one data row exists
            first_row = next(reader, None)
            if first_row is None:
                return False, f"CSV file {path} has no data rows."
            
            return True, ""
    except Exception as e:
        return False, f"Error reading CSV {path}: {str(e)}"

def run_verification() -> Dict[str, Any]:
    """
    Main verification logic for T030.
    Checks existence and schema compliance of required artifacts.
    """
    results = {
        "feature_importance_png": False,
        "sensitivity_report_csv": False,
        "perturbation_results_csv": False,
        "collinearity_report_md": False,
        "all_passed": False,
        "errors": []
    }

    # Define paths relative to project root
    project_root = Path(__file__).resolve().parent.parent.parent
    artifacts_dir = project_root / "artifacts"
    
    # Ensure artifacts directory exists (should have been created by previous tasks)
    ensure_dirs()

    # 1. Verify artifacts/feature_importance.png
    feature_importance_path = artifacts_dir / "feature_importance.png"
    exists, err = verify_file_exists_and_non_empty(feature_importance_path)
    if exists:
        results["feature_importance_png"] = True
        logger.info(f"Verified: {feature_importance_path} exists and is non-empty.")
    else:
        results["errors"].append(f"feature_importance.png: {err}")
        logger.warning(f"Verification failed for feature_importance.png: {err}")

    # 2. Verify artifacts/sensitivity_report.csv
    # Required columns: threshold_type, threshold_value, r2, mae, variance
    sensitivity_path = artifacts_dir / "sensitivity_report.csv"
    required_cols_sens = ["threshold_type", "threshold_value", "r2", "mae", "variance"]
    exists, err = verify_csv_columns(sensitivity_path, required_cols_sens)
    if exists:
        results["sensitivity_report_csv"] = True
        logger.info(f"Verified: {sensitivity_path} exists, non-empty, and has correct columns.")
    else:
        results["errors"].append(f"sensitivity_report.csv: {err}")
        logger.warning(f"Verification failed for sensitivity_report.csv: {err}")

    # 3. Verify artifacts/perturbation_results.csv
    # Columns generated by T029: typically molecule_id, top_atoms, r2_drop, etc.
    # We check for existence and non-empty, and verify it has *some* columns.
    perturbation_path = artifacts_dir / "perturbation_results.csv"
    exists, err = verify_file_exists_and_non_empty(perturbation_path)
    if exists:
        # Additional check: ensure it's a valid CSV with headers
        try:
            with open(perturbation_path, 'r', newline='', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                if reader.fieldnames is None or len(list(reader)) == 0:
                    err = "File has headers but no data rows."
                    exists = False
        except Exception as e:
            err = f"Error reading file: {str(e)}"
            exists = False

    if exists:
        results["perturbation_results_csv"] = True
        logger.info(f"Verified: {perturbation_path} exists and is non-empty.")
    else:
        results["errors"].append(f"perturbation_results.csv: {err}")
        logger.warning(f"Verification failed for perturbation_results.csv: {err}")

    # 4. Verify artifacts/collinearity_report.md
    collinearity_path = artifacts_dir / "collinearity_report.md"
    exists, err = verify_file_exists_and_non_empty(collinearity_path)
    if exists:
        results["collinearity_report_md"] = True
        logger.info(f"Verified: {collinearity_path} exists and is non-empty.")
    else:
        results["errors"].append(f"collinearity_report.md: {err}")
        logger.warning(f"Verification failed for collinearity_report.md: {err}")

    # Aggregate result
    results["all_passed"] = all([
        results["feature_importance_png"],
        results["sensitivity_report_csv"],
        results["perturbation_results_csv"],
        results["collinearity_report_md"]
    ])

    return results

def main():
    """Entry point for the verification script."""
    parser = argparse.ArgumentParser(description="Verify artifact existence and schema compliance for T030.")
    parser.add_argument('--verbose', action='store_true', help="Enable verbose logging")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    logger.info("Starting artifact verification for T030...")
    results = run_verification()

    print("\n--- Verification Results ---")
    print(f"Feature Importance Plot: {'PASS' if results['feature_importance_png'] else 'FAIL'}")
    print(f"Sensitivity Report CSV: {'PASS' if results['sensitivity_report_csv'] else 'FAIL'}")
    print(f"Perturbation Results CSV: {'PASS' if results['perturbation_results_csv'] else 'FAIL'}")
    print(f"Collinearity Report MD: {'PASS' if results['collinearity_report_md'] else 'FAIL'}")
    print(f"Overall Status: {'ALL PASSED' if results['all_passed'] else 'SOME FAILED'}")
    
    if results["errors"]:
        print("\nErrors encountered:")
        for err in results["errors"]:
            print(f"  - {err}")

    # Exit with error code if any verification failed
    if not results["all_passed"]:
        logger.error("Verification failed. Check logs for details.")
        sys.exit(1)
    else:
        logger.info("All verifications passed successfully.")
        sys.exit(0)

if __name__ == "__main__":
    main()