import os
import sys
import logging
import argparse
from pathlib import Path
from typing import Optional

from src.utils.config import get_project_root, get_state_root, get_data_root
from src.utils.logging import get_logger
from src.data.download import main as download_main
from src.data.harmonize import main as harmonize_main, check_data_sufficiency, check_global_poll_count
from src.data.weights import main as weights_main
from src.models.frequentist import main as frequentist_main
from src.models.bayesian import main as bayesian_main
from src.evaluation.metrics import main as metrics_main
from src.evaluation.meta_analysis import main as meta_analysis_main
from src.evaluation.report_generator import main as report_main

logger = get_logger(__name__)

STATE_FILE_PATH = "state/projects/PROJ-206-statistical-analysis-of-publicly-availab.yaml"

def check_sufficiency_gate() -> bool:
    """
    System-level blocking gate.
    Checks for data sufficiency flags generated by T013 (check_data_sufficiency)
    and T014 (check_global_poll_count) before allowing downstream tasks to execute.
    
    Returns:
        bool: True if data is sufficient and pipeline can proceed, False otherwise.
    
    Raises:
        RuntimeError: If data is insufficient, halting the pipeline.
    """
    state_root = get_state_root()
    state_file = Path(state_root) / STATE_FILE_PATH
    
    if not state_file.exists():
        logger.warning("State file not found. Assuming pipeline has not run data checks yet. "
                     "Proceeding with caution (downstream tasks may fail).")
        return True

    try:
        import yaml
        with open(state_file, 'r') as f:
            state_data = yaml.safe_load(f) or {}
    except Exception as e:
        logger.error(f"Failed to parse state file {state_file}: {e}")
        # If state is unreadable, we cannot verify sufficiency. Fail loudly.
        raise RuntimeError(f"Cannot verify data sufficiency due to state file error: {e}")

    # Check flags set by T013 and T014
    # These flags are expected to be set in the state file by the harmonize/weights scripts
    # when they successfully pass their checks.
    
    # T014: Global poll count check
    global_poll_check_passed = state_data.get('checks', {}).get('global_poll_count_passed', False)
    
    # T013: Data sufficiency check (30-day window, distinct cycles)
    data_sufficiency_passed = state_data.get('checks', {}).get('data_sufficiency_passed', False)

    if not global_poll_check_passed:
        error_msg = (
            "DATA SUFFICIENCY GATE FAILED: Global poll count check (T014) failed. "
            "Total ingested polls across all cycles is less than 500. "
            "Pipeline halted to prevent unreliable statistical analysis."
        )
        logger.error(error_msg)
        raise RuntimeError(error_msg)

    if not data_sufficiency_passed:
        error_msg = (
            "DATA SUFFICIENCY GATE FAILED: Data sufficiency check (T013) failed. "
            "Insufficient polls in the 30 days preceding the election or "
            "fewer than 3 distinct election cycles found. "
            "Pipeline halted to prevent unreliable statistical analysis."
        )
        logger.error(error_msg)
        raise RuntimeError(error_msg)

    logger.info("DATA SUFFICIENCY GATE PASSED: All checks (T013, T014) passed. Proceeding with pipeline.")
    return True

def run_pipeline(args: Optional[argparse.Namespace] = None):
    """
    Executes the full pipeline sequence.
    Steps:
    1. Download raw data (T009a)
    2. Harmonize data and perform checks (T010, T013, T014)
    3. Check sufficiency gate (T015) - BLOCKING
    4. Calculate weights (T011, T012)
    5. Run Frequentist models (T017, T018)
    6. Run Bayesian models (T021)
    7. Evaluate metrics (T019, T024, T025)
    8. Run Meta Analysis (T026)
    9. Generate Report (T028)
    """
    logger.info("Starting Statistical Analysis Pipeline...")
    
    # Step 1: Download
    logger.info("Step 1: Downloading data...")
    try:
        download_main()
    except Exception as e:
        logger.error(f"Download failed: {e}")
        raise

    # Step 2: Harmonize (includes T013/T014 checks internally)
    logger.info("Step 2: Harmonizing data...")
    try:
        harmonize_main()
    except Exception as e:
        logger.error(f"Harmonization failed: {e}")
        # If harmonize failed, it likely means a check failed (T013/T014)
        # The error should have been logged by harmonize_main
        raise

    # Step 3: T015 - Sufficiency Gate
    logger.info("Step 3: Checking data sufficiency gate (T015)...")
    try:
        check_sufficiency_gate()
    except RuntimeError as e:
        # Re-raise to halt execution
        raise

    # Step 4: Weights
    logger.info("Step 4: Calculating weights...")
    try:
        weights_main()
    except Exception as e:
        logger.error(f"Weights calculation failed: {e}")
        raise

    # Step 5: Frequentist
    logger.info("Step 5: Running Frequentist models...")
    try:
        frequentist_main()
    except Exception as e:
        logger.error(f"Frequentist modeling failed: {e}")
        raise

    # Step 6: Bayesian
    logger.info("Step 6: Running Bayesian models...")
    try:
        bayesian_main()
    except Exception as e:
        logger.error(f"Bayesian modeling failed: {e}")
        raise

    # Step 7: Metrics
    logger.info("Step 7: Evaluating metrics...")
    try:
        metrics_main()
    except Exception as e:
        logger.error(f"Metrics evaluation failed: {e}")
        raise

    # Step 8: Meta Analysis
    logger.info("Step 8: Running Meta Analysis...")
    try:
        meta_analysis_main()
    except Exception as e:
        logger.error(f"Meta Analysis failed: {e}")
        raise

    # Step 9: Report
    logger.info("Step 9: Generating Report...")
    try:
        report_main()
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise

    logger.info("Pipeline completed successfully.")

def main():
    parser = argparse.ArgumentParser(description="Statistical Analysis of Publicly Available Election Poll Aggregates")
    parser.add_argument('--skip-download', action='store_true', help='Skip data download step')
    parser.add_argument('--skip-harmonize', action='store_true', help='Skip data harmonization step')
    # Add more flags as needed for partial runs, but T015 gate always runs if downstream is requested
    
    args = parser.parse_args()
    
    # Initialize logging
    # (Assuming logging is initialized elsewhere or by config, but safe to call here if needed)
    
    try:
        if args.skip_download and args.skip_harmonize:
            # If skipping both, we assume data exists and checks passed, 
            # but strictly speaking T015 should verify state.
            # We proceed to check the gate.
            pass
        
        # If we are running the pipeline, we must check the gate before downstream
        # The gate logic is integrated into run_pipeline, but we can also call it explicitly
        # if we want to just check without running everything.
        
        # For this task, we implement the gate inside run_pipeline to block execution.
        # If the user wants to just check, they could call a specific function, 
        # but the requirement is "before executing downstream tasks".
        
        run_pipeline(args)
        
    except RuntimeError as e:
        logger.error(f"Pipeline execution halted: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error in pipeline: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()