"""
Convergence Reporter Module for User Story 2.

Aggregates convergence logs from the belief updater, calculates the global
convergence rate against the N_valid count, and explicitly verifies/asserts
it meets the ≥90% threshold (SC-002). Generates `data/models/convergence_report.json`.
"""
import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple

# Import from sibling modules based on API surface
from utils.io import ensure_dir, load_json, save_json, IOLoadError, IOSaveError
from utils.config import get_config
from utils.logger import get_logger

# Local imports within modeling
from modeling.runtime_enforcer import RuntimeLimitExceeded, SampleSizeReductionRequired

logger = get_logger(__name__)


class ConvergenceReportError(Exception):
    """Exception raised when convergence criteria are not met."""
    pass


def load_valid_participants(config: Optional[Dict] = None) -> List[str]:
    """
    Load the list of valid participants from the runtime enforcer output.
    This list represents the N_valid count for the convergence check.

    Args:
        config: Configuration dictionary. If None, uses global config.

    Returns:
        List of participant IDs that passed QC and are valid for modeling.
    """
    cfg = config or get_config()
    # The runtime enforcer writes the valid list to state/valid_participants.json
    # based on the workflow established in T024b/T024.
    valid_path = cfg.get("paths", {}).get("state", "state") + "/valid_participants.json"
    try:
        with open(valid_path, 'r') as f:
            data = json.load(f)
            participants = data.get("valid_participants", [])
        if not participants:
            logger.warning(f"No valid participants found in {valid_path}.")
        return participants
    except FileNotFoundError:
        # Fallback: try to load from the exclusions logic if valid list doesn't exist yet
        # but typically T024b ensures this file exists.
        exclusions_path = cfg.get("paths", {}).get("state", "state") + "/exclusions.yaml"
        if os.path.exists(exclusions_path):
            # If we can't find the valid list, we assume all downloaded participants
            # are valid unless explicitly excluded. However, to be robust, we rely
            # on the explicit valid_participants.json generated by T024b.
            raise IOLoadError(f"Valid participants file not found: {valid_path}. "
                              "Ensure T024b (runtime_enforcer) has run.")
        raise IOLoadError(f"Valid participants file not found: {valid_path}")


def load_convergence_logs(log_dir: Optional[Path] = None) -> Dict[str, Dict[str, Any]]:
    """
    Load convergence logs generated by `belief_updater.py` for each participant.
    These logs contain R-hat, ESS, and convergence status.

    Args:
        log_dir: Directory containing participant logs. Defaults to data/models/logs.

    Returns:
        Dictionary mapping participant_id to their convergence log data.
    """
    cfg = get_config()
    base_dir = log_dir or Path(cfg.get("paths", {}).get("models", "data/models"))
    log_dir_path = base_dir / "logs"

    if not log_dir_path.exists():
        logger.warning(f"Convergence log directory not found: {log_dir_path}. Returning empty dict.")
        return {}

    convergence_data = {}
    for log_file in log_dir_path.glob("*.json"):
        participant_id = log_file.stem
        try:
            with open(log_file, 'r') as f:
                data = json.load(f)
                convergence_data[participant_id] = data
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse convergence log for {participant_id}: {e}")
            continue

    return convergence_data


def calculate_convergence_rate(
    valid_participants: List[str],
    convergence_logs: Dict[str, Dict[str, Any]]
) -> Tuple[float, List[str], List[str]]:
    """
    Calculate the global convergence rate.

    Args:
        valid_participants: List of participant IDs that should have been modeled.
        convergence_logs: Dictionary of convergence data per participant.

    Returns:
        Tuple of (rate, list of converging participants, list of non-converging participants).
    """
    if not valid_participants:
        logger.warning("No valid participants to check convergence against.")
        return 1.0, [], []

    converging = []
    non_converging = []

    for pid in valid_participants:
        log = convergence_logs.get(pid)
        if log is None:
            # Participant was valid but no log exists -> treated as non-converging/failure
            logger.warning(f"Participant {pid} is valid but has no convergence log.")
            non_converging.append(pid)
            continue

        is_converged = log.get("converged", False)
        if is_converged:
            converging.append(pid)
        else:
            non_converging.append(pid)

    n_valid = len(valid_participants)
    n_converged = len(converging)
    rate = n_converged / n_valid if n_valid > 0 else 0.0

    return rate, converging, non_converging


def verify_threshold(
    rate: float,
    threshold: float = 0.90,
    participant_ids: Optional[List[str]] = None
) -> bool:
    """
    Verify that the convergence rate meets the required threshold (SC-002).

    Args:
        rate: The calculated convergence rate.
        threshold: The minimum required rate (default 0.90).
        participant_ids: List of participant IDs for error reporting.

    Returns:
        True if threshold is met, False otherwise.

    Raises:
        ConvergenceReportError: If the threshold is not met.
    """
    if rate >= threshold:
        logger.info(f"Convergence rate {rate:.2%} meets threshold {threshold:.2%}.")
        return True
    else:
        msg = (f"Convergence rate {rate:.2%} FAILED to meet threshold {threshold:.2%}. "
               f"SC-002 Violation.")
        logger.error(msg)
        # We raise an error to fail loudly as per constraints, but the caller
        # might want to catch this to generate the report anyway for debugging.
        # However, the task says "explicitly verify/assert it meets the threshold".
        # We raise the exception to signal failure in the pipeline.
        raise ConvergenceReportError(msg)


def generate_convergence_report(
    valid_participants: List[str],
    converging: List[str],
    non_converging: List[str],
    convergence_logs: Dict[str, Dict[str, Any]],
    output_path: Optional[Path] = None,
    threshold: float = 0.90
) -> Dict[str, Any]:
    """
    Aggregate all data and generate the final convergence report JSON.

    Args:
        valid_participants: List of all valid participant IDs.
        converging: List of IDs that converged.
        non_converging: List of IDs that did not converge.
        convergence_logs: Raw log data.
        output_path: Path to save the report.
        threshold: The threshold used for verification.

    Returns:
        The generated report dictionary.
    """
    cfg = get_config()
    if output_path is None:
        base_dir = Path(cfg.get("paths", {}).get("models", "data/models"))
        output_path = base_dir / "convergence_report.json"

    ensure_dir(output_path)

    n_valid = len(valid_participants)
    n_converged = len(converging)
    rate = n_converged / n_valid if n_valid > 0 else 0.0

    # Prepare details for each participant
    participant_details = []
    for pid in valid_participants:
        log = convergence_logs.get(pid, {})
        status = "converged" if pid in converging else "failed"
        details = {
            "participant_id": pid,
            "status": status,
            "r_hat_max": log.get("r_hat_max", None),
            "ess_min": log.get("ess_min", None),
            "samples": log.get("samples", None),
            "runtime_seconds": log.get("runtime_seconds", None),
            "message": log.get("message", "")
        }
        participant_details.append(details)

    report = {
        "report_type": "convergence_summary",
        "threshold": threshold,
        "total_valid_participants": n_valid,
        "converged_count": n_converged,
        "failed_count": len(non_converging),
        "convergence_rate": rate,
        "threshold_met": rate >= threshold,
        "converging_participants": converging,
        "non_converging_participants": non_converging,
        "participant_details": participant_details,
        "generated_at": get_config().get("timestamp", "unknown")
    }

    try:
        save_json(report, output_path)
        logger.info(f"Convergence report saved to {output_path}")
    except IOSaveError as e:
        logger.error(f"Failed to save convergence report: {e}")
        raise

    return report


def main(args: Optional[List[str]] = None) -> int:
    """
    Main entry point for the convergence reporter script.

    Usage: python -m code.modeling.convergence_reporter
    """
    import argparse

    parser = argparse.ArgumentParser(description="Generate convergence report for belief updater.")
    parser.add_argument("--config", type=str, default=None, help="Path to config YAML")
    parser.add_argument("--threshold", type=float, default=0.90, help="Convergence threshold (default 0.90)")
    parser.add_argument("--output", type=str, default=None, help="Output path for report JSON")

    parsed_args = parser.parse_args(args)

    # Setup config
    if parsed_args.config:
        load_config_from_yaml(parsed_args.config)

    cfg = get_config()
    logger.info("Starting convergence report generation...")

    try:
        # 1. Load valid participants (N_valid)
        valid_participants = load_valid_participants(cfg)
        logger.info(f"Loaded {len(valid_participants)} valid participants.")

        if not valid_participants:
            logger.warning("No valid participants found. Generating empty report.")
            # Generate report with 0 participants
            report = generate_convergence_report(
                [], [], [], {},
                output_path=Path(parsed_args.output) if parsed_args.output else None,
                threshold=parsed_args.threshold
            )
            return 0

        # 2. Load convergence logs
        convergence_logs = load_convergence_logs()
        logger.info(f"Loaded convergence logs for {len(convergence_logs)} participants.")

        # 3. Calculate rate
        rate, converging, non_converging = calculate_convergence_rate(
            valid_participants, convergence_logs
        )
        logger.info(f"Convergence Rate: {rate:.2%} ({len(converging)}/{len(valid_participants)})")

        # 4. Verify threshold (SC-002)
        try:
            verify_threshold(rate, threshold=parsed_args.threshold)
        except ConvergenceReportError as e:
            # Even if it fails, we must generate the report to document the failure
            logger.error(f"Threshold verification failed: {e}")
            # We continue to generate the report so the file exists with the failure details

        # 5. Generate Report
        output_path = Path(parsed_args.output) if parsed_args.output else None
        report = generate_convergence_report(
            valid_participants, converging, non_converging, convergence_logs,
            output_path=output_path,
            threshold=parsed_args.threshold
        )

        if not report["threshold_met"]:
            logger.critical("SC-002 VIOLATION: Convergence rate below 90%.")
            return 1
        else:
            logger.info("SC-002 PASSED: Convergence rate meets threshold.")
            return 0

    except Exception as e:
        logger.exception(f"Error during convergence reporting: {e}")
        return 2


if __name__ == "__main__":
    sys.exit(main())
