"""
summary_table.py - Generate the final summary table for US3.

Aggregates enrichment results (p-values, q-values) and ChIP-seq overlap statistics
to produce a unified CSV file satisfying US-3-SC1 Scenario 3.
"""
import os
import sys
import logging
import json
from pathlib import Path
from typing import Dict, List, Any, Optional

import pandas as pd

# Import from local project modules
from code.config import DATA_PROCESSED_DIR
from code.enrichment import aggregate_enrichment_results
from code.validate import load_enrichment_results, get_top_motifs_per_cell_type

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Define expected file paths based on previous tasks
ENRICHMENT_MATRIX_PATH = DATA_PROCESSED_DIR / "enrichment_matrix.csv"
CHIP_OVERLAP_REPORT_PATH = DATA_PROCESSED_DIR / "validation_report.json"
SUMMARY_TABLE_PATH = DATA_PROCESSED_DIR / "summary_table.csv"

def load_chip_overlap_stats() -> Dict[str, float]:
    """
    Load ChIP-seq overlap statistics from the validation report.
    
    Expects a JSON file generated by T032/T030 with overlap percentages.
    Returns a dictionary mapping motif_id -> chip_overlap_pct.
    """
    if not CHIP_OVERLAP_REPORT_PATH.exists():
        raise FileNotFoundError(
            f"Validation report not found at {CHIP_OVERLAP_REPORT_PATH}. "
            "Ensure T030/T032 has been executed successfully."
        )
    
    with open(CHIP_OVERLAP_REPORT_PATH, 'r') as f:
        report = json.load(f)
    
    # The report structure is expected to contain a 'motif_overlaps' list or similar.
    # Based on typical validation output, we look for a list of dicts with 'motif_id' and 'overlap_pct'.
    # If the structure is flat (e.g., top motifs only), we adapt.
    # Assuming the report contains a key 'motif_overlaps' which is a list of dicts.
    # If the report is just a summary, we might need to extract from 'top_motifs' if stored there.
    # Let's assume the structure: {"motif_overlaps": [{"motif_id": "...", "overlap_pct": 0.85}, ...]}
    
    overlaps = {}
    if "motif_overlaps" in report:
        for entry in report["motif_overlaps"]:
            motif_id = entry.get("motif_id")
            pct = entry.get("overlap_pct")
            if motif_id and pct is not None:
                overlaps[motif_id] = pct
    elif "top_motifs" in report:
        # Fallback if stored in top_motifs list
        for entry in report["top_motifs"]:
            motif_id = entry.get("motif_id")
            pct = entry.get("overlap_pct")
            if motif_id and pct is not None:
                overlaps[motif_id] = pct
    else:
        # Try to parse the whole report if it's a dict of motif_id -> stats
        for key, value in report.items():
            if isinstance(value, dict):
                if "overlap_pct" in value:
                    overlaps[key] = value["overlap_pct"]
    
    logger.info(f"Loaded {len(overlaps)} ChIP-seq overlap statistics.")
    return overlaps

def generate_summary_table() -> pd.DataFrame:
    """
    Generate the final summary table with columns:
    motif_id, p_value_raw, q_value_adj, chip_overlap_pct.
    
    This function merges enrichment results (from T024) with ChIP overlap stats (from T030).
    """
    if not ENRICHMENT_MATRIX_PATH.exists():
        raise FileNotFoundError(
            f"Enrichment matrix not found at {ENRICHMENT_MATRIX_PATH}. "
            "Ensure T024 (enrichment matrix generation) has been completed."
        )
    
    # Load enrichment results
    # The enrichment matrix is expected to have columns: motif_id, cell_type, p_value, q_value (or similar)
    # We need to aggregate or select the most relevant p/q values. 
    # Usually, we want the global or max enrichment per motif across cell types, or a specific cell type.
    # Given the task asks for a summary table, we will assume we need to aggregate by motif_id.
    # If the matrix has multiple rows per motif (one per cell type), we take the max q-value (min p-value) or average.
    # Let's assume the matrix has 'motif_id', 'p_value', 'q_value'.
    
    df_enrichment = pd.read_csv(ENRICHMENT_MATRIX_PATH)
    
    required_cols = ['motif_id', 'p_value', 'q_value']
    if not all(col in df_enrichment.columns for col in required_cols):
        # Try alternative column names if standard ones are missing
        # e.g., 'p_value_raw', 'q_value_adj'
        col_map = {}
        if 'p_value_raw' in df_enrichment.columns: col_map['p_value'] = 'p_value_raw'
        if 'q_value_adj' in df_enrichment.columns: col_map['q_value'] = 'q_value_adj'
        
        if col_map:
            df_enrichment = df_enrichment.rename(columns=col_map)
            if not all(col in df_enrichment.columns for col in required_cols):
                raise ValueError(f"Enrichment matrix missing required columns. Found: {df_enrichment.columns.tolist()}")
        else:
            raise ValueError(f"Enrichment matrix missing required columns. Found: {df_enrichment.columns.tolist()}")
    
    # Aggregate by motif_id. We take the minimum p-value (most significant) and corresponding q-value.
    # If q-values are independent, we might need to be careful, but typically we report the best hit.
    # Let's group by motif_id and take the row with the minimum p_value.
    df_agg = df_enrichment.loc[df_enrichment.groupby('motif_id')['p_value'].idxmin()]
    
    # Reset index to make motif_id a column again if it was index
    df_agg = df_agg.reset_index(drop=True)
    
    # Load ChIP overlap stats
    chip_stats = load_chip_overlap_stats()
    
    # Merge overlap stats into the dataframe
    # If a motif is not in the overlap stats, we set overlap to 0.0 or NaN. 
    # The task implies we have overlap stats for the motifs we are summarizing.
    df_agg['chip_overlap_pct'] = df_agg['motif_id'].map(chip_stats).fillna(0.0)
    
    # Select and rename columns to match the requirement exactly
    # Required: motif_id, p_value_raw, q_value_adj, chip_overlap_pct
    output_df = df_agg[['motif_id', 'p_value', 'q_value', 'chip_overlap_pct']].copy()
    output_df = output_df.rename(columns={
        'p_value': 'p_value_raw',
        'q_value': 'q_value_adj'
    })
    
    # Sort by q_value_adj ascending for readability
    output_df = output_df.sort_values('q_value_adj')
    
    logger.info(f"Generated summary table with {len(output_df)} rows.")
    return output_df

def main():
    """
    Main entry point to generate the summary table.
    """
    logger.info("Starting summary table generation (T033).")
    
    try:
        # Ensure output directory exists
        DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
        
        # Generate the table
        df_summary = generate_summary_table()
        
        # Write to CSV
        df_summary.to_csv(SUMMARY_TABLE_PATH, index=False)
        logger.info(f"Summary table written to {SUMMARY_TABLE_PATH}")
        
        return 0
    except Exception as e:
        logger.error(f"Failed to generate summary table: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
