"""
Sensitivity Analysis Module for Equipartition Theorem Investigation.

Implements threshold sweeps and boundary analysis to verify robustness
of statistical conclusions regarding the validity of the equipartition theorem.
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Any, Tuple, Optional
import numpy as np

class SensitivityError(Exception):
    """Custom exception for sensitivity analysis errors."""
    pass


def load_statistical_results(filepath: str) -> Dict[str, Any]:
    """
    Load statistical results from the JSON artifact generated by US2.

    Args:
        filepath: Path to statistical_results.json

    Returns:
        Dictionary containing test results, p-values, and rejection flags.

    Raises:
        SensitivityError: If file not found or invalid JSON.
    """
    path = Path(filepath)
    if not path.exists():
        raise SensitivityError(f"Statistical results file not found: {filepath}")

    try:
        with open(path, 'r') as f:
            data = json.load(f)
        return data
    except json.JSONDecodeError as e:
        raise SensitivityError(f"Invalid JSON in statistical results: {e}")


def calculate_quasi_thermal_ratio(
    df: 'pd.DataFrame',
    energy_col: str = 'E_trans',
    reference_temp: float = 1.0
) -> np.ndarray:
    """
    Calculate the quasi-thermal energy ratio for each sample.

    The ratio is defined as E_observed / E_expected, where E_expected
    is derived from the reference temperature (equipartition prediction).

    Args:
        df: DataFrame containing energy data.
        energy_col: Column name for energy values.
        reference_temp: Reference temperature (T_ref) for normalization.

    Returns:
        Array of quasi-thermal ratios.
    """
    # Assuming energy is proportional to temperature (E ~ kT)
    # Ratio = E_observed / (k * T_ref)
    # Since k is constant, we normalize by T_ref directly for the ratio
    # The spec mentions anchoring to reference value 1.0
    observed = df[energy_col].values
    expected = np.full_like(observed, reference_temp, dtype=float)
    # Avoid division by zero
    expected[expected == 0] = 1e-9
    return observed / expected


def sweep_quasi_thermal_boundaries(
    results: Dict[str, Any],
    boundaries: List[float] = [0.01, 0.05, 0.10],
    reference_value: float = 1.0
) -> Dict[str, Any]:
    """
    Sweep quasi-thermal energy ratio boundaries to record classification rates.

    This function analyzes how the classification of samples as "quasi-thermal"
    vs "non-thermal" changes as the acceptance boundary around the reference
    value (1.0) is varied.

    The boundary is defined as a percentage deviation from the reference value.
    For a boundary b, a sample is classified as quasi-thermal if:
        |Ratio - 1.0| <= b

    Args:
        results: Dictionary from load_statistical_results containing bin data.
        boundaries: List of boundary percentages (e.g., 0.01 for 1%).
        reference_value: The reference ratio value (default 1.0).

    Returns:
        Dictionary mapping each boundary to classification statistics.
        Structure: {
            "boundaries": [list of boundaries],
            "classification_rates": [fraction of samples within boundary],
            "counts_within": [int],
            "counts_total": [int],
            "details": [list of dicts with per-bin stats]
        }
    """
    if 'bins' not in results:
        raise SensitivityError("Statistical results missing 'bins' key")

    bins_data = results['bins']
    total_samples = 0
    total_within_boundary = {b: 0 for b in boundaries}
    bin_details = []

    # Iterate over all bins in the results
    for bin_id, bin_data in bins_data.items():
        # Extract energy ratios or calculate them if raw energies are present
        # Assuming the statistical results contain pre-calculated ratios or enough info
        # If 'ratios' key exists, use it. Otherwise, we might need to re-calculate
        # from energy columns if available in the bin data.
        # For this implementation, we assume 'ratios' or similar metric is present
        # or we derive it from the 'observed_mean' vs 'expected' if stored.

        # Fallback: If specific ratio data isn't in the JSON, we assume the
        # statistical test results (p-values) imply the deviation magnitude.
        # However, the task specifically asks for "quasi-thermal energy ratio boundaries".
        # We will assume the 'bins' structure contains 'observed_mean' and 'expected_mean'.

        if 'observed_mean' in bin_data and 'expected_mean' in bin_data:
            ratio = bin_data['observed_mean'] / bin_data['expected_mean']
            count = bin_data.get('n_samples', 1)
        elif 'ratio' in bin_data:
            ratio = bin_data['ratio']
            count = bin_data.get('n_samples', 1)
        else:
            # If we cannot compute a ratio, skip this bin for ratio analysis
            # but still count it in total if possible
            continue

        total_samples += count

        for b in boundaries:
            threshold_low = reference_value * (1 - b)
            threshold_high = reference_value * (1 + b)

            if threshold_low <= ratio <= threshold_high:
                total_within_boundary[b] += count

    classification_rates = []
    counts_within = []
    detailed_results = []

    for b in boundaries:
        rate = total_within_boundary[b] / total_samples if total_samples > 0 else 0.0
        classification_rates.append(rate)
        counts_within.append(total_within_boundary[b])

        detailed_results.append({
            "boundary": b,
            "boundary_percent": f"{b*100:.1f}%",
            "samples_within": total_within_boundary[b],
            "total_samples": total_samples,
            "classification_rate": rate
        })

    return {
        "boundaries": boundaries,
        "classification_rates": classification_rates,
        "counts_within": counts_within,
        "total_samples": total_samples,
        "details": detailed_results
    }


def verify_robustness(
    results: Dict[str, Any],
    alpha_thresholds: List[float] = [0.01, 0.05, 0.10],
    boundary_thresholds: List[float] = [0.01, 0.05, 0.10]
) -> Dict[str, Any]:
    """
    Verify robustness of the primary rejection decision across thresholds.

    Checks if the primary conclusion (reject/fail to reject equipartition)
    remains consistent across the specified sets of significance thresholds
    and boundary values.

    Args:
        results: Statistical results dictionary.
        alpha_thresholds: List of alpha values to test.
        boundary_thresholds: List of quasi-thermal boundaries to test.

    Returns:
        Dictionary containing robustness verification results.
    """
    # This function primarily relies on the alpha sweep for statistical tests
    # and the boundary sweep for energy ratio classification.
    # We need to determine if the "primary decision" flips.

    # 1. Check alpha robustness (from statistical tests)
    alpha_sweep = sweep_alpha_thresholds(results, alpha_thresholds)
    alpha_robust = True
    rejection_flags = [r['rejection_count'] > 0 for r in alpha_sweep.get('results', [])]
    if len(set(rejection_flags)) > 1:
        alpha_robust = False

    # 2. Check boundary robustness
    boundary_sweep = sweep_quasi_thermal_boundaries(results, boundary_thresholds)
    # We check if the classification rate changes drastically (e.g., > 50% change)
    # or if the primary decision (e.g., "mostly thermal" vs "mostly non-thermal") flips.
    # Let's define "mostly thermal" as > 50% of samples within the boundary.
    boundary_robust = True
    thermal_flags = [r['classification_rate'] > 0.5 for r in boundary_sweep.get('details', [])]
    if len(set(thermal_flags)) > 1:
        boundary_robust = False

    return {
        "alpha_robust": alpha_robust,
        "boundary_robust": boundary_robust,
        "overall_robust": alpha_robust and boundary_robust,
        "alpha_results": alpha_sweep,
        "boundary_results": boundary_sweep
    }


def sweep_alpha_thresholds(
    results: Dict[str, Any],
    thresholds: List[float] = [0.01, 0.05, 0.10]
) -> Dict[str, Any]:
    """
    Sweep significance threshold alpha and record rejection counts.

    Args:
        results: Statistical results dictionary.
        thresholds: List of alpha values.

    Returns:
        Dictionary with rejection counts for each alpha.
    """
    if 'tests' not in results:
        raise SensitivityError("Statistical results missing 'tests' key")

    test_results = results['tests']
    rejection_counts = {t: 0 for t in thresholds}

    for test_entry in test_results:
        p_value = test_entry.get('p_value', 1.0)
        for t in thresholds:
            if p_value < t:
                rejection_counts[t] += 1

    return {
        "thresholds": thresholds,
        "rejection_counts": rejection_counts,
        "results": [
            {"alpha": t, "rejections": rejection_counts[t]}
            for t in thresholds
        ]
    }


def run_sensitivity_analysis(
    input_path: str,
    output_path: str
) -> Dict[str, Any]:
    """
    Run the full sensitivity analysis pipeline.

    1. Load statistical results.
    2. Sweep alpha thresholds.
    3. Sweep quasi-thermal boundaries.
    4. Verify robustness.
    5. Save report to JSON.

    Args:
        input_path: Path to statistical_results.json.
        output_path: Path to write sensitivity_analysis_report.json.

    Returns:
        The generated report dictionary.
    """
    # Load data
    results = load_statistical_results(input_path)

    # Perform sweeps
    alpha_results = sweep_alpha_thresholds(results)
    boundary_results = sweep_quasi_thermal_boundaries(results)

    # Verify robustness
    robustness = verify_robustness(results)

    # Compile report
    report = {
        "input_file": input_path,
        "alpha_sweep": alpha_results,
        "boundary_sweep": boundary_results,
        "robustness_verification": robustness,
        "summary": {
            "alpha_robust": robustness['alpha_robust'],
            "boundary_robust": robustness['boundary_robust'],
            "overall_robust": robustness['overall_robust']
        }
    }

    # Write output
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w') as f:
        json.dump(report, f, indent=2)

    return report


def main():
    """Entry point for CLI execution."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Run sensitivity analysis on statistical results."
    )
    parser.add_argument(
        "--input",
        type=str,
        default="artifacts/statistical_results.json",
        help="Path to statistical_results.json"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="artifacts/sensitivity_analysis_report.json",
        help="Path for output report"
    )

    args = parser.parse_args()

    try:
        print(f"Loading results from {args.input}...")
        report = run_sensitivity_analysis(args.input, args.output)
        print(f"Sensitivity analysis complete. Report saved to {args.output}")
        print(f"Overall Robustness: {report['summary']['overall_robust']}")
    except SensitivityError as e:
        print(f"Error: {e}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()