import json
import logging
import os
from pathlib import Path
from typing import Dict, List, Any, Tuple
import matplotlib.pyplot as plt
import numpy as np

# Ensure we can import from the project root if run as a script
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

logger = logging.getLogger(__name__)

def load_outlier_indices(filepath: str) -> Dict[str, List[int]]:
    """
    Load outlier indices from the JSON file generated by T024b.
    Returns a dict: {'ai': [indices], 'non_ai': [indices]}
    """
    path = Path(filepath)
    if not path.exists():
        logger.warning(f"Outlier indices file not found at {filepath}. Proceeding without outlier exclusion for visualization.")
        return {'ai': [], 'non_ai': []}
    
    with open(path, 'r') as f:
        data = json.load(f)
    
    return {
        'ai': data.get('ai', []),
        'non_ai': data.get('non_ai', [])
    }

def prepare_boxplot_data(
    processed_data: List[Dict[str, Any]], 
    outlier_indices: Dict[str, List[int]]
) -> Tuple[List[float], List[float]]:
    """
    Prepare data for boxplot, excluding outliers for the visualization only.
    
    Args:
        processed_data: List of PR records from data/processed/processed_data.json
        outlier_indices: Dict of indices to exclude per group
    
    Returns:
        Tuple of (ai_turnaround_times, non_ai_turnaround_times) with outliers removed
    """
    ai_times = []
    non_ai_times = []
    
    # We assume the processed data list preserves the original order or has an index field.
    # Since the analyze.py logic likely returns a list, we iterate with index.
    # If the data was filtered/reordered in T018, we need to match the logic used in T024.
    # Assuming processed_data is the list used in T024.
    
    for i, record in enumerate(processed_data):
        turnaround = record.get('turnaround_hours')
        if turnaround is None:
            continue
            
        is_ai = record.get('is_ai', False)
        
        # Check if this index is in the outlier list for its group
        if is_ai and i in outlier_indices.get('ai', []):
            continue
        if not is_ai and i in outlier_indices.get('non_ai', []):
            continue
        
        if is_ai:
            ai_times.append(turnaround)
        else:
            non_ai_times.append(turnaround)
    
    return ai_times, non_ai_times

def generate_boxplot(
    ai_data: List[float], 
    non_ai_data: List[float], 
    output_path: str, 
    dpi: int = 300
) -> None:
    """
    Generate and save a publication-quality boxplot comparing turnaround times.
    
    Args:
        ai_data: List of turnaround hours for AI-assisted PRs (outliers excluded for whiskers)
        non_ai_data: List of turnaround hours for non-AI PRs (outliers excluded for whiskers)
        output_path: Full path to save the image (e.g., artifacts/boxplot.png)
        dpi: Resolution of the output image (default 300)
    """
    if not ai_data or not non_ai_data:
        raise ValueError("Cannot generate boxplot: one or both groups have no data after outlier exclusion.")

    plt.style.use('seaborn-v0_8-whitegrid')
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Prepare data for boxplot
    data_to_plot = [non_ai_data, ai_data]
    labels = ['Non-AI', 'AI-Assisted']
    
    # Create boxplot
    bp = ax.boxplot(
        data_to_plot,
        labels=labels,
        patch_artist=True,
        notch=False,
        showfliers=False # We already excluded outliers for the visualization logic
    )
    
    # Color the boxes
    colors = ['#a6cee3', '#1f78b4'] # Light blue, Dark blue
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
    
    # Labels and Title
    ax.set_ylabel('Turnaround Time (Hours)', fontsize=12, fontweight='bold')
    ax.set_xlabel('PR Type', fontsize=12, fontweight='bold')
    ax.set_title('Comparison of Code Review Turnaround Times: AI vs. Non-AI', fontsize=14, fontweight='bold')
    
    # Add median lines if needed (boxplot draws them by default, but we ensure visibility)
    for line in bp['medians']:
        line.set_color('red')
        line.set_linewidth(2)
    
    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    # Save with high DPI
    plt.savefig(output_path, dpi=dpi, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    
    logger.info(f"Boxplot saved to {output_path} at {dpi} DPI")

def main():
    """
    Main entry point for T033: Save visualization to artifacts/boxplot.png with >= 300 DPI.
    """
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    
    project_root = Path(__file__).parent.parent
    processed_data_path = project_root / 'data' / 'processed' / 'processed_data.json'
    outlier_indices_path = project_root / 'data' / 'processed' / 'outlier_indices.json'
    output_path = project_root / 'artifacts' / 'boxplot.png'
    
    # Ensure artifacts directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Load processed data (Assuming T018 saved it here)
    if not processed_data_path.exists():
        logger.error(f"Processed data not found at {processed_data_path}. Run T018 first.")
        return
    
    with open(processed_data_path, 'r') as f:
        processed_data = json.load(f)
    
    logger.info(f"Loaded {len(processed_data)} records from {processed_data_path}")
    
    # Load outlier indices (from T024b)
    outlier_indices = load_outlier_indices(str(outlier_indices_path))
    logger.info(f"Loaded outlier indices: AI={len(outlier_indices['ai'])}, Non-AI={len(outlier_indices['non_ai'])}")
    
    # Prepare data (excluding outliers for visualization)
    ai_times, non_ai_times = prepare_boxplot_data(processed_data, outlier_indices)
    
    logger.info(f"Data for plot: AI={len(ai_times)}, Non-AI={len(non_ai_times)}")
    
    if len(ai_times) == 0 or len(non_ai_times) == 0:
        logger.error("Cannot plot: One group is empty after outlier exclusion.")
        return

    # Generate and save boxplot (T033 requirement: >= 300 DPI)
    generate_boxplot(ai_times, non_ai_times, str(output_path), dpi=300)
    
    logger.info("T033 completed successfully.")

if __name__ == '__main__':
    main()