import os
import logging
import pandas as pd
import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Any

from utils import get_logger, ensure_directory, log_stage
from utils.helpers import ensure_directory as utils_ensure_directory

# Constants for paths relative to project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SENSITIVITY_DATA_PATH = PROJECT_ROOT / "results" / "sensitivity_data.csv"
SENSITIVITY_SUMMARY_PATH = PROJECT_ROOT / "results" / "sensitivity_summary.txt"

def load_sensitivity_data(path: Optional[Path] = None) -> pd.DataFrame:
    """
    Loads the sensitivity analysis data from the CSV file generated by T026.
    
    Args:
        path: Optional path to the sensitivity data CSV. Defaults to results/sensitivity_data.csv.
    
    Returns:
        DataFrame containing sensitivity sweep results.
    
    Raises:
        FileNotFoundError: If the sensitivity data file does not exist.
        ValueError: If the file is empty or lacks required columns.
    """
    if path is None:
        path = SENSITIVITY_DATA_PATH
    
    if not path.exists():
        raise FileNotFoundError(f"Sensitivity data file not found at {path}. "
                                "Ensure T026 has been executed successfully.")
    
    df = pd.read_csv(path)
    
    required_columns = ['chi2_threshold', 'mond_pass_count', 'nfw_pass_count', 
                        'total_galaxies', 'mond_pass_rate', 'nfw_pass_rate']
    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Sensitivity data missing required columns: {missing_cols}")
    
    if df.empty:
        raise ValueError("Sensitivity data file is empty.")
    
    return df

def compute_summary_stats(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Computes summary statistics for the sensitivity analysis.
    
    Args:
        df: DataFrame with sensitivity sweep results.
    
    Returns:
        Dictionary containing summary statistics.
    """
    stats = {}
    
    # Find the threshold that maximizes the difference in pass rates (MOND vs NFW)
    if not df.empty:
        df['diff_rate'] = df['mond_pass_rate'] - df['nfw_pass_rate']
        max_diff_idx = df['diff_rate'].abs().idxmax()
        best_row = df.loc[max_diff_idx]
        
        stats['optimal_threshold'] = best_row['chi2_threshold']
        stats['mond_pass_rate_at_optimal'] = best_row['mond_pass_rate']
        stats['nfw_pass_rate_at_optimal'] = best_row['nfw_pass_rate']
        stats['max_abs_diff'] = best_row['diff_rate']
        
        # Calculate average pass rates across all thresholds
        stats['avg_mond_pass_rate'] = df['mond_pass_rate'].mean()
        stats['avg_nfw_pass_rate'] = df['nfw_pass_rate'].mean()
        
        # Count how many thresholds favor MOND (higher pass rate)
        stats['mond_favored_count'] = (df['mond_pass_rate'] > df['nfw_pass_rate']).sum()
        stats['nfw_favored_count'] = (df['nfw_pass_rate'] > df['mond_pass_rate']).sum()
        
        # Total number of thresholds tested
        stats['total_thresholds'] = len(df)
    else:
        stats['optimal_threshold'] = None
        stats['mond_pass_rate_at_optimal'] = None
        stats['nfw_pass_rate_at_optimal'] = None
        stats['max_abs_diff'] = None
        stats['avg_mond_pass_rate'] = None
        stats['avg_nfw_pass_rate'] = None
        stats['mond_favored_count'] = 0
        stats['nfw_favored_count'] = 0
        stats['total_thresholds'] = 0
    
    return stats

def generate_summary_text(stats: Dict[str, Any], total_galaxies: int) -> str:
    """
    Generates a human-readable text summary of the sensitivity analysis.
    
    Args:
        stats: Dictionary of summary statistics.
        total_galaxies: Total number of galaxies in the dataset.
    
    Returns:
        Formatted string summary.
    """
    lines = []
    lines.append("=" * 70)
    lines.append("SENSITIVITY ANALYSIS SUMMARY")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"Total Galaxies Analyzed: {total_galaxies}")
    lines.append(f"Number of Thresholds Tested: {stats['total_thresholds']}")
    lines.append("")
    lines.append("OVERALL PASS RATE COMPARISON")
    lines.append("-" * 40)
    if stats['avg_mond_pass_rate'] is not None:
        lines.append(f"Average MOND Pass Rate: {stats['avg_mond_pass_rate']:.2%}")
        lines.append(f"Average NFW Pass Rate:  {stats['avg_nfw_pass_rate']:.2%}")
        lines.append("")
        if stats['mond_favored_count'] > stats['nfw_favored_count']:
            lines.append(f"MOND outperformed NFW in {stats['mond_favored_count']} out of {stats['total_thresholds']} thresholds.")
        elif stats['nfw_favored_count'] > stats['mond_favored_count']:
            lines.append(f"NFW outperformed MOND in {stats['nfw_favored_count']} out of {stats['total_thresholds']} thresholds.")
        else:
            lines.append(f"MOND and NFW performed equally across all thresholds.")
    else:
        lines.append("No data available to compute average pass rates.")
    
    lines.append("")
    lines.append("OPTIMAL THRESHOLD ANALYSIS")
    lines.append("-" * 40)
    if stats['optimal_threshold'] is not None:
        lines.append(f"Threshold with Maximum Absolute Difference: {stats['optimal_threshold']:.4f}")
        lines.append(f"  - MOND Pass Rate at Optimal: {stats['mond_pass_rate_at_optimal']:.2%}")
        lines.append(f"  - NFW Pass Rate at Optimal:  {stats['nfw_pass_rate_at_optimal']:.2%}")
        lines.append(f"  - Absolute Difference:       {abs(stats['max_abs_diff']):.2%}")
    else:
        lines.append("No optimal threshold could be determined from the data.")
    
    lines.append("")
    lines.append("CONCLUSION")
    lines.append("-" * 40)
    if stats['avg_mond_pass_rate'] is not None and stats['avg_nfw_pass_rate'] is not None:
        if stats['avg_mond_pass_rate'] > stats['avg_nfw_pass_rate']:
            lines.append("Based on the sensitivity sweep, the MOND model demonstrates a higher")
            lines.append("average goodness-of-fit pass rate across the tested chi-squared thresholds.")
            lines.append("This suggests MOND is more robust to variations in the acceptance criteria.")
        elif stats['avg_nfw_pass_rate'] > stats['avg_mond_pass_rate']:
            lines.append("Based on the sensitivity sweep, the NFW model demonstrates a higher")
            lines.append("average goodness-of-fit pass rate across the tested chi-squared thresholds.")
            lines.append("This suggests NFW is more robust to variations in the acceptance criteria.")
        else:
            lines.append("Both models show equivalent robustness across the tested chi-squared thresholds.")
    else:
        lines.append("Unable to draw a conclusion due to missing data.")
    
    lines.append("")
    lines.append("=" * 70)
    
    return "\n".join(lines)

def write_summary(summary_text: str, path: Optional[Path] = None) -> None:
    """
    Writes the summary text to the specified file path.
    
    Args:
        summary_text: The text content to write.
        path: Optional path for the output file. Defaults to results/sensitivity_summary.txt.
    """
    if path is None:
        path = SENSITIVITY_SUMMARY_PATH
    
    ensure_directory(path.parent)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(summary_text)
    
    logging.info(f"Sensitivity summary written to {path}")

def main() -> int:
    """
    Main entry point for the sensitivity summary generation script.
    
    Returns:
        0 on success, non-zero on failure.
    """
    log_stage("Starting Sensitivity Summary Generation (T035)")
    logger = get_logger(__name__)
    
    try:
        # Load sensitivity data
        logger.info(f"Loading sensitivity data from {SENSITIVITY_DATA_PATH}")
        df = load_sensitivity_data()
        
        # Determine total galaxies from the first row (should be constant)
        total_galaxies = int(df['total_galaxies'].iloc[0])
        
        # Compute summary statistics
        logger.info("Computing summary statistics")
        stats = compute_summary_stats(df)
        
        # Generate summary text
        logger.info("Generating summary text")
        summary_text = generate_summary_text(stats, total_galaxies)
        
        # Write summary to file
        logger.info(f"Writing summary to {SENSITIVITY_SUMMARY_PATH}")
        write_summary(summary_text, SENSITIVITY_SUMMARY_PATH)
        
        logger.info("Sensitivity summary generation completed successfully.")
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"Fatal error: {e}")
        return 1
    except ValueError as e:
        logger.error(f"Data validation error: {e}")
        return 1
    except Exception as e:
        logger.exception(f"Unexpected error during sensitivity summary generation: {e}")
        return 1

if __name__ == "__main__":
    import sys
    sys.exit(main())
