"""
Contract test for statistical report schema (T028).

This test validates that the output of the statistical analysis pipeline
(data/results/stats_report.json) conforms to the expected schema defined
in the project specifications. It ensures that all required fields for
the paired t-test, bootstrap confidence intervals, and associational framing
are present and of the correct type.

This task implements the contract test for User Story 3 (US3).
"""
import json
import os
import pytest
from typing import Any, Dict

# Path relative to project root
STATS_REPORT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "data",
    "results",
    "stats_report.json"
)


def load_stats_report() -> Dict[str, Any]:
    """Load the stats report from disk."""
    if not os.path.exists(STATS_REPORT_PATH):
        pytest.fail(f"Stats report not found at {STATS_REPORT_PATH}. "
                    "Run the analysis pipeline first.")
    with open(STATS_REPORT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


class TestStatsReportSchema:
    """
    Contract tests for the statistical report schema.

    These tests verify the structure, types, and presence of required fields
    in the stats_report.json file generated by the comparative analysis.
    """

    def test_report_exists_and_is_dict(self):
        """Ensure the report is a valid JSON object."""
        report = load_stats_report()
        assert isinstance(report, dict), "Report must be a dictionary"

    def test_top_level_keys_present(self):
        """Verify all required top-level keys exist."""
        report = load_stats_report()
        required_keys = [
            "baseline_summary",
            "quantum_summary",
            "paired_t_test",
            "bootstrap_ci",
            "conclusion_framing",
            "metadata"
        ]
        for key in required_keys:
            assert key in report, f"Missing required top-level key: {key}"

    def test_baseline_summary_schema(self):
        """Validate the baseline model summary structure."""
        report = load_stats_report()
        baseline = report["baseline_summary"]
        assert "mean_accuracy" in baseline
        assert "mean_f1" in baseline
        assert "std_accuracy" in baseline
        assert "std_f1" in baseline
        assert "n_seeds" in baseline
        assert isinstance(baseline["mean_accuracy"], (int, float))
        assert isinstance(baseline["n_seeds"], int)

    def test_quantum_summary_schema(self):
        """Validate the quantum model summary structure."""
        report = load_stats_report()
        quantum = report["quantum_summary"]
        assert "mean_accuracy" in quantum
        assert "mean_f1" in quantum
        assert "std_accuracy" in quantum
        assert "std_f1" in quantum
        assert "n_seeds" in quantum
        assert isinstance(quantum["mean_accuracy"], (int, float))

    def test_paired_t_test_schema(self):
        """Validate the paired t-test results structure."""
        report = load_stats_report()
        t_test = report["paired_t_test"]
        required_fields = [
            "t_statistic",
            "p_value",
            "cohen_d",
            "confidence_level",
            "significant_at_005"
        ]
        for field in required_fields:
            assert field in t_test, f"Missing t-test field: {field}"

        assert isinstance(t_test["t_statistic"], (int, float))
        assert isinstance(t_test["p_value"], (int, float))
        assert 0 <= t_test["p_value"] <= 1, "p-value must be between 0 and 1"
        assert isinstance(t_test["cohen_d"], (int, float))
        assert isinstance(t_test["significant_at_005"], bool)

    def test_bootstrap_ci_schema(self):
        """Validate the bootstrap confidence interval structure."""
        report = load_stats_report()
        bootstrap = report["bootstrap_ci"]
        assert "mean_difference" in bootstrap
        assert "ci_lower" in bootstrap
        assert "ci_upper" in bootstrap
        assert "n_iterations" in bootstrap
        assert "confidence_level" in bootstrap

        assert isinstance(bootstrap["mean_difference"], (int, float))
        assert isinstance(bootstrap["ci_lower"], (int, float))
        assert isinstance(bootstrap["ci_upper"], (int, float))
        assert bootstrap["ci_lower"] <= bootstrap["ci_upper"], \
            "CI lower bound must be <= upper bound"

    def test_conclusion_framing_schema(self):
        """
        Validate the conclusion framing section.
        
        Ensures FR-006 compliance: results are framed as "associational improvements"
        and avoid causal claims.
        """
        report = load_stats_report()
        framing = report["conclusion_framing"]
        
        assert "summary_text" in framing, "Missing summary_text in framing"
        assert "framings" in framing, "Missing framings list in framing"
        
        summary = framing["summary_text"]
        assert isinstance(summary, str) and len(summary) > 0
        
        # Check for FR-006 compliance keywords
        # We assert that causal language is NOT present, and associational language IS
        assert "causal" not in summary.lower(), "Framing should not claim causality"
        assert "association" in summary.lower() or "correlation" in summary.lower(), \
            "Framing must use associational language"
        
        assert isinstance(framing["framings"], list)
        assert len(framing["framings"]) > 0

    def test_metadata_schema(self):
        """Validate the metadata section."""
        report = load_stats_report()
        meta = report["metadata"]
        
        required_meta = ["experiment_date", "seeds_used", "framework_version"]
        for key in required_meta:
            assert key in meta, f"Missing metadata key: {key}"
        
        assert isinstance(meta["seeds_used"], list)
        assert len(meta["seeds_used"]) > 0

    def test_consistency_across_sections(self):
        """
        Verify consistency between summary stats and t-test inputs.
        
        Ensures that the number of seeds matches across sections.
        """
        report = load_stats_report()
        
        n_baseline = report["baseline_summary"]["n_seeds"]
        n_quantum = report["quantum_summary"]["n_seeds"]
        n_meta = len(report["metadata"]["seeds_used"])
        
        assert n_baseline == n_quantum, \
            "Number of seeds must match between baseline and quantum summaries"
        assert n_baseline == n_meta, \
            "Number of seeds must match metadata seeds list"