"""
Sensitivity Analysis Module for Visual Search Strategies Project.

This module implements the sensitivity analysis for the exploratory cluster-based approach.
It fits descriptive LMMs using cluster labels (k=2, k=3) and reports coefficient variance.
"""
import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple

import pandas as pd
import numpy as np
import yaml
import statsmodels.formula.api as smf
from statsmodels.regression.mixed_linear_model import MixedLM

from config import get_config
from utils.logging import get_logger

# Ensure the parent directory is in the path for imports if running as script
if __package__ is None:
    sys.path.insert(0, str(Path(__file__).parent.parent))

def get_logger_wrapper(name: str = __name__) -> logging.Logger:
    """Get a logger instance configured for this module."""
    return get_logger(name)

def load_cluster_labels(k: int, logger: Optional[logging.Logger] = None) -> pd.DataFrame:
    """
    Load cluster labels generated by sensitivity clustering task (T024b).

    Args:
        k: Number of clusters (2 or 3).
        logger: Logger instance.

    Returns:
        DataFrame with participant IDs and cluster labels.
    """
    config = get_config()
    labels_path = config.PROCESSED_DATA_DIR / f"labels_k{k}.csv"

    if logger:
        logger.info(f"Loading cluster labels from {labels_path}")

    if not labels_path.exists():
        raise FileNotFoundError(f"Cluster labels file not found: {labels_path}")

    return pd.read_csv(labels_path)

def load_processed_features(logger: Optional[logging.Logger] = None) -> pd.DataFrame:
    """
    Load the processed features dataset containing detection times and covariates.

    Returns:
        DataFrame with features.
    """
    config = get_config()
    features_path = config.PROCESSED_DATA_DIR / "features.csv"

    if logger:
        logger.info(f"Loading processed features from {features_path}")

    if not features_path.exists():
        raise FileNotFoundError(f"Features file not found: {features_path}")

    return pd.read_csv(features_path)

def fit_descriptive_lmm(data: pd.DataFrame, cluster_col: str, outcome: str = "detection_time",
                        group_col: str = "participant_id", logger: Optional[logging.Logger] = None) -> Dict[str, Any]:
    """
    Fit a Linear Mixed-Effects Model using cluster labels as a fixed effect.
    This is for descriptive/exploratory purposes only (T029b logic applied to sensitivity).

    Args:
        data: DataFrame with data.
        cluster_col: Name of the column containing cluster labels.
        outcome: Name of the outcome variable.
        group_col: Name of the grouping variable (random effect).
        logger: Logger instance.

    Returns:
        Dictionary containing model results (coefficients, p-values, etc.).
    """
    if logger:
        logger.info(f"Fitting descriptive LMM with cluster '{cluster_col}' as predictor")

    # Ensure cluster column is treated as categorical
    data[cluster_col] = data[cluster_col].astype("category")

    # Formula: outcome ~ cluster + (1|group)
    formula = f"{outcome} ~ C({cluster_col})"
    try:
        model = smf.mixedlm(formula, data, groups=data[group_col])
        result = model.fit(maxiter=1000)

        if logger:
            logger.info(f"Model converged: {result.converged}")

        # Extract coefficients table
        summary = result.summary()
        # Parse summary to get coefficients and p-values
        # statsmodels summary is text, easier to access params and pvalues directly
        params = result.params
        pvalues = result.pvalues

        results_dict = {
            "formula": formula,
            "converged": result.converged,
            "coefficients": params.to_dict(),
            "p_values": pvalues.to_dict(),
            "log_likelihood": result.llf,
            "aic": result.aic,
            "bic": result.bic,
            "random_effects_variance": result.cov_re.iloc[0, 0] if result.cov_re is not None else None
        }

        return results_dict

    except Exception as e:
        if logger:
            logger.error(f"Failed to fit LMM for cluster {cluster_col}: {e}")
        return {
            "formula": formula,
            "converged": False,
            "error": str(e),
            "coefficients": {},
            "p_values": {}
        }

def run_sensitivity_analysis(k_values: List[int] = [2, 3], logger: Optional[logging.Logger] = None) -> Dict[str, Any]:
    """
    Run the full sensitivity analysis by fitting LMMs for different k values.

    Args:
        k_values: List of k values to test (default [2, 3]).
        logger: Logger instance.

    Returns:
        Dictionary containing the full sensitivity analysis report.
    """
    if logger is None:
        logger = get_logger(__name__)

    logger.info("Starting Sensitivity Analysis")

    # Load base features
    try:
        features_df = load_processed_features(logger)
    except FileNotFoundError as e:
        logger.error(str(e))
        return {"error": str(e), "status": "failed"}

    analysis_results = {}
    coefficient_variances = []

    for k in k_values:
        logger.info(f"Processing k={k}")
        try:
            # Load labels for this k
            labels_df = load_cluster_labels(k, logger)

            # Merge with features
            # Assuming labels_df has 'participant_id' and 'cluster_k{K}' column or similar
            # Based on T024b, it likely saves 'cluster' column. Let's assume standard column name 'cluster'
            # or 'cluster_k{K}'. We need to be careful.
            # Let's assume the column is named 'cluster' in the saved file for simplicity,
            # or we rename it.
            
            # Check column name
            cluster_col_name = None
            for col in labels_df.columns:
                if 'cluster' in col.lower():
                    cluster_col_name = col
                    break
            
            if not cluster_col_name:
                logger.warning(f"No cluster column found in labels_k{k}.csv. Skipping k={k}")
                continue

            # Merge
            merged_df = features_df.merge(labels_df[[ 'participant_id', cluster_col_name ]], on='participant_id', how='inner')

            if merged_df.empty:
                logger.warning(f"No overlapping data for k={k}. Skipping.")
                continue

            # Fit model
            model_results = fit_descriptive_lmm(
                merged_df, 
                cluster_col_name, 
                outcome="detection_time",
                group_col="participant_id",
                logger=logger
            )

            analysis_results[f"k_{k}"] = model_results

            # Calculate coefficient variance for the cluster effect (excluding intercept)
            if not model_results.get("error"):
                coeffs = model_results.get("coefficients", {})
                # Filter out intercept if present
                cluster_coeffs = [v for k_key, v in coeffs.items() if "C" in k_key and "cluster" in k_key.lower()]
                if cluster_coeffs:
                  variance = np.var(cluster_coeffs)
                  coefficient_variances.append(variance)
                  logger.info(f"Variance of cluster coefficients for k={k}: {variance:.4f}")

        except Exception as e:
            logger.error(f"Error processing k={k}: {e}")
            analysis_results[f"k_{k}"] = {"error": str(e), "status": "failed"}

    # Summary statistics
    summary = {
        "k_values_tested": k_values,
        "coefficient_variances": coefficient_variances,
        "mean_variance": np.mean(coefficient_variances) if coefficient_variances else None,
        "std_variance": np.std(coefficient_variances) if coefficient_variances else None,
        "stability_assessment": "Stable" if (coefficient_variances and np.std(coefficient_variances) < 0.1) else "Unstable",
        "status": "completed"
    }

    return {
        "summary": summary,
        "details": analysis_results
    }

def save_sensitivity_report(report: Dict[str, Any], output_path: Optional[Path] = None, logger: Optional[logging.Logger] = None) -> Path:
    """
    Save the sensitivity analysis report to a YAML file.

    Args:
        report: The report dictionary.
        output_path: Path to save the file. If None, uses config default.
        logger: Logger instance.

    Returns:
        Path to the saved file.
    """
    config = get_config()
    if output_path is None:
        output_path = config.RESULTS_DIR / "sensitivity_report.yaml"

    # Ensure directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        yaml.dump(report, f, default_flow_style=False, sort_keys=False)

    if logger:
        logger.info(f"Sensitivity report saved to {output_path}")

    return output_path

def main():
    """Main entry point for running the sensitivity analysis."""
    logger = get_logger(__name__)
    logger.info("Running Sensitivity Analysis (T026)")

    try:
        # Run analysis
        report = run_sensitivity_analysis(k_values=[2, 3], logger=logger)

        # Save report
        saved_path = save_sensitivity_report(report, logger=logger)

        logger.info(f"Sensitivity analysis completed successfully. Report: {saved_path}")
        return 0

    except Exception as e:
        logger.error(f"Sensitivity analysis failed: {e}", exc_info=True)
        return 1

if __name__ == "__main__":
    sys.exit(main())