"""Create project layout and update README with a directory tree.

This script is idempotent: running it multiple times will not raise errors.
It creates the required top-level directories (``src``, ``tests``, ``data``,
``config``, ``docs``, ``contracts``) and writes a short tree listing into
``README.md`` at the repository root.

As durable evidence of the layout, it also writes ``docs/project_layout.txt``
containing the tree listing and an explicit per-directory existence check,
so a reviewer can verify the directories were actually created.
"""

import os
from datetime import datetime, timezone
from pathlib import Path

def create_directories(base_path: Path) -> None:
    """Create the required project directories under ``base_path``."""
    dirs = [
        "src",
        "tests",
        "data",
        "config",
        "docs",
        "contracts",
    ]
    for d in dirs:
        dir_path = base_path / d
        dir_path.mkdir(parents=True, exist_ok=True)

def generate_tree_listing(base_path: Path) -> str:
    """Return a short tree representation of the top-level layout."""
    # Only list the immediate children required by the task.
    entries = [
        "src/",
        "tests/",
        "data/",
        "config/",
        "docs/",
        "contracts/",
    ]
    tree = "project_root/\n"
    for i, entry in enumerate(entries):
        connector = "└─ " if i == len(entries) - 1 else "├─ "
        tree += f"{connector}{entry}\n"
    return tree

def update_readme(base_path: Path) -> None:
    """Write a README.md containing a brief description and the tree."""
    readme_path = base_path / "README.md"
    tree = generate_tree_listing(base_path)
    content = (
        "# Project Overview\n\n"
        "This repository implements the **Binding Problem in LLMs** project.\n\n"
        "## Directory Layout\n\n"
        "The top-level structure is created automatically by the setup script:\n\n"
        "```\n"
        f"{tree}"
        "```\n"
    )
    readme_path.write_text(content, encoding="utf-8")

def write_layout_manifest(base_path: Path) -> None:
    """Write a durable evidence file listing the created directories.

    The manifest records, for each required directory, whether it exists
    on disk (and whether it is a directory), plus the generated tree
    listing. This gives reviewers verifiable proof of the layout.
    """
    docs_dir = base_path / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = docs_dir / "project_layout.txt"

    required_dirs = ["src", "tests", "data", "config", "docs", "contracts"]
    lines = [
        "Project layout manifest (generated by code/create_project_layout.py)",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        f"Base path: {base_path}",
        "",
        "Directory existence check:",
    ]
    all_ok = True
    for d in required_dirs:
        p = base_path / d
        exists = p.exists() and p.is_dir()
        all_ok = all_ok and exists
        lines.append(f"  {'OK ' if exists else 'MISSING'} {d}/")
    lines += [
        "",
        "Tree listing:",
        generate_tree_listing(base_path),
        f"All required directories present: {all_ok}",
    ]
    manifest_path.write_text("\n".join(lines), encoding="utf-8")

    if not all_ok:
        missing = [d for d in required_dirs if not (base_path / d).is_dir()]
        raise RuntimeError(
            f"Layout verification failed; missing directories: {missing}"
        )

def main() -> None:
    """Entry point for the script."""
    repo_root = Path(__file__).resolve().parents[1]  # project root
    create_directories(repo_root)
    update_readme(repo_root)
    write_layout_manifest(repo_root)
    print(f"Project layout created and verified under {repo_root}")
    print(f"Evidence manifest written to {repo_root / 'docs' / 'project_layout.txt'}")

if __name__ == "__main__":
    main()