"""
Validation script for Conflict Detector (US1).

Runs the conflict detector on the synthetic dataset generated by T005
and calculates Precision, Recall, and F1-Score to verify the >= 80% baseline.

Output: Prints metrics to stdout and writes a summary to data/processed/validation_results.json
"""
import json
import os
import sys
import csv
from pathlib import Path
from typing import List, Dict, Any, Tuple

# Add project root to path for imports
project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(project_root / "code"))

from src.heuristics.conflict_detector import ConflictDetector
from src.utils.logging import get_logger
from src.utils.seeding import set_deterministic_seed

# Constants
SYNTHETIC_PAIRS_PATH = "data/raw/synthetic_pairs.json"
OUTPUT_RESULTS_PATH = "data/processed/validation_results.json"
THRESHOLD_DEFAULT = 0.90

logger = get_logger(__name__)

def load_synthetic_pairs(path: str) -> List[Dict[str, Any]]:
    """Load the synthetic pairs dataset generated by T005."""
    full_path = project_root / path
    if not full_path.exists():
        raise FileNotFoundError(f"Synthetic pairs dataset not found at {full_path}. "
                                "Please ensure T005 (synthetic_pairs.py) has been run.")
    
    with open(full_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def calculate_metrics(predictions: List[bool], ground_truth: List[bool]) -> Dict[str, float]:
    """Calculate Precision, Recall, F1, and Accuracy."""
    if not predictions or not ground_truth:
        return {
            "precision": 0.0,
            "recall": 0.0,
            "f1_score": 0.0,
            "accuracy": 0.0,
            "total_samples": 0
        }

    tp = fp = tn = fn = 0

    for pred, truth in zip(predictions, ground_truth):
        if pred and truth:
            tp += 1
        elif pred and not truth:
            fp += 1
        elif not pred and truth:
            fn += 1
        else:
            tn += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    accuracy = (tp + tn) / len(predictions)

    return {
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "accuracy": accuracy,
        "total_samples": len(predictions),
        "true_positives": tp,
        "false_positives": fp,
        "true_negatives": tn,
        "false_negatives": fn
    }

def run_validation(threshold: float = THRESHOLD_DEFAULT) -> Dict[str, Any]:
    """
    Main validation logic.
    1. Load data.
    2. Initialize detector.
    3. Run inference.
    4. Calculate metrics.
    5. Return results.
    """
    set_deterministic_seed(42)
    
    logger.info(f"Loading synthetic pairs from {SYNTHETIC_PAIRS_PATH}")
    data = load_synthetic_pairs(SYNTHETIC_PAIRS_PATH)
    
    if not data:
        raise ValueError("Synthetic pairs dataset is empty.")

    logger.info(f"Initialized ConflictDetector with threshold {threshold}")
    detector = ConflictDetector(threshold=threshold)
    
    predictions = []
    ground_truth = []
    
    logger.info(f"Running inference on {len(data)} pairs...")
    for i, item in enumerate(data):
        patch_a = item.get("patch_a", "")
        patch_b = item.get("patch_b", "")
        is_contradiction = item.get("is_contradiction", False)
        
        # Predict
        # The detector returns a boolean based on the threshold
        pred = detector.is_conflict(patch_a, patch_b)
        
        predictions.append(pred)
        ground_truth.append(is_contradiction)

    metrics = calculate_metrics(predictions, ground_truth)
    
    return {
        "threshold_used": threshold,
        "metrics": metrics,
        "status": "passed" if metrics["precision"] >= 0.80 and metrics["recall"] >= 0.80 else "failed"
    }

def save_results(results: Dict[str, Any], output_path: str):
    """Save results to JSON."""
    full_path = project_root / output_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(full_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2)
    logger.info(f"Results saved to {full_path}")

def main():
    """Entry point for the validation script."""
    logger.info("Starting Conflict Detector Validation (T016)")
    
    try:
        results = run_validation()
        
        metrics = results["metrics"]
        logger.info("-" * 40)
        logger.info("VALIDATION RESULTS")
        logger.info("-" * 40)
        logger.info(f"Total Samples: {metrics['total_samples']}")
        logger.info(f"Precision: {metrics['precision']:.4f}")
        logger.info(f"Recall:    {metrics['recall']:.4f}")
        logger.info(f"F1-Score:  {metrics['f1_score']:.4f}")
        logger.info(f"Accuracy:  {metrics['accuracy']:.4f}")
        logger.info("-" * 40)
        
        if results["status"] == "passed":
            logger.info("SUCCESS: Baseline >= 80% Precision/Recall achieved.")
        else:
            logger.warning("FAILURE: Baseline >= 80% Precision/Recall NOT achieved.")
        
        save_results(results, OUTPUT_RESULTS_PATH)
        
        # Exit with appropriate code for CI
        if results["status"] == "failed":
            sys.exit(1)
        else:
            sys.exit(0)

    except Exception as e:
        logger.error(f"Validation failed with error: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()
