import os
import sys
import time
import logging
import json
import csv
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add project root to path if running as script
if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent.parent
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

from strategies.lazy import LazyTraversal
from data_loader import load_noisy_graphs
from runner import run_batch, save_results_to_csv, TimeoutError
from config import get_model_path
import networkx as nx

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Output paths per task specification
OUTPUT_DIR = Path("data/processed")
RESULTS_FILE = OUTPUT_DIR / "noisy_lazy_results.csv"
GRAPHS_FILE = Path("data/processed/graphs/graph_noise_42.json")

def ensure_output_dirs():
    """Ensure the output directory exists."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def load_tasks(graph_path: Optional[Path] = None) -> List[Dict[str, Any]]:
    """
    Load tasks and their associated noisy memory graphs.
    
    This function loads the synthetic noisy graph dataset generated in T011
    (graph_noise_42.json) and pairs it with the LoCoMo benchmark tasks.
    Since the noisy graph is a single aggregated graph representing the
    noisy memory structure, we load the tasks from the raw data loader
    and attach the graph to each task for processing.
    
    Returns:
        List of task dictionaries with 'graph' key attached.
    """
    if graph_path is None:
        graph_path = GRAPHS_FILE
    
    if not graph_path.exists():
        raise FileNotFoundError(
            f"Noisy graph file not found at {graph_path}. "
            "Run T011 (data_loader.py --generate-graphs) first."
        )

    # Load the noisy graph
    logger.info(f"Loading noisy graph from {graph_path}")
    noisy_graph = load_noisy_graphs(graph_path)
    
    if not isinstance(noisy_graph, nx.DiGraph):
        # If loaded as dict, reconstruct graph if needed, or assume it's the graph object
        # The data_loader.save_noisy_graphs saves a dict with 'graph' key usually, 
        # but load_noisy_graphs should return the graph or the dict. 
        # Let's handle the dict case from the loader if it returns { 'graph': nx.Graph, ... }
        if isinstance(noisy_graph, dict) and 'graph' in noisy_graph:
            noisy_graph = noisy_graph['graph']
        else:
            # Fallback: try to load as json and reconstruct if necessary
            # But assuming load_noisy_graphs returns the graph object or dict with it
            raise ValueError(f"Invalid noisy graph format loaded from {graph_path}")

    # Load the raw tasks (LoCoMo subset)
    # We need to re-fetch the tasks to pair with the graph. 
    # Since we are running on the noisy graph which is a synthetic modification 
    # of the memory structure derived from the tasks, we assume the tasks 
    # are the same set used to generate the graph, or a representative subset.
    # To be safe and reproducible, we load the tasks from the raw data file 
    # if it exists, or re-download a small subset if strictly necessary.
    # However, T011 generates the graph from the tasks. 
    # We will load the tasks from the raw data file generated by T011 if available,
    # or re-use the data_loader to fetch the same subset.
    
    # For this runner, we assume the tasks are available in data/processed/raw_tasks.json
    # or we fetch a small subset again to ensure we have the tasks to run against.
    raw_tasks_path = Path("data/processed/raw_tasks.json")
    tasks = []
    
    if raw_tasks_path.exists():
        logger.info(f"Loading tasks from {raw_tasks_path}")
        with open(raw_tasks_path, 'r') as f:
            tasks = json.load(f)
    else:
        # Fallback: fetch a small subset to run against the noisy graph
        # This ensures the runner can execute even if raw tasks file is missing
        # but strictly speaking, the graph was built from specific tasks.
        logger.warning(f"Raw tasks file not found at {raw_tasks_path}. Fetching a small subset.")
        from data_loader import fetch_locomo_dataset
        tasks = fetch_locomo_dataset(subset=10) # Small subset for testing/noisy run

    # Attach the noisy graph to each task
    # In a real scenario, each task might have its own subgraph, but the T011 spec
    # generates a single "synthetic noisy graph dataset" (graph_noise_42.json).
    # We will attach this global noisy graph to all tasks for the purpose of
    # running the traversal strategy on the noisy environment.
    for task in tasks:
        task['memory_graph'] = noisy_graph
    
    logger.info(f"Loaded {len(tasks)} tasks with noisy graph attached.")
    return tasks

def evaluate_task(task: Dict[str, Any], strategy: LazyTraversal) -> Dict[str, Any]:
    """
    Evaluate a single task using the Lazy strategy on the noisy graph.
    
    Args:
        task: Dictionary containing task details (question, context, answer) and memory_graph.
        strategy: The LazyTraversal instance to use.
        
    Returns:
        Dictionary with task_id, accuracy, nodes_visited, latency_ms.
    """
    task_id = task.get('task_id', f"task_{hash(str(task)) % 10000}")
    question = task.get('question', '')
    context = task.get('context', '')
    expected_answer = task.get('answer', '')
    memory_graph = task.get('memory_graph')
    
    if memory_graph is None:
        logger.error(f"Task {task_id} has no memory graph attached.")
        return {
            'task_id': task_id,
            'accuracy': 0.0,
            'nodes_visited': 0,
            'latency_ms': 0.0,
            'error': 'Missing memory graph'
        }

    start_time = time.time()
    
    try:
        # Run the traversal strategy
        # The strategy needs to traverse the graph to reconstruct memory
        # and then answer the question.
        # We assume the strategy's run method handles the LLM inference internally
        # or we pass the graph and question to it.
        # Based on the API surface, strategy.run() likely takes the graph and query.
        
        # Note: The actual implementation of FullTraversal/LazyTraversal in
        # strategies/full.py and strategies/lazy.py is assumed to handle
        # the graph traversal and LLM interaction.
        
        # We call the strategy's traversal method.
        # Assuming the strategy is initialized with the graph or passed it.
        # Let's assume the strategy.run(graph, query) pattern or similar.
        # Looking at the API: strategies.base.BaseTraversal.
        # We'll assume the strategy has a method `traverse` or `run`.
        # For this implementation, we'll simulate the call based on typical patterns
        # if the exact method signature isn't clear, but we must use the real classes.
        
        # Let's assume the strategy is instantiated with config and then run.
        # We'll create a fresh instance or use the passed one.
        # The passed 'strategy' is already initialized.
        
        # We need to call the strategy on the graph.
        # Assuming: result = strategy.run(memory_graph, question)
        # If the strategy expects the graph in __init__, we might need to adapt.
        # Given the constraints, we will assume the strategy's `run` method
        # takes the graph and the query.
        
        # If the strategy doesn't take the graph in run, we might need to
        # set it. But for this task, we assume the strategy is designed to
        # accept the graph as an argument or is bound to it.
        # Let's assume the standard pattern: strategy.traverse(graph, query)
        
        # We'll try to call `run` or `traverse`. If it fails, we log and return error.
        result = None
        if hasattr(strategy, 'run'):
            result = strategy.run(memory_graph, question)
        elif hasattr(strategy, 'traverse'):
            result = strategy.traverse(memory_graph, question)
        else:
            raise AttributeError("Strategy has no 'run' or 'traverse' method.")
        
        # Extract metrics from result
        # Assuming result is a dict with 'answer', 'nodes_visited', etc.
        # Or we calculate accuracy manually.
        
        end_time = time.time()
        latency_ms = (end_time - start_time) * 1000
        
        # Calculate accuracy (simple string match or semantic similarity if available)
        # For now, simple string match or partial match
        actual_answer = result.get('answer', '') if isinstance(result, dict) else str(result)
        accuracy = 0.0
        if expected_answer and actual_answer:
            # Simple heuristic: check if expected answer is in actual answer
            if expected_answer.lower() in actual_answer.lower():
                accuracy = 1.0
            else:
                # Fallback: check overlap
                expected_words = set(expected_answer.lower().split())
                actual_words = set(actual_answer.lower().split())
                if expected_words & actual_words:
                    accuracy = 0.5 # Partial credit
        
        nodes_visited = result.get('nodes_visited', 0) if isinstance(result, dict) else 0
        
        return {
            'task_id': task_id,
            'accuracy': accuracy,
            'nodes_visited': nodes_visited,
            'latency_ms': latency_ms
        }
        
    except TimeoutError as e:
        logger.warning(f"Task {task_id} timed out.")
        return {
            'task_id': task_id,
            'accuracy': 0.0,
            'nodes_visited': 0,
            'latency_ms': (time.time() - start_time) * 1000,
            'error': 'Timeout'
        }
    except Exception as e:
        logger.error(f"Error evaluating task {task_id}: {e}", exc_info=True)
        return {
            'task_id': task_id,
            'accuracy': 0.0,
            'nodes_visited': 0,
            'latency_ms': (time.time() - start_time) * 1000,
            'error': str(e)
        }

def main():
    """
    Main entry point for the noisy lazy execution runner.
    Runs the Lazy strategy on the noisy graph dataset and saves results.
    """
    ensure_output_dirs()
    
    # Initialize the Lazy strategy
    # We assume the strategy can be initialized with default config
    # or we pass the model path from config.
    model_path = get_model_path()
    logger.info(f"Using model path: {model_path}")
    
    strategy = LazyTraversal()
    
    # Load tasks with noisy graph
    tasks = load_tasks()
    
    if not tasks:
        logger.error("No tasks loaded. Exiting.")
        sys.exit(1)
    
    logger.info(f"Starting evaluation of {len(tasks)} tasks with Lazy strategy on noisy graph.")
    
    # Run batch evaluation
    # We use the run_batch helper from runner.py
    results = run_batch(
        tasks=tasks,
        evaluate_func=lambda t: evaluate_task(t, strategy),
        chunk_size=10, # Process in small chunks
        timeout_per_task=300 # 5 minutes per task
    )
    
    # Save results to CSV
    save_results_to_csv(results, RESULTS_FILE)
    logger.info(f"Results saved to {RESULTS_FILE}")
    
    # Log summary
    total_tasks = len(results)
    successful = sum(1 for r in results if r.get('error') is None)
    avg_accuracy = sum(r['accuracy'] for r in results) / total_tasks if total_tasks > 0 else 0.0
    avg_latency = sum(r['latency_ms'] for r in results) / total_tasks if total_tasks > 0 else 0.0
    
    logger.info(f"Completed: {successful}/{total_tasks} tasks. Avg Accuracy: {avg_accuracy:.4f}, Avg Latency: {avg_latency:.2f}ms")

if __name__ == "__main__":
    main()
