"""
Generate VDOS Retention Report for topological-only analysis.

This module reads the filtered configuration IDs and VDOS availability status
to generate a report listing configurations that are retained despite missing VDOS.
This report confirms retention, NOT exclusion, for Structure-Only mode analysis.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional

from config.env_config import get_processed_dir
from logging_config import get_logger

logger = get_logger(__name__)


def load_filtered_config_ids(processed_dir: Path) -> List[str]:
    """
    Load the list of filtered configuration IDs from the previous step.

    Args:
        processed_dir: Path to the data/processed directory.

    Returns:
        List of configuration IDs to process.
    """
    filtered_path = processed_dir / "filtered_config_ids.json"
    if not filtered_path.exists():
        raise FileNotFoundError(
            f"Filtered config IDs file not found at {filtered_path}. "
            "Ensure T024b (Execute Filter) has been run successfully."
        )

    with open(filtered_path, "r") as f:
        data = json.load(f)

    return data.get("config_ids", [])


def load_vdos_missing_status(processed_dir: Path) -> Dict[str, str]:
    """
    Load the VDOS missing status flags from the descriptors processing step.

    This function reads the internal flags generated by the filter_and_fallback
    logic in T024a/T024b to identify which configs are VDOS-MISSING.

    Args:
        processed_dir: Path to the data/processed directory.

    Returns:
        Dictionary mapping config_id to status string (e.g., "VDOS-MISSING").
    """
    # The status is typically stored in a temporary state or a specific report
    # generated by the filter step. Based on the pipeline flow, we check for
    # a specific status file or read from the main descriptors metadata if available.
    # Since T024b outputs 'filtered_config_ids.json' and internal flags, we assume
    # the status is tracked in a companion file or we re-evaluate availability.
    # However, per task T024b description, it outputs 'internal flags for VDOS status'.
    # We will look for a specific status file that T024b should have created,
    # or if not, we assume the 'vdos_missing_report.json' from T024a execution context.

    status_path = processed_dir / "vdos_missing_status.json"
    if status_path.exists():
        with open(status_path, "r") as f:
            return json.load(f)

    # Fallback: Check if T024a created a specific report
    missing_report_path = processed_dir / "vdos_missing_report.json"
    if missing_report_path.exists():
        with open(missing_report_path, "r") as f:
            data = json.load(f)
            # Map config_id to status
            return {item["id"]: item["status"] for item in data.get("missing_configs", [])}

    # If no explicit status file exists, we must assume we need to re-check or
    # the previous step T024b did not persist the status correctly.
    # For robustness, we return an empty dict and log a warning, but the task
    # implies the data exists from T024b.
    logger.warning(f"VDOS status file not found at {status_path} or {missing_report_path}. "
                   "Assuming no VDOS-MISSING flags found in previous step.")
    return {}


def generate_retention_report(
    config_ids: List[str],
    vdos_status: Dict[str, str]
) -> Dict[str, List[Dict[str, str]]]:
    """
    Generate the retention report structure.

    Args:
        config_ids: List of all filtered config IDs.
        vdos_status: Dictionary mapping config_id to VDOS status.

    Returns:
        Dictionary with 'retained_configs' list.
    """
    retained = []
    for config_id in config_ids:
        status = vdos_status.get(config_id)
        if status == "VDOS-MISSING":
            retained.append({
                "id": config_id,
                "status": "VDOS-MISSING",
                "reason": "VDOS data not found in metadata; retained for topological-only analysis (Structure-Only Mode)."
            })

    return {
        "retained_configs": retained
    }


def save_retention_report(
    report: Dict[str, List[Dict[str, str]]],
    output_path: Path
) -> None:
    """
    Save the retention report to a JSON file.

    Args:
        report: The retention report dictionary.
        output_path: Path to save the report.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(report, f, indent=2)
    logger.info(f"VDOS Retention Report saved to {output_path}")


def main() -> None:
    """
    Main entry point to generate the VDOS Retention Report.
    """
    processed_dir = get_processed_dir()
    output_path = processed_dir / "vdos_retention_report.json"

    logger.info(f"Starting VDOS Retention Report generation in {processed_dir}")

    try:
        # 1. Load filtered config IDs (from T024b)
        config_ids = load_filtered_config_ids(processed_dir)
        logger.info(f"Loaded {len(config_ids)} filtered configuration IDs.")

        # 2. Load VDOS missing status (from T024a/T024b internal flags)
        vdos_status = load_vdos_missing_status(processed_dir)
        logger.info(f"Loaded VDOS status for {len(vdos_status)} configurations.")

        # 3. Generate report
        report = generate_retention_report(config_ids, vdos_status)
        retained_count = len(report["retained_configs"])
        logger.info(f"Identified {retained_count} configurations with missing VDOS for retention.")

        # 4. Save report
        save_retention_report(report, output_path)

        logger.info("VDOS Retention Report generation completed successfully.")

    except FileNotFoundError as e:
        logger.error(f"Required input file missing: {e}")
        raise
    except Exception as e:
        logger.error(f"Error generating VDOS Retention Report: {e}")
        raise


if __name__ == "__main__":
    main()
