"""
Bias check analysis for excluded entries.
Analyzes exclusion logs to identify potential biases in the dataset filtering process.
"""
import os
import json
import logging
import argparse
from pathlib import Path
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, asdict

from utils.logger import get_logger, log_bias_check

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

@dataclass
class ExclusionReason:
    material_id: str
    reason: str
    category: str
    family_id: Optional[str] = None

@dataclass
class BiasReport:
    summary: Dict[str, int]
    total_excluded: int
    report: List[Dict[str, Any]]
    small_families: List[str]
    warnings: List[str]

def load_exclusion_log(input_path: Path) -> List[ExclusionReason]:
    """Load exclusion log from JSON file.
    
    Args:
        input_path: Path to the exclusion log JSON file.
        
    Returns:
        List of ExclusionReason objects.
        
    Raises:
        FileNotFoundError: If the input file does not exist.
        json.JSONDecodeError: If the file is not valid JSON.
        IsADirectoryError: If the input path is a directory.
    """
    if input_path.is_dir():
        raise IsADirectoryError(f"Input path is a directory: {input_path}. "
                                "Expected a file path to an exclusion log (e.g., exclusion_log.json).")
        
    if not input_path.exists():
        raise FileNotFoundError(f"Exclusion log not found at {input_path}. "
                              "Ensure the pipeline has run and generated exclusion logs.")
    
    with open(input_path, "r") as f:
        data = json.load(f)
    
    if not isinstance(data, list):
        raise ValueError(f"Expected list of exclusion reasons in {input_path}, got {type(data)}")
    
    return [ExclusionReason(**item) for item in data]

def analyze_exclusion_bias(exclusion_reasons: List[ExclusionReason]) -> BiasReport:
    """Analyze the bias in excluded entries.
    
    Args:
        exclusion_reasons: List of ExclusionReason objects from filtering.
        
    Returns:
        BiasReport containing summary statistics and warnings.
    """
    category_counts: Dict[str, int] = {}
    detailed_report = []
    family_counts: Dict[str, int] = {}
    warnings = []

    for reason in exclusion_reasons:
        # Count by category
        category_counts[reason.category] = category_counts.get(reason.category, 0) + 1
        
        # Track family occurrences
        if reason.family_id:
            family_counts[reason.family_id] = family_counts.get(reason.family_id, 0) + 1

        # Add to detailed report
        detailed_report.append({
            "material_id": reason.material_id,
            "reason": reason.reason,
            "category": reason.category,
            "family_id": reason.family_id
        })

    # Identify small families (families with very few excluded entries might indicate bias)
    # Threshold: families with < 2 excluded entries are flagged as "small"
    small_families = [fam for fam, count in family_counts.items() if count < 2]

    # Generate warnings for significant biases
    if category_counts:
        max_category = max(category_counts, key=category_counts.get)
        max_count = category_counts[max_category]
        total = sum(category_counts.values())
        
        if total > 0:
            ratio = max_count / total
            if ratio > 0.8:
                warnings.append(f"High bias detected: {max_category} accounts for {ratio:.1%} of exclusions.")
    
    if not exclusion_reasons:
        warnings.append("No exclusions found. Verify that filtering is active.")

    report = BiasReport(
        summary=category_counts,
        total_excluded=len(exclusion_reasons),
        report=detailed_report,
        small_families=small_families,
        warnings=warnings
    )

    # Log bias check results using the project logger
    log_bias_check(report.summary)

    return report

def write_bias_report(report: BiasReport, output_path: Path) -> None:
    """Write bias report to JSON file.
    
    Args:
        report: The BiasReport to write.
        output_path: Path to the output JSON file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    report_dict = asdict(report)
    with open(output_path, "w") as f:
        json.dump(report_dict, f, indent=2)
    logger.info(f"Bias report written to {output_path}")

def main():
    """Entry point for bias check analysis.
    
    Expects:
        --input: Path to exclusion log JSON (generated by filter_worker.py)
        --output: Path to write bias report JSON
    """
    parser = argparse.ArgumentParser(description="Run bias check on excluded entries.")
    parser.add_argument("--input", type=str, required=True, 
                      help="Path to exclusion log JSON (e.g., data/processed/exclusion_log.json)")
    parser.add_argument("--output", type=str, required=True, 
                      help="Path to output bias report JSON (e.g., data/results/bias_report.json)")
    
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    try:
        exclusion_reasons = load_exclusion_log(input_path)
        report = analyze_exclusion_bias(exclusion_reasons)
        write_bias_report(report, output_path)
        logger.info("Bias check completed successfully.")
    except FileNotFoundError as e:
        logger.error(f"Input file error: {e}")
        raise SystemExit(1)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in input file: {e}")
        raise SystemExit(1)
    except ValueError as e:
        logger.error(f"Data validation error: {e}")
        raise SystemExit(1)
    except IsADirectoryError as e:
        logger.error(f"Invalid input path: {e}")
        raise SystemExit(1)

if __name__ == "__main__":
    main()