"""
retrieve_checksum.py

Implements the download and checksum verification of data files listed in
data/manifest.json. This script iterates over verified manifest entries,
downloads the files to the local data/raw directory, computes their SHA-256
checksums, and updates the manifest with the local path and checksum.

Dependency: Requires data/manifest.json to exist (generated by T004).
"""

import hashlib
import json
import os
import sys
import time
import logging
from pathlib import Path
from typing import Dict, Any, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

# Constants
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
MANIFEST_PATH = DATA_DIR / "manifest.json"
RETRY_COUNT = 3
RETRY_DELAY = 5  # seconds

def calculate_sha256(file_path: Path) -> str:
    """
    Calculate the SHA-256 checksum of a file.

    Args:
        file_path: Path to the file.

    Returns:
        Hexadecimal string of the SHA-256 hash.
    """
    sha256_hash = hashlib.sha256()
    try:
        with open(file_path, "rb") as f:
            # Read in chunks to handle large files (e.g., BAM files)
            for chunk in iter(lambda: f.read(4096), b""):
                sha256_hash.update(chunk)
        return sha256_hash.hexdigest()
    except FileNotFoundError:
        raise FileNotFoundError(f"File not found for checksum calculation: {file_path}")
    except Exception as e:
        raise RuntimeError(f"Error calculating checksum for {file_path}: {e}")

def download_file(url: str, dest_path: Path, timeout: int = 60) -> bool:
    """
    Download a file from a URL to a destination path with retry logic.
    Uses the 'requests' library which is a dependency of the project.

    Args:
        url: Source URL.
        dest_path: Local destination path.
        timeout: Request timeout in seconds.

    Returns:
        True if download successful, False otherwise.
    """
    # Ensure destination directory exists
    dest_path.parent.mkdir(parents=True, exist_ok=True)

    # Check if file already exists and is non-empty (skip download)
    if dest_path.exists() and dest_path.stat().st_size > 0:
        logger.info(f"File already exists and is non-empty, skipping download: {dest_path}")
        return True

    import requests

    attempt = 0
    while attempt < RETRY_COUNT:
        try:
            logger.info(f"Downloading {url} to {dest_path} (Attempt {attempt + 1}/{RETRY_COUNT})")
            response = requests.get(url, stream=True, timeout=timeout)
            response.raise_for_status()

            with open(dest_path, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)

            logger.info(f"Download successful: {dest_path}")
            return True

        except requests.exceptions.RequestException as e:
            attempt += 1
            logger.warning(f"Download failed: {e}. Retrying in {RETRY_DELAY} seconds...")
            time.sleep(RETRY_DELAY)

    logger.error(f"Failed to download {url} after {RETRY_COUNT} attempts.")
    return False

def load_manifest() -> Optional[Dict[str, Any]]:
    """
    Load the manifest.json file.

    Returns:
        Manifest dictionary or None if not found/corrupt.
    """
    if not MANIFEST_PATH.exists():
        logger.error(f"Manifest file not found at {MANIFEST_PATH}.")
        return None

    try:
        with open(MANIFEST_PATH, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in manifest: {e}")
        return None
    except Exception as e:
        logger.error(f"Error reading manifest: {e}")
        return None

def update_manifest_entry(entry: Dict[str, Any], local_path: Path, checksum: str) -> Dict[str, Any]:
    """
    Update a manifest entry with local path and checksum.

    Args:
        entry: The manifest entry dictionary.
        local_path: The local path where the file was saved.
        checksum: The SHA-256 checksum of the file.

    Returns:
        Updated entry dictionary.
    """
    entry['local_path'] = str(local_path)
    entry['checksum'] = checksum
    entry['verified'] = True
    return entry

def process_manifest(manifest: Dict[str, Any]) -> bool:
    """
    Iterate over manifest entries, download files, compute checksums, and update manifest.

    Args:
        manifest: The manifest dictionary.

    Returns:
        True if all files processed successfully, False otherwise.
    """
    entries = manifest.get('entries', [])
    if not entries:
        logger.warning("No entries found in manifest.")
        return True

    success_count = 0
    fail_count = 0

    for i, entry in enumerate(entries):
        accession_id = entry.get('accession_id', f'entry_{i}')
        url = entry.get('url')
        file_type = entry.get('file_type', 'unknown')
        cell_type = entry.get('cell_type', 'unknown')

        if not url:
            logger.error(f"Entry {accession_id} missing URL. Skipping.")
            fail_count += 1
            continue

        # Determine local filename
        # Use accession_id to ensure uniqueness, preserving file extension if present
        filename = f"{accession_id}.{file_type}"
        local_path = RAW_DIR / filename

        # Download
        if not download_file(url, local_path):
            logger.error(f"Skipping checksum for {accession_id} due to download failure.")
            fail_count += 1
            continue

        # Calculate checksum
        try:
            checksum = calculate_sha256(local_path)
            logger.info(f"Checksum for {accession_id}: {checksum}")
        except Exception as e:
            logger.error(f"Checksum calculation failed for {accession_id}: {e}")
            fail_count += 1
            continue

        # Update entry
        entry = update_manifest_entry(entry, local_path, checksum)
        success_count += 1

    logger.info(f"Processing complete. Success: {success_count}, Failed: {fail_count}")
    return fail_count == 0

def save_manifest(manifest: Dict[str, Any]) -> bool:
    """
    Save the updated manifest back to disk.

    Args:
        manifest: The updated manifest dictionary.

    Returns:
        True if save successful, False otherwise.
    """
    try:
        with open(MANIFEST_PATH, 'w') as f:
            json.dump(manifest, f, indent=2)
        logger.info(f"Manifest updated and saved to {MANIFEST_PATH}")
        return True
    except Exception as e:
        logger.error(f"Failed to save manifest: {e}")
        return False

def main():
    """
    Main entry point for the retrieve_checksum script.
    """
    logger.info("Starting data retrieval and checksum verification.")

    # Ensure raw data directory exists
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    # Load manifest
    manifest = load_manifest()
    if not manifest:
        logger.error("Aborting: Could not load manifest.")
        sys.exit(1)

    # Process entries
    success = process_manifest(manifest)

    if success:
        # Save updated manifest
        if save_manifest(manifest):
            logger.info("Task completed successfully.")
            sys.exit(0)
        else:
            logger.error("Task completed with download/checksum success but failed to save manifest.")
            sys.exit(1)
    else:
        logger.error("Task failed due to download or checksum errors.")
        sys.exit(1)

if __name__ == "__main__":
    main()
