"""
Validate data sources identified by search_sources.py.

This script verifies:
1. URL accessibility (HTTP 200/302 for ENCODE download links)
2. File format (bam or bigwig extension)
3. Cross-referencing of cell types (ensuring we have the required modalities)

Outputs:
- data/manifest.json: If >= 5 matched multi-modal sets are found.
- data/data_gap_report.md: If < 5 matched sets are found, triggering a pipeline halt.
"""

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests

# Project root relative to this file
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
CANDIDATE_SOURCES_PATH = DATA_DIR / "candidate_sources.json"
MANIFEST_PATH = DATA_DIR / "manifest.json"
GAP_REPORT_PATH = DATA_DIR / "data_gap_report.md"

# Required modalities for a "matched set" per spec
REQUIRED_MODALITIES = ["ChIP-seq", "ATAC-seq", "H3K27ac"]
MIN_CELL_TYPES = 5

# ENCODE download base URL
ENCODE_DOWNLOAD_BASE = "https://www.encodeproject.org"


def load_candidates() -> List[Dict[str, Any]]:
    """Load candidate sources from the JSON generated by T003."""
    if not CANDIDATE_SOURCES_PATH.exists():
        raise FileNotFoundError(
            f"Candidate sources file not found: {CANDIDATE_SOURCES_PATH}. "
            "Run search_sources.py first."
        )
    with open(CANDIDATE_SOURCES_PATH, "r") as f:
        return json.load(f)


def check_url_accessibility(url: str, timeout: int = 10) -> Tuple[bool, str]:
    """
    Check if a URL is accessible.
    Returns (is_accessible, status_message).
    """
    if not url:
        return False, "Empty URL"

    try:
        # HEAD request is safer for checking existence
        response = requests.head(url, timeout=timeout, allow_redirects=True)
        if response.status_code in (200, 302, 301):
            return True, f"Status {response.status_code}"
        else:
            return False, f"Status {response.status_code}"
    except requests.exceptions.RequestException as e:
        return False, f"Request failed: {str(e)}"


def validate_file_format(url: str) -> bool:
    """Check if URL ends with .bam or .bigwig."""
    return url.lower().endswith((".bam", ".bigwig"))


def group_by_cell_type(candidates: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Group candidates by cell type."""
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for item in candidates:
        cell_type = item.get("cell_type", "Unknown")
        if cell_type not in groups:
            groups[cell_type] = []
        groups[cell_type].append(item)
    return groups


def find_matched_sets(candidates: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[str]]:
    """
    Identify cell types that have ALL required modalities available.
    Returns a list of matched cell types and a log of search details.
    """
    groups = group_by_cell_type(candidates)
    matched_cell_types = []
    search_log = []

    for cell_type, items in groups.items():
        # Deduplicate by modality (take the first valid one found)
        available_modalities: Dict[str, Dict[str, Any]] = {}

        for item in items:
            # Basic validation before considering
            is_valid, msg = check_url_accessibility(item.get("url", ""))
            if not is_valid:
                search_log.append(f"  - {cell_type}: {item.get('file_type', 'N/A')} URL failed: {msg}")
                continue

            if not validate_file_format(item.get("url", "")):
                search_log.append(f"  - {cell_type}: {item.get('file_type', 'N/A')} invalid format")
                continue

            file_type = item.get("file_type", "")
            if file_type not in available_modalities:
                available_modalities[file_type] = item

        # Check if we have all required modalities
        found_modalities = set(available_modalities.keys())
        missing = set(REQUIRED_MODALITIES) - found_modalities

        if not missing:
            matched_cell_types.append(cell_type)
            search_log.append(f"  - {cell_type}: MATCHED (found: {', '.join(found_modalities)})")
        else:
            search_log.append(f"  - {cell_type}: INCOMPLETE (missing: {', '.join(missing)})")

    return matched_cell_types, search_log


def generate_manifest(candidates: List[Dict[str, Any]], matched_cell_types: List[str]) -> Dict[str, Any]:
    """Generate the manifest.json content."""
    # Filter candidates to only those in matched cell types
    matched_candidates = [
        item for item in candidates
        if item.get("cell_type") in matched_cell_types
    ]

    manifest = {
        "version": "1.0",
        "generated_by": "validate_sources.py",
        "matched_cell_types": matched_cell_types,
        "total_matched_sets": len(matched_cell_types),
        "required_modalities": REQUIRED_MODALITIES,
        "sources": matched_candidates
    }
    return manifest


def generate_gap_report(
    candidates: List[Dict[str, Any]],
    matched_cell_types: List[str],
    search_log: List[str],
    missing_cell_types: List[str]
) -> str:
    """Generate the data_gap_report.md content."""
    total_candidates = len(candidates)
    matched_count = len(matched_cell_types)

    report_lines = [
        "# Data Gap Report",
        "",
        "## Summary",
        f"- **Total candidates found**: {total_candidates}",
        f"- **Matched cell types (>= {MIN_CELL_TYPES})**: {matched_count}",
        f"- **Status**: {'SUCCESS' if matched_count >= MIN_CELL_TYPES else 'HALT TRIGGERED'}",
        "",
        "## Missing Cell Types",
        "The following cell types could not be matched with all required modalities (ChIP-seq, ATAC-seq, H3K27ac):",
        ""
    ]

    if missing_cell_types:
        for ct in missing_cell_types:
            report_lines.append(f"- {ct}")
    else:
        report_lines.append("- None (All candidates incomplete but no specific list generated)")

    report_lines.extend([
        "",
        "## Search Query Log",
        "Details of validation attempts:",
        ""
    ])
    report_lines.extend(search_log)

    report_lines.extend([
        "",
        "## Recommendation",
        "The automated pipeline requires >= " + str(MIN_CELL_TYPES) + " matched multi-modal cell types to proceed.",
        "Current count: " + str(matched_count) + ".",
        "",
        "1. **Re-run search**: Consider broadening the search query in `search_sources.py`.",
        "2. **Manual review**: Inspect `data/candidate_sources.json` for potential manual additions.",
        "3. **Scope revision**: If data is truly unavailable, the project scope must be revised to sequence-only or fewer cell types.",
        "",
        "**ACTION REQUIRED**: The pipeline is halted. Do not proceed to T005 until this report is resolved."
    ])

    return "\n".join(report_lines)


def main():
    """Main entry point for validation."""
    print(f"Loading candidates from {CANDIDATE_SOURCES_PATH}...")
    try:
        candidates = load_candidates()
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    if not candidates:
        print("No candidates found in candidate_sources.json. Cannot validate.")
        # Generate a gap report indicating zero candidates
        report = generate_gap_report([], [], ["No candidates found."], [])
        GAP_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(GAP_REPORT_PATH, "w") as f:
            f.write(report)
        print(f"Gap report generated: {GAP_REPORT_PATH}")
        sys.exit(1)

    print(f"Validating {len(candidates)} candidates...")
    matched_cell_types, search_log = find_matched_sets(candidates)

    print(f"Found {len(matched_cell_types)} matched cell types: {matched_cell_types}")

    # Determine missing cell types for the report
    # A cell type is "missing" if it was searched but didn't meet criteria
    # We can derive this from the groups logic, but for simplicity,
    # we list all cell types that are not in matched_cell_types.
    all_cell_types = set(item.get("cell_type") for item in candidates)
    missing_cell_types = list(all_cell_types - set(matched_cell_types))

    if len(matched_cell_types) >= MIN_CELL_TYPES:
        print(f"Success! Found {len(matched_cell_types)} >= {MIN_CELL_TYPES} matched sets.")
        manifest = generate_manifest(candidates, matched_cell_types)

        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(MANIFEST_PATH, "w") as f:
            json.dump(manifest, f, indent=2)

        print(f"Manifest generated: {MANIFEST_PATH}")
        print("Pipeline can proceed to T005.")
    else:
        print(f"Failure! Found {len(matched_cell_types)} < {MIN_CELL_TYPES} matched sets.")
        report = generate_gap_report(candidates, matched_cell_types, search_log, missing_cell_types)

        GAP_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(GAP_REPORT_PATH, "w") as f:
            f.write(report)

        print(f"Gap report generated: {GAP_REPORT_PATH}")
        print("PIPELINE HALTED. Please review the gap report.")
        sys.exit(0) # Exit 0 but with a file that triggers the halt logic in the orchestrator


if __name__ == "__main__":
    main()