import os
import logging
from pathlib import Path
from typing import Optional, List, Tuple, Dict, Any
import pandas as pd
import numpy as np

from src.utils.logging import get_logger
from src.utils.config import get_data_dir

logger = get_logger(__name__)

def load_interim_lagged_mmns(data_dir: Optional[Path] = None) -> pd.DataFrame:
    """
    Load the intermediate lagged MMN data generated by T022.
    Expects: data/interim_lagged_mmns.csv
    """
    if data_dir is None:
        data_dir = get_data_dir()
    
    file_path = Path(data_dir) / "interim_lagged_mmns.csv"
    
    if not file_path.exists():
        raise FileNotFoundError(f"Required input file not found: {file_path}")
    
    logger.info(f"Loading interim lagged MMNs from {file_path}")
    df = pd.read_csv(file_path)
    
    required_cols = ['subject_id', 'block_id', 'mmn_amplitude', 'source_window_start_trial']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in {file_path}: {missing_cols}")
    
    return df

def load_accuracy_blocks(data_dir: Optional[Path] = None) -> pd.DataFrame:
    """
    Load the behavioral accuracy blocks generated by T021.
    Expects: data/accuracy_blocks.csv
    """
    if data_dir is None:
        data_dir = get_data_dir()
    
    file_path = Path(data_dir) / "accuracy_blocks.csv"
    
    if not file_path.exists():
        raise FileNotFoundError(f"Required input file not found: {file_path}")
    
    logger.info(f"Loading accuracy blocks from {file_path}")
    df = pd.read_csv(file_path)
    
    required_cols = ['subject_id', 'block_id', 'accuracy', 'trial_start', 'trial_end']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in {file_path}: {missing_cols}")
    
    return df

def load_excluded_subjects(data_dir: Optional[Path] = None) -> Optional[pd.DataFrame]:
    """
    Load the excluded subjects list from the power report.
    Expects: data/power_report.csv
    Returns a DataFrame of excluded subject IDs if the file exists, else None.
    """
    if data_dir is None:
        data_dir = get_data_dir()
    
    file_path = Path(data_dir) / "power_report.csv"
    
    if not file_path.exists():
        logger.warning(f"Power report not found at {file_path}. Assuming no exclusions.")
        return None
    
    logger.info(f"Loading power report from {file_path}")
    df = pd.read_csv(file_path)
    
    # Filter for underpowered subjects based on the current analysis mode logic.
    # For T023, we assume the 'analysis_mode' logic has already determined which
    # rows to flag. Here we just load the raw flags.
    # We return the list of subject_ids that are flagged as underpowered.
    # Note: T023 logic handles the filtering based on analysis_mode.
    # This function simply retrieves the data.
    return df

def filter_by_excluded_subjects(
    mmn_df: pd.DataFrame,
    acc_df: pd.DataFrame,
    excluded_df: Optional[pd.DataFrame],
    analysis_mode: str = "error_signal"
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Filter the MMN and Accuracy DataFrames based on the excluded subjects.
    
    Logic (per T023):
    - If analysis_mode == "error_signal": Exclude subjects flagged as 'underpowered_primary'.
    - If analysis_mode == "stimulus_driven": Include all subjects but retain power_status.
    
    Returns filtered (mmn_df, acc_df).
    """
    if excluded_df is None:
        logger.info("No exclusions applied (power report missing).")
        return mmn_df, acc_df

    # Identify subjects to exclude
    if analysis_mode == "error_signal":
        # Exclude if power_status is 'underpowered_primary'
        to_exclude = excluded_df[excluded_df['power_status'] == 'underpowered_primary']['subject_id'].unique()
        logger.info(f"Filtering out {len(to_exclude)} subjects flagged as underpowered (error_signal mode).")
    else:
        # stimulus_driven mode: do not exclude based on power status for the primary hypothesis
        # We might still want to log warnings, but we keep the data.
        to_exclude = []
        logger.info("No subject filtering applied (stimulus_driven mode).")

    if len(to_exclude) > 0:
        mmn_df = mmn_df[~mmn_df['subject_id'].isin(to_exclude)]
        acc_df = acc_df[~acc_df['subject_id'].isin(to_exclude)]
        logger.info(f"Filtered data shapes: MMN={mmn_df.shape}, Accuracy={acc_df.shape}")
    else:
        logger.info("No subjects to exclude.")

    return mmn_df, acc_df

def validate_aligned_data(df: pd.DataFrame) -> bool:
    """
    Validate the final aligned dataset against the schema requirements.
    Checks for required columns and non-null values in critical fields.
    """
    required_cols = [
        'subject_id', 'block_id', 'mmn_amplitude', 
        'source_window_start_trial', 'accuracy', 
        'trial_start', 'trial_end', 'learning_phase', 'power_status'
    ]
    
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        logger.error(f"Validation failed: Missing columns {missing_cols}")
        return False

    # Check for NaN in critical numeric columns
    if df['mmn_amplitude'].isnull().any():
        logger.warning("Validation: mmn_amplitude contains NaN values.")
        # We might not fail here if NaN is expected, but usually we want to flag it.
    
    if df['accuracy'].isnull().any():
        logger.warning("Validation: accuracy contains NaN values.")

    logger.info("Validation passed: Aligned data schema is correct.")
    return True

def run_finalization_pipeline(
    data_dir: Optional[Path] = None,
    analysis_mode: str = "error_signal"
) -> Path:
    """
    Main pipeline function for T024: Finalize and Write Aligned Dataset.
    
    Steps:
    1. Load interim_lagged_mmns.csv (T022 output)
    2. Load accuracy_blocks.csv (T021 output)
    3. Load power_report.csv (T016 output)
    4. Filter data based on analysis_mode (T023 logic)
    5. Merge filtered dataframes on (subject_id, block_id)
    6. Add learning_phase column if not present (from T022b)
    7. Validate schema
    8. Write final aligned_data.csv
    """
    if data_dir is None:
        data_dir = get_data_dir()
    else:
        data_dir = Path(data_dir)
    
    logger.info("Starting Finalization Pipeline (T024)...")
    
    # 1. Load Inputs
    mmn_df = load_interim_lagged_mmns(data_dir)
    acc_df = load_accuracy_blocks(data_dir)
    power_df = load_excluded_subjects(data_dir)
    
    # 2. Filter Data
    mmn_filtered, acc_filtered = filter_by_excluded_subjects(
        mmn_df, acc_df, power_df, analysis_mode
    )
    
    # 3. Merge
    # Ensure both have 'block_id' and 'subject_id' as join keys.
    # The lagged alignment (T022) aligns MMN from window [t-50, t-10] to accuracy block [t, t+n].
    # The block_id should represent the target accuracy block.
    # We merge on subject_id and block_id.
    
    merged_df = pd.merge(
        mmn_filtered,
        acc_filtered,
        on=['subject_id', 'block_id'],
        how='inner',
        suffixes=('_mmn', '_acc')
    )
    
    if merged_df.empty:
        logger.warning("Merge resulted in an empty DataFrame. Check block_id alignment.")
    else:
        logger.info(f"Merged data shape: {merged_df.shape}")
    
    # 4. Ensure learning_phase exists
    # T022b should have added this to the interim file. If not, we add it here as a fallback.
    if 'learning_phase' not in merged_df.columns:
        logger.warning("learning_phase column missing. Generating based on block_id.")
        # Simple heuristic: Early if block_id < median, else Late
        median_block = merged_df['block_id'].median()
        merged_df['learning_phase'] = merged_df['block_id'].apply(
            lambda x: 'Early' if x < median_block else 'Late'
        )
    
    # 5. Ensure power_status exists
    if 'power_status' not in merged_df.columns:
        # Map from the power report if we have it, else default to 'powered'
        if power_df is not None and not power_df.empty:
            # Merge power status
            merged_df = pd.merge(
                merged_df,
                power_df[['subject_id', 'power_status']].drop_duplicates(),
                on='subject_id',
                how='left'
            )
        else:
            merged_df['power_status'] = 'powered'
            
    # Fill NaN in power_status if merge failed
    merged_df['power_status'] = merged_df['power_status'].fillna('powered')
    
    # 6. Validate
    is_valid = validate_aligned_data(merged_df)
    if not is_valid:
        raise RuntimeError("Finalized data failed schema validation.")
    
    # 7. Write Output
    output_path = data_dir / "aligned_data.csv"
    merged_df.to_csv(output_path, index=False)
    logger.info(f"Final aligned dataset written to {output_path}")
    
    return output_path

def main():
    """Entry point for running the finalization pipeline."""
    import sys
    # Parse simple args if needed, default to defaults
    data_dir = Path(os.environ.get('DATA_DIR', 'data'))
    analysis_mode = os.environ.get('ANALYSIS_MODE', 'error_signal')
    
    try:
        run_finalization_pipeline(data_dir=data_dir, analysis_mode=analysis_mode)
    except Exception as e:
        logger.error(f"Finalization pipeline failed: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()
