"""
PR Classification Module (T014 + T015a + T015c)

Implements primary signature-based classification (T014) and secondary
heuristic-based detection (T015a) using local heuristics only.
"""
import os
import sys
import json
import csv
import re
import math
import hashlib
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime

# Project imports
from utils.logging import get_logger, setup_logging
from utils.config import get_path, get_classification_thresholds, get_config_summary
from utils.seeds import set_global_seed

# --- Secondary Detector Parameters (T015c) ---
# Defined locally to ensure executability without external data dependencies.
# These values are hardcoded baselines as per task requirements.

# Hardcoded baseline of common Python tokens and standard library imports
# Used as the reference set for n-gram anomaly detection (Jaccard similarity).
COMMON_PYTHON_TOKENS_BASELINE = {
    "import", "from", "def", "class", "return", "if", "else", "elif",
    "for", "while", "try", "except", "finally", "with", "as", "pass",
    "break", "continue", "lambda", "yield", "global", "nonlocal", "assert",
    "del", "print", "input", "len", "range", "str", "int", "float", "bool",
    "list", "dict", "set", "tuple", "None", "True", "False",
    "os", "sys", "re", "math", "json", "csv", "pathlib", "typing",
    "datetime", "collections", "itertools", "functools", "io",
    "requests", "pandas", "numpy", "scipy", "matplotlib", "seaborn",
    "pytest", "unittest", "logging", "hashlib", "random", "time",
    "argparse", "subprocess", "shutil", "tempfile", "glob", "fnmatch",
    "pickle", "copy", "abc", "dataclasses", "enum", "contextlib",
    "warnings", "traceback", "inspect", "ast", "tokenize", "dis",
    "gc", "weakref", "array", "struct", "codecs", "unicodedata",
    "string", "textwrap", "unicodedata", "locale", "gettext",
    "builtins", "__name__", "__file__", "__doc__", "__package__",
    "__loader__", "__spec__", "__cached__"
}

# Entropy thresholds (bits per token)
# Typical human code tends to be more structured (lower entropy) or highly variable (high entropy).
# LLM code often falls in a specific "sweet spot" of moderate entropy.
ENTROPY_THRESHOLD_LOW = 2.5
ENTROPY_THRESHOLD_HIGH = 5.5

# N-gram parameters
NGRAM_SIZE = 3
NGRAM_ANOMALY_THRESHOLD = 0.3  # Jaccard similarity threshold

# Scoring weights
WEIGHT_ENTROPY = 0.6
WEIGHT_NGRAM = 0.4

# --- Logger Setup ---
logger = get_logger()

def set_reproducibility_seed(seed: int = 42) -> None:
    """Set global random seed for reproducibility (T050)."""
    set_global_seed(seed)

def is_llm_bot(user: str) -> bool:
    """Check if user is a known LLM bot (e.g., Copilot)."""
    llm_patterns = [
        "copilot", "github-copilot", "codex", "gpt", "llama",
        "claude", "gemini", "mistral", "deepseek"
    ]
    user_lower = user.lower()
    return any(pattern in user_lower for pattern in llm_patterns)

def is_human_bot(user: str) -> bool:
    """Check if user is a known infrastructure bot (e.g., Dependabot)."""
    human_bot_patterns = [
        "dependabot", "renovate", "snyk", "codecov", "coveralls",
        "travis", "circleci", "jenkins", "github-actions"
    ]
    user_lower = user.lower()
    return any(pattern in user_lower for pattern in human_bot_patterns)

def has_llm_signature(message: str) -> bool:
    """Check if commit message contains LLM signatures."""
    if not message:
        return False
    llm_indicators = [
        "copilot", "generated by", "generated with", "auto-generated",
        "ai-generated", "llm", "copilot suggested"
    ]
    message_lower = message.lower()
    return any(indicator in message_lower for indicator in llm_indicators)

def calculate_signature_strength(user: str, message: str) -> float:
    """Calculate strength of LLM signature (0.0 to 1.0)."""
    score = 0.0
    if is_llm_bot(user):
        score += 0.5
    if has_llm_signature(message):
        score += 0.5
    return min(score, 1.0)

def calculate_confidence_score(user: str, message: str) -> float:
    """
    Calculate primary confidence score based on signature match logic.
    Returns a float in [0.0, 1.0].
    """
    if is_human_bot(user):
        return 0.0  # High confidence Human
    if is_llm_bot(user):
        return 1.0  # High confidence LLM

    strength = calculate_signature_strength(user, message)
    # If no clear signature, confidence is low (ambiguous)
    return strength

def tokenize_code(code: str) -> List[str]:
    """Simple tokenizer for code: split by non-alphanumeric chars."""
    # Remove comments and strings for entropy calculation to focus on structure
    code = re.sub(r'#.*', '', code)
    code = re.sub(r'""".*?"""', '', code, flags=re.DOTALL)
    code = re.sub(r"'''.*?'''", '', code, flags=re.DOTALL)
    code = re.sub(r'".*?"', '', code)
    code = re.sub(r"'.*?'", '', code)

    # Split by whitespace and punctuation
    tokens = re.findall(r'\w+|[^\w\s]', code)
    return [t.lower() for t in tokens if t]

def calculate_code_entropy(code: str) -> float:
    """
    Calculate Shannon entropy of tokenized code (T015a).
    Returns entropy in bits.
    """
    tokens = tokenize_code(code)
    if not tokens:
        return 0.0

    freq = {}
    for t in tokens:
        freq[t] = freq.get(t, 0) + 1

    entropy = 0.0
    total = len(tokens)
    for count in freq.values():
        p = count / total
        if p > 0:
            entropy -= p * math.log2(p)

    return entropy

def calculate_ngram_anomaly_score(code: str) -> float:
    """
    Calculate n-gram anomaly score using Jaccard similarity against a hardcoded baseline.
    Returns a score in [0.0, 1.0] where 0.0 is highly anomalous (low similarity)
    and 1.0 is normal (high similarity).
    """
    tokens = tokenize_code(code)
    if len(tokens) < NGRAM_SIZE:
        return 0.0  # Too short to be anomalous or normal

    # Generate 3-grams
    ngrams = set()
    for i in range(len(tokens) - NGRAM_SIZE + 1):
        ngram = tuple(tokens[i:i + NGRAM_SIZE])
        ngrams.add(ngram)

    if not ngrams:
        return 0.0

    # Calculate Jaccard similarity against baseline
    # Baseline n-grams are derived from COMMON_PYTHON_TOKENS_BASELINE
    # Since baseline is tokens, we create synthetic n-grams from them
    baseline_ngrams = set()
    baseline_tokens = list(COMMON_PYTHON_TOKENS_BASELINE)
    for i in range(len(baseline_tokens) - NGRAM_SIZE + 1):
        ngram = tuple(baseline_tokens[i:i + NGRAM_SIZE])
        baseline_ngrams.add(ngram)

    if not baseline_ngrams:
        return 0.5  # Neutral if baseline empty

    intersection = len(ngrams & baseline_ngrams)
    union = len(ngrams | baseline_ngrams)

    jaccard = intersection / union if union > 0 else 0.0

    # Normalize: High Jaccard = Normal (1.0), Low Jaccard = Anomalous (0.0)
    # The task asks for an anomaly score, but typically we want a "normalcy" score
    # to combine with entropy. Let's return Jaccard as the "normalcy" score.
    return jaccard

def compute_secondary_detector_score(code: str) -> float:
    """
    Compute secondary detector score using local heuristics (T015a).
    Combines entropy and n-gram anomaly scores.
    Returns a float in [0.0, 1.0].
    """
    entropy = calculate_code_entropy(code)
    ngram_score = calculate_ngram_anomaly_score(code)

    # Normalize entropy to [0, 1] range for combination
    # Assuming entropy range roughly [0, 10] for code
    normalized_entropy = max(0.0, min(1.0, entropy / 10.0))

    # Heuristic: LLM code often has moderate entropy (not too low, not too high)
    # and high n-gram similarity to standard patterns.
    # We want a score that is high for LLM-like characteristics.
    # Let's define:
    # - High n-gram similarity (close to 1.0) -> LLM-like
    # - Moderate entropy (around 0.5 normalized) -> LLM-like

    # Simple weighted combination for "LLM-ness"
    # If entropy is too low (<0.2) or too high (>0.8), it might be human (boilerplate or complex logic)
    # If entropy is moderate (0.2-0.8) and n-gram is high, it's likely LLM.

    entropy_factor = 1.0 - abs(normalized_entropy - 0.5) * 2  # Peaks at 0.5, drops to 0 at 0 and 1
    ngram_factor = ngram_score

    # Weighted sum
    score = (WEIGHT_ENTROPY * entropy_factor) + (WEIGHT_NGRAM * ngram_factor)

    return max(0.0, min(1.0, score))

def extract_diff_text(pr_data: Dict[str, Any]) -> str:
    """Extract diff text from PR data."""
    # Try multiple possible keys
    diff_keys = ["diff", "patch", "body", "description", "text"]
    for key in diff_keys:
        if key in pr_data:
            return str(pr_data[key])
    return ""

def load_prs_from_raw(input_path: str) -> List[Dict[str, Any]]:
    """Load PRs from raw JSON file."""
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and "prs" in data:
        return data["prs"]
    else:
        return [data]

def classify_prs(prs: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Classify PRs with primary and secondary detectors.
    Outputs: source_type, confidence_score, flagged, detector_score.
    """
    results = []
    for pr in prs:
        pr_id = pr.get("id", pr.get("pr_id", 0))
        user = pr.get("user", pr.get("author", ""))
        message = pr.get("message", pr.get("commit_message", ""))
        diff = extract_diff_text(pr)

        # Primary classification
        confidence = calculate_confidence_score(user, message)
        source_type = "llm" if confidence >= 0.6 else "human"
        flagged = confidence < 0.6

        # Secondary detector
        detector_score = compute_secondary_detector_score(diff)

        # Update source_type if secondary detector strongly disagrees (optional refinement)
        # For now, we keep primary as source_type but include detector_score for validation
        # If detector_score > 0.7 and primary says human, we might flag it for review
        if detector_score > 0.7 and source_type == "human" and confidence < 0.8:
            # Ambiguous case, keep as human but flag if not already
            if not flagged:
                flagged = True

        result = {
            "pr_id": pr_id,
            "source_type": source_type,
            "confidence_score": round(confidence, 4),
            "flagged": flagged,
            "detector_score": round(detector_score, 4),
            "user": user,
            "message": message[:200] if message else "", # Truncate for safety
            "diff_length": len(diff)
        }
        results.append(result)

    return results

def save_classified_prs(results: List[Dict[str, Any]], output_path: str) -> None:
    """Save classified PRs to CSV."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    fieldnames = ["pr_id", "source_type", "confidence_score", "flagged", "detector_score", "user", "message", "diff_length"]
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

def run_classification(input_path: str, output_path: str) -> Dict[str, Any]:
    """Run full classification pipeline."""
    logger.log("classification_started", input=input_path, output=output_path)

    prs = load_prs_from_raw(input_path)
    logger.log("prs_loaded", count=len(prs))

    results = classify_prs(prs)
    logger.log("classification_completed", count=len(results))

    save_classified_prs(results, output_path)
    logger.log("results_saved", path=output_path)

    # Summary stats
    llm_count = sum(1 for r in results if r["source_type"] == "llm")
    human_count = len(results) - llm_count
    flagged_count = sum(1 for r in results if r["flagged"])

    summary = {
        "total_prs": len(results),
        "llm_count": llm_count,
        "human_count": human_count,
        "flagged_count": flagged_count,
        "output_file": output_path
    }

    return summary

def main():
    """CLI entry point."""
    import argparse
    parser = argparse.ArgumentParser(description="Classify PRs as LLM or Human")
    parser.add_argument("--input", required=True, help="Input JSON file path")
    parser.add_argument("--output", required=True, help="Output CSV file path")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    setup_logging(script_name="classify_prs")
    set_reproducibility_seed(args.seed)

    try:
        summary = run_classification(args.input, args.output)
        print(json.dumps(summary, indent=2))
    except Exception as e:
        logger.log("classification_failed", error=str(e))
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()