import os
import sys
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
import pandas as pd
import numpy as np
from datetime import datetime

# Import existing utilities
from src.utils.config import ensure_dirs
from src.utils.plots import plot_weekly_counts

logger = logging.getLogger(__name__)

def load_signals(input_path: str) -> pd.DataFrame:
    """
    Load the signals CSV generated by T026.
    Raises FileNotFoundError if the file does not exist.
    """
    path = Path(input_path)
    if not path.exists():
        raise FileNotFoundError(f"Signals file not found: {input_path}")
    
    df = pd.read_csv(path)
    logger.info(f"Loaded {len(df)} signals from {input_path}")
    return df

def identify_top_signals(df: pd.DataFrame, top_n: int = 5) -> List[Dict[str, Any]]:
    """
    Identify top N candidate SOCs based on signal strength.
    
    Prioritization logic:
    1. Must have signal_flag == True.
    2. If fewer than N signals exist, return all available signals.
    3. If zero signals exist, return empty list.
    4. Ranking metric: ROR (descending), then PRR (descending) as tiebreaker.
    
    Returns a list of dicts containing SOC info and metrics.
    """
    # Filter for signals
    signals_df = df[df['signal_flag'] == True].copy()
    
    if len(signals_df) == 0:
        logger.warning("No signals found meeting the 2-out-of-3 threshold.")
        return []
    
    # Sort by ROR descending, then PRR descending
    # Ensure we handle potential NaNs by filling with -inf for sorting
    signals_df['ror'] = signals_df['ror'].fillna(-np.inf)
    signals_df['prr'] = signals_df['prr'].fillna(-np.inf)
    
    signals_df = signals_df.sort_values(
        by=['ror', 'prr'], 
        ascending=[False, False]
    )
    
    # Select top N (or all if fewer)
    selected = signals_df.head(top_n)
    
    top_signals = []
    for _, row in selected.iterrows():
        top_signals.append({
            'soc': row['soc'],
            'ror': row['ror'],
            'prr': row['prr'],
            'ic': row['ic'],
            'signal_flag': row['signal_flag']
        })
    
    logger.info(f"Identified {len(top_signals)} top signals for temporal analysis.")
    return top_signals

def generate_empty_signal_warning(output_dir: str) -> str:
    """
    Generate a placeholder warning file if no signals are found.
    Returns the path to the created file.
    """
    path = Path(output_dir) / "empty_signal_warning.txt"
    with open(path, 'w') as f:
        f.write("WARNING: No candidate SOCs met the signal detection threshold.\n")
        f.write("Temporal analysis could not be performed.\n")
        f.write("Check output/signals.csv to verify signal detection results.\n")
    logger.info(f"Generated empty signal warning at {path}")
    return str(path)

def run_temporal_preparation(
    signals_input: str,
    output_dir: str,
    top_n: int = 5
) -> List[str]:
    """
    Main entry point for T032: Identify top signals and prepare for temporal analysis.
    
    This function:
    1. Loads signals from signals_input.
    2. Identifies top N signals.
    3. Writes a warning file if no signals exist.
    4. Returns a list of SOC codes to be processed by subsequent temporal tasks (T033).
    
    Args:
        signals_input: Path to output/signals.csv
        output_dir: Directory for output artifacts (e.g., output/temporal_profiles)
        top_n: Number of top signals to select.
    
    Returns:
        List of SOC codes (strings) for top signals. Empty if no signals found.
    """
    ensure_dirs([output_dir])
    
    try:
        df = load_signals(signals_input)
    except FileNotFoundError as e:
        logger.error(f"Failed to load signals: {e}")
        # If signals file is missing, we cannot proceed. 
        # Generate warning file to indicate failure state.
        generate_empty_signal_warning(output_dir)
        return []
    
    top_signals = identify_top_signals(df, top_n)
    
    if not top_signals:
        generate_empty_signal_warning(output_dir)
        return []
    
    soc_codes = [s['soc'] for s in top_signals]
    
    # Log the selected SOCs for the next stage
    logger.info(f"Selected SOCs for temporal analysis: {soc_codes}")
    
    # Optional: Write a small manifest of selected SOCs for T033 to read
    manifest_path = Path(output_dir) / "selected_soc_manifest.csv"
    manifest_df = pd.DataFrame(top_signals)
    manifest_df.to_csv(manifest_path, index=False)
    logger.info(f"Wrote SOC manifest to {manifest_path}")
    
    return soc_codes

def main():
    """
    Command-line entry point for T032.
    """
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Default paths based on project structure
    signals_path = "output/signals.csv"
    temporal_output_dir = "output/temporal_profiles"
    
    # Allow override via arguments if needed
    if len(sys.argv) > 1:
        signals_path = sys.argv[1]
    if len(sys.argv) > 2:
        temporal_output_dir = sys.argv[2]
    
    logger.info(f"Starting T032: Identify top signals from {signals_path}")
    
    socs = run_temporal_preparation(
        signals_input=signals_path,
        output_dir=temporal_output_dir,
        top_n=5
    )
    
    if not socs:
        logger.info("No signals found. Temporal analysis skipped.")
        return 1
    
    logger.info(f"Successfully identified {len(socs)} signals. Ready for T033.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
