"""
Task T019b: TRACEABILITY
Associate the checksum generated in T019 with the SimulationRun metadata record.

This script reads the checksum manifest produced by T019 (state/checksums_raw.json),
loads the single run results (data/processed/single_run_results.json), finds the
matching checksum for the run's parameters (N, seed, theta), and updates the
metadata record with the checksum hash.
"""
import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path for imports if running as script
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.config import get_project_paths

def setup_logging(log_file: Path) -> None:
    """Configure logging to file and console."""
    log_file.parent.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )

def load_checksum_manifest(checksum_path: Path) -> dict:
    """Load the checksum manifest generated by T019."""
    if not checksum_path.exists():
        raise FileNotFoundError(f"Checksum manifest not found: {checksum_path}")
    
    with open(checksum_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def load_single_run_results(results_path: Path) -> dict:
    """Load the single run results metadata."""
    if not results_path.exists():
        raise FileNotFoundError(f"Single run results not found: {results_path}")
    
    with open(results_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def find_checksum_for_run(
    checksum_manifest: dict, 
    run_params: dict
) -> str:
    """
    Find the checksum hash that matches the run parameters.
    
    Args:
        checksum_manifest: Dict containing 'entries' list with file paths and hashes
        run_params: Dict with 'N', 'seed', 'theta' to match against filename pattern
    
    Returns:
        str: The SHA-256 checksum hash
        
    Raises:
        ValueError: If no matching checksum is found
    """
    n = run_params.get('N')
    seed = run_params.get('seed')
    theta = run_params.get('theta')
    
    if n is None or seed is None:
        raise ValueError("Run parameters must include 'N' and 'seed'")
    
    # Expected filename pattern from T019: matrix_N{N}_seed{seed}.npy
    expected_pattern = f"matrix_N{n}_seed{seed}.npy"
    
    entries = checksum_manifest.get('entries', [])
    for entry in entries:
        file_path = entry.get('file_path', '')
        if expected_pattern in file_path:
            # Verify theta matches if present in both
            if 'theta' in run_params and 'theta' in entry:
                if entry['theta'] == run_params['theta']:
                    return entry['hash']
            elif 'theta' not in entry:
                # If checksum entry doesn't have theta, just match on N and seed
                return entry['hash']
    
    raise ValueError(
        f"No checksum found for matrix_N{n}_seed{seed}.npy. "
        f"Available entries: {[e.get('file_path', '') for e in entries]}"
    )

def update_run_metadata(
    results: dict, 
    checksum_hash: str, 
    checksum_file: str
) -> dict:
    """
    Update the run metadata with checksum information.
    
    Args:
        results: The loaded single run results dict
        checksum_hash: The SHA-256 hash
        checksum_file: The path to the raw matrix file
        
    Returns:
        dict: Updated results with checksum info
    """
    # Ensure traceability metadata exists
    if 'traceability' not in results:
        results['traceability'] = {}
    
    results['traceability']['raw_matrix_checksum'] = checksum_hash
    results['traceability']['raw_matrix_file'] = checksum_file
    results['traceability']['checksum_timestamp'] = datetime.now(timezone.utc).isoformat()
    results['traceability']['data_hygiene_status'] = 'verified'
    
    return results

def save_updated_results(results: dict, output_path: Path) -> None:
    """Save the updated results to JSON."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2)

def main():
    """Main entry point for T019b traceability task."""
    parser = argparse.ArgumentParser(
        description='Associate checksum with simulation run metadata (T019b)'
    )
    parser.add_argument(
        '--checksum-manifest',
        type=str,
        default=None,
        help='Path to checksum manifest (default: auto-detect from project paths)'
    )
    parser.add_argument(
        '--results-file',
        type=str,
        default=None,
        help='Path to single run results JSON (default: auto-detect from project paths)'
    )
    parser.add_argument(
        '--output-file',
        type=str,
        default=None,
        help='Path to output updated results (default: same as input)'
    )
    parser.add_argument(
        '--log-file',
        type=str,
        default=None,
        help='Path to log file (default: auto-detect)'
    )
    
    args = parser.parse_args()
    
    # Get project paths
    paths = get_project_paths()
    
    checksum_manifest_path = Path(args.checksum_manifest) if args.checksum_manifest else paths['state'] / 'checksums_raw.json'
    results_path = Path(args.results_file) if args.results_file else paths['processed'] / 'single_run_results.json'
    output_path = Path(args.output_file) if args.output_file else results_path
    log_path = Path(args.log_file) if args.log_file else paths['logs'] / 'task019b_traceability.log'
    
    setup_logging(log_path)
    logger = logging.getLogger(__name__)
    
    logger.info(f"Starting T019b traceability task")
    logger.info(f"Checksum manifest: {checksum_manifest_path}")
    logger.info(f"Results file: {results_path}")
    logger.info(f"Output file: {output_path}")
    
    try:
        # Load checksum manifest
        logger.info("Loading checksum manifest...")
        checksum_manifest = load_checksum_manifest(checksum_manifest_path)
        logger.info(f"Loaded {len(checksum_manifest.get('entries', []))} checksum entries")
        
        # Load single run results
        logger.info("Loading single run results...")
        results = load_single_run_results(results_path)
        
        # Extract run parameters
        run_params = {
            'N': results.get('N'),
            'seed': results.get('seed'),
            'theta': results.get('theta')
        }
        
        if not all(v is not None for v in [run_params['N'], run_params['seed']]):
            raise ValueError("Results file must contain 'N' and 'seed' parameters")
        
        logger.info(f"Run parameters: N={run_params['N']}, seed={run_params['seed']}, theta={run_params.get('theta')}")
        
        # Find matching checksum
        logger.info("Searching for matching checksum...")
        checksum_hash = find_checksum_for_run(checksum_manifest, run_params)
        logger.info(f"Found checksum: {checksum_hash[:16]}...")
        
        # Determine the raw matrix file path from the manifest
        expected_pattern = f"matrix_N{run_params['N']}_seed{run_params['seed']}.npy"
        raw_matrix_file = None
        for entry in checksum_manifest.get('entries', []):
            if expected_pattern in entry.get('file_path', ''):
                raw_matrix_file = entry['file_path']
                break
        
        if not raw_matrix_file:
            raw_matrix_file = f"data/raw/{expected_pattern}"
        
        # Update metadata
        logger.info("Updating run metadata with checksum...")
        updated_results = update_run_metadata(results, checksum_hash, raw_matrix_file)
        
        # Save updated results
        logger.info(f"Saving updated results to {output_path}")
        save_updated_results(updated_results, output_path)
        
        logger.info("T019b traceability task completed successfully")
        logger.info(f"Data hygiene status: {updated_results['traceability']['data_hygiene_status']}")
        
        return 0
        
    except FileNotFoundError as e:
        logger.error(f"File not found: {e}")
        logger.error("Ensure T019 has completed and generated the required files.")
        return 1
    except ValueError as e:
        logger.error(f"Validation error: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        return 1

if __name__ == '__main__':
    sys.exit(main())
