import os
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional

import numpy as np
import pandas as pd

# Add project root to path to allow imports from code/
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from utils.config import load_environment
from utils.exceptions import DataQualityError
from ingestion.logging_utils import setup_logging, get_logger

def load_model_metrics_from_training_log(log_path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Load model metrics from the training log or pickle file generated by train.py.
    
    This function assumes that the training script (T020-T024) has already executed
    and saved metrics to a pickle file or log. Since the training script is expected
    to save metrics, we read them from the expected location.
    
    Returns:
        Dictionary with metrics structure as required by T025.
    """
    if log_path is None:
        log_path = project_root / "artifacts" / "training_metrics.pkl"
    
    if not log_path.exists():
        raise FileNotFoundError(
            f"Training metrics file not found at {log_path}. "
            "Ensure that code/modeling/train.py has been executed successfully."
        )
    
    import pickle
    with open(log_path, 'rb') as f:
        metrics = pickle.load(f)
    
    return metrics

def generate_model_metrics_json(metrics: Dict[str, Any], output_path: Path) -> None:
    """
    Generate the model_metrics.json file with the explicit schema required by T025.
    
    Schema:
    {
      "mean_r2": float,
      "mean_rmse": float,
      "loso_r2_sd": float,
      "spatial_cv_r2_sd": float,
      "per_target_metrics": {
        "target_name": {
          "mean_r2": float,
          "mean_rmse": float,
          ...
        },
        ...
      }
    }
    
    Args:
        metrics: Dictionary containing all computed metrics from training.
        output_path: Path where the JSON file will be written.
    """
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Extract and structure the metrics according to the required schema
    structured_metrics = {
        "mean_r2": float(metrics.get("mean_r2", 0.0)),
        "mean_rmse": float(metrics.get("mean_rmse", 0.0)),
        "loso_r2_sd": float(metrics.get("loso_r2_sd", 0.0)),
        "spatial_cv_r2_sd": float(metrics.get("spatial_cv_r2_sd", 0.0)),
        "per_target_metrics": {}
    }
    
    # Populate per-target metrics
    if "per_target_metrics" in metrics:
        for target, target_metrics in metrics["per_target_metrics"].items():
            structured_metrics["per_target_metrics"][target] = {
                "mean_r2": float(target_metrics.get("mean_r2", 0.0)),
                "mean_rmse": float(target_metrics.get("mean_rmse", 0.0)),
                "std_r2": float(target_metrics.get("std_r2", 0.0)),
                "std_rmse": float(target_metrics.get("std_rmse", 0.0))
            }
    
    # Write to JSON file
    with open(output_path, 'w') as f:
        json.dump(structured_metrics, f, indent=2)
    
    logging.info(f"Model metrics written to {output_path}")

def main():
    """
    Main entry point for generating model_metrics.json.
    
    This script:
    1. Loads metrics from the training pipeline output.
    2. Structures them according to the T025 schema.
    3. Writes the JSON file to artifacts/model_metrics.json.
    """
    # Setup logging
    setup_logging()
    logger = get_logger(__name__)
    
    # Load environment configuration
    load_environment()
    
    # Define paths
    metrics_input_path = project_root / "artifacts" / "training_metrics.pkl"
    metrics_output_path = project_root / "artifacts" / "model_metrics.json"
    
    try:
        # Load metrics from training
        logger.info("Loading metrics from training pipeline...")
        metrics = load_model_metrics_from_training_log(metrics_input_path)
        
        # Generate the JSON output
        logger.info("Generating model_metrics.json...")
        generate_model_metrics_json(metrics, metrics_output_path)
        
        logger.info(f"Successfully generated {metrics_output_path}")
        
    except FileNotFoundError as e:
        logger.error(str(e))
        logger.error("The training pipeline (code/modeling/train.py) must be executed first.")
        raise
    except Exception as e:
        logger.error(f"Error generating model metrics: {e}")
        raise

if __name__ == "__main__":
    main()
