import os
import sys
import logging
import json
import time
import pickle
import pandas as pd
import numpy as np
from sklearn.inspection import permutation_importance
from xgboost import XGBRegressor
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / "data"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
LME_ARTIFACT_PATH = ARTIFACTS_DIR / "mixed_effects_results.json"
XGBOOST_ARTIFACT_PATH = ARTIFACTS_DIR / "xgboost_model_artifact.json"

def load_split_data():
    """Load the train and test data splits generated by T030."""
    train_path = DATA_DIR / "train_data.csv"
    test_path = DATA_DIR / "test_data.csv"
    
    if not train_path.exists() or not test_path.exists():
        raise FileNotFoundError(
            "Split data files not found. Please run preprocessing.py (T030) first."
        )
    
    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)
    
    logger.info(f"Loaded train data: {train_df.shape}, test data: {test_df.shape}")
    return train_df, test_df

def prepare_features(df, target_col='ductility'):
    """Prepare features and target from the dataframe."""
    # Exclude target and non-feature columns
    exclude_cols = [target_col, 'alloy_family', 'source']
    feature_cols = [c for c in df.columns if c not in exclude_cols]
    
    X = df[feature_cols]
    y = df[target_col]
    
    logger.info(f"Prepared features: {X.shape}, target: {y.shape}")
    return X, y, feature_cols

def tune_and_train(X_train, y_train, X_val, y_val, time_budget=300):
    """
    Tune hyperparameters and train the XGBoost model.
    Uses a simple grid search with early stopping within time budget.
    """
    start_time = time.time()
    
    # Define parameter grid
    param_grid = {
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1],
        'n_estimators': [100, 200, 500],
        'subsample': [0.8, 1.0],
        'colsample_bytree': [0.8, 1.0]
    }
    
    best_score = -np.inf
    best_params = None
    best_model = None
    
    # Simple grid search (limited iterations for time budget)
    # In a real scenario, use Optuna or Ray Tune
    from sklearn.model_selection import ParameterGrid
    
    param_list = list(ParameterGrid(param_grid))
    logger.info(f"Starting hyperparameter tuning with {len(param_list)} combinations...")
    
    for i, params in enumerate(param_list):
        if time.time() - start_time > time_budget:
            logger.warning("Time budget exceeded during tuning. Stopping.")
            break
        
        model = XGBRegressor(
            **params,
            tree_method="hist",
            objective='reg:squarederror',
            random_state=42,
            n_jobs=-1
        )
        
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            early_stopping_rounds=20,
            verbose=False
        )
        
        val_score = model.score(X_val, y_val)
        
        if val_score > best_score:
            best_score = val_score
            best_params = params
            best_model = model
            logger.info(f"New best score: {val_score:.4f} with params: {params}")
    
    if best_model is None:
        raise RuntimeError("Model training failed to find a valid model.")
        
    logger.info(f"Tuning complete. Best params: {best_params}, Best score: {best_score:.4f}")
    return best_model, best_params, best_score

def evaluate_model(model, X_test, y_test):
    """Evaluate the model on the test set."""
    y_pred = model.predict(X_test)
    
    r2 = model.score(X_test, y_test)
    mae = np.mean(np.abs(y_test - y_pred))
    rmse = np.sqrt(np.mean((y_test - y_pred)**2))
    
    metrics = {
        'r2': float(r2),
        'mae': float(mae),
        'rmse': float(rmse),
        'n_test_samples': len(y_test)
    }
    
    logger.info(f"Test Metrics: R²={r2:.4f}, MAE={mae:.4f}, RMSE={rmse:.4f}")
    return metrics

def compute_permutation_importance(model, X_test, y_test, feature_names, n_repeats=10, random_state=42):
    """
    Compute permutation feature importance.
    Returns a dictionary mapping feature names to their importance scores.
    """
    result = permutation_importance(
        model, X_test, y_test,
        n_repeats=n_repeats,
        random_state=random_state,
        n_jobs=-1
    )
    
    importance_dict = {
        name: float(score) 
        for name, score in zip(feature_names, result.importances_mean)
    }
    
    # Sort by importance
    sorted_importance = dict(sorted(importance_dict.items(), key=lambda x: x[1], reverse=True))
    
    logger.info("Permutation importance computed.")
    return sorted_importance

def load_lme_artifact():
    """Load the Mixed Effects model artifact from T027."""
    if not LME_ARTIFACT_PATH.exists():
        logger.warning(f"LME artifact not found at {LME_ARTIFACT_PATH}. Skipping comparison.")
        return None
    
    with open(LME_ARTIFACT_PATH, 'r') as f:
        lme_data = json.load(f)
    
    return lme_data

def compare_with_lme(xgb_importance, lme_data):
    """
    Compare top 3 XGBoost features with top 3 LME coefficients.
    Handles cases where feature sets are disjoint or reduced.
    """
    comparison_result = {
        "xgb_top_3": [],
        "lme_top_3": [],
        "intersection": [],
        "warning": None
    }
    
    if not lme_data:
        comparison_result["warning"] = "No LME artifact found to compare against."
        return comparison_result
    
    # Extract top 3 XGBoost features
    xgb_top_3 = list(xgb_importance.keys())[:3]
    comparison_result["xgb_top_3"] = xgb_top_3
    
    # Extract LME fixed effects (standardized coefficients)
    # Assuming structure: {"fixed_effects": {"feature_name": {"coef": value, ...}, ...}}
    fixed_effects = lme_data.get("fixed_effects", {})
    if not fixed_effects:
        comparison_result["warning"] = "No fixed effects found in LME artifact."
        return comparison_result
    
    # Sort LME coefficients by absolute value
    lme_sorted = sorted(
        fixed_effects.items(),
        key=lambda x: abs(x[1].get("coef", 0)),
        reverse=True
    )
    lme_top_3 = [item[0] for item in lme_sorted[:3]]
    comparison_result["lme_top_3"] = lme_top_3
    
    # Find intersection
    intersection = list(set(xgb_top_3) & set(lme_top_3))
    comparison_result["intersection"] = intersection
    
    # Check for disjoint sets or reduced sets
    if not intersection:
        comparison_result["warning"] = "No common features between top 3 XGBoost and LME results."
    elif len(intersection) < 3:
        comparison_result["warning"] = f"Only {len(intersection)} common features found between top 3 lists."
    
    # Log comparison
    logger.info(f"XGBoost Top 3: {xgb_top_3}")
    logger.info(f"LME Top 3: {lme_top_3}")
    logger.info(f"Intersection: {intersection}")
    
    return comparison_result

def save_artifacts(metrics, importance, lme_comparison, model_params, model):
    """Save all artifacts to disk."""
    artifact_path = ARTIFACTS_DIR / "xgboost_model_artifact.json"
    model_path = ARTIFACTS_DIR / "xgboost_model.pkl"
    
    # Prepare artifact data
    artifact_data = {
        "metrics": metrics,
        "permutation_importance": importance,
        "lme_comparison": lme_comparison,
        "hyperparameters": model_params,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
    }
    
    # Save JSON artifact
    with open(artifact_path, 'w') as f:
        json.dump(artifact_data, f, indent=2)
    logger.info(f"Saved artifact to {artifact_path}")
    
    # Save model pickle
    with open(model_path, 'wb') as f:
        pickle.dump(model, f)
    logger.info(f"Saved model to {model_path}")
    
    return artifact_data

def main():
    """Main entry point for T033."""
    logger.info("Starting T033: Feature Importance and LME Comparison")
    
    try:
        # 1. Load data
        train_df, test_df = load_split_data()
        
        # 2. Prepare features
        X_train, y_train, train_features = prepare_features(train_df)
        X_test, y_test, test_features = prepare_features(test_df)
        
        # Ensure features match
        if not set(train_features) == set(test_features):
            raise ValueError("Feature mismatch between train and test sets.")
        
        # 3. Split into val set for tuning (if not already done in T030)
        # Assuming T030 produced train/test. We need a val set for tuning.
        # If T030 produced train/val/test, we would load them separately.
        # For this implementation, we assume T030 produced train/test and we split train further.
        from sklearn.model_selection import train_test_split
        X_train_sub, X_val, y_train_sub, y_val = train_test_split(
            X_train, y_train, test_size=0.2, random_state=42
        )
        
        # 4. Tune and Train
        model, best_params, best_val_score = tune_and_train(
            X_train_sub, y_train_sub, X_val, y_val
        )
        
        # 5. Evaluate
        metrics = evaluate_model(model, X_test, y_test)
        
        # 6. Compute Permutation Importance
        importance = compute_permutation_importance(
            model, X_test, y_test, test_features
        )
        
        # 7. Compare with LME
        lme_data = load_lme_artifact()
        lme_comparison = compare_with_lme(importance, lme_data)
        
        # 8. Save Artifacts
        final_artifact = save_artifacts(
            metrics, importance, lme_comparison, best_params, model
        )
        
        logger.info("T033 completed successfully.")
        return final_artifact
        
    except Exception as e:
        logger.error(f"T033 failed: {str(e)}", exc_info=True)
        raise

if __name__ == "__main__":
    main()