"""
Contract test for data extraction schema (T013).

This test validates that the cleaned study data adheres strictly to the
`contracts/cleaned_study.schema.yaml` definition. It ensures that the
data pipeline (T016-T023) produces output that matches the required
structure, types, and enumerations defined in the contract.

This test is part of User Story 1 (Data Collection and Cleaning Pipeline).
"""

import json
import os
import sys
import unittest
from pathlib import Path
from typing import Any, Dict, List

import yaml

# Project root setup for imports if running from CLI
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from code.utils.logging import get_logger

logger = get_logger(__name__)

# Path to the contract schema
SCHEMA_PATH = PROJECT_ROOT / "contracts" / "cleaned_study.schema.yaml"
# Path to the expected output CSV (generated by T021/T022)
OUTPUT_CSV_PATH = PROJECT_ROOT / "data" / "processed" / "cleaned_studies.csv"

# Expected fields and their types/enums based on T007a and T007b
EXPECTED_FIELDS = {
    "id": str,
    "title": str,
    "registry": str,  # Enum: ClinicalTrials.gov, OSF
    "age_range": str,
    "diagnosis": str,
    "outcomes": list,
    "intervention_components": list,
    "delivery_format": str,
    "follow_up": str,
    "abstract_text": (str, type(None)),  # Optional
    "assessor_blinding": str,  # Enum: single-blind, double-blind, unblinded, not-reported
}

VALID_REGISTRIES = {"ClinicalTrials.gov", "OSF"}
VALID_BLINDING = {"single-blind", "double-blind", "unblinded", "not-reported"}

class TestCleanedStudySchema(unittest.TestCase):
    """
    Contract test for the cleaned study data schema.
    """

    def setUp(self):
        """Load the schema and ensure test prerequisites exist."""
        self.schema = None
        self.data = None
        self.errors = []

        # Check if schema exists
        if not SCHEMA_PATH.exists():
            self.skipTest(f"Schema file not found at {SCHEMA_PATH}. "
                          "This task depends on T007a and T007b being completed.")

        # Load schema
        with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
            self.schema = yaml.safe_load(f)

        # Check if output CSV exists
        if not OUTPUT_CSV_PATH.exists():
            self.skipTest(f"Output CSV not found at {OUTPUT_CSV_PATH}. "
                          "This test requires the data pipeline (T016-T023) to have run.")

        # Load CSV data
        import pandas as pd
        self.data = pd.read_csv(OUTPUT_CSV_PATH)

    def test_schema_structure(self):
        """Verify the schema file has the expected top-level structure."""
        self.assertIsNotNone(self.schema, "Schema could not be loaded.")
        self.assertIn("type", self.schema, "Schema must have a 'type' field.")
        self.assertEqual(self.schema["type"], "object", "Schema type must be 'object'.")
        self.assertIn("properties", self.schema, "Schema must have 'properties'.")

    def test_required_fields_exist_in_schema(self):
        """Ensure all required fields defined in the task are in the schema."""
        schema_props = self.schema.get("properties", {})
        for field in EXPECTED_FIELDS.keys():
            self.assertIn(field, schema_props, f"Field '{field}' is missing from schema.")

    def test_csv_has_all_schema_fields(self):
        """Verify the CSV output contains all fields defined in the schema."""
        schema_props = self.schema.get("properties", {})
        csv_columns = set(self.data.columns)
        schema_fields = set(schema_props.keys())

        missing = schema_fields - csv_columns
        self.assertEqual(len(missing), 0, f"CSV is missing fields from schema: {missing}")

    def test_field_types_and_enums(self):
        """Validate data types and enumeration constraints for each field."""
        errors = []

        for row_idx, row in self.data.iterrows():
            study_id = row.get("id", f"Row {row_idx}")

            # 1. Check 'registry' enum
            if pd.notna(row["registry"]):
                if row["registry"] not in VALID_REGISTRIES:
                    errors.append(f"Row {study_id}: Invalid registry '{row['registry']}'. "
                                  f"Must be one of {VALID_REGISTRIES}.")

            # 2. Check 'assessor_blinding' enum
            if pd.notna(row["assessor_blinding"]):
                if row["assessor_blinding"] not in VALID_BLINDING:
                    errors.append(f"Row {study_id}: Invalid blinding status '{row['assessor_blinding']}'. "
                                  f"Must be one of {VALID_BLINDING}.")

            # 3. Check list fields (outcomes, intervention_components)
            # CSV loads lists as strings (e.g., "['a', 'b']") or JSON strings.
            # We assume the cleaner (T018) outputs them as JSON strings or comma-separated.
            # For strict contract testing, we expect them to be valid JSON or non-empty strings.
            for list_field in ["outcomes", "intervention_components"]:
                val = row[list_field]
                if pd.notna(val):
                    if not isinstance(val, str) and not isinstance(val, list):
                        errors.append(f"Row {study_id}: Field '{list_field}' must be a list or string representation.")

        if errors:
            self.fail("Schema validation errors found:\n" + "\n".join(errors))

    def test_no_null_required_fields(self):
        """Ensure required fields are not null/NaN."""
        required_fields = ["id", "title", "registry", "age_range", "diagnosis", "outcomes", "delivery_format"]
        null_errors = []

        for field in required_fields:
            null_count = self.data[field].isna().sum()
            if null_count > 0:
                null_errors.append(f"Field '{field}' has {null_count} null values.")

        if null_errors:
            self.fail("Null value errors found:\n" + "\n".join(null_errors))

if __name__ == "__main__":
    unittest.main()