import json
import os
from pathlib import Path
from typing import Dict, Any, List, Optional
import pandas as pd
from datetime import datetime

from code.config import get_path, ensure_dirs, get_project_root
from code.logging_utils import get_logger

logger = get_logger(__name__)

def load_regression_results() -> Optional[Dict[str, Any]]:
    """
    Load the regression results from the intermediates JSON file.
    Expects the file to be generated by T027 (analysis.py).
    """
    root = get_project_root()
    results_path = root / "data" / "intermediates" / "regression_results.json"
    
    if not results_path.exists():
        logger.error(f"Regression results file not found: {results_path}")
        return None
    
    try:
        with open(results_path, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse regression results JSON: {e}")
        return None

def load_vif_check() -> Optional[Dict[str, Any]]:
    """
    Load the VIF check results from the intermediates JSON file.
    """
    root = get_project_root()
    vif_path = root / "data" / "intermediates" / "vif_check.json"
    
    if not vif_path.exists():
        logger.warning(f"VIF check file not found: {vif_path}")
        return None
    
    try:
        with open(vif_path, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse VIF check JSON: {e}")
        return None

def determine_causality_warning() -> bool:
    """
    Determine if a causality warning should be included based on metadata.
    Checks if the study was randomized. If not, returns True (warning needed).
    """
    root = get_project_root()
    metadata_path = root / "data" / "raw" / "metadata.json"
    
    if not metadata_path.exists():
        # Default to caution if metadata is missing
        logger.warning("Metadata file not found; defaulting to causality warning.")
        return True
    
    try:
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
        
        randomized = metadata.get('randomized', False)
        return not randomized
    except (json.JSONDecodeError, KeyError) as e:
        logger.warning(f"Error reading metadata for causality check: {e}")
        return True

def generate_markdown_report(results: Dict[str, Any], vif_check: Optional[Dict[str, Any]], causality_warning: bool) -> str:
    """
    Generate a markdown report from the regression results and VIF check.
    """
    report_lines = [
        "# Regression Analysis Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Overview",
        "This report summarizes the multivariate regression analysis investigating the role of microglial morphology in age-related cognitive decline.",
        "The model predicts cognitive status using morphological features with interaction terms for Pathology Status and Brain Region.",
        ""
    ]

    if causality_warning:
        report_lines.extend([
            "## ⚠️ Causality Disclaimer",
            "Associational findings only; causality not inferred. This study is observational and does not establish a causal relationship between microglial morphology and cognitive decline.",
            ""
        ])

    report_lines.extend([
        "## Methodology",
        "- **Preprocessing:** Z-score normalization per cohort",
        "- **Feature Engineering:** Dynamic 'Early AD' classification",
        "- **Collinearity Check:** Variance Inflation Factor (VIF) analysis",
        "- **Model:** Multiple Linear Regression with Interaction Terms",
        ""
    ])

    if vif_check:
        report_lines.extend([
            "## Collinearity Analysis (VIF)",
            f"- **Maximum VIF:** {vif_check.get('max_vif', 'N/A')}",
            f"- **PCA Applied:** {'Yes' if vif_check.get('trigger_pca') else 'No'}",
            "",
            "### VIF Scores by Feature",
            "| Feature | VIF Score |",
            "| :--- | :--- |",
        ])
        vif_scores = vif_check.get('vif_scores', {})
        for feature, score in vif_scores.items():
            report_lines.append(f"| {feature} | {score:.4f} |")
        report_lines.append("")

    report_lines.extend([
        "## Regression Results",
        "",
        "### Model Coefficients",
        "| Feature | Coefficient | P-Value |",
        "| :--- | :--- | :--- |",
    ])

    coefficients = results.get('coefficients', {})
    p_values = results.get('p_values', {})
    feature_names = list(coefficients.keys())

    for feature in feature_names:
        coef = coefficients.get(feature, 0)
        p_val = p_values.get(feature, 1.0)
        sig_marker = "*" if p_val < 0.05 else ""
        report_lines.append(f"| {feature} | {coef:.4f} | {p_val:.4f} {sig_marker} |")
    
    report_lines.append("")

    interaction_terms = results.get('interaction_terms', {})
    if interaction_terms:
        report_lines.extend([
            "### Interaction Terms",
            "| Interaction | Coefficient | P-Value |",
            "| :--- | :--- | :--- |",
        ])
        for term, coef in interaction_terms.items():
            p_val = p_values.get(term, 1.0)
            sig_marker = "*" if p_val < 0.05 else ""
            report_lines.append(f"| {term} | {coef:.4f} | {p_val:.4f} {sig_marker} |")
        report_lines.append("")

    report_lines.extend([
        "### Model Performance",
        f"- **R²:** {results.get('r2', 'N/A'):.4f}",
        f"- **Adjusted R²:** {results.get('adj_r2', 'N/A'):.4f}",
        f"- **F-statistic:** {results.get('f_statistic', 'N/A'):.4f}",
        f"- **P-value (F-stat):** {results.get('f_p_value', 'N/A'):.6f}",
        "",
        "## Conclusions",
        "The analysis provides insights into the relationship between microglial morphological metrics and cognitive status.",
        "Significant interaction terms suggest that the effect of morphology on cognition varies by brain region and pathology status.",
        ""
    ])

    return "\n".join(report_lines)

def generate_json_report(results: Dict[str, Any], vif_check: Optional[Dict[str, Any]], causality_warning: bool) -> Dict[str, Any]:
    """
    Generate a structured JSON report containing all analysis details.
    """
    report_data = {
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "causality_warning": causality_warning,
            "warning_text": "Associational findings only; causality not inferred." if causality_warning else None
        },
        "methodology": {
            "normalization": "Z-score per cohort",
            "feature_engineering": "Dynamic Early AD classification",
            "collinearity_handling": "VIF check with optional PCA",
            "model_type": "Multiple Linear Regression with Interaction Terms"
        },
        "vif_analysis": vif_check,
        "regression_results": results
    }
    return report_data

def run_report_pipeline() -> bool:
    """
    Orchestrates the generation of regression reports.
    Loads results from intermediates, determines warnings, and writes final reports.
    """
    root = get_project_root()
    ensure_dirs(root / "reports")

    # Load data
    results = load_regression_results()
    if not results:
        logger.error("Cannot generate report: Regression results missing.")
        return False

    vif_check = load_vif_check()
    causality_warning = determine_causality_warning()

    # Generate JSON
    json_report = generate_json_report(results, vif_check, causality_warning)
    json_path = root / "reports" / "regression_results.json"
    with open(json_path, 'w') as f:
        json.dump(json_report, f, indent=2)
    logger.info(f"JSON report written to {json_path}")

    # Generate Markdown
    md_report = generate_markdown_report(results, vif_check, causality_warning)
    md_path = root / "reports" / "regression_results.md"
    with open(md_path, 'w') as f:
        f.write(md_report)
    logger.info(f"Markdown report written to {md_path}")

    return True