"""
MSE Validator for Quantization Error Analysis.

Computes Mean Squared Error (MSE) between quantized activations (generated by T019a)
and original float32 activations to validate the variance-sensitivity hypothesis.

This task depends on:
- T019a: Generates `data/processed/quantized_activations.json`
- T017: Generates `data/processed/correlation_results.json` (for variance context)
"""
import os
import json
import logging
import numpy as np
from pathlib import Path
from typing import Dict, Any, List, Tuple

# Import project config
from config import Config

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def load_quantized_activations(config: Config) -> Dict[str, Any]:
    """
    Load quantized activations generated by T019a.
    
    Args:
        config: Project configuration object
        
    Returns:
        Dictionary containing quantized activations and metadata
        
    Raises:
        FileNotFoundError: If the quantized activations file does not exist
        ValueError: If the file structure is invalid
    """
    input_path = config.DATA_PROCESSED_DIR / "quantized_activations.json"
    
    if not input_path.exists():
        raise FileNotFoundError(
            f"Quantized activations file not found: {input_path}. "
            f"Please ensure T019a (run_quantization_validation.py) has been executed successfully."
        )
    
    logger.info(f"Loading quantized activations from {input_path}")
    
    with open(input_path, 'r') as f:
        data = json.load(f)
    
    # Validate structure
    if 'activations' not in data:
        raise ValueError("Invalid structure in quantized_activations.json: missing 'activations' key")
    
    if 'metadata' not in data:
        raise ValueError("Invalid structure in quantized_activations.json: missing 'metadata' key")
        
    logger.info(f"Loaded {len(data['activations'])} quantized activation entries")
    return data

def load_original_activations(config: Config) -> Dict[str, Any]:
    """
    Load original float32 activations.
    
    Note: In a full implementation, this would load the original float32 activations
    that were used as the ground truth for quantization. For this implementation,
    we assume the original activations are stored alongside quantized ones or
    reconstructed from the correlation results if available.
    
    For the purpose of this task, we assume the quantized_activations.json contains
    both the quantized values and the reference float32 values (or a way to reconstruct them).
    """
    # Check if original activations are embedded in the quantized file
    input_path = config.DATA_PROCESSED_DIR / "quantized_activations.json"
    
    with open(input_path, 'r') as f:
        data = json.load(f)
    
    # If original activations are stored separately, we would load them here.
    # For now, we assume the data structure includes 'original_activations' or similar.
    if 'original_activations' in data:
        logger.info("Found embedded original activations in quantized file")
        return data
    
    # Alternative: Load from a separate file if it exists
    original_path = config.DATA_PROCESSED_DIR / "original_activations.json"
    if original_path.exists():
        logger.info(f"Loading original activations from {original_path}")
        with open(original_path, 'r') as f:
            return json.load(f)
    
    # Fallback: Try to reconstruct from correlation results if available
    # This is a less ideal scenario but allows the task to proceed if data is missing
    correlation_path = config.DATA_PROCESSED_DIR / "correlation_results.json"
    if correlation_path.exists():
        logger.warning("Original activations not found. Attempting to use correlation results for variance context.")
        with open(correlation_path, 'r') as f:
            corr_data = json.load(f)
            # We can't fully reconstruct original activations, but we can use variance data
            # for a partial validation. However, for MSE calculation, we need the actual values.
            # In a real scenario, this would be a failure condition.
            raise FileNotFoundError(
                "Original float32 activations not found. "
                "MSE calculation requires both quantized and original float32 values. "
                "Please ensure the quantization pipeline (T019a) stored original activations."
            )
    
    raise FileNotFoundError(
        "Could not locate original float32 activations. "
        "Ensure T019a saved both quantized and original activations."
    )

def compute_mse(quantized: np.ndarray, original: np.ndarray) -> float:
    """
    Compute Mean Squared Error between quantized and original activations.
    
    Args:
        quantized: Quantized activation values (W2A4)
        original: Original float32 activation values
        
    Returns:
        Mean Squared Error as a float
    """
    if quantized.shape != original.shape:
        raise ValueError(
            f"Shape mismatch: quantized {quantized.shape} vs original {original.shape}"
        )
    
    mse = np.mean((quantized - original) ** 2)
    return float(mse)

def compute_layerwise_mse(quantized_activations: List[Dict], original_activations: List[Dict]) -> Dict[str, float]:
    """
    Compute MSE for each layer separately.
    
    Args:
        quantized_activations: List of dicts with layer name and quantized values
        original_activations: List of dicts with layer name and original values
        
    Returns:
        Dictionary mapping layer names to MSE values
    """
    # Create lookup for original activations by layer
    original_lookup = {entry['layer']: entry['values'] for entry in original_activations}
    
    layer_mse = {}
    for entry in quantized_activations:
        layer_name = entry['layer']
        if layer_name not in original_lookup:
            logger.warning(f"Original activations missing for layer: {layer_name}")
            continue
            
        quantized_vals = np.array(entry['values'], dtype=np.float32)
        original_vals = np.array(original_lookup[layer_name], dtype=np.float32)
        
        mse = compute_mse(quantized_vals, original_vals)
        layer_mse[layer_name] = mse
        
    return layer_mse

def analyze_variance_sensitivity(mse_results: Dict[str, float], variance_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Analyze the relationship between activation variance and quantization error.
    
    This validates the variance-sensitivity hypothesis: layers with higher variance
    should exhibit different quantization error characteristics.
    
    Args:
        mse_results: Dictionary of layer MSE values
        variance_data: Variance data from correlation_results.json
        
    Returns:
        Analysis results including correlation between variance and MSE
    """
    # Extract layer variances from correlation results
    # Assuming variance_data contains 'variances' keyed by layer
    if 'variances' not in variance_data:
        logger.warning("Variance data not found in correlation results. Skipping sensitivity analysis.")
        return {"status": "skipped", "reason": "missing variance data"}
    
    variances = variance_data['variances']
    
    # Align layers between MSE and variance results
    common_layers = set(mse_results.keys()) & set(variances.keys())
    if not common_layers:
        return {"status": "failed", "reason": "no common layers between MSE and variance data"}
    
    mse_values = [mse_results[layer] for layer in common_layers]
    var_values = [variances[layer] for layer in common_layers]
    
    # Compute correlation between variance and MSE
    if len(common_layers) > 1:
        correlation = np.corrcoef(mse_values, var_values)[0, 1]
        logger.info(f"Correlation between activation variance and MSE: {correlation:.4f}")
    else:
        correlation = None
        logger.warning("Insufficient data points for correlation calculation")
    
    return {
        "status": "success",
        "common_layers": list(common_layers),
        "correlation": float(correlation) if correlation is not None else None,
        "layer_mse": mse_results,
        "layer_variance": {layer: variances[layer] for layer in common_layers}
    }

def run_mse_validation(config: Config) -> Dict[str, Any]:
    """
    Main validation routine: load data, compute MSE, analyze variance sensitivity.
    
    Args:
        config: Project configuration object
        
    Returns:
        Dictionary containing MSE results and analysis
    """
    logger.info("Starting MSE validation for quantization error")
    
    # Load data
    quantized_data = load_quantized_activations(config)
    original_data = load_original_activations(config)
    
    # Extract activations
    quantized_activations = quantized_data['activations']
    original_activations = original_data.get('original_activations', original_data['activations'])
    
    # Compute overall MSE
    all_quantized = []
    all_original = []
    for q_entry, o_entry in zip(quantized_activations, original_activations):
        if q_entry['layer'] == o_entry['layer']:
            all_quantized.extend(q_entry['values'])
            all_original.extend(o_entry['values'])
    
    all_quantized = np.array(all_quantized, dtype=np.float32)
    all_original = np.array(all_original, dtype=np.float32)
    
    overall_mse = compute_mse(all_quantized, all_original)
    logger.info(f"Overall MSE: {overall_mse:.6e}")
    
    # Compute layer-wise MSE
    layer_mse = compute_layerwise_mse(quantized_activations, original_activations)
    logger.info(f"Computed MSE for {len(layer_mse)} layers")
    
    # Load variance data for sensitivity analysis
    variance_path = config.DATA_PROCESSED_DIR / "correlation_results.json"
    variance_data = {}
    if variance_path.exists():
        with open(variance_path, 'r') as f:
            variance_data = json.load(f)
    else:
        logger.warning("Correlation results not found. Skipping variance sensitivity analysis.")
    
    # Analyze variance sensitivity
    sensitivity_analysis = analyze_variance_sensitivity(layer_mse, variance_data)
    
    # Prepare results
    results = {
        "overall_mse": overall_mse,
        "layer_mse": layer_mse,
        "metadata": {
            "num_layers": len(layer_mse),
            "quantization_config": quantized_data.get('metadata', {}),
            "sample_size": len(all_quantized),
            "timestamp": quantized_data.get('metadata', {}).get('timestamp', 'unknown')
        },
        "variance_sensitivity_analysis": sensitivity_analysis
    }
    
    return results

def save_results(results: Dict[str, Any], config: Config) -> Path:
    """
    Save MSE validation results to disk.
    
    Args:
        results: Dictionary of validation results
        config: Project configuration object
        
    Returns:
        Path to the saved file
    """
    output_path = config.DATA_PROCESSED_DIR / "mse_validation_results.json"
    
    logger.info(f"Saving MSE validation results to {output_path}")
    
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=2)
    
    return output_path

def main():
    """Entry point for MSE validation script."""
    config = Config()
    
    # Ensure output directory exists
    config.DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    
    try:
        # Run validation
        results = run_mse_validation(config)
        
        # Save results
        output_path = save_results(results, config)
        
        logger.info(f"MSE validation complete. Results saved to: {output_path}")
        logger.info(f"Overall MSE: {results['overall_mse']:.6e}")
        
        # Print summary
        print("\n=== MSE Validation Summary ===")
        print(f"Overall MSE: {results['overall_mse']:.6e}")
        print(f"Layers analyzed: {results['metadata']['num_layers']}")
        
        if results['variance_sensitivity_analysis']['status'] == 'success':
            corr = results['variance_sensitivity_analysis']['correlation']
            print(f"Variance-MSE correlation: {corr:.4f}")
        
        print("==============================\n")
        
    except FileNotFoundError as e:
        logger.error(f"Data file error: {e}")
        raise
    except Exception as e:
        logger.error(f"Validation failed: {e}")
        raise

if __name__ == "__main__":
    main()