"""
finalize_descriptors.py

Implements Task T017:
- Loads the processed descriptors from `data/processed/descriptors.csv`
- Loads uncertainty flags from `data/raw/uncertainty_flags.json`
- Merges the `T_d_uncertainty` column into the main dataset
- Saves the final merged dataset to `data/processed/descriptors.csv`
- Updates `state/...yaml` with the SHA-256 hash of the final artifact
"""

import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

# Import state management utilities from the project's utils package
from utils.state_manager import compute_sha256, load_state, save_state, update_artifact_state

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def load_descriptors() -> pd.DataFrame:
    """
    Load the intermediate descriptors from the processed directory.
    Expects the file to exist from previous steps (T014).
    """
    path = Path("data/processed/descriptors.csv")
    if not path.exists():
        raise FileNotFoundError(f"Intermediate descriptors file not found at {path}. "
                                "Ensure T014 (feature_engineering) has run successfully.")
    
    logger.info(f"Loading descriptors from {path}")
    df = pd.read_csv(path)
    
    required_cols = ['formula', 'T_d']
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in descriptors: {missing}")
        
    return df


def load_uncertainty_flags() -> Dict[str, float]:
    """
    Load the uncertainty flags generated by T013c.
    Returns a dictionary mapping 'formula' to 'T_d_uncertainty' (sigma).
    """
    path = Path("data/raw/uncertainty_flags.json")
    if not path.exists():
        raise FileNotFoundError(f"Uncertainty flags file not found at {path}. "
                                "Ensure T013c (uncertainty flagging) has run successfully.")
    
    logger.info(f"Loading uncertainty flags from {path}")
    with open(path, 'r') as f:
        data = json.load(f)
    
    # Convert list of dicts to a mapping for efficient lookup
    # Expected format: [{"formula": "CsPbI3", "T_d_uncertainty": 10.0}, ...]
    if not isinstance(data, list):
        raise ValueError("Uncertainty flags file must contain a list of entries.")
        
    uncertainty_map = {}
    for entry in data:
        formula = entry.get('formula')
        uncertainty = entry.get('T_d_uncertainty')
        if formula and uncertainty is not None:
            uncertainty_map[formula] = float(uncertainty)
            
    return uncertainty_map


def merge_uncertainty(df: pd.DataFrame, uncertainty_map: Dict[str, float]) -> pd.DataFrame:
    """
    Merge the uncertainty values into the main dataframe.
    """
    logger.info(f"Merging uncertainty data for {len(uncertainty_map)} entries")
    
    # Create a Series from the map aligned with the dataframe index
    # Using map is efficient and handles missing keys gracefully (NaN)
    df['T_d_uncertainty'] = df['formula'].map(uncertainty_map)
    
    # Check for any missing uncertainties (should be rare if T013c covered T012 output)
    missing_count = df['T_d_uncertainty'].isna().sum()
    if missing_count > 0:
        logger.warning(f"Found {missing_count} entries in descriptors without uncertainty flags. "
                       "These will be NaN. Ensure T013c covered all entries from T012.")
    else:
        logger.info("Successfully merged uncertainty for all entries.")
        
    return df


def save_descriptors(df: pd.DataFrame, output_path: Path) -> None:
    """
    Save the final processed dataset to disk.
    """
    logger.info(f"Saving final descriptors to {output_path}")
    df.to_csv(output_path, index=False)
    logger.info("Save complete.")


def update_state(output_path: Path) -> str:
    """
    Compute the SHA-256 hash of the final artifact and update the state file.
    Returns the hash.
    """
    logger.info(f"Computing SHA-256 for {output_path}")
    file_hash = compute_sha256(output_path)
    
    state_path = Path("state/artifacts.yaml")
    state_path.parent.mkdir(parents=True, exist_ok=True)
    
    state = load_state(state_path)
    update_artifact_state(state, str(output_path), file_hash)
    save_state(state, state_path)
    
    logger.info(f"State updated. Hash: {file_hash}")
    return file_hash


def main() -> None:
    """
    Main entry point for T017.
    """
    try:
        # 1. Load intermediate data
        df = load_descriptors()
        
        # 2. Load uncertainty flags
        uncertainty_map = load_uncertainty_flags()
        
        # 3. Merge uncertainty
        df_final = merge_uncertainty(df, uncertainty_map)
        
        # 4. Save final dataset
        output_path = Path("data/processed/descriptors.csv")
        save_descriptors(df_final, output_path)
        
        # 5. Update state with hash
        update_state(output_path)
        
        logger.info("T017 completed successfully.")
        
    except Exception as e:
        logger.error(f"Task T017 failed: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()