"""
propagate_uncertainty.py

Implements T013b: Extract temperature_precision from T013 output, calculate sigma
using T043 (combined uncertainty), and write T_d_uncertainty column to
data/processed/descriptors.csv.

Dependencies:
  - T013: data/raw/metadata.json (contains temperature_precision per formula)
  - T043: code/utils/uncertainty_propagator.py (calculate_combined_uncertainty)
  - T014 (feature_engineering): data/processed/descriptors.csv (input to be updated)
"""

import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

# Import the real uncertainty propagation logic from T043
from utils.uncertainty_propagator import calculate_combined_uncertainty

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

def load_json(path: Path) -> Dict[str, Any]:
    """Load a JSON file and return its contents."""
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def load_descriptors(path: Path) -> pd.DataFrame:
    """Load the descriptors CSV generated by T014."""
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")
    return pd.read_csv(path)

def map_uncertainty_to_descriptors(
    descriptors_df: pd.DataFrame,
    metadata: Dict[str, Any]
) -> pd.DataFrame:
    """
    Map temperature_precision from metadata to each row in descriptors_df,
    then calculate sigma (combined uncertainty) for each row.

    Steps:
      1. For each row, look up the formula in metadata to get temperature_precision.
      2. If missing, default to 10.0°C (as per T042) and log a warning.
      3. Use calculate_combined_uncertainty (from T043) to compute sigma.
         - calculate_combined_uncertainty expects: temperature_precision, experimental_error (optional).
         - We assume experimental_error is 0 unless specified in metadata.
      4. Assign the resulting sigma to a new column: T_d_uncertainty.
    """
    # Create a copy to avoid modifying the original
    df = descriptors_df.copy()

    # Ensure we have a formula column
    if "formula" not in df.columns:
        raise ValueError("Input descriptors DataFrame must contain a 'formula' column.")

    # Map temperature_precision from metadata
    # metadata structure: { "formula": { "temperature_precision": float, ... } }
    temp_precision_map = {}
    for formula, entry in metadata.items():
        if isinstance(entry, dict):
            # T042 logic: if missing, default to 10.0
            precision = entry.get("temperature_precision")
            if precision is None:
                precision = 10.0
                logger.warning(
                    f"temperature_precision missing for formula {formula}; "
                    f"defaulting to 10.0°C as per T042."
                )
            temp_precision_map[formula] = precision
        else:
            # Fallback for malformed entries
            temp_precision_map[formula] = 10.0
            logger.warning(
                f"Malformed metadata entry for formula {formula}; "
                f"defaulting to 10.0°C."
            )

    # Apply mapping to DataFrame
    df["temp_precision"] = df["formula"].map(temp_precision_map)

    # Calculate combined uncertainty (sigma) for each row
    # T043: calculate_combined_uncertainty(temp_precision, experimental_error=0.0)
    # We assume no additional experimental error unless explicitly provided (not in current spec)
    def compute_sigma(row: pd.Series) -> float:
        temp_prec = row["temp_precision"]
        # Assume experimental_error is 0.0 if not present
        return calculate_combined_uncertainty(temp_precision=temp_prec, experimental_error=0.0)

    df["T_d_uncertainty"] = df.apply(compute_sigma, axis=1)

    # Drop the temporary temp_precision column
    df.drop(columns=["temp_precision"], inplace=True)

    logger.info(
        f"Successfully mapped uncertainty to {len(df)} descriptors. "
        f"Sample T_d_uncertainty values: {df['T_d_uncertainty'].head().tolist()}"
    )

    return df

def save_descriptors(df: pd.DataFrame, output_path: Path) -> None:
    """Save the updated descriptors DataFrame to CSV."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    logger.info(f"Saved updated descriptors to {output_path}")

def main() -> int:
    """
    Main entry point for T013b.

    Reads:
      - data/raw/metadata.json (from T013)
      - data/processed/descriptors.csv (from T014)

    Writes:
      - data/processed/descriptors.csv (updated with T_d_uncertainty column)
    """
    # Define paths relative to project root
    project_root = Path(__file__).resolve().parent.parent
    metadata_path = project_root / "data" / "raw" / "metadata.json"
    descriptors_input_path = project_root / "data" / "processed" / "descriptors.csv"
    descriptors_output_path = project_root / "data" / "processed" / "descriptors.csv"

    # Load inputs
    logger.info(f"Loading metadata from {metadata_path}")
    metadata = load_json(metadata_path)

    logger.info(f"Loading descriptors from {descriptors_input_path}")
    descriptors_df = load_descriptors(descriptors_input_path)

    # Map uncertainty and calculate sigma
    logger.info("Mapping temperature_precision and calculating T_d_uncertainty...")
    updated_df = map_uncertainty_to_descriptors(descriptors_df, metadata)

    # Save updated descriptors
    logger.info(f"Saving updated descriptors to {descriptors_output_path}")
    save_descriptors(updated_df, descriptors_output_path)

    logger.info("T013b completed successfully.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
