"""
Integration test for the full modeling and validation pipeline (T030).

This test verifies the end-to-end flow of:
1. Loading the fixed gene panel from meta-analysis results.
2. Training tumor-specific models on the training set.
3. Performing LOO (Leave-One-Out) validation logic.
4. Simulating external validation logic (using mock external data).

It uses a small subset of `data/processed/` generated by previous tasks (T020, T028).
"""
import os
import sys
import json
import tempfile
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
import pytest
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, classification_report
from scipy.stats import rankdata

# Add project root to path to allow imports from src
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.config import get_project_root, ensure_directories
from src.modeling import train_model, run_nested_cv, load_gene_panel
from src.validation import run_loo_validation, validate_external_dataset, check_loo_feasibility
from src.utils import setup_logging

# Configure logging for the test
logger = logging.getLogger(__name__)
setup_logging(level=logging.INFO)

class TestDataModelingIntegration:
    """
    Integration tests for the modeling and validation pipeline.
    """

    @pytest.fixture
    def temp_project_dirs(self, tmp_path: Path):
        """
        Creates a temporary directory structure mimicking the project layout
        with small, synthetic but REAL-structure data files for testing.
        
        Note: While the data values are generated here for the sake of the 
        integration test running in isolation (without waiting for T012-T028 to 
        download real TCGA/GEO data), the code paths exercised are the real 
        production logic. The data structure (columns, types) matches the 
        expected schema from T020 and T028.
        """
        root = tmp_path / "test_project"
        data_processed = root / "data" / "processed"
        results_meta = root / "results" / "meta_analysis"
        results_loo = root / "results" / "loo_iterations"
        data_raw = root / "data" / "raw" # For external validation mock
        
        (data_processed).mkdir(parents=True, exist_ok=True)
        (results_meta).mkdir(parents=True, exist_ok=True)
        (results_loo).mkdir(parents=True, exist_ok=True)
        (data_raw).mkdir(parents=True, exist_ok=True)

        # 1. Create Mock Gene Panel (Output of T028)
        # Simulating a panel of 10 genes selected from intersection/union
        gene_panel = {
            "selected": ["GENE_A", "GENE_B", "GENE_C", "GENE_D", "GENE_E", 
                         "GENE_F", "GENE_G", "GENE_H", "GENE_I", "GENE_J"],
            "method": "intersection",
            "fallback_reason": None,
            "metadata": {
                "source": "LOO-Blind DE + REML",
                "total_tumor_types": 3
            }
        }
        with open(results_meta / "gene_panel.json", "w") as f:
            json.dump(gene_panel, f, indent=2)

        # 2. Create Mock Training and Discovery Sets for 3 Tumor Types
        # Simulating T020 output: *_training_set.csv and *_discovery_set.csv
        tumor_types = ["BRCA", "LUAD", "COAD"]
        samples_per_type = 50 # Small subset for integration test speed
        
        for t_type in tumor_types:
            # Create a realistic dataframe structure
            # Columns: sample_id, response_label (0/1), and expression for the 10 panel genes
            np.random.seed(42) # Deterministic for testing
            n_samples = samples_per_type
            
            # Generate expression data (log2-normalized counts)
            # Correlate expression of GENE_A and GENE_B with response to ensure model can learn
            response = np.random.binomial(1, 0.4, n_samples) # 40% responders
            
            data = {
                "sample_id": [f"{t_type}_{i}" for i in range(n_samples)],
                "response_label": response,
                "GENE_A": np.random.normal(5, 1, n_samples) + (response * 1.5),
                "GENE_B": np.random.normal(6, 1, n_samples) + (response * 1.2),
                "GENE_C": np.random.normal(4, 1, n_samples), # Noise
                "GENE_D": np.random.normal(7, 1, n_samples), # Noise
                "GENE_E": np.random.normal(3, 1, n_samples),
                "GENE_F": np.random.normal(8, 1, n_samples),
                "GENE_G": np.random.normal(2, 1, n_samples),
                "GENE_H": np.random.normal(9, 1, n_samples),
                "GENE_I": np.random.normal(1, 1, n_samples),
                "GENE_J": np.random.normal(10, 1, n_samples),
            }
            df = pd.DataFrame(data)
            
            # Save Discovery Set (for LOO logic verification)
            df.to_csv(data_processed / f"{t_type}_discovery_set.csv", index=False)
            # Save Training Set (for Model Training)
            df.to_csv(data_processed / f"{t_type}_training_set.csv", index=False)

        # 3. Create Mock External GEO Dataset for T034
        # Simulating an external validation file
        external_data = {
            "sample_id": ["EXT_1", "EXT_2", "EXT_3", "EXT_4", "EXT_5"],
            "response_label": [1, 0, 1, 0, 1],
            "GENE_A": [6.5, 4.0, 7.0, 3.5, 7.5],
            "GENE_B": [7.2, 5.0, 8.0, 4.5, 8.5],
            "GENE_C": [4.1, 4.0, 4.2, 3.9, 4.3],
            "GENE_D": [7.0, 7.1, 6.9, 7.2, 6.8],
            "GENE_E": [3.0, 3.1, 2.9, 3.2, 2.8],
            "GENE_F": [8.0, 8.1, 7.9, 8.2, 7.8],
            "GENE_G": [2.0, 2.1, 1.9, 2.2, 1.8],
            "GENE_H": [9.0, 9.1, 8.9, 9.2, 8.8],
            "GENE_I": [1.0, 1.1, 0.9, 1.2, 0.8],
            "GENE_J": [10.0, 10.1, 9.9, 10.2, 9.8],
        }
        ext_df = pd.DataFrame(external_data)
        ext_df.to_csv(data_raw / "GSE12345_BRCA_external.csv", index=False)

        # 4. Create summary.md with batch correction method (required by T034)
        summary_path = root / "results" / "summary.md"
        with open(summary_path, "w") as f:
            f.write("# Summary\n")
            f.write("batch_correction_method: ComBat\n")
            f.write("override_note: ComBat used instead of ComBat-seq per Plan Phase 1\n")

        return {
            "root": root,
            "data_processed": data_processed,
            "results_meta": results_meta,
            "results_loo": results_loo,
            "data_raw": data_raw
        }

    def test_end_to_end_pipeline(self, temp_project_dirs: Dict[str, Any]):
        """
        Verifies the full pipeline:
        1. Loads gene panel.
        2. Trains models on training sets.
        3. Runs LOO validation (checks feasibility and execution).
        4. Runs external validation logic.
        """
        root = temp_project_dirs["root"]
        data_processed = temp_project_dirs["data_processed"]
        results_meta = temp_project_dirs["results_meta"]
        results_loo = temp_project_dirs["results_loo"]
        data_raw = temp_project_dirs["data_raw"]

        # Change to project root to simulate running from CLI
        original_cwd = os.getcwd()
        os.chdir(str(root))

        try:
            # --- Step 1: Load Gene Panel ---
            logger.info("Step 1: Loading gene panel...")
            panel = load_gene_panel(str(results_meta / "gene_panel.json"))
            assert panel is not None
            assert "selected" in panel
            assert len(panel["selected"]) > 0
            logger.info(f"Loaded panel with {len(panel['selected'])} genes.")

            # --- Step 2: Train Tumor-Specific Models ---
            logger.info("Step 2: Training tumor-specific models...")
            tumor_types = ["BRCA", "LUAD", "COAD"]
            trained_models = {}
            
            for t_type in tumor_types:
                training_file = data_processed / f"{t_type}_training_set.csv"
                assert training_file.exists(), f"Training file missing: {training_file}"
                
                model, metrics = train_model(
                    training_file=str(training_file),
                    gene_panel=panel["selected"],
                    tumor_type=t_type
                )
                assert model is not None
                assert "auc" in metrics
                trained_models[t_type] = model
                logger.info(f"Trained model for {t_type}, AUC: {metrics['auc']:.3f}")

            # --- Step 3: LOO Validation ---
            logger.info("Step 3: Running LOO Validation...")
            # Check feasibility first (T033)
            # This should pass since we have 3 types
            try:
                check_loo_feasibility(str(data_processed))
                logger.info("LOO Feasibility check passed.")
            except RuntimeError as e:
                pytest.fail(f"LOO Feasibility check failed unexpectedly: {e}")

            # Run the LOO loop
            loo_results = run_loo_validation(
                data_dir=str(data_processed),
                gene_panel=panel["selected"],
                output_dir=str(results_loo)
            )
            
            assert loo_results is not None
            assert len(loo_results) == 3 # 3 tumor types
            for t_type, res in loo_results.items():
                assert "auc" in res
                assert "model_path" in res
                # Verify the output file was actually written
                expected_file = Path(res["model_path"])
                assert expected_file.exists(), f"LOO result file not written: {expected_file}"
                logger.info(f"LOO for {t_type}: AUC={res['auc']:.3f}")

            # --- Step 4: External Validation ---
            logger.info("Step 4: Running External Validation...")
            # We need a mock trained model for BRCA to test external validation
            if "BRCA" in trained_models:
                external_file = data_raw / "GSE12345_BRCA_external.csv"
                assert external_file.exists()
                
                ext_metrics = validate_external_dataset(
                    model=trained_models["BRCA"],
                    external_file=str(external_file),
                    gene_panel=panel["selected"],
                    tumor_type="BRCA"
                )
                
                assert ext_metrics is not None
                assert "auc" in ext_metrics
                assert "pr_auc" in ext_metrics
                logger.info(f"External Validation AUC: {ext_metrics['auc']:.3f}")

            # --- Assertions ---
            # Verify that all LOO files were created in the correct directory
            loo_files = list(results_loo.glob("loo_iteration_*_metrics.json"))
            assert len(loo_files) == 3, f"Expected 3 LOO result files, found {len(loo_files)}"

            logger.info("Integration test PASSED: Full pipeline executed successfully.")

        finally:
            os.chdir(original_cwd)

    def test_loo_halt_on_insufficient_types(self, temp_project_dirs: Dict[str, Any]):
        """
        Verifies that LOO validation halts if < 3 tumor types are present.
        """
        # Modify the temp directory to only have 2 types
        root = temp_project_dirs["root"]
        data_processed = temp_project_dirs["data_processed"]
        
        # Remove one type's files
        (data_processed / "COAD_discovery_set.csv").unlink()
        (data_processed / "COAD_training_set.csv").unlink()
        
        original_cwd = os.getcwd()
        os.chdir(str(root))

        try:
            with pytest.raises(RuntimeError) as exc_info:
                check_loo_feasibility(str(data_processed))
            
            assert "insufficient_loo_types" in str(exc_info.value).lower()
            logger.info("Correctly halted on insufficient LOO types.")
        finally:
            os.chdir(original_cwd)

    def test_model_schema_compliance(self, temp_project_dirs: Dict[str, Any]):
        """
        Verifies that the output metrics conform to the expected schema (T029).
        """
        root = temp_project_dirs["root"]
        data_processed = temp_project_dirs["data_processed"]
        results_meta = temp_project_dirs["results_meta"]
        results_loo = temp_project_dirs["results_loo"]
        
        original_cwd = os.getcwd()
        os.chdir(str(root))

        try:
            panel = load_gene_panel(str(results_meta / "gene_panel.json"))
            
            # Train a single model to check metrics structure
            model, metrics = train_model(
                training_file=str(data_processed / "BRCA_training_set.csv"),
                gene_panel=panel["selected"],
                tumor_type="BRCA"
            )
            
            # Check required fields based on model_output.schema.yaml (implied)
            required_fields = ["tumor_type", "model_type", "auc", "pr_auc", "accuracy", "genes_used"]
            for field in required_fields:
                assert field in metrics, f"Missing required field in metrics: {field}"
            
            assert metrics["tumor_type"] == "BRCA"
            assert metrics["model_type"] == "ElasticNet"
            assert isinstance(metrics["auc"], float)
            assert len(metrics["genes_used"]) == len(panel["selected"])
            
            logger.info("Model output schema compliance verified.")
        finally:
            os.chdir(original_cwd)
