import os
import sys
import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

# Local imports from project structure
from config import get_project_root, get_output_path, get_data_path
from logging_config import get_logger

# Ensure we can import from the code directory if run as script
PROJECT_ROOT = get_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

def load_metrics() -> Dict[str, Any]:
    """
    Load the metrics.json file generated by the evaluation stage.
    This file contains R², MAE, Pearson R, p-value, and SC-003 verification results.
    """
    metrics_path = get_output_path("metrics.json")
    if not os.path.exists(metrics_path):
        raise FileNotFoundError(f"Metrics file not found at {metrics_path}. "
                                "Ensure T029 (generate metrics) and T037 (SC-003 verification) have run.")
    
    with open(metrics_path, 'r') as f:
        return json.load(f)

def load_top_descriptors() -> List[str]:
    """
    Load the top 5 descriptors ranked by mean absolute SHAP impact.
    These are typically derived from T034 and stored in a JSON file or extracted from metrics.
    For this implementation, we assume they are stored in 'outputs/top_descriptors.json' 
    or embedded in 'metrics.json' under a specific key. 
    If not present in metrics, we look for a dedicated file.
    """
    # Check if top descriptors are in metrics
    metrics = load_metrics()
    if 'top_descriptors' in metrics:
        return metrics['top_descriptors']
    
    # Fallback: try loading from a dedicated file (if T034 saved it separately)
    top_desc_path = get_output_path("top_descriptors.json")
    if os.path.exists(top_desc_path):
        with open(top_desc_path, 'r') as f:
            data = json.load(f)
            # Expecting a list of strings or a dict with 'descriptors' key
            if isinstance(data, list):
                return data
            elif isinstance(data, dict) and 'descriptors' in data:
                return data['descriptors']
    
    # If still not found, raise an error as this is a critical dependency
    raise FileNotFoundError(
        "Top descriptors not found in metrics.json or outputs/top_descriptors.json. "
        "Ensure T034 (rank descriptors) has completed successfully."
    )

def normalize_descriptor_name(descriptor: str) -> str:
    """
    Normalize descriptor names for comparison with Nørskov reference.
    Handles common variations (e.g., 'adsorption_energy' -> 'reaction_energy').
    """
    # Map known variations to standard Nørskov terminology
    mapping = {
        'adsorption_energy': 'reaction_energy',
        'adsorption energy': 'reaction energy',
        'd_band_center': 'd-band center',
        'd band center': 'd-band center',
        'activation_barrier': 'activation barrier',
        'activation energy': 'activation barrier',
        'surface_facet': 'surface facet',
        'composition_family': 'composition family'
    }
    return mapping.get(descriptor.lower(), descriptor.lower().replace('_', ' '))

def compare_with_norskov(top_descriptors: List[str]) -> List[Dict[str, Any]]:
    """
    Compare the top 5 descriptors against the Nørskov et al. reference list.
    Reference list from Nørskov (approximate): 
    ['d-band center', 'reaction energy', 'activation barrier', 'surface coverage', 'coordination number']
    
    Returns a list of dicts with: descriptor, norskov_match (bool or N/A), novelty_flag.
    """
    # Nørskov reference descriptors (normalized)
    norskov_ref = [
        'd-band center',
        'reaction energy',
        'activation barrier',
        'surface coverage',
        'coordination number'
    ]
    
    comparison_results = []
    
    for desc in top_descriptors:
        normalized = normalize_descriptor_name(desc)
        # Check for match (case-insensitive, after normalization)
        match = normalized in [n.lower() for n in norskov_ref]
        
        # Determine novelty flag: True if NOT in Nørskov reference
        novelty = not match
        
        comparison_results.append({
            'descriptor': desc,
            'normalized_name': normalized,
            'norskov_match': match,
            'novelty_flag': novelty
        })
    
    return comparison_results

def generate_comparison_table(comparison_results: List[Dict[str, Any]]) -> str:
    """
    Generate a Markdown table from the comparison results.
    """
    lines = []
    lines.append("| Descriptor | Nørskov Match | Novelty Flag |")
    lines.append("|------------|---------------|--------------|")
    
    for row in comparison_results:
        match_str = "Yes" if row['norskov_match'] else ("No" if row['norskov_match'] is False else "N/A")
        novelty_str = "Yes" if row['novelty_flag'] else "No"
        lines.append(f"| {row['descriptor']} | {match_str} | {novelty_str} |")
    
    return "\n".join(lines)

def generate_final_report(metrics: Dict[str, Any], comparison_table: str) -> str:
    """
    Generate the full final report in Markdown format.
    Includes:
    - Performance metrics (Pearson R, MAE, p-value)
    - Top 5 descriptors list
    - SC-003 verification result (quantitative)
    - Nørskov comparison table
    """
    report_lines = []
    
    # Header
    report_lines.append("# Final Report: Predicting Catalytic Activity")
    report_lines.append("")
    report_lines.append("## Executive Summary")
    report_lines.append("")
    
    # Performance Metrics
    report_lines.append("### Model Performance Metrics")
    report_lines.append("")
    report_lines.append("| Metric | Value |")
    report_lines.append("|--------|-------|")
    
    # Extract metrics safely
    pearson_r = metrics.get('pearson_r', 'N/A')
    mae = metrics.get('mae', 'N/A')
    p_value = metrics.get('p_value', 'N/A')
    r2_full = metrics.get('r2_full_model', metrics.get('r2', 'N/A'))
    
    report_lines.append(f"| Pearson R | {pearson_r} |")
    report_lines.append(f"| MAE | {mae} |")
    report_lines.append(f"| p-value | {p_value} |")
    report_lines.append(f"| R² (Full Model) | {r2_full} |")
    report_lines.append("")
    
    # Top 5 Descriptors
    report_lines.append("### Top 5 Descriptors (by SHAP Impact)")
    report_lines.append("")
    top_descs = metrics.get('top_descriptors', [])
    if top_descs:
        for i, desc in enumerate(top_descs[:5], 1):
            report_lines.append(f"{i}. {desc}")
    else:
        report_lines.append("*No descriptors available*")
    report_lines.append("")
    
    # SC-003 Verification
    report_lines.append("### SC-003 Verification: Reduced Model Performance")
    report_lines.append("")
    sc003_status = metrics.get('SC-003_status', 'Unknown')
    reduced_r2 = metrics.get('reduced_r2', 'N/A')
    full_r2 = metrics.get('full_r2', r2_full)
    ratio = metrics.get('reduced_full_ratio', 'N/A')
    
    report_lines.append(f"- **Status**: {sc003_status}")
    report_lines.append(f"- **Reduced Model R²**: {reduced_r2}")
    report_lines.append(f"- **Full Model R²**: {full_r2}")
    report_lines.append(f"- **Ratio (Reduced/Full)**: {ratio}")
    report_lines.append("")
    report_lines.append(f"*Verification passed if ratio >= 0.50.*")
    report_lines.append("")
    
    # Nørskov Comparison
    report_lines.append("### Comparison with Nørskov et al. (FR-007)")
    report_lines.append("")
    report_lines.append(comparison_table)
    report_lines.append("")
    report_lines.append("**Note**: `adsorption_energy` is mapped to `reaction_energy` in the comparison.")
    report_lines.append("")
    
    return "\n".join(report_lines)

def save_report(report_content: str, output_filename: str = "final_report.md") -> Path:
    """
    Save the generated report to the outputs directory.
    """
    output_path = get_output_path(output_filename)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report_content)
    logging.info(f"Final report saved to {output_path}")
    return output_path

def run_report_generation():
    """
    Main function to orchestrate the report generation.
    """
    logger = get_logger(__name__)
    logger.info("Starting final report generation (T040)...")
    
    try:
        # 1. Load metrics (from T029, T037)
        logger.info("Loading metrics...")
        metrics = load_metrics()
        
        # 2. Load top descriptors (from T034)
        logger.info("Loading top descriptors...")
        top_descriptors = load_top_descriptors()
        
        # 3. Compare with Nørskov (FR-007)
        logger.info("Comparing with Nørskov reference...")
        comparison_results = compare_with_norskov(top_descriptors)
        comparison_table = generate_comparison_table(comparison_results)
        
        # 4. Generate full report
        logger.info("Generating final report content...")
        report_content = generate_final_report(metrics, comparison_table)
        
        # 5. Save report
        logger.info("Saving report...")
        report_path = save_report(report_content)
        
        logger.info(f"Report generation complete. Output: {report_path}")
        return report_path
        
    except FileNotFoundError as e:
        logger.error(f"Missing required data: {e}")
        raise
    except Exception as e:
        logger.error(f"Error during report generation: {e}")
        raise

def main():
    """
    Entry point for running the report generation script.
    """
    setup_logger = logging.getLogger(__name__)
    setup_logger.setLevel(logging.INFO)
    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    setup_logger.addHandler(handler)
    
    run_report_generation()

if __name__ == "__main__":
    main()